define([], function () {
  return {
    // ── Property pane ──
    PropertyPane_HeaderDescription: 'إعدادات مخطط جانت الذكي',
    PropertyPane_GeneralGroupName: 'عام',
    PropertyPane_TitleFieldLabel: 'عنوان الويب بارت',
    WebPart_DefaultTitle: 'مخطط جانت الذكي',

    // ── Toolbar ──
    Toolbar_ViewDashboard: 'لوحة المعلومات',
    Toolbar_ViewList: 'قائمة',
    Toolbar_ViewGantt: 'جانت',
    Toolbar_ViewKanban: 'كانبان',
    Toolbar_ZoomDay: 'يوم',
    Toolbar_ZoomWeek: 'أسبوع',
    Toolbar_ZoomMonth: 'شهر',
    Toolbar_ZoomQuarter: 'ربع سنة',
    Toolbar_SelectProjectAriaLabel: 'اختر المشروع',
    Toolbar_PortfolioLabel: 'المحفظة',
    Toolbar_SelectAProject: 'اختر مشروعًا',
    Toolbar_AllProjectsSubtext: 'جميع المشاريع',
    Toolbar_NoProjectsYet: 'لا توجد مشاريع بعد',
    Toolbar_ArchivedBadge: 'مؤرشف',
    Toolbar_ShowArchivedProjects: 'إظهار المشاريع المؤرشفة',
    Toolbar_NewProject: '+ مشروع جديد',
    Toolbar_ImportFileAsNewProject: '📥 استيراد ملف كمشروع جديد…',
    Toolbar_AddTask: '+ إضافة مهمة',
    Toolbar_EditProject: 'تعديل المشروع',
    Toolbar_OptionsButton: '⚙ خيارات',
    Toolbar_MoreOptionsTitle: 'المزيد من الخيارات',
    Toolbar_ExportToExcel: '📊 تصدير إلى Excel',
    Toolbar_ExportToPowerPoint: '📑 تصدير إلى PowerPoint',
    Toolbar_ScrollToTodayTitle: 'الانتقال إلى اليوم',
    Toolbar_TodayButton: '◉ اليوم',
    Toolbar_ImportTasks: '📥 استيراد المهام…',
    Toolbar_ExportAsImage: '🖼 تصدير كصورة (PNG)',
    Toolbar_UnarchiveProject: '📂 إلغاء أرشفة المشروع',
    Toolbar_ArchiveProject: '🗄️ أرشفة المشروع',
    Toolbar_SendToRecycleBin: '🗑️ نقل إلى سلة المحذوفات',

    // ── Filter bar ──
    FilterBar_ClearOption: 'مسح',
    FilterBar_DueAny: 'أي تاريخ استحقاق',
    FilterBar_DueOverdue: 'متأخر',
    FilterBar_DueToday: 'مستحق اليوم',
    FilterBar_DueWeek: 'مستحق خلال 7 أيام',
    FilterBar_SearchPlaceholder: 'البحث عن المهام…',
    FilterBar_SearchAriaLabel: 'البحث عن المهام',
    FilterBar_StatusChipLabel: 'الحالة',
    FilterBar_PriorityChipLabel: 'الأولوية',
    FilterBar_AssigneeChipLabel: 'المسؤول',
    FilterBar_PhaseChipLabel: 'المرحلة',
    FilterBar_DueDateAriaLabel: 'التصفية حسب تاريخ الاستحقاق',
    FilterBar_MatchCount: '{matchCount} من {totalCount}',
    FilterBar_ClearFilters: '✕ مسح عوامل التصفية',
    FilterBar_ChipLabelWithCount: '{label} ({count}) ▾',
    FilterBar_ChipLabelNoCount: '{label} ▾',

    // ── Gantt view ──
    Gantt_TaskColumnHeader: 'المهمة',
    Gantt_DurationColumnHeader: 'المدة',
    Gantt_AddTaskButton: '+ إضافة مهمة',
    Gantt_EmptyTitle: 'لا توجد مهام بعد',
    Gantt_EmptySubtitle: 'أضف مهام لرؤيتها في مخطط جانت.',
    Gantt_AddFirstTask: '+ إضافة أول مهمة',
    Gantt_ImportTasksButton: '📥 استيراد المهام',
    Gantt_EditTitle: 'تعديل',
    Gantt_DeleteTitle: 'حذف',
    Gantt_EditTaskAriaLabel: 'تعديل المهمة {taskTitle}',
    Gantt_DeleteTaskAriaLabel: 'حذف المهمة {taskTitle}',
    Gantt_ExpandPhaseAriaLabel: '{action} المرحلة {phase}',
    Gantt_ExpandAction: 'توسيع',
    Gantt_CollapseAction: 'طي',
    Gantt_DependencyViolationTooltip: 'بدأت قبل اكتمال جميع التبعيات',
    Gantt_MilestoneAriaLabel: '{taskTitle}، معلم رئيسي، {date}',
    Gantt_BarAriaLabel: '{taskTitle}، من {startDate} إلى {dueDate}، اكتمال {percent}%',
    Gantt_PercentCompleteTooltip: 'اكتمال {value}%',

    // ── Gantt options/settings panel ──
    GanttSettings_PanelHeader: '⚙ خيارات',
    GanttSettings_ColorCodingSection: 'ترميز الألوان',
    GanttSettings_ByStatus: 'حسب الحالة',
    GanttSettings_ByPriority: 'حسب الأولوية',
    GanttSettings_ByPhase: 'حسب المرحلة',
    GanttSettings_ByHealth: 'حسب الحالة الصحية',
    GanttSettings_HeaderColorSection: 'لون الرأس',
    GanttSettings_ThemeDark: 'داكن',
    GanttSettings_ThemeNavy: 'كحلي',
    GanttSettings_ThemeTeal: 'أزرق مخضر',
    GanttSettings_ThemePurple: 'بنفسجي',
    GanttSettings_ThemeLight: 'فاتح',
    GanttSettings_HeaderLabelsSection: 'تسميات الرأس',
    GanttSettings_WeekLabelDates: 'تواريخ',
    GanttSettings_WeekLabelDatesDesc: '3 يونيو، 10 يونيو…',
    GanttSettings_WeekLabelProject: 'أسابيع المشروع',
    GanttSettings_WeekLabelProjectDesc: 'أ1، أ2…',
    GanttSettings_WeekLabelIso: 'أسابيع التقويم',
    GanttSettings_WeekLabelIsoDesc: 'أ23، أ24…',
    GanttSettings_ProjectWeeksHint: 'يبدأ الأسبوع 1 من يوم الاثنين لأقدم مهمة لديك — مثالي للعروض التقديمية.',
    GanttSettings_BarStyleSection: 'نمط الأشرطة',
    GanttSettings_BarStyleGradient: 'متدرج',
    GanttSettings_BarStyleFlat: 'مسطح',
    GanttSettings_RowHeightSection: 'ارتفاع الصف',
    GanttSettings_HeightCompact: 'مضغوط',
    GanttSettings_HeightNormal: 'عادي',
    GanttSettings_HeightSpacious: 'واسع',
    GanttSettings_ShowHideSection: 'إظهار / إخفاء',
    GanttSettings_WeekendShading: 'تظليل عطلة نهاية الأسبوع',
    GanttSettings_DependencyArrows: 'أسهم التبعية',
    GanttSettings_CriticalPathAlwaysVisible: 'المسار الحرج مرئي دائمًا',
    GanttSettings_AllOthersOnHoverOnly: 'البقية عند التمرير فقط',
    GanttSettings_CriticalPathHighlight: 'تمييز المسار الحرج',
    GanttSettings_ProgressPercentOnBars: 'نسبة التقدم على الأشرطة',
    GanttSettings_AssigneeNameOnBars: 'اسم المسؤول على الأشرطة',
    GanttSettings_HealthStatusBadges: 'شارات الحالة الصحية',

    // ── List view ──
    ListView_ColTaskName: 'اسم المهمة',
    ListView_ColStatus: 'الحالة',
    ListView_ColHealth: 'الحالة الصحية',
    ListView_ColPriority: 'الأولوية',
    ListView_ColStart: 'البداية',
    ListView_ColDue: 'الاستحقاق',
    ListView_ColAssignedTo: 'مُسند إلى',
    ListView_ColProgress: 'التقدم',
    ListView_ColPhase: 'المرحلة',
    ListView_ColPredecessors: 'السابقات',
    ListView_EmptyTitle: 'لا توجد مهام بعد',
    ListView_AddFirstTask: '+ إضافة أول مهمة',
    ListView_AddTaskRow: '+ إضافة مهمة',
    ListView_Unassigned: 'غير مُسند',
    ListView_DependencyViolationTooltip: 'بدأت قبل اكتمال جميع التبعيات',
    ListView_StatusAriaLabel: 'حالة {taskTitle}',
    ListView_PriorityAriaLabel: 'أولوية {taskTitle}',
    ListView_EditTaskAriaLabel: 'تعديل المهمة {taskTitle}',
    ListView_DeleteTaskAriaLabel: 'حذف المهمة {taskTitle}',
    ListView_EditTitle: 'تعديل',
    ListView_DeleteTitle: 'حذف',

    // ── Kanban view ──
    Kanban_ColumnNotStarted: 'لم تبدأ',
    Kanban_ColumnInProgress: 'قيد التنفيذ',
    Kanban_ColumnOnHold: 'معلقة',
    Kanban_ColumnCompleted: 'مكتملة',
    Kanban_ColumnCancelled: 'ملغاة',
    Kanban_AddTaskButton: '+ إضافة مهمة',
    Kanban_EditTitle: 'تعديل',
    Kanban_DeleteTitle: 'حذف',
    Kanban_CardAriaLabel: '{taskTitle}، {status}. اضغط Enter للتعديل، السهم الأيسر أو الأيمن لتغيير الحالة.',
    Kanban_EditTaskAriaLabel: 'تعديل المهمة {taskTitle}',
    Kanban_DeleteTaskAriaLabel: 'حذف المهمة {taskTitle}',

    // ── Dashboard view ──
    Dashboard_TotalTasks: 'إجمالي المهام',
    Dashboard_Completed: 'مكتملة',
    Dashboard_InProgress: 'قيد التنفيذ',
    Dashboard_OnHold: 'معلقة',
    Dashboard_NotStarted: 'لم تبدأ',
    Dashboard_Cancelled: 'ملغاة',
    Dashboard_OverallProgress: 'التقدم العام',
    Dashboard_ProjectManagerLabel: 'مدير المشروع: {name}',
    Dashboard_PhaseProgressHeader: 'تقدم المراحل',
    Dashboard_StatusBreakdownHeader: 'توزيع الحالة',
    Dashboard_PriorityBreakdownHeader: 'توزيع الأولوية',
    Dashboard_PriorityCritical: 'حرجة',
    Dashboard_PriorityHigh: 'عالية',
    Dashboard_PriorityMedium: 'متوسطة',
    Dashboard_PriorityLow: 'منخفضة',
    Dashboard_OverdueHeader: 'متأخرة  ({count})',
    Dashboard_DueNext14DaysHeader: 'مستحقة خلال 14 يومًا  ({count})',
    Dashboard_CompletedThisWeekHeader: 'اكتملت هذا الأسبوع',
    Dashboard_UpdatedThisWeekHeader: 'تم تحديثها هذا الأسبوع',
    Dashboard_Today: 'اليوم',
    Dashboard_Tomorrow: 'غدًا',
    Dashboard_DaysLeft: '{days}ي',
    Dashboard_EmptyTitle: 'لا توجد مهام بعد',
    Dashboard_EmptySubtitle: 'أضف مهامًا لرؤية لوحة معلومات مشروعك.',
    Dashboard_AddTaskButton: '+ إضافة مهمة',

    // ── Portfolio view ──
    Portfolio_ProjectCount: '{count} مشروع{plural}',
    Portfolio_OnTrackSummary: '{count} على المسار الصحيح',
    Portfolio_AtRiskSummary: '{count} معرضة للخطر',
    Portfolio_OverdueSummary: '{count} متأخرة',
    Portfolio_DoneSummary: '{count} منتهية',
    Portfolio_SortLabel: 'ترتيب:',
    Portfolio_SortAZ: 'أ-ي',
    Portfolio_SortHealth: 'الحالة الصحية',
    Portfolio_SortStatus: 'الحالة',
    Portfolio_SortCompletion: 'الاكتمال',
    Portfolio_RefreshTitle: 'تحديث',
    Portfolio_RefreshButton: 'تحديث',
    Portfolio_LoadingStats: 'جارٍ تحميل الإحصاءات…',
    Portfolio_EmptyTitle: 'لا توجد مشاريع بعد',
    Portfolio_CreateFirstProject: '+ إنشاء أول مشروع',
    Portfolio_StatsUnavailable: 'الإحصاءات غير متاحة',
    Portfolio_StatsUnavailableDetail: 'تعذر تحميل إحصاءات هذا المشروع.',
    Portfolio_OverallProgressLabel: 'التقدم العام',
    Portfolio_TaskCountDone: 'منتهية',
    Portfolio_TaskCountActive: 'نشطة',
    Portfolio_TaskCountAtRisk: 'معرضة للخطر',
    Portfolio_TaskCountOverdue: 'متأخرة',
    Portfolio_ViewGanttLink: 'عرض جانت ←',
    Portfolio_TodayTooltip: 'اليوم',

    // ── Task panel ──
    TaskPanel_EditHeader: 'تعديل: {taskTitle}',
    TaskPanel_NewTaskHeader: 'مهمة جديدة',
    TaskPanel_TabBasic: 'أساسي',
    TaskPanel_TabDetails: 'تفاصيل',
    TaskPanel_TabLinks: 'الروابط',
    TaskPanel_ProjectLabelPrefix: 'المشروع: ',
    TaskPanel_TaskNameLabel: 'اسم المهمة',
    TaskPanel_TaskNamePlaceholder: 'أدخل اسم المهمة',
    TaskPanel_TaskNameRequired: 'اسم المهمة مطلوب',
    TaskPanel_DescriptionLabel: 'الوصف',
    TaskPanel_DescriptionPlaceholder: 'أدخل الوصف',
    TaskPanel_StartDateLabel: 'تاريخ البدء',
    TaskPanel_DueDateLabel: 'تاريخ الاستحقاق',
    TaskPanel_DueDateError: 'يجب أن يكون تاريخ الاستحقاق في تاريخ البدء أو بعده',
    TaskPanel_StatusLabel: 'الحالة',
    TaskPanel_PriorityLabel: 'الأولوية',
    TaskPanel_PercentCompleteLabel: 'نسبة الاكتمال: {percent}%',
    TaskPanel_AssignedToLabel: 'مُسند إلى',
    TaskPanel_AssignedToPlaceholder: 'البحث عن أشخاص…',
    TaskPanel_PhaseLabel: 'المرحلة',
    TaskPanel_PhasePlaceholder: 'أدخل اسم المرحلة',
    TaskPanel_PhaseHint: 'يجمع المهام معًا في عرضي جانت والقائمة.',
    TaskPanel_MilestoneLabel: 'معلم رئيسي',
    TaskPanel_MilestoneOnText: 'نعم',
    TaskPanel_MilestoneOffText: 'لا',
    TaskPanel_CustomBarColorLabel: 'لون شريط مخصص',
    TaskPanel_CustomBarColorOptionalSuffix: ' (اختياري)',
    TaskPanel_AutoColorHint: 'لون تلقائي من إعدادات الحالة/الأولوية/المرحلة.',
    TaskPanel_NotesLabel: 'ملاحظات',
    TaskPanel_NotesPlaceholder: 'أدخل الملاحظات',
    TaskPanel_ParentTaskLabel: 'المهمة الرئيسية',
    TaskPanel_ParentTaskNone: '(لا شيء)',
    TaskPanel_ParentTaskHasChildrenHint: 'هذه المهمة لديها مهام فرعية ولا يمكن أن يكون لها مهمة رئيسية خاصة بها.',
    TaskPanel_ParentTaskHint: 'ضمّن هذه المهمة تحت أخرى كمهمة فرعية.',
    TaskPanel_DependsOnLabel: 'تعتمد على',
    TaskPanel_RemoveDependencyTitle: 'إزالة الاعتماد على "{taskTitle}"',
    TaskPanel_AddDependencyPlaceholder: 'إضافة تبعية…',
    TaskPanel_SelectATaskOption: 'اختر مهمة…',
    TaskPanel_DependsOnHint: 'لا يمكن أن تبدأ المهمة حتى تكتمل هذه المهام.',
    TaskPanel_SavingLabel: 'جارٍ الحفظ…',
    TaskPanel_CreatingLabel: 'جارٍ الإنشاء…',
    TaskPanel_SaveChangesButton: 'حفظ التغييرات',
    TaskPanel_CreateTaskButton: 'إنشاء مهمة',
    TaskPanel_CancelButton: 'إلغاء',
    TaskPanel_DismissAriaLabel: 'إغلاق',
    TaskPanel_DiscardUnsavedChangesConfirm: 'هل تريد تجاهل التغييرات غير المحفوظة؟',
    TaskPanel_SaveFallbackError: 'تعذر حفظ المهمة.',

    // ── Project panel ──
    ProjectPanel_EditHeader: 'تعديل المشروع',
    ProjectPanel_NewHeader: 'مشروع جديد',
    ProjectPanel_ProjectNameLabel: 'اسم المشروع',
    ProjectPanel_ProjectNamePlaceholder: 'أدخل اسم المشروع',
    ProjectPanel_ProjectNameRequired: 'اسم المشروع مطلوب',
    ProjectPanel_DescriptionLabel: 'الوصف',
    ProjectPanel_DescriptionPlaceholder: 'أدخل الوصف',
    ProjectPanel_ProjectColorLabel: 'لون المشروع',
    ProjectPanel_StatusLabel: 'الحالة',
    ProjectPanel_StartDateLabel: 'تاريخ البدء',
    ProjectPanel_DueDateLabel: 'تاريخ الاستحقاق',
    ProjectPanel_DueDateError: 'يجب أن يكون تاريخ الاستحقاق في تاريخ البدء أو بعده',
    ProjectPanel_WhatHappensNextTitle: 'ماذا يحدث بعد ذلك؟',
    ProjectPanel_WhatHappensNextBody: 'ستتمكن من إضافة المهام وإعداد المراحل وتتبع التقدم بمجرد إنشاء المشروع.',
    ProjectPanel_SavingLabel: 'جارٍ الحفظ…',
    ProjectPanel_CreatingLabel: 'جارٍ الإنشاء…',
    ProjectPanel_SaveChangesButton: 'حفظ التغييرات',
    ProjectPanel_CreateProjectButton: 'إنشاء المشروع',
    ProjectPanel_CancelButton: 'إلغاء',
    ProjectPanel_DismissAriaLabel: 'إغلاق',
    ProjectPanel_DiscardUnsavedChangesConfirm: 'هل تريد تجاهل التغييرات غير المحفوظة؟',
    ProjectPanel_SaveFallbackError: 'تعذر حفظ المشروع.',

    // ── Import panel ──
    ImportPanel_SourceExcelTitle: 'ملف Excel / CSV',
    ImportPanel_SourceExcelSubtitle: 'استيراد المهام من جدول بيانات',
    ImportPanel_SourcePlannerTitle: 'Microsoft Planner',
    ImportPanel_SourcePlannerSubtitle: 'استيراد المهام من خطة Planner',
    ImportPanel_ClickToBrowse: 'انقر للتصفح',
    ImportPanel_DragDropSuffix: ' أو اسحب وأفلت',
    ImportPanel_SupportedExtensions: 'يدعم .xlsx، .xls، .csv',
    ImportPanel_RowsColsSummary: 'تم اكتشاف {rows} صفوف، {cols} أعمدة',
    ImportPanel_LoadingPlannerPlans: 'جارٍ تحميل خطط Planner…',
    ImportPanel_PlannerLoadError: 'تعذر تحميل خطط Planner.',
    ImportPanel_PlannerPermissionsHintPrefix: 'تأكد من أن لديك وصولاً إلى Planner وأن ',
    ImportPanel_PlannerPermissionsHintEmphasis: 'المهام بواسطة Planner و To Do',
    ImportPanel_PlannerPermissionsHintSuffix: ' متاحة لهذا الموقع.',
    ImportPanel_NoPlannerPlansFoundTitle: 'لم يتم العثور على خطط Planner',
    ImportPanel_NoPlannerPlansFoundBody: 'قد لا يكون لديك وصول إلى أي خطط Planner، أو لا توجد خطط لهذا الحساب.',
    ImportPanel_TaskCountFoundIn: 'تم العثور على {count} مهمة في "{planName}"',
    ImportPanel_ProjectDetailsIntroPrefix: 'الاستيراد إلى ',
    ImportPanel_ProjectDetailsIntroSuffix: '. راجع تفاصيل المشروع أدناه.',
    ImportPanel_ProjectNameLabel: 'اسم المشروع',
    ImportPanel_DescriptionLabel: 'الوصف',
    ImportPanel_StatusLabel: 'الحالة',
    ImportPanel_ColorLabel: 'اللون',
    ImportPanel_MapIntro: 'قم بربط الأعمدة من ملفك بحقول المهام.',
    ImportPanel_CreatingProjectStatus: 'جارٍ إنشاء المشروع…',
    ImportPanel_ImportingTasksStatus: 'جارٍ استيراد المهام…',
    ImportPanel_ProgressLabel: '{done} من {total}',
    ImportPanel_CouldNotCreateProject: 'تعذر إنشاء المشروع.',
    ImportPanel_ImportCompletedWithErrors: 'اكتمل الاستيراد مع {count} خطأ (أخطاء).',
    ImportPanel_ProjectCreatedSuccess: 'تم إنشاء المشروع بنجاح!',
    ImportPanel_ImportSuccessful: 'تم الاستيراد بنجاح!',
    ImportPanel_TasksAddedTo: 'تمت إضافة {count} مهمة إلى "{projectName}"',
    ImportPanel_FailedRowsLabel: 'الصفوف الفاشلة:',
    ImportPanel_CloseButton: 'إغلاق',
    ImportPanel_OpenProjectButton: 'فتح المشروع',
    ImportPanel_ViewImportedTasksButton: 'عرض المهام المستوردة',
    ImportPanel_NextMapColumnsButton: 'التالي: ربط الأعمدة',
    ImportPanel_ImportNTasksButton: 'استيراد {count} مهمة',
    ImportPanel_BackButton: 'رجوع',
    ImportPanel_CancelButton: 'إلغاء',
    ImportPanel_NextButton: 'التالي',
    ImportPanel_StepSource: 'المصدر',
    ImportPanel_StepProject: 'المشروع',
    ImportPanel_StepMap: 'الربط',
    ImportPanel_StepImport: 'الاستيراد',
    ImportPanel_StepDone: 'تم',
    ImportPanel_ImportAsNewProjectHeader: 'استيراد ملف كمشروع جديد',
    ImportPanel_ImportIntoProjectHeader: 'استيراد المهام إلى {projectName}',
    ImportPanel_CouldNotParseFile: 'تعذر تحليل الملف.',
    ImportPanel_CouldNotLoadPlannerTasks: 'تعذر تحميل المهام من هذه الخطة.',
    ImportPanel_CouldNotCreateProjectDetail: 'تعذر إنشاء المشروع: {detail}',
    ImportPanel_CouldNotLinkDependencies: 'تعذر ربط التبعيات: {detail}',
    ImportPanel_UnknownError: 'خطأ غير معروف',

    // ── Column mapper (import) ──
    ColumnMapper_TaskNameRequiredBanner: 'يجب ربط اسم المهمة للمتابعة.',
    ColumnMapper_SkippedColumnsBanner: 'سيتم تخطي {count} عمود (أعمدة).',
    ColumnMapper_SourceColumnHeader: 'عمود المصدر',
    ColumnMapper_TargetFieldHeader: 'الحقل الهدف',
    ColumnMapper_StatusHeader: 'الحالة',
    ColumnMapper_SkippedBadge: 'تم التخطي',
    ColumnMapper_AutoMappedBadge: 'ربط تلقائي',
    ColumnMapper_SetBadge: 'محدد',
    ColumnMapper_PreviewTitle: 'معاينة: {columnName}',
    ColumnMapper_EmptyCellDash: '—',

    // ── Import field display names / ImportService ──
    ImportField_TaskName: 'اسم المهمة',
    ImportField_StartDate: 'تاريخ البدء',
    ImportField_DueDate: 'تاريخ الاستحقاق',
    ImportField_Status: 'الحالة',
    ImportField_Priority: 'الأولوية',
    ImportField_AssignedTo: 'مُسند إلى',
    ImportField_AssignedToEmail: 'البريد الإلكتروني للمسؤول',
    ImportField_PercentComplete: 'نسبة الاكتمال',
    ImportField_Phase: 'المرحلة',
    ImportField_Description: 'الوصف',
    ImportField_Notes: 'ملاحظات',
    ImportField_IsMilestone: 'معلم رئيسي',
    ImportField_Dependencies: 'التبعيات',
    ImportField_SkipColumn: '(تخطي هذا العمود)',
    ImportService_EmptyFileError: 'يبدو أن الملف فارغ أو لا يحتوي على صفوف بيانات.',
    ImportService_ReadErrorDetail: 'تعذر قراءة الملف: {detail}.',
    ImportService_FileReadError: 'خطأ في قراءة الملف.',
    ImportService_RowError: 'الصف {rowNum} ("{title}"): {error}',
    ImportService_AmbiguousDependency: 'التبعية "{name}" تطابق أكثر من عنوان مهمة واحد — تم التخطي.',
    ImportService_LinkDependencyError: 'تعذر ربط التبعيات للمهمة {taskId}: {error}',

    // ── Health labels (shared: healthUtils.ts and ExportService.ts both use this set; also replaces the duplicated Export_PortfolioHealthLabel* keys) ──
    Health_Done: 'منتهية',
    Health_OnTrack: 'على المسار الصحيح',
    Health_AtRisk: 'معرضة للخطر',
    Health_Overdue: 'متأخرة',

    // ── Status / Priority display labels (DISPLAY-ONLY — stored SharePoint Choice values remain unchanged/English) ──
    Status_NotStarted: 'لم تبدأ',
    Status_InProgress: 'قيد التنفيذ',
    Status_Completed: 'مكتملة',
    Status_OnHold: 'معلقة',
    Status_Cancelled: 'ملغاة',
    Priority_Critical: 'حرجة',
    Priority_High: 'عالية',
    Priority_Medium: 'متوسطة',
    Priority_Low: 'منخفضة',
    ProjectStatus_Planning: 'التخطيط',
    ProjectStatus_Active: 'نشط',
    ProjectStatus_OnHold: 'معلق',
    ProjectStatus_Completed: 'مكتمل',
    ProjectStatus_Cancelled: 'ملغى',

    // ── Shell (SmartGantt.tsx) ──
    SmartGantt_LoadingProjects: 'جارٍ تحميل المشاريع…',
    SmartGantt_UnableToLoad: 'تعذر التحميل',
    SmartGantt_RetryButton: 'إعادة المحاولة',
    SmartGantt_NoProjectsYet: 'لا توجد مشاريع بعد',
    SmartGantt_NoProjectsSubtitle: 'أنشئ مشروعك الأول للبدء.',
    SmartGantt_CreateFirstProjectButton: '+ إنشاء أول مشروع',
    SmartGantt_ImportFromExcelButton: '📥 استيراد من Excel',
    SmartGantt_LoadingTasks: 'جارٍ تحميل المهام…',
    SmartGantt_DismissAriaLabel: 'إغلاق',
    SmartGantt_DeleteTaskDialogTitle: 'حذف المهمة',
    SmartGantt_DeleteTaskDialogSubtext: 'هل أنت متأكد أنك تريد حذف "{taskTitle}"؟ لا يمكن التراجع عن هذا الإجراء.',
    SmartGantt_DeleteButton: 'حذف',
    SmartGantt_CancelButton: 'إلغاء',
    SmartGantt_ArchiveProjectDialogTitle: 'أرشفة المشروع',
    SmartGantt_ArchiveProjectDialogSubtext: 'أرشفة "{projectTitle}"؟ يمكنك إلغاء أرشفته لاحقًا.',
    SmartGantt_ArchiveButton: 'أرشفة',
    SmartGantt_SendToRecycleBinDialogTitle: 'نقل إلى سلة المحذوفات',
    SmartGantt_SendToRecycleBinDialogSubtext: 'نقل "{projectTitle}" إلى سلة محذوفات الموقع؟',
    SmartGantt_SendToRecycleBinButton: 'نقل إلى سلة المحذوفات',
    SmartGantt_FailedLoadProjects: 'فشل تحميل المشاريع. تحقق من أذونات الموقع.',
    SmartGantt_FailedLoadTasks: 'فشل تحميل المهام لهذا المشروع.',
    SmartGantt_FailedLoadPortfolioStats: 'فشل تحميل إحصاءات المحفظة.',
    SmartGantt_CouldNotSaveProject: 'تعذر حفظ المشروع: {message}',
    SmartGantt_CouldNotDeleteProject: 'تعذر حذف المشروع: {message}',
    SmartGantt_CouldNotArchiveProject: 'تعذر أرشفة المشروع: {message}',
    SmartGantt_CouldNotUnarchiveProject: 'تعذر إلغاء أرشفة المشروع: {message}',
    SmartGantt_CouldNotSaveTask: 'تعذر حفظ المهمة: {message}',
    SmartGantt_CouldNotDeleteTask: 'تعذر حذف المهمة: {message}',
    SmartGantt_ImageExportFailed: 'فشل تصدير الصورة: {message}',
    SmartGantt_PowerPointExportFailed: 'فشل تصدير PowerPoint: {message}',
    SmartGantt_PortfolioExportFailed: 'فشل تصدير المحفظة: {message}',
    SmartGantt_CouldNotUpdateTask: 'تعذر تحديث المهمة: {message}',

    // ── Common ──
    ColorSwatch_AutoColorAriaLabel: 'لون تلقائي',
    ColorSwatch_CustomColorAriaLabel: 'لون مخصص',
    ColorSwatch_PickCustomColorTitle: 'اختر لونًا مخصصًا',

    // ── Export (Excel / PowerPoint) ──
    Export_ColTaskName: 'اسم المهمة',
    Export_ColPhase: 'المرحلة',
    Export_ColStartDate: 'تاريخ البدء',
    Export_ColDueDate: 'تاريخ الاستحقاق',
    Export_ColStatus: 'الحالة',
    Export_ColPriority: 'الأولوية',
    Export_ColAssignedTo: 'مُسند إلى',
    Export_ColAssignedToEmail: 'البريد الإلكتروني للمسؤول',
    Export_ColPercentComplete: 'نسبة الاكتمال',
    Export_ColIsMilestone: 'معلم رئيسي',
    Export_ColDescription: 'الوصف',
    Export_ColNotes: 'ملاحظات',
    Export_Yes: 'نعم',
    Export_No: 'لا',
    Export_SheetNameTasks: 'المهام',
    Export_ExcelFileSuffix: ' - المهام.xlsx',
    Export_TaskNameColumnLabel: 'اسم المهمة',
    Export_ExportedDateLabel: 'تم التصدير في {date}',
    Export_ProjectReportLabel: 'تقرير المشروع',
    Export_StatusLine: 'الحالة: {status}',
    Export_DateRangeSeparator: ' إلى ',
    Export_ProjectManagerLine: 'مدير المشروع: {name}',
    Export_GeneratedDateLine: 'تم الإنشاء في {date}',
    Export_ProjectSummaryTitle: 'ملخص المشروع',
    Export_StatTotalTasks: 'إجمالي المهام',
    Export_StatCompleted: 'مكتملة',
    Export_StatInProgress: 'قيد التنفيذ',
    Export_StatOnHold: 'معلقة',
    Export_StatNotStarted: 'لم تبدأ',
    Export_OverallProgressLine: 'التقدم العام',
    Export_OverallProgressPercent: '{percent}%',
    Export_StatusBreakdownTitle: 'توزيع الحالة',
    Export_StatusBreakdownRow: '{status}: {count} ({percent}%)',
    Export_GanttTimelineTitle: 'الجدول الزمني لجانت',
    Export_SummaryRecentActivityTitle: 'النشاط الأخير',
    Export_ProjectOverviewLabel: 'نظرة عامة على المشروع',
    Export_DetailStatusLabel: 'الحالة',
    Export_DetailStartDateLabel: 'تاريخ البدء',
    Export_DetailDueDateLabel: 'تاريخ الاستحقاق',
    Export_DetailProjectManagerLabel: 'مدير المشروع',
    Export_Past7DaysLabel: 'آخر 7 أيام',
    Export_NoActivityMessage: 'لا يوجد نشاط حديث.',
    Export_CompletedThisWeekHeader: 'اكتملت هذا الأسبوع ({count})',
    Export_NewBadge: 'جديد  ',
    Export_CompletedPercentLine: 'اكتمال {percent}%',
    Export_MoreItemsSuffix: '+ {count} أخرى',
    Export_InProgressUpdatedHeader: 'قيد التنفيذ / تم تحديثها',
    Export_StatusPercentLine: '{status} — {percent}%',
    Export_PortfolioReportLabel: 'تقرير المحفظة',
    Export_PortfolioOverviewTitle: 'نظرة عامة على المحفظة',
    Export_ProjectsCountLine: '{count} مشروع',
    Export_HealthSummaryOnTrack: '{count} على المسار الصحيح',
    Export_HealthSummaryAtRisk: '{count} معرضة للخطر',
    Export_HealthSummaryOverdue: '{count} متأخرة',
    Export_ProjectsSummaryHeader: 'ملخص المشاريع',
    Export_TableProject: 'المشروع',
    Export_TableStatus: 'الحالة',
    Export_TableHealth: 'الحالة الصحية',
    Export_TableTotal: 'الإجمالي',
    Export_TableDone: 'منتهية',
    Export_TableActive: 'نشطة',
    Export_TableAtRisk: 'معرضة للخطر',
    Export_TableOverdue: 'متأخرة',
    Export_TablePctDone: 'نسبة الاكتمال',
    Export_TableDueDate: 'تاريخ الاستحقاق',
    Export_PortfolioSummaryFileName: 'ملخص المحفظة.xlsx',
    Export_PortfolioReportFileName: 'تقرير المحفظة.pptx',
    Export_ProjectReportFileName: 'تقرير {projectName}.pptx',
    Export_UnavailableLabel: 'غير متاح',
    Export_SheetNamePortfolio: 'المحفظة',
    Export_ColStart: 'البداية',
    Export_ColDue: 'الاستحقاق',
    Export_ImageGenerationFailed: 'تعذر إنشاء الصورة — قد يكون الرسم البياني كبيرًا جدًا للتصدير كصورة.',
    Export_DrawingContextFailed: 'تعذر إنشاء سياق رسم للتصدير.',
    Export_SvgRenderFailed: 'فشل عرض SVG',

    // ── Added in v1.5 review ──
    Svc_TooManyDependencies: 'تحتوي هذه المهمة على عدد كبير جدًا من التبعيات بحيث لا يمكن حفظها (الحد الأقصى نحو 60). أزل بعضها وحاول مرة أخرى.',
    Svc_TaskChangedByOthers: 'تم تغيير هذه المهمة بواسطة شخص آخر منذ تحميلها. حدّث الصفحة وحاول مرة أخرى.',
    Svc_ProjectChangedByOthers: 'تم تغيير هذا المشروع بواسطة شخص آخر منذ فتحه. حدّث الصفحة وحاول مرة أخرى.',
    Svc_ColumnCreateFailed: 'تعذر إنشاء {count} من الأعمدة في قائمة المهام الجديدة: {detail}',
    Svc_BaselineUnavailable: 'خطوط الأساس غير متاحة لهذا المشروع لأنه تعذرت إضافة أعمدة خط الأساس (قد تحتاج إلى إذن لتعديل القائمة).',
    Svc_SubtaskReassignFailed: 'تعذرت إعادة إسناد المهام الفرعية لهذه المهمة قبل حذفها: {detail}',
    Svc_UnresolvedDependency: 'الصف {row} ("{title}"): تعذرت مطابقة التبعية "{name}" مع مهمة مستوردة.',
    Svc_SelfDependency: 'الصف {row} ("{title}"): التبعية "{name}" تشير إلى المهمة نفسها وتم تخطيها.',
    Svc_ColId: 'المعرّف',
    Svc_ColDependencies: 'التبعيات',
    Svc_ColBaselineStart: 'بداية خط الأساس',
    Svc_ColBaselineDue: 'استحقاق خط الأساس',
    Svc_CsvFileSuffix: ' - Tasks.csv',
    Svc_IcsFileSuffix: ' - Milestones.ics',
    Svc_PortfolioCsvFileName: 'Portfolio Summary.csv',
    Svc_PP_DisplayGroup: 'الإعدادات الافتراضية',
    Svc_PP_DefaultView: 'طريقة العرض الافتراضية',
    Svc_PP_ViewGantt: 'جانت',
    Svc_PP_ViewList: 'قائمة',
    Svc_PP_ViewKanban: 'كانبان',
    Svc_PP_ViewDashboard: 'لوحة المعلومات',
    Svc_PP_ViewPortfolio: 'المحفظة',
    Svc_PP_DefaultZoom: 'التكبير الافتراضي',
    Svc_PP_ZoomDay: 'يوم',
    Svc_PP_ZoomWeek: 'أسبوع',
    Svc_PP_ZoomMonth: 'شهر',
    Svc_PP_ZoomQuarter: 'ربع سنة',
    Svc_PP_CalendarGroup: 'تقويم العمل',
    Svc_PP_DaySun: 'الأحد يوم عمل',
    Svc_PP_DayMon: 'الاثنين يوم عمل',
    Svc_PP_DayTue: 'الثلاثاء يوم عمل',
    Svc_PP_DayWed: 'الأربعاء يوم عمل',
    Svc_PP_DayThu: 'الخميس يوم عمل',
    Svc_PP_DayFri: 'الجمعة يوم عمل',
    Svc_PP_DaySat: 'السبت يوم عمل',
    Svc_PP_Holidays: 'العطلات (تواريخ غير عمل)',
    Svc_PP_HolidaysHint: 'تاريخ واحد في كل سطر، بالتنسيق yyyy-MM-dd (مثال: 2026-12-25).',
    Gantt_TimelineAriaLabel: 'الجدول الزمني للمهام',
    Gantt_DragLabel: '{start} → {end} ({days} ي)',
    Gantt_KeyboardMoveAnnouncement: '{taskTitle}: {startDate} إلى {dueDate}',
    Gantt_KeyboardHint: 'اضغط Enter لفتح المهمة. تنقلها مفاتيح الأسهم اليمنى واليسرى بمقدار يوم عمل واحد. استخدم Shift مع مفاتيح الأسهم لتغيير تاريخ الانتهاء.',
    Gantt_ParentCycleTooltip: 'هذه المهمة جزء من سلسلة دائرية من المهام الأصل والفرعية، لذا تظهر في المستوى الأعلى',
    Gantt_CollapseAll: 'طي جميع المراحل',
    Gantt_ExpandAll: 'توسيع جميع المراحل',
    Gantt_BaselineTooltip: 'خط الأساس: {start} → {due}',
    Gantt_VarianceTooltip: 'تباين الانتهاء: {days} يوم مقارنة بخط الأساس',
    Gantt_LinkHandleTitle: 'اسحبه إلى مهمة أخرى لإنشاء تبعية',
    Toolbar_FitToProject: 'ملاءمة',
    Toolbar_FitToProjectTitle: 'تكبير لملاءمة المشروع بالكامل',
    Toolbar_UndoTitle: 'تراجع (Ctrl+Z)',
    Toolbar_RedoTitle: 'إعادة (Ctrl+Y)',
    Toolbar_ExportCsv: '📄 تصدير المهام إلى CSV',
    Toolbar_ExportIcs: '📅 تصدير المعالم (iCal)',
    Toolbar_Print: '🖨 طباعة / حفظ كـ PDF',
    Toolbar_SetBaseline: '📐 تعيين خط الأساس…',
    Toolbar_CopyLink: '🔗 نسخ الرابط',
    Toolbar_CopyLinkTitle: 'انسخ رابطًا لطريقة العرض هذه (المشروع وطريقة العرض والتكبير والمرشحات)',
    App_UndoButton: 'تراجع',
    App_Undone: 'تم التراجع عن التغيير.',
    App_Redone: 'تمت إعادة التغيير.',
    App_DependentsMovedOne: 'تم نقل مهمة تابعة واحدة.',
    App_DependentsMovedMany: 'تم نقل {count} من المهام التابعة.',
    App_TaskConflict: 'تم تغيير هذه المهمة بواسطة شخص آخر. تمت إعادة تحميل أحدث المهام — راجعها وحاول مرة أخرى.',
    App_DependencyCycle: 'سيؤدي هذا الربط إلى إنشاء تبعية دائرية.',
    App_DependencyExists: 'هاتان المهمتان مرتبطتان بالفعل.',
    App_LinkCopied: 'تم نسخ الرابط إلى الحافظة.',
    App_LinkCopyFailed: 'تعذر نسخ الرابط: {message}',
    App_PopupBlocked: 'تم حظر نافذة الطباعة. اسمح بالنوافذ المنبثقة لهذا الموقع وحاول مرة أخرى.',
    App_SetBaselineDialogTitle: 'تعيين خط الأساس',
    App_SetBaselineDialogSubtext: 'هل تريد حفظ تواريخ البداية والاستحقاق الحالية لجميع المهام البالغ عددها {count} كخط أساس؟ سيتم استبدال أي خط أساس موجود.',
    App_SetBaselineButton: 'تعيين خط الأساس',
    App_BaselineSaved: 'تم حفظ خط الأساس.',
    App_BaselineFailed: 'تعذر حفظ خط الأساس: {message}',
    App_CsvExportFailed: 'فشل تصدير CSV: {message}',
    App_IcsExportFailed: 'فشل تصدير التقويم: {message}',
    App_BulkDeleteDialogTitle: 'حذف المهام',
    App_BulkDeleteDialogSubtext: 'هل تريد بالتأكيد حذف {count} من المهام؟ لا يمكن التراجع عن هذا الإجراء.',
    Common_PeoplePicker_ClearAriaLabel: 'مسح',
    Common_PeoplePicker_DirectoryHeader: 'الأشخاص في الدليل',
    Common_PeoplePicker_EmailLabel: 'البريد الإلكتروني (اختياري)',
    Common_PeoplePicker_EmailPlaceholder: 'name@company.com',
    Common_PeoplePicker_ExternalHint: 'غير موجود في الدليل. سيتم الحفظ كنص عادي.',
    Common_PeoplePicker_InvalidEmail: 'أدخل عنوان بريد إلكتروني صالحًا.',
    Common_PeoplePicker_ListAriaLabel: 'اقتراحات الأشخاص',
    Common_PeoplePicker_RecentHeader: 'المستخدمة مؤخرًا',
    Common_PeoplePicker_ResultsAnnouncement: '{count} اقتراحات متاحة',
    Common_PeoplePicker_Searching: 'جارٍ البحث…',
    Common_PeoplePicker_UseExternal: 'استخدام “{name}” (خارجي / غير موجود في الدليل)',
    Import_Mapper_PreviewFirstRows: 'معاينة (أول {count} من الصفوف)',
    Import_Mapper_RequiredLegend: 'حقل مطلوب',
    Import_Mapper_RequiredMarkerLabel: 'مطلوب',
    Import_Mapper_SelectAriaLabel: 'الحقل الهدف للعمود {columnName}',
    Import_Panel_DateOrderAuto: 'اكتشاف تلقائي',
    Import_Panel_DateOrderDMY: 'يوم/شهر/سنة (31/12/2026)',
    Import_Panel_DateOrderDetected: 'تم الاكتشاف من ملفك: {order}.',
    Import_Panel_DateOrderHint: 'ينطبق على التواريخ المكتوبة بالأرقام، مثل 03/04/2026.',
    Import_Panel_DateOrderLabel: 'ترتيب التاريخ',
    Import_Panel_DateOrderMDY: 'شهر/يوم/سنة (12/31/2026)',
    Import_Panel_DropZoneAriaLabel: 'اختر ملفًا للاستيراد. اضغط Enter للتصفح.',
    Import_Panel_DropZoneChangeAriaLabel: 'الملف المحدد {fileName}. اضغط Enter لاختيار ملف مختلف.',
    Import_Panel_FailedCount: 'فشل {count}',
    Import_Panel_NewProjectIntroMany: 'سيتم إنشاء مشروع جديد واستيراد جميع المهام البالغ عددها {count} إليه. يمكنك تغيير هذه التفاصيل في أي وقت بعد الاستيراد.',
    Import_Panel_NewProjectIntroOne: 'سيتم إنشاء مشروع جديد واستيراد المهمة ({count}) إليه. يمكنك تغيير هذه التفاصيل في أي وقت بعد الاستيراد.',
    Import_Panel_PlanAriaLabel: '{planName}، {groupName}',
    Import_Panel_ProblemEndBeforeStart: 'تاريخ الاستحقاق قبل تاريخ البداية',
    Import_Panel_ProblemInvalidDueDate: 'تاريخ الاستحقاق "{value}" ليس تاريخًا صالحًا',
    Import_Panel_ProblemInvalidStartDate: 'تاريخ البداية "{value}" ليس تاريخًا صالحًا',
    Import_Panel_ProblemMissingTitle: 'اسم المهمة مفقود',
    Import_Panel_ProgressLabelWithPercent: '{done} من {total} ({percent}%)',
    Import_Panel_SkipInvalidRows: 'تخطي الصفوف التي بها مشكلات',
    Import_Panel_SuccessWithWarningsMany: 'تم الاستيراد بنجاح مع {count} من التحذيرات.',
    Import_Panel_SuccessWithWarningsOne: 'تم الاستيراد بنجاح مع {count} تحذير.',
    Import_Panel_ValidationHeader: 'الصفوف التي بها مشكلات',
    Import_Panel_ValidationMore: '…و{count} أخرى',
    Import_Panel_ValidationRow: 'الصف {rowNum}: {problem}',
    Import_Panel_ValidationSummaryMany: '{count} من الصفوف بها مشكلات',
    Import_Panel_ValidationSummaryOne: '{count} صف به مشكلة',
    Import_Panel_WarningsLabel: 'التحذيرات ({count}):',
    Panel_Project_ManagerLabel: 'مدير المشروع',
    Panel_Project_ManagerPlaceholder: 'ابحث عن أشخاص أو اكتب اسمًا…',
    Panel_Task_BaselineDueLabel: 'انتهاء خط الأساس',
    Panel_Task_BaselineHeader: 'خط الأساس',
    Panel_Task_BaselineStartLabel: 'بداية خط الأساس',
    Panel_Task_DepTypeFF: 'من النهاية إلى النهاية (FF)',
    Panel_Task_DepTypeFS: 'من النهاية إلى البداية (FS)',
    Panel_Task_DepTypeSF: 'من البداية إلى النهاية (SF)',
    Panel_Task_DepTypeSS: 'من البداية إلى البداية (SS)',
    Panel_Task_LagAriaLabel: 'التأخير بأيام العمل للمهمة {taskTitle}',
    Panel_Task_LagHint: 'التأخير بأيام العمل. استخدم رقمًا سالبًا لوقت التقديم.',
    Panel_Task_LinkTypeAriaLabel: 'نوع الارتباط للمهمة {taskTitle}',
    Panel_Task_VarianceEarlier: 'أبكر بـ {days} من أيام العمل',
    Panel_Task_VarianceLater: 'أبعد بـ {days} من أيام العمل',
    Panel_Task_VarianceOnBaseline: 'مطابق لخط الأساس',
    View_Dashboard_BurndownActual: 'الفعلي',
    View_Dashboard_BurndownAria: 'مخطط الاحتراق: تبقّى {remaining} من {total} مهمة',
    View_Dashboard_BurndownHeader: 'الاحتراق (المهام المتبقية)',
    View_Dashboard_BurndownIdeal: 'المثالي',
    View_Dashboard_BurndownNoData: 'لا توجد مهام مؤرخة كافية لرسم مخطط الاحتراق.',
    View_Dashboard_CriticalPathHeader: 'المسار الحرج  ({count})',
    View_Dashboard_PhaseDoneSummary: 'اكتمل {done}/{total}  •  {percent}%',
    View_Dashboard_TaskRowAriaLabel: 'فتح المهمة {taskTitle}، {status}',
    View_Dashboard_WorkloadHeader: 'عبء العمل حسب المسؤول',
    View_Dashboard_WorkloadOpen: '{count} مفتوحة',
    View_Dashboard_WorkloadOverdue: '{count} متأخرة',
    View_Kanban_AddTaskInColumnAriaLabel: 'إضافة مهمة إلى {column}',
    View_Kanban_CollapseColumn: 'طي عمود {column}',
    View_Kanban_ExpandColumn: 'توسيع عمود {column}',
    View_Kanban_LaneHeader: '{name} ({count})',
    View_Kanban_LaneNoPhase: 'بدون مرحلة',
    View_Kanban_LaneUnassigned: 'غير معيّن',
    View_Kanban_LanesAssignee: 'المسؤول',
    View_Kanban_LanesNone: 'بدون',
    View_Kanban_LanesPhase: 'المرحلة',
    View_Kanban_SwimlanesLabel: 'المسارات',
    View_Kanban_WipEditTitle: 'تعيين حد العمل قيد التنفيذ للعمود {column} (0 لعدم وجود حد)',
    View_Kanban_WipExceededTitle: 'تم تجاوز حد WIP: {count} من {limit}',
    View_Kanban_WipInputAriaLabel: 'حد WIP للعمود {column}',
    View_Kanban_WipLabel: 'WIP {count}/{limit}',
    View_Kanban_WipSet: 'WIP',
    View_List_BulkAssignApply: 'تعيين',
    View_List_BulkAssigneePlaceholder: 'تعيين إلى…',
    View_List_BulkBarAriaLabel: 'إجراءات مجمّعة للمهام المحددة',
    View_List_BulkClear: 'مسح التحديد',
    View_List_BulkDelete: 'حذف المحدد',
    View_List_BulkPercentApply: 'تعيين %',
    View_List_BulkPercentPlaceholder: '% الإنجاز',
    View_List_BulkPriorityPlaceholder: 'تعيين الأولوية…',
    View_List_BulkSelectedCount: '{count} محددة',
    View_List_BulkStatusPlaceholder: 'تعيين الحالة…',
    View_List_ExportCsv: 'تصدير CSV',
    View_List_NonWorkingDay: 'يوم غير عمل',
    View_List_SelectAllAriaLabel: 'تحديد جميع المهام',
    View_List_SelectRowAriaLabel: 'تحديد {taskTitle}',
    View_Portfolio_CardAriaLabel: 'فتح المشروع {projectName}، {status}',
    View_Portfolio_ClearFilters: 'مسح المرشحات',
    View_Portfolio_FilteredCount: '{shown} من {total} من المشاريع',
    View_Portfolio_HideDone: 'إخفاء المكتملة / الملغاة',
    View_Portfolio_NoMatches: 'لا توجد مشاريع تطابق المرشحات.',
    View_Portfolio_ProjectCountMany: '{count} من المشاريع',
    View_Portfolio_ProjectCountOne: '{count} مشروع',
    View_Portfolio_SearchAriaLabel: 'البحث في المشاريع',
    View_Portfolio_SearchPlaceholder: 'البحث في المشاريع…',
    Import_Panel_CopyDetails: 'نسخ التفاصيل',
    Import_Panel_Copied: 'تم النسخ',
  };
});
