define([], function () {
  return {
    // ── Property pane ──
    PropertyPane_HeaderDescription: 'إعدادات مخطط جانت الذكي',
    PropertyPane_GeneralGroupName: 'عام',
    PropertyPane_TitleFieldLabel: 'عنوان الويب بارت',
    WebPart_DefaultTitle: 'مخطط جانت الذكي',

    // ── Toolbar ──
    Toolbar_ViewDashboard: 'لوحة المعلومات',
    Toolbar_ViewList: 'قائمة',
    Toolbar_ViewGantt: 'جانت',
    Toolbar_ViewKanban: 'كانبان',
    Toolbar_ZoomDay: 'يوم',
    Toolbar_ZoomWeek: 'أسبوع',
    Toolbar_ZoomMonth: 'شهر',
    Toolbar_ZoomQuarter: 'ربع سنة',
    Toolbar_SelectProjectAriaLabel: 'اختر المشروع',
    Toolbar_PortfolioLabel: 'المحفظة',
    Toolbar_SelectAProject: 'اختر مشروعًا',
    Toolbar_AllProjectsSubtext: 'جميع المشاريع',
    Toolbar_NoProjectsYet: 'لا توجد مشاريع بعد',
    Toolbar_ArchivedBadge: 'مؤرشف',
    Toolbar_ShowArchivedProjects: 'إظهار المشاريع المؤرشفة',
    Toolbar_NewProject: '+ مشروع جديد',
    Toolbar_ImportFileAsNewProject: '📥 استيراد ملف كمشروع جديد…',
    Toolbar_AddTask: '+ إضافة مهمة',
    Toolbar_EditProject: 'تعديل المشروع',
    Toolbar_OptionsButton: '⚙ خيارات',
    Toolbar_MoreOptionsTitle: 'المزيد من الخيارات',
    Toolbar_ExportToExcel: '📊 تصدير إلى Excel',
    Toolbar_ExportToPowerPoint: '📑 تصدير إلى PowerPoint',
    Toolbar_ScrollToTodayTitle: 'الانتقال إلى اليوم',
    Toolbar_TodayButton: '◉ اليوم',
    Toolbar_ImportTasks: '📥 استيراد المهام…',
    Toolbar_ExportAsImage: '🖼 تصدير كصورة (PNG)',
    Toolbar_UnarchiveProject: '📂 إلغاء أرشفة المشروع',
    Toolbar_ArchiveProject: '🗄️ أرشفة المشروع',
    Toolbar_SendToRecycleBin: '🗑️ نقل إلى سلة المحذوفات',

    // ── Filter bar ──
    FilterBar_ClearOption: 'مسح',
    FilterBar_DueAny: 'أي تاريخ استحقاق',
    FilterBar_DueOverdue: 'متأخر',
    FilterBar_DueToday: 'مستحق اليوم',
    FilterBar_DueWeek: 'مستحق خلال 7 أيام',
    FilterBar_SearchPlaceholder: 'البحث عن المهام…',
    FilterBar_SearchAriaLabel: 'البحث عن المهام',
    FilterBar_StatusChipLabel: 'الحالة',
    FilterBar_PriorityChipLabel: 'الأولوية',
    FilterBar_AssigneeChipLabel: 'المسؤول',
    FilterBar_PhaseChipLabel: 'المرحلة',
    FilterBar_DueDateAriaLabel: 'التصفية حسب تاريخ الاستحقاق',
    FilterBar_MatchCount: '{matchCount} من {totalCount}',
    FilterBar_ClearFilters: '✕ مسح عوامل التصفية',
    FilterBar_ChipLabelWithCount: '{label} ({count}) ▾',
    FilterBar_ChipLabelNoCount: '{label} ▾',

    // ── Gantt view ──
    Gantt_TaskColumnHeader: 'المهمة',
    Gantt_DurationColumnHeader: 'المدة',
    Gantt_AddTaskButton: '+ إضافة مهمة',
    Gantt_EmptyTitle: 'لا توجد مهام بعد',
    Gantt_EmptySubtitle: 'أضف مهام لرؤيتها في مخطط جانت.',
    Gantt_AddFirstTask: '+ إضافة أول مهمة',
    Gantt_ImportTasksButton: '📥 استيراد المهام',
    Gantt_EditTitle: 'تعديل',
    Gantt_DeleteTitle: 'حذف',
    Gantt_EditTaskAriaLabel: 'تعديل المهمة {taskTitle}',
    Gantt_DeleteTaskAriaLabel: 'حذف المهمة {taskTitle}',
    Gantt_ExpandPhaseAriaLabel: '{action} المرحلة {phase}',
    Gantt_ExpandAction: 'توسيع',
    Gantt_CollapseAction: 'طي',
    Gantt_DependencyViolationTooltip: 'بدأت قبل اكتمال جميع التبعيات',
    Gantt_MilestoneAriaLabel: '{taskTitle}، معلم رئيسي، {date}',
    Gantt_BarAriaLabel: '{taskTitle}، من {startDate} إلى {dueDate}، اكتمال {percent}%',
    Gantt_PercentCompleteTooltip: 'اكتمال {value}%',

    // ── Gantt options/settings panel ──
    GanttSettings_PanelHeader: '⚙ خيارات',
    GanttSettings_ColorCodingSection: 'ترميز الألوان',
    GanttSettings_ByStatus: 'حسب الحالة',
    GanttSettings_ByPriority: 'حسب الأولوية',
    GanttSettings_ByPhase: 'حسب المرحلة',
    GanttSettings_ByHealth: 'حسب الحالة الصحية',
    GanttSettings_HeaderColorSection: 'لون الرأس',
    GanttSettings_ThemeDark: 'داكن',
    GanttSettings_ThemeNavy: 'كحلي',
    GanttSettings_ThemeTeal: 'أزرق مخضر',
    GanttSettings_ThemePurple: 'بنفسجي',
    GanttSettings_ThemeLight: 'فاتح',
    GanttSettings_HeaderLabelsSection: 'تسميات الرأس',
    GanttSettings_WeekLabelDates: 'تواريخ',
    GanttSettings_WeekLabelDatesDesc: '3 يونيو، 10 يونيو…',
    GanttSettings_WeekLabelProject: 'أسابيع المشروع',
    GanttSettings_WeekLabelProjectDesc: 'أ1، أ2…',
    GanttSettings_WeekLabelIso: 'أسابيع التقويم',
    GanttSettings_WeekLabelIsoDesc: 'أ23، أ24…',
    GanttSettings_ProjectWeeksHint: 'يبدأ الأسبوع 1 من يوم الاثنين لأقدم مهمة لديك — مثالي للعروض التقديمية.',
    GanttSettings_BarStyleSection: 'نمط الأشرطة',
    GanttSettings_BarStyleGradient: 'متدرج',
    GanttSettings_BarStyleFlat: 'مسطح',
    GanttSettings_RowHeightSection: 'ارتفاع الصف',
    GanttSettings_HeightCompact: 'مضغوط',
    GanttSettings_HeightNormal: 'عادي',
    GanttSettings_HeightSpacious: 'واسع',
    GanttSettings_ShowHideSection: 'إظهار / إخفاء',
    GanttSettings_WeekendShading: 'تظليل عطلة نهاية الأسبوع',
    GanttSettings_DependencyArrows: 'أسهم التبعية',
    GanttSettings_CriticalPathAlwaysVisible: 'المسار الحرج مرئي دائمًا',
    GanttSettings_AllOthersOnHoverOnly: 'البقية عند التمرير فقط',
    GanttSettings_CriticalPathHighlight: 'تمييز المسار الحرج',
    GanttSettings_ProgressPercentOnBars: 'نسبة التقدم على الأشرطة',
    GanttSettings_AssigneeNameOnBars: 'اسم المسؤول على الأشرطة',
    GanttSettings_HealthStatusBadges: 'شارات الحالة الصحية',

    // ── List view ──
    ListView_ColTaskName: 'اسم المهمة',
    ListView_ColStatus: 'الحالة',
    ListView_ColHealth: 'الحالة الصحية',
    ListView_ColPriority: 'الأولوية',
    ListView_ColStart: 'البداية',
    ListView_ColDue: 'الاستحقاق',
    ListView_ColAssignedTo: 'مُسند إلى',
    ListView_ColProgress: 'التقدم',
    ListView_ColPhase: 'المرحلة',
    ListView_ColPredecessors: 'السابقات',
    ListView_EmptyTitle: 'لا توجد مهام بعد',
    ListView_AddFirstTask: '+ إضافة أول مهمة',
    ListView_AddTaskRow: '+ إضافة مهمة',
    ListView_Unassigned: 'غير مُسند',
    ListView_DependencyViolationTooltip: 'بدأت قبل اكتمال جميع التبعيات',
    ListView_StatusAriaLabel: 'حالة {taskTitle}',
    ListView_PriorityAriaLabel: 'أولوية {taskTitle}',
    ListView_EditTaskAriaLabel: 'تعديل المهمة {taskTitle}',
    ListView_DeleteTaskAriaLabel: 'حذف المهمة {taskTitle}',
    ListView_EditTitle: 'تعديل',
    ListView_DeleteTitle: 'حذف',

    // ── Kanban view ──
    Kanban_ColumnNotStarted: 'لم تبدأ',
    Kanban_ColumnInProgress: 'قيد التنفيذ',
    Kanban_ColumnOnHold: 'معلقة',
    Kanban_ColumnCompleted: 'مكتملة',
    Kanban_ColumnCancelled: 'ملغاة',
    Kanban_AddTaskButton: '+ إضافة مهمة',
    Kanban_EditTitle: 'تعديل',
    Kanban_DeleteTitle: 'حذف',
    Kanban_CardAriaLabel: '{taskTitle}، {status}. اضغط Enter للتعديل، السهم الأيسر أو الأيمن لتغيير الحالة.',
    Kanban_EditTaskAriaLabel: 'تعديل المهمة {taskTitle}',
    Kanban_DeleteTaskAriaLabel: 'حذف المهمة {taskTitle}',

    // ── Dashboard view ──
    Dashboard_TotalTasks: 'إجمالي المهام',
    Dashboard_Completed: 'مكتملة',
    Dashboard_InProgress: 'قيد التنفيذ',
    Dashboard_OnHold: 'معلقة',
    Dashboard_NotStarted: 'لم تبدأ',
    Dashboard_Cancelled: 'ملغاة',
    Dashboard_OverallProgress: 'التقدم العام',
    Dashboard_ProjectManagerLabel: 'مدير المشروع: {name}',
    Dashboard_PhaseProgressHeader: 'تقدم المراحل',
    Dashboard_StatusBreakdownHeader: 'توزيع الحالة',
    Dashboard_PriorityBreakdownHeader: 'توزيع الأولوية',
    Dashboard_PriorityCritical: 'حرجة',
    Dashboard_PriorityHigh: 'عالية',
    Dashboard_PriorityMedium: 'متوسطة',
    Dashboard_PriorityLow: 'منخفضة',
    Dashboard_OverdueHeader: 'متأخرة  ({count})',
    Dashboard_DueNext14DaysHeader: 'مستحقة خلال 14 يومًا  ({count})',
    Dashboard_CompletedThisWeekHeader: 'اكتملت هذا الأسبوع',
    Dashboard_UpdatedThisWeekHeader: 'تم تحديثها هذا الأسبوع',
    Dashboard_Today: 'اليوم',
    Dashboard_Tomorrow: 'غدًا',
    Dashboard_DaysLeft: '{days}ي',
    Dashboard_EmptyTitle: 'لا توجد مهام بعد',
    Dashboard_EmptySubtitle: 'أضف مهامًا لرؤية لوحة معلومات مشروعك.',
    Dashboard_AddTaskButton: '+ إضافة مهمة',

    // ── Portfolio view ──
    Portfolio_ProjectCount: '{count} مشروع{plural}',
    Portfolio_OnTrackSummary: '{count} على المسار الصحيح',
    Portfolio_AtRiskSummary: '{count} معرضة للخطر',
    Portfolio_OverdueSummary: '{count} متأخرة',
    Portfolio_DoneSummary: '{count} منتهية',
    Portfolio_SortLabel: 'ترتيب:',
    Portfolio_SortAZ: 'أ-ي',
    Portfolio_SortHealth: 'الحالة الصحية',
    Portfolio_SortStatus: 'الحالة',
    Portfolio_SortCompletion: 'الاكتمال',
    Portfolio_RefreshTitle: 'تحديث',
    Portfolio_RefreshButton: 'تحديث',
    Portfolio_LoadingStats: 'جارٍ تحميل الإحصاءات…',
    Portfolio_EmptyTitle: 'لا توجد مشاريع بعد',
    Portfolio_CreateFirstProject: '+ إنشاء أول مشروع',
    Portfolio_StatsUnavailable: 'الإحصاءات غير متاحة',
    Portfolio_StatsUnavailableDetail: 'تعذر تحميل إحصاءات هذا المشروع.',
    Portfolio_OverallProgressLabel: 'التقدم العام',
    Portfolio_TaskCountDone: 'منتهية',
    Portfolio_TaskCountActive: 'نشطة',
    Portfolio_TaskCountAtRisk: 'معرضة للخطر',
    Portfolio_TaskCountOverdue: 'متأخرة',
    Portfolio_ViewGanttLink: 'عرض جانت ←',
    Portfolio_TodayTooltip: 'اليوم',

    // ── Task panel ──
    TaskPanel_EditHeader: 'تعديل: {taskTitle}',
    TaskPanel_NewTaskHeader: 'مهمة جديدة',
    TaskPanel_TabBasic: 'أساسي',
    TaskPanel_TabDetails: 'تفاصيل',
    TaskPanel_TabLinks: 'الروابط',
    TaskPanel_ProjectLabelPrefix: 'المشروع: ',
    TaskPanel_TaskNameLabel: 'اسم المهمة',
    TaskPanel_TaskNamePlaceholder: 'أدخل اسم المهمة',
    TaskPanel_TaskNameRequired: 'اسم المهمة مطلوب',
    TaskPanel_DescriptionLabel: 'الوصف',
    TaskPanel_DescriptionPlaceholder: 'أدخل الوصف',
    TaskPanel_StartDateLabel: 'تاريخ البدء',
    TaskPanel_DueDateLabel: 'تاريخ الاستحقاق',
    TaskPanel_DueDateError: 'يجب أن يكون تاريخ الاستحقاق في تاريخ البدء أو بعده',
    TaskPanel_StatusLabel: 'الحالة',
    TaskPanel_PriorityLabel: 'الأولوية',
    TaskPanel_PercentCompleteLabel: 'نسبة الاكتمال: {percent}%',
    TaskPanel_AssignedToLabel: 'مُسند إلى',
    TaskPanel_AssignedToPlaceholder: 'البحث عن أشخاص…',
    TaskPanel_PhaseLabel: 'المرحلة',
    TaskPanel_PhasePlaceholder: 'أدخل اسم المرحلة',
    TaskPanel_PhaseHint: 'يجمع المهام معًا في عرضي جانت والقائمة.',
    TaskPanel_MilestoneLabel: 'معلم رئيسي',
    TaskPanel_MilestoneOnText: 'نعم',
    TaskPanel_MilestoneOffText: 'لا',
    TaskPanel_CustomBarColorLabel: 'لون شريط مخصص',
    TaskPanel_CustomBarColorOptionalSuffix: ' (اختياري)',
    TaskPanel_AutoColorHint: 'لون تلقائي من إعدادات الحالة/الأولوية/المرحلة.',
    TaskPanel_NotesLabel: 'ملاحظات',
    TaskPanel_NotesPlaceholder: 'أدخل الملاحظات',
    TaskPanel_ParentTaskLabel: 'المهمة الرئيسية',
    TaskPanel_ParentTaskNone: '(لا شيء)',
    TaskPanel_ParentTaskHasChildrenHint: 'هذه المهمة لديها مهام فرعية ولا يمكن أن يكون لها مهمة رئيسية خاصة بها.',
    TaskPanel_ParentTaskHint: 'ضمّن هذه المهمة تحت أخرى كمهمة فرعية.',
    TaskPanel_DependsOnLabel: 'تعتمد على',
    TaskPanel_RemoveDependencyTitle: 'إزالة الاعتماد على "{taskTitle}"',
    TaskPanel_AddDependencyPlaceholder: 'إضافة تبعية…',
    TaskPanel_SelectATaskOption: 'اختر مهمة…',
    TaskPanel_DependsOnHint: 'لا يمكن أن تبدأ المهمة حتى تكتمل هذه المهام.',
    TaskPanel_SavingLabel: 'جارٍ الحفظ…',
    TaskPanel_CreatingLabel: 'جارٍ الإنشاء…',
    TaskPanel_SaveChangesButton: 'حفظ التغييرات',
    TaskPanel_CreateTaskButton: 'إنشاء مهمة',
    TaskPanel_CancelButton: 'إلغاء',
    TaskPanel_DismissAriaLabel: 'إغلاق',
    TaskPanel_DiscardUnsavedChangesConfirm: 'هل تريد تجاهل التغييرات غير المحفوظة؟',
    TaskPanel_SaveFallbackError: 'تعذر حفظ المهمة.',

    // ── Project panel ──
    ProjectPanel_EditHeader: 'تعديل المشروع',
    ProjectPanel_NewHeader: 'مشروع جديد',
    ProjectPanel_ProjectNameLabel: 'اسم المشروع',
    ProjectPanel_ProjectNamePlaceholder: 'أدخل اسم المشروع',
    ProjectPanel_ProjectNameRequired: 'اسم المشروع مطلوب',
    ProjectPanel_DescriptionLabel: 'الوصف',
    ProjectPanel_DescriptionPlaceholder: 'أدخل الوصف',
    ProjectPanel_ProjectColorLabel: 'لون المشروع',
    ProjectPanel_StatusLabel: 'الحالة',
    ProjectPanel_StartDateLabel: 'تاريخ البدء',
    ProjectPanel_DueDateLabel: 'تاريخ الاستحقاق',
    ProjectPanel_DueDateError: 'يجب أن يكون تاريخ الاستحقاق في تاريخ البدء أو بعده',
    ProjectPanel_WhatHappensNextTitle: 'ماذا يحدث بعد ذلك؟',
    ProjectPanel_WhatHappensNextBody: 'ستتمكن من إضافة المهام وإعداد المراحل وتتبع التقدم بمجرد إنشاء المشروع.',
    ProjectPanel_SavingLabel: 'جارٍ الحفظ…',
    ProjectPanel_CreatingLabel: 'جارٍ الإنشاء…',
    ProjectPanel_SaveChangesButton: 'حفظ التغييرات',
    ProjectPanel_CreateProjectButton: 'إنشاء المشروع',
    ProjectPanel_CancelButton: 'إلغاء',
    ProjectPanel_DismissAriaLabel: 'إغلاق',
    ProjectPanel_DiscardUnsavedChangesConfirm: 'هل تريد تجاهل التغييرات غير المحفوظة؟',
    ProjectPanel_SaveFallbackError: 'تعذر حفظ المشروع.',

    // ── Import panel ──
    ImportPanel_SourceExcelTitle: 'ملف Excel / CSV',
    ImportPanel_SourceExcelSubtitle: 'استيراد المهام من جدول بيانات',
    ImportPanel_SourcePlannerTitle: 'Microsoft Planner',
    ImportPanel_SourcePlannerSubtitle: 'استيراد المهام من خطة Planner',
    ImportPanel_ClickToBrowse: 'انقر للتصفح',
    ImportPanel_DragDropSuffix: ' أو اسحب وأفلت',
    ImportPanel_SupportedExtensions: 'يدعم .xlsx، .xls، .csv',
    ImportPanel_RowsColsSummary: 'تم اكتشاف {rows} صفوف، {cols} أعمدة',
    ImportPanel_LoadingPlannerPlans: 'جارٍ تحميل خطط Planner…',
    ImportPanel_PlannerLoadError: 'تعذر تحميل خطط Planner.',
    ImportPanel_PlannerPermissionsHintPrefix: 'تأكد من أن لديك وصولاً إلى Planner وأن ',
    ImportPanel_PlannerPermissionsHintEmphasis: 'المهام بواسطة Planner و To Do',
    ImportPanel_PlannerPermissionsHintSuffix: ' متاحة لهذا الموقع.',
    ImportPanel_NoPlannerPlansFoundTitle: 'لم يتم العثور على خطط Planner',
    ImportPanel_NoPlannerPlansFoundBody: 'قد لا يكون لديك وصول إلى أي خطط Planner، أو لا توجد خطط لهذا الحساب.',
    ImportPanel_TaskCountFoundIn: 'تم العثور على {count} مهمة في "{planName}"',
    ImportPanel_ProjectDetailsIntroPrefix: 'الاستيراد إلى ',
    ImportPanel_ProjectDetailsIntroSuffix: '. راجع تفاصيل المشروع أدناه.',
    ImportPanel_ProjectNameLabel: 'اسم المشروع',
    ImportPanel_DescriptionLabel: 'الوصف',
    ImportPanel_StatusLabel: 'الحالة',
    ImportPanel_ColorLabel: 'اللون',
    ImportPanel_MapIntro: 'قم بربط الأعمدة من ملفك بحقول المهام.',
    ImportPanel_CreatingProjectStatus: 'جارٍ إنشاء المشروع…',
    ImportPanel_ImportingTasksStatus: 'جارٍ استيراد المهام…',
    ImportPanel_ProgressLabel: '{done} من {total}',
    ImportPanel_CouldNotCreateProject: 'تعذر إنشاء المشروع.',
    ImportPanel_ImportCompletedWithErrors: 'اكتمل الاستيراد مع {count} خطأ (أخطاء).',
    ImportPanel_ProjectCreatedSuccess: 'تم إنشاء المشروع بنجاح!',
    ImportPanel_ImportSuccessful: 'تم الاستيراد بنجاح!',
    ImportPanel_TasksAddedTo: 'تمت إضافة {count} مهمة إلى "{projectName}"',
    ImportPanel_FailedRowsLabel: 'الصفوف الفاشلة:',
    ImportPanel_CloseButton: 'إغلاق',
    ImportPanel_OpenProjectButton: 'فتح المشروع',
    ImportPanel_ViewImportedTasksButton: 'عرض المهام المستوردة',
    ImportPanel_NextMapColumnsButton: 'التالي: ربط الأعمدة',
    ImportPanel_ImportNTasksButton: 'استيراد {count} مهمة',
    ImportPanel_BackButton: 'رجوع',
    ImportPanel_CancelButton: 'إلغاء',
    ImportPanel_NextButton: 'التالي',
    ImportPanel_StepSource: 'المصدر',
    ImportPanel_StepProject: 'المشروع',
    ImportPanel_StepMap: 'الربط',
    ImportPanel_StepImport: 'الاستيراد',
    ImportPanel_StepDone: 'تم',
    ImportPanel_ImportAsNewProjectHeader: 'استيراد ملف كمشروع جديد',
    ImportPanel_ImportIntoProjectHeader: 'استيراد المهام إلى {projectName}',
    ImportPanel_CouldNotParseFile: 'تعذر تحليل الملف.',
    ImportPanel_CouldNotLoadPlannerTasks: 'تعذر تحميل المهام من هذه الخطة.',
    ImportPanel_CouldNotCreateProjectDetail: 'تعذر إنشاء المشروع: {detail}',
    ImportPanel_CouldNotLinkDependencies: 'تعذر ربط التبعيات: {detail}',
    ImportPanel_UnknownError: 'خطأ غير معروف',

    // ── Column mapper (import) ──
    ColumnMapper_TaskNameRequiredBanner: 'يجب ربط اسم المهمة للمتابعة.',
    ColumnMapper_SkippedColumnsBanner: 'سيتم تخطي {count} عمود (أعمدة).',
    ColumnMapper_SourceColumnHeader: 'عمود المصدر',
    ColumnMapper_TargetFieldHeader: 'الحقل الهدف',
    ColumnMapper_StatusHeader: 'الحالة',
    ColumnMapper_SkippedBadge: 'تم التخطي',
    ColumnMapper_AutoMappedBadge: 'ربط تلقائي',
    ColumnMapper_SetBadge: 'محدد',
    ColumnMapper_PreviewTitle: 'معاينة: {columnName}',
    ColumnMapper_EmptyCellDash: '—',

    // ── Import field display names / ImportService ──
    ImportField_TaskName: 'اسم المهمة',
    ImportField_StartDate: 'تاريخ البدء',
    ImportField_DueDate: 'تاريخ الاستحقاق',
    ImportField_Status: 'الحالة',
    ImportField_Priority: 'الأولوية',
    ImportField_AssignedTo: 'مُسند إلى',
    ImportField_AssignedToEmail: 'البريد الإلكتروني للمسؤول',
    ImportField_PercentComplete: 'نسبة الاكتمال',
    ImportField_Phase: 'المرحلة',
    ImportField_Description: 'الوصف',
    ImportField_Notes: 'ملاحظات',
    ImportField_IsMilestone: 'معلم رئيسي',
    ImportField_Dependencies: 'التبعيات',
    ImportField_SkipColumn: '(تخطي هذا العمود)',
    ImportService_EmptyFileError: 'يبدو أن الملف فارغ أو لا يحتوي على صفوف بيانات.',
    ImportService_ReadErrorDetail: 'تعذر قراءة الملف: {detail}.',
    ImportService_FileReadError: 'خطأ في قراءة الملف.',
    ImportService_RowError: 'الصف {rowNum} ("{title}"): {error}',
    ImportService_AmbiguousDependency: 'التبعية "{name}" تطابق أكثر من عنوان مهمة واحد — تم التخطي.',
    ImportService_LinkDependencyError: 'تعذر ربط التبعيات للمهمة {taskId}: {error}',

    // ── Health labels (shared: healthUtils.ts and ExportService.ts both use this set; also replaces the duplicated Export_PortfolioHealthLabel* keys) ──
    Health_Done: 'منتهية',
    Health_OnTrack: 'على المسار الصحيح',
    Health_AtRisk: 'معرضة للخطر',
    Health_Overdue: 'متأخرة',

    // ── Status / Priority display labels (DISPLAY-ONLY — stored SharePoint Choice values remain unchanged/English) ──
    Status_NotStarted: 'لم تبدأ',
    Status_InProgress: 'قيد التنفيذ',
    Status_Completed: 'مكتملة',
    Status_OnHold: 'معلقة',
    Status_Cancelled: 'ملغاة',
    Priority_Critical: 'حرجة',
    Priority_High: 'عالية',
    Priority_Medium: 'متوسطة',
    Priority_Low: 'منخفضة',
    ProjectStatus_Planning: 'التخطيط',
    ProjectStatus_Active: 'نشط',
    ProjectStatus_OnHold: 'معلق',
    ProjectStatus_Completed: 'مكتمل',
    ProjectStatus_Cancelled: 'ملغى',

    // ── Shell (SmartGantt.tsx) ──
    SmartGantt_LoadingProjects: 'جارٍ تحميل المشاريع…',
    SmartGantt_UnableToLoad: 'تعذر التحميل',
    SmartGantt_RetryButton: 'إعادة المحاولة',
    SmartGantt_NoProjectsYet: 'لا توجد مشاريع بعد',
    SmartGantt_NoProjectsSubtitle: 'أنشئ مشروعك الأول للبدء.',
    SmartGantt_CreateFirstProjectButton: '+ إنشاء أول مشروع',
    SmartGantt_ImportFromExcelButton: '📥 استيراد من Excel',
    SmartGantt_LoadingTasks: 'جارٍ تحميل المهام…',
    SmartGantt_DismissAriaLabel: 'إغلاق',
    SmartGantt_DeleteTaskDialogTitle: 'حذف المهمة',
    SmartGantt_DeleteTaskDialogSubtext: 'هل أنت متأكد أنك تريد حذف "{taskTitle}"؟ لا يمكن التراجع عن هذا الإجراء.',
    SmartGantt_DeleteButton: 'حذف',
    SmartGantt_CancelButton: 'إلغاء',
    SmartGantt_ArchiveProjectDialogTitle: 'أرشفة المشروع',
    SmartGantt_ArchiveProjectDialogSubtext: 'أرشفة "{projectTitle}"؟ يمكنك إلغاء أرشفته لاحقًا.',
    SmartGantt_ArchiveButton: 'أرشفة',
    SmartGantt_SendToRecycleBinDialogTitle: 'نقل إلى سلة المحذوفات',
    SmartGantt_SendToRecycleBinDialogSubtext: 'نقل "{projectTitle}" إلى سلة محذوفات الموقع؟',
    SmartGantt_SendToRecycleBinButton: 'نقل إلى سلة المحذوفات',
    SmartGantt_FailedLoadProjects: 'فشل تحميل المشاريع. تحقق من أذونات الموقع.',
    SmartGantt_FailedLoadTasks: 'فشل تحميل المهام لهذا المشروع.',
    SmartGantt_FailedLoadPortfolioStats: 'فشل تحميل إحصاءات المحفظة.',
    SmartGantt_CouldNotSaveProject: 'تعذر حفظ المشروع: {message}',
    SmartGantt_CouldNotDeleteProject: 'تعذر حذف المشروع: {message}',
    SmartGantt_CouldNotArchiveProject: 'تعذر أرشفة المشروع: {message}',
    SmartGantt_CouldNotUnarchiveProject: 'تعذر إلغاء أرشفة المشروع: {message}',
    SmartGantt_CouldNotSaveTask: 'تعذر حفظ المهمة: {message}',
    SmartGantt_CouldNotDeleteTask: 'تعذر حذف المهمة: {message}',
    SmartGantt_ImageExportFailed: 'فشل تصدير الصورة: {message}',
    SmartGantt_PowerPointExportFailed: 'فشل تصدير PowerPoint: {message}',
    SmartGantt_PortfolioExportFailed: 'فشل تصدير المحفظة: {message}',
    SmartGantt_CouldNotUpdateTask: 'تعذر تحديث المهمة: {message}',

    // ── Common ──
    ColorSwatch_AutoColorAriaLabel: 'لون تلقائي',
    ColorSwatch_CustomColorAriaLabel: 'لون مخصص',
    ColorSwatch_PickCustomColorTitle: 'اختر لونًا مخصصًا',

    // ── Export (Excel / PowerPoint) ──
    Export_ColTaskName: 'اسم المهمة',
    Export_ColPhase: 'المرحلة',
    Export_ColStartDate: 'تاريخ البدء',
    Export_ColDueDate: 'تاريخ الاستحقاق',
    Export_ColStatus: 'الحالة',
    Export_ColPriority: 'الأولوية',
    Export_ColAssignedTo: 'مُسند إلى',
    Export_ColAssignedToEmail: 'البريد الإلكتروني للمسؤول',
    Export_ColPercentComplete: 'نسبة الاكتمال',
    Export_ColIsMilestone: 'معلم رئيسي',
    Export_ColDescription: 'الوصف',
    Export_ColNotes: 'ملاحظات',
    Export_Yes: 'نعم',
    Export_No: 'لا',
    Export_SheetNameTasks: 'المهام',
    Export_ExcelFileSuffix: ' - المهام.xlsx',
    Export_TaskNameColumnLabel: 'اسم المهمة',
    Export_ExportedDateLabel: 'تم التصدير في {date}',
    Export_ProjectReportLabel: 'تقرير المشروع',
    Export_StatusLine: 'الحالة: {status}',
    Export_DateRangeSeparator: ' إلى ',
    Export_ProjectManagerLine: 'مدير المشروع: {name}',
    Export_GeneratedDateLine: 'تم الإنشاء في {date}',
    Export_ProjectSummaryTitle: 'ملخص المشروع',
    Export_StatTotalTasks: 'إجمالي المهام',
    Export_StatCompleted: 'مكتملة',
    Export_StatInProgress: 'قيد التنفيذ',
    Export_StatOnHold: 'معلقة',
    Export_StatNotStarted: 'لم تبدأ',
    Export_OverallProgressLine: 'التقدم العام',
    Export_OverallProgressPercent: '{percent}%',
    Export_StatusBreakdownTitle: 'توزيع الحالة',
    Export_StatusBreakdownRow: '{status}: {count} ({percent}%)',
    Export_GanttTimelineTitle: 'الجدول الزمني لجانت',
    Export_SummaryRecentActivityTitle: 'النشاط الأخير',
    Export_ProjectOverviewLabel: 'نظرة عامة على المشروع',
    Export_DetailStatusLabel: 'الحالة',
    Export_DetailStartDateLabel: 'تاريخ البدء',
    Export_DetailDueDateLabel: 'تاريخ الاستحقاق',
    Export_DetailProjectManagerLabel: 'مدير المشروع',
    Export_Past7DaysLabel: 'آخر 7 أيام',
    Export_NoActivityMessage: 'لا يوجد نشاط حديث.',
    Export_CompletedThisWeekHeader: 'اكتملت هذا الأسبوع ({count})',
    Export_NewBadge: 'جديد  ',
    Export_CompletedPercentLine: 'اكتمال {percent}%',
    Export_MoreItemsSuffix: '+ {count} أخرى',
    Export_InProgressUpdatedHeader: 'قيد التنفيذ / تم تحديثها',
    Export_StatusPercentLine: '{status} — {percent}%',
    Export_PortfolioReportLabel: 'تقرير المحفظة',
    Export_PortfolioOverviewTitle: 'نظرة عامة على المحفظة',
    Export_ProjectsCountLine: '{count} مشروع',
    Export_HealthSummaryOnTrack: '{count} على المسار الصحيح',
    Export_HealthSummaryAtRisk: '{count} معرضة للخطر',
    Export_HealthSummaryOverdue: '{count} متأخرة',
    Export_ProjectsSummaryHeader: 'ملخص المشاريع',
    Export_TableProject: 'المشروع',
    Export_TableStatus: 'الحالة',
    Export_TableHealth: 'الحالة الصحية',
    Export_TableTotal: 'الإجمالي',
    Export_TableDone: 'منتهية',
    Export_TableActive: 'نشطة',
    Export_TableAtRisk: 'معرضة للخطر',
    Export_TableOverdue: 'متأخرة',
    Export_TablePctDone: 'نسبة الاكتمال',
    Export_TableDueDate: 'تاريخ الاستحقاق',
    Export_PortfolioSummaryFileName: 'ملخص المحفظة.xlsx',
    Export_PortfolioReportFileName: 'تقرير المحفظة.pptx',
    Export_ProjectReportFileName: 'تقرير {projectName}.pptx',
    Export_UnavailableLabel: 'غير متاح',
    Export_SheetNamePortfolio: 'المحفظة',
    Export_ColStart: 'البداية',
    Export_ColDue: 'الاستحقاق',
    Export_ImageGenerationFailed: 'تعذر إنشاء الصورة — قد يكون الرسم البياني كبيرًا جدًا للتصدير كصورة.',
    Export_DrawingContextFailed: 'تعذر إنشاء سياق رسم للتصدير.',
    Export_SvgRenderFailed: 'فشل عرض SVG',
  };
});
