define([], function () {
  return {
    // ── Property pane ──
    PropertyPane_HeaderDescription: 'Nastavení Smart Gantt Chart',
    PropertyPane_GeneralGroupName: 'Obecné',
    PropertyPane_TitleFieldLabel: 'Název webové části',
    WebPart_DefaultTitle: 'Smart Gantt Chart',

    // ── Toolbar ──
    Toolbar_ViewDashboard: 'Přehled',
    Toolbar_ViewList: 'Seznam',
    Toolbar_ViewGantt: 'Gantt',
    Toolbar_ViewKanban: 'Kanban',
    Toolbar_ZoomDay: 'Den',
    Toolbar_ZoomWeek: 'Týden',
    Toolbar_ZoomMonth: 'Měsíc',
    Toolbar_ZoomQuarter: 'Čtvrtletí',
    Toolbar_SelectProjectAriaLabel: 'Vybrat projekt',
    Toolbar_PortfolioLabel: 'Portfolio',
    Toolbar_SelectAProject: 'Vyberte projekt',
    Toolbar_AllProjectsSubtext: 'Všechny projekty',
    Toolbar_NoProjectsYet: 'Zatím žádné projekty',
    Toolbar_ArchivedBadge: 'Archivováno',
    Toolbar_ShowArchivedProjects: 'Zobrazit archivované projekty',
    Toolbar_NewProject: '+ Nový projekt',
    Toolbar_ImportFileAsNewProject: '📥 Importovat soubor jako nový projekt…',
    Toolbar_AddTask: '+ Přidat úkol',
    Toolbar_EditProject: 'Upravit projekt',
    Toolbar_OptionsButton: '⚙ Možnosti',
    Toolbar_MoreOptionsTitle: 'Další možnosti',
    Toolbar_ExportToExcel: '📊 Exportovat do Excelu',
    Toolbar_ExportToPowerPoint: '📑 Exportovat do PowerPointu',
    Toolbar_ScrollToTodayTitle: 'Přejít na dnešek',
    Toolbar_TodayButton: '◉ Dnes',
    Toolbar_ImportTasks: '📥 Importovat úkoly…',
    Toolbar_ExportAsImage: '🖼 Exportovat jako obrázek (PNG)',
    Toolbar_UnarchiveProject: '📂 Obnovit projekt z archivu',
    Toolbar_ArchiveProject: '🗄️ Archivovat projekt',
    Toolbar_SendToRecycleBin: '🗑️ Přesunout do koše',

    // ── Filter bar ──
    FilterBar_ClearOption: 'Vymazat',
    FilterBar_DueAny: 'Libovolný termín',
    FilterBar_DueOverdue: 'Po termínu',
    FilterBar_DueToday: 'Termín dnes',
    FilterBar_DueWeek: 'Termín do 7 dnů',
    FilterBar_SearchPlaceholder: 'Hledat úkoly…',
    FilterBar_SearchAriaLabel: 'Hledat úkoly',
    FilterBar_StatusChipLabel: 'Stav',
    FilterBar_PriorityChipLabel: 'Priorita',
    FilterBar_AssigneeChipLabel: 'Přiřazeno',
    FilterBar_PhaseChipLabel: 'Fáze',
    FilterBar_DueDateAriaLabel: 'Filtrovat podle termínu splnění',
    FilterBar_MatchCount: '{matchCount} z {totalCount}',
    FilterBar_ClearFilters: '✕ Vymazat filtry',
    FilterBar_ChipLabelWithCount: '{label} ({count}) ▾',
    FilterBar_ChipLabelNoCount: '{label} ▾',

    // ── Gantt view ──
    Gantt_TaskColumnHeader: 'Úkol',
    Gantt_DurationColumnHeader: 'Trvání',
    Gantt_AddTaskButton: '+ Přidat úkol',
    Gantt_EmptyTitle: 'Zatím žádné úkoly',
    Gantt_EmptySubtitle: 'Přidejte úkoly, abyste je viděli v Ganttově diagramu.',
    Gantt_AddFirstTask: '+ Přidat první úkol',
    Gantt_ImportTasksButton: '📥 Importovat úkoly',
    Gantt_EditTitle: 'Upravit',
    Gantt_DeleteTitle: 'Smazat',
    Gantt_EditTaskAriaLabel: 'Upravit úkol {taskTitle}',
    Gantt_DeleteTaskAriaLabel: 'Smazat úkol {taskTitle}',
    Gantt_ExpandPhaseAriaLabel: '{action} fázi {phase}',
    Gantt_ExpandAction: 'Rozbalit',
    Gantt_CollapseAction: 'Sbalit',
    Gantt_DependencyViolationTooltip: 'Zahájeno dříve, než byly dokončeny všechny závislosti',
    Gantt_MilestoneAriaLabel: '{taskTitle}, milník, {date}',
    Gantt_BarAriaLabel: '{taskTitle}, {startDate} až {dueDate}, dokončeno na {percent} %',
    Gantt_PercentCompleteTooltip: 'Dokončeno na {value} %',

    // ── Gantt options/settings panel ──
    GanttSettings_PanelHeader: '⚙ Možnosti',
    GanttSettings_ColorCodingSection: 'Barevné rozlišení',
    GanttSettings_ByStatus: 'Podle stavu',
    GanttSettings_ByPriority: 'Podle priority',
    GanttSettings_ByPhase: 'Podle fáze',
    GanttSettings_ByHealth: 'Podle zdraví projektu',
    GanttSettings_HeaderColorSection: 'Barva záhlaví',
    GanttSettings_ThemeDark: 'Tmavá',
    GanttSettings_ThemeNavy: 'Námořnická modrá',
    GanttSettings_ThemeTeal: 'Petrolejová',
    GanttSettings_ThemePurple: 'Fialová',
    GanttSettings_ThemeLight: 'Světlá',
    GanttSettings_HeaderLabelsSection: 'Popisky záhlaví',
    GanttSettings_WeekLabelDates: 'Data',
    GanttSettings_WeekLabelDatesDesc: '3. čvn, 10. čvn…',
    GanttSettings_WeekLabelProject: 'Týdny projektu',
    GanttSettings_WeekLabelProjectDesc: 'T1, T2…',
    GanttSettings_WeekLabelIso: 'Kalendářní týdny',
    GanttSettings_WeekLabelIsoDesc: 'T23, T24…',
    GanttSettings_ProjectWeeksHint: 'Týden 1 začíná pondělím vašeho nejdřívějšího úkolu — ideální pro prezentace.',
    GanttSettings_BarStyleSection: 'Styl pruhů',
    GanttSettings_BarStyleGradient: 'Přechod',
    GanttSettings_BarStyleFlat: 'Plná barva',
    GanttSettings_RowHeightSection: 'Výška řádku',
    GanttSettings_HeightCompact: 'Kompaktní',
    GanttSettings_HeightNormal: 'Normální',
    GanttSettings_HeightSpacious: 'Prostorná',
    GanttSettings_ShowHideSection: 'Zobrazit / skrýt',
    GanttSettings_WeekendShading: 'Zvýraznění víkendů',
    GanttSettings_DependencyArrows: 'Šipky závislostí',
    GanttSettings_CriticalPathAlwaysVisible: 'Kritická cesta vždy viditelná',
    GanttSettings_AllOthersOnHoverOnly: 'Ostatní pouze při najetí myší',
    GanttSettings_CriticalPathHighlight: 'Zvýraznění kritické cesty',
    GanttSettings_ProgressPercentOnBars: 'Procento postupu na pruzích',
    GanttSettings_AssigneeNameOnBars: 'Jméno řešitele na pruzích',
    GanttSettings_HealthStatusBadges: 'Odznaky stavu zdraví',

    // ── List view ──
    ListView_ColTaskName: 'Název úkolu',
    ListView_ColStatus: 'Stav',
    ListView_ColHealth: 'Zdraví',
    ListView_ColPriority: 'Priorita',
    ListView_ColStart: 'Zahájení',
    ListView_ColDue: 'Termín',
    ListView_ColAssignedTo: 'Přiřazeno komu',
    ListView_ColProgress: 'Postup',
    ListView_ColPhase: 'Fáze',
    ListView_ColPredecessors: 'Předchůdci',
    ListView_EmptyTitle: 'Zatím žádné úkoly',
    ListView_AddFirstTask: '+ Přidat první úkol',
    ListView_AddTaskRow: '+ Přidat úkol',
    ListView_Unassigned: 'Nepřiřazeno',
    ListView_DependencyViolationTooltip: 'Zahájeno dříve, než byly dokončeny všechny závislosti',
    ListView_StatusAriaLabel: 'Stav úkolu {taskTitle}',
    ListView_PriorityAriaLabel: 'Priorita úkolu {taskTitle}',
    ListView_EditTaskAriaLabel: 'Upravit úkol {taskTitle}',
    ListView_DeleteTaskAriaLabel: 'Smazat úkol {taskTitle}',
    ListView_EditTitle: 'Upravit',
    ListView_DeleteTitle: 'Smazat',

    // ── Kanban view ──
    Kanban_ColumnNotStarted: 'Nezahájeno',
    Kanban_ColumnInProgress: 'Probíhá',
    Kanban_ColumnOnHold: 'Pozastaveno',
    Kanban_ColumnCompleted: 'Dokončeno',
    Kanban_ColumnCancelled: 'Zrušeno',
    Kanban_AddTaskButton: '+ Přidat úkol',
    Kanban_EditTitle: 'Upravit',
    Kanban_DeleteTitle: 'Smazat',
    Kanban_CardAriaLabel: '{taskTitle}, {status}. Stiskněte Enter pro úpravu, šipkou vlevo nebo vpravo změníte stav.',
    Kanban_EditTaskAriaLabel: 'Upravit úkol {taskTitle}',
    Kanban_DeleteTaskAriaLabel: 'Smazat úkol {taskTitle}',

    // ── Dashboard view ──
    Dashboard_TotalTasks: 'Celkem úkolů',
    Dashboard_Completed: 'Dokončeno',
    Dashboard_InProgress: 'Probíhá',
    Dashboard_OnHold: 'Pozastaveno',
    Dashboard_NotStarted: 'Nezahájeno',
    Dashboard_Cancelled: 'Zrušeno',
    Dashboard_OverallProgress: 'Celkový postup',
    Dashboard_ProjectManagerLabel: 'Projektový manažer: {name}',
    Dashboard_PhaseProgressHeader: 'Postup podle fází',
    Dashboard_StatusBreakdownHeader: 'Rozdělení podle stavu',
    Dashboard_PriorityBreakdownHeader: 'Rozdělení podle priority',
    Dashboard_PriorityCritical: 'Kritická',
    Dashboard_PriorityHigh: 'Vysoká',
    Dashboard_PriorityMedium: 'Střední',
    Dashboard_PriorityLow: 'Nízká',
    Dashboard_OverdueHeader: 'Po termínu  ({count})',
    Dashboard_DueNext14DaysHeader: 'Termín do 14 dnů  ({count})',
    Dashboard_CompletedThisWeekHeader: 'Dokončeno tento týden',
    Dashboard_UpdatedThisWeekHeader: 'Aktualizováno tento týden',
    Dashboard_Today: 'Dnes',
    Dashboard_Tomorrow: 'Zítra',
    Dashboard_DaysLeft: '{days} d',
    Dashboard_EmptyTitle: 'Zatím žádné úkoly',
    Dashboard_EmptySubtitle: 'Přidejte úkoly, abyste viděli přehled projektu.',
    Dashboard_AddTaskButton: '+ Přidat úkol',

    // ── Portfolio view ──
    Portfolio_ProjectCount: '{count} projekt{plural}',
    Portfolio_OnTrackSummary: '{count} podle plánu',
    Portfolio_AtRiskSummary: '{count} v ohrožení',
    Portfolio_OverdueSummary: '{count} po termínu',
    Portfolio_DoneSummary: '{count} dokončeno',
    Portfolio_SortLabel: 'Řadit:',
    Portfolio_SortAZ: 'A-Z',
    Portfolio_SortHealth: 'Zdraví',
    Portfolio_SortStatus: 'Stav',
    Portfolio_SortCompletion: 'Dokončení',
    Portfolio_RefreshTitle: 'Obnovit',
    Portfolio_RefreshButton: 'Obnovit',
    Portfolio_LoadingStats: 'Načítání statistik…',
    Portfolio_EmptyTitle: 'Zatím žádné projekty',
    Portfolio_CreateFirstProject: '+ Vytvořit první projekt',
    Portfolio_StatsUnavailable: 'Statistiky nejsou k dispozici',
    Portfolio_StatsUnavailableDetail: 'Nepodařilo se načíst statistiky pro tento projekt.',
    Portfolio_OverallProgressLabel: 'Celkový postup',
    Portfolio_TaskCountDone: 'Dokončeno',
    Portfolio_TaskCountActive: 'Aktivní',
    Portfolio_TaskCountAtRisk: 'V ohrožení',
    Portfolio_TaskCountOverdue: 'Po termínu',
    Portfolio_ViewGanttLink: 'Zobrazit Gantt →',
    Portfolio_TodayTooltip: 'Dnes',

    // ── Task panel ──
    TaskPanel_EditHeader: 'Upravit: {taskTitle}',
    TaskPanel_NewTaskHeader: 'Nový úkol',
    TaskPanel_TabBasic: 'Základní',
    TaskPanel_TabDetails: 'Podrobnosti',
    TaskPanel_TabLinks: 'Odkazy',
    TaskPanel_ProjectLabelPrefix: 'Projekt: ',
    TaskPanel_TaskNameLabel: 'Název úkolu',
    TaskPanel_TaskNamePlaceholder: 'Zadejte název úkolu',
    TaskPanel_TaskNameRequired: 'Název úkolu je povinný',
    TaskPanel_DescriptionLabel: 'Popis',
    TaskPanel_DescriptionPlaceholder: 'Zadejte popis',
    TaskPanel_StartDateLabel: 'Datum zahájení',
    TaskPanel_DueDateLabel: 'Termín splnění',
    TaskPanel_DueDateError: 'Termín splnění musí být stejný nebo pozdější než datum zahájení',
    TaskPanel_StatusLabel: 'Stav',
    TaskPanel_PriorityLabel: 'Priorita',
    TaskPanel_PercentCompleteLabel: '% dokončeno: {percent} %',
    TaskPanel_AssignedToLabel: 'Přiřazeno komu',
    TaskPanel_AssignedToPlaceholder: 'Hledat osoby…',
    TaskPanel_PhaseLabel: 'Fáze',
    TaskPanel_PhasePlaceholder: 'Zadejte název fáze',
    TaskPanel_PhaseHint: 'Seskupuje úkoly v zobrazeních Gantt a Seznam.',
    TaskPanel_MilestoneLabel: 'Milník',
    TaskPanel_MilestoneOnText: 'Ano',
    TaskPanel_MilestoneOffText: 'Ne',
    TaskPanel_CustomBarColorLabel: 'Vlastní barva pruhu',
    TaskPanel_CustomBarColorOptionalSuffix: ' (volitelné)',
    TaskPanel_AutoColorHint: 'Automatická barva podle nastavení stavu/priority/fáze.',
    TaskPanel_NotesLabel: 'Poznámky',
    TaskPanel_NotesPlaceholder: 'Zadejte poznámky',
    TaskPanel_ParentTaskLabel: 'Nadřazený úkol',
    TaskPanel_ParentTaskNone: '(žádný)',
    TaskPanel_ParentTaskHasChildrenHint: 'Tento úkol má podúkoly a nemůže mít vlastní nadřazený úkol.',
    TaskPanel_ParentTaskHint: 'Vnořte tento úkol pod jiný jako podúkol.',
    TaskPanel_DependsOnLabel: 'Závisí na',
    TaskPanel_RemoveDependencyTitle: 'Odebrat závislost na "{taskTitle}"',
    TaskPanel_AddDependencyPlaceholder: 'Přidat závislost…',
    TaskPanel_SelectATaskOption: 'Vyberte úkol…',
    TaskPanel_DependsOnHint: 'Úkol nelze zahájit, dokud nejsou tyto dokončeny.',
    TaskPanel_SavingLabel: 'Ukládání…',
    TaskPanel_CreatingLabel: 'Vytváření…',
    TaskPanel_SaveChangesButton: 'Uložit změny',
    TaskPanel_CreateTaskButton: 'Vytvořit úkol',
    TaskPanel_CancelButton: 'Zrušit',
    TaskPanel_DismissAriaLabel: 'Zavřít',
    TaskPanel_DiscardUnsavedChangesConfirm: 'Zahodit neuložené změny?',
    TaskPanel_SaveFallbackError: 'Úkol se nepodařilo uložit.',

    // ── Project panel ──
    ProjectPanel_EditHeader: 'Upravit projekt',
    ProjectPanel_NewHeader: 'Nový projekt',
    ProjectPanel_ProjectNameLabel: 'Název projektu',
    ProjectPanel_ProjectNamePlaceholder: 'Zadejte název projektu',
    ProjectPanel_ProjectNameRequired: 'Název projektu je povinný',
    ProjectPanel_DescriptionLabel: 'Popis',
    ProjectPanel_DescriptionPlaceholder: 'Zadejte popis',
    ProjectPanel_ProjectColorLabel: 'Barva projektu',
    ProjectPanel_StatusLabel: 'Stav',
    ProjectPanel_StartDateLabel: 'Datum zahájení',
    ProjectPanel_DueDateLabel: 'Termín splnění',
    ProjectPanel_DueDateError: 'Termín splnění musí být stejný nebo pozdější než datum zahájení',
    ProjectPanel_WhatHappensNextTitle: 'Co bude následovat?',
    ProjectPanel_WhatHappensNextBody: 'Po vytvoření projektu budete moci přidávat úkoly, nastavit fáze a sledovat postup.',
    ProjectPanel_SavingLabel: 'Ukládání…',
    ProjectPanel_CreatingLabel: 'Vytváření…',
    ProjectPanel_SaveChangesButton: 'Uložit změny',
    ProjectPanel_CreateProjectButton: 'Vytvořit projekt',
    ProjectPanel_CancelButton: 'Zrušit',
    ProjectPanel_DismissAriaLabel: 'Zavřít',
    ProjectPanel_DiscardUnsavedChangesConfirm: 'Zahodit neuložené změny?',
    ProjectPanel_SaveFallbackError: 'Projekt se nepodařilo uložit.',

    // ── Import panel ──
    ImportPanel_SourceExcelTitle: 'Soubor Excel / CSV',
    ImportPanel_SourceExcelSubtitle: 'Import úkolů z tabulky',
    ImportPanel_SourcePlannerTitle: 'Microsoft Planner',
    ImportPanel_SourcePlannerSubtitle: 'Import úkolů z plánu v Planneru',
    ImportPanel_ClickToBrowse: 'Kliknutím vyberte soubor',
    ImportPanel_DragDropSuffix: ' nebo přetáhněte soubor sem',
    ImportPanel_SupportedExtensions: 'Podporuje .xlsx, .xls, .csv',
    ImportPanel_RowsColsSummary: 'Zjištěno {rows} řádků, {cols} sloupců',
    ImportPanel_LoadingPlannerPlans: 'Načítání plánů Planneru…',
    ImportPanel_PlannerLoadError: 'Nepodařilo se načíst plány Planneru.',
    ImportPanel_PlannerPermissionsHintPrefix: 'Ujistěte se, že máte přístup k Planneru a že ',
    ImportPanel_PlannerPermissionsHintEmphasis: 'Úkoly od Planneru a To Do',
    ImportPanel_PlannerPermissionsHintSuffix: ' jsou k dispozici pro tento web.',
    ImportPanel_NoPlannerPlansFoundTitle: 'Nebyly nalezeny žádné plány Planneru',
    ImportPanel_NoPlannerPlansFoundBody: 'Možná nemáte přístup k žádným plánům Planneru, nebo pro tento účet žádné neexistují.',
    ImportPanel_TaskCountFoundIn: 'V plánu "{planName}" bylo nalezeno {count} úkolů',
    ImportPanel_ProjectDetailsIntroPrefix: 'Import do ',
    ImportPanel_ProjectDetailsIntroSuffix: '. Zkontrolujte níže podrobnosti projektu.',
    ImportPanel_ProjectNameLabel: 'Název projektu',
    ImportPanel_DescriptionLabel: 'Popis',
    ImportPanel_StatusLabel: 'Stav',
    ImportPanel_ColorLabel: 'Barva',
    ImportPanel_MapIntro: 'Namapujte sloupce ze souboru na pole úkolu.',
    ImportPanel_CreatingProjectStatus: 'Vytváření projektu…',
    ImportPanel_ImportingTasksStatus: 'Import úkolů…',
    ImportPanel_ProgressLabel: '{done} z {total}',
    ImportPanel_CouldNotCreateProject: 'Projekt se nepodařilo vytvořit.',
    ImportPanel_ImportCompletedWithErrors: 'Import byl dokončen s {count} chybou/chybami.',
    ImportPanel_ProjectCreatedSuccess: 'Projekt byl úspěšně vytvořen!',
    ImportPanel_ImportSuccessful: 'Import byl úspěšný!',
    ImportPanel_TasksAddedTo: 'Do projektu "{projectName}" bylo přidáno {count} úkolů',
    ImportPanel_FailedRowsLabel: 'Neúspěšné řádky:',
    ImportPanel_CloseButton: 'Zavřít',
    ImportPanel_OpenProjectButton: 'Otevřít projekt',
    ImportPanel_ViewImportedTasksButton: 'Zobrazit importované úkoly',
    ImportPanel_NextMapColumnsButton: 'Další: Namapovat sloupce',
    ImportPanel_ImportNTasksButton: 'Importovat {count} úkolů',
    ImportPanel_BackButton: 'Zpět',
    ImportPanel_CancelButton: 'Zrušit',
    ImportPanel_NextButton: 'Další',
    ImportPanel_StepSource: 'Zdroj',
    ImportPanel_StepProject: 'Projekt',
    ImportPanel_StepMap: 'Mapování',
    ImportPanel_StepImport: 'Import',
    ImportPanel_StepDone: 'Hotovo',
    ImportPanel_ImportAsNewProjectHeader: 'Importovat soubor jako nový projekt',
    ImportPanel_ImportIntoProjectHeader: 'Importovat úkoly do projektu {projectName}',
    ImportPanel_CouldNotParseFile: 'Soubor se nepodařilo zpracovat.',
    ImportPanel_CouldNotLoadPlannerTasks: 'Nepodařilo se načíst úkoly z tohoto plánu.',
    ImportPanel_CouldNotCreateProjectDetail: 'Projekt se nepodařilo vytvořit: {detail}',
    ImportPanel_CouldNotLinkDependencies: 'Nepodařilo se propojit závislosti: {detail}',
    ImportPanel_UnknownError: 'neznámá chyba',

    // ── Column mapper (import) ──
    ColumnMapper_TaskNameRequiredBanner: 'Pro pokračování musí být namapován název úkolu.',
    ColumnMapper_SkippedColumnsBanner: 'Bude přeskočeno {count} sloupců.',
    ColumnMapper_SourceColumnHeader: 'Zdrojový sloupec',
    ColumnMapper_TargetFieldHeader: 'Cílové pole',
    ColumnMapper_StatusHeader: 'Stav',
    ColumnMapper_SkippedBadge: 'Přeskočeno',
    ColumnMapper_AutoMappedBadge: 'Automaticky namapováno',
    ColumnMapper_SetBadge: 'Nastaveno',
    ColumnMapper_PreviewTitle: 'Náhled: {columnName}',
    ColumnMapper_EmptyCellDash: '—',

    // ── Import field display names / ImportService ──
    ImportField_TaskName: 'Název úkolu',
    ImportField_StartDate: 'Datum zahájení',
    ImportField_DueDate: 'Termín splnění',
    ImportField_Status: 'Stav',
    ImportField_Priority: 'Priorita',
    ImportField_AssignedTo: 'Přiřazeno komu',
    ImportField_AssignedToEmail: 'E-mail přiřazené osoby',
    ImportField_PercentComplete: '% dokončeno',
    ImportField_Phase: 'Fáze',
    ImportField_Description: 'Popis',
    ImportField_Notes: 'Poznámky',
    ImportField_IsMilestone: 'Je milník',
    ImportField_Dependencies: 'Závislosti',
    ImportField_SkipColumn: '(Přeskočit tento sloupec)',
    ImportService_EmptyFileError: 'Zdá se, že soubor je prázdný nebo neobsahuje žádné datové řádky.',
    ImportService_ReadErrorDetail: 'Soubor se nepodařilo přečíst: {detail}.',
    ImportService_FileReadError: 'Chyba při čtení souboru.',
    ImportService_RowError: 'Řádek {rowNum} ("{title}"): {error}',
    ImportService_AmbiguousDependency: 'Závislost "{name}" odpovídá více než jednomu názvu úkolu — přeskočeno.',
    ImportService_LinkDependencyError: 'Nepodařilo se propojit závislosti pro úkol {taskId}: {error}',

    // ── Health labels (shared: healthUtils.ts and ExportService.ts both use this set; also replaces the duplicated Export_PortfolioHealthLabel* keys) ──
    Health_Done: 'Dokončeno',
    Health_OnTrack: 'Podle plánu',
    Health_AtRisk: 'V ohrožení',
    Health_Overdue: 'Po termínu',

    // ── Status / Priority display labels (DISPLAY-ONLY — stored SharePoint Choice values remain unchanged/English) ──
    Status_NotStarted: 'Nezahájeno',
    Status_InProgress: 'Probíhá',
    Status_Completed: 'Dokončeno',
    Status_OnHold: 'Pozastaveno',
    Status_Cancelled: 'Zrušeno',
    Priority_Critical: 'Kritická',
    Priority_High: 'Vysoká',
    Priority_Medium: 'Střední',
    Priority_Low: 'Nízká',
    ProjectStatus_Planning: 'Plánování',
    ProjectStatus_Active: 'Aktivní',
    ProjectStatus_OnHold: 'Pozastaveno',
    ProjectStatus_Completed: 'Dokončeno',
    ProjectStatus_Cancelled: 'Zrušeno',

    // ── Shell (SmartGantt.tsx) ──
    SmartGantt_LoadingProjects: 'Načítání projektů…',
    SmartGantt_UnableToLoad: 'Nelze načíst',
    SmartGantt_RetryButton: 'Zkusit znovu',
    SmartGantt_NoProjectsYet: 'Zatím žádné projekty',
    SmartGantt_NoProjectsSubtitle: 'Vytvořte svůj první projekt a začněte.',
    SmartGantt_CreateFirstProjectButton: '+ Vytvořit první projekt',
    SmartGantt_ImportFromExcelButton: '📥 Importovat z Excelu',
    SmartGantt_LoadingTasks: 'Načítání úkolů…',
    SmartGantt_DismissAriaLabel: 'Zavřít',
    SmartGantt_DeleteTaskDialogTitle: 'Smazat úkol',
    SmartGantt_DeleteTaskDialogSubtext: 'Opravdu chcete smazat úkol "{taskTitle}"? Tuto akci nelze vrátit zpět.',
    SmartGantt_DeleteButton: 'Smazat',
    SmartGantt_CancelButton: 'Zrušit',
    SmartGantt_ArchiveProjectDialogTitle: 'Archivovat projekt',
    SmartGantt_ArchiveProjectDialogSubtext: 'Archivovat projekt "{projectTitle}"? Později jej můžete obnovit z archivu.',
    SmartGantt_ArchiveButton: 'Archivovat',
    SmartGantt_SendToRecycleBinDialogTitle: 'Přesunout do koše',
    SmartGantt_SendToRecycleBinDialogSubtext: 'Přesunout projekt "{projectTitle}" do koše webu?',
    SmartGantt_SendToRecycleBinButton: 'Přesunout do koše',
    SmartGantt_FailedLoadProjects: 'Nepodařilo se načíst projekty. Zkontrolujte oprávnění k webu.',
    SmartGantt_FailedLoadTasks: 'Nepodařilo se načíst úkoly pro tento projekt.',
    SmartGantt_FailedLoadPortfolioStats: 'Nepodařilo se načíst statistiky portfolia.',
    SmartGantt_CouldNotSaveProject: 'Projekt se nepodařilo uložit: {message}',
    SmartGantt_CouldNotDeleteProject: 'Projekt se nepodařilo smazat: {message}',
    SmartGantt_CouldNotArchiveProject: 'Projekt se nepodařilo archivovat: {message}',
    SmartGantt_CouldNotUnarchiveProject: 'Projekt se nepodařilo obnovit z archivu: {message}',
    SmartGantt_CouldNotSaveTask: 'Úkol se nepodařilo uložit: {message}',
    SmartGantt_CouldNotDeleteTask: 'Úkol se nepodařilo smazat: {message}',
    SmartGantt_ImageExportFailed: 'Export obrázku se nezdařil: {message}',
    SmartGantt_PowerPointExportFailed: 'Export do PowerPointu se nezdařil: {message}',
    SmartGantt_PortfolioExportFailed: 'Export portfolia se nezdařil: {message}',
    SmartGantt_CouldNotUpdateTask: 'Úkol se nepodařilo aktualizovat: {message}',

    // ── Common ──
    ColorSwatch_AutoColorAriaLabel: 'Automatická barva',
    ColorSwatch_CustomColorAriaLabel: 'Vlastní barva',
    ColorSwatch_PickCustomColorTitle: 'Vyberte vlastní barvu',

    // ── Export (Excel / PowerPoint) ──
    Export_ColTaskName: 'Název úkolu',
    Export_ColPhase: 'Fáze',
    Export_ColStartDate: 'Datum zahájení',
    Export_ColDueDate: 'Termín splnění',
    Export_ColStatus: 'Stav',
    Export_ColPriority: 'Priorita',
    Export_ColAssignedTo: 'Přiřazeno komu',
    Export_ColAssignedToEmail: 'E-mail přiřazené osoby',
    Export_ColPercentComplete: '% dokončeno',
    Export_ColIsMilestone: 'Je milník',
    Export_ColDescription: 'Popis',
    Export_ColNotes: 'Poznámky',
    Export_Yes: 'Ano',
    Export_No: 'Ne',
    Export_SheetNameTasks: 'Úkoly',
    Export_ExcelFileSuffix: ' - Úkoly.xlsx',
    Export_TaskNameColumnLabel: 'NÁZEV ÚKOLU',
    Export_ExportedDateLabel: 'Exportováno {date}',
    Export_ProjectReportLabel: 'ZPRÁVA O PROJEKTU',
    Export_StatusLine: 'Stav: {status}',
    Export_DateRangeSeparator: ' do ',
    Export_ProjectManagerLine: 'Projektový manažer: {name}',
    Export_GeneratedDateLine: 'Vygenerováno {date}',
    Export_ProjectSummaryTitle: 'Souhrn projektu',
    Export_StatTotalTasks: 'Celkem úkolů',
    Export_StatCompleted: 'Dokončeno',
    Export_StatInProgress: 'Probíhá',
    Export_StatOnHold: 'Pozastaveno',
    Export_StatNotStarted: 'Nezahájeno',
    Export_OverallProgressLine: 'Celkový postup',
    Export_OverallProgressPercent: '{percent} %',
    Export_StatusBreakdownTitle: 'Rozdělení podle stavu',
    Export_StatusBreakdownRow: '{status}: {count} ({percent} %)',
    Export_GanttTimelineTitle: 'Časová osa Gantt',
    Export_SummaryRecentActivityTitle: 'Nedávná aktivita',
    Export_ProjectOverviewLabel: 'Přehled projektu',
    Export_DetailStatusLabel: 'Stav',
    Export_DetailStartDateLabel: 'Datum zahájení',
    Export_DetailDueDateLabel: 'Termín splnění',
    Export_DetailProjectManagerLabel: 'Projektový manažer',
    Export_Past7DaysLabel: 'Posledních 7 dní',
    Export_NoActivityMessage: 'Žádná nedávná aktivita.',
    Export_CompletedThisWeekHeader: 'Dokončeno tento týden ({count})',
    Export_NewBadge: 'NOVÉ  ',
    Export_CompletedPercentLine: 'Dokončeno na {percent} %',
    Export_MoreItemsSuffix: '+ {count} dalších',
    Export_InProgressUpdatedHeader: 'Probíhá / aktualizováno',
    Export_StatusPercentLine: '{status} — {percent} %',
    Export_PortfolioReportLabel: 'ZPRÁVA O PORTFOLIU',
    Export_PortfolioOverviewTitle: 'Přehled portfolia',
    Export_ProjectsCountLine: '{count} projektů',
    Export_HealthSummaryOnTrack: '{count} podle plánu',
    Export_HealthSummaryAtRisk: '{count} v ohrožení',
    Export_HealthSummaryOverdue: '{count} po termínu',
    Export_ProjectsSummaryHeader: 'Souhrn projektů',
    Export_TableProject: 'Projekt',
    Export_TableStatus: 'Stav',
    Export_TableHealth: 'Zdraví',
    Export_TableTotal: 'Celkem',
    Export_TableDone: 'Dokončeno',
    Export_TableActive: 'Aktivní',
    Export_TableAtRisk: 'V ohrožení',
    Export_TableOverdue: 'Po termínu',
    Export_TablePctDone: '% dokončeno',
    Export_TableDueDate: 'Termín splnění',
    Export_PortfolioSummaryFileName: 'Souhrn portfolia.xlsx',
    Export_PortfolioReportFileName: 'Zpráva o portfoliu.pptx',
    Export_ProjectReportFileName: 'Zpráva {projectName}.pptx',
    Export_UnavailableLabel: 'Není k dispozici',
    Export_SheetNamePortfolio: 'Portfolio',
    Export_ColStart: 'Zahájení',
    Export_ColDue: 'Termín',
    Export_ImageGenerationFailed: 'Obrázek se nepodařilo vytvořit – graf může být na export jako obrázek příliš velký.',
    Export_DrawingContextFailed: 'Nepodařilo se vytvořit kreslicí kontext pro export.',
    Export_SvgRenderFailed: 'Vykreslení SVG se nezdařilo',

    // ── Added in v1.5 review ──
    Svc_TooManyDependencies: 'Tento úkol má příliš mnoho závislostí, než aby šel uložit (limit je zhruba 60). Některé odeberte a zkuste to znovu.',
    Svc_TaskChangedByOthers: 'Tento úkol změnil od jeho načtení někdo jiný. Aktualizujte stránku a zkuste to znovu.',
    Svc_ProjectChangedByOthers: 'Tento projekt změnil od jeho otevření někdo jiný. Aktualizujte stránku a zkuste to znovu.',
    Svc_ColumnCreateFailed: 'Nepodařilo se vytvořit sloupce ({count}) v novém seznamu úkolů: {detail}',
    Svc_BaselineUnavailable: 'Základní plány nejsou pro tento projekt k dispozici, protože se nepodařilo přidat sloupce základního plánu (možná potřebujete oprávnění k úpravě seznamu).',
    Svc_SubtaskReassignFailed: 'Před odstraněním úkolu se nepodařilo přeřadit jeho podúkoly: {detail}',
    Svc_UnresolvedDependency: 'Řádek {row} („{title}“): závislost „{name}“ se nepodařilo přiřadit k importovanému úkolu.',
    Svc_SelfDependency: 'Řádek {row} („{title}“): závislost „{name}“ odkazuje na samotný úkol a byla přeskočena.',
    Svc_ColId: 'ID',
    Svc_ColDependencies: 'Závislosti',
    Svc_ColBaselineStart: 'Zahájení základního plánu',
    Svc_ColBaselineDue: 'Termín základního plánu',
    Svc_CsvFileSuffix: ' – Úkoly.csv',
    Svc_IcsFileSuffix: ' – Milníky.ics',
    Svc_PortfolioCsvFileName: 'Souhrn portfolia.csv',
    Svc_PP_DisplayGroup: 'Výchozí hodnoty',
    Svc_PP_DefaultView: 'Výchozí zobrazení',
    Svc_PP_ViewGantt: 'Gantt',
    Svc_PP_ViewList: 'Seznam',
    Svc_PP_ViewKanban: 'Kanban',
    Svc_PP_ViewDashboard: 'Přehled',
    Svc_PP_ViewPortfolio: 'Portfolio',
    Svc_PP_DefaultZoom: 'Výchozí přiblížení',
    Svc_PP_ZoomDay: 'Den',
    Svc_PP_ZoomWeek: 'Týden',
    Svc_PP_ZoomMonth: 'Měsíc',
    Svc_PP_ZoomQuarter: 'Čtvrtletí',
    Svc_PP_CalendarGroup: 'Pracovní kalendář',
    Svc_PP_DaySun: 'Neděle je pracovní den',
    Svc_PP_DayMon: 'Pondělí je pracovní den',
    Svc_PP_DayTue: 'Úterý je pracovní den',
    Svc_PP_DayWed: 'Středa je pracovní den',
    Svc_PP_DayThu: 'Čtvrtek je pracovní den',
    Svc_PP_DayFri: 'Pátek je pracovní den',
    Svc_PP_DaySat: 'Sobota je pracovní den',
    Svc_PP_Holidays: 'Svátky (nepracovní dny)',
    Svc_PP_HolidaysHint: 'Jedno datum na řádek ve formátu rrrr-MM-dd (například 2026-12-25).',
    Gantt_TimelineAriaLabel: 'Časová osa úkolů',
    Gantt_DragLabel: '{start} → {end} ({days} d)',
    Gantt_KeyboardMoveAnnouncement: '{taskTitle}: {startDate} až {dueDate}',
    Gantt_KeyboardHint: 'Stisknutím klávesy Enter otevřete úkol. Šipkami doleva a doprava jej posunete o jeden pracovní den. Klávesa Shift se šipkami změní datum ukončení.',
    Gantt_ParentCycleTooltip: 'Tento úkol je součástí kruhového řetězce nadřazených úkolů a podúkolů, proto se zobrazuje na nejvyšší úrovni',
    Gantt_CollapseAll: 'Sbalit všechny fáze',
    Gantt_ExpandAll: 'Rozbalit všechny fáze',
    Gantt_BaselineTooltip: 'Základní plán: {start} → {due}',
    Gantt_VarianceTooltip: 'Odchylka dokončení: {days} dnů oproti základnímu plánu',
    Gantt_LinkHandleTitle: 'Přetažením na jiný úkol vytvoříte závislost',
    Toolbar_FitToProject: 'Přizpůsobit',
    Toolbar_FitToProjectTitle: 'Přiblížit tak, aby se vešel celý projekt',
    Toolbar_UndoTitle: 'Zpět (Ctrl+Z)',
    Toolbar_RedoTitle: 'Znovu (Ctrl+Y)',
    Toolbar_ExportCsv: '📄 Exportovat úkoly do CSV',
    Toolbar_ExportIcs: '📅 Exportovat milníky (iCal)',
    Toolbar_Print: '🖨 Tisk / Uložit jako PDF',
    Toolbar_SetBaseline: '📐 Nastavit základní plán…',
    Toolbar_CopyLink: '🔗 Kopírovat odkaz',
    Toolbar_CopyLinkTitle: 'Kopírovat odkaz na toto zobrazení (projekt, zobrazení, přiblížení a filtry)',
    App_UndoButton: 'Zpět',
    App_Undone: 'Změna byla vrácena zpět.',
    App_Redone: 'Změna byla provedena znovu.',
    App_DependentsMovedOne: 'Byl přesunut 1 závislý úkol.',
    App_DependentsMovedMany: 'Počet přesunutých závislých úkolů: {count}.',
    App_TaskConflict: 'Tento úkol změnil někdo jiný. Nejnovější úkoly byly znovu načteny – zkontrolujte je a zkuste to znovu.',
    App_DependencyCycle: 'Tato vazba by vytvořila cyklickou závislost.',
    App_DependencyExists: 'Tyto úkoly jsou již propojeny.',
    App_LinkCopied: 'Odkaz byl zkopírován do schránky.',
    App_LinkCopyFailed: 'Odkaz se nepodařilo zkopírovat: {message}',
    App_PopupBlocked: 'Okno pro tisk bylo zablokováno. Povolte pro tento web místní okna a zkuste to znovu.',
    App_SetBaselineDialogTitle: 'Nastavit základní plán',
    App_SetBaselineDialogSubtext: 'Uložit aktuální data zahájení a termíny všech úkolů ({count}) jako základní plán? Stávající základní plán bude nahrazen.',
    App_SetBaselineButton: 'Nastavit základní plán',
    App_BaselineSaved: 'Základní plán byl uložen.',
    App_BaselineFailed: 'Základní plán se nepodařilo uložit: {message}',
    App_CsvExportFailed: 'Export do CSV se nezdařil: {message}',
    App_IcsExportFailed: 'Export kalendáře se nezdařil: {message}',
    App_BulkDeleteDialogTitle: 'Odstranit úkoly',
    App_BulkDeleteDialogSubtext: 'Opravdu chcete odstranit úkoly ({count})? Tuto akci nelze vrátit zpět.',
    Common_PeoplePicker_ClearAriaLabel: 'Vymazat',
    Common_PeoplePicker_DirectoryHeader: 'Osoby v adresáři',
    Common_PeoplePicker_EmailLabel: 'E-mail (volitelné)',
    Common_PeoplePicker_EmailPlaceholder: 'jmeno@firma.cz',
    Common_PeoplePicker_ExternalHint: 'Není v adresáři. Uloženo jako volný text.',
    Common_PeoplePicker_InvalidEmail: 'Zadejte platnou e-mailovou adresu.',
    Common_PeoplePicker_ListAriaLabel: 'Návrhy osob',
    Common_PeoplePicker_RecentHeader: 'Naposledy použité',
    Common_PeoplePicker_ResultsAnnouncement: 'Počet dostupných návrhů: {count}',
    Common_PeoplePicker_Searching: 'Vyhledávání…',
    Common_PeoplePicker_UseExternal: 'Použít „{name}“ (externí / není v adresáři)',
    Import_Mapper_PreviewFirstRows: 'Náhled (prvních {count} řádků)',
    Import_Mapper_RequiredLegend: 'Povinné pole',
    Import_Mapper_RequiredMarkerLabel: 'Povinné',
    Import_Mapper_SelectAriaLabel: 'Cílové pole pro sloupec {columnName}',
    Import_Panel_DateOrderAuto: 'Automaticky zjistit',
    Import_Panel_DateOrderDMY: 'Den/měsíc/rok (31/12/2026)',
    Import_Panel_DateOrderDetected: 'Zjištěno z vašeho souboru: {order}.',
    Import_Panel_DateOrderHint: 'Platí pro data zapsaná číslicemi, například 03/04/2026.',
    Import_Panel_DateOrderLabel: 'Pořadí data',
    Import_Panel_DateOrderMDY: 'Měsíc/den/rok (12/31/2026)',
    Import_Panel_DropZoneAriaLabel: 'Vyberte soubor k importu. Stisknutím klávesy Enter zobrazíte výběr souborů.',
    Import_Panel_DropZoneChangeAriaLabel: 'Vybraný soubor {fileName}. Stisknutím klávesy Enter vyberete jiný soubor.',
    Import_Panel_FailedCount: 'Nezdařilo se: {count}',
    Import_Panel_NewProjectIntroMany: 'Bude vytvořen nový projekt a budou do něj naimportovány všechny úkoly ({count}). Tyto údaje můžete po importu kdykoli změnit.',
    Import_Panel_NewProjectIntroOne: 'Bude vytvořen nový projekt a bude do něj naimportován {count} úkol. Tyto údaje můžete po importu kdykoli změnit.',
    Import_Panel_PlanAriaLabel: '{planName}, {groupName}',
    Import_Panel_ProblemEndBeforeStart: 'Termín je před datem zahájení',
    Import_Panel_ProblemInvalidDueDate: 'Termín „{value}“ není platné datum',
    Import_Panel_ProblemInvalidStartDate: 'Datum zahájení „{value}“ není platné datum',
    Import_Panel_ProblemMissingTitle: 'Chybí název úkolu',
    Import_Panel_ProgressLabelWithPercent: '{done} z {total} ({percent} %)',
    Import_Panel_SkipInvalidRows: 'Přeskočit řádky s problémy',
    Import_Panel_SuccessWithWarningsMany: 'Import byl úspěšný, počet upozornění: {count}.',
    Import_Panel_SuccessWithWarningsOne: 'Import byl úspěšný, počet upozornění: {count}.',
    Import_Panel_ValidationHeader: 'Řádky s problémy',
    Import_Panel_ValidationMore: '…a dalších {count}',
    Import_Panel_ValidationRow: 'Řádek {rowNum}: {problem}',
    Import_Panel_ValidationSummaryMany: 'Počet řádků s problémy: {count}',
    Import_Panel_ValidationSummaryOne: '{count} řádek má problém',
    Import_Panel_WarningsLabel: 'Upozornění ({count}):',
    Panel_Project_ManagerLabel: 'Vedoucí projektu',
    Panel_Project_ManagerPlaceholder: 'Vyhledejte osoby nebo zadejte jméno…',
    Panel_Task_BaselineDueLabel: 'Dokončení podle základního plánu',
    Panel_Task_BaselineHeader: 'Základní plán',
    Panel_Task_BaselineStartLabel: 'Zahájení podle základního plánu',
    Panel_Task_DepTypeFF: 'Konec–Konec (FF)',
    Panel_Task_DepTypeFS: 'Konec–Začátek (FS)',
    Panel_Task_DepTypeSF: 'Začátek–Konec (SF)',
    Panel_Task_DepTypeSS: 'Začátek–Začátek (SS)',
    Panel_Task_LagAriaLabel: 'Zpoždění v pracovních dnech pro {taskTitle}',
    Panel_Task_LagHint: 'Zpoždění se udává v pracovních dnech. Pro předstih použijte záporné číslo.',
    Panel_Task_LinkTypeAriaLabel: 'Typ vazby pro {taskTitle}',
    Panel_Task_VarianceEarlier: 'O {days} pracovních dnů dříve',
    Panel_Task_VarianceLater: 'O {days} pracovních dnů později',
    Panel_Task_VarianceOnBaseline: 'podle základního plánu',
    View_Dashboard_BurndownActual: 'Skutečnost',
    View_Dashboard_BurndownAria: 'Graf vyhoření: zbývá {remaining} z {total} úkolů',
    View_Dashboard_BurndownHeader: 'Vyhoření (zbývající úkoly)',
    View_Dashboard_BurndownIdeal: 'Ideál',
    View_Dashboard_BurndownNoData: 'Není dostatek úkolů s daty pro vykreslení grafu vyhoření.',
    View_Dashboard_CriticalPathHeader: 'Kritická cesta  ({count})',
    View_Dashboard_PhaseDoneSummary: '{done}/{total} hotovo  •  {percent} %',
    View_Dashboard_TaskRowAriaLabel: 'Otevřít úkol {taskTitle}, {status}',
    View_Dashboard_WorkloadHeader: 'Vytížení podle řešitele',
    View_Dashboard_WorkloadOpen: 'Otevřených: {count}',
    View_Dashboard_WorkloadOverdue: 'Po termínu: {count}',
    View_Kanban_AddTaskInColumnAriaLabel: 'Přidat úkol do sloupce {column}',
    View_Kanban_CollapseColumn: 'Sbalit sloupec {column}',
    View_Kanban_ExpandColumn: 'Rozbalit sloupec {column}',
    View_Kanban_LaneHeader: '{name} ({count})',
    View_Kanban_LaneNoPhase: 'Bez fáze',
    View_Kanban_LaneUnassigned: 'Nepřiřazeno',
    View_Kanban_LanesAssignee: 'Řešitel',
    View_Kanban_LanesNone: 'Žádné',
    View_Kanban_LanesPhase: 'Fáze',
    View_Kanban_SwimlanesLabel: 'Swimlanes',
    View_Kanban_WipEditTitle: 'Nastavit limit rozpracované práce pro {column} (0 = bez limitu)',
    View_Kanban_WipExceededTitle: 'Limit WIP překročen: {count} z {limit}',
    View_Kanban_WipInputAriaLabel: 'Limit WIP pro {column}',
    View_Kanban_WipLabel: 'WIP {count}/{limit}',
    View_Kanban_WipSet: 'WIP',
    View_List_BulkAssignApply: 'Přiřadit',
    View_List_BulkAssigneePlaceholder: 'Přiřadit…',
    View_List_BulkBarAriaLabel: 'Hromadné akce pro vybrané úkoly',
    View_List_BulkClear: 'Zrušit výběr',
    View_List_BulkDelete: 'Odstranit vybrané',
    View_List_BulkPercentApply: 'Nastavit %',
    View_List_BulkPercentPlaceholder: '% dokončení',
    View_List_BulkPriorityPlaceholder: 'Nastavit prioritu…',
    View_List_BulkSelectedCount: 'Vybráno: {count}',
    View_List_BulkStatusPlaceholder: 'Nastavit stav…',
    View_List_ExportCsv: 'Exportovat CSV',
    View_List_NonWorkingDay: 'Nepracovní den',
    View_List_SelectAllAriaLabel: 'Vybrat všechny úkoly',
    View_List_SelectRowAriaLabel: 'Vybrat {taskTitle}',
    View_Portfolio_CardAriaLabel: 'Otevřít projekt {projectName}, {status}',
    View_Portfolio_ClearFilters: 'Vymazat filtry',
    View_Portfolio_FilteredCount: '{shown} z {total} projektů',
    View_Portfolio_HideDone: 'Skrýt dokončené / zrušené',
    View_Portfolio_NoMatches: 'Vašim filtrům neodpovídají žádné projekty.',
    View_Portfolio_ProjectCountMany: 'Počet projektů: {count}',
    View_Portfolio_ProjectCountOne: '{count} projekt',
    View_Portfolio_SearchAriaLabel: 'Hledat projekty',
    View_Portfolio_SearchPlaceholder: 'Hledat projekty…',
    Import_Panel_CopyDetails: 'Kopírovat podrobnosti',
    Import_Panel_Copied: 'Zkopírováno',
  };
});
