define([], function () {
  return {
    // ── Property pane ──
    PropertyPane_HeaderDescription: 'Indstillinger for Smart Gantt Chart',
    PropertyPane_GeneralGroupName: 'Generelt',
    PropertyPane_TitleFieldLabel: 'Webdelens titel',
    WebPart_DefaultTitle: 'Smart Gantt Chart',

    // ── Toolbar ──
    Toolbar_ViewDashboard: 'Dashboard',
    Toolbar_ViewList: 'Liste',
    Toolbar_ViewGantt: 'Gantt',
    Toolbar_ViewKanban: 'Kanban',
    Toolbar_ZoomDay: 'Dag',
    Toolbar_ZoomWeek: 'Uge',
    Toolbar_ZoomMonth: 'Måned',
    Toolbar_ZoomQuarter: 'Kvartal',
    Toolbar_SelectProjectAriaLabel: 'Vælg projekt',
    Toolbar_PortfolioLabel: 'Portefølje',
    Toolbar_SelectAProject: 'Vælg et projekt',
    Toolbar_AllProjectsSubtext: 'Alle projekter',
    Toolbar_NoProjectsYet: 'Ingen projekter endnu',
    Toolbar_ArchivedBadge: 'Arkiveret',
    Toolbar_ShowArchivedProjects: 'Vis arkiverede projekter',
    Toolbar_NewProject: '+ Nyt projekt',
    Toolbar_ImportFileAsNewProject: '📥 Importer fil som nyt projekt…',
    Toolbar_AddTask: '+ Tilføj opgave',
    Toolbar_EditProject: 'Rediger projekt',
    Toolbar_OptionsButton: '⚙ Indstillinger',
    Toolbar_MoreOptionsTitle: 'Flere indstillinger',
    Toolbar_ExportToExcel: '📊 Eksporter til Excel',
    Toolbar_ExportToPowerPoint: '📑 Eksporter til PowerPoint',
    Toolbar_ScrollToTodayTitle: 'Rul til i dag',
    Toolbar_TodayButton: '◉ I dag',
    Toolbar_ImportTasks: '📥 Importer opgaver…',
    Toolbar_ExportAsImage: '🖼 Eksporter som billede (PNG)',
    Toolbar_UnarchiveProject: '📂 Gendan fra arkiv',
    Toolbar_ArchiveProject: '🗄️ Arkiver projekt',
    Toolbar_SendToRecycleBin: '🗑️ Send til papirkurv',

    // ── Filter bar ──
    FilterBar_ClearOption: 'Ryd',
    FilterBar_DueAny: 'Enhver forfaldsdato',
    FilterBar_DueOverdue: 'Forfalden',
    FilterBar_DueToday: 'Forfalder i dag',
    FilterBar_DueWeek: 'Forfalder om 7 dage',
    FilterBar_SearchPlaceholder: 'Søg efter opgaver…',
    FilterBar_SearchAriaLabel: 'Søg efter opgaver',
    FilterBar_StatusChipLabel: 'Status',
    FilterBar_PriorityChipLabel: 'Prioritet',
    FilterBar_AssigneeChipLabel: 'Ansvarlig',
    FilterBar_PhaseChipLabel: 'Fase',
    FilterBar_DueDateAriaLabel: 'Filtrer efter forfaldsdato',
    FilterBar_MatchCount: '{matchCount} af {totalCount}',
    FilterBar_ClearFilters: '✕ Ryd filtre',
    FilterBar_ChipLabelWithCount: '{label} ({count}) ▾',
    FilterBar_ChipLabelNoCount: '{label} ▾',

    // ── Gantt view ──
    Gantt_TaskColumnHeader: 'Opgave',
    Gantt_DurationColumnHeader: 'Varighed',
    Gantt_AddTaskButton: '+ Tilføj opgave',
    Gantt_EmptyTitle: 'Ingen opgaver endnu',
    Gantt_EmptySubtitle: 'Tilføj opgaver for at se dem i Gantt-diagrammet.',
    Gantt_AddFirstTask: '+ Tilføj første opgave',
    Gantt_ImportTasksButton: '📥 Importer opgaver',
    Gantt_EditTitle: 'Rediger',
    Gantt_DeleteTitle: 'Slet',
    Gantt_EditTaskAriaLabel: 'Rediger opgave {taskTitle}',
    Gantt_DeleteTaskAriaLabel: 'Slet opgave {taskTitle}',
    Gantt_ExpandPhaseAriaLabel: '{action} fase {phase}',
    Gantt_ExpandAction: 'Udvid',
    Gantt_CollapseAction: 'Skjul',
    Gantt_DependencyViolationTooltip: 'Startet før alle afhængigheder var fuldført',
    Gantt_MilestoneAriaLabel: '{taskTitle}, milepæl, {date}',
    Gantt_BarAriaLabel: '{taskTitle}, {startDate} til {dueDate}, {percent}% fuldført',
    Gantt_PercentCompleteTooltip: '{value}% fuldført',

    // ── Gantt options/settings panel ──
    GanttSettings_PanelHeader: '⚙ Indstillinger',
    GanttSettings_ColorCodingSection: 'Farvekodning',
    GanttSettings_ByStatus: 'Efter status',
    GanttSettings_ByPriority: 'Efter prioritet',
    GanttSettings_ByPhase: 'Efter fase',
    GanttSettings_ByHealth: 'Efter sundhed',
    GanttSettings_HeaderColorSection: 'Overskriftsfarve',
    GanttSettings_ThemeDark: 'Mørk',
    GanttSettings_ThemeNavy: 'Marineblå',
    GanttSettings_ThemeTeal: 'Petroleum',
    GanttSettings_ThemePurple: 'Lilla',
    GanttSettings_ThemeLight: 'Lys',
    GanttSettings_HeaderLabelsSection: 'Overskriftsetiketter',
    GanttSettings_WeekLabelDates: 'Datoer',
    GanttSettings_WeekLabelDatesDesc: '3. jun, 10. jun…',
    GanttSettings_WeekLabelProject: 'Projektuger',
    GanttSettings_WeekLabelProjectDesc: 'U1, U2…',
    GanttSettings_WeekLabelIso: 'Kalenderuger',
    GanttSettings_WeekLabelIsoDesc: 'U23, U24…',
    GanttSettings_ProjectWeeksHint: 'Uge 1 starter fra mandagen i din tidligste opgave — velegnet til præsentationer.',
    GanttSettings_BarStyleSection: 'Bjælkestil',
    GanttSettings_BarStyleGradient: 'Farveovergang',
    GanttSettings_BarStyleFlat: 'Flad',
    GanttSettings_RowHeightSection: 'Rækkehøjde',
    GanttSettings_HeightCompact: 'Kompakt',
    GanttSettings_HeightNormal: 'Normal',
    GanttSettings_HeightSpacious: 'Rummelig',
    GanttSettings_ShowHideSection: 'Vis / skjul',
    GanttSettings_WeekendShading: 'Weekendmarkering',
    GanttSettings_DependencyArrows: 'Afhængighedspile',
    GanttSettings_CriticalPathAlwaysVisible: 'Kritisk vej altid synlig',
    GanttSettings_AllOthersOnHoverOnly: 'Alle andre kun ved museover',
    GanttSettings_CriticalPathHighlight: 'Fremhæv kritisk vej',
    GanttSettings_ProgressPercentOnBars: 'Fremdrift i % på bjælker',
    GanttSettings_AssigneeNameOnBars: 'Ansvarliges navn på bjælker',
    GanttSettings_HealthStatusBadges: 'Statusmærker for sundhed',

    // ── List view ──
    ListView_ColTaskName: 'Opgavenavn',
    ListView_ColStatus: 'Status',
    ListView_ColHealth: 'Sundhed',
    ListView_ColPriority: 'Prioritet',
    ListView_ColStart: 'Start',
    ListView_ColDue: 'Forfald',
    ListView_ColAssignedTo: 'Tildelt til',
    ListView_ColProgress: 'Fremdrift',
    ListView_ColPhase: 'Fase',
    ListView_ColPredecessors: 'Forgængere',
    ListView_EmptyTitle: 'Ingen opgaver endnu',
    ListView_AddFirstTask: '+ Tilføj første opgave',
    ListView_AddTaskRow: '+ Tilføj opgave',
    ListView_Unassigned: 'Ikke tildelt',
    ListView_DependencyViolationTooltip: 'Startet før alle afhængigheder var fuldført',
    ListView_StatusAriaLabel: 'Status for {taskTitle}',
    ListView_PriorityAriaLabel: 'Prioritet for {taskTitle}',
    ListView_EditTaskAriaLabel: 'Rediger opgave {taskTitle}',
    ListView_DeleteTaskAriaLabel: 'Slet opgave {taskTitle}',
    ListView_EditTitle: 'Rediger',
    ListView_DeleteTitle: 'Slet',

    // ── Kanban view ──
    Kanban_ColumnNotStarted: 'Ikke startet',
    Kanban_ColumnInProgress: 'I gang',
    Kanban_ColumnOnHold: 'Sat i bero',
    Kanban_ColumnCompleted: 'Fuldført',
    Kanban_ColumnCancelled: 'Annulleret',
    Kanban_AddTaskButton: '+ Tilføj opgave',
    Kanban_EditTitle: 'Rediger',
    Kanban_DeleteTitle: 'Slet',
    Kanban_CardAriaLabel: '{taskTitle}, {status}. Tryk på Enter for at redigere, venstre eller højre pil for at skifte status.',
    Kanban_EditTaskAriaLabel: 'Rediger opgave {taskTitle}',
    Kanban_DeleteTaskAriaLabel: 'Slet opgave {taskTitle}',

    // ── Dashboard view ──
    Dashboard_TotalTasks: 'Opgaver i alt',
    Dashboard_Completed: 'Fuldført',
    Dashboard_InProgress: 'I gang',
    Dashboard_OnHold: 'Sat i bero',
    Dashboard_NotStarted: 'Ikke startet',
    Dashboard_Cancelled: 'Annulleret',
    Dashboard_OverallProgress: 'Samlet fremdrift',
    Dashboard_ProjectManagerLabel: 'Projektleder: {name}',
    Dashboard_PhaseProgressHeader: 'Fasefremdrift',
    Dashboard_StatusBreakdownHeader: 'Statusfordeling',
    Dashboard_PriorityBreakdownHeader: 'Prioritetsfordeling',
    Dashboard_PriorityCritical: 'Kritisk',
    Dashboard_PriorityHigh: 'Høj',
    Dashboard_PriorityMedium: 'Mellem',
    Dashboard_PriorityLow: 'Lav',
    Dashboard_OverdueHeader: 'Forfaldne  ({count})',
    Dashboard_DueNext14DaysHeader: 'Forfalder inden for 14 dage  ({count})',
    Dashboard_CompletedThisWeekHeader: 'Fuldført denne uge',
    Dashboard_UpdatedThisWeekHeader: 'Opdateret denne uge',
    Dashboard_Today: 'I dag',
    Dashboard_Tomorrow: 'I morgen',
    Dashboard_DaysLeft: '{days}d',
    Dashboard_EmptyTitle: 'Ingen opgaver endnu',
    Dashboard_EmptySubtitle: 'Tilføj opgaver for at se dit projektdashboard.',
    Dashboard_AddTaskButton: '+ Tilføj opgave',

    // ── Portfolio view ──
    Portfolio_ProjectCount: '{count} projekt{plural}',
    Portfolio_OnTrackSummary: '{count} på sporet',
    Portfolio_AtRiskSummary: '{count} i risiko',
    Portfolio_OverdueSummary: '{count} forfaldne',
    Portfolio_DoneSummary: '{count} færdige',
    Portfolio_SortLabel: 'Sortér:',
    Portfolio_SortAZ: 'A-Å',
    Portfolio_SortHealth: 'Sundhed',
    Portfolio_SortStatus: 'Status',
    Portfolio_SortCompletion: 'Fuldførelse',
    Portfolio_RefreshTitle: 'Opdater',
    Portfolio_RefreshButton: 'Opdater',
    Portfolio_LoadingStats: 'Indlæser statistik…',
    Portfolio_EmptyTitle: 'Ingen projekter endnu',
    Portfolio_CreateFirstProject: '+ Opret første projekt',
    Portfolio_StatsUnavailable: 'Statistik ikke tilgængelig',
    Portfolio_StatsUnavailableDetail: 'Kunne ikke indlæse statistik for dette projekt.',
    Portfolio_OverallProgressLabel: 'Samlet fremdrift',
    Portfolio_TaskCountDone: 'Færdige',
    Portfolio_TaskCountActive: 'Aktive',
    Portfolio_TaskCountAtRisk: 'I risiko',
    Portfolio_TaskCountOverdue: 'Forfaldne',
    Portfolio_ViewGanttLink: 'Vis Gantt →',
    Portfolio_TodayTooltip: 'I dag',

    // ── Task panel ──
    TaskPanel_EditHeader: 'Rediger: {taskTitle}',
    TaskPanel_NewTaskHeader: 'Ny opgave',
    TaskPanel_TabBasic: 'Grundlæggende',
    TaskPanel_TabDetails: 'Detaljer',
    TaskPanel_TabLinks: 'Links',
    TaskPanel_ProjectLabelPrefix: 'Projekt: ',
    TaskPanel_TaskNameLabel: 'Opgavenavn',
    TaskPanel_TaskNamePlaceholder: 'Angiv opgavenavn',
    TaskPanel_TaskNameRequired: 'Opgavenavn er påkrævet',
    TaskPanel_DescriptionLabel: 'Beskrivelse',
    TaskPanel_DescriptionPlaceholder: 'Angiv beskrivelse',
    TaskPanel_StartDateLabel: 'Startdato',
    TaskPanel_DueDateLabel: 'Forfaldsdato',
    TaskPanel_DueDateError: 'Forfaldsdato skal være på eller efter startdato',
    TaskPanel_StatusLabel: 'Status',
    TaskPanel_PriorityLabel: 'Prioritet',
    TaskPanel_PercentCompleteLabel: '% fuldført: {percent}%',
    TaskPanel_AssignedToLabel: 'Tildelt til',
    TaskPanel_AssignedToPlaceholder: 'Søg efter personer…',
    TaskPanel_PhaseLabel: 'Fase',
    TaskPanel_PhasePlaceholder: 'Angiv fasenavn',
    TaskPanel_PhaseHint: 'Grupperer opgaver sammen i Gantt- og listevisninger.',
    TaskPanel_MilestoneLabel: 'Milepæl',
    TaskPanel_MilestoneOnText: 'Ja',
    TaskPanel_MilestoneOffText: 'Nej',
    TaskPanel_CustomBarColorLabel: 'Brugerdefineret bjælkefarve',
    TaskPanel_CustomBarColorOptionalSuffix: ' (valgfrit)',
    TaskPanel_AutoColorHint: 'Automatisk farve fra indstillinger for status/prioritet/fase.',
    TaskPanel_NotesLabel: 'Noter',
    TaskPanel_NotesPlaceholder: 'Angiv noter',
    TaskPanel_ParentTaskLabel: 'Overordnet opgave',
    TaskPanel_ParentTaskNone: '(ingen)',
    TaskPanel_ParentTaskHasChildrenHint: 'Denne opgave har underopgaver og kan ikke have sin egen overordnede opgave.',
    TaskPanel_ParentTaskHint: 'Sæt denne opgave ind under en anden som en underopgave.',
    TaskPanel_DependsOnLabel: 'Afhænger af',
    TaskPanel_RemoveDependencyTitle: 'Fjern afhængighed af "{taskTitle}"',
    TaskPanel_AddDependencyPlaceholder: 'Tilføj en afhængighed…',
    TaskPanel_SelectATaskOption: 'Vælg en opgave…',
    TaskPanel_DependsOnHint: 'Opgaven kan ikke starte, før disse er fuldført.',
    TaskPanel_SavingLabel: 'Gemmer…',
    TaskPanel_CreatingLabel: 'Opretter…',
    TaskPanel_SaveChangesButton: 'Gem ændringer',
    TaskPanel_CreateTaskButton: 'Opret opgave',
    TaskPanel_CancelButton: 'Annuller',
    TaskPanel_DismissAriaLabel: 'Luk',
    TaskPanel_DiscardUnsavedChangesConfirm: 'Kassér ugemte ændringer?',
    TaskPanel_SaveFallbackError: 'Kunne ikke gemme opgaven.',

    // ── Project panel ──
    ProjectPanel_EditHeader: 'Rediger projekt',
    ProjectPanel_NewHeader: 'Nyt projekt',
    ProjectPanel_ProjectNameLabel: 'Projektnavn',
    ProjectPanel_ProjectNamePlaceholder: 'Angiv projektnavn',
    ProjectPanel_ProjectNameRequired: 'Projektnavn er påkrævet',
    ProjectPanel_DescriptionLabel: 'Beskrivelse',
    ProjectPanel_DescriptionPlaceholder: 'Angiv beskrivelse',
    ProjectPanel_ProjectColorLabel: 'Projektfarve',
    ProjectPanel_StatusLabel: 'Status',
    ProjectPanel_StartDateLabel: 'Startdato',
    ProjectPanel_DueDateLabel: 'Forfaldsdato',
    ProjectPanel_DueDateError: 'Forfaldsdato skal være på eller efter startdato',
    ProjectPanel_WhatHappensNextTitle: 'Hvad sker der nu?',
    ProjectPanel_WhatHappensNextBody: 'Du vil kunne tilføje opgaver, oprette faser og følge fremdrift, når projektet er oprettet.',
    ProjectPanel_SavingLabel: 'Gemmer…',
    ProjectPanel_CreatingLabel: 'Opretter…',
    ProjectPanel_SaveChangesButton: 'Gem ændringer',
    ProjectPanel_CreateProjectButton: 'Opret projekt',
    ProjectPanel_CancelButton: 'Annuller',
    ProjectPanel_DismissAriaLabel: 'Luk',
    ProjectPanel_DiscardUnsavedChangesConfirm: 'Kassér ugemte ændringer?',
    ProjectPanel_SaveFallbackError: 'Kunne ikke gemme projektet.',

    // ── Import panel ──
    ImportPanel_SourceExcelTitle: 'Excel-/CSV-fil',
    ImportPanel_SourceExcelSubtitle: 'Importer opgaver fra et regneark',
    ImportPanel_SourcePlannerTitle: 'Microsoft Planner',
    ImportPanel_SourcePlannerSubtitle: 'Importer opgaver fra en Planner-plan',
    ImportPanel_ClickToBrowse: 'Klik for at gennemse',
    ImportPanel_DragDropSuffix: ' eller træk og slip',
    ImportPanel_SupportedExtensions: 'Understøtter .xlsx, .xls, .csv',
    ImportPanel_RowsColsSummary: '{rows} rækker, {cols} kolonner registreret',
    ImportPanel_LoadingPlannerPlans: 'Indlæser Planner-planer…',
    ImportPanel_PlannerLoadError: 'Kunne ikke indlæse Planner-planer.',
    ImportPanel_PlannerPermissionsHintPrefix: 'Sørg for, at du har adgang til Planner, og at ',
    ImportPanel_PlannerPermissionsHintEmphasis: 'Opgaver af Planner og To Do',
    ImportPanel_PlannerPermissionsHintSuffix: ' er tilgængelig for dette websted.',
    ImportPanel_NoPlannerPlansFoundTitle: 'Ingen Planner-planer fundet',
    ImportPanel_NoPlannerPlansFoundBody: 'Du har muligvis ikke adgang til nogen Planner-planer, eller der findes ingen for denne konto.',
    ImportPanel_TaskCountFoundIn: '{count} opgaver fundet i "{planName}"',
    ImportPanel_ProjectDetailsIntroPrefix: 'Importerer til ',
    ImportPanel_ProjectDetailsIntroSuffix: '. Gennemgå projektoplysningerne nedenfor.',
    ImportPanel_ProjectNameLabel: 'Projektnavn',
    ImportPanel_DescriptionLabel: 'Beskrivelse',
    ImportPanel_StatusLabel: 'Status',
    ImportPanel_ColorLabel: 'Farve',
    ImportPanel_MapIntro: 'Tilknyt kolonnerne fra din fil til opgavefelter.',
    ImportPanel_CreatingProjectStatus: 'Opretter projekt…',
    ImportPanel_ImportingTasksStatus: 'Importerer opgaver…',
    ImportPanel_ProgressLabel: '{done} af {total}',
    ImportPanel_CouldNotCreateProject: 'Kunne ikke oprette projektet.',
    ImportPanel_ImportCompletedWithErrors: 'Import gennemført med {count} fejl.',
    ImportPanel_ProjectCreatedSuccess: 'Projektet blev oprettet!',
    ImportPanel_ImportSuccessful: 'Import gennemført!',
    ImportPanel_TasksAddedTo: '{count} opgaver tilføjet til "{projectName}"',
    ImportPanel_FailedRowsLabel: 'Mislykkede rækker:',
    ImportPanel_CloseButton: 'Luk',
    ImportPanel_OpenProjectButton: 'Åbn projekt',
    ImportPanel_ViewImportedTasksButton: 'Vis importerede opgaver',
    ImportPanel_NextMapColumnsButton: 'Næste: Tilknyt kolonner',
    ImportPanel_ImportNTasksButton: 'Importer {count} opgaver',
    ImportPanel_BackButton: 'Tilbage',
    ImportPanel_CancelButton: 'Annuller',
    ImportPanel_NextButton: 'Næste',
    ImportPanel_StepSource: 'Kilde',
    ImportPanel_StepProject: 'Projekt',
    ImportPanel_StepMap: 'Tilknytning',
    ImportPanel_StepImport: 'Import',
    ImportPanel_StepDone: 'Færdig',
    ImportPanel_ImportAsNewProjectHeader: 'Importer fil som nyt projekt',
    ImportPanel_ImportIntoProjectHeader: 'Importer opgaver til {projectName}',
    ImportPanel_CouldNotParseFile: 'Kunne ikke fortolke filen.',
    ImportPanel_CouldNotLoadPlannerTasks: 'Kunne ikke indlæse opgaver fra denne plan.',
    ImportPanel_CouldNotCreateProjectDetail: 'Kunne ikke oprette projekt: {detail}',
    ImportPanel_CouldNotLinkDependencies: 'Kunne ikke oprette afhængigheder: {detail}',
    ImportPanel_UnknownError: 'ukendt fejl',

    // ── Column mapper (import) ──
    ColumnMapper_TaskNameRequiredBanner: 'Opgavenavn skal tilknyttes for at fortsætte.',
    ColumnMapper_SkippedColumnsBanner: '{count} kolonne(r) springes over.',
    ColumnMapper_SourceColumnHeader: 'Kildekolonne',
    ColumnMapper_TargetFieldHeader: 'Målfelt',
    ColumnMapper_StatusHeader: 'Status',
    ColumnMapper_SkippedBadge: 'Sprunget over',
    ColumnMapper_AutoMappedBadge: 'Automatisk tilknyttet',
    ColumnMapper_SetBadge: 'Angivet',
    ColumnMapper_PreviewTitle: 'Forhåndsvisning: {columnName}',
    ColumnMapper_EmptyCellDash: '—',

    // ── Import field display names / ImportService ──
    ImportField_TaskName: 'Opgavenavn',
    ImportField_StartDate: 'Startdato',
    ImportField_DueDate: 'Forfaldsdato',
    ImportField_Status: 'Status',
    ImportField_Priority: 'Prioritet',
    ImportField_AssignedTo: 'Tildelt til',
    ImportField_AssignedToEmail: 'E-mail for tildelt til',
    ImportField_PercentComplete: '% fuldført',
    ImportField_Phase: 'Fase',
    ImportField_Description: 'Beskrivelse',
    ImportField_Notes: 'Noter',
    ImportField_IsMilestone: 'Er milepæl',
    ImportField_Dependencies: 'Afhængigheder',
    ImportField_SkipColumn: '(Spring denne kolonne over)',
    ImportService_EmptyFileError: 'Filen ser ud til at være tom eller har ingen datarækker.',
    ImportService_ReadErrorDetail: 'Kunne ikke læse filen: {detail}.',
    ImportService_FileReadError: 'Fejl ved læsning af fil.',
    ImportService_RowError: 'Række {rowNum} ("{title}"): {error}',
    ImportService_AmbiguousDependency: 'Afhængigheden "{name}" matcher mere end én opgavetitel — sprunget over.',
    ImportService_LinkDependencyError: 'Kunne ikke oprette afhængigheder for opgave {taskId}: {error}',

    // ── Health labels (shared: healthUtils.ts and ExportService.ts both use this set; also replaces the duplicated Export_PortfolioHealthLabel* keys) ──
    Health_Done: 'Færdig',
    Health_OnTrack: 'På sporet',
    Health_AtRisk: 'I risiko',
    Health_Overdue: 'Forfalden',

    // ── Status / Priority display labels (DISPLAY-ONLY — stored SharePoint Choice values remain unchanged/English) ──
    Status_NotStarted: 'Ikke startet',
    Status_InProgress: 'I gang',
    Status_Completed: 'Fuldført',
    Status_OnHold: 'Sat i bero',
    Status_Cancelled: 'Annulleret',
    Priority_Critical: 'Kritisk',
    Priority_High: 'Høj',
    Priority_Medium: 'Mellem',
    Priority_Low: 'Lav',
    ProjectStatus_Planning: 'Planlægning',
    ProjectStatus_Active: 'Aktiv',
    ProjectStatus_OnHold: 'Sat i bero',
    ProjectStatus_Completed: 'Fuldført',
    ProjectStatus_Cancelled: 'Annulleret',

    // ── Shell (SmartGantt.tsx) ──
    SmartGantt_LoadingProjects: 'Indlæser projekter…',
    SmartGantt_UnableToLoad: 'Kan ikke indlæse',
    SmartGantt_RetryButton: 'Prøv igen',
    SmartGantt_NoProjectsYet: 'Ingen projekter endnu',
    SmartGantt_NoProjectsSubtitle: 'Opret dit første projekt for at komme i gang.',
    SmartGantt_CreateFirstProjectButton: '+ Opret første projekt',
    SmartGantt_ImportFromExcelButton: '📥 Importer fra Excel',
    SmartGantt_LoadingTasks: 'Indlæser opgaver…',
    SmartGantt_DismissAriaLabel: 'Luk',
    SmartGantt_DeleteTaskDialogTitle: 'Slet opgave',
    SmartGantt_DeleteTaskDialogSubtext: 'Er du sikker på, at du vil slette "{taskTitle}"? Dette kan ikke fortrydes.',
    SmartGantt_DeleteButton: 'Slet',
    SmartGantt_CancelButton: 'Annuller',
    SmartGantt_ArchiveProjectDialogTitle: 'Arkiver projekt',
    SmartGantt_ArchiveProjectDialogSubtext: 'Arkiver "{projectTitle}"? Du kan gendanne det senere.',
    SmartGantt_ArchiveButton: 'Arkiver',
    SmartGantt_SendToRecycleBinDialogTitle: 'Send til papirkurv',
    SmartGantt_SendToRecycleBinDialogSubtext: 'Send "{projectTitle}" til webstedets papirkurv?',
    SmartGantt_SendToRecycleBinButton: 'Send til papirkurv',
    SmartGantt_FailedLoadProjects: 'Kunne ikke indlæse projekter. Kontrollér webstedstilladelser.',
    SmartGantt_FailedLoadTasks: 'Kunne ikke indlæse opgaver for dette projekt.',
    SmartGantt_FailedLoadPortfolioStats: 'Kunne ikke indlæse porteføljestatistik.',
    SmartGantt_CouldNotSaveProject: 'Kunne ikke gemme projektet: {message}',
    SmartGantt_CouldNotDeleteProject: 'Kunne ikke slette projektet: {message}',
    SmartGantt_CouldNotArchiveProject: 'Kunne ikke arkivere projektet: {message}',
    SmartGantt_CouldNotUnarchiveProject: 'Kunne ikke gendanne projektet fra arkiv: {message}',
    SmartGantt_CouldNotSaveTask: 'Kunne ikke gemme opgaven: {message}',
    SmartGantt_CouldNotDeleteTask: 'Kunne ikke slette opgaven: {message}',
    SmartGantt_ImageExportFailed: 'Billedeksport mislykkedes: {message}',
    SmartGantt_PowerPointExportFailed: 'PowerPoint-eksport mislykkedes: {message}',
    SmartGantt_PortfolioExportFailed: 'Porteføljeeksport mislykkedes: {message}',
    SmartGantt_CouldNotUpdateTask: 'Kunne ikke opdatere opgaven: {message}',

    // ── Common ──
    ColorSwatch_AutoColorAriaLabel: 'Automatisk farve',
    ColorSwatch_CustomColorAriaLabel: 'Brugerdefineret farve',
    ColorSwatch_PickCustomColorTitle: 'Vælg en brugerdefineret farve',

    // ── Export (Excel / PowerPoint) ──
    Export_ColTaskName: 'Opgavenavn',
    Export_ColPhase: 'Fase',
    Export_ColStartDate: 'Startdato',
    Export_ColDueDate: 'Forfaldsdato',
    Export_ColStatus: 'Status',
    Export_ColPriority: 'Prioritet',
    Export_ColAssignedTo: 'Tildelt til',
    Export_ColAssignedToEmail: 'E-mail for tildelt til',
    Export_ColPercentComplete: '% fuldført',
    Export_ColIsMilestone: 'Er milepæl',
    Export_ColDescription: 'Beskrivelse',
    Export_ColNotes: 'Noter',
    Export_Yes: 'Ja',
    Export_No: 'Nej',
    Export_SheetNameTasks: 'Opgaver',
    Export_ExcelFileSuffix: ' - Opgaver.xlsx',
    Export_TaskNameColumnLabel: 'OPGAVENAVN',
    Export_ExportedDateLabel: 'Eksporteret {date}',
    Export_ProjectReportLabel: 'PROJEKTRAPPORT',
    Export_StatusLine: 'Status: {status}',
    Export_DateRangeSeparator: ' til ',
    Export_ProjectManagerLine: 'Projektleder: {name}',
    Export_GeneratedDateLine: 'Genereret {date}',
    Export_ProjectSummaryTitle: 'Projektoversigt',
    Export_StatTotalTasks: 'Opgaver i alt',
    Export_StatCompleted: 'Fuldført',
    Export_StatInProgress: 'I gang',
    Export_StatOnHold: 'Sat i bero',
    Export_StatNotStarted: 'Ikke startet',
    Export_OverallProgressLine: 'Samlet fremdrift',
    Export_OverallProgressPercent: '{percent}%',
    Export_StatusBreakdownTitle: 'Statusfordeling',
    Export_StatusBreakdownRow: '{status}: {count} ({percent}%)',
    Export_GanttTimelineTitle: 'Gantt-tidslinje',
    Export_SummaryRecentActivityTitle: 'Seneste aktivitet',
    Export_ProjectOverviewLabel: 'Projektoversigt',
    Export_DetailStatusLabel: 'Status',
    Export_DetailStartDateLabel: 'Startdato',
    Export_DetailDueDateLabel: 'Forfaldsdato',
    Export_DetailProjectManagerLabel: 'Projektleder',
    Export_Past7DaysLabel: 'Seneste 7 dage',
    Export_NoActivityMessage: 'Ingen seneste aktivitet.',
    Export_CompletedThisWeekHeader: 'Fuldført denne uge ({count})',
    Export_NewBadge: 'NY  ',
    Export_CompletedPercentLine: '{percent}% fuldført',
    Export_MoreItemsSuffix: '+ {count} mere',
    Export_InProgressUpdatedHeader: 'I gang / opdateret',
    Export_StatusPercentLine: '{status} — {percent}%',
    Export_PortfolioReportLabel: 'PORTEFØLJERAPPORT',
    Export_PortfolioOverviewTitle: 'Porteføljeoversigt',
    Export_ProjectsCountLine: '{count} projekter',
    Export_HealthSummaryOnTrack: '{count} på sporet',
    Export_HealthSummaryAtRisk: '{count} i risiko',
    Export_HealthSummaryOverdue: '{count} forfaldne',
    Export_ProjectsSummaryHeader: 'Projektoversigt',
    Export_TableProject: 'Projekt',
    Export_TableStatus: 'Status',
    Export_TableHealth: 'Sundhed',
    Export_TableTotal: 'I alt',
    Export_TableDone: 'Færdig',
    Export_TableActive: 'Aktiv',
    Export_TableAtRisk: 'I risiko',
    Export_TableOverdue: 'Forfalden',
    Export_TablePctDone: '% færdig',
    Export_TableDueDate: 'Forfaldsdato',
    Export_PortfolioSummaryFileName: 'Porteføljeoversigt.xlsx',
    Export_PortfolioReportFileName: 'Porteføljerapport.pptx',
    Export_ProjectReportFileName: '{projectName} rapport.pptx',
    Export_UnavailableLabel: 'Ikke tilgængelig',
    Export_SheetNamePortfolio: 'Portefølje',
    Export_ColStart: 'Start',
    Export_ColDue: 'Forfald',
    Export_ImageGenerationFailed: 'Kunne ikke generere billedet – diagrammet er muligvis for stort til at eksportere som billede.',
    Export_DrawingContextFailed: 'Kunne ikke oprette en tegnekontekst til eksporten.',
    Export_SvgRenderFailed: 'SVG-gengivelse mislykkedes',

    // ── Added in v1.5 review ──
    Svc_TooManyDependencies: 'Denne opgave har for mange afhængigheder til at kunne gemmes (grænsen er ca. 60). Fjern nogle, og prøv igen.',
    Svc_TaskChangedByOthers: 'Denne opgave er blevet ændret af en anden, siden du indlæste den. Opdater, og prøv igen.',
    Svc_ProjectChangedByOthers: 'Dette projekt er blevet ændret af en anden, siden du åbnede det. Opdater, og prøv igen.',
    Svc_ColumnCreateFailed: 'Kunne ikke oprette {count} kolonne(r) på den nye opgaveliste: {detail}',
    Svc_BaselineUnavailable: 'Baselines er ikke tilgængelige for dette projekt, fordi baseline-kolonnerne ikke kunne tilføjes (du skal muligvis have tilladelse til at redigere listen).',
    Svc_SubtaskReassignFailed: 'Kunne ikke omfordele denne opgaves underopgaver, før den blev slettet: {detail}',
    Svc_UnresolvedDependency: 'Række {row} ("{title}"): afhængigheden "{name}" kunne ikke matches med en importeret opgave.',
    Svc_SelfDependency: 'Række {row} ("{title}"): afhængigheden "{name}" peger på selve opgaven og blev sprunget over.',
    Svc_ColId: 'ID',
    Svc_ColDependencies: 'Afhængigheder',
    Svc_ColBaselineStart: 'Baseline-start',
    Svc_ColBaselineDue: 'Baseline-frist',
    Svc_CsvFileSuffix: ' - Opgaver.csv',
    Svc_IcsFileSuffix: ' - Milepæle.ics',
    Svc_PortfolioCsvFileName: 'Porteføljeoversigt.csv',
    Svc_PP_DisplayGroup: 'Standarder',
    Svc_PP_DefaultView: 'Standardvisning',
    Svc_PP_ViewGantt: 'Gantt',
    Svc_PP_ViewList: 'Liste',
    Svc_PP_ViewKanban: 'Kanban',
    Svc_PP_ViewDashboard: 'Dashboard',
    Svc_PP_ViewPortfolio: 'Portefølje',
    Svc_PP_DefaultZoom: 'Standardzoom',
    Svc_PP_ZoomDay: 'Dag',
    Svc_PP_ZoomWeek: 'Uge',
    Svc_PP_ZoomMonth: 'Måned',
    Svc_PP_ZoomQuarter: 'Kvartal',
    Svc_PP_CalendarGroup: 'Arbejdskalender',
    Svc_PP_DaySun: 'Søndag er en arbejdsdag',
    Svc_PP_DayMon: 'Mandag er en arbejdsdag',
    Svc_PP_DayTue: 'Tirsdag er en arbejdsdag',
    Svc_PP_DayWed: 'Onsdag er en arbejdsdag',
    Svc_PP_DayThu: 'Torsdag er en arbejdsdag',
    Svc_PP_DayFri: 'Fredag er en arbejdsdag',
    Svc_PP_DaySat: 'Lørdag er en arbejdsdag',
    Svc_PP_Holidays: 'Helligdage (ikke-arbejdsdage)',
    Svc_PP_HolidaysHint: 'Én dato pr. linje i formatet åååå-MM-dd (for eksempel 2026-12-25).',
    Gantt_TimelineAriaLabel: 'Opgavetidslinje',
    Gantt_DragLabel: '{start} → {end} ({days} d.)',
    Gantt_KeyboardMoveAnnouncement: '{taskTitle}: {startDate} til {dueDate}',
    Gantt_KeyboardHint: 'Tryk på Enter for at åbne opgaven. Venstre- og højrepil flytter den én arbejdsdag. Shift sammen med piletasterne ændrer slutdatoen.',
    Gantt_ParentCycleTooltip: 'Denne opgave er en del af en cirkulær kæde af overordnede opgaver og underopgaver, så den vises på øverste niveau',
    Gantt_CollapseAll: 'Skjul alle faser',
    Gantt_ExpandAll: 'Vis alle faser',
    Gantt_BaselineTooltip: 'Baseline: {start} → {due}',
    Gantt_VarianceTooltip: 'Afvigelse i afslutning: {days} dage i forhold til baseline',
    Gantt_LinkHandleTitle: 'Træk over på en anden opgave for at oprette en afhængighed',
    Toolbar_FitToProject: 'Tilpas',
    Toolbar_FitToProjectTitle: 'Zoom for at vise hele projektet',
    Toolbar_UndoTitle: 'Fortryd (Ctrl+Z)',
    Toolbar_RedoTitle: 'Gentag (Ctrl+Y)',
    Toolbar_ExportCsv: '📄 Eksporter opgaver til CSV',
    Toolbar_ExportIcs: '📅 Eksporter milepæle (iCal)',
    Toolbar_Print: '🖨 Udskriv / Gem som PDF',
    Toolbar_SetBaseline: '📐 Angiv baseline…',
    Toolbar_CopyLink: '🔗 Kopiér link',
    Toolbar_CopyLinkTitle: 'Kopiér et link til denne visning (projekt, visning, zoom og filtre)',
    App_UndoButton: 'Fortryd',
    App_Undone: 'Ændringen er fortrudt.',
    App_Redone: 'Ændringen er gentaget.',
    App_DependentsMovedOne: '1 afhængig opgave blev flyttet.',
    App_DependentsMovedMany: '{count} afhængige opgaver blev flyttet.',
    App_TaskConflict: 'Denne opgave er blevet ændret af en anden. De nyeste opgaver er indlæst igen – gennemgå dem, og prøv igen.',
    App_DependencyCycle: 'Dette link ville skabe en cirkulær afhængighed.',
    App_DependencyExists: 'Disse opgaver er allerede linket.',
    App_LinkCopied: 'Linket er kopieret til udklipsholderen.',
    App_LinkCopyFailed: 'Kunne ikke kopiere linket: {message}',
    App_PopupBlocked: 'Udskriftsvinduet blev blokeret. Tillad pop op-vinduer for dette websted, og prøv igen.',
    App_SetBaselineDialogTitle: 'Angiv baseline',
    App_SetBaselineDialogSubtext: 'Vil du gemme de aktuelle start- og forfaldsdatoer for alle {count} opgaver som baseline? En eksisterende baseline erstattes.',
    App_SetBaselineButton: 'Angiv baseline',
    App_BaselineSaved: 'Baseline er gemt.',
    App_BaselineFailed: 'Kunne ikke gemme baseline: {message}',
    App_CsvExportFailed: 'CSV-eksport mislykkedes: {message}',
    App_IcsExportFailed: 'Kalendereksport mislykkedes: {message}',
    App_BulkDeleteDialogTitle: 'Slet opgaver',
    App_BulkDeleteDialogSubtext: 'Er du sikker på, at du vil slette {count} opgaver? Dette kan ikke fortrydes.',
    Common_PeoplePicker_ClearAriaLabel: 'Ryd',
    Common_PeoplePicker_DirectoryHeader: 'Personer i biblioteket',
    Common_PeoplePicker_EmailLabel: 'E-mail (valgfrit)',
    Common_PeoplePicker_EmailPlaceholder: 'navn@virksomhed.dk',
    Common_PeoplePicker_ExternalHint: 'Ikke i biblioteket. Gemmes som fri tekst.',
    Common_PeoplePicker_InvalidEmail: 'Angiv en gyldig e-mailadresse.',
    Common_PeoplePicker_ListAriaLabel: 'Forslag til personer',
    Common_PeoplePicker_RecentHeader: 'Senest brugt',
    Common_PeoplePicker_ResultsAnnouncement: '{count} forslag tilgængelige',
    Common_PeoplePicker_Searching: 'Søger…',
    Common_PeoplePicker_UseExternal: 'Brug "{name}" (ekstern / ikke i biblioteket)',
    Import_Mapper_PreviewFirstRows: 'Eksempelvisning (første {count} rækker)',
    Import_Mapper_RequiredLegend: 'Obligatorisk felt',
    Import_Mapper_RequiredMarkerLabel: 'Obligatorisk',
    Import_Mapper_SelectAriaLabel: 'Målfelt for kolonnen {columnName}',
    Import_Panel_DateOrderAuto: 'Registrer automatisk',
    Import_Panel_DateOrderDMY: 'Dag/måned/år (31/12/2026)',
    Import_Panel_DateOrderDetected: 'Registreret fra din fil: {order}.',
    Import_Panel_DateOrderHint: 'Gælder for datoer skrevet med tal, f.eks. 03/04/2026.',
    Import_Panel_DateOrderLabel: 'Datorækkefølge',
    Import_Panel_DateOrderMDY: 'Måned/dag/år (12/31/2026)',
    Import_Panel_DropZoneAriaLabel: 'Vælg en fil, der skal importeres. Tryk på Enter for at gennemse.',
    Import_Panel_DropZoneChangeAriaLabel: 'Valgt fil {fileName}. Tryk på Enter for at vælge en anden fil.',
    Import_Panel_FailedCount: '{count} mislykkedes',
    Import_Panel_NewProjectIntroMany: 'Der oprettes et nyt projekt, og alle {count} opgaver importeres til det. Du kan ændre disse oplysninger når som helst efter importen.',
    Import_Panel_NewProjectIntroOne: 'Der oprettes et nyt projekt, og {count} opgave importeres til det. Du kan ændre disse oplysninger når som helst efter importen.',
    Import_Panel_PlanAriaLabel: '{planName}, {groupName}',
    Import_Panel_ProblemEndBeforeStart: 'Forfaldsdatoen ligger før startdatoen',
    Import_Panel_ProblemInvalidDueDate: 'Forfaldsdatoen "{value}" er ikke en gyldig dato',
    Import_Panel_ProblemInvalidStartDate: 'Startdatoen "{value}" er ikke en gyldig dato',
    Import_Panel_ProblemMissingTitle: 'Opgavenavn mangler',
    Import_Panel_ProgressLabelWithPercent: '{done} af {total} ({percent} %)',
    Import_Panel_SkipInvalidRows: 'Spring rækker med problemer over',
    Import_Panel_SuccessWithWarningsMany: 'Importen lykkedes med {count} advarsler.',
    Import_Panel_SuccessWithWarningsOne: 'Importen lykkedes med {count} advarsel.',
    Import_Panel_ValidationHeader: 'Rækker med problemer',
    Import_Panel_ValidationMore: '…og {count} flere',
    Import_Panel_ValidationRow: 'Række {rowNum}: {problem}',
    Import_Panel_ValidationSummaryMany: '{count} rækker har problemer',
    Import_Panel_ValidationSummaryOne: '{count} række har et problem',
    Import_Panel_WarningsLabel: 'Advarsler ({count}):',
    Panel_Project_ManagerLabel: 'Projektleder',
    Panel_Project_ManagerPlaceholder: 'Søg efter personer, eller skriv et navn…',
    Panel_Task_BaselineDueLabel: 'Baseline-afslutning',
    Panel_Task_BaselineHeader: 'Baseline',
    Panel_Task_BaselineStartLabel: 'Baseline-start',
    Panel_Task_DepTypeFF: 'Slut til slut (FF)',
    Panel_Task_DepTypeFS: 'Slut til start (FS)',
    Panel_Task_DepTypeSF: 'Start til slut (SF)',
    Panel_Task_DepTypeSS: 'Start til start (SS)',
    Panel_Task_LagAriaLabel: 'Forsinkelse i arbejdsdage for {taskTitle}',
    Panel_Task_LagHint: 'Forsinkelse angives i arbejdsdage. Brug et negativt tal for fremskyndelse.',
    Panel_Task_LinkTypeAriaLabel: 'Linktype for {taskTitle}',
    Panel_Task_VarianceEarlier: '{days} arbejdsdag(e) tidligere',
    Panel_Task_VarianceLater: '{days} arbejdsdag(e) senere',
    Panel_Task_VarianceOnBaseline: 'på baseline',
    View_Dashboard_BurndownActual: 'Faktisk',
    View_Dashboard_BurndownAria: 'Burndown-diagram: {remaining} af {total} opgaver tilbage',
    View_Dashboard_BurndownHeader: 'Burndown (resterende opgaver)',
    View_Dashboard_BurndownIdeal: 'Ideel',
    View_Dashboard_BurndownNoData: 'Ikke nok opgaver med datoer til at tegne et burndown.',
    View_Dashboard_CriticalPathHeader: 'Kritisk vej  ({count})',
    View_Dashboard_PhaseDoneSummary: '{done}/{total} færdige  •  {percent} %',
    View_Dashboard_TaskRowAriaLabel: 'Åbn opgaven {taskTitle}, {status}',
    View_Dashboard_WorkloadHeader: 'Arbejdsbyrde pr. ansvarlig',
    View_Dashboard_WorkloadOpen: '{count} åbne',
    View_Dashboard_WorkloadOverdue: '{count} forsinkede',
    View_Kanban_AddTaskInColumnAriaLabel: 'Tilføj opgave til {column}',
    View_Kanban_CollapseColumn: 'Skjul kolonnen {column}',
    View_Kanban_ExpandColumn: 'Vis kolonnen {column}',
    View_Kanban_LaneHeader: '{name} ({count})',
    View_Kanban_LaneNoPhase: 'Ingen fase',
    View_Kanban_LaneUnassigned: 'Ikke tildelt',
    View_Kanban_LanesAssignee: 'Ansvarlig',
    View_Kanban_LanesNone: 'Ingen',
    View_Kanban_LanesPhase: 'Fase',
    View_Kanban_SwimlanesLabel: 'Swimlanes',
    View_Kanban_WipEditTitle: 'Angiv grænse for igangværende arbejde for {column} (0 for ingen grænse)',
    View_Kanban_WipExceededTitle: 'WIP-grænse overskredet: {count} af {limit}',
    View_Kanban_WipInputAriaLabel: 'WIP-grænse for {column}',
    View_Kanban_WipLabel: 'WIP {count}/{limit}',
    View_Kanban_WipSet: 'WIP',
    View_List_BulkAssignApply: 'Tildel',
    View_List_BulkAssigneePlaceholder: 'Tildel til…',
    View_List_BulkBarAriaLabel: 'Massehandlinger for valgte opgaver',
    View_List_BulkClear: 'Ryd markering',
    View_List_BulkDelete: 'Slet valgte',
    View_List_BulkPercentApply: 'Angiv %',
    View_List_BulkPercentPlaceholder: '% færdig',
    View_List_BulkPriorityPlaceholder: 'Angiv prioritet…',
    View_List_BulkSelectedCount: '{count} valgt',
    View_List_BulkStatusPlaceholder: 'Angiv status…',
    View_List_ExportCsv: 'Eksporter CSV',
    View_List_NonWorkingDay: 'Ikke-arbejdsdag',
    View_List_SelectAllAriaLabel: 'Markér alle opgaver',
    View_List_SelectRowAriaLabel: 'Markér {taskTitle}',
    View_Portfolio_CardAriaLabel: 'Åbn projektet {projectName}, {status}',
    View_Portfolio_ClearFilters: 'Ryd filtre',
    View_Portfolio_FilteredCount: '{shown} af {total} projekter',
    View_Portfolio_HideDone: 'Skjul afsluttede / annullerede',
    View_Portfolio_NoMatches: 'Ingen projekter matcher dine filtre.',
    View_Portfolio_ProjectCountMany: '{count} projekter',
    View_Portfolio_ProjectCountOne: '{count} projekt',
    View_Portfolio_SearchAriaLabel: 'Søg efter projekter',
    View_Portfolio_SearchPlaceholder: 'Søg efter projekter…',
    Import_Panel_CopyDetails: 'Kopiér detaljer',
    Import_Panel_Copied: 'Kopieret',
  };
});
