define([], function () {
  return {
    // ── Property pane ──
    PropertyPane_HeaderDescription: 'Ρυθμίσεις Smart Gantt Chart',
    PropertyPane_GeneralGroupName: 'Γενικά',
    PropertyPane_TitleFieldLabel: 'Τίτλος Web Part',
    WebPart_DefaultTitle: 'Smart Gantt Chart',

    // ── Toolbar ──
    Toolbar_ViewDashboard: 'Πίνακας Ελέγχου',
    Toolbar_ViewList: 'Λίστα',
    Toolbar_ViewGantt: 'Gantt',
    Toolbar_ViewKanban: 'Kanban',
    Toolbar_ZoomDay: 'Ημέρα',
    Toolbar_ZoomWeek: 'Εβδομάδα',
    Toolbar_ZoomMonth: 'Μήνας',
    Toolbar_ZoomQuarter: 'Τρίμηνο',
    Toolbar_SelectProjectAriaLabel: 'Επιλογή έργου',
    Toolbar_PortfolioLabel: 'Χαρτοφυλάκιο',
    Toolbar_SelectAProject: 'Επιλέξτε ένα Έργο',
    Toolbar_AllProjectsSubtext: 'Όλα τα έργα',
    Toolbar_NoProjectsYet: 'Δεν υπάρχουν ακόμη έργα',
    Toolbar_ArchivedBadge: 'Αρχειοθετημένο',
    Toolbar_ShowArchivedProjects: 'Εμφάνιση αρχειοθετημένων έργων',
    Toolbar_NewProject: '+ Νέο Έργο',
    Toolbar_ImportFileAsNewProject: '📥 Εισαγωγή Αρχείου ως Νέο Έργο…',
    Toolbar_AddTask: '+ Προσθήκη Εργασίας',
    Toolbar_EditProject: 'Επεξεργασία Έργου',
    Toolbar_OptionsButton: '⚙ Επιλογές',
    Toolbar_MoreOptionsTitle: 'Περισσότερες επιλογές',
    Toolbar_ExportToExcel: '📊 Εξαγωγή σε Excel',
    Toolbar_ExportToPowerPoint: '📑 Εξαγωγή σε PowerPoint',
    Toolbar_ScrollToTodayTitle: 'Μετάβαση σε σήμερα',
    Toolbar_TodayButton: '◉ Σήμερα',
    Toolbar_ImportTasks: '📥 Εισαγωγή Εργασιών…',
    Toolbar_ExportAsImage: '🖼 Εξαγωγή ως Εικόνα (PNG)',
    Toolbar_UnarchiveProject: '📂 Κατάργηση Αρχειοθέτησης Έργου',
    Toolbar_ArchiveProject: '🗄️ Αρχειοθέτηση Έργου',
    Toolbar_SendToRecycleBin: '🗑️ Αποστολή στον Κάδο Ανακύκλωσης',

    // ── Filter bar ──
    FilterBar_ClearOption: 'Εκκαθάριση',
    FilterBar_DueAny: 'Οποιαδήποτε ημερομηνία λήξης',
    FilterBar_DueOverdue: 'Εκπρόθεσμο',
    FilterBar_DueToday: 'Λήγει σήμερα',
    FilterBar_DueWeek: 'Λήγει σε 7 ημέρες',
    FilterBar_SearchPlaceholder: 'Αναζήτηση εργασιών…',
    FilterBar_SearchAriaLabel: 'Αναζήτηση εργασιών',
    FilterBar_StatusChipLabel: 'Κατάσταση',
    FilterBar_PriorityChipLabel: 'Προτεραιότητα',
    FilterBar_AssigneeChipLabel: 'Ανάδοχος',
    FilterBar_PhaseChipLabel: 'Φάση',
    FilterBar_DueDateAriaLabel: 'Φιλτράρισμα κατά ημερομηνία λήξης',
    FilterBar_MatchCount: '{matchCount} από {totalCount}',
    FilterBar_ClearFilters: '✕ Εκκαθάριση φίλτρων',
    FilterBar_ChipLabelWithCount: '{label} ({count}) ▾',
    FilterBar_ChipLabelNoCount: '{label} ▾',

    // ── Gantt view ──
    Gantt_TaskColumnHeader: 'Εργασία',
    Gantt_DurationColumnHeader: 'Διάρκ.',
    Gantt_AddTaskButton: '+ Προσθήκη Εργασίας',
    Gantt_EmptyTitle: 'Δεν υπάρχουν ακόμη εργασίες',
    Gantt_EmptySubtitle: 'Προσθέστε εργασίες για να τις δείτε στο διάγραμμα Gantt.',
    Gantt_AddFirstTask: '+ Προσθήκη Πρώτης Εργασίας',
    Gantt_ImportTasksButton: '📥 Εισαγωγή Εργασιών',
    Gantt_EditTitle: 'Επεξεργασία',
    Gantt_DeleteTitle: 'Διαγραφή',
    Gantt_EditTaskAriaLabel: 'Επεξεργασία εργασίας {taskTitle}',
    Gantt_DeleteTaskAriaLabel: 'Διαγραφή εργασίας {taskTitle}',
    Gantt_ExpandPhaseAriaLabel: '{action} φάσης {phase}',
    Gantt_ExpandAction: 'Ανάπτυξη',
    Gantt_CollapseAction: 'Σύμπτυξη',
    Gantt_DependencyViolationTooltip: 'Ξεκίνησε πριν ολοκληρωθούν όλες οι εξαρτήσεις',
    Gantt_MilestoneAriaLabel: '{taskTitle}, ορόσημο, {date}',
    Gantt_BarAriaLabel: '{taskTitle}, {startDate} έως {dueDate}, {percent}% ολοκληρωμένο',
    Gantt_PercentCompleteTooltip: '{value}% ολοκληρωμένο',

    // ── Gantt options/settings panel ──
    GanttSettings_PanelHeader: '⚙ Επιλογές',
    GanttSettings_ColorCodingSection: 'Χρωματική Κωδικοποίηση',
    GanttSettings_ByStatus: 'Κατά Κατάσταση',
    GanttSettings_ByPriority: 'Κατά Προτεραιότητα',
    GanttSettings_ByPhase: 'Κατά Φάση',
    GanttSettings_ByHealth: 'Κατά Υγεία',
    GanttSettings_HeaderColorSection: 'Χρώμα Κεφαλίδας',
    GanttSettings_ThemeDark: 'Σκούρο',
    GanttSettings_ThemeNavy: 'Ναυτικό Μπλε',
    GanttSettings_ThemeTeal: 'Γαλαζοπράσινο',
    GanttSettings_ThemePurple: 'Μωβ',
    GanttSettings_ThemeLight: 'Ανοιχτόχρωμο',
    GanttSettings_HeaderLabelsSection: 'Ετικέτες Κεφαλίδας',
    GanttSettings_WeekLabelDates: 'Ημερομηνίες',
    GanttSettings_WeekLabelDatesDesc: '3 Ιουν, 10 Ιουν…',
    GanttSettings_WeekLabelProject: 'Εβδομάδες Έργου',
    GanttSettings_WeekLabelProjectDesc: 'Ε1, Ε2…',
    GanttSettings_WeekLabelIso: 'Ημερολογιακές Εβδομάδες',
    GanttSettings_WeekLabelIsoDesc: 'Ε23, Ε24…',
    GanttSettings_ProjectWeeksHint: 'Η Εβδομάδα 1 ξεκινά από τη Δευτέρα της παλαιότερης εργασίας σας — ιδανικό για παρουσιάσεις.',
    GanttSettings_BarStyleSection: 'Στυλ Γραμμής',
    GanttSettings_BarStyleGradient: 'Διαβάθμιση',
    GanttSettings_BarStyleFlat: 'Επίπεδο',
    GanttSettings_RowHeightSection: 'Ύψος Γραμμής',
    GanttSettings_HeightCompact: 'Συμπαγές',
    GanttSettings_HeightNormal: 'Κανονικό',
    GanttSettings_HeightSpacious: 'Ευρύχωρο',
    GanttSettings_ShowHideSection: 'Εμφάνιση / Απόκρυψη',
    GanttSettings_WeekendShading: 'Σκίαση Σαββατοκύριακου',
    GanttSettings_DependencyArrows: 'Βέλη εξαρτήσεων',
    GanttSettings_CriticalPathAlwaysVisible: 'Η κρίσιμη διαδρομή πάντα ορατή',
    GanttSettings_AllOthersOnHoverOnly: 'Όλα τα υπόλοιπα μόνο με πέρασμα ποντικιού',
    GanttSettings_CriticalPathHighlight: 'Επισήμανση κρίσιμης διαδρομής',
    GanttSettings_ProgressPercentOnBars: '% Προόδου στις γραμμές',
    GanttSettings_AssigneeNameOnBars: 'Όνομα αναδόχου στις γραμμές',
    GanttSettings_HealthStatusBadges: 'Σήματα κατάστασης υγείας',

    // ── List view ──
    ListView_ColTaskName: 'Όνομα Εργασίας',
    ListView_ColStatus: 'Κατάσταση',
    ListView_ColHealth: 'Υγεία',
    ListView_ColPriority: 'Προτεραιότητα',
    ListView_ColStart: 'Έναρξη',
    ListView_ColDue: 'Λήξη',
    ListView_ColAssignedTo: 'Ανατέθηκε σε',
    ListView_ColProgress: 'Πρόοδος',
    ListView_ColPhase: 'Φάση',
    ListView_ColPredecessors: 'Προαπαιτούμενα',
    ListView_EmptyTitle: 'Δεν υπάρχουν ακόμη εργασίες',
    ListView_AddFirstTask: '+ Προσθήκη Πρώτης Εργασίας',
    ListView_AddTaskRow: '+ Προσθήκη Εργασίας',
    ListView_Unassigned: 'Μη ανατεθειμένο',
    ListView_DependencyViolationTooltip: 'Ξεκίνησε πριν ολοκληρωθούν όλες οι εξαρτήσεις',
    ListView_StatusAriaLabel: 'Κατάσταση του {taskTitle}',
    ListView_PriorityAriaLabel: 'Προτεραιότητα του {taskTitle}',
    ListView_EditTaskAriaLabel: 'Επεξεργασία εργασίας {taskTitle}',
    ListView_DeleteTaskAriaLabel: 'Διαγραφή εργασίας {taskTitle}',
    ListView_EditTitle: 'Επεξεργασία',
    ListView_DeleteTitle: 'Διαγραφή',

    // ── Kanban view ──
    Kanban_ColumnNotStarted: 'Δεν Έχει Ξεκινήσει',
    Kanban_ColumnInProgress: 'Σε Εξέλιξη',
    Kanban_ColumnOnHold: 'Σε Αναμονή',
    Kanban_ColumnCompleted: 'Ολοκληρωμένο',
    Kanban_ColumnCancelled: 'Ακυρωμένο',
    Kanban_AddTaskButton: '+ Προσθήκη Εργασίας',
    Kanban_EditTitle: 'Επεξεργασία',
    Kanban_DeleteTitle: 'Διαγραφή',
    Kanban_CardAriaLabel: '{taskTitle}, {status}. Πατήστε Enter για επεξεργασία, Αριστερό ή Δεξί βέλος για αλλαγή κατάστασης.',
    Kanban_EditTaskAriaLabel: 'Επεξεργασία εργασίας {taskTitle}',
    Kanban_DeleteTaskAriaLabel: 'Διαγραφή εργασίας {taskTitle}',

    // ── Dashboard view ──
    Dashboard_TotalTasks: 'Σύνολο Εργασιών',
    Dashboard_Completed: 'Ολοκληρωμένες',
    Dashboard_InProgress: 'Σε Εξέλιξη',
    Dashboard_OnHold: 'Σε Αναμονή',
    Dashboard_NotStarted: 'Δεν Έχουν Ξεκινήσει',
    Dashboard_Cancelled: 'Ακυρωμένες',
    Dashboard_OverallProgress: 'Συνολική Πρόοδος',
    Dashboard_ProjectManagerLabel: 'Διαχειριστής Έργου: {name}',
    Dashboard_PhaseProgressHeader: 'Πρόοδος Φάσεων',
    Dashboard_StatusBreakdownHeader: 'Ανάλυση Κατάστασης',
    Dashboard_PriorityBreakdownHeader: 'Ανάλυση Προτεραιότητας',
    Dashboard_PriorityCritical: 'Κρίσιμη',
    Dashboard_PriorityHigh: 'Υψηλή',
    Dashboard_PriorityMedium: 'Μεσαία',
    Dashboard_PriorityLow: 'Χαμηλή',
    Dashboard_OverdueHeader: 'Εκπρόθεσμες  ({count})',
    Dashboard_DueNext14DaysHeader: 'Λήγουν τις επόμενες 14 ημέρες  ({count})',
    Dashboard_CompletedThisWeekHeader: 'Ολοκληρώθηκαν Αυτή την Εβδομάδα',
    Dashboard_UpdatedThisWeekHeader: 'Ενημερώθηκαν Αυτή την Εβδομάδα',
    Dashboard_Today: 'Σήμερα',
    Dashboard_Tomorrow: 'Αύριο',
    Dashboard_DaysLeft: '{days}η',
    Dashboard_EmptyTitle: 'Δεν υπάρχουν ακόμη εργασίες',
    Dashboard_EmptySubtitle: 'Προσθέστε εργασίες για να δείτε τον πίνακα ελέγχου του έργου σας.',
    Dashboard_AddTaskButton: '+ Προσθήκη Εργασίας',

    // ── Portfolio view ──
    Portfolio_ProjectCount: '{count} Έργο{plural}',
    Portfolio_OnTrackSummary: '{count} Εντός Χρονοδιαγράμματος',
    Portfolio_AtRiskSummary: '{count} Σε Κίνδυνο',
    Portfolio_OverdueSummary: '{count} Εκπρόθεσμα',
    Portfolio_DoneSummary: '{count} Ολοκληρωμένα',
    Portfolio_SortLabel: 'Ταξινόμηση:',
    Portfolio_SortAZ: 'Α-Ω',
    Portfolio_SortHealth: 'Υγεία',
    Portfolio_SortStatus: 'Κατάσταση',
    Portfolio_SortCompletion: 'Ολοκλήρωση',
    Portfolio_RefreshTitle: 'Ανανέωση',
    Portfolio_RefreshButton: 'Ανανέωση',
    Portfolio_LoadingStats: 'Φόρτωση στατιστικών…',
    Portfolio_EmptyTitle: 'Δεν υπάρχουν ακόμη έργα',
    Portfolio_CreateFirstProject: '+ Δημιουργία Πρώτου Έργου',
    Portfolio_StatsUnavailable: 'Τα στατιστικά δεν είναι διαθέσιμα',
    Portfolio_StatsUnavailableDetail: 'Δεν ήταν δυνατή η φόρτωση στατιστικών για αυτό το έργο.',
    Portfolio_OverallProgressLabel: 'Συνολική Πρόοδος',
    Portfolio_TaskCountDone: 'Ολοκληρωμένες',
    Portfolio_TaskCountActive: 'Ενεργές',
    Portfolio_TaskCountAtRisk: 'Σε Κίνδυνο',
    Portfolio_TaskCountOverdue: 'Εκπρόθεσμες',
    Portfolio_ViewGanttLink: 'Προβολή Gantt →',
    Portfolio_TodayTooltip: 'Σήμερα',

    // ── Task panel ──
    TaskPanel_EditHeader: 'Επεξεργασία: {taskTitle}',
    TaskPanel_NewTaskHeader: 'Νέα Εργασία',
    TaskPanel_TabBasic: 'Βασικά',
    TaskPanel_TabDetails: 'Λεπτομέρειες',
    TaskPanel_TabLinks: 'Συνδέσεις',
    TaskPanel_ProjectLabelPrefix: 'Έργο: ',
    TaskPanel_TaskNameLabel: 'Όνομα Εργασίας',
    TaskPanel_TaskNamePlaceholder: 'Εισαγάγετε όνομα εργασίας',
    TaskPanel_TaskNameRequired: 'Το όνομα εργασίας είναι υποχρεωτικό',
    TaskPanel_DescriptionLabel: 'Περιγραφή',
    TaskPanel_DescriptionPlaceholder: 'Εισαγάγετε περιγραφή',
    TaskPanel_StartDateLabel: 'Ημερομηνία Έναρξης',
    TaskPanel_DueDateLabel: 'Ημερομηνία Λήξης',
    TaskPanel_DueDateError: 'Η ημερομηνία λήξης πρέπει να είναι ίδια ή μεταγενέστερη της ημερομηνίας έναρξης',
    TaskPanel_StatusLabel: 'Κατάσταση',
    TaskPanel_PriorityLabel: 'Προτεραιότητα',
    TaskPanel_PercentCompleteLabel: '% Ολοκλήρωσης: {percent}%',
    TaskPanel_AssignedToLabel: 'Ανατέθηκε σε',
    TaskPanel_AssignedToPlaceholder: 'Αναζήτηση ατόμων…',
    TaskPanel_PhaseLabel: 'Φάση',
    TaskPanel_PhasePlaceholder: 'Εισαγάγετε όνομα φάσης',
    TaskPanel_PhaseHint: 'Ομαδοποιεί εργασίες στις προβολές Gantt και Λίστα.',
    TaskPanel_MilestoneLabel: 'Ορόσημο',
    TaskPanel_MilestoneOnText: 'Ναι',
    TaskPanel_MilestoneOffText: 'Όχι',
    TaskPanel_CustomBarColorLabel: 'Προσαρμοσμένο Χρώμα Γραμμής',
    TaskPanel_CustomBarColorOptionalSuffix: ' (προαιρετικό)',
    TaskPanel_AutoColorHint: 'Αυτόματο χρώμα από τις ρυθμίσεις κατάστασης/προτεραιότητας/φάσης.',
    TaskPanel_NotesLabel: 'Σημειώσεις',
    TaskPanel_NotesPlaceholder: 'Εισαγάγετε σημειώσεις',
    TaskPanel_ParentTaskLabel: 'Γονική Εργασία',
    TaskPanel_ParentTaskNone: '(καμία)',
    TaskPanel_ParentTaskHasChildrenHint: 'Αυτή η εργασία έχει υποεργασίες και δεν μπορεί να έχει δική της γονική εργασία.',
    TaskPanel_ParentTaskHint: 'Εμφωλεύστε αυτή την εργασία κάτω από μια άλλη ως υποεργασία.',
    TaskPanel_DependsOnLabel: 'Εξαρτάται από',
    TaskPanel_RemoveDependencyTitle: 'Κατάργηση εξάρτησης από "{taskTitle}"',
    TaskPanel_AddDependencyPlaceholder: 'Προσθήκη εξάρτησης…',
    TaskPanel_SelectATaskOption: 'Επιλέξτε μια εργασία…',
    TaskPanel_DependsOnHint: 'Η εργασία δεν μπορεί να ξεκινήσει μέχρι να ολοκληρωθούν αυτές.',
    TaskPanel_SavingLabel: 'Αποθήκευση…',
    TaskPanel_CreatingLabel: 'Δημιουργία…',
    TaskPanel_SaveChangesButton: 'Αποθήκευση Αλλαγών',
    TaskPanel_CreateTaskButton: 'Δημιουργία Εργασίας',
    TaskPanel_CancelButton: 'Άκυρο',
    TaskPanel_DismissAriaLabel: 'Απόρριψη',
    TaskPanel_DiscardUnsavedChangesConfirm: 'Απόρριψη μη αποθηκευμένων αλλαγών;',
    TaskPanel_SaveFallbackError: 'Δεν ήταν δυνατή η αποθήκευση της εργασίας.',

    // ── Project panel ──
    ProjectPanel_EditHeader: 'Επεξεργασία Έργου',
    ProjectPanel_NewHeader: 'Νέο Έργο',
    ProjectPanel_ProjectNameLabel: 'Όνομα Έργου',
    ProjectPanel_ProjectNamePlaceholder: 'Εισαγάγετε όνομα έργου',
    ProjectPanel_ProjectNameRequired: 'Το όνομα έργου είναι υποχρεωτικό',
    ProjectPanel_DescriptionLabel: 'Περιγραφή',
    ProjectPanel_DescriptionPlaceholder: 'Εισαγάγετε περιγραφή',
    ProjectPanel_ProjectColorLabel: 'Χρώμα Έργου',
    ProjectPanel_StatusLabel: 'Κατάσταση',
    ProjectPanel_StartDateLabel: 'Ημερομηνία Έναρξης',
    ProjectPanel_DueDateLabel: 'Ημερομηνία Λήξης',
    ProjectPanel_DueDateError: 'Η ημερομηνία λήξης πρέπει να είναι ίδια ή μεταγενέστερη της ημερομηνίας έναρξης',
    ProjectPanel_WhatHappensNextTitle: 'Τι ακολουθεί;',
    ProjectPanel_WhatHappensNextBody: 'Μόλις δημιουργηθεί το έργο, θα μπορείτε να προσθέτετε εργασίες, να ορίζετε φάσεις και να παρακολουθείτε την πρόοδο.',
    ProjectPanel_SavingLabel: 'Αποθήκευση…',
    ProjectPanel_CreatingLabel: 'Δημιουργία…',
    ProjectPanel_SaveChangesButton: 'Αποθήκευση Αλλαγών',
    ProjectPanel_CreateProjectButton: 'Δημιουργία Έργου',
    ProjectPanel_CancelButton: 'Άκυρο',
    ProjectPanel_DismissAriaLabel: 'Απόρριψη',
    ProjectPanel_DiscardUnsavedChangesConfirm: 'Απόρριψη μη αποθηκευμένων αλλαγών;',
    ProjectPanel_SaveFallbackError: 'Δεν ήταν δυνατή η αποθήκευση του έργου.',

    // ── Import panel ──
    ImportPanel_SourceExcelTitle: 'Αρχείο Excel / CSV',
    ImportPanel_SourceExcelSubtitle: 'Εισαγωγή εργασιών από υπολογιστικό φύλλο',
    ImportPanel_SourcePlannerTitle: 'Microsoft Planner',
    ImportPanel_SourcePlannerSubtitle: 'Εισαγωγή εργασιών από ένα σχέδιο Planner',
    ImportPanel_ClickToBrowse: 'Κάντε κλικ για περιήγηση',
    ImportPanel_DragDropSuffix: ' ή σύρετε και αφήστε',
    ImportPanel_SupportedExtensions: 'Υποστηρίζει .xlsx, .xls, .csv',
    ImportPanel_RowsColsSummary: '{rows} γραμμές, {cols} στήλες εντοπίστηκαν',
    ImportPanel_LoadingPlannerPlans: 'Φόρτωση σχεδίων Planner…',
    ImportPanel_PlannerLoadError: 'Δεν ήταν δυνατή η φόρτωση σχεδίων Planner.',
    ImportPanel_PlannerPermissionsHintPrefix: 'Βεβαιωθείτε ότι έχετε πρόσβαση στο Planner και ότι η εφαρμογή ',
    ImportPanel_PlannerPermissionsHintEmphasis: 'Tasks by Planner and To Do',
    ImportPanel_PlannerPermissionsHintSuffix: ' είναι διαθέσιμη σε αυτόν τον ιστότοπο.',
    ImportPanel_NoPlannerPlansFoundTitle: 'Δεν βρέθηκαν σχέδια Planner',
    ImportPanel_NoPlannerPlansFoundBody: 'Ίσως δεν έχετε πρόσβαση σε κανένα σχέδιο Planner, ή δεν υπάρχει κανένα για αυτόν τον λογαριασμό.',
    ImportPanel_TaskCountFoundIn: '{count} εργασίες βρέθηκαν στο "{planName}"',
    ImportPanel_ProjectDetailsIntroPrefix: 'Εισαγωγή στο ',
    ImportPanel_ProjectDetailsIntroSuffix: '. Ελέγξτε τα στοιχεία του έργου παρακάτω.',
    ImportPanel_ProjectNameLabel: 'Όνομα Έργου',
    ImportPanel_DescriptionLabel: 'Περιγραφή',
    ImportPanel_StatusLabel: 'Κατάσταση',
    ImportPanel_ColorLabel: 'Χρώμα',
    ImportPanel_MapIntro: 'Αντιστοιχίστε τις στήλες του αρχείου σας στα πεδία εργασίας.',
    ImportPanel_CreatingProjectStatus: 'Δημιουργία έργου…',
    ImportPanel_ImportingTasksStatus: 'Εισαγωγή εργασιών…',
    ImportPanel_ProgressLabel: '{done} από {total}',
    ImportPanel_CouldNotCreateProject: 'Δεν ήταν δυνατή η δημιουργία του έργου.',
    ImportPanel_ImportCompletedWithErrors: 'Η εισαγωγή ολοκληρώθηκε με {count} σφάλμα(τα).',
    ImportPanel_ProjectCreatedSuccess: 'Το έργο δημιουργήθηκε με επιτυχία!',
    ImportPanel_ImportSuccessful: 'Η εισαγωγή ήταν επιτυχής!',
    ImportPanel_TasksAddedTo: '{count} εργασίες προστέθηκαν στο "{projectName}"',
    ImportPanel_FailedRowsLabel: 'Γραμμές που απέτυχαν:',
    ImportPanel_CloseButton: 'Κλείσιμο',
    ImportPanel_OpenProjectButton: 'Άνοιγμα Έργου',
    ImportPanel_ViewImportedTasksButton: 'Προβολή Εισαγόμενων Εργασιών',
    ImportPanel_NextMapColumnsButton: 'Επόμενο: Αντιστοίχιση Στηλών',
    ImportPanel_ImportNTasksButton: 'Εισαγωγή {count} Εργασιών',
    ImportPanel_BackButton: 'Πίσω',
    ImportPanel_CancelButton: 'Άκυρο',
    ImportPanel_NextButton: 'Επόμενο',
    ImportPanel_StepSource: 'Πηγή',
    ImportPanel_StepProject: 'Έργο',
    ImportPanel_StepMap: 'Αντιστοίχιση',
    ImportPanel_StepImport: 'Εισαγωγή',
    ImportPanel_StepDone: 'Ολοκληρώθηκε',
    ImportPanel_ImportAsNewProjectHeader: 'Εισαγωγή Αρχείου ως Νέο Έργο',
    ImportPanel_ImportIntoProjectHeader: 'Εισαγωγή Εργασιών στο {projectName}',
    ImportPanel_CouldNotParseFile: 'Δεν ήταν δυνατή η ανάλυση του αρχείου.',
    ImportPanel_CouldNotLoadPlannerTasks: 'Δεν ήταν δυνατή η φόρτωση εργασιών από αυτό το σχέδιο.',
    ImportPanel_CouldNotCreateProjectDetail: 'Δεν ήταν δυνατή η δημιουργία έργου: {detail}',
    ImportPanel_CouldNotLinkDependencies: 'Δεν ήταν δυνατή η σύνδεση εξαρτήσεων: {detail}',
    ImportPanel_UnknownError: 'άγνωστο σφάλμα',

    // ── Column mapper (import) ──
    ColumnMapper_TaskNameRequiredBanner: 'Το Όνομα Εργασίας πρέπει να αντιστοιχιστεί για να συνεχίσετε.',
    ColumnMapper_SkippedColumnsBanner: '{count} στήλη(ες) θα παραλειφθούν.',
    ColumnMapper_SourceColumnHeader: 'Στήλη Πηγής',
    ColumnMapper_TargetFieldHeader: 'Πεδίο Προορισμού',
    ColumnMapper_StatusHeader: 'Κατάσταση',
    ColumnMapper_SkippedBadge: 'Παραλείφθηκε',
    ColumnMapper_AutoMappedBadge: 'Αυτόματη αντιστοίχιση',
    ColumnMapper_SetBadge: 'Ορίστηκε',
    ColumnMapper_PreviewTitle: 'Προεπισκόπηση: {columnName}',
    ColumnMapper_EmptyCellDash: '—',

    // ── Import field display names / ImportService ──
    ImportField_TaskName: 'Όνομα Εργασίας',
    ImportField_StartDate: 'Ημερομηνία Έναρξης',
    ImportField_DueDate: 'Ημερομηνία Λήξης',
    ImportField_Status: 'Κατάσταση',
    ImportField_Priority: 'Προτεραιότητα',
    ImportField_AssignedTo: 'Ανατέθηκε σε',
    ImportField_AssignedToEmail: 'Email Αναδόχου',
    ImportField_PercentComplete: '% Ολοκλήρωσης',
    ImportField_Phase: 'Φάση',
    ImportField_Description: 'Περιγραφή',
    ImportField_Notes: 'Σημειώσεις',
    ImportField_IsMilestone: 'Είναι Ορόσημο',
    ImportField_Dependencies: 'Εξαρτήσεις',
    ImportField_SkipColumn: '(Παράλειψη αυτής της στήλης)',
    ImportService_EmptyFileError: 'Το αρχείο φαίνεται να είναι κενό ή δεν περιέχει γραμμές δεδομένων.',
    ImportService_ReadErrorDetail: 'Δεν ήταν δυνατή η ανάγνωση του αρχείου: {detail}.',
    ImportService_FileReadError: 'Σφάλμα ανάγνωσης αρχείου.',
    ImportService_RowError: 'Γραμμή {rowNum} ("{title}"): {error}',
    ImportService_AmbiguousDependency: 'Η εξάρτηση "{name}" ταιριάζει με περισσότερους από έναν τίτλους εργασιών — παραλείφθηκε.',
    ImportService_LinkDependencyError: 'Δεν ήταν δυνατή η σύνδεση εξαρτήσεων για την εργασία {taskId}: {error}',

    // ── Health labels (shared: healthUtils.ts and ExportService.ts both use this set; also replaces the duplicated Export_PortfolioHealthLabel* keys) ──
    Health_Done: 'Ολοκληρωμένο',
    Health_OnTrack: 'Εντός Χρονοδιαγράμματος',
    Health_AtRisk: 'Σε Κίνδυνο',
    Health_Overdue: 'Εκπρόθεσμο',

    // ── Status / Priority display labels (DISPLAY-ONLY — stored SharePoint Choice values remain unchanged/English) ──
    Status_NotStarted: 'Δεν Έχει Ξεκινήσει',
    Status_InProgress: 'Σε Εξέλιξη',
    Status_Completed: 'Ολοκληρωμένο',
    Status_OnHold: 'Σε Αναμονή',
    Status_Cancelled: 'Ακυρωμένο',
    Priority_Critical: 'Κρίσιμη',
    Priority_High: 'Υψηλή',
    Priority_Medium: 'Μεσαία',
    Priority_Low: 'Χαμηλή',
    ProjectStatus_Planning: 'Σχεδιασμός',
    ProjectStatus_Active: 'Ενεργό',
    ProjectStatus_OnHold: 'Σε Αναμονή',
    ProjectStatus_Completed: 'Ολοκληρωμένο',
    ProjectStatus_Cancelled: 'Ακυρωμένο',

    // ── Shell (SmartGantt.tsx) ──
    SmartGantt_LoadingProjects: 'Φόρτωση έργων…',
    SmartGantt_UnableToLoad: 'Αδυναμία φόρτωσης',
    SmartGantt_RetryButton: 'Επανάληψη',
    SmartGantt_NoProjectsYet: 'Δεν υπάρχουν ακόμη έργα',
    SmartGantt_NoProjectsSubtitle: 'Δημιουργήστε το πρώτο σας έργο για να ξεκινήσετε.',
    SmartGantt_CreateFirstProjectButton: '+ Δημιουργία Πρώτου Έργου',
    SmartGantt_ImportFromExcelButton: '📥 Εισαγωγή από Excel',
    SmartGantt_LoadingTasks: 'Φόρτωση εργασιών…',
    SmartGantt_DismissAriaLabel: 'Απόρριψη',
    SmartGantt_DeleteTaskDialogTitle: 'Διαγραφή Εργασίας',
    SmartGantt_DeleteTaskDialogSubtext: 'Είστε βέβαιοι ότι θέλετε να διαγράψετε το "{taskTitle}"; Αυτή η ενέργεια δεν μπορεί να αναιρεθεί.',
    SmartGantt_DeleteButton: 'Διαγραφή',
    SmartGantt_CancelButton: 'Άκυρο',
    SmartGantt_ArchiveProjectDialogTitle: 'Αρχειοθέτηση Έργου',
    SmartGantt_ArchiveProjectDialogSubtext: 'Αρχειοθέτηση του "{projectTitle}"; Μπορείτε να καταργήσετε την αρχειοθέτηση αργότερα.',
    SmartGantt_ArchiveButton: 'Αρχειοθέτηση',
    SmartGantt_SendToRecycleBinDialogTitle: 'Αποστολή στον Κάδο Ανακύκλωσης',
    SmartGantt_SendToRecycleBinDialogSubtext: 'Αποστολή του "{projectTitle}" στον κάδο ανακύκλωσης του ιστότοπου;',
    SmartGantt_SendToRecycleBinButton: 'Αποστολή στον Κάδο Ανακύκλωσης',
    SmartGantt_FailedLoadProjects: 'Αποτυχία φόρτωσης έργων. Ελέγξτε τα δικαιώματα του ιστότοπου.',
    SmartGantt_FailedLoadTasks: 'Αποτυχία φόρτωσης εργασιών για αυτό το έργο.',
    SmartGantt_FailedLoadPortfolioStats: 'Αποτυχία φόρτωσης στατιστικών χαρτοφυλακίου.',
    SmartGantt_CouldNotSaveProject: 'Δεν ήταν δυνατή η αποθήκευση του έργου: {message}',
    SmartGantt_CouldNotDeleteProject: 'Δεν ήταν δυνατή η διαγραφή του έργου: {message}',
    SmartGantt_CouldNotArchiveProject: 'Δεν ήταν δυνατή η αρχειοθέτηση του έργου: {message}',
    SmartGantt_CouldNotUnarchiveProject: 'Δεν ήταν δυνατή η κατάργηση αρχειοθέτησης του έργου: {message}',
    SmartGantt_CouldNotSaveTask: 'Δεν ήταν δυνατή η αποθήκευση της εργασίας: {message}',
    SmartGantt_CouldNotDeleteTask: 'Δεν ήταν δυνατή η διαγραφή της εργασίας: {message}',
    SmartGantt_ImageExportFailed: 'Η εξαγωγή εικόνας απέτυχε: {message}',
    SmartGantt_PowerPointExportFailed: 'Η εξαγωγή PowerPoint απέτυχε: {message}',
    SmartGantt_PortfolioExportFailed: 'Η εξαγωγή χαρτοφυλακίου απέτυχε: {message}',
    SmartGantt_CouldNotUpdateTask: 'Δεν ήταν δυνατή η ενημέρωση της εργασίας: {message}',

    // ── Common ──
    ColorSwatch_AutoColorAriaLabel: 'Αυτόματο χρώμα',
    ColorSwatch_CustomColorAriaLabel: 'Προσαρμοσμένο χρώμα',
    ColorSwatch_PickCustomColorTitle: 'Επιλέξτε ένα προσαρμοσμένο χρώμα',

    // ── Export (Excel / PowerPoint) ──
    Export_ColTaskName: 'Όνομα Εργασίας',
    Export_ColPhase: 'Φάση',
    Export_ColStartDate: 'Ημερομηνία Έναρξης',
    Export_ColDueDate: 'Ημερομηνία Λήξης',
    Export_ColStatus: 'Κατάσταση',
    Export_ColPriority: 'Προτεραιότητα',
    Export_ColAssignedTo: 'Ανατέθηκε σε',
    Export_ColAssignedToEmail: 'Email Αναδόχου',
    Export_ColPercentComplete: '% Ολοκλήρωσης',
    Export_ColIsMilestone: 'Είναι Ορόσημο',
    Export_ColDescription: 'Περιγραφή',
    Export_ColNotes: 'Σημειώσεις',
    Export_Yes: 'Ναι',
    Export_No: 'Όχι',
    Export_SheetNameTasks: 'Εργασίες',
    Export_ExcelFileSuffix: ' - Εργασίες.xlsx',
    Export_TaskNameColumnLabel: 'ΟΝΟΜΑ ΕΡΓΑΣΙΑΣ',
    Export_ExportedDateLabel: 'Εξήχθη {date}',
    Export_ProjectReportLabel: 'ΑΝΑΦΟΡΑ ΕΡΓΟΥ',
    Export_StatusLine: 'Κατάσταση: {status}',
    Export_DateRangeSeparator: ' έως ',
    Export_ProjectManagerLine: 'Διαχειριστής Έργου: {name}',
    Export_GeneratedDateLine: 'Δημιουργήθηκε {date}',
    Export_ProjectSummaryTitle: 'Σύνοψη Έργου',
    Export_StatTotalTasks: 'Σύνολο Εργασιών',
    Export_StatCompleted: 'Ολοκληρωμένες',
    Export_StatInProgress: 'Σε Εξέλιξη',
    Export_StatOnHold: 'Σε Αναμονή',
    Export_StatNotStarted: 'Δεν Έχουν Ξεκινήσει',
    Export_OverallProgressLine: 'Συνολική Πρόοδος',
    Export_OverallProgressPercent: '{percent}%',
    Export_StatusBreakdownTitle: 'Ανάλυση Κατάστασης',
    Export_StatusBreakdownRow: '{status}: {count} ({percent}%)',
    Export_GanttTimelineTitle: 'Χρονοδιάγραμμα Gantt',
    Export_SummaryRecentActivityTitle: 'Πρόσφατη Δραστηριότητα',
    Export_ProjectOverviewLabel: 'Επισκόπηση Έργου',
    Export_DetailStatusLabel: 'Κατάσταση',
    Export_DetailStartDateLabel: 'Ημερομηνία Έναρξης',
    Export_DetailDueDateLabel: 'Ημερομηνία Λήξης',
    Export_DetailProjectManagerLabel: 'Διαχειριστής Έργου',
    Export_Past7DaysLabel: 'Τελευταίες 7 Ημέρες',
    Export_NoActivityMessage: 'Καμία πρόσφατη δραστηριότητα.',
    Export_CompletedThisWeekHeader: 'Ολοκληρώθηκαν Αυτή την Εβδομάδα ({count})',
    Export_NewBadge: 'ΝΕΟ  ',
    Export_CompletedPercentLine: '{percent}% ολοκληρωμένο',
    Export_MoreItemsSuffix: '+ {count} ακόμη',
    Export_InProgressUpdatedHeader: 'Σε Εξέλιξη / Ενημερώθηκαν',
    Export_StatusPercentLine: '{status} — {percent}%',
    Export_PortfolioReportLabel: 'ΑΝΑΦΟΡΑ ΧΑΡΤΟΦΥΛΑΚΙΟΥ',
    Export_PortfolioOverviewTitle: 'Επισκόπηση Χαρτοφυλακίου',
    Export_ProjectsCountLine: '{count} Έργα',
    Export_HealthSummaryOnTrack: '{count} Εντός Χρονοδιαγράμματος',
    Export_HealthSummaryAtRisk: '{count} Σε Κίνδυνο',
    Export_HealthSummaryOverdue: '{count} Εκπρόθεσμα',
    Export_ProjectsSummaryHeader: 'Σύνοψη Έργων',
    Export_TableProject: 'Έργο',
    Export_TableStatus: 'Κατάσταση',
    Export_TableHealth: 'Υγεία',
    Export_TableTotal: 'Σύνολο',
    Export_TableDone: 'Ολοκληρωμένα',
    Export_TableActive: 'Ενεργά',
    Export_TableAtRisk: 'Σε Κίνδυνο',
    Export_TableOverdue: 'Εκπρόθεσμα',
    Export_TablePctDone: '% Ολοκλήρωσης',
    Export_TableDueDate: 'Ημερομηνία Λήξης',
    Export_PortfolioSummaryFileName: 'Σύνοψη Χαρτοφυλακίου.xlsx',
    Export_PortfolioReportFileName: 'Αναφορά Χαρτοφυλακίου.pptx',
    Export_ProjectReportFileName: '{projectName} Αναφορά.pptx',
    Export_UnavailableLabel: 'Μη διαθέσιμο',
    Export_SheetNamePortfolio: 'Χαρτοφυλάκιο',
    Export_ColStart: 'Έναρξη',
    Export_ColDue: 'Λήξη',
    Export_ImageGenerationFailed: 'Δεν ήταν δυνατή η δημιουργία της εικόνας — το διάγραμμα ενδέχεται να είναι πολύ μεγάλο για εξαγωγή ως εικόνα.',
    Export_DrawingContextFailed: 'Δεν ήταν δυνατή η δημιουργία περιβάλλοντος σχεδίασης για την εξαγωγή.',
    Export_SvgRenderFailed: 'Η απόδοση SVG απέτυχε',
  };
});
