define([], function () {
  return {
    // ── Property pane ──
    PropertyPane_HeaderDescription: 'Smart Gantt Chart Settings',
    PropertyPane_GeneralGroupName: 'General',
    PropertyPane_TitleFieldLabel: 'Web Part Title',
    WebPart_DefaultTitle: 'Smart Gantt Chart',

    // ── Toolbar ──
    Toolbar_ViewDashboard: 'Dashboard',
    Toolbar_ViewList: 'List',
    Toolbar_ViewGantt: 'Gantt',
    Toolbar_ViewKanban: 'Kanban',
    Toolbar_ZoomDay: 'Day',
    Toolbar_ZoomWeek: 'Week',
    Toolbar_ZoomMonth: 'Month',
    Toolbar_ZoomQuarter: 'Quarter',
    Toolbar_SelectProjectAriaLabel: 'Select project',
    Toolbar_PortfolioLabel: 'Portfolio',
    Toolbar_SelectAProject: 'Select a Project',
    Toolbar_AllProjectsSubtext: 'All projects',
    Toolbar_NoProjectsYet: 'No projects yet',
    Toolbar_ArchivedBadge: 'Archived',
    Toolbar_ShowArchivedProjects: 'Show archived projects',
    Toolbar_NewProject: '+ New Project',
    Toolbar_ImportFileAsNewProject: '📥 Import File as New Project…',
    Toolbar_AddTask: '+ Add Task',
    Toolbar_EditProject: 'Edit Project',
    Toolbar_OptionsButton: '⚙ Options',
    Toolbar_MoreOptionsTitle: 'More options',
    Toolbar_ExportToExcel: '📊 Export to Excel',
    Toolbar_ExportToPowerPoint: '📑 Export to PowerPoint',
    Toolbar_ScrollToTodayTitle: 'Scroll to today',
    Toolbar_TodayButton: '◉ Today',
    Toolbar_ImportTasks: '📥 Import Tasks…',
    Toolbar_ExportAsImage: '🖼 Export as Image (PNG)',
    Toolbar_UnarchiveProject: '📂 Unarchive Project',
    Toolbar_ArchiveProject: '🗄️ Archive Project',
    Toolbar_SendToRecycleBin: '🗑️ Send to Recycle Bin',

    // ── Filter bar ──
    FilterBar_ClearOption: 'Clear',
    FilterBar_DueAny: 'Any due date',
    FilterBar_DueOverdue: 'Overdue',
    FilterBar_DueToday: 'Due today',
    FilterBar_DueWeek: 'Due in 7 days',
    FilterBar_SearchPlaceholder: 'Search tasks…',
    FilterBar_SearchAriaLabel: 'Search tasks',
    FilterBar_StatusChipLabel: 'Status',
    FilterBar_PriorityChipLabel: 'Priority',
    FilterBar_AssigneeChipLabel: 'Assignee',
    FilterBar_PhaseChipLabel: 'Phase',
    FilterBar_DueDateAriaLabel: 'Filter by due date',
    FilterBar_MatchCount: '{matchCount} of {totalCount}',
    FilterBar_ClearFilters: '✕ Clear filters',
    FilterBar_ChipLabelWithCount: '{label} ({count}) ▾',
    FilterBar_ChipLabelNoCount: '{label} ▾',

    // ── Gantt view ──
    Gantt_TaskColumnHeader: 'Task',
    Gantt_DurationColumnHeader: 'Dur.',
    Gantt_AddTaskButton: '+ Add Task',
    Gantt_EmptyTitle: 'No tasks yet',
    Gantt_EmptySubtitle: 'Add tasks to see them on the Gantt chart.',
    Gantt_AddFirstTask: '+ Add First Task',
    Gantt_ImportTasksButton: '📥 Import Tasks',
    Gantt_EditTitle: 'Edit',
    Gantt_DeleteTitle: 'Delete',
    Gantt_EditTaskAriaLabel: 'Edit task {taskTitle}',
    Gantt_DeleteTaskAriaLabel: 'Delete task {taskTitle}',
    Gantt_ExpandPhaseAriaLabel: '{action} phase {phase}',
    Gantt_ExpandAction: 'Expand',
    Gantt_CollapseAction: 'Collapse',
    Gantt_DependencyViolationTooltip: 'Started before all dependencies were completed',
    Gantt_MilestoneAriaLabel: '{taskTitle}, milestone, {date}',
    Gantt_BarAriaLabel: '{taskTitle}, {startDate} to {dueDate}, {percent}% complete',
    Gantt_PercentCompleteTooltip: '{value}% complete',

    // ── Gantt options/settings panel ──
    GanttSettings_PanelHeader: '⚙ Options',
    GanttSettings_ColorCodingSection: 'Color Coding',
    GanttSettings_ByStatus: 'By Status',
    GanttSettings_ByPriority: 'By Priority',
    GanttSettings_ByPhase: 'By Phase',
    GanttSettings_ByHealth: 'By Health',
    GanttSettings_HeaderColorSection: 'Header Color',
    GanttSettings_ThemeDark: 'Dark',
    GanttSettings_ThemeNavy: 'Navy',
    GanttSettings_ThemeTeal: 'Teal',
    GanttSettings_ThemePurple: 'Purple',
    GanttSettings_ThemeLight: 'Light',
    GanttSettings_HeaderLabelsSection: 'Header Labels',
    GanttSettings_WeekLabelDates: 'Dates',
    GanttSettings_WeekLabelDatesDesc: 'Jun 3, Jun 10…',
    GanttSettings_WeekLabelProject: 'Project Weeks',
    GanttSettings_WeekLabelProjectDesc: 'W1, W2…',
    GanttSettings_WeekLabelIso: 'Calendar Weeks',
    GanttSettings_WeekLabelIsoDesc: 'W23, W24…',
    GanttSettings_ProjectWeeksHint: 'Week 1 starts from the Monday of your earliest task — great for presentations.',
    GanttSettings_BarStyleSection: 'Bar Style',
    GanttSettings_BarStyleGradient: 'Gradient',
    GanttSettings_BarStyleFlat: 'Flat',
    GanttSettings_RowHeightSection: 'Row Height',
    GanttSettings_HeightCompact: 'Compact',
    GanttSettings_HeightNormal: 'Normal',
    GanttSettings_HeightSpacious: 'Spacious',
    GanttSettings_ShowHideSection: 'Show / Hide',
    GanttSettings_WeekendShading: 'Weekend shading',
    GanttSettings_DependencyArrows: 'Dependency arrows',
    GanttSettings_CriticalPathAlwaysVisible: 'Critical path always visible',
    GanttSettings_AllOthersOnHoverOnly: 'All others on hover only',
    GanttSettings_CriticalPathHighlight: 'Critical path highlight',
    GanttSettings_ProgressPercentOnBars: 'Progress % on bars',
    GanttSettings_AssigneeNameOnBars: 'Assignee name on bars',
    GanttSettings_HealthStatusBadges: 'Health status badges',

    // ── List view ──
    ListView_ColTaskName: 'Task Name',
    ListView_ColStatus: 'Status',
    ListView_ColHealth: 'Health',
    ListView_ColPriority: 'Priority',
    ListView_ColStart: 'Start',
    ListView_ColDue: 'Due',
    ListView_ColAssignedTo: 'Assigned To',
    ListView_ColProgress: 'Progress',
    ListView_ColPhase: 'Phase',
    ListView_ColPredecessors: 'Predecessors',
    ListView_EmptyTitle: 'No tasks yet',
    ListView_AddFirstTask: '+ Add First Task',
    ListView_AddTaskRow: '+ Add Task',
    ListView_Unassigned: 'Unassigned',
    ListView_DependencyViolationTooltip: 'Started before all dependencies were completed',
    ListView_StatusAriaLabel: 'Status of {taskTitle}',
    ListView_PriorityAriaLabel: 'Priority of {taskTitle}',
    ListView_EditTaskAriaLabel: 'Edit task {taskTitle}',
    ListView_DeleteTaskAriaLabel: 'Delete task {taskTitle}',
    ListView_EditTitle: 'Edit',
    ListView_DeleteTitle: 'Delete',

    // ── Kanban view ──
    Kanban_ColumnNotStarted: 'Not Started',
    Kanban_ColumnInProgress: 'In Progress',
    Kanban_ColumnOnHold: 'On Hold',
    Kanban_ColumnCompleted: 'Completed',
    Kanban_ColumnCancelled: 'Cancelled',
    Kanban_AddTaskButton: '+ Add Task',
    Kanban_EditTitle: 'Edit',
    Kanban_DeleteTitle: 'Delete',
    Kanban_CardAriaLabel: '{taskTitle}, {status}. Press Enter to edit, Left or Right arrow to change status.',
    Kanban_EditTaskAriaLabel: 'Edit task {taskTitle}',
    Kanban_DeleteTaskAriaLabel: 'Delete task {taskTitle}',

    // ── Dashboard view ──
    Dashboard_TotalTasks: 'Total Tasks',
    Dashboard_Completed: 'Completed',
    Dashboard_InProgress: 'In Progress',
    Dashboard_OnHold: 'On Hold',
    Dashboard_NotStarted: 'Not Started',
    Dashboard_Cancelled: 'Cancelled',
    Dashboard_OverallProgress: 'Overall Progress',
    Dashboard_ProjectManagerLabel: 'Project Manager: {name}',
    Dashboard_PhaseProgressHeader: 'Phase Progress',
    Dashboard_StatusBreakdownHeader: 'Status Breakdown',
    Dashboard_PriorityBreakdownHeader: 'Priority Breakdown',
    Dashboard_PriorityCritical: 'Critical',
    Dashboard_PriorityHigh: 'High',
    Dashboard_PriorityMedium: 'Medium',
    Dashboard_PriorityLow: 'Low',
    Dashboard_OverdueHeader: 'Overdue  ({count})',
    Dashboard_DueNext14DaysHeader: 'Due in next 14 days  ({count})',
    Dashboard_CompletedThisWeekHeader: 'Completed This Week',
    Dashboard_UpdatedThisWeekHeader: 'Updated This Week',
    Dashboard_Today: 'Today',
    Dashboard_Tomorrow: 'Tomorrow',
    Dashboard_DaysLeft: '{days}d',
    Dashboard_EmptyTitle: 'No tasks yet',
    Dashboard_EmptySubtitle: 'Add tasks to see your project dashboard.',
    Dashboard_AddTaskButton: '+ Add Task',

    // ── Portfolio view ──
    Portfolio_ProjectCount: '{count} Project{plural}',
    Portfolio_OnTrackSummary: '{count} On Track',
    Portfolio_AtRiskSummary: '{count} At Risk',
    Portfolio_OverdueSummary: '{count} Overdue',
    Portfolio_DoneSummary: '{count} Done',
    Portfolio_SortLabel: 'Sort:',
    Portfolio_SortAZ: 'A-Z',
    Portfolio_SortHealth: 'Health',
    Portfolio_SortStatus: 'Status',
    Portfolio_SortCompletion: 'Completion',
    Portfolio_RefreshTitle: 'Refresh',
    Portfolio_RefreshButton: 'Refresh',
    Portfolio_LoadingStats: 'Loading stats…',
    Portfolio_EmptyTitle: 'No projects yet',
    Portfolio_CreateFirstProject: '+ Create First Project',
    Portfolio_StatsUnavailable: 'Stats unavailable',
    Portfolio_StatsUnavailableDetail: 'Could not load statistics for this project.',
    Portfolio_OverallProgressLabel: 'Overall Progress',
    Portfolio_TaskCountDone: 'Done',
    Portfolio_TaskCountActive: 'Active',
    Portfolio_TaskCountAtRisk: 'At Risk',
    Portfolio_TaskCountOverdue: 'Overdue',
    Portfolio_ViewGanttLink: 'View Gantt →',
    Portfolio_TodayTooltip: 'Today',

    // ── Task panel ──
    TaskPanel_EditHeader: 'Edit: {taskTitle}',
    TaskPanel_NewTaskHeader: 'New Task',
    TaskPanel_TabBasic: 'Basic',
    TaskPanel_TabDetails: 'Details',
    TaskPanel_TabLinks: 'Links',
    TaskPanel_ProjectLabelPrefix: 'Project: ',
    TaskPanel_TaskNameLabel: 'Task Name',
    TaskPanel_TaskNamePlaceholder: 'Enter task name',
    TaskPanel_TaskNameRequired: 'Task name is required',
    TaskPanel_DescriptionLabel: 'Description',
    TaskPanel_DescriptionPlaceholder: 'Enter description',
    TaskPanel_StartDateLabel: 'Start Date',
    TaskPanel_DueDateLabel: 'Due Date',
    TaskPanel_DueDateError: 'Due date must be on or after start date',
    TaskPanel_StatusLabel: 'Status',
    TaskPanel_PriorityLabel: 'Priority',
    TaskPanel_PercentCompleteLabel: '% Complete: {percent}%',
    TaskPanel_AssignedToLabel: 'Assigned To',
    TaskPanel_AssignedToPlaceholder: 'Search people…',
    TaskPanel_PhaseLabel: 'Phase',
    TaskPanel_PhasePlaceholder: 'Enter phase name',
    TaskPanel_PhaseHint: 'Groups tasks together in Gantt and List views.',
    TaskPanel_MilestoneLabel: 'Milestone',
    TaskPanel_MilestoneOnText: 'Yes',
    TaskPanel_MilestoneOffText: 'No',
    TaskPanel_CustomBarColorLabel: 'Custom Bar Color',
    TaskPanel_CustomBarColorOptionalSuffix: ' (optional)',
    TaskPanel_AutoColorHint: 'Auto color from status/priority/phase settings.',
    TaskPanel_NotesLabel: 'Notes',
    TaskPanel_NotesPlaceholder: 'Enter notes',
    TaskPanel_ParentTaskLabel: 'Parent Task',
    TaskPanel_ParentTaskNone: '(none)',
    TaskPanel_ParentTaskHasChildrenHint: 'This task has sub-tasks and cannot have its own parent.',
    TaskPanel_ParentTaskHint: 'Nest this task under another as a sub-task.',
    TaskPanel_DependsOnLabel: 'Depends On',
    TaskPanel_RemoveDependencyTitle: 'Remove dependency on "{taskTitle}"',
    TaskPanel_AddDependencyPlaceholder: 'Add a dependency…',
    TaskPanel_SelectATaskOption: 'Select a task…',
    TaskPanel_DependsOnHint: 'Task cannot start until these are completed.',
    TaskPanel_SavingLabel: 'Saving…',
    TaskPanel_CreatingLabel: 'Creating…',
    TaskPanel_SaveChangesButton: 'Save Changes',
    TaskPanel_CreateTaskButton: 'Create Task',
    TaskPanel_CancelButton: 'Cancel',
    TaskPanel_DismissAriaLabel: 'Dismiss',
    TaskPanel_DiscardUnsavedChangesConfirm: 'Discard unsaved changes?',
    TaskPanel_SaveFallbackError: 'Could not save the task.',

    // ── Project panel ──
    ProjectPanel_EditHeader: 'Edit Project',
    ProjectPanel_NewHeader: 'New Project',
    ProjectPanel_ProjectNameLabel: 'Project Name',
    ProjectPanel_ProjectNamePlaceholder: 'Enter project name',
    ProjectPanel_ProjectNameRequired: 'Project name is required',
    ProjectPanel_DescriptionLabel: 'Description',
    ProjectPanel_DescriptionPlaceholder: 'Enter description',
    ProjectPanel_ProjectColorLabel: 'Project Color',
    ProjectPanel_StatusLabel: 'Status',
    ProjectPanel_StartDateLabel: 'Start Date',
    ProjectPanel_DueDateLabel: 'Due Date',
    ProjectPanel_DueDateError: 'Due date must be on or after start date',
    ProjectPanel_WhatHappensNextTitle: 'What happens next?',
    ProjectPanel_WhatHappensNextBody: "You'll be able to add tasks, set up phases, and track progress once the project is created.",
    ProjectPanel_SavingLabel: 'Saving…',
    ProjectPanel_CreatingLabel: 'Creating…',
    ProjectPanel_SaveChangesButton: 'Save Changes',
    ProjectPanel_CreateProjectButton: 'Create Project',
    ProjectPanel_CancelButton: 'Cancel',
    ProjectPanel_DismissAriaLabel: 'Dismiss',
    ProjectPanel_DiscardUnsavedChangesConfirm: 'Discard unsaved changes?',
    ProjectPanel_SaveFallbackError: 'Could not save the project.',

    // ── Import panel ──
    ImportPanel_SourceExcelTitle: 'Excel / CSV File',
    ImportPanel_SourceExcelSubtitle: 'Import tasks from a spreadsheet',
    ImportPanel_SourcePlannerTitle: 'Microsoft Planner',
    ImportPanel_SourcePlannerSubtitle: 'Import tasks from a Planner plan',
    ImportPanel_ClickToBrowse: 'Click to browse',
    ImportPanel_DragDropSuffix: ' or drag and drop',
    ImportPanel_SupportedExtensions: 'Supports .xlsx, .xls, .csv',
    ImportPanel_RowsColsSummary: '{rows} rows, {cols} columns detected',
    ImportPanel_LoadingPlannerPlans: 'Loading Planner plans…',
    ImportPanel_PlannerLoadError: 'Could not load Planner plans.',
    ImportPanel_PlannerPermissionsHintPrefix: 'Make sure you have access to Planner and that ',
    ImportPanel_PlannerPermissionsHintEmphasis: 'Tasks by Planner and To Do',
    ImportPanel_PlannerPermissionsHintSuffix: ' is available to this site.',
    ImportPanel_NoPlannerPlansFoundTitle: 'No Planner plans found',
    ImportPanel_NoPlannerPlansFoundBody: 'You may not have access to any Planner plans, or none exist for this account.',
    ImportPanel_TaskCountFoundIn: '{count} tasks found in "{planName}"',
    ImportPanel_ProjectDetailsIntroPrefix: 'Importing into ',
    ImportPanel_ProjectDetailsIntroSuffix: '. Review the project details below.',
    ImportPanel_ProjectNameLabel: 'Project Name',
    ImportPanel_DescriptionLabel: 'Description',
    ImportPanel_StatusLabel: 'Status',
    ImportPanel_ColorLabel: 'Color',
    ImportPanel_MapIntro: 'Map the columns from your file to task fields.',
    ImportPanel_CreatingProjectStatus: 'Creating project…',
    ImportPanel_ImportingTasksStatus: 'Importing tasks…',
    ImportPanel_ProgressLabel: '{done} of {total}',
    ImportPanel_CouldNotCreateProject: 'Could not create the project.',
    ImportPanel_ImportCompletedWithErrors: 'Import completed with {count} error(s).',
    ImportPanel_ProjectCreatedSuccess: 'Project created successfully!',
    ImportPanel_ImportSuccessful: 'Import successful!',
    ImportPanel_TasksAddedTo: '{count} tasks added to "{projectName}"',
    ImportPanel_FailedRowsLabel: 'Failed rows:',
    ImportPanel_CloseButton: 'Close',
    ImportPanel_OpenProjectButton: 'Open Project',
    ImportPanel_ViewImportedTasksButton: 'View Imported Tasks',
    ImportPanel_NextMapColumnsButton: 'Next: Map Columns',
    ImportPanel_ImportNTasksButton: 'Import {count} Tasks',
    ImportPanel_BackButton: 'Back',
    ImportPanel_CancelButton: 'Cancel',
    ImportPanel_NextButton: 'Next',
    ImportPanel_StepSource: 'Source',
    ImportPanel_StepProject: 'Project',
    ImportPanel_StepMap: 'Map',
    ImportPanel_StepImport: 'Import',
    ImportPanel_StepDone: 'Done',
    ImportPanel_ImportAsNewProjectHeader: 'Import File as New Project',
    ImportPanel_ImportIntoProjectHeader: 'Import Tasks into {projectName}',
    ImportPanel_CouldNotParseFile: 'Could not parse the file.',
    ImportPanel_CouldNotLoadPlannerTasks: 'Could not load tasks from this plan.',
    ImportPanel_CouldNotCreateProjectDetail: 'Could not create project: {detail}',
    ImportPanel_CouldNotLinkDependencies: 'Could not link dependencies: {detail}',
    ImportPanel_UnknownError: 'unknown error',

    // ── Column mapper (import) ──
    ColumnMapper_TaskNameRequiredBanner: 'Task Name must be mapped to continue.',
    ColumnMapper_SkippedColumnsBanner: '{count} column(s) will be skipped.',
    ColumnMapper_SourceColumnHeader: 'Source Column',
    ColumnMapper_TargetFieldHeader: 'Target Field',
    ColumnMapper_StatusHeader: 'Status',
    ColumnMapper_SkippedBadge: 'Skipped',
    ColumnMapper_AutoMappedBadge: 'Auto-mapped',
    ColumnMapper_SetBadge: 'Set',
    ColumnMapper_PreviewTitle: 'Preview: {columnName}',
    ColumnMapper_EmptyCellDash: '—',

    // ── Import field display names / ImportService ──
    ImportField_TaskName: 'Task Name',
    ImportField_StartDate: 'Start Date',
    ImportField_DueDate: 'Due Date',
    ImportField_Status: 'Status',
    ImportField_Priority: 'Priority',
    ImportField_AssignedTo: 'Assigned To',
    ImportField_AssignedToEmail: 'Assigned To Email',
    ImportField_PercentComplete: '% Complete',
    ImportField_Phase: 'Phase',
    ImportField_Description: 'Description',
    ImportField_Notes: 'Notes',
    ImportField_IsMilestone: 'Is Milestone',
    ImportField_Dependencies: 'Dependencies',
    ImportField_SkipColumn: '(Skip this column)',
    ImportService_EmptyFileError: 'The file appears to be empty or has no data rows.',
    ImportService_ReadErrorDetail: 'Could not read the file: {detail}.',
    ImportService_FileReadError: 'File read error.',
    ImportService_RowError: 'Row {rowNum} ("{title}"): {error}',
    ImportService_AmbiguousDependency: 'Dependency "{name}" matches more than one task title — skipped.',
    ImportService_LinkDependencyError: 'Could not link dependencies for task {taskId}: {error}',

    // ── Health labels (shared: healthUtils.ts and ExportService.ts both use this set; also replaces the duplicated Export_PortfolioHealthLabel* keys) ──
    Health_Done: 'Done',
    Health_OnTrack: 'On Track',
    Health_AtRisk: 'At Risk',
    Health_Overdue: 'Overdue',

    // ── Status / Priority display labels (DISPLAY-ONLY — stored SharePoint Choice values remain unchanged/English) ──
    Status_NotStarted: 'Not Started',
    Status_InProgress: 'In Progress',
    Status_Completed: 'Completed',
    Status_OnHold: 'On Hold',
    Status_Cancelled: 'Cancelled',
    Priority_Critical: 'Critical',
    Priority_High: 'High',
    Priority_Medium: 'Medium',
    Priority_Low: 'Low',
    ProjectStatus_Planning: 'Planning',
    ProjectStatus_Active: 'Active',
    ProjectStatus_OnHold: 'On Hold',
    ProjectStatus_Completed: 'Completed',
    ProjectStatus_Cancelled: 'Cancelled',

    // ── Shell (SmartGantt.tsx) ──
    SmartGantt_LoadingProjects: 'Loading projects…',
    SmartGantt_UnableToLoad: 'Unable to load',
    SmartGantt_RetryButton: 'Retry',
    SmartGantt_NoProjectsYet: 'No projects yet',
    SmartGantt_NoProjectsSubtitle: 'Create your first project to get started.',
    SmartGantt_CreateFirstProjectButton: '+ Create First Project',
    SmartGantt_ImportFromExcelButton: '📥 Import from Excel',
    SmartGantt_LoadingTasks: 'Loading tasks…',
    SmartGantt_DismissAriaLabel: 'Dismiss',
    SmartGantt_DeleteTaskDialogTitle: 'Delete Task',
    SmartGantt_DeleteTaskDialogSubtext: 'Are you sure you want to delete "{taskTitle}"? This cannot be undone.',
    SmartGantt_DeleteButton: 'Delete',
    SmartGantt_CancelButton: 'Cancel',
    SmartGantt_ArchiveProjectDialogTitle: 'Archive Project',
    SmartGantt_ArchiveProjectDialogSubtext: 'Archive "{projectTitle}"? You can unarchive it later.',
    SmartGantt_ArchiveButton: 'Archive',
    SmartGantt_SendToRecycleBinDialogTitle: 'Send to Recycle Bin',
    SmartGantt_SendToRecycleBinDialogSubtext: 'Send "{projectTitle}" to the site recycle bin?',
    SmartGantt_SendToRecycleBinButton: 'Send to Recycle Bin',
    SmartGantt_FailedLoadProjects: 'Failed to load projects. Check site permissions.',
    SmartGantt_FailedLoadTasks: 'Failed to load tasks for this project.',
    SmartGantt_FailedLoadPortfolioStats: 'Failed to load portfolio statistics.',
    SmartGantt_CouldNotSaveProject: 'Could not save the project: {message}',
    SmartGantt_CouldNotDeleteProject: 'Could not delete the project: {message}',
    SmartGantt_CouldNotArchiveProject: 'Could not archive the project: {message}',
    SmartGantt_CouldNotUnarchiveProject: 'Could not unarchive the project: {message}',
    SmartGantt_CouldNotSaveTask: 'Could not save the task: {message}',
    SmartGantt_CouldNotDeleteTask: 'Could not delete the task: {message}',
    SmartGantt_ImageExportFailed: 'Image export failed: {message}',
    SmartGantt_PowerPointExportFailed: 'PowerPoint export failed: {message}',
    SmartGantt_PortfolioExportFailed: 'Portfolio export failed: {message}',
    SmartGantt_CouldNotUpdateTask: 'Could not update the task: {message}',

    // ── Common ──
    ColorSwatch_AutoColorAriaLabel: 'Auto color',
    ColorSwatch_CustomColorAriaLabel: 'Custom color',
    ColorSwatch_PickCustomColorTitle: 'Pick a custom color',

    // ── Export (Excel / PowerPoint) ──
    Export_ColTaskName: 'Task Name',
    Export_ColPhase: 'Phase',
    Export_ColStartDate: 'Start Date',
    Export_ColDueDate: 'Due Date',
    Export_ColStatus: 'Status',
    Export_ColPriority: 'Priority',
    Export_ColAssignedTo: 'Assigned To',
    Export_ColAssignedToEmail: 'Assigned To Email',
    Export_ColPercentComplete: '% Complete',
    Export_ColIsMilestone: 'Is Milestone',
    Export_ColDescription: 'Description',
    Export_ColNotes: 'Notes',
    Export_Yes: 'Yes',
    Export_No: 'No',
    Export_SheetNameTasks: 'Tasks',
    Export_ExcelFileSuffix: ' - Tasks.xlsx',
    Export_TaskNameColumnLabel: 'TASK NAME',
    Export_ExportedDateLabel: 'Exported {date}',
    Export_ProjectReportLabel: 'PROJECT REPORT',
    Export_StatusLine: 'Status: {status}',
    Export_DateRangeSeparator: ' to ',
    Export_ProjectManagerLine: 'Project Manager: {name}',
    Export_GeneratedDateLine: 'Generated {date}',
    Export_ProjectSummaryTitle: 'Project Summary',
    Export_StatTotalTasks: 'Total Tasks',
    Export_StatCompleted: 'Completed',
    Export_StatInProgress: 'In Progress',
    Export_StatOnHold: 'On Hold',
    Export_StatNotStarted: 'Not Started',
    Export_OverallProgressLine: 'Overall Progress',
    Export_OverallProgressPercent: '{percent}%',
    Export_StatusBreakdownTitle: 'Status Breakdown',
    Export_StatusBreakdownRow: '{status}: {count} ({percent}%)',
    Export_GanttTimelineTitle: 'Gantt Timeline',
    Export_SummaryRecentActivityTitle: 'Recent Activity',
    Export_ProjectOverviewLabel: 'Project Overview',
    Export_DetailStatusLabel: 'Status',
    Export_DetailStartDateLabel: 'Start Date',
    Export_DetailDueDateLabel: 'Due Date',
    Export_DetailProjectManagerLabel: 'Project Manager',
    Export_Past7DaysLabel: 'Past 7 Days',
    Export_NoActivityMessage: 'No recent activity.',
    Export_CompletedThisWeekHeader: 'Completed This Week ({count})',
    Export_NewBadge: 'NEW  ',
    Export_CompletedPercentLine: '{percent}% complete',
    Export_MoreItemsSuffix: '+ {count} more',
    Export_InProgressUpdatedHeader: 'In Progress / Updated',
    Export_StatusPercentLine: '{status} — {percent}%',
    Export_PortfolioReportLabel: 'PORTFOLIO REPORT',
    Export_PortfolioOverviewTitle: 'Portfolio Overview',
    Export_ProjectsCountLine: '{count} Projects',
    Export_HealthSummaryOnTrack: '{count} On Track',
    Export_HealthSummaryAtRisk: '{count} At Risk',
    Export_HealthSummaryOverdue: '{count} Overdue',
    Export_ProjectsSummaryHeader: 'Projects Summary',
    Export_TableProject: 'Project',
    Export_TableStatus: 'Status',
    Export_TableHealth: 'Health',
    Export_TableTotal: 'Total',
    Export_TableDone: 'Done',
    Export_TableActive: 'Active',
    Export_TableAtRisk: 'At Risk',
    Export_TableOverdue: 'Overdue',
    Export_TablePctDone: '% Done',
    Export_TableDueDate: 'Due Date',
    Export_PortfolioSummaryFileName: 'Portfolio Summary.xlsx',
    Export_PortfolioReportFileName: 'Portfolio Report.pptx',
    Export_ProjectReportFileName: '{projectName} Report.pptx',
    Export_UnavailableLabel: 'Unavailable',
    Export_SheetNamePortfolio: 'Portfolio',
    Export_ColStart: 'Start',
    Export_ColDue: 'Due',
    Export_ImageGenerationFailed: 'Could not generate the image — the chart may be too large to export as an image.',
    Export_DrawingContextFailed: 'Could not create a drawing context for the export.',
    Export_SvgRenderFailed: 'SVG render failed',
  };
});
