define([], function () {
  return {
    // ── Property pane ──
    PropertyPane_HeaderDescription: 'Configuración de Diagrama de Gantt Inteligente',
    PropertyPane_GeneralGroupName: 'General',
    PropertyPane_TitleFieldLabel: 'Título de la Web Part',
    WebPart_DefaultTitle: 'Diagrama de Gantt Inteligente',

    // ── Toolbar ──
    Toolbar_ViewDashboard: 'Panel',
    Toolbar_ViewList: 'Lista',
    Toolbar_ViewGantt: 'Gantt',
    Toolbar_ViewKanban: 'Kanban',
    Toolbar_ZoomDay: 'Día',
    Toolbar_ZoomWeek: 'Semana',
    Toolbar_ZoomMonth: 'Mes',
    Toolbar_ZoomQuarter: 'Trimestre',
    Toolbar_SelectProjectAriaLabel: 'Seleccionar proyecto',
    Toolbar_PortfolioLabel: 'Cartera',
    Toolbar_SelectAProject: 'Seleccionar un Proyecto',
    Toolbar_AllProjectsSubtext: 'Todos los proyectos',
    Toolbar_NoProjectsYet: 'Aún no hay proyectos',
    Toolbar_ArchivedBadge: 'Archivado',
    Toolbar_ShowArchivedProjects: 'Mostrar proyectos archivados',
    Toolbar_NewProject: '+ Nuevo Proyecto',
    Toolbar_ImportFileAsNewProject: '📥 Importar Archivo como Nuevo Proyecto…',
    Toolbar_AddTask: '+ Añadir Tarea',
    Toolbar_EditProject: 'Editar Proyecto',
    Toolbar_OptionsButton: '⚙ Opciones',
    Toolbar_MoreOptionsTitle: 'Más opciones',
    Toolbar_ExportToExcel: '📊 Exportar a Excel',
    Toolbar_ExportToPowerPoint: '📑 Exportar a PowerPoint',
    Toolbar_ScrollToTodayTitle: 'Desplazarse a hoy',
    Toolbar_TodayButton: '◉ Hoy',
    Toolbar_ImportTasks: '📥 Importar Tareas…',
    Toolbar_ExportAsImage: '🖼 Exportar como Imagen (PNG)',
    Toolbar_UnarchiveProject: '📂 Desarchivar Proyecto',
    Toolbar_ArchiveProject: '🗄️ Archivar Proyecto',
    Toolbar_SendToRecycleBin: '🗑️ Enviar a la Papelera de Reciclaje',

    // ── Filter bar ──
    FilterBar_ClearOption: 'Borrar',
    FilterBar_DueAny: 'Cualquier fecha de vencimiento',
    FilterBar_DueOverdue: 'Vencidas',
    FilterBar_DueToday: 'Vence hoy',
    FilterBar_DueWeek: 'Vence en 7 días',
    FilterBar_SearchPlaceholder: 'Buscar tareas…',
    FilterBar_SearchAriaLabel: 'Buscar tareas',
    FilterBar_StatusChipLabel: 'Estado',
    FilterBar_PriorityChipLabel: 'Prioridad',
    FilterBar_AssigneeChipLabel: 'Asignado a',
    FilterBar_PhaseChipLabel: 'Fase',
    FilterBar_DueDateAriaLabel: 'Filtrar por fecha de vencimiento',
    FilterBar_MatchCount: '{matchCount} de {totalCount}',
    FilterBar_ClearFilters: '✕ Borrar filtros',
    FilterBar_ChipLabelWithCount: '{label} ({count}) ▾',
    FilterBar_ChipLabelNoCount: '{label} ▾',

    // ── Gantt view ──
    Gantt_TaskColumnHeader: 'Tarea',
    Gantt_DurationColumnHeader: 'Dur.',
    Gantt_AddTaskButton: '+ Añadir Tarea',
    Gantt_EmptyTitle: 'Aún no hay tareas',
    Gantt_EmptySubtitle: 'Añada tareas para verlas en el diagrama de Gantt.',
    Gantt_AddFirstTask: '+ Añadir Primera Tarea',
    Gantt_ImportTasksButton: '📥 Importar Tareas',
    Gantt_EditTitle: 'Editar',
    Gantt_DeleteTitle: 'Eliminar',
    Gantt_EditTaskAriaLabel: 'Editar tarea {taskTitle}',
    Gantt_DeleteTaskAriaLabel: 'Eliminar tarea {taskTitle}',
    Gantt_ExpandPhaseAriaLabel: '{action} fase {phase}',
    Gantt_ExpandAction: 'Expandir',
    Gantt_CollapseAction: 'Contraer',
    Gantt_DependencyViolationTooltip: 'Comenzó antes de que se completaran todas las dependencias',
    Gantt_MilestoneAriaLabel: '{taskTitle}, hito, {date}',
    Gantt_BarAriaLabel: '{taskTitle}, {startDate} a {dueDate}, {percent}% completado',
    Gantt_PercentCompleteTooltip: '{value}% completado',

    // ── Gantt options/settings panel ──
    GanttSettings_PanelHeader: '⚙ Opciones',
    GanttSettings_ColorCodingSection: 'Codificación por Color',
    GanttSettings_ByStatus: 'Por Estado',
    GanttSettings_ByPriority: 'Por Prioridad',
    GanttSettings_ByPhase: 'Por Fase',
    GanttSettings_ByHealth: 'Por Estado de Salud',
    GanttSettings_HeaderColorSection: 'Color del Encabezado',
    GanttSettings_ThemeDark: 'Oscuro',
    GanttSettings_ThemeNavy: 'Azul Marino',
    GanttSettings_ThemeTeal: 'Turquesa',
    GanttSettings_ThemePurple: 'Morado',
    GanttSettings_ThemeLight: 'Claro',
    GanttSettings_HeaderLabelsSection: 'Etiquetas del Encabezado',
    GanttSettings_WeekLabelDates: 'Fechas',
    GanttSettings_WeekLabelDatesDesc: '3 jun, 10 jun…',
    GanttSettings_WeekLabelProject: 'Semanas del Proyecto',
    GanttSettings_WeekLabelProjectDesc: 'S1, S2…',
    GanttSettings_WeekLabelIso: 'Semanas del Calendario',
    GanttSettings_WeekLabelIsoDesc: 'S23, S24…',
    GanttSettings_ProjectWeeksHint: 'La semana 1 comienza el lunes de su tarea más temprana, ideal para presentaciones.',
    GanttSettings_BarStyleSection: 'Estilo de Barra',
    GanttSettings_BarStyleGradient: 'Degradado',
    GanttSettings_BarStyleFlat: 'Plano',
    GanttSettings_RowHeightSection: 'Altura de Fila',
    GanttSettings_HeightCompact: 'Compacta',
    GanttSettings_HeightNormal: 'Normal',
    GanttSettings_HeightSpacious: 'Amplia',
    GanttSettings_ShowHideSection: 'Mostrar / Ocultar',
    GanttSettings_WeekendShading: 'Sombreado de fines de semana',
    GanttSettings_DependencyArrows: 'Flechas de dependencia',
    GanttSettings_CriticalPathAlwaysVisible: 'Ruta crítica siempre visible',
    GanttSettings_AllOthersOnHoverOnly: 'El resto solo al pasar el cursor',
    GanttSettings_CriticalPathHighlight: 'Resaltado de ruta crítica',
    GanttSettings_ProgressPercentOnBars: '% de progreso en las barras',
    GanttSettings_AssigneeNameOnBars: 'Nombre del asignado en las barras',
    GanttSettings_HealthStatusBadges: 'Distintivos de estado de salud',

    // ── List view ──
    ListView_ColTaskName: 'Nombre de la Tarea',
    ListView_ColStatus: 'Estado',
    ListView_ColHealth: 'Estado de Salud',
    ListView_ColPriority: 'Prioridad',
    ListView_ColStart: 'Inicio',
    ListView_ColDue: 'Vencimiento',
    ListView_ColAssignedTo: 'Asignado a',
    ListView_ColProgress: 'Progreso',
    ListView_ColPhase: 'Fase',
    ListView_ColPredecessors: 'Predecesoras',
    ListView_EmptyTitle: 'Aún no hay tareas',
    ListView_AddFirstTask: '+ Añadir Primera Tarea',
    ListView_AddTaskRow: '+ Añadir Tarea',
    ListView_Unassigned: 'Sin asignar',
    ListView_DependencyViolationTooltip: 'Comenzó antes de que se completaran todas las dependencias',
    ListView_StatusAriaLabel: 'Estado de {taskTitle}',
    ListView_PriorityAriaLabel: 'Prioridad de {taskTitle}',
    ListView_EditTaskAriaLabel: 'Editar tarea {taskTitle}',
    ListView_DeleteTaskAriaLabel: 'Eliminar tarea {taskTitle}',
    ListView_EditTitle: 'Editar',
    ListView_DeleteTitle: 'Eliminar',

    // ── Kanban view ──
    Kanban_ColumnNotStarted: 'Sin Iniciar',
    Kanban_ColumnInProgress: 'En Curso',
    Kanban_ColumnOnHold: 'En Espera',
    Kanban_ColumnCompleted: 'Completada',
    Kanban_ColumnCancelled: 'Cancelada',
    Kanban_AddTaskButton: '+ Añadir Tarea',
    Kanban_EditTitle: 'Editar',
    Kanban_DeleteTitle: 'Eliminar',
    Kanban_CardAriaLabel: '{taskTitle}, {status}. Pulse Intro para editar, flecha izquierda o derecha para cambiar el estado.',
    Kanban_EditTaskAriaLabel: 'Editar tarea {taskTitle}',
    Kanban_DeleteTaskAriaLabel: 'Eliminar tarea {taskTitle}',

    // ── Dashboard view ──
    Dashboard_TotalTasks: 'Total de Tareas',
    Dashboard_Completed: 'Completadas',
    Dashboard_InProgress: 'En Curso',
    Dashboard_OnHold: 'En Espera',
    Dashboard_NotStarted: 'Sin Iniciar',
    Dashboard_Cancelled: 'Canceladas',
    Dashboard_OverallProgress: 'Progreso General',
    Dashboard_ProjectManagerLabel: 'Jefe de Proyecto: {name}',
    Dashboard_PhaseProgressHeader: 'Progreso por Fase',
    Dashboard_StatusBreakdownHeader: 'Desglose por Estado',
    Dashboard_PriorityBreakdownHeader: 'Desglose por Prioridad',
    Dashboard_PriorityCritical: 'Crítica',
    Dashboard_PriorityHigh: 'Alta',
    Dashboard_PriorityMedium: 'Media',
    Dashboard_PriorityLow: 'Baja',
    Dashboard_OverdueHeader: 'Vencidas  ({count})',
    Dashboard_DueNext14DaysHeader: 'Vencen en los próximos 14 días  ({count})',
    Dashboard_CompletedThisWeekHeader: 'Completadas Esta Semana',
    Dashboard_UpdatedThisWeekHeader: 'Actualizadas Esta Semana',
    Dashboard_Today: 'Hoy',
    Dashboard_Tomorrow: 'Mañana',
    Dashboard_DaysLeft: '{days}d',
    Dashboard_EmptyTitle: 'Aún no hay tareas',
    Dashboard_EmptySubtitle: 'Añada tareas para ver el panel de su proyecto.',
    Dashboard_AddTaskButton: '+ Añadir Tarea',

    // ── Portfolio view ──
    Portfolio_ProjectCount: '{count} Proyecto{plural}',
    Portfolio_OnTrackSummary: '{count} En Curso Correcto',
    Portfolio_AtRiskSummary: '{count} En Riesgo',
    Portfolio_OverdueSummary: '{count} Vencidos',
    Portfolio_DoneSummary: '{count} Finalizados',
    Portfolio_SortLabel: 'Ordenar:',
    Portfolio_SortAZ: 'A-Z',
    Portfolio_SortHealth: 'Estado de Salud',
    Portfolio_SortStatus: 'Estado',
    Portfolio_SortCompletion: 'Finalización',
    Portfolio_RefreshTitle: 'Actualizar',
    Portfolio_RefreshButton: 'Actualizar',
    Portfolio_LoadingStats: 'Cargando estadísticas…',
    Portfolio_EmptyTitle: 'Aún no hay proyectos',
    Portfolio_CreateFirstProject: '+ Crear Primer Proyecto',
    Portfolio_StatsUnavailable: 'Estadísticas no disponibles',
    Portfolio_StatsUnavailableDetail: 'No se pudieron cargar las estadísticas de este proyecto.',
    Portfolio_OverallProgressLabel: 'Progreso General',
    Portfolio_TaskCountDone: 'Finalizadas',
    Portfolio_TaskCountActive: 'Activas',
    Portfolio_TaskCountAtRisk: 'En Riesgo',
    Portfolio_TaskCountOverdue: 'Vencidas',
    Portfolio_ViewGanttLink: 'Ver Gantt →',
    Portfolio_TodayTooltip: 'Hoy',

    // ── Task panel ──
    TaskPanel_EditHeader: 'Editar: {taskTitle}',
    TaskPanel_NewTaskHeader: 'Nueva Tarea',
    TaskPanel_TabBasic: 'Básico',
    TaskPanel_TabDetails: 'Detalles',
    TaskPanel_TabLinks: 'Enlaces',
    TaskPanel_ProjectLabelPrefix: 'Proyecto: ',
    TaskPanel_TaskNameLabel: 'Nombre de la Tarea',
    TaskPanel_TaskNamePlaceholder: 'Introduzca el nombre de la tarea',
    TaskPanel_TaskNameRequired: 'El nombre de la tarea es obligatorio',
    TaskPanel_DescriptionLabel: 'Descripción',
    TaskPanel_DescriptionPlaceholder: 'Introduzca una descripción',
    TaskPanel_StartDateLabel: 'Fecha de Inicio',
    TaskPanel_DueDateLabel: 'Fecha de Vencimiento',
    TaskPanel_DueDateError: 'La fecha de vencimiento debe ser igual o posterior a la fecha de inicio',
    TaskPanel_StatusLabel: 'Estado',
    TaskPanel_PriorityLabel: 'Prioridad',
    TaskPanel_PercentCompleteLabel: '% Completado: {percent}%',
    TaskPanel_AssignedToLabel: 'Asignado a',
    TaskPanel_AssignedToPlaceholder: 'Buscar personas…',
    TaskPanel_PhaseLabel: 'Fase',
    TaskPanel_PhasePlaceholder: 'Introduzca el nombre de la fase',
    TaskPanel_PhaseHint: 'Agrupa tareas en las vistas de Gantt y Lista.',
    TaskPanel_MilestoneLabel: 'Hito',
    TaskPanel_MilestoneOnText: 'Sí',
    TaskPanel_MilestoneOffText: 'No',
    TaskPanel_CustomBarColorLabel: 'Color de Barra Personalizado',
    TaskPanel_CustomBarColorOptionalSuffix: ' (opcional)',
    TaskPanel_AutoColorHint: 'Color automático según la configuración de estado/prioridad/fase.',
    TaskPanel_NotesLabel: 'Notas',
    TaskPanel_NotesPlaceholder: 'Introduzca notas',
    TaskPanel_ParentTaskLabel: 'Tarea Principal',
    TaskPanel_ParentTaskNone: '(ninguna)',
    TaskPanel_ParentTaskHasChildrenHint: 'Esta tarea tiene subtareas y no puede tener su propia tarea principal.',
    TaskPanel_ParentTaskHint: 'Anide esta tarea bajo otra como subtarea.',
    TaskPanel_DependsOnLabel: 'Depende De',
    TaskPanel_RemoveDependencyTitle: 'Eliminar dependencia de "{taskTitle}"',
    TaskPanel_AddDependencyPlaceholder: 'Añadir una dependencia…',
    TaskPanel_SelectATaskOption: 'Seleccionar una tarea…',
    TaskPanel_DependsOnHint: 'La tarea no puede comenzar hasta que estas se completen.',
    TaskPanel_SavingLabel: 'Guardando…',
    TaskPanel_CreatingLabel: 'Creando…',
    TaskPanel_SaveChangesButton: 'Guardar Cambios',
    TaskPanel_CreateTaskButton: 'Crear Tarea',
    TaskPanel_CancelButton: 'Cancelar',
    TaskPanel_DismissAriaLabel: 'Descartar',
    TaskPanel_DiscardUnsavedChangesConfirm: '¿Descartar cambios no guardados?',
    TaskPanel_SaveFallbackError: 'No se pudo guardar la tarea.',

    // ── Project panel ──
    ProjectPanel_EditHeader: 'Editar Proyecto',
    ProjectPanel_NewHeader: 'Nuevo Proyecto',
    ProjectPanel_ProjectNameLabel: 'Nombre del Proyecto',
    ProjectPanel_ProjectNamePlaceholder: 'Introduzca el nombre del proyecto',
    ProjectPanel_ProjectNameRequired: 'El nombre del proyecto es obligatorio',
    ProjectPanel_DescriptionLabel: 'Descripción',
    ProjectPanel_DescriptionPlaceholder: 'Introduzca una descripción',
    ProjectPanel_ProjectColorLabel: 'Color del Proyecto',
    ProjectPanel_StatusLabel: 'Estado',
    ProjectPanel_StartDateLabel: 'Fecha de Inicio',
    ProjectPanel_DueDateLabel: 'Fecha de Vencimiento',
    ProjectPanel_DueDateError: 'La fecha de vencimiento debe ser igual o posterior a la fecha de inicio',
    ProjectPanel_WhatHappensNextTitle: '¿Qué ocurre a continuación?',
    ProjectPanel_WhatHappensNextBody: 'Podrá añadir tareas, configurar fases y hacer seguimiento del progreso una vez creado el proyecto.',
    ProjectPanel_SavingLabel: 'Guardando…',
    ProjectPanel_CreatingLabel: 'Creando…',
    ProjectPanel_SaveChangesButton: 'Guardar Cambios',
    ProjectPanel_CreateProjectButton: 'Crear Proyecto',
    ProjectPanel_CancelButton: 'Cancelar',
    ProjectPanel_DismissAriaLabel: 'Descartar',
    ProjectPanel_DiscardUnsavedChangesConfirm: '¿Descartar cambios no guardados?',
    ProjectPanel_SaveFallbackError: 'No se pudo guardar el proyecto.',

    // ── Import panel ──
    ImportPanel_SourceExcelTitle: 'Archivo Excel / CSV',
    ImportPanel_SourceExcelSubtitle: 'Importar tareas desde una hoja de cálculo',
    ImportPanel_SourcePlannerTitle: 'Microsoft Planner',
    ImportPanel_SourcePlannerSubtitle: 'Importar tareas desde un plan de Planner',
    ImportPanel_ClickToBrowse: 'Haga clic para examinar',
    ImportPanel_DragDropSuffix: ' o arrastre y suelte',
    ImportPanel_SupportedExtensions: 'Admite .xlsx, .xls, .csv',
    ImportPanel_RowsColsSummary: '{rows} filas, {cols} columnas detectadas',
    ImportPanel_LoadingPlannerPlans: 'Cargando planes de Planner…',
    ImportPanel_PlannerLoadError: 'No se pudieron cargar los planes de Planner.',
    ImportPanel_PlannerPermissionsHintPrefix: 'Asegúrese de tener acceso a Planner y de que ',
    ImportPanel_PlannerPermissionsHintEmphasis: 'Tareas de Planner y To Do',
    ImportPanel_PlannerPermissionsHintSuffix: ' esté disponible en este sitio.',
    ImportPanel_NoPlannerPlansFoundTitle: 'No se encontraron planes de Planner',
    ImportPanel_NoPlannerPlansFoundBody: 'Es posible que no tenga acceso a ningún plan de Planner, o que no exista ninguno para esta cuenta.',
    ImportPanel_TaskCountFoundIn: '{count} tareas encontradas en "{planName}"',
    ImportPanel_ProjectDetailsIntroPrefix: 'Importando en ',
    ImportPanel_ProjectDetailsIntroSuffix: '. Revise los detalles del proyecto a continuación.',
    ImportPanel_ProjectNameLabel: 'Nombre del Proyecto',
    ImportPanel_DescriptionLabel: 'Descripción',
    ImportPanel_StatusLabel: 'Estado',
    ImportPanel_ColorLabel: 'Color',
    ImportPanel_MapIntro: 'Asigne las columnas de su archivo a los campos de la tarea.',
    ImportPanel_CreatingProjectStatus: 'Creando proyecto…',
    ImportPanel_ImportingTasksStatus: 'Importando tareas…',
    ImportPanel_ProgressLabel: '{done} de {total}',
    ImportPanel_CouldNotCreateProject: 'No se pudo crear el proyecto.',
    ImportPanel_ImportCompletedWithErrors: 'Importación completada con {count} error(es).',
    ImportPanel_ProjectCreatedSuccess: '¡Proyecto creado correctamente!',
    ImportPanel_ImportSuccessful: '¡Importación correcta!',
    ImportPanel_TasksAddedTo: '{count} tareas añadidas a "{projectName}"',
    ImportPanel_FailedRowsLabel: 'Filas con errores:',
    ImportPanel_CloseButton: 'Cerrar',
    ImportPanel_OpenProjectButton: 'Abrir Proyecto',
    ImportPanel_ViewImportedTasksButton: 'Ver Tareas Importadas',
    ImportPanel_NextMapColumnsButton: 'Siguiente: Asignar Columnas',
    ImportPanel_ImportNTasksButton: 'Importar {count} Tareas',
    ImportPanel_BackButton: 'Atrás',
    ImportPanel_CancelButton: 'Cancelar',
    ImportPanel_NextButton: 'Siguiente',
    ImportPanel_StepSource: 'Origen',
    ImportPanel_StepProject: 'Proyecto',
    ImportPanel_StepMap: 'Asignar',
    ImportPanel_StepImport: 'Importar',
    ImportPanel_StepDone: 'Finalizado',
    ImportPanel_ImportAsNewProjectHeader: 'Importar Archivo como Nuevo Proyecto',
    ImportPanel_ImportIntoProjectHeader: 'Importar Tareas en {projectName}',
    ImportPanel_CouldNotParseFile: 'No se pudo analizar el archivo.',
    ImportPanel_CouldNotLoadPlannerTasks: 'No se pudieron cargar las tareas de este plan.',
    ImportPanel_CouldNotCreateProjectDetail: 'No se pudo crear el proyecto: {detail}',
    ImportPanel_CouldNotLinkDependencies: 'No se pudieron vincular las dependencias: {detail}',
    ImportPanel_UnknownError: 'error desconocido',

    // ── Column mapper (import) ──
    ColumnMapper_TaskNameRequiredBanner: 'El Nombre de la Tarea debe estar asignado para continuar.',
    ColumnMapper_SkippedColumnsBanner: 'Se omitirán {count} columna(s).',
    ColumnMapper_SourceColumnHeader: 'Columna de Origen',
    ColumnMapper_TargetFieldHeader: 'Campo de Destino',
    ColumnMapper_StatusHeader: 'Estado',
    ColumnMapper_SkippedBadge: 'Omitida',
    ColumnMapper_AutoMappedBadge: 'Asignada automáticamente',
    ColumnMapper_SetBadge: 'Establecida',
    ColumnMapper_PreviewTitle: 'Vista previa: {columnName}',
    ColumnMapper_EmptyCellDash: '—',

    // ── Import field display names / ImportService ──
    ImportField_TaskName: 'Nombre de la Tarea',
    ImportField_StartDate: 'Fecha de Inicio',
    ImportField_DueDate: 'Fecha de Vencimiento',
    ImportField_Status: 'Estado',
    ImportField_Priority: 'Prioridad',
    ImportField_AssignedTo: 'Asignado a',
    ImportField_AssignedToEmail: 'Correo del Asignado',
    ImportField_PercentComplete: '% Completado',
    ImportField_Phase: 'Fase',
    ImportField_Description: 'Descripción',
    ImportField_Notes: 'Notas',
    ImportField_IsMilestone: 'Es un Hito',
    ImportField_Dependencies: 'Dependencias',
    ImportField_SkipColumn: '(Omitir esta columna)',
    ImportService_EmptyFileError: 'El archivo parece estar vacío o no contiene filas de datos.',
    ImportService_ReadErrorDetail: 'No se pudo leer el archivo: {detail}.',
    ImportService_FileReadError: 'Error de lectura del archivo.',
    ImportService_RowError: 'Fila {rowNum} ("{title}"): {error}',
    ImportService_AmbiguousDependency: 'La dependencia "{name}" coincide con más de un título de tarea; se omitió.',
    ImportService_LinkDependencyError: 'No se pudieron vincular las dependencias de la tarea {taskId}: {error}',

    // ── Health labels (shared: healthUtils.ts and ExportService.ts both use this set; also replaces the duplicated Export_PortfolioHealthLabel* keys) ──
    Health_Done: 'Finalizado',
    Health_OnTrack: 'En Curso Correcto',
    Health_AtRisk: 'En Riesgo',
    Health_Overdue: 'Vencido',

    // ── Status / Priority display labels (DISPLAY-ONLY — stored SharePoint Choice values remain unchanged/English) ──
    Status_NotStarted: 'Sin Iniciar',
    Status_InProgress: 'En Curso',
    Status_Completed: 'Completada',
    Status_OnHold: 'En Espera',
    Status_Cancelled: 'Cancelada',
    Priority_Critical: 'Crítica',
    Priority_High: 'Alta',
    Priority_Medium: 'Media',
    Priority_Low: 'Baja',
    ProjectStatus_Planning: 'Planificación',
    ProjectStatus_Active: 'Activo',
    ProjectStatus_OnHold: 'En Espera',
    ProjectStatus_Completed: 'Completado',
    ProjectStatus_Cancelled: 'Cancelado',

    // ── Shell (SmartGantt.tsx) ──
    SmartGantt_LoadingProjects: 'Cargando proyectos…',
    SmartGantt_UnableToLoad: 'No se puede cargar',
    SmartGantt_RetryButton: 'Reintentar',
    SmartGantt_NoProjectsYet: 'Aún no hay proyectos',
    SmartGantt_NoProjectsSubtitle: 'Cree su primer proyecto para comenzar.',
    SmartGantt_CreateFirstProjectButton: '+ Crear Primer Proyecto',
    SmartGantt_ImportFromExcelButton: '📥 Importar desde Excel',
    SmartGantt_LoadingTasks: 'Cargando tareas…',
    SmartGantt_DismissAriaLabel: 'Descartar',
    SmartGantt_DeleteTaskDialogTitle: 'Eliminar Tarea',
    SmartGantt_DeleteTaskDialogSubtext: '¿Está seguro de que desea eliminar "{taskTitle}"? Esta acción no se puede deshacer.',
    SmartGantt_DeleteButton: 'Eliminar',
    SmartGantt_CancelButton: 'Cancelar',
    SmartGantt_ArchiveProjectDialogTitle: 'Archivar Proyecto',
    SmartGantt_ArchiveProjectDialogSubtext: '¿Archivar "{projectTitle}"? Podrá desarchivarlo más tarde.',
    SmartGantt_ArchiveButton: 'Archivar',
    SmartGantt_SendToRecycleBinDialogTitle: 'Enviar a la Papelera de Reciclaje',
    SmartGantt_SendToRecycleBinDialogSubtext: '¿Enviar "{projectTitle}" a la papelera de reciclaje del sitio?',
    SmartGantt_SendToRecycleBinButton: 'Enviar a la Papelera de Reciclaje',
    SmartGantt_FailedLoadProjects: 'No se pudieron cargar los proyectos. Verifique los permisos del sitio.',
    SmartGantt_FailedLoadTasks: 'No se pudieron cargar las tareas de este proyecto.',
    SmartGantt_FailedLoadPortfolioStats: 'No se pudieron cargar las estadísticas de la cartera.',
    SmartGantt_CouldNotSaveProject: 'No se pudo guardar el proyecto: {message}',
    SmartGantt_CouldNotDeleteProject: 'No se pudo eliminar el proyecto: {message}',
    SmartGantt_CouldNotArchiveProject: 'No se pudo archivar el proyecto: {message}',
    SmartGantt_CouldNotUnarchiveProject: 'No se pudo desarchivar el proyecto: {message}',
    SmartGantt_CouldNotSaveTask: 'No se pudo guardar la tarea: {message}',
    SmartGantt_CouldNotDeleteTask: 'No se pudo eliminar la tarea: {message}',
    SmartGantt_ImageExportFailed: 'Error al exportar la imagen: {message}',
    SmartGantt_PowerPointExportFailed: 'Error al exportar a PowerPoint: {message}',
    SmartGantt_PortfolioExportFailed: 'Error al exportar la cartera: {message}',
    SmartGantt_CouldNotUpdateTask: 'No se pudo actualizar la tarea: {message}',

    // ── Common ──
    ColorSwatch_AutoColorAriaLabel: 'Color automático',
    ColorSwatch_CustomColorAriaLabel: 'Color personalizado',
    ColorSwatch_PickCustomColorTitle: 'Elegir un color personalizado',

    // ── Export (Excel / PowerPoint) ──
    Export_ColTaskName: 'Nombre de la Tarea',
    Export_ColPhase: 'Fase',
    Export_ColStartDate: 'Fecha de Inicio',
    Export_ColDueDate: 'Fecha de Vencimiento',
    Export_ColStatus: 'Estado',
    Export_ColPriority: 'Prioridad',
    Export_ColAssignedTo: 'Asignado a',
    Export_ColAssignedToEmail: 'Correo del Asignado',
    Export_ColPercentComplete: '% Completado',
    Export_ColIsMilestone: 'Es un Hito',
    Export_ColDescription: 'Descripción',
    Export_ColNotes: 'Notas',
    Export_Yes: 'Sí',
    Export_No: 'No',
    Export_SheetNameTasks: 'Tareas',
    Export_ExcelFileSuffix: ' - Tareas.xlsx',
    Export_TaskNameColumnLabel: 'NOMBRE DE LA TAREA',
    Export_ExportedDateLabel: 'Exportado el {date}',
    Export_ProjectReportLabel: 'INFORME DEL PROYECTO',
    Export_StatusLine: 'Estado: {status}',
    Export_DateRangeSeparator: ' a ',
    Export_ProjectManagerLine: 'Jefe de Proyecto: {name}',
    Export_GeneratedDateLine: 'Generado el {date}',
    Export_ProjectSummaryTitle: 'Resumen del Proyecto',
    Export_StatTotalTasks: 'Total de Tareas',
    Export_StatCompleted: 'Completadas',
    Export_StatInProgress: 'En Curso',
    Export_StatOnHold: 'En Espera',
    Export_StatNotStarted: 'Sin Iniciar',
    Export_OverallProgressLine: 'Progreso General',
    Export_OverallProgressPercent: '{percent}%',
    Export_StatusBreakdownTitle: 'Desglose por Estado',
    Export_StatusBreakdownRow: '{status}: {count} ({percent}%)',
    Export_GanttTimelineTitle: 'Cronograma de Gantt',
    Export_SummaryRecentActivityTitle: 'Actividad Reciente',
    Export_ProjectOverviewLabel: 'Resumen del Proyecto',
    Export_DetailStatusLabel: 'Estado',
    Export_DetailStartDateLabel: 'Fecha de Inicio',
    Export_DetailDueDateLabel: 'Fecha de Vencimiento',
    Export_DetailProjectManagerLabel: 'Jefe de Proyecto',
    Export_Past7DaysLabel: 'Últimos 7 Días',
    Export_NoActivityMessage: 'Sin actividad reciente.',
    Export_CompletedThisWeekHeader: 'Completadas Esta Semana ({count})',
    Export_NewBadge: 'NUEVO  ',
    Export_CompletedPercentLine: '{percent}% completado',
    Export_MoreItemsSuffix: '+ {count} más',
    Export_InProgressUpdatedHeader: 'En Curso / Actualizadas',
    Export_StatusPercentLine: '{status} — {percent}%',
    Export_PortfolioReportLabel: 'INFORME DE CARTERA',
    Export_PortfolioOverviewTitle: 'Resumen de la Cartera',
    Export_ProjectsCountLine: '{count} Proyectos',
    Export_HealthSummaryOnTrack: '{count} En Curso Correcto',
    Export_HealthSummaryAtRisk: '{count} En Riesgo',
    Export_HealthSummaryOverdue: '{count} Vencidos',
    Export_ProjectsSummaryHeader: 'Resumen de Proyectos',
    Export_TableProject: 'Proyecto',
    Export_TableStatus: 'Estado',
    Export_TableHealth: 'Estado de Salud',
    Export_TableTotal: 'Total',
    Export_TableDone: 'Finalizadas',
    Export_TableActive: 'Activas',
    Export_TableAtRisk: 'En Riesgo',
    Export_TableOverdue: 'Vencidas',
    Export_TablePctDone: '% Finalizado',
    Export_TableDueDate: 'Fecha de Vencimiento',
    Export_PortfolioSummaryFileName: 'Resumen de Cartera.xlsx',
    Export_PortfolioReportFileName: 'Informe de Cartera.pptx',
    Export_ProjectReportFileName: 'Informe de {projectName}.pptx',
    Export_UnavailableLabel: 'No disponible',
    Export_SheetNamePortfolio: 'Portafolio',
    Export_ColStart: 'Inicio',
    Export_ColDue: 'Vencimiento',
    Export_ImageGenerationFailed: 'No se pudo generar la imagen; el diagrama puede ser demasiado grande para exportarlo como imagen.',
    Export_DrawingContextFailed: 'No se pudo crear un contexto de dibujo para la exportación.',
    Export_SvgRenderFailed: 'Error al renderizar el SVG',

    // ── Added in v1.5 review ──
    Svc_TooManyDependencies: 'Esta tarea tiene demasiadas dependencias para guardarse (el límite es de unas 60). Quite algunas e inténtelo de nuevo.',
    Svc_TaskChangedByOthers: 'Otra persona ha modificado esta tarea desde que la cargó. Actualice e inténtelo de nuevo.',
    Svc_ProjectChangedByOthers: 'Otra persona ha modificado este proyecto desde que lo abrió. Actualice e inténtelo de nuevo.',
    Svc_ColumnCreateFailed: 'No se pudieron crear {count} columna(s) en la nueva lista de tareas: {detail}',
    Svc_BaselineUnavailable: 'Las líneas base no están disponibles para este proyecto porque no se pudieron agregar las columnas de línea base (es posible que necesite permiso para editar la lista).',
    Svc_SubtaskReassignFailed: 'No se pudieron reasignar las subtareas de esta tarea antes de eliminarla: {detail}',
    Svc_UnresolvedDependency: 'Fila {row} ("{title}"): la dependencia "{name}" no se pudo vincular a una tarea importada.',
    Svc_SelfDependency: 'Fila {row} ("{title}"): la dependencia "{name}" apunta a la propia tarea y se omitió.',
    Svc_ColId: 'ID',
    Svc_ColDependencies: 'Dependencias',
    Svc_ColBaselineStart: 'Inicio de línea base',
    Svc_ColBaselineDue: 'Vencimiento de línea base',
    Svc_CsvFileSuffix: ' - Tasks.csv',
    Svc_IcsFileSuffix: ' - Milestones.ics',
    Svc_PortfolioCsvFileName: 'Portfolio Summary.csv',
    Svc_PP_DisplayGroup: 'Valores predeterminados',
    Svc_PP_DefaultView: 'Vista predeterminada',
    Svc_PP_ViewGantt: 'Gantt',
    Svc_PP_ViewList: 'Lista',
    Svc_PP_ViewKanban: 'Kanban',
    Svc_PP_ViewDashboard: 'Panel',
    Svc_PP_ViewPortfolio: 'Cartera',
    Svc_PP_DefaultZoom: 'Zoom predeterminado',
    Svc_PP_ZoomDay: 'Día',
    Svc_PP_ZoomWeek: 'Semana',
    Svc_PP_ZoomMonth: 'Mes',
    Svc_PP_ZoomQuarter: 'Trimestre',
    Svc_PP_CalendarGroup: 'Calendario laboral',
    Svc_PP_DaySun: 'El domingo es día laborable',
    Svc_PP_DayMon: 'El lunes es día laborable',
    Svc_PP_DayTue: 'El martes es día laborable',
    Svc_PP_DayWed: 'El miércoles es día laborable',
    Svc_PP_DayThu: 'El jueves es día laborable',
    Svc_PP_DayFri: 'El viernes es día laborable',
    Svc_PP_DaySat: 'El sábado es día laborable',
    Svc_PP_Holidays: 'Festivos (fechas no laborables)',
    Svc_PP_HolidaysHint: 'Una fecha por línea, con el formato aaaa-MM-dd (por ejemplo, 2026-12-25).',
    Gantt_TimelineAriaLabel: 'Cronología de tareas',
    Gantt_DragLabel: '{start} → {end} ({days} d)',
    Gantt_KeyboardMoveAnnouncement: '{taskTitle}: del {startDate} al {dueDate}',
    Gantt_KeyboardHint: 'Pulse Enter para abrir la tarea. Las teclas de flecha izquierda y derecha la mueven un día laborable. Con Shift y las flechas se cambia la fecha de finalización.',
    Gantt_ParentCycleTooltip: 'Esta tarea forma parte de una cadena circular de tarea principal y subtareas, por lo que se muestra en el nivel superior',
    Gantt_CollapseAll: 'Contraer todas las fases',
    Gantt_ExpandAll: 'Expandir todas las fases',
    Gantt_BaselineTooltip: 'Línea base: {start} → {due}',
    Gantt_VarianceTooltip: 'Desviación de finalización: {days} días respecto a la línea base',
    Gantt_LinkHandleTitle: 'Arrastre sobre otra tarea para crear una dependencia',
    Toolbar_FitToProject: 'Ajustar',
    Toolbar_FitToProjectTitle: 'Ajustar el zoom a todo el proyecto',
    Toolbar_UndoTitle: 'Deshacer (Ctrl+Z)',
    Toolbar_RedoTitle: 'Rehacer (Ctrl+Y)',
    Toolbar_ExportCsv: '📄 Exportar tareas a CSV',
    Toolbar_ExportIcs: '📅 Exportar hitos (iCal)',
    Toolbar_Print: '🖨 Imprimir / Guardar como PDF',
    Toolbar_SetBaseline: '📐 Establecer línea base…',
    Toolbar_CopyLink: '🔗 Copiar vínculo',
    Toolbar_CopyLinkTitle: 'Copiar un vínculo a esta vista (proyecto, vista, zoom y filtros)',
    App_UndoButton: 'Deshacer',
    App_Undone: 'Cambio deshecho.',
    App_Redone: 'Cambio rehecho.',
    App_DependentsMovedOne: 'Se movió 1 tarea dependiente.',
    App_DependentsMovedMany: 'Se movieron {count} tareas dependientes.',
    App_TaskConflict: 'Otra persona ha modificado esta tarea. Se han recargado las últimas tareas: revíselas e inténtelo de nuevo.',
    App_DependencyCycle: 'Ese vínculo crearía una dependencia circular.',
    App_DependencyExists: 'Esas tareas ya están vinculadas.',
    App_LinkCopied: 'Vínculo copiado en el portapapeles.',
    App_LinkCopyFailed: 'No se pudo copiar el vínculo: {message}',
    App_PopupBlocked: 'La ventana de impresión se bloqueó. Permita las ventanas emergentes para este sitio e inténtelo de nuevo.',
    App_SetBaselineDialogTitle: 'Establecer línea base',
    App_SetBaselineDialogSubtext: '¿Guardar las fechas actuales de inicio y vencimiento de las {count} tareas como línea base? Se reemplazará cualquier línea base existente.',
    App_SetBaselineButton: 'Establecer línea base',
    App_BaselineSaved: 'Línea base guardada.',
    App_BaselineFailed: 'No se pudo guardar la línea base: {message}',
    App_CsvExportFailed: 'Error en la exportación a CSV: {message}',
    App_IcsExportFailed: 'Error en la exportación del calendario: {message}',
    App_BulkDeleteDialogTitle: 'Eliminar tareas',
    App_BulkDeleteDialogSubtext: '¿Está seguro de que desea eliminar {count} tareas? Esta acción no se puede deshacer.',
    Common_PeoplePicker_ClearAriaLabel: 'Borrar',
    Common_PeoplePicker_DirectoryHeader: 'Personas del directorio',
    Common_PeoplePicker_EmailLabel: 'Correo electrónico (opcional)',
    Common_PeoplePicker_EmailPlaceholder: 'name@company.com',
    Common_PeoplePicker_ExternalHint: 'No está en el directorio. Se guardará como texto libre.',
    Common_PeoplePicker_InvalidEmail: 'Introduzca una dirección de correo electrónico válida.',
    Common_PeoplePicker_ListAriaLabel: 'Sugerencias de personas',
    Common_PeoplePicker_RecentHeader: 'Usados recientemente',
    Common_PeoplePicker_ResultsAnnouncement: '{count} sugerencias disponibles',
    Common_PeoplePicker_Searching: 'Buscando…',
    Common_PeoplePicker_UseExternal: 'Usar “{name}” (externo / no está en el directorio)',
    Import_Mapper_PreviewFirstRows: 'Vista previa (primeras {count} filas)',
    Import_Mapper_RequiredLegend: 'Campo obligatorio',
    Import_Mapper_RequiredMarkerLabel: 'Obligatorio',
    Import_Mapper_SelectAriaLabel: 'Campo de destino para la columna {columnName}',
    Import_Panel_DateOrderAuto: 'Detección automática',
    Import_Panel_DateOrderDMY: 'Día/Mes/Año (31/12/2026)',
    Import_Panel_DateOrderDetected: 'Detectado en su archivo: {order}.',
    Import_Panel_DateOrderHint: 'Se aplica a las fechas escritas con números, como 03/04/2026.',
    Import_Panel_DateOrderLabel: 'Orden de fecha',
    Import_Panel_DateOrderMDY: 'Mes/Día/Año (12/31/2026)',
    Import_Panel_DropZoneAriaLabel: 'Elija un archivo para importar. Pulse Enter para explorar.',
    Import_Panel_DropZoneChangeAriaLabel: 'Archivo seleccionado: {fileName}. Pulse Enter para elegir otro archivo.',
    Import_Panel_FailedCount: '{count} con error',
    Import_Panel_NewProjectIntroMany: 'Se creará un nuevo proyecto y se importarán en él las {count} tareas. Puede cambiar estos detalles en cualquier momento después de la importación.',
    Import_Panel_NewProjectIntroOne: 'Se creará un nuevo proyecto y se importará en él {count} tarea. Puede cambiar estos detalles en cualquier momento después de la importación.',
    Import_Panel_PlanAriaLabel: '{planName}, {groupName}',
    Import_Panel_ProblemEndBeforeStart: 'La fecha de vencimiento es anterior a la fecha de inicio',
    Import_Panel_ProblemInvalidDueDate: 'La fecha de vencimiento "{value}" no es una fecha válida',
    Import_Panel_ProblemInvalidStartDate: 'La fecha de inicio "{value}" no es una fecha válida',
    Import_Panel_ProblemMissingTitle: 'Falta el nombre de la tarea',
    Import_Panel_ProgressLabelWithPercent: '{done} de {total} ({percent} %)',
    Import_Panel_SkipInvalidRows: 'Omitir filas con problemas',
    Import_Panel_SuccessWithWarningsMany: 'Importación correcta con {count} advertencias.',
    Import_Panel_SuccessWithWarningsOne: 'Importación correcta con {count} advertencia.',
    Import_Panel_ValidationHeader: 'Filas con problemas',
    Import_Panel_ValidationMore: '…y {count} más',
    Import_Panel_ValidationRow: 'Fila {rowNum}: {problem}',
    Import_Panel_ValidationSummaryMany: '{count} filas tienen problemas',
    Import_Panel_ValidationSummaryOne: '{count} fila tiene un problema',
    Import_Panel_WarningsLabel: 'Advertencias ({count}):',
    Panel_Project_ManagerLabel: 'Director del proyecto',
    Panel_Project_ManagerPlaceholder: 'Busque personas o escriba un nombre…',
    Panel_Task_BaselineDueLabel: 'Finalización de línea base',
    Panel_Task_BaselineHeader: 'Línea base',
    Panel_Task_BaselineStartLabel: 'Inicio de línea base',
    Panel_Task_DepTypeFF: 'Fin a Fin (FF)',
    Panel_Task_DepTypeFS: 'Fin a Inicio (FS)',
    Panel_Task_DepTypeSF: 'Inicio a Fin (SF)',
    Panel_Task_DepTypeSS: 'Inicio a Inicio (SS)',
    Panel_Task_LagAriaLabel: 'Retraso en días laborables para {taskTitle}',
    Panel_Task_LagHint: 'El retraso se expresa en días laborables. Use un número negativo para un adelanto.',
    Panel_Task_LinkTypeAriaLabel: 'Tipo de vínculo para {taskTitle}',
    Panel_Task_VarianceEarlier: '{days} día(s) laborable(s) antes',
    Panel_Task_VarianceLater: '{days} día(s) laborable(s) después',
    Panel_Task_VarianceOnBaseline: 'según la línea base',
    View_Dashboard_BurndownActual: 'Real',
    View_Dashboard_BurndownAria: 'Gráfico de trabajo pendiente: quedan {remaining} de {total} tareas',
    View_Dashboard_BurndownHeader: 'Trabajo pendiente (tareas restantes)',
    View_Dashboard_BurndownIdeal: 'Ideal',
    View_Dashboard_BurndownNoData: 'No hay suficientes tareas con fechas para dibujar un gráfico de trabajo pendiente.',
    View_Dashboard_CriticalPathHeader: 'Ruta crítica  ({count})',
    View_Dashboard_PhaseDoneSummary: '{done}/{total} completadas  •  {percent} %',
    View_Dashboard_TaskRowAriaLabel: 'Abrir tarea {taskTitle}, {status}',
    View_Dashboard_WorkloadHeader: 'Carga de trabajo por responsable',
    View_Dashboard_WorkloadOpen: '{count} abiertas',
    View_Dashboard_WorkloadOverdue: '{count} vencidas',
    View_Kanban_AddTaskInColumnAriaLabel: 'Añadir tarea a {column}',
    View_Kanban_CollapseColumn: 'Contraer la columna {column}',
    View_Kanban_ExpandColumn: 'Expandir la columna {column}',
    View_Kanban_LaneHeader: '{name} ({count})',
    View_Kanban_LaneNoPhase: 'Sin fase',
    View_Kanban_LaneUnassigned: 'Sin asignar',
    View_Kanban_LanesAssignee: 'Responsable',
    View_Kanban_LanesNone: 'Ninguno',
    View_Kanban_LanesPhase: 'Fase',
    View_Kanban_SwimlanesLabel: 'Carriles',
    View_Kanban_WipEditTitle: 'Establecer el límite de trabajo en curso para {column} (0 para sin límite)',
    View_Kanban_WipExceededTitle: 'Límite de WIP superado: {count} de {limit}',
    View_Kanban_WipInputAriaLabel: 'Límite de WIP para {column}',
    View_Kanban_WipLabel: 'WIP {count}/{limit}',
    View_Kanban_WipSet: 'WIP',
    View_List_BulkAssignApply: 'Asignar',
    View_List_BulkAssigneePlaceholder: 'Asignar a…',
    View_List_BulkBarAriaLabel: 'Acciones masivas para las tareas seleccionadas',
    View_List_BulkClear: 'Borrar selección',
    View_List_BulkDelete: 'Eliminar seleccionadas',
    View_List_BulkPercentApply: 'Establecer %',
    View_List_BulkPercentPlaceholder: '% completado',
    View_List_BulkPriorityPlaceholder: 'Establecer prioridad…',
    View_List_BulkSelectedCount: '{count} seleccionadas',
    View_List_BulkStatusPlaceholder: 'Establecer estado…',
    View_List_ExportCsv: 'Exportar CSV',
    View_List_NonWorkingDay: 'Día no laborable',
    View_List_SelectAllAriaLabel: 'Seleccionar todas las tareas',
    View_List_SelectRowAriaLabel: 'Seleccionar {taskTitle}',
    View_Portfolio_CardAriaLabel: 'Abrir proyecto {projectName}, {status}',
    View_Portfolio_ClearFilters: 'Borrar filtros',
    View_Portfolio_FilteredCount: '{shown} de {total} proyectos',
    View_Portfolio_HideDone: 'Ocultar completados / cancelados',
    View_Portfolio_NoMatches: 'Ningún proyecto coincide con los filtros.',
    View_Portfolio_ProjectCountMany: '{count} proyectos',
    View_Portfolio_ProjectCountOne: '{count} proyecto',
    View_Portfolio_SearchAriaLabel: 'Buscar proyectos',
    View_Portfolio_SearchPlaceholder: 'Buscar proyectos…',
    Import_Panel_CopyDetails: 'Copiar detalles',
    Import_Panel_Copied: 'Copiado',
  };
});
