define([], function () {
  return {
    // ── Property pane ──
    PropertyPane_HeaderDescription: 'Smart Gantt Chart -asetukset',
    PropertyPane_GeneralGroupName: 'Yleiset',
    PropertyPane_TitleFieldLabel: 'Web-osan otsikko',
    WebPart_DefaultTitle: 'Smart Gantt Chart',

    // ── Toolbar ──
    Toolbar_ViewDashboard: 'Koontinäyttö',
    Toolbar_ViewList: 'Luettelo',
    Toolbar_ViewGantt: 'Gantt',
    Toolbar_ViewKanban: 'Kanban',
    Toolbar_ZoomDay: 'Päivä',
    Toolbar_ZoomWeek: 'Viikko',
    Toolbar_ZoomMonth: 'Kuukausi',
    Toolbar_ZoomQuarter: 'Vuosineljännes',
    Toolbar_SelectProjectAriaLabel: 'Valitse projekti',
    Toolbar_PortfolioLabel: 'Salkku',
    Toolbar_SelectAProject: 'Valitse projekti',
    Toolbar_AllProjectsSubtext: 'Kaikki projektit',
    Toolbar_NoProjectsYet: 'Ei vielä projekteja',
    Toolbar_ArchivedBadge: 'Arkistoitu',
    Toolbar_ShowArchivedProjects: 'Näytä arkistoidut projektit',
    Toolbar_NewProject: '+ Uusi projekti',
    Toolbar_ImportFileAsNewProject: '📥 Tuo tiedosto uutena projektina…',
    Toolbar_AddTask: '+ Lisää tehtävä',
    Toolbar_EditProject: 'Muokkaa projektia',
    Toolbar_OptionsButton: '⚙ Asetukset',
    Toolbar_MoreOptionsTitle: 'Lisää asetuksia',
    Toolbar_ExportToExcel: '📊 Vie Exceliin',
    Toolbar_ExportToPowerPoint: '📑 Vie PowerPointiin',
    Toolbar_ScrollToTodayTitle: 'Vieritä tähän päivään',
    Toolbar_TodayButton: '◉ Tänään',
    Toolbar_ImportTasks: '📥 Tuo tehtäviä…',
    Toolbar_ExportAsImage: '🖼 Vie kuvana (PNG)',
    Toolbar_UnarchiveProject: '📂 Palauta arkistosta',
    Toolbar_ArchiveProject: '🗄️ Arkistoi projekti',
    Toolbar_SendToRecycleBin: '🗑️ Siirrä roskakoriin',

    // ── Filter bar ──
    FilterBar_ClearOption: 'Tyhjennä',
    FilterBar_DueAny: 'Mikä tahansa eräpäivä',
    FilterBar_DueOverdue: 'Myöhässä',
    FilterBar_DueToday: 'Erääntyy tänään',
    FilterBar_DueWeek: 'Erääntyy 7 päivässä',
    FilterBar_SearchPlaceholder: 'Hae tehtäviä…',
    FilterBar_SearchAriaLabel: 'Hae tehtäviä',
    FilterBar_StatusChipLabel: 'Tila',
    FilterBar_PriorityChipLabel: 'Prioriteetti',
    FilterBar_AssigneeChipLabel: 'Vastuuhenkilö',
    FilterBar_PhaseChipLabel: 'Vaihe',
    FilterBar_DueDateAriaLabel: 'Suodata eräpäivän mukaan',
    FilterBar_MatchCount: '{matchCount} / {totalCount}',
    FilterBar_ClearFilters: '✕ Tyhjennä suodattimet',
    FilterBar_ChipLabelWithCount: '{label} ({count}) ▾',
    FilterBar_ChipLabelNoCount: '{label} ▾',

    // ── Gantt view ──
    Gantt_TaskColumnHeader: 'Tehtävä',
    Gantt_DurationColumnHeader: 'Kesto',
    Gantt_AddTaskButton: '+ Lisää tehtävä',
    Gantt_EmptyTitle: 'Ei vielä tehtäviä',
    Gantt_EmptySubtitle: 'Lisää tehtäviä nähdäksesi ne Gantt-kaaviossa.',
    Gantt_AddFirstTask: '+ Lisää ensimmäinen tehtävä',
    Gantt_ImportTasksButton: '📥 Tuo tehtäviä',
    Gantt_EditTitle: 'Muokkaa',
    Gantt_DeleteTitle: 'Poista',
    Gantt_EditTaskAriaLabel: 'Muokkaa tehtävää {taskTitle}',
    Gantt_DeleteTaskAriaLabel: 'Poista tehtävä {taskTitle}',
    Gantt_ExpandPhaseAriaLabel: '{action} vaihe {phase}',
    Gantt_ExpandAction: 'Laajenna',
    Gantt_CollapseAction: 'Tiivistä',
    Gantt_DependencyViolationTooltip: 'Aloitettu ennen kuin kaikki riippuvuudet oli suoritettu',
    Gantt_MilestoneAriaLabel: '{taskTitle}, virstanpylväs, {date}',
    Gantt_BarAriaLabel: '{taskTitle}, {startDate}–{dueDate}, {percent}% valmis',
    Gantt_PercentCompleteTooltip: '{value}% valmis',

    // ── Gantt options/settings panel ──
    GanttSettings_PanelHeader: '⚙ Asetukset',
    GanttSettings_ColorCodingSection: 'Värikoodaus',
    GanttSettings_ByStatus: 'Tilan mukaan',
    GanttSettings_ByPriority: 'Prioriteetin mukaan',
    GanttSettings_ByPhase: 'Vaiheen mukaan',
    GanttSettings_ByHealth: 'Tilan (health) mukaan',
    GanttSettings_HeaderColorSection: 'Otsikkorivin väri',
    GanttSettings_ThemeDark: 'Tumma',
    GanttSettings_ThemeNavy: 'Laivastonsininen',
    GanttSettings_ThemeTeal: 'Sinivihreä',
    GanttSettings_ThemePurple: 'Violetti',
    GanttSettings_ThemeLight: 'Vaalea',
    GanttSettings_HeaderLabelsSection: 'Otsikkorivin merkinnät',
    GanttSettings_WeekLabelDates: 'Päivämäärät',
    GanttSettings_WeekLabelDatesDesc: '3. kesäk., 10. kesäk.…',
    GanttSettings_WeekLabelProject: 'Projektiviikot',
    GanttSettings_WeekLabelProjectDesc: 'V1, V2…',
    GanttSettings_WeekLabelIso: 'Kalenteriviikot',
    GanttSettings_WeekLabelIsoDesc: 'Vk23, Vk24…',
    GanttSettings_ProjectWeeksHint: 'Viikko 1 alkaa varhaisimman tehtäväsi maanantaista — erinomainen esityksiin.',
    GanttSettings_BarStyleSection: 'Palkkien tyyli',
    GanttSettings_BarStyleGradient: 'Liukuväri',
    GanttSettings_BarStyleFlat: 'Yksivärinen',
    GanttSettings_RowHeightSection: 'Rivin korkeus',
    GanttSettings_HeightCompact: 'Tiivis',
    GanttSettings_HeightNormal: 'Normaali',
    GanttSettings_HeightSpacious: 'Väljä',
    GanttSettings_ShowHideSection: 'Näytä / piilota',
    GanttSettings_WeekendShading: 'Viikonlopun korostus',
    GanttSettings_DependencyArrows: 'Riippuvuusnuolet',
    GanttSettings_CriticalPathAlwaysVisible: 'Kriittinen polku aina näkyvissä',
    GanttSettings_AllOthersOnHoverOnly: 'Muut vain kohdistettaessa',
    GanttSettings_CriticalPathHighlight: 'Kriittisen polun korostus',
    GanttSettings_ProgressPercentOnBars: 'Edistymisprosentti palkeissa',
    GanttSettings_AssigneeNameOnBars: 'Vastuuhenkilön nimi palkeissa',
    GanttSettings_HealthStatusBadges: 'Tilamerkinnät (health)',

    // ── List view ──
    ListView_ColTaskName: 'Tehtävän nimi',
    ListView_ColStatus: 'Tila',
    ListView_ColHealth: 'Tila (health)',
    ListView_ColPriority: 'Prioriteetti',
    ListView_ColStart: 'Alkaa',
    ListView_ColDue: 'Erääntyy',
    ListView_ColAssignedTo: 'Vastuuhenkilö',
    ListView_ColProgress: 'Edistyminen',
    ListView_ColPhase: 'Vaihe',
    ListView_ColPredecessors: 'Edeltäjät',
    ListView_EmptyTitle: 'Ei vielä tehtäviä',
    ListView_AddFirstTask: '+ Lisää ensimmäinen tehtävä',
    ListView_AddTaskRow: '+ Lisää tehtävä',
    ListView_Unassigned: 'Ei vastuuhenkilöä',
    ListView_DependencyViolationTooltip: 'Aloitettu ennen kuin kaikki riippuvuudet oli suoritettu',
    ListView_StatusAriaLabel: 'Tehtävän {taskTitle} tila',
    ListView_PriorityAriaLabel: 'Tehtävän {taskTitle} prioriteetti',
    ListView_EditTaskAriaLabel: 'Muokkaa tehtävää {taskTitle}',
    ListView_DeleteTaskAriaLabel: 'Poista tehtävä {taskTitle}',
    ListView_EditTitle: 'Muokkaa',
    ListView_DeleteTitle: 'Poista',

    // ── Kanban view ──
    Kanban_ColumnNotStarted: 'Ei aloitettu',
    Kanban_ColumnInProgress: 'Käynnissä',
    Kanban_ColumnOnHold: 'Keskeytetty',
    Kanban_ColumnCompleted: 'Valmis',
    Kanban_ColumnCancelled: 'Peruttu',
    Kanban_AddTaskButton: '+ Lisää tehtävä',
    Kanban_EditTitle: 'Muokkaa',
    Kanban_DeleteTitle: 'Poista',
    Kanban_CardAriaLabel: '{taskTitle}, {status}. Paina Enter muokataksesi, nuolinäppäimillä vasen/oikea vaihdat tilaa.',
    Kanban_EditTaskAriaLabel: 'Muokkaa tehtävää {taskTitle}',
    Kanban_DeleteTaskAriaLabel: 'Poista tehtävä {taskTitle}',

    // ── Dashboard view ──
    Dashboard_TotalTasks: 'Tehtäviä yhteensä',
    Dashboard_Completed: 'Valmis',
    Dashboard_InProgress: 'Käynnissä',
    Dashboard_OnHold: 'Keskeytetty',
    Dashboard_NotStarted: 'Ei aloitettu',
    Dashboard_Cancelled: 'Peruttu',
    Dashboard_OverallProgress: 'Kokonaisedistyminen',
    Dashboard_ProjectManagerLabel: 'Projektipäällikkö: {name}',
    Dashboard_PhaseProgressHeader: 'Vaiheiden edistyminen',
    Dashboard_StatusBreakdownHeader: 'Tilan erittely',
    Dashboard_PriorityBreakdownHeader: 'Prioriteetin erittely',
    Dashboard_PriorityCritical: 'Kriittinen',
    Dashboard_PriorityHigh: 'Korkea',
    Dashboard_PriorityMedium: 'Keskitaso',
    Dashboard_PriorityLow: 'Matala',
    Dashboard_OverdueHeader: 'Myöhässä  ({count})',
    Dashboard_DueNext14DaysHeader: 'Erääntyy seuraavien 14 päivän aikana  ({count})',
    Dashboard_CompletedThisWeekHeader: 'Valmistui tällä viikolla',
    Dashboard_UpdatedThisWeekHeader: 'Päivitetty tällä viikolla',
    Dashboard_Today: 'Tänään',
    Dashboard_Tomorrow: 'Huomenna',
    Dashboard_DaysLeft: '{days} pv',
    Dashboard_EmptyTitle: 'Ei vielä tehtäviä',
    Dashboard_EmptySubtitle: 'Lisää tehtäviä nähdäksesi projektin koontinäytön.',
    Dashboard_AddTaskButton: '+ Lisää tehtävä',

    // ── Portfolio view ──
    Portfolio_ProjectCount: '{count} projekti{plural}',
    Portfolio_OnTrackSummary: '{count} aikataulussa',
    Portfolio_AtRiskSummary: '{count} riskissä',
    Portfolio_OverdueSummary: '{count} myöhässä',
    Portfolio_DoneSummary: '{count} valmis',
    Portfolio_SortLabel: 'Järjestä:',
    Portfolio_SortAZ: 'A-Ö',
    Portfolio_SortHealth: 'Tila (health)',
    Portfolio_SortStatus: 'Tila',
    Portfolio_SortCompletion: 'Valmiusaste',
    Portfolio_RefreshTitle: 'Päivitä',
    Portfolio_RefreshButton: 'Päivitä',
    Portfolio_LoadingStats: 'Ladataan tilastoja…',
    Portfolio_EmptyTitle: 'Ei vielä projekteja',
    Portfolio_CreateFirstProject: '+ Luo ensimmäinen projekti',
    Portfolio_StatsUnavailable: 'Tilastot eivät ole saatavilla',
    Portfolio_StatsUnavailableDetail: 'Tämän projektin tilastoja ei voitu ladata.',
    Portfolio_OverallProgressLabel: 'Kokonaisedistyminen',
    Portfolio_TaskCountDone: 'Valmis',
    Portfolio_TaskCountActive: 'Aktiivinen',
    Portfolio_TaskCountAtRisk: 'Riskissä',
    Portfolio_TaskCountOverdue: 'Myöhässä',
    Portfolio_ViewGanttLink: 'Näytä Gantt →',
    Portfolio_TodayTooltip: 'Tänään',

    // ── Task panel ──
    TaskPanel_EditHeader: 'Muokkaa: {taskTitle}',
    TaskPanel_NewTaskHeader: 'Uusi tehtävä',
    TaskPanel_TabBasic: 'Perustiedot',
    TaskPanel_TabDetails: 'Lisätiedot',
    TaskPanel_TabLinks: 'Linkit',
    TaskPanel_ProjectLabelPrefix: 'Projekti: ',
    TaskPanel_TaskNameLabel: 'Tehtävän nimi',
    TaskPanel_TaskNamePlaceholder: 'Kirjoita tehtävän nimi',
    TaskPanel_TaskNameRequired: 'Tehtävän nimi on pakollinen',
    TaskPanel_DescriptionLabel: 'Kuvaus',
    TaskPanel_DescriptionPlaceholder: 'Kirjoita kuvaus',
    TaskPanel_StartDateLabel: 'Alkamispäivä',
    TaskPanel_DueDateLabel: 'Eräpäivä',
    TaskPanel_DueDateError: 'Eräpäivän on oltava sama tai myöhäisempi kuin alkamispäivä',
    TaskPanel_StatusLabel: 'Tila',
    TaskPanel_PriorityLabel: 'Prioriteetti',
    TaskPanel_PercentCompleteLabel: 'Valmis: {percent}%',
    TaskPanel_AssignedToLabel: 'Vastuuhenkilö',
    TaskPanel_AssignedToPlaceholder: 'Hae henkilöitä…',
    TaskPanel_PhaseLabel: 'Vaihe',
    TaskPanel_PhasePlaceholder: 'Kirjoita vaiheen nimi',
    TaskPanel_PhaseHint: 'Ryhmittelee tehtävät yhteen Gantt- ja luettelonäkymissä.',
    TaskPanel_MilestoneLabel: 'Virstanpylväs',
    TaskPanel_MilestoneOnText: 'Kyllä',
    TaskPanel_MilestoneOffText: 'Ei',
    TaskPanel_CustomBarColorLabel: 'Mukautettu palkin väri',
    TaskPanel_CustomBarColorOptionalSuffix: ' (valinnainen)',
    TaskPanel_AutoColorHint: 'Automaattinen väri tila-/prioriteetti-/vaiheasetusten perusteella.',
    TaskPanel_NotesLabel: 'Muistiinpanot',
    TaskPanel_NotesPlaceholder: 'Kirjoita muistiinpanoja',
    TaskPanel_ParentTaskLabel: 'Ylätehtävä',
    TaskPanel_ParentTaskNone: '(ei mikään)',
    TaskPanel_ParentTaskHasChildrenHint: 'Tällä tehtävällä on alitehtäviä, joten sillä ei voi olla omaa ylätehtävää.',
    TaskPanel_ParentTaskHint: 'Sijoita tämä tehtävä toisen alle alitehtäväksi.',
    TaskPanel_DependsOnLabel: 'Riippuu tehtävistä',
    TaskPanel_RemoveDependencyTitle: 'Poista riippuvuus tehtävään "{taskTitle}"',
    TaskPanel_AddDependencyPlaceholder: 'Lisää riippuvuus…',
    TaskPanel_SelectATaskOption: 'Valitse tehtävä…',
    TaskPanel_DependsOnHint: 'Tehtävä ei voi alkaa ennen kuin nämä on suoritettu.',
    TaskPanel_SavingLabel: 'Tallennetaan…',
    TaskPanel_CreatingLabel: 'Luodaan…',
    TaskPanel_SaveChangesButton: 'Tallenna muutokset',
    TaskPanel_CreateTaskButton: 'Luo tehtävä',
    TaskPanel_CancelButton: 'Peruuta',
    TaskPanel_DismissAriaLabel: 'Hylkää',
    TaskPanel_DiscardUnsavedChangesConfirm: 'Hylätäänkö tallentamattomat muutokset?',
    TaskPanel_SaveFallbackError: 'Tehtävää ei voitu tallentaa.',

    // ── Project panel ──
    ProjectPanel_EditHeader: 'Muokkaa projektia',
    ProjectPanel_NewHeader: 'Uusi projekti',
    ProjectPanel_ProjectNameLabel: 'Projektin nimi',
    ProjectPanel_ProjectNamePlaceholder: 'Kirjoita projektin nimi',
    ProjectPanel_ProjectNameRequired: 'Projektin nimi on pakollinen',
    ProjectPanel_DescriptionLabel: 'Kuvaus',
    ProjectPanel_DescriptionPlaceholder: 'Kirjoita kuvaus',
    ProjectPanel_ProjectColorLabel: 'Projektin väri',
    ProjectPanel_StatusLabel: 'Tila',
    ProjectPanel_StartDateLabel: 'Alkamispäivä',
    ProjectPanel_DueDateLabel: 'Eräpäivä',
    ProjectPanel_DueDateError: 'Eräpäivän on oltava sama tai myöhäisempi kuin alkamispäivä',
    ProjectPanel_WhatHappensNextTitle: 'Mitä tapahtuu seuraavaksi?',
    ProjectPanel_WhatHappensNextBody: 'Kun projekti on luotu, voit lisätä tehtäviä, määrittää vaiheita ja seurata edistymistä.',
    ProjectPanel_SavingLabel: 'Tallennetaan…',
    ProjectPanel_CreatingLabel: 'Luodaan…',
    ProjectPanel_SaveChangesButton: 'Tallenna muutokset',
    ProjectPanel_CreateProjectButton: 'Luo projekti',
    ProjectPanel_CancelButton: 'Peruuta',
    ProjectPanel_DismissAriaLabel: 'Hylkää',
    ProjectPanel_DiscardUnsavedChangesConfirm: 'Hylätäänkö tallentamattomat muutokset?',
    ProjectPanel_SaveFallbackError: 'Projektia ei voitu tallentaa.',

    // ── Import panel ──
    ImportPanel_SourceExcelTitle: 'Excel-/CSV-tiedosto',
    ImportPanel_SourceExcelSubtitle: 'Tuo tehtäviä laskentataulukosta',
    ImportPanel_SourcePlannerTitle: 'Microsoft Planner',
    ImportPanel_SourcePlannerSubtitle: 'Tuo tehtäviä Planner-suunnitelmasta',
    ImportPanel_ClickToBrowse: 'Napsauta selataksesi',
    ImportPanel_DragDropSuffix: ' tai vedä ja pudota',
    ImportPanel_SupportedExtensions: 'Tuetut muodot: .xlsx, .xls, .csv',
    ImportPanel_RowsColsSummary: '{rows} riviä, {cols} saraketta havaittu',
    ImportPanel_LoadingPlannerPlans: 'Ladataan Planner-suunnitelmia…',
    ImportPanel_PlannerLoadError: 'Planner-suunnitelmia ei voitu ladata.',
    ImportPanel_PlannerPermissionsHintPrefix: 'Varmista, että sinulla on käyttöoikeus Planneriin ja että ',
    ImportPanel_PlannerPermissionsHintEmphasis: 'Tasks by Planner and To Do',
    ImportPanel_PlannerPermissionsHintSuffix: ' on käytettävissä tällä sivustolla.',
    ImportPanel_NoPlannerPlansFoundTitle: 'Planner-suunnitelmia ei löytynyt',
    ImportPanel_NoPlannerPlansFoundBody: 'Sinulla ei ehkä ole käyttöoikeutta yhteenkään Planner-suunnitelmaan, tai niitä ei ole tälle tilille.',
    ImportPanel_TaskCountFoundIn: '{count} tehtävää löytyi suunnitelmasta "{planName}"',
    ImportPanel_ProjectDetailsIntroPrefix: 'Tuodaan kohteeseen ',
    ImportPanel_ProjectDetailsIntroSuffix: '. Tarkista projektin tiedot alla.',
    ImportPanel_ProjectNameLabel: 'Projektin nimi',
    ImportPanel_DescriptionLabel: 'Kuvaus',
    ImportPanel_StatusLabel: 'Tila',
    ImportPanel_ColorLabel: 'Väri',
    ImportPanel_MapIntro: 'Yhdistä tiedoston sarakkeet tehtäväkenttiin.',
    ImportPanel_CreatingProjectStatus: 'Luodaan projektia…',
    ImportPanel_ImportingTasksStatus: 'Tuodaan tehtäviä…',
    ImportPanel_ProgressLabel: '{done}/{total}',
    ImportPanel_CouldNotCreateProject: 'Projektia ei voitu luoda.',
    ImportPanel_ImportCompletedWithErrors: 'Tuonti valmistui {count} virheellä.',
    ImportPanel_ProjectCreatedSuccess: 'Projekti luotiin onnistuneesti!',
    ImportPanel_ImportSuccessful: 'Tuonti onnistui!',
    ImportPanel_TasksAddedTo: '{count} tehtävää lisätty projektiin "{projectName}"',
    ImportPanel_FailedRowsLabel: 'Epäonnistuneet rivit:',
    ImportPanel_CloseButton: 'Sulje',
    ImportPanel_OpenProjectButton: 'Avaa projekti',
    ImportPanel_ViewImportedTasksButton: 'Näytä tuodut tehtävät',
    ImportPanel_NextMapColumnsButton: 'Seuraava: Yhdistä sarakkeet',
    ImportPanel_ImportNTasksButton: 'Tuo {count} tehtävää',
    ImportPanel_BackButton: 'Takaisin',
    ImportPanel_CancelButton: 'Peruuta',
    ImportPanel_NextButton: 'Seuraava',
    ImportPanel_StepSource: 'Lähde',
    ImportPanel_StepProject: 'Projekti',
    ImportPanel_StepMap: 'Yhdistä',
    ImportPanel_StepImport: 'Tuonti',
    ImportPanel_StepDone: 'Valmis',
    ImportPanel_ImportAsNewProjectHeader: 'Tuo tiedosto uutena projektina',
    ImportPanel_ImportIntoProjectHeader: 'Tuo tehtäviä projektiin {projectName}',
    ImportPanel_CouldNotParseFile: 'Tiedostoa ei voitu jäsentää.',
    ImportPanel_CouldNotLoadPlannerTasks: 'Tämän suunnitelman tehtäviä ei voitu ladata.',
    ImportPanel_CouldNotCreateProjectDetail: 'Projektia ei voitu luoda: {detail}',
    ImportPanel_CouldNotLinkDependencies: 'Riippuvuuksia ei voitu yhdistää: {detail}',
    ImportPanel_UnknownError: 'tuntematon virhe',

    // ── Column mapper (import) ──
    ColumnMapper_TaskNameRequiredBanner: 'Tehtävän nimi on yhdistettävä ennen kuin voit jatkaa.',
    ColumnMapper_SkippedColumnsBanner: '{count} saraketta ohitetaan.',
    ColumnMapper_SourceColumnHeader: 'Lähdesarake',
    ColumnMapper_TargetFieldHeader: 'Kohdekenttä',
    ColumnMapper_StatusHeader: 'Tila',
    ColumnMapper_SkippedBadge: 'Ohitettu',
    ColumnMapper_AutoMappedBadge: 'Automaattisesti yhdistetty',
    ColumnMapper_SetBadge: 'Asetettu',
    ColumnMapper_PreviewTitle: 'Esikatselu: {columnName}',
    ColumnMapper_EmptyCellDash: '—',

    // ── Import field display names / ImportService ──
    ImportField_TaskName: 'Tehtävän nimi',
    ImportField_StartDate: 'Alkamispäivä',
    ImportField_DueDate: 'Eräpäivä',
    ImportField_Status: 'Tila',
    ImportField_Priority: 'Prioriteetti',
    ImportField_AssignedTo: 'Vastuuhenkilö',
    ImportField_AssignedToEmail: 'Vastuuhenkilön sähköposti',
    ImportField_PercentComplete: 'Valmis %',
    ImportField_Phase: 'Vaihe',
    ImportField_Description: 'Kuvaus',
    ImportField_Notes: 'Muistiinpanot',
    ImportField_IsMilestone: 'On virstanpylväs',
    ImportField_Dependencies: 'Riippuvuudet',
    ImportField_SkipColumn: '(Ohita tämä sarake)',
    ImportService_EmptyFileError: 'Tiedosto näyttää olevan tyhjä tai siinä ei ole datarivejä.',
    ImportService_ReadErrorDetail: 'Tiedostoa ei voitu lukea: {detail}.',
    ImportService_FileReadError: 'Tiedoston lukuvirhe.',
    ImportService_RowError: 'Rivi {rowNum} ("{title}"): {error}',
    ImportService_AmbiguousDependency: 'Riippuvuus "{name}" täsmää useampaan tehtävän nimeen — ohitettu.',
    ImportService_LinkDependencyError: 'Riippuvuuksia ei voitu yhdistää tehtävälle {taskId}: {error}',

    // ── Health labels (shared: healthUtils.ts and ExportService.ts both use this set; also replaces the duplicated Export_PortfolioHealthLabel* keys) ──
    Health_Done: 'Valmis',
    Health_OnTrack: 'Aikataulussa',
    Health_AtRisk: 'Riskissä',
    Health_Overdue: 'Myöhässä',

    // ── Status / Priority display labels (DISPLAY-ONLY — stored SharePoint Choice values remain unchanged/English) ──
    Status_NotStarted: 'Ei aloitettu',
    Status_InProgress: 'Käynnissä',
    Status_Completed: 'Valmis',
    Status_OnHold: 'Keskeytetty',
    Status_Cancelled: 'Peruttu',
    Priority_Critical: 'Kriittinen',
    Priority_High: 'Korkea',
    Priority_Medium: 'Keskitaso',
    Priority_Low: 'Matala',
    ProjectStatus_Planning: 'Suunnittelu',
    ProjectStatus_Active: 'Aktiivinen',
    ProjectStatus_OnHold: 'Keskeytetty',
    ProjectStatus_Completed: 'Valmis',
    ProjectStatus_Cancelled: 'Peruttu',

    // ── Shell (SmartGantt.tsx) ──
    SmartGantt_LoadingProjects: 'Ladataan projekteja…',
    SmartGantt_UnableToLoad: 'Lataaminen epäonnistui',
    SmartGantt_RetryButton: 'Yritä uudelleen',
    SmartGantt_NoProjectsYet: 'Ei vielä projekteja',
    SmartGantt_NoProjectsSubtitle: 'Luo ensimmäinen projektisi aloittaaksesi.',
    SmartGantt_CreateFirstProjectButton: '+ Luo ensimmäinen projekti',
    SmartGantt_ImportFromExcelButton: '📥 Tuo Excelistä',
    SmartGantt_LoadingTasks: 'Ladataan tehtäviä…',
    SmartGantt_DismissAriaLabel: 'Hylkää',
    SmartGantt_DeleteTaskDialogTitle: 'Poista tehtävä',
    SmartGantt_DeleteTaskDialogSubtext: 'Haluatko varmasti poistaa tehtävän "{taskTitle}"? Tätä ei voi kumota.',
    SmartGantt_DeleteButton: 'Poista',
    SmartGantt_CancelButton: 'Peruuta',
    SmartGantt_ArchiveProjectDialogTitle: 'Arkistoi projekti',
    SmartGantt_ArchiveProjectDialogSubtext: 'Arkistoidaanko "{projectTitle}"? Voit palauttaa sen myöhemmin.',
    SmartGantt_ArchiveButton: 'Arkistoi',
    SmartGantt_SendToRecycleBinDialogTitle: 'Siirrä roskakoriin',
    SmartGantt_SendToRecycleBinDialogSubtext: 'Siirretäänkö "{projectTitle}" sivuston roskakoriin?',
    SmartGantt_SendToRecycleBinButton: 'Siirrä roskakoriin',
    SmartGantt_FailedLoadProjects: 'Projektien lataaminen epäonnistui. Tarkista sivuston käyttöoikeudet.',
    SmartGantt_FailedLoadTasks: 'Tämän projektin tehtävien lataaminen epäonnistui.',
    SmartGantt_FailedLoadPortfolioStats: 'Salkun tilastojen lataaminen epäonnistui.',
    SmartGantt_CouldNotSaveProject: 'Projektia ei voitu tallentaa: {message}',
    SmartGantt_CouldNotDeleteProject: 'Projektia ei voitu poistaa: {message}',
    SmartGantt_CouldNotArchiveProject: 'Projektia ei voitu arkistoida: {message}',
    SmartGantt_CouldNotUnarchiveProject: 'Projektia ei voitu palauttaa arkistosta: {message}',
    SmartGantt_CouldNotSaveTask: 'Tehtävää ei voitu tallentaa: {message}',
    SmartGantt_CouldNotDeleteTask: 'Tehtävää ei voitu poistaa: {message}',
    SmartGantt_ImageExportFailed: 'Kuvana vieminen epäonnistui: {message}',
    SmartGantt_PowerPointExportFailed: 'PowerPoint-vienti epäonnistui: {message}',
    SmartGantt_PortfolioExportFailed: 'Salkun vienti epäonnistui: {message}',
    SmartGantt_CouldNotUpdateTask: 'Tehtävää ei voitu päivittää: {message}',

    // ── Common ──
    ColorSwatch_AutoColorAriaLabel: 'Automaattinen väri',
    ColorSwatch_CustomColorAriaLabel: 'Mukautettu väri',
    ColorSwatch_PickCustomColorTitle: 'Valitse mukautettu väri',

    // ── Export (Excel / PowerPoint) ──
    Export_ColTaskName: 'Tehtävän nimi',
    Export_ColPhase: 'Vaihe',
    Export_ColStartDate: 'Alkamispäivä',
    Export_ColDueDate: 'Eräpäivä',
    Export_ColStatus: 'Tila',
    Export_ColPriority: 'Prioriteetti',
    Export_ColAssignedTo: 'Vastuuhenkilö',
    Export_ColAssignedToEmail: 'Vastuuhenkilön sähköposti',
    Export_ColPercentComplete: 'Valmis %',
    Export_ColIsMilestone: 'On virstanpylväs',
    Export_ColDescription: 'Kuvaus',
    Export_ColNotes: 'Muistiinpanot',
    Export_Yes: 'Kyllä',
    Export_No: 'Ei',
    Export_SheetNameTasks: 'Tehtävät',
    Export_ExcelFileSuffix: ' - Tehtävät.xlsx',
    Export_TaskNameColumnLabel: 'TEHTÄVÄN NIMI',
    Export_ExportedDateLabel: 'Viety {date}',
    Export_ProjectReportLabel: 'PROJEKTIRAPORTTI',
    Export_StatusLine: 'Tila: {status}',
    Export_DateRangeSeparator: ' – ',
    Export_ProjectManagerLine: 'Projektipäällikkö: {name}',
    Export_GeneratedDateLine: 'Luotu {date}',
    Export_ProjectSummaryTitle: 'Projektin yhteenveto',
    Export_StatTotalTasks: 'Tehtäviä yhteensä',
    Export_StatCompleted: 'Valmis',
    Export_StatInProgress: 'Käynnissä',
    Export_StatOnHold: 'Keskeytetty',
    Export_StatNotStarted: 'Ei aloitettu',
    Export_OverallProgressLine: 'Kokonaisedistyminen',
    Export_OverallProgressPercent: '{percent}%',
    Export_StatusBreakdownTitle: 'Tilan erittely',
    Export_StatusBreakdownRow: '{status}: {count} ({percent}%)',
    Export_GanttTimelineTitle: 'Gantt-aikajana',
    Export_SummaryRecentActivityTitle: 'Viimeaikainen toiminta',
    Export_ProjectOverviewLabel: 'Projektin yleiskatsaus',
    Export_DetailStatusLabel: 'Tila',
    Export_DetailStartDateLabel: 'Alkamispäivä',
    Export_DetailDueDateLabel: 'Eräpäivä',
    Export_DetailProjectManagerLabel: 'Projektipäällikkö',
    Export_Past7DaysLabel: 'Viimeiset 7 päivää',
    Export_NoActivityMessage: 'Ei viimeaikaista toimintaa.',
    Export_CompletedThisWeekHeader: 'Valmistui tällä viikolla ({count})',
    Export_NewBadge: 'UUSI  ',
    Export_CompletedPercentLine: '{percent}% valmis',
    Export_MoreItemsSuffix: '+ {count} lisää',
    Export_InProgressUpdatedHeader: 'Käynnissä / Päivitetty',
    Export_StatusPercentLine: '{status} — {percent}%',
    Export_PortfolioReportLabel: 'SALKKURAPORTTI',
    Export_PortfolioOverviewTitle: 'Salkun yleiskatsaus',
    Export_ProjectsCountLine: '{count} projektia',
    Export_HealthSummaryOnTrack: '{count} aikataulussa',
    Export_HealthSummaryAtRisk: '{count} riskissä',
    Export_HealthSummaryOverdue: '{count} myöhässä',
    Export_ProjectsSummaryHeader: 'Projektien yhteenveto',
    Export_TableProject: 'Projekti',
    Export_TableStatus: 'Tila',
    Export_TableHealth: 'Tila (health)',
    Export_TableTotal: 'Yhteensä',
    Export_TableDone: 'Valmis',
    Export_TableActive: 'Aktiivinen',
    Export_TableAtRisk: 'Riskissä',
    Export_TableOverdue: 'Myöhässä',
    Export_TablePctDone: 'Valmis %',
    Export_TableDueDate: 'Eräpäivä',
    Export_PortfolioSummaryFileName: 'Salkun yhteenveto.xlsx',
    Export_PortfolioReportFileName: 'Salkkuraportti.pptx',
    Export_ProjectReportFileName: '{projectName} - raportti.pptx',
    Export_UnavailableLabel: 'Ei saatavilla',
    Export_SheetNamePortfolio: 'Salkku',
    Export_ColStart: 'Alkaa',
    Export_ColDue: 'Erääntyy',
    Export_ImageGenerationFailed: 'Kuvaa ei voitu luoda – kaavio saattaa olla liian suuri vietäväksi kuvana.',
    Export_DrawingContextFailed: 'Piirtokontekstia vientiä varten ei voitu luoda.',
    Export_SvgRenderFailed: 'SVG-renderöinti epäonnistui',
  };
});
