define([], function () {
  return {
    // ── Property pane ──
    PropertyPane_HeaderDescription: 'Paramètres du diagramme de Gantt intelligent',
    PropertyPane_GeneralGroupName: 'Général',
    PropertyPane_TitleFieldLabel: 'Titre du composant WebPart',
    WebPart_DefaultTitle: 'Diagramme de Gantt intelligent',

    // ── Toolbar ──
    Toolbar_ViewDashboard: 'Tableau de bord',
    Toolbar_ViewList: 'Liste',
    Toolbar_ViewGantt: 'Gantt',
    Toolbar_ViewKanban: 'Kanban',
    Toolbar_ZoomDay: 'Jour',
    Toolbar_ZoomWeek: 'Semaine',
    Toolbar_ZoomMonth: 'Mois',
    Toolbar_ZoomQuarter: 'Trimestre',
    Toolbar_SelectProjectAriaLabel: 'Sélectionner un projet',
    Toolbar_PortfolioLabel: 'Portefeuille',
    Toolbar_SelectAProject: 'Sélectionner un projet',
    Toolbar_AllProjectsSubtext: 'Tous les projets',
    Toolbar_NoProjectsYet: 'Aucun projet pour le moment',
    Toolbar_ArchivedBadge: 'Archivé',
    Toolbar_ShowArchivedProjects: 'Afficher les projets archivés',
    Toolbar_NewProject: '+ Nouveau projet',
    Toolbar_ImportFileAsNewProject: '📥 Importer un fichier comme nouveau projet…',
    Toolbar_AddTask: '+ Ajouter une tâche',
    Toolbar_EditProject: 'Modifier le projet',
    Toolbar_OptionsButton: '⚙ Options',
    Toolbar_MoreOptionsTitle: 'Plus d\'options',
    Toolbar_ExportToExcel: '📊 Exporter vers Excel',
    Toolbar_ExportToPowerPoint: '📑 Exporter vers PowerPoint',
    Toolbar_ScrollToTodayTitle: 'Aller à aujourd\'hui',
    Toolbar_TodayButton: '◉ Aujourd\'hui',
    Toolbar_ImportTasks: '📥 Importer des tâches…',
    Toolbar_ExportAsImage: '🖼 Exporter en image (PNG)',
    Toolbar_UnarchiveProject: '📂 Désarchiver le projet',
    Toolbar_ArchiveProject: '🗄️ Archiver le projet',
    Toolbar_SendToRecycleBin: '🗑️ Envoyer à la corbeille',

    // ── Filter bar ──
    FilterBar_ClearOption: 'Effacer',
    FilterBar_DueAny: 'Toute échéance',
    FilterBar_DueOverdue: 'En retard',
    FilterBar_DueToday: 'Échéance aujourd\'hui',
    FilterBar_DueWeek: 'Échéance sous 7 jours',
    FilterBar_SearchPlaceholder: 'Rechercher des tâches…',
    FilterBar_SearchAriaLabel: 'Rechercher des tâches',
    FilterBar_StatusChipLabel: 'Statut',
    FilterBar_PriorityChipLabel: 'Priorité',
    FilterBar_AssigneeChipLabel: 'Assigné à',
    FilterBar_PhaseChipLabel: 'Phase',
    FilterBar_DueDateAriaLabel: 'Filtrer par date d\'échéance',
    FilterBar_MatchCount: '{matchCount} sur {totalCount}',
    FilterBar_ClearFilters: '✕ Effacer les filtres',
    FilterBar_ChipLabelWithCount: '{label} ({count}) ▾',
    FilterBar_ChipLabelNoCount: '{label} ▾',

    // ── Gantt view ──
    Gantt_TaskColumnHeader: 'Tâche',
    Gantt_DurationColumnHeader: 'Durée',
    Gantt_AddTaskButton: '+ Ajouter une tâche',
    Gantt_EmptyTitle: 'Aucune tâche pour le moment',
    Gantt_EmptySubtitle: 'Ajoutez des tâches pour les voir dans le diagramme de Gantt.',
    Gantt_AddFirstTask: '+ Ajouter la première tâche',
    Gantt_ImportTasksButton: '📥 Importer des tâches',
    Gantt_EditTitle: 'Modifier',
    Gantt_DeleteTitle: 'Supprimer',
    Gantt_EditTaskAriaLabel: 'Modifier la tâche {taskTitle}',
    Gantt_DeleteTaskAriaLabel: 'Supprimer la tâche {taskTitle}',
    Gantt_ExpandPhaseAriaLabel: '{action} la phase {phase}',
    Gantt_ExpandAction: 'Développer',
    Gantt_CollapseAction: 'Réduire',
    Gantt_DependencyViolationTooltip: 'Commencée avant l\'achèvement de toutes les dépendances',
    Gantt_MilestoneAriaLabel: '{taskTitle}, jalon, {date}',
    Gantt_BarAriaLabel: '{taskTitle}, du {startDate} au {dueDate}, {percent} % terminé',
    Gantt_PercentCompleteTooltip: '{value} % terminé',

    // ── Gantt options/settings panel ──
    GanttSettings_PanelHeader: '⚙ Options',
    GanttSettings_ColorCodingSection: 'Code couleur',
    GanttSettings_ByStatus: 'Par statut',
    GanttSettings_ByPriority: 'Par priorité',
    GanttSettings_ByPhase: 'Par phase',
    GanttSettings_ByHealth: 'Par état de santé',
    GanttSettings_HeaderColorSection: 'Couleur de l\'en-tête',
    GanttSettings_ThemeDark: 'Sombre',
    GanttSettings_ThemeNavy: 'Marine',
    GanttSettings_ThemeTeal: 'Sarcelle',
    GanttSettings_ThemePurple: 'Violet',
    GanttSettings_ThemeLight: 'Clair',
    GanttSettings_HeaderLabelsSection: 'Étiquettes d\'en-tête',
    GanttSettings_WeekLabelDates: 'Dates',
    GanttSettings_WeekLabelDatesDesc: '3 juin, 10 juin…',
    GanttSettings_WeekLabelProject: 'Semaines du projet',
    GanttSettings_WeekLabelProjectDesc: 'S1, S2…',
    GanttSettings_WeekLabelIso: 'Semaines calendaires',
    GanttSettings_WeekLabelIsoDesc: 'S23, S24…',
    GanttSettings_ProjectWeeksHint: 'La semaine 1 commence le lundi de votre première tâche — idéal pour les présentations.',
    GanttSettings_BarStyleSection: 'Style des barres',
    GanttSettings_BarStyleGradient: 'Dégradé',
    GanttSettings_BarStyleFlat: 'Uni',
    GanttSettings_RowHeightSection: 'Hauteur des lignes',
    GanttSettings_HeightCompact: 'Compacte',
    GanttSettings_HeightNormal: 'Normale',
    GanttSettings_HeightSpacious: 'Spacieuse',
    GanttSettings_ShowHideSection: 'Afficher / Masquer',
    GanttSettings_WeekendShading: 'Ombrage des week-ends',
    GanttSettings_DependencyArrows: 'Flèches de dépendance',
    GanttSettings_CriticalPathAlwaysVisible: 'Chemin critique toujours visible',
    GanttSettings_AllOthersOnHoverOnly: 'Autres au survol uniquement',
    GanttSettings_CriticalPathHighlight: 'Surbrillance du chemin critique',
    GanttSettings_ProgressPercentOnBars: '% de progression sur les barres',
    GanttSettings_AssigneeNameOnBars: 'Nom de l\'assigné sur les barres',
    GanttSettings_HealthStatusBadges: 'Badges d\'état de santé',

    // ── List view ──
    ListView_ColTaskName: 'Nom de la tâche',
    ListView_ColStatus: 'Statut',
    ListView_ColHealth: 'État de santé',
    ListView_ColPriority: 'Priorité',
    ListView_ColStart: 'Début',
    ListView_ColDue: 'Échéance',
    ListView_ColAssignedTo: 'Assigné à',
    ListView_ColProgress: 'Progression',
    ListView_ColPhase: 'Phase',
    ListView_ColPredecessors: 'Prédécesseurs',
    ListView_EmptyTitle: 'Aucune tâche pour le moment',
    ListView_AddFirstTask: '+ Ajouter la première tâche',
    ListView_AddTaskRow: '+ Ajouter une tâche',
    ListView_Unassigned: 'Non assigné',
    ListView_DependencyViolationTooltip: 'Commencée avant l\'achèvement de toutes les dépendances',
    ListView_StatusAriaLabel: 'Statut de {taskTitle}',
    ListView_PriorityAriaLabel: 'Priorité de {taskTitle}',
    ListView_EditTaskAriaLabel: 'Modifier la tâche {taskTitle}',
    ListView_DeleteTaskAriaLabel: 'Supprimer la tâche {taskTitle}',
    ListView_EditTitle: 'Modifier',
    ListView_DeleteTitle: 'Supprimer',

    // ── Kanban view ──
    Kanban_ColumnNotStarted: 'Non commencée',
    Kanban_ColumnInProgress: 'En cours',
    Kanban_ColumnOnHold: 'En attente',
    Kanban_ColumnCompleted: 'Terminée',
    Kanban_ColumnCancelled: 'Annulée',
    Kanban_AddTaskButton: '+ Ajouter une tâche',
    Kanban_EditTitle: 'Modifier',
    Kanban_DeleteTitle: 'Supprimer',
    Kanban_CardAriaLabel: '{taskTitle}, {status}. Appuyez sur Entrée pour modifier, flèche gauche ou droite pour changer le statut.',
    Kanban_EditTaskAriaLabel: 'Modifier la tâche {taskTitle}',
    Kanban_DeleteTaskAriaLabel: 'Supprimer la tâche {taskTitle}',

    // ── Dashboard view ──
    Dashboard_TotalTasks: 'Total des tâches',
    Dashboard_Completed: 'Terminées',
    Dashboard_InProgress: 'En cours',
    Dashboard_OnHold: 'En attente',
    Dashboard_NotStarted: 'Non commencées',
    Dashboard_Cancelled: 'Annulées',
    Dashboard_OverallProgress: 'Progression globale',
    Dashboard_ProjectManagerLabel: 'Chef de projet : {name}',
    Dashboard_PhaseProgressHeader: 'Progression par phase',
    Dashboard_StatusBreakdownHeader: 'Répartition par statut',
    Dashboard_PriorityBreakdownHeader: 'Répartition par priorité',
    Dashboard_PriorityCritical: 'Critique',
    Dashboard_PriorityHigh: 'Élevée',
    Dashboard_PriorityMedium: 'Moyenne',
    Dashboard_PriorityLow: 'Faible',
    Dashboard_OverdueHeader: 'En retard  ({count})',
    Dashboard_DueNext14DaysHeader: 'Échéance sous 14 jours  ({count})',
    Dashboard_CompletedThisWeekHeader: 'Terminées cette semaine',
    Dashboard_UpdatedThisWeekHeader: 'Mises à jour cette semaine',
    Dashboard_Today: 'Aujourd\'hui',
    Dashboard_Tomorrow: 'Demain',
    Dashboard_DaysLeft: '{days} j',
    Dashboard_EmptyTitle: 'Aucune tâche pour le moment',
    Dashboard_EmptySubtitle: 'Ajoutez des tâches pour voir le tableau de bord de votre projet.',
    Dashboard_AddTaskButton: '+ Ajouter une tâche',

    // ── Portfolio view ──
    Portfolio_ProjectCount: '{count} projet{plural}',
    Portfolio_OnTrackSummary: '{count} sur la bonne voie',
    Portfolio_AtRiskSummary: '{count} à risque',
    Portfolio_OverdueSummary: '{count} en retard',
    Portfolio_DoneSummary: '{count} terminés',
    Portfolio_SortLabel: 'Trier :',
    Portfolio_SortAZ: 'A-Z',
    Portfolio_SortHealth: 'État de santé',
    Portfolio_SortStatus: 'Statut',
    Portfolio_SortCompletion: 'Achèvement',
    Portfolio_RefreshTitle: 'Actualiser',
    Portfolio_RefreshButton: 'Actualiser',
    Portfolio_LoadingStats: 'Chargement des statistiques…',
    Portfolio_EmptyTitle: 'Aucun projet pour le moment',
    Portfolio_CreateFirstProject: '+ Créer le premier projet',
    Portfolio_StatsUnavailable: 'Statistiques indisponibles',
    Portfolio_StatsUnavailableDetail: 'Impossible de charger les statistiques de ce projet.',
    Portfolio_OverallProgressLabel: 'Progression globale',
    Portfolio_TaskCountDone: 'Terminées',
    Portfolio_TaskCountActive: 'Actives',
    Portfolio_TaskCountAtRisk: 'À risque',
    Portfolio_TaskCountOverdue: 'En retard',
    Portfolio_ViewGanttLink: 'Voir le Gantt →',
    Portfolio_TodayTooltip: 'Aujourd\'hui',

    // ── Task panel ──
    TaskPanel_EditHeader: 'Modifier : {taskTitle}',
    TaskPanel_NewTaskHeader: 'Nouvelle tâche',
    TaskPanel_TabBasic: 'De base',
    TaskPanel_TabDetails: 'Détails',
    TaskPanel_TabLinks: 'Liens',
    TaskPanel_ProjectLabelPrefix: 'Projet : ',
    TaskPanel_TaskNameLabel: 'Nom de la tâche',
    TaskPanel_TaskNamePlaceholder: 'Saisissez le nom de la tâche',
    TaskPanel_TaskNameRequired: 'Le nom de la tâche est requis',
    TaskPanel_DescriptionLabel: 'Description',
    TaskPanel_DescriptionPlaceholder: 'Saisissez une description',
    TaskPanel_StartDateLabel: 'Date de début',
    TaskPanel_DueDateLabel: 'Date d\'échéance',
    TaskPanel_DueDateError: 'La date d\'échéance doit être postérieure ou égale à la date de début',
    TaskPanel_StatusLabel: 'Statut',
    TaskPanel_PriorityLabel: 'Priorité',
    TaskPanel_PercentCompleteLabel: '% terminé : {percent} %',
    TaskPanel_AssignedToLabel: 'Assigné à',
    TaskPanel_AssignedToPlaceholder: 'Rechercher des personnes…',
    TaskPanel_PhaseLabel: 'Phase',
    TaskPanel_PhasePlaceholder: 'Saisissez le nom de la phase',
    TaskPanel_PhaseHint: 'Regroupe les tâches dans les vues Gantt et Liste.',
    TaskPanel_MilestoneLabel: 'Jalon',
    TaskPanel_MilestoneOnText: 'Oui',
    TaskPanel_MilestoneOffText: 'Non',
    TaskPanel_CustomBarColorLabel: 'Couleur de barre personnalisée',
    TaskPanel_CustomBarColorOptionalSuffix: ' (facultatif)',
    TaskPanel_AutoColorHint: 'Couleur automatique selon les paramètres de statut/priorité/phase.',
    TaskPanel_NotesLabel: 'Notes',
    TaskPanel_NotesPlaceholder: 'Saisissez des notes',
    TaskPanel_ParentTaskLabel: 'Tâche parente',
    TaskPanel_ParentTaskNone: '(aucune)',
    TaskPanel_ParentTaskHasChildrenHint: 'Cette tâche possède des sous-tâches et ne peut pas avoir de parent.',
    TaskPanel_ParentTaskHint: 'Imbriquer cette tâche sous une autre en tant que sous-tâche.',
    TaskPanel_DependsOnLabel: 'Dépend de',
    TaskPanel_RemoveDependencyTitle: 'Supprimer la dépendance sur « {taskTitle} »',
    TaskPanel_AddDependencyPlaceholder: 'Ajouter une dépendance…',
    TaskPanel_SelectATaskOption: 'Sélectionner une tâche…',
    TaskPanel_DependsOnHint: 'La tâche ne peut pas commencer tant que celles-ci ne sont pas terminées.',
    TaskPanel_SavingLabel: 'Enregistrement…',
    TaskPanel_CreatingLabel: 'Création…',
    TaskPanel_SaveChangesButton: 'Enregistrer les modifications',
    TaskPanel_CreateTaskButton: 'Créer la tâche',
    TaskPanel_CancelButton: 'Annuler',
    TaskPanel_DismissAriaLabel: 'Fermer',
    TaskPanel_DiscardUnsavedChangesConfirm: 'Abandonner les modifications non enregistrées ?',
    TaskPanel_SaveFallbackError: 'Impossible d\'enregistrer la tâche.',

    // ── Project panel ──
    ProjectPanel_EditHeader: 'Modifier le projet',
    ProjectPanel_NewHeader: 'Nouveau projet',
    ProjectPanel_ProjectNameLabel: 'Nom du projet',
    ProjectPanel_ProjectNamePlaceholder: 'Saisissez le nom du projet',
    ProjectPanel_ProjectNameRequired: 'Le nom du projet est requis',
    ProjectPanel_DescriptionLabel: 'Description',
    ProjectPanel_DescriptionPlaceholder: 'Saisissez une description',
    ProjectPanel_ProjectColorLabel: 'Couleur du projet',
    ProjectPanel_StatusLabel: 'Statut',
    ProjectPanel_StartDateLabel: 'Date de début',
    ProjectPanel_DueDateLabel: 'Date d\'échéance',
    ProjectPanel_DueDateError: 'La date d\'échéance doit être postérieure ou égale à la date de début',
    ProjectPanel_WhatHappensNextTitle: 'Que se passe-t-il ensuite ?',
    ProjectPanel_WhatHappensNextBody: 'Vous pourrez ajouter des tâches, définir des phases et suivre la progression une fois le projet créé.',
    ProjectPanel_SavingLabel: 'Enregistrement…',
    ProjectPanel_CreatingLabel: 'Création…',
    ProjectPanel_SaveChangesButton: 'Enregistrer les modifications',
    ProjectPanel_CreateProjectButton: 'Créer le projet',
    ProjectPanel_CancelButton: 'Annuler',
    ProjectPanel_DismissAriaLabel: 'Fermer',
    ProjectPanel_DiscardUnsavedChangesConfirm: 'Abandonner les modifications non enregistrées ?',
    ProjectPanel_SaveFallbackError: 'Impossible d\'enregistrer le projet.',

    // ── Import panel ──
    ImportPanel_SourceExcelTitle: 'Fichier Excel / CSV',
    ImportPanel_SourceExcelSubtitle: 'Importer des tâches depuis un tableur',
    ImportPanel_SourcePlannerTitle: 'Microsoft Planner',
    ImportPanel_SourcePlannerSubtitle: 'Importer des tâches depuis un plan Planner',
    ImportPanel_ClickToBrowse: 'Cliquez pour parcourir',
    ImportPanel_DragDropSuffix: ' ou glissez-déposez',
    ImportPanel_SupportedExtensions: 'Prend en charge .xlsx, .xls, .csv',
    ImportPanel_RowsColsSummary: '{rows} lignes, {cols} colonnes détectées',
    ImportPanel_LoadingPlannerPlans: 'Chargement des plans Planner…',
    ImportPanel_PlannerLoadError: 'Impossible de charger les plans Planner.',
    ImportPanel_PlannerPermissionsHintPrefix: 'Assurez-vous d\'avoir accès à Planner et que ',
    ImportPanel_PlannerPermissionsHintEmphasis: 'Tâches par Planner et To Do',
    ImportPanel_PlannerPermissionsHintSuffix: ' est disponible sur ce site.',
    ImportPanel_NoPlannerPlansFoundTitle: 'Aucun plan Planner trouvé',
    ImportPanel_NoPlannerPlansFoundBody: 'Vous n\'avez peut-être pas accès à des plans Planner, ou aucun n\'existe pour ce compte.',
    ImportPanel_TaskCountFoundIn: '{count} tâches trouvées dans « {planName} »',
    ImportPanel_ProjectDetailsIntroPrefix: 'Importation dans ',
    ImportPanel_ProjectDetailsIntroSuffix: '. Vérifiez les détails du projet ci-dessous.',
    ImportPanel_ProjectNameLabel: 'Nom du projet',
    ImportPanel_DescriptionLabel: 'Description',
    ImportPanel_StatusLabel: 'Statut',
    ImportPanel_ColorLabel: 'Couleur',
    ImportPanel_MapIntro: 'Associez les colonnes de votre fichier aux champs de tâche.',
    ImportPanel_CreatingProjectStatus: 'Création du projet…',
    ImportPanel_ImportingTasksStatus: 'Importation des tâches…',
    ImportPanel_ProgressLabel: '{done} sur {total}',
    ImportPanel_CouldNotCreateProject: 'Impossible de créer le projet.',
    ImportPanel_ImportCompletedWithErrors: 'Importation terminée avec {count} erreur(s).',
    ImportPanel_ProjectCreatedSuccess: 'Projet créé avec succès !',
    ImportPanel_ImportSuccessful: 'Importation réussie !',
    ImportPanel_TasksAddedTo: '{count} tâches ajoutées à « {projectName} »',
    ImportPanel_FailedRowsLabel: 'Lignes en échec :',
    ImportPanel_CloseButton: 'Fermer',
    ImportPanel_OpenProjectButton: 'Ouvrir le projet',
    ImportPanel_ViewImportedTasksButton: 'Voir les tâches importées',
    ImportPanel_NextMapColumnsButton: 'Suivant : Mapper les colonnes',
    ImportPanel_ImportNTasksButton: 'Importer {count} tâches',
    ImportPanel_BackButton: 'Retour',
    ImportPanel_CancelButton: 'Annuler',
    ImportPanel_NextButton: 'Suivant',
    ImportPanel_StepSource: 'Source',
    ImportPanel_StepProject: 'Projet',
    ImportPanel_StepMap: 'Mappage',
    ImportPanel_StepImport: 'Importation',
    ImportPanel_StepDone: 'Terminé',
    ImportPanel_ImportAsNewProjectHeader: 'Importer un fichier comme nouveau projet',
    ImportPanel_ImportIntoProjectHeader: 'Importer des tâches dans {projectName}',
    ImportPanel_CouldNotParseFile: 'Impossible d\'analyser le fichier.',
    ImportPanel_CouldNotLoadPlannerTasks: 'Impossible de charger les tâches de ce plan.',
    ImportPanel_CouldNotCreateProjectDetail: 'Impossible de créer le projet : {detail}',
    ImportPanel_CouldNotLinkDependencies: 'Impossible de lier les dépendances : {detail}',
    ImportPanel_UnknownError: 'erreur inconnue',

    // ── Column mapper (import) ──
    ColumnMapper_TaskNameRequiredBanner: 'Le nom de la tâche doit être mappé pour continuer.',
    ColumnMapper_SkippedColumnsBanner: '{count} colonne(s) seront ignorées.',
    ColumnMapper_SourceColumnHeader: 'Colonne source',
    ColumnMapper_TargetFieldHeader: 'Champ cible',
    ColumnMapper_StatusHeader: 'Statut',
    ColumnMapper_SkippedBadge: 'Ignorée',
    ColumnMapper_AutoMappedBadge: 'Mappée automatiquement',
    ColumnMapper_SetBadge: 'Définie',
    ColumnMapper_PreviewTitle: 'Aperçu : {columnName}',
    ColumnMapper_EmptyCellDash: '—',

    // ── Import field display names / ImportService ──
    ImportField_TaskName: 'Nom de la tâche',
    ImportField_StartDate: 'Date de début',
    ImportField_DueDate: 'Date d\'échéance',
    ImportField_Status: 'Statut',
    ImportField_Priority: 'Priorité',
    ImportField_AssignedTo: 'Assigné à',
    ImportField_AssignedToEmail: 'E-mail de l\'assigné',
    ImportField_PercentComplete: '% terminé',
    ImportField_Phase: 'Phase',
    ImportField_Description: 'Description',
    ImportField_Notes: 'Notes',
    ImportField_IsMilestone: 'Est un jalon',
    ImportField_Dependencies: 'Dépendances',
    ImportField_SkipColumn: '(Ignorer cette colonne)',
    ImportService_EmptyFileError: 'Le fichier semble vide ou ne contient aucune ligne de données.',
    ImportService_ReadErrorDetail: 'Impossible de lire le fichier : {detail}.',
    ImportService_FileReadError: 'Erreur de lecture du fichier.',
    ImportService_RowError: 'Ligne {rowNum} (« {title} ») : {error}',
    ImportService_AmbiguousDependency: 'La dépendance « {name} » correspond à plusieurs titres de tâche — ignorée.',
    ImportService_LinkDependencyError: 'Impossible de lier les dépendances pour la tâche {taskId} : {error}',

    // ── Health labels ──
    Health_Done: 'Terminé',
    Health_OnTrack: 'Sur la bonne voie',
    Health_AtRisk: 'À risque',
    Health_Overdue: 'En retard',

    // ── Status / Priority display labels ──
    Status_NotStarted: 'Non commencée',
    Status_InProgress: 'En cours',
    Status_Completed: 'Terminée',
    Status_OnHold: 'En attente',
    Status_Cancelled: 'Annulée',
    Priority_Critical: 'Critique',
    Priority_High: 'Élevée',
    Priority_Medium: 'Moyenne',
    Priority_Low: 'Faible',
    ProjectStatus_Planning: 'Planification',
    ProjectStatus_Active: 'Actif',
    ProjectStatus_OnHold: 'En attente',
    ProjectStatus_Completed: 'Terminé',
    ProjectStatus_Cancelled: 'Annulé',

    // ── Shell (SmartGantt.tsx) ──
    SmartGantt_LoadingProjects: 'Chargement des projets…',
    SmartGantt_UnableToLoad: 'Impossible de charger',
    SmartGantt_RetryButton: 'Réessayer',
    SmartGantt_NoProjectsYet: 'Aucun projet pour le moment',
    SmartGantt_NoProjectsSubtitle: 'Créez votre premier projet pour commencer.',
    SmartGantt_CreateFirstProjectButton: '+ Créer le premier projet',
    SmartGantt_ImportFromExcelButton: '📥 Importer depuis Excel',
    SmartGantt_LoadingTasks: 'Chargement des tâches…',
    SmartGantt_DismissAriaLabel: 'Fermer',
    SmartGantt_DeleteTaskDialogTitle: 'Supprimer la tâche',
    SmartGantt_DeleteTaskDialogSubtext: 'Voulez-vous vraiment supprimer « {taskTitle} » ? Cette action est irréversible.',
    SmartGantt_DeleteButton: 'Supprimer',
    SmartGantt_CancelButton: 'Annuler',
    SmartGantt_ArchiveProjectDialogTitle: 'Archiver le projet',
    SmartGantt_ArchiveProjectDialogSubtext: 'Archiver « {projectTitle} » ? Vous pourrez le désarchiver plus tard.',
    SmartGantt_ArchiveButton: 'Archiver',
    SmartGantt_SendToRecycleBinDialogTitle: 'Envoyer à la corbeille',
    SmartGantt_SendToRecycleBinDialogSubtext: 'Envoyer « {projectTitle} » à la corbeille du site ?',
    SmartGantt_SendToRecycleBinButton: 'Envoyer à la corbeille',
    SmartGantt_FailedLoadProjects: 'Échec du chargement des projets. Vérifiez les autorisations du site.',
    SmartGantt_FailedLoadTasks: 'Échec du chargement des tâches pour ce projet.',
    SmartGantt_FailedLoadPortfolioStats: 'Échec du chargement des statistiques du portefeuille.',
    SmartGantt_CouldNotSaveProject: 'Impossible d\'enregistrer le projet : {message}',
    SmartGantt_CouldNotDeleteProject: 'Impossible de supprimer le projet : {message}',
    SmartGantt_CouldNotArchiveProject: 'Impossible d\'archiver le projet : {message}',
    SmartGantt_CouldNotUnarchiveProject: 'Impossible de désarchiver le projet : {message}',
    SmartGantt_CouldNotSaveTask: 'Impossible d\'enregistrer la tâche : {message}',
    SmartGantt_CouldNotDeleteTask: 'Impossible de supprimer la tâche : {message}',
    SmartGantt_ImageExportFailed: 'Échec de l\'exportation de l\'image : {message}',
    SmartGantt_PowerPointExportFailed: 'Échec de l\'exportation PowerPoint : {message}',
    SmartGantt_PortfolioExportFailed: 'Échec de l\'exportation du portefeuille : {message}',
    SmartGantt_CouldNotUpdateTask: 'Impossible de mettre à jour la tâche : {message}',

    // ── Common ──
    ColorSwatch_AutoColorAriaLabel: 'Couleur automatique',
    ColorSwatch_CustomColorAriaLabel: 'Couleur personnalisée',
    ColorSwatch_PickCustomColorTitle: 'Choisir une couleur personnalisée',

    // ── Export (Excel / PowerPoint) ──
    Export_ColTaskName: 'Nom de la tâche',
    Export_ColPhase: 'Phase',
    Export_ColStartDate: 'Date de début',
    Export_ColDueDate: 'Date d\'échéance',
    Export_ColStatus: 'Statut',
    Export_ColPriority: 'Priorité',
    Export_ColAssignedTo: 'Assigné à',
    Export_ColAssignedToEmail: 'E-mail de l\'assigné',
    Export_ColPercentComplete: '% terminé',
    Export_ColIsMilestone: 'Est un jalon',
    Export_ColDescription: 'Description',
    Export_ColNotes: 'Notes',
    Export_Yes: 'Oui',
    Export_No: 'Non',
    Export_SheetNameTasks: 'Tâches',
    Export_ExcelFileSuffix: ' - Tâches.xlsx',
    Export_TaskNameColumnLabel: 'NOM DE LA TÂCHE',
    Export_ExportedDateLabel: 'Exporté le {date}',
    Export_ProjectReportLabel: 'RAPPORT DE PROJET',
    Export_StatusLine: 'Statut : {status}',
    Export_DateRangeSeparator: ' au ',
    Export_ProjectManagerLine: 'Chef de projet : {name}',
    Export_GeneratedDateLine: 'Généré le {date}',
    Export_ProjectSummaryTitle: 'Résumé du projet',
    Export_StatTotalTasks: 'Total des tâches',
    Export_StatCompleted: 'Terminées',
    Export_StatInProgress: 'En cours',
    Export_StatOnHold: 'En attente',
    Export_StatNotStarted: 'Non commencées',
    Export_OverallProgressLine: 'Progression globale',
    Export_OverallProgressPercent: '{percent} %',
    Export_StatusBreakdownTitle: 'Répartition par statut',
    Export_StatusBreakdownRow: '{status} : {count} ({percent} %)',
    Export_GanttTimelineTitle: 'Chronologie Gantt',
    Export_SummaryRecentActivityTitle: 'Activité récente',
    Export_ProjectOverviewLabel: 'Aperçu du projet',
    Export_DetailStatusLabel: 'Statut',
    Export_DetailStartDateLabel: 'Date de début',
    Export_DetailDueDateLabel: 'Date d\'échéance',
    Export_DetailProjectManagerLabel: 'Chef de projet',
    Export_Past7DaysLabel: '7 derniers jours',
    Export_NoActivityMessage: 'Aucune activité récente.',
    Export_CompletedThisWeekHeader: 'Terminées cette semaine ({count})',
    Export_NewBadge: 'NOUVEAU  ',
    Export_CompletedPercentLine: '{percent} % terminé',
    Export_MoreItemsSuffix: '+ {count} de plus',
    Export_InProgressUpdatedHeader: 'En cours / Mises à jour',
    Export_StatusPercentLine: '{status} — {percent} %',
    Export_PortfolioReportLabel: 'RAPPORT DE PORTEFEUILLE',
    Export_PortfolioOverviewTitle: 'Aperçu du portefeuille',
    Export_ProjectsCountLine: '{count} projets',
    Export_HealthSummaryOnTrack: '{count} sur la bonne voie',
    Export_HealthSummaryAtRisk: '{count} à risque',
    Export_HealthSummaryOverdue: '{count} en retard',
    Export_ProjectsSummaryHeader: 'Résumé des projets',
    Export_TableProject: 'Projet',
    Export_TableStatus: 'Statut',
    Export_TableHealth: 'État de santé',
    Export_TableTotal: 'Total',
    Export_TableDone: 'Terminées',
    Export_TableActive: 'Actives',
    Export_TableAtRisk: 'À risque',
    Export_TableOverdue: 'En retard',
    Export_TablePctDone: '% Terminé',
    Export_TableDueDate: 'Date d\'échéance',
    Export_PortfolioSummaryFileName: 'Résumé du portefeuille.xlsx',
    Export_PortfolioReportFileName: 'Rapport de portefeuille.pptx',
    Export_ProjectReportFileName: 'Rapport {projectName}.pptx',
    Export_UnavailableLabel: 'Indisponible',
    Export_SheetNamePortfolio: 'Portefeuille',
    Export_ColStart: 'Début',
    Export_ColDue: 'Échéance',
    Export_ImageGenerationFailed: 'Impossible de générer l\'image — le diagramme est peut-être trop grand pour être exporté sous forme d\'image.',
    Export_DrawingContextFailed: 'Impossible de créer un contexte de dessin pour l\'exportation.',
    Export_SvgRenderFailed: 'Échec du rendu SVG',

    // ── Added in v1.5 review ──
    Svc_TooManyDependencies: 'Cette tâche a trop de dépendances pour être enregistrée (la limite est d\'environ 60). Supprimez-en quelques-unes et réessayez.',
    Svc_TaskChangedByOthers: 'Cette tâche a été modifiée par quelqu\'un d\'autre depuis son chargement. Actualisez et réessayez.',
    Svc_ProjectChangedByOthers: 'Ce projet a été modifié par quelqu\'un d\'autre depuis son ouverture. Actualisez et réessayez.',
    Svc_ColumnCreateFailed: 'Impossible de créer {count} colonne(s) dans la nouvelle liste de tâches : {detail}',
    Svc_BaselineUnavailable: 'Les références ne sont pas disponibles pour ce projet, car les colonnes de référence n\'ont pas pu être ajoutées (vous avez peut-être besoin de l\'autorisation de modifier la liste).',
    Svc_SubtaskReassignFailed: 'Impossible de réaffecter les sous-tâches de cette tâche avant sa suppression : {detail}',
    Svc_UnresolvedDependency: 'Ligne {row} (« {title} ») : la dépendance « {name} » n\'a pas pu être associée à une tâche importée.',
    Svc_SelfDependency: 'Ligne {row} (« {title} ») : la dépendance « {name} » pointe vers la tâche elle-même et a été ignorée.',
    Svc_ColId: 'ID',
    Svc_ColDependencies: 'Dépendances',
    Svc_ColBaselineStart: 'Début de référence',
    Svc_ColBaselineDue: 'Échéance de référence',
    Svc_CsvFileSuffix: ' - Tasks.csv',
    Svc_IcsFileSuffix: ' - Milestones.ics',
    Svc_PortfolioCsvFileName: 'Portfolio Summary.csv',
    Svc_PP_DisplayGroup: 'Valeurs par défaut',
    Svc_PP_DefaultView: 'Vue par défaut',
    Svc_PP_ViewGantt: 'Gantt',
    Svc_PP_ViewList: 'Liste',
    Svc_PP_ViewKanban: 'Kanban',
    Svc_PP_ViewDashboard: 'Tableau de bord',
    Svc_PP_ViewPortfolio: 'Portefeuille',
    Svc_PP_DefaultZoom: 'Zoom par défaut',
    Svc_PP_ZoomDay: 'Jour',
    Svc_PP_ZoomWeek: 'Semaine',
    Svc_PP_ZoomMonth: 'Mois',
    Svc_PP_ZoomQuarter: 'Trimestre',
    Svc_PP_CalendarGroup: 'Calendrier de travail',
    Svc_PP_DaySun: 'Le dimanche est un jour ouvré',
    Svc_PP_DayMon: 'Le lundi est un jour ouvré',
    Svc_PP_DayTue: 'Le mardi est un jour ouvré',
    Svc_PP_DayWed: 'Le mercredi est un jour ouvré',
    Svc_PP_DayThu: 'Le jeudi est un jour ouvré',
    Svc_PP_DayFri: 'Le vendredi est un jour ouvré',
    Svc_PP_DaySat: 'Le samedi est un jour ouvré',
    Svc_PP_Holidays: 'Jours fériés (dates non travaillées)',
    Svc_PP_HolidaysHint: 'Une date par ligne, au format aaaa-MM-jj (par exemple 2026-12-25).',
    Gantt_TimelineAriaLabel: 'Chronologie des tâches',
    Gantt_DragLabel: '{start} → {end} ({days} j)',
    Gantt_KeyboardMoveAnnouncement: '{taskTitle} : du {startDate} au {dueDate}',
    Gantt_KeyboardHint: 'Appuyez sur Entrée pour ouvrir la tâche. Les flèches gauche et droite la déplacent d\'un jour ouvré. Maj avec les flèches modifie sa date de fin.',
    Gantt_ParentCycleTooltip: 'Cette tâche fait partie d\'une chaîne circulaire de tâche parente et de sous-tâches ; elle est donc affichée au niveau supérieur',
    Gantt_CollapseAll: 'Réduire toutes les phases',
    Gantt_ExpandAll: 'Développer toutes les phases',
    Gantt_BaselineTooltip: 'Référence : {start} → {due}',
    Gantt_VarianceTooltip: 'Écart de fin : {days} jours par rapport à la référence',
    Gantt_LinkHandleTitle: 'Faites glisser vers une autre tâche pour créer une dépendance',
    Toolbar_FitToProject: 'Ajuster',
    Toolbar_FitToProjectTitle: 'Ajuster le zoom à l\'ensemble du projet',
    Toolbar_UndoTitle: 'Annuler (Ctrl+Z)',
    Toolbar_RedoTitle: 'Rétablir (Ctrl+Y)',
    Toolbar_ExportCsv: '📄 Exporter les tâches en CSV',
    Toolbar_ExportIcs: '📅 Exporter les jalons (iCal)',
    Toolbar_Print: '🖨 Imprimer / Enregistrer au format PDF',
    Toolbar_SetBaseline: '📐 Définir la référence…',
    Toolbar_CopyLink: '🔗 Copier le lien',
    Toolbar_CopyLinkTitle: 'Copier un lien vers cette vue (projet, vue, zoom et filtres)',
    App_UndoButton: 'Annuler',
    App_Undone: 'Modification annulée.',
    App_Redone: 'Modification rétablie.',
    App_DependentsMovedOne: '1 tâche dépendante a été déplacée.',
    App_DependentsMovedMany: '{count} tâches dépendantes ont été déplacées.',
    App_TaskConflict: 'Cette tâche a été modifiée par quelqu\'un d\'autre. Les dernières tâches ont été rechargées ; vérifiez-les et réessayez.',
    App_DependencyCycle: 'Ce lien créerait une dépendance circulaire.',
    App_DependencyExists: 'Ces tâches sont déjà liées.',
    App_LinkCopied: 'Lien copié dans le presse-papiers.',
    App_LinkCopyFailed: 'Impossible de copier le lien : {message}',
    App_PopupBlocked: 'La fenêtre d\'impression a été bloquée. Autorisez les fenêtres contextuelles pour ce site et réessayez.',
    App_SetBaselineDialogTitle: 'Définir la référence',
    App_SetBaselineDialogSubtext: 'Enregistrer les dates de début et d\'échéance actuelles des {count} tâches comme référence ? Toute référence existante sera remplacée.',
    App_SetBaselineButton: 'Définir la référence',
    App_BaselineSaved: 'Référence enregistrée.',
    App_BaselineFailed: 'Impossible d\'enregistrer la référence : {message}',
    App_CsvExportFailed: 'Échec de l\'exportation CSV : {message}',
    App_IcsExportFailed: 'Échec de l\'exportation du calendrier : {message}',
    App_BulkDeleteDialogTitle: 'Supprimer les tâches',
    App_BulkDeleteDialogSubtext: 'Voulez-vous vraiment supprimer {count} tâches ? Cette action est irréversible.',
    Common_PeoplePicker_ClearAriaLabel: 'Effacer',
    Common_PeoplePicker_DirectoryHeader: 'Personnes de l\'annuaire',
    Common_PeoplePicker_EmailLabel: 'E-mail (facultatif)',
    Common_PeoplePicker_EmailPlaceholder: 'name@company.com',
    Common_PeoplePicker_ExternalHint: 'Absent de l\'annuaire. Enregistré en texte libre.',
    Common_PeoplePicker_InvalidEmail: 'Saisissez une adresse e-mail valide.',
    Common_PeoplePicker_ListAriaLabel: 'Suggestions de personnes',
    Common_PeoplePicker_RecentHeader: 'Utilisés récemment',
    Common_PeoplePicker_ResultsAnnouncement: '{count} suggestions disponibles',
    Common_PeoplePicker_Searching: 'Recherche en cours…',
    Common_PeoplePicker_UseExternal: 'Utiliser « {name} » (externe / absent de l\'annuaire)',
    Import_Mapper_PreviewFirstRows: 'Aperçu ({count} premières lignes)',
    Import_Mapper_RequiredLegend: 'Champ obligatoire',
    Import_Mapper_RequiredMarkerLabel: 'Obligatoire',
    Import_Mapper_SelectAriaLabel: 'Champ cible pour la colonne {columnName}',
    Import_Panel_DateOrderAuto: 'Détection automatique',
    Import_Panel_DateOrderDMY: 'Jour/Mois/Année (31/12/2026)',
    Import_Panel_DateOrderDetected: 'Détecté à partir de votre fichier : {order}.',
    Import_Panel_DateOrderHint: 'S\'applique aux dates écrites en chiffres, comme 03/04/2026.',
    Import_Panel_DateOrderLabel: 'Ordre des dates',
    Import_Panel_DateOrderMDY: 'Mois/Jour/Année (12/31/2026)',
    Import_Panel_DropZoneAriaLabel: 'Choisissez un fichier à importer. Appuyez sur Entrée pour parcourir.',
    Import_Panel_DropZoneChangeAriaLabel: 'Fichier sélectionné : {fileName}. Appuyez sur Entrée pour choisir un autre fichier.',
    Import_Panel_FailedCount: '{count} en échec',
    Import_Panel_NewProjectIntroMany: 'Un nouveau projet sera créé et les {count} tâches y seront importées. Vous pourrez modifier ces informations à tout moment après l\'importation.',
    Import_Panel_NewProjectIntroOne: 'Un nouveau projet sera créé et {count} tâche y sera importée. Vous pourrez modifier ces informations à tout moment après l\'importation.',
    Import_Panel_PlanAriaLabel: '{planName}, {groupName}',
    Import_Panel_ProblemEndBeforeStart: 'La date d\'échéance est antérieure à la date de début',
    Import_Panel_ProblemInvalidDueDate: 'La date d\'échéance « {value} » n\'est pas une date valide',
    Import_Panel_ProblemInvalidStartDate: 'La date de début « {value} » n\'est pas une date valide',
    Import_Panel_ProblemMissingTitle: 'Le nom de la tâche est manquant',
    Import_Panel_ProgressLabelWithPercent: '{done} sur {total} ({percent} %)',
    Import_Panel_SkipInvalidRows: 'Ignorer les lignes avec des problèmes',
    Import_Panel_SuccessWithWarningsMany: 'Importation réussie avec {count} avertissements.',
    Import_Panel_SuccessWithWarningsOne: 'Importation réussie avec {count} avertissement.',
    Import_Panel_ValidationHeader: 'Lignes avec des problèmes',
    Import_Panel_ValidationMore: '…et {count} de plus',
    Import_Panel_ValidationRow: 'Ligne {rowNum} : {problem}',
    Import_Panel_ValidationSummaryMany: '{count} lignes présentent des problèmes',
    Import_Panel_ValidationSummaryOne: '{count} ligne présente un problème',
    Import_Panel_WarningsLabel: 'Avertissements ({count}) :',
    Panel_Project_ManagerLabel: 'Chef de projet',
    Panel_Project_ManagerPlaceholder: 'Recherchez des personnes ou saisissez un nom…',
    Panel_Task_BaselineDueLabel: 'Fin de référence',
    Panel_Task_BaselineHeader: 'Référence',
    Panel_Task_BaselineStartLabel: 'Début de référence',
    Panel_Task_DepTypeFF: 'Fin à Fin (FF)',
    Panel_Task_DepTypeFS: 'Fin à Début (FS)',
    Panel_Task_DepTypeSF: 'Début à Fin (SF)',
    Panel_Task_DepTypeSS: 'Début à Début (SS)',
    Panel_Task_LagAriaLabel: 'Décalage en jours ouvrés pour {taskTitle}',
    Panel_Task_LagHint: 'Le décalage est exprimé en jours ouvrés. Utilisez un nombre négatif pour une avance.',
    Panel_Task_LinkTypeAriaLabel: 'Type de lien pour {taskTitle}',
    Panel_Task_VarianceEarlier: '{days} jour(s) ouvré(s) plus tôt',
    Panel_Task_VarianceLater: '{days} jour(s) ouvré(s) plus tard',
    Panel_Task_VarianceOnBaseline: 'conforme à la référence',
    View_Dashboard_BurndownActual: 'Réel',
    View_Dashboard_BurndownAria: 'Graphique d\'avancement : {remaining} tâches restantes sur {total}',
    View_Dashboard_BurndownHeader: 'Avancement (tâches restantes)',
    View_Dashboard_BurndownIdeal: 'Idéal',
    View_Dashboard_BurndownNoData: 'Pas assez de tâches datées pour tracer un graphique d\'avancement.',
    View_Dashboard_CriticalPathHeader: 'Chemin critique  ({count})',
    View_Dashboard_PhaseDoneSummary: '{done}/{total} terminées  •  {percent} %',
    View_Dashboard_TaskRowAriaLabel: 'Ouvrir la tâche {taskTitle}, {status}',
    View_Dashboard_WorkloadHeader: 'Charge de travail par responsable',
    View_Dashboard_WorkloadOpen: '{count} ouvertes',
    View_Dashboard_WorkloadOverdue: '{count} en retard',
    View_Kanban_AddTaskInColumnAriaLabel: 'Ajouter une tâche à {column}',
    View_Kanban_CollapseColumn: 'Réduire la colonne {column}',
    View_Kanban_ExpandColumn: 'Développer la colonne {column}',
    View_Kanban_LaneHeader: '{name} ({count})',
    View_Kanban_LaneNoPhase: 'Sans phase',
    View_Kanban_LaneUnassigned: 'Non affecté',
    View_Kanban_LanesAssignee: 'Responsable',
    View_Kanban_LanesNone: 'Aucun',
    View_Kanban_LanesPhase: 'Phase',
    View_Kanban_SwimlanesLabel: 'Couloirs',
    View_Kanban_WipEditTitle: 'Définir la limite de travail en cours pour {column} (0 pour aucune limite)',
    View_Kanban_WipExceededTitle: 'Limite WIP dépassée : {count} sur {limit}',
    View_Kanban_WipInputAriaLabel: 'Limite WIP pour {column}',
    View_Kanban_WipLabel: 'WIP {count}/{limit}',
    View_Kanban_WipSet: 'WIP',
    View_List_BulkAssignApply: 'Affecter',
    View_List_BulkAssigneePlaceholder: 'Affecter à…',
    View_List_BulkBarAriaLabel: 'Actions groupées pour les tâches sélectionnées',
    View_List_BulkClear: 'Effacer la sélection',
    View_List_BulkDelete: 'Supprimer la sélection',
    View_List_BulkPercentApply: 'Définir %',
    View_List_BulkPercentPlaceholder: '% d\'avancement',
    View_List_BulkPriorityPlaceholder: 'Définir la priorité…',
    View_List_BulkSelectedCount: '{count} sélectionnées',
    View_List_BulkStatusPlaceholder: 'Définir l\'état…',
    View_List_ExportCsv: 'Exporter en CSV',
    View_List_NonWorkingDay: 'Jour non ouvré',
    View_List_SelectAllAriaLabel: 'Sélectionner toutes les tâches',
    View_List_SelectRowAriaLabel: 'Sélectionner {taskTitle}',
    View_Portfolio_CardAriaLabel: 'Ouvrir le projet {projectName}, {status}',
    View_Portfolio_ClearFilters: 'Effacer les filtres',
    View_Portfolio_FilteredCount: '{shown} sur {total} projets',
    View_Portfolio_HideDone: 'Masquer les projets terminés / annulés',
    View_Portfolio_NoMatches: 'Aucun projet ne correspond à vos filtres.',
    View_Portfolio_ProjectCountMany: '{count} projets',
    View_Portfolio_ProjectCountOne: '{count} projet',
    View_Portfolio_SearchAriaLabel: 'Rechercher des projets',
    View_Portfolio_SearchPlaceholder: 'Rechercher des projets…',
    Import_Panel_CopyDetails: 'Copier les détails',
    Import_Panel_Copied: 'Copié',
  };
});
