define([], function () {
  return {
    // ── Property pane ──
    PropertyPane_HeaderDescription: 'Paramètres du diagramme de Gantt intelligent',
    PropertyPane_GeneralGroupName: 'Général',
    PropertyPane_TitleFieldLabel: 'Titre du composant WebPart',
    WebPart_DefaultTitle: 'Diagramme de Gantt intelligent',

    // ── Toolbar ──
    Toolbar_ViewDashboard: 'Tableau de bord',
    Toolbar_ViewList: 'Liste',
    Toolbar_ViewGantt: 'Gantt',
    Toolbar_ViewKanban: 'Kanban',
    Toolbar_ZoomDay: 'Jour',
    Toolbar_ZoomWeek: 'Semaine',
    Toolbar_ZoomMonth: 'Mois',
    Toolbar_ZoomQuarter: 'Trimestre',
    Toolbar_SelectProjectAriaLabel: 'Sélectionner un projet',
    Toolbar_PortfolioLabel: 'Portefeuille',
    Toolbar_SelectAProject: 'Sélectionner un projet',
    Toolbar_AllProjectsSubtext: 'Tous les projets',
    Toolbar_NoProjectsYet: 'Aucun projet pour le moment',
    Toolbar_ArchivedBadge: 'Archivé',
    Toolbar_ShowArchivedProjects: 'Afficher les projets archivés',
    Toolbar_NewProject: '+ Nouveau projet',
    Toolbar_ImportFileAsNewProject: '📥 Importer un fichier comme nouveau projet…',
    Toolbar_AddTask: '+ Ajouter une tâche',
    Toolbar_EditProject: 'Modifier le projet',
    Toolbar_OptionsButton: '⚙ Options',
    Toolbar_MoreOptionsTitle: 'Plus d\'options',
    Toolbar_ExportToExcel: '📊 Exporter vers Excel',
    Toolbar_ExportToPowerPoint: '📑 Exporter vers PowerPoint',
    Toolbar_ScrollToTodayTitle: 'Aller à aujourd\'hui',
    Toolbar_TodayButton: '◉ Aujourd\'hui',
    Toolbar_ImportTasks: '📥 Importer des tâches…',
    Toolbar_ExportAsImage: '🖼 Exporter en image (PNG)',
    Toolbar_UnarchiveProject: '📂 Désarchiver le projet',
    Toolbar_ArchiveProject: '🗄️ Archiver le projet',
    Toolbar_SendToRecycleBin: '🗑️ Envoyer à la corbeille',

    // ── Filter bar ──
    FilterBar_ClearOption: 'Effacer',
    FilterBar_DueAny: 'Toute échéance',
    FilterBar_DueOverdue: 'En retard',
    FilterBar_DueToday: 'Échéance aujourd\'hui',
    FilterBar_DueWeek: 'Échéance sous 7 jours',
    FilterBar_SearchPlaceholder: 'Rechercher des tâches…',
    FilterBar_SearchAriaLabel: 'Rechercher des tâches',
    FilterBar_StatusChipLabel: 'Statut',
    FilterBar_PriorityChipLabel: 'Priorité',
    FilterBar_AssigneeChipLabel: 'Assigné à',
    FilterBar_PhaseChipLabel: 'Phase',
    FilterBar_DueDateAriaLabel: 'Filtrer par date d\'échéance',
    FilterBar_MatchCount: '{matchCount} sur {totalCount}',
    FilterBar_ClearFilters: '✕ Effacer les filtres',
    FilterBar_ChipLabelWithCount: '{label} ({count}) ▾',
    FilterBar_ChipLabelNoCount: '{label} ▾',

    // ── Gantt view ──
    Gantt_TaskColumnHeader: 'Tâche',
    Gantt_DurationColumnHeader: 'Durée',
    Gantt_AddTaskButton: '+ Ajouter une tâche',
    Gantt_EmptyTitle: 'Aucune tâche pour le moment',
    Gantt_EmptySubtitle: 'Ajoutez des tâches pour les voir dans le diagramme de Gantt.',
    Gantt_AddFirstTask: '+ Ajouter la première tâche',
    Gantt_ImportTasksButton: '📥 Importer des tâches',
    Gantt_EditTitle: 'Modifier',
    Gantt_DeleteTitle: 'Supprimer',
    Gantt_EditTaskAriaLabel: 'Modifier la tâche {taskTitle}',
    Gantt_DeleteTaskAriaLabel: 'Supprimer la tâche {taskTitle}',
    Gantt_ExpandPhaseAriaLabel: '{action} la phase {phase}',
    Gantt_ExpandAction: 'Développer',
    Gantt_CollapseAction: 'Réduire',
    Gantt_DependencyViolationTooltip: 'Commencée avant l\'achèvement de toutes les dépendances',
    Gantt_MilestoneAriaLabel: '{taskTitle}, jalon, {date}',
    Gantt_BarAriaLabel: '{taskTitle}, du {startDate} au {dueDate}, {percent} % terminé',
    Gantt_PercentCompleteTooltip: '{value} % terminé',

    // ── Gantt options/settings panel ──
    GanttSettings_PanelHeader: '⚙ Options',
    GanttSettings_ColorCodingSection: 'Code couleur',
    GanttSettings_ByStatus: 'Par statut',
    GanttSettings_ByPriority: 'Par priorité',
    GanttSettings_ByPhase: 'Par phase',
    GanttSettings_ByHealth: 'Par état de santé',
    GanttSettings_HeaderColorSection: 'Couleur de l\'en-tête',
    GanttSettings_ThemeDark: 'Sombre',
    GanttSettings_ThemeNavy: 'Marine',
    GanttSettings_ThemeTeal: 'Sarcelle',
    GanttSettings_ThemePurple: 'Violet',
    GanttSettings_ThemeLight: 'Clair',
    GanttSettings_HeaderLabelsSection: 'Étiquettes d\'en-tête',
    GanttSettings_WeekLabelDates: 'Dates',
    GanttSettings_WeekLabelDatesDesc: '3 juin, 10 juin…',
    GanttSettings_WeekLabelProject: 'Semaines du projet',
    GanttSettings_WeekLabelProjectDesc: 'S1, S2…',
    GanttSettings_WeekLabelIso: 'Semaines calendaires',
    GanttSettings_WeekLabelIsoDesc: 'S23, S24…',
    GanttSettings_ProjectWeeksHint: 'La semaine 1 commence le lundi de votre première tâche — idéal pour les présentations.',
    GanttSettings_BarStyleSection: 'Style des barres',
    GanttSettings_BarStyleGradient: 'Dégradé',
    GanttSettings_BarStyleFlat: 'Uni',
    GanttSettings_RowHeightSection: 'Hauteur des lignes',
    GanttSettings_HeightCompact: 'Compacte',
    GanttSettings_HeightNormal: 'Normale',
    GanttSettings_HeightSpacious: 'Spacieuse',
    GanttSettings_ShowHideSection: 'Afficher / Masquer',
    GanttSettings_WeekendShading: 'Ombrage des week-ends',
    GanttSettings_DependencyArrows: 'Flèches de dépendance',
    GanttSettings_CriticalPathAlwaysVisible: 'Chemin critique toujours visible',
    GanttSettings_AllOthersOnHoverOnly: 'Autres au survol uniquement',
    GanttSettings_CriticalPathHighlight: 'Surbrillance du chemin critique',
    GanttSettings_ProgressPercentOnBars: '% de progression sur les barres',
    GanttSettings_AssigneeNameOnBars: 'Nom de l\'assigné sur les barres',
    GanttSettings_HealthStatusBadges: 'Badges d\'état de santé',

    // ── List view ──
    ListView_ColTaskName: 'Nom de la tâche',
    ListView_ColStatus: 'Statut',
    ListView_ColHealth: 'État de santé',
    ListView_ColPriority: 'Priorité',
    ListView_ColStart: 'Début',
    ListView_ColDue: 'Échéance',
    ListView_ColAssignedTo: 'Assigné à',
    ListView_ColProgress: 'Progression',
    ListView_ColPhase: 'Phase',
    ListView_ColPredecessors: 'Prédécesseurs',
    ListView_EmptyTitle: 'Aucune tâche pour le moment',
    ListView_AddFirstTask: '+ Ajouter la première tâche',
    ListView_AddTaskRow: '+ Ajouter une tâche',
    ListView_Unassigned: 'Non assigné',
    ListView_DependencyViolationTooltip: 'Commencée avant l\'achèvement de toutes les dépendances',
    ListView_StatusAriaLabel: 'Statut de {taskTitle}',
    ListView_PriorityAriaLabel: 'Priorité de {taskTitle}',
    ListView_EditTaskAriaLabel: 'Modifier la tâche {taskTitle}',
    ListView_DeleteTaskAriaLabel: 'Supprimer la tâche {taskTitle}',
    ListView_EditTitle: 'Modifier',
    ListView_DeleteTitle: 'Supprimer',

    // ── Kanban view ──
    Kanban_ColumnNotStarted: 'Non commencée',
    Kanban_ColumnInProgress: 'En cours',
    Kanban_ColumnOnHold: 'En attente',
    Kanban_ColumnCompleted: 'Terminée',
    Kanban_ColumnCancelled: 'Annulée',
    Kanban_AddTaskButton: '+ Ajouter une tâche',
    Kanban_EditTitle: 'Modifier',
    Kanban_DeleteTitle: 'Supprimer',
    Kanban_CardAriaLabel: '{taskTitle}, {status}. Appuyez sur Entrée pour modifier, flèche gauche ou droite pour changer le statut.',
    Kanban_EditTaskAriaLabel: 'Modifier la tâche {taskTitle}',
    Kanban_DeleteTaskAriaLabel: 'Supprimer la tâche {taskTitle}',

    // ── Dashboard view ──
    Dashboard_TotalTasks: 'Total des tâches',
    Dashboard_Completed: 'Terminées',
    Dashboard_InProgress: 'En cours',
    Dashboard_OnHold: 'En attente',
    Dashboard_NotStarted: 'Non commencées',
    Dashboard_Cancelled: 'Annulées',
    Dashboard_OverallProgress: 'Progression globale',
    Dashboard_ProjectManagerLabel: 'Chef de projet : {name}',
    Dashboard_PhaseProgressHeader: 'Progression par phase',
    Dashboard_StatusBreakdownHeader: 'Répartition par statut',
    Dashboard_PriorityBreakdownHeader: 'Répartition par priorité',
    Dashboard_PriorityCritical: 'Critique',
    Dashboard_PriorityHigh: 'Élevée',
    Dashboard_PriorityMedium: 'Moyenne',
    Dashboard_PriorityLow: 'Faible',
    Dashboard_OverdueHeader: 'En retard  ({count})',
    Dashboard_DueNext14DaysHeader: 'Échéance sous 14 jours  ({count})',
    Dashboard_CompletedThisWeekHeader: 'Terminées cette semaine',
    Dashboard_UpdatedThisWeekHeader: 'Mises à jour cette semaine',
    Dashboard_Today: 'Aujourd\'hui',
    Dashboard_Tomorrow: 'Demain',
    Dashboard_DaysLeft: '{days} j',
    Dashboard_EmptyTitle: 'Aucune tâche pour le moment',
    Dashboard_EmptySubtitle: 'Ajoutez des tâches pour voir le tableau de bord de votre projet.',
    Dashboard_AddTaskButton: '+ Ajouter une tâche',

    // ── Portfolio view ──
    Portfolio_ProjectCount: '{count} projet{plural}',
    Portfolio_OnTrackSummary: '{count} sur la bonne voie',
    Portfolio_AtRiskSummary: '{count} à risque',
    Portfolio_OverdueSummary: '{count} en retard',
    Portfolio_DoneSummary: '{count} terminés',
    Portfolio_SortLabel: 'Trier :',
    Portfolio_SortAZ: 'A-Z',
    Portfolio_SortHealth: 'État de santé',
    Portfolio_SortStatus: 'Statut',
    Portfolio_SortCompletion: 'Achèvement',
    Portfolio_RefreshTitle: 'Actualiser',
    Portfolio_RefreshButton: 'Actualiser',
    Portfolio_LoadingStats: 'Chargement des statistiques…',
    Portfolio_EmptyTitle: 'Aucun projet pour le moment',
    Portfolio_CreateFirstProject: '+ Créer le premier projet',
    Portfolio_StatsUnavailable: 'Statistiques indisponibles',
    Portfolio_StatsUnavailableDetail: 'Impossible de charger les statistiques de ce projet.',
    Portfolio_OverallProgressLabel: 'Progression globale',
    Portfolio_TaskCountDone: 'Terminées',
    Portfolio_TaskCountActive: 'Actives',
    Portfolio_TaskCountAtRisk: 'À risque',
    Portfolio_TaskCountOverdue: 'En retard',
    Portfolio_ViewGanttLink: 'Voir le Gantt →',
    Portfolio_TodayTooltip: 'Aujourd\'hui',

    // ── Task panel ──
    TaskPanel_EditHeader: 'Modifier : {taskTitle}',
    TaskPanel_NewTaskHeader: 'Nouvelle tâche',
    TaskPanel_TabBasic: 'De base',
    TaskPanel_TabDetails: 'Détails',
    TaskPanel_TabLinks: 'Liens',
    TaskPanel_ProjectLabelPrefix: 'Projet : ',
    TaskPanel_TaskNameLabel: 'Nom de la tâche',
    TaskPanel_TaskNamePlaceholder: 'Saisissez le nom de la tâche',
    TaskPanel_TaskNameRequired: 'Le nom de la tâche est requis',
    TaskPanel_DescriptionLabel: 'Description',
    TaskPanel_DescriptionPlaceholder: 'Saisissez une description',
    TaskPanel_StartDateLabel: 'Date de début',
    TaskPanel_DueDateLabel: 'Date d\'échéance',
    TaskPanel_DueDateError: 'La date d\'échéance doit être postérieure ou égale à la date de début',
    TaskPanel_StatusLabel: 'Statut',
    TaskPanel_PriorityLabel: 'Priorité',
    TaskPanel_PercentCompleteLabel: '% terminé : {percent} %',
    TaskPanel_AssignedToLabel: 'Assigné à',
    TaskPanel_AssignedToPlaceholder: 'Rechercher des personnes…',
    TaskPanel_PhaseLabel: 'Phase',
    TaskPanel_PhasePlaceholder: 'Saisissez le nom de la phase',
    TaskPanel_PhaseHint: 'Regroupe les tâches dans les vues Gantt et Liste.',
    TaskPanel_MilestoneLabel: 'Jalon',
    TaskPanel_MilestoneOnText: 'Oui',
    TaskPanel_MilestoneOffText: 'Non',
    TaskPanel_CustomBarColorLabel: 'Couleur de barre personnalisée',
    TaskPanel_CustomBarColorOptionalSuffix: ' (facultatif)',
    TaskPanel_AutoColorHint: 'Couleur automatique selon les paramètres de statut/priorité/phase.',
    TaskPanel_NotesLabel: 'Notes',
    TaskPanel_NotesPlaceholder: 'Saisissez des notes',
    TaskPanel_ParentTaskLabel: 'Tâche parente',
    TaskPanel_ParentTaskNone: '(aucune)',
    TaskPanel_ParentTaskHasChildrenHint: 'Cette tâche possède des sous-tâches et ne peut pas avoir de parent.',
    TaskPanel_ParentTaskHint: 'Imbriquer cette tâche sous une autre en tant que sous-tâche.',
    TaskPanel_DependsOnLabel: 'Dépend de',
    TaskPanel_RemoveDependencyTitle: 'Supprimer la dépendance sur « {taskTitle} »',
    TaskPanel_AddDependencyPlaceholder: 'Ajouter une dépendance…',
    TaskPanel_SelectATaskOption: 'Sélectionner une tâche…',
    TaskPanel_DependsOnHint: 'La tâche ne peut pas commencer tant que celles-ci ne sont pas terminées.',
    TaskPanel_SavingLabel: 'Enregistrement…',
    TaskPanel_CreatingLabel: 'Création…',
    TaskPanel_SaveChangesButton: 'Enregistrer les modifications',
    TaskPanel_CreateTaskButton: 'Créer la tâche',
    TaskPanel_CancelButton: 'Annuler',
    TaskPanel_DismissAriaLabel: 'Fermer',
    TaskPanel_DiscardUnsavedChangesConfirm: 'Abandonner les modifications non enregistrées ?',
    TaskPanel_SaveFallbackError: 'Impossible d\'enregistrer la tâche.',

    // ── Project panel ──
    ProjectPanel_EditHeader: 'Modifier le projet',
    ProjectPanel_NewHeader: 'Nouveau projet',
    ProjectPanel_ProjectNameLabel: 'Nom du projet',
    ProjectPanel_ProjectNamePlaceholder: 'Saisissez le nom du projet',
    ProjectPanel_ProjectNameRequired: 'Le nom du projet est requis',
    ProjectPanel_DescriptionLabel: 'Description',
    ProjectPanel_DescriptionPlaceholder: 'Saisissez une description',
    ProjectPanel_ProjectColorLabel: 'Couleur du projet',
    ProjectPanel_StatusLabel: 'Statut',
    ProjectPanel_StartDateLabel: 'Date de début',
    ProjectPanel_DueDateLabel: 'Date d\'échéance',
    ProjectPanel_DueDateError: 'La date d\'échéance doit être postérieure ou égale à la date de début',
    ProjectPanel_WhatHappensNextTitle: 'Que se passe-t-il ensuite ?',
    ProjectPanel_WhatHappensNextBody: 'Vous pourrez ajouter des tâches, définir des phases et suivre la progression une fois le projet créé.',
    ProjectPanel_SavingLabel: 'Enregistrement…',
    ProjectPanel_CreatingLabel: 'Création…',
    ProjectPanel_SaveChangesButton: 'Enregistrer les modifications',
    ProjectPanel_CreateProjectButton: 'Créer le projet',
    ProjectPanel_CancelButton: 'Annuler',
    ProjectPanel_DismissAriaLabel: 'Fermer',
    ProjectPanel_DiscardUnsavedChangesConfirm: 'Abandonner les modifications non enregistrées ?',
    ProjectPanel_SaveFallbackError: 'Impossible d\'enregistrer le projet.',

    // ── Import panel ──
    ImportPanel_SourceExcelTitle: 'Fichier Excel / CSV',
    ImportPanel_SourceExcelSubtitle: 'Importer des tâches depuis un tableur',
    ImportPanel_SourcePlannerTitle: 'Microsoft Planner',
    ImportPanel_SourcePlannerSubtitle: 'Importer des tâches depuis un plan Planner',
    ImportPanel_ClickToBrowse: 'Cliquez pour parcourir',
    ImportPanel_DragDropSuffix: ' ou glissez-déposez',
    ImportPanel_SupportedExtensions: 'Prend en charge .xlsx, .xls, .csv',
    ImportPanel_RowsColsSummary: '{rows} lignes, {cols} colonnes détectées',
    ImportPanel_LoadingPlannerPlans: 'Chargement des plans Planner…',
    ImportPanel_PlannerLoadError: 'Impossible de charger les plans Planner.',
    ImportPanel_PlannerPermissionsHintPrefix: 'Assurez-vous d\'avoir accès à Planner et que ',
    ImportPanel_PlannerPermissionsHintEmphasis: 'Tâches par Planner et To Do',
    ImportPanel_PlannerPermissionsHintSuffix: ' est disponible sur ce site.',
    ImportPanel_NoPlannerPlansFoundTitle: 'Aucun plan Planner trouvé',
    ImportPanel_NoPlannerPlansFoundBody: 'Vous n\'avez peut-être pas accès à des plans Planner, ou aucun n\'existe pour ce compte.',
    ImportPanel_TaskCountFoundIn: '{count} tâches trouvées dans « {planName} »',
    ImportPanel_ProjectDetailsIntroPrefix: 'Importation dans ',
    ImportPanel_ProjectDetailsIntroSuffix: '. Vérifiez les détails du projet ci-dessous.',
    ImportPanel_ProjectNameLabel: 'Nom du projet',
    ImportPanel_DescriptionLabel: 'Description',
    ImportPanel_StatusLabel: 'Statut',
    ImportPanel_ColorLabel: 'Couleur',
    ImportPanel_MapIntro: 'Associez les colonnes de votre fichier aux champs de tâche.',
    ImportPanel_CreatingProjectStatus: 'Création du projet…',
    ImportPanel_ImportingTasksStatus: 'Importation des tâches…',
    ImportPanel_ProgressLabel: '{done} sur {total}',
    ImportPanel_CouldNotCreateProject: 'Impossible de créer le projet.',
    ImportPanel_ImportCompletedWithErrors: 'Importation terminée avec {count} erreur(s).',
    ImportPanel_ProjectCreatedSuccess: 'Projet créé avec succès !',
    ImportPanel_ImportSuccessful: 'Importation réussie !',
    ImportPanel_TasksAddedTo: '{count} tâches ajoutées à « {projectName} »',
    ImportPanel_FailedRowsLabel: 'Lignes en échec :',
    ImportPanel_CloseButton: 'Fermer',
    ImportPanel_OpenProjectButton: 'Ouvrir le projet',
    ImportPanel_ViewImportedTasksButton: 'Voir les tâches importées',
    ImportPanel_NextMapColumnsButton: 'Suivant : Mapper les colonnes',
    ImportPanel_ImportNTasksButton: 'Importer {count} tâches',
    ImportPanel_BackButton: 'Retour',
    ImportPanel_CancelButton: 'Annuler',
    ImportPanel_NextButton: 'Suivant',
    ImportPanel_StepSource: 'Source',
    ImportPanel_StepProject: 'Projet',
    ImportPanel_StepMap: 'Mappage',
    ImportPanel_StepImport: 'Importation',
    ImportPanel_StepDone: 'Terminé',
    ImportPanel_ImportAsNewProjectHeader: 'Importer un fichier comme nouveau projet',
    ImportPanel_ImportIntoProjectHeader: 'Importer des tâches dans {projectName}',
    ImportPanel_CouldNotParseFile: 'Impossible d\'analyser le fichier.',
    ImportPanel_CouldNotLoadPlannerTasks: 'Impossible de charger les tâches de ce plan.',
    ImportPanel_CouldNotCreateProjectDetail: 'Impossible de créer le projet : {detail}',
    ImportPanel_CouldNotLinkDependencies: 'Impossible de lier les dépendances : {detail}',
    ImportPanel_UnknownError: 'erreur inconnue',

    // ── Column mapper (import) ──
    ColumnMapper_TaskNameRequiredBanner: 'Le nom de la tâche doit être mappé pour continuer.',
    ColumnMapper_SkippedColumnsBanner: '{count} colonne(s) seront ignorées.',
    ColumnMapper_SourceColumnHeader: 'Colonne source',
    ColumnMapper_TargetFieldHeader: 'Champ cible',
    ColumnMapper_StatusHeader: 'Statut',
    ColumnMapper_SkippedBadge: 'Ignorée',
    ColumnMapper_AutoMappedBadge: 'Mappée automatiquement',
    ColumnMapper_SetBadge: 'Définie',
    ColumnMapper_PreviewTitle: 'Aperçu : {columnName}',
    ColumnMapper_EmptyCellDash: '—',

    // ── Import field display names / ImportService ──
    ImportField_TaskName: 'Nom de la tâche',
    ImportField_StartDate: 'Date de début',
    ImportField_DueDate: 'Date d\'échéance',
    ImportField_Status: 'Statut',
    ImportField_Priority: 'Priorité',
    ImportField_AssignedTo: 'Assigné à',
    ImportField_AssignedToEmail: 'E-mail de l\'assigné',
    ImportField_PercentComplete: '% terminé',
    ImportField_Phase: 'Phase',
    ImportField_Description: 'Description',
    ImportField_Notes: 'Notes',
    ImportField_IsMilestone: 'Est un jalon',
    ImportField_Dependencies: 'Dépendances',
    ImportField_SkipColumn: '(Ignorer cette colonne)',
    ImportService_EmptyFileError: 'Le fichier semble vide ou ne contient aucune ligne de données.',
    ImportService_ReadErrorDetail: 'Impossible de lire le fichier : {detail}.',
    ImportService_FileReadError: 'Erreur de lecture du fichier.',
    ImportService_RowError: 'Ligne {rowNum} (« {title} ») : {error}',
    ImportService_AmbiguousDependency: 'La dépendance « {name} » correspond à plusieurs titres de tâche — ignorée.',
    ImportService_LinkDependencyError: 'Impossible de lier les dépendances pour la tâche {taskId} : {error}',

    // ── Health labels ──
    Health_Done: 'Terminé',
    Health_OnTrack: 'Sur la bonne voie',
    Health_AtRisk: 'À risque',
    Health_Overdue: 'En retard',

    // ── Status / Priority display labels ──
    Status_NotStarted: 'Non commencée',
    Status_InProgress: 'En cours',
    Status_Completed: 'Terminée',
    Status_OnHold: 'En attente',
    Status_Cancelled: 'Annulée',
    Priority_Critical: 'Critique',
    Priority_High: 'Élevée',
    Priority_Medium: 'Moyenne',
    Priority_Low: 'Faible',
    ProjectStatus_Planning: 'Planification',
    ProjectStatus_Active: 'Actif',
    ProjectStatus_OnHold: 'En attente',
    ProjectStatus_Completed: 'Terminé',
    ProjectStatus_Cancelled: 'Annulé',

    // ── Shell (SmartGantt.tsx) ──
    SmartGantt_LoadingProjects: 'Chargement des projets…',
    SmartGantt_UnableToLoad: 'Impossible de charger',
    SmartGantt_RetryButton: 'Réessayer',
    SmartGantt_NoProjectsYet: 'Aucun projet pour le moment',
    SmartGantt_NoProjectsSubtitle: 'Créez votre premier projet pour commencer.',
    SmartGantt_CreateFirstProjectButton: '+ Créer le premier projet',
    SmartGantt_ImportFromExcelButton: '📥 Importer depuis Excel',
    SmartGantt_LoadingTasks: 'Chargement des tâches…',
    SmartGantt_DismissAriaLabel: 'Fermer',
    SmartGantt_DeleteTaskDialogTitle: 'Supprimer la tâche',
    SmartGantt_DeleteTaskDialogSubtext: 'Voulez-vous vraiment supprimer « {taskTitle} » ? Cette action est irréversible.',
    SmartGantt_DeleteButton: 'Supprimer',
    SmartGantt_CancelButton: 'Annuler',
    SmartGantt_ArchiveProjectDialogTitle: 'Archiver le projet',
    SmartGantt_ArchiveProjectDialogSubtext: 'Archiver « {projectTitle} » ? Vous pourrez le désarchiver plus tard.',
    SmartGantt_ArchiveButton: 'Archiver',
    SmartGantt_SendToRecycleBinDialogTitle: 'Envoyer à la corbeille',
    SmartGantt_SendToRecycleBinDialogSubtext: 'Envoyer « {projectTitle} » à la corbeille du site ?',
    SmartGantt_SendToRecycleBinButton: 'Envoyer à la corbeille',
    SmartGantt_FailedLoadProjects: 'Échec du chargement des projets. Vérifiez les autorisations du site.',
    SmartGantt_FailedLoadTasks: 'Échec du chargement des tâches pour ce projet.',
    SmartGantt_FailedLoadPortfolioStats: 'Échec du chargement des statistiques du portefeuille.',
    SmartGantt_CouldNotSaveProject: 'Impossible d\'enregistrer le projet : {message}',
    SmartGantt_CouldNotDeleteProject: 'Impossible de supprimer le projet : {message}',
    SmartGantt_CouldNotArchiveProject: 'Impossible d\'archiver le projet : {message}',
    SmartGantt_CouldNotUnarchiveProject: 'Impossible de désarchiver le projet : {message}',
    SmartGantt_CouldNotSaveTask: 'Impossible d\'enregistrer la tâche : {message}',
    SmartGantt_CouldNotDeleteTask: 'Impossible de supprimer la tâche : {message}',
    SmartGantt_ImageExportFailed: 'Échec de l\'exportation de l\'image : {message}',
    SmartGantt_PowerPointExportFailed: 'Échec de l\'exportation PowerPoint : {message}',
    SmartGantt_PortfolioExportFailed: 'Échec de l\'exportation du portefeuille : {message}',
    SmartGantt_CouldNotUpdateTask: 'Impossible de mettre à jour la tâche : {message}',

    // ── Common ──
    ColorSwatch_AutoColorAriaLabel: 'Couleur automatique',
    ColorSwatch_CustomColorAriaLabel: 'Couleur personnalisée',
    ColorSwatch_PickCustomColorTitle: 'Choisir une couleur personnalisée',

    // ── Export (Excel / PowerPoint) ──
    Export_ColTaskName: 'Nom de la tâche',
    Export_ColPhase: 'Phase',
    Export_ColStartDate: 'Date de début',
    Export_ColDueDate: 'Date d\'échéance',
    Export_ColStatus: 'Statut',
    Export_ColPriority: 'Priorité',
    Export_ColAssignedTo: 'Assigné à',
    Export_ColAssignedToEmail: 'E-mail de l\'assigné',
    Export_ColPercentComplete: '% terminé',
    Export_ColIsMilestone: 'Est un jalon',
    Export_ColDescription: 'Description',
    Export_ColNotes: 'Notes',
    Export_Yes: 'Oui',
    Export_No: 'Non',
    Export_SheetNameTasks: 'Tâches',
    Export_ExcelFileSuffix: ' - Tâches.xlsx',
    Export_TaskNameColumnLabel: 'NOM DE LA TÂCHE',
    Export_ExportedDateLabel: 'Exporté le {date}',
    Export_ProjectReportLabel: 'RAPPORT DE PROJET',
    Export_StatusLine: 'Statut : {status}',
    Export_DateRangeSeparator: ' au ',
    Export_ProjectManagerLine: 'Chef de projet : {name}',
    Export_GeneratedDateLine: 'Généré le {date}',
    Export_ProjectSummaryTitle: 'Résumé du projet',
    Export_StatTotalTasks: 'Total des tâches',
    Export_StatCompleted: 'Terminées',
    Export_StatInProgress: 'En cours',
    Export_StatOnHold: 'En attente',
    Export_StatNotStarted: 'Non commencées',
    Export_OverallProgressLine: 'Progression globale',
    Export_OverallProgressPercent: '{percent} %',
    Export_StatusBreakdownTitle: 'Répartition par statut',
    Export_StatusBreakdownRow: '{status} : {count} ({percent} %)',
    Export_GanttTimelineTitle: 'Chronologie Gantt',
    Export_SummaryRecentActivityTitle: 'Activité récente',
    Export_ProjectOverviewLabel: 'Aperçu du projet',
    Export_DetailStatusLabel: 'Statut',
    Export_DetailStartDateLabel: 'Date de début',
    Export_DetailDueDateLabel: 'Date d\'échéance',
    Export_DetailProjectManagerLabel: 'Chef de projet',
    Export_Past7DaysLabel: '7 derniers jours',
    Export_NoActivityMessage: 'Aucune activité récente.',
    Export_CompletedThisWeekHeader: 'Terminées cette semaine ({count})',
    Export_NewBadge: 'NOUVEAU  ',
    Export_CompletedPercentLine: '{percent} % terminé',
    Export_MoreItemsSuffix: '+ {count} de plus',
    Export_InProgressUpdatedHeader: 'En cours / Mises à jour',
    Export_StatusPercentLine: '{status} — {percent} %',
    Export_PortfolioReportLabel: 'RAPPORT DE PORTEFEUILLE',
    Export_PortfolioOverviewTitle: 'Aperçu du portefeuille',
    Export_ProjectsCountLine: '{count} projets',
    Export_HealthSummaryOnTrack: '{count} sur la bonne voie',
    Export_HealthSummaryAtRisk: '{count} à risque',
    Export_HealthSummaryOverdue: '{count} en retard',
    Export_ProjectsSummaryHeader: 'Résumé des projets',
    Export_TableProject: 'Projet',
    Export_TableStatus: 'Statut',
    Export_TableHealth: 'État de santé',
    Export_TableTotal: 'Total',
    Export_TableDone: 'Terminées',
    Export_TableActive: 'Actives',
    Export_TableAtRisk: 'À risque',
    Export_TableOverdue: 'En retard',
    Export_TablePctDone: '% Terminé',
    Export_TableDueDate: 'Date d\'échéance',
    Export_PortfolioSummaryFileName: 'Résumé du portefeuille.xlsx',
    Export_PortfolioReportFileName: 'Rapport de portefeuille.pptx',
    Export_ProjectReportFileName: 'Rapport {projectName}.pptx',
    Export_UnavailableLabel: 'Indisponible',
    Export_SheetNamePortfolio: 'Portefeuille',
    Export_ColStart: 'Début',
    Export_ColDue: 'Échéance',
    Export_ImageGenerationFailed: 'Impossible de générer l\'image — le diagramme est peut-être trop grand pour être exporté sous forme d\'image.',
    Export_DrawingContextFailed: 'Impossible de créer un contexte de dessin pour l\'exportation.',
    Export_SvgRenderFailed: 'Échec du rendu SVG',
  };
});
