define([], function () {
  return {
    // ── Property pane ──
    PropertyPane_HeaderDescription: 'הגדרות תרשים גאנט חכם',
    PropertyPane_GeneralGroupName: 'כללי',
    PropertyPane_TitleFieldLabel: 'כותרת רכיב האתר',
    WebPart_DefaultTitle: 'תרשים גאנט חכם',

    // ── Toolbar ──
    Toolbar_ViewDashboard: 'לוח בקרה',
    Toolbar_ViewList: 'רשימה',
    Toolbar_ViewGantt: 'גאנט',
    Toolbar_ViewKanban: 'קנבן',
    Toolbar_ZoomDay: 'יום',
    Toolbar_ZoomWeek: 'שבוע',
    Toolbar_ZoomMonth: 'חודש',
    Toolbar_ZoomQuarter: 'רבעון',
    Toolbar_SelectProjectAriaLabel: 'בחר פרויקט',
    Toolbar_PortfolioLabel: 'תיק פרויקטים',
    Toolbar_SelectAProject: 'בחר פרויקט',
    Toolbar_AllProjectsSubtext: 'כל הפרויקטים',
    Toolbar_NoProjectsYet: 'אין עדיין פרויקטים',
    Toolbar_ArchivedBadge: 'בארכיון',
    Toolbar_ShowArchivedProjects: 'הצג פרויקטים בארכיון',
    Toolbar_NewProject: '+ פרויקט חדש',
    Toolbar_ImportFileAsNewProject: '📥 ייבוא קובץ כפרויקט חדש…',
    Toolbar_AddTask: '+ הוספת משימה',
    Toolbar_EditProject: 'עריכת פרויקט',
    Toolbar_OptionsButton: '⚙ אפשרויות',
    Toolbar_MoreOptionsTitle: 'אפשרויות נוספות',
    Toolbar_ExportToExcel: '📊 ייצוא ל-Excel',
    Toolbar_ExportToPowerPoint: '📑 ייצוא ל-PowerPoint',
    Toolbar_ScrollToTodayTitle: 'גלול להיום',
    Toolbar_TodayButton: '◉ היום',
    Toolbar_ImportTasks: '📥 ייבוא משימות…',
    Toolbar_ExportAsImage: '🖼 ייצוא כתמונה (PNG)',
    Toolbar_UnarchiveProject: '📂 הוצאה מהארכיון',
    Toolbar_ArchiveProject: '🗄️ העברה לארכיון',
    Toolbar_SendToRecycleBin: '🗑️ העברה לסל המיחזור',

    // ── Filter bar ──
    FilterBar_ClearOption: 'ניקוי',
    FilterBar_DueAny: 'כל תאריך יעד',
    FilterBar_DueOverdue: 'באיחור',
    FilterBar_DueToday: 'יעד היום',
    FilterBar_DueWeek: 'יעד תוך 7 ימים',
    FilterBar_SearchPlaceholder: 'חיפוש משימות…',
    FilterBar_SearchAriaLabel: 'חיפוש משימות',
    FilterBar_StatusChipLabel: 'סטטוס',
    FilterBar_PriorityChipLabel: 'עדיפות',
    FilterBar_AssigneeChipLabel: 'אחראי',
    FilterBar_PhaseChipLabel: 'שלב',
    FilterBar_DueDateAriaLabel: 'סינון לפי תאריך יעד',
    FilterBar_MatchCount: '{matchCount} מתוך {totalCount}',
    FilterBar_ClearFilters: '✕ ניקוי מסננים',
    FilterBar_ChipLabelWithCount: '{label} ({count}) ▾',
    FilterBar_ChipLabelNoCount: '{label} ▾',

    // ── Gantt view ──
    Gantt_TaskColumnHeader: 'משימה',
    Gantt_DurationColumnHeader: 'משך',
    Gantt_AddTaskButton: '+ הוספת משימה',
    Gantt_EmptyTitle: 'אין עדיין משימות',
    Gantt_EmptySubtitle: 'הוסף משימות כדי לראות אותן בתרשים הגאנט.',
    Gantt_AddFirstTask: '+ הוספת משימה ראשונה',
    Gantt_ImportTasksButton: '📥 ייבוא משימות',
    Gantt_EditTitle: 'עריכה',
    Gantt_DeleteTitle: 'מחיקה',
    Gantt_EditTaskAriaLabel: 'עריכת משימה {taskTitle}',
    Gantt_DeleteTaskAriaLabel: 'מחיקת משימה {taskTitle}',
    Gantt_ExpandPhaseAriaLabel: '{action} שלב {phase}',
    Gantt_ExpandAction: 'הרחבה',
    Gantt_CollapseAction: 'צמצום',
    Gantt_DependencyViolationTooltip: 'התחילה לפני שכל התלויות הושלמו',
    Gantt_MilestoneAriaLabel: '{taskTitle}, אבן דרך, {date}',
    Gantt_BarAriaLabel: '{taskTitle}, {startDate} עד {dueDate}, {percent}% הושלם',
    Gantt_PercentCompleteTooltip: '{value}% הושלם',

    // ── Gantt options/settings panel ──
    GanttSettings_PanelHeader: '⚙ אפשרויות',
    GanttSettings_ColorCodingSection: 'קידוד צבעים',
    GanttSettings_ByStatus: 'לפי סטטוס',
    GanttSettings_ByPriority: 'לפי עדיפות',
    GanttSettings_ByPhase: 'לפי שלב',
    GanttSettings_ByHealth: 'לפי מצב בריאות',
    GanttSettings_HeaderColorSection: 'צבע כותרת',
    GanttSettings_ThemeDark: 'כהה',
    GanttSettings_ThemeNavy: 'כחול נייבי',
    GanttSettings_ThemeTeal: 'טורקיז',
    GanttSettings_ThemePurple: 'סגול',
    GanttSettings_ThemeLight: 'בהיר',
    GanttSettings_HeaderLabelsSection: 'תוויות כותרת',
    GanttSettings_WeekLabelDates: 'תאריכים',
    GanttSettings_WeekLabelDatesDesc: '3 ביוני, 10 ביוני…',
    GanttSettings_WeekLabelProject: 'שבועות פרויקט',
    GanttSettings_WeekLabelProjectDesc: 'ש1, ש2…',
    GanttSettings_WeekLabelIso: 'שבועות לוח שנה',
    GanttSettings_WeekLabelIsoDesc: 'ש23, ש24…',
    GanttSettings_ProjectWeeksHint: 'שבוע 1 מתחיל ביום שני של המשימה המוקדמת ביותר שלך — מצוין למצגות.',
    GanttSettings_BarStyleSection: 'סגנון פס',
    GanttSettings_BarStyleGradient: 'גרדיאנט',
    GanttSettings_BarStyleFlat: 'שטוח',
    GanttSettings_RowHeightSection: 'גובה שורה',
    GanttSettings_HeightCompact: 'קומפקטי',
    GanttSettings_HeightNormal: 'רגיל',
    GanttSettings_HeightSpacious: 'מרווח',
    GanttSettings_ShowHideSection: 'הצגה / הסתרה',
    GanttSettings_WeekendShading: 'הצללת סופי שבוע',
    GanttSettings_DependencyArrows: 'חצי תלות',
    GanttSettings_CriticalPathAlwaysVisible: 'נתיב קריטי תמיד גלוי',
    GanttSettings_AllOthersOnHoverOnly: 'כל השאר רק במעבר עכבר',
    GanttSettings_CriticalPathHighlight: 'הדגשת נתיב קריטי',
    GanttSettings_ProgressPercentOnBars: 'אחוז התקדמות על הפסים',
    GanttSettings_AssigneeNameOnBars: 'שם אחראי על הפסים',
    GanttSettings_HealthStatusBadges: 'תגי מצב בריאות',

    // ── List view ──
    ListView_ColTaskName: 'שם משימה',
    ListView_ColStatus: 'סטטוס',
    ListView_ColHealth: 'מצב בריאות',
    ListView_ColPriority: 'עדיפות',
    ListView_ColStart: 'התחלה',
    ListView_ColDue: 'יעד',
    ListView_ColAssignedTo: 'הוקצה ל',
    ListView_ColProgress: 'התקדמות',
    ListView_ColPhase: 'שלב',
    ListView_ColPredecessors: 'תלויות קודמות',
    ListView_EmptyTitle: 'אין עדיין משימות',
    ListView_AddFirstTask: '+ הוספת משימה ראשונה',
    ListView_AddTaskRow: '+ הוספת משימה',
    ListView_Unassigned: 'לא מוקצה',
    ListView_DependencyViolationTooltip: 'התחילה לפני שכל התלויות הושלמו',
    ListView_StatusAriaLabel: 'סטטוס של {taskTitle}',
    ListView_PriorityAriaLabel: 'עדיפות של {taskTitle}',
    ListView_EditTaskAriaLabel: 'עריכת משימה {taskTitle}',
    ListView_DeleteTaskAriaLabel: 'מחיקת משימה {taskTitle}',
    ListView_EditTitle: 'עריכה',
    ListView_DeleteTitle: 'מחיקה',

    // ── Kanban view ──
    Kanban_ColumnNotStarted: 'טרם התחיל',
    Kanban_ColumnInProgress: 'בביצוע',
    Kanban_ColumnOnHold: 'בהמתנה',
    Kanban_ColumnCompleted: 'הושלם',
    Kanban_ColumnCancelled: 'בוטל',
    Kanban_AddTaskButton: '+ הוספת משימה',
    Kanban_EditTitle: 'עריכה',
    Kanban_DeleteTitle: 'מחיקה',
    Kanban_CardAriaLabel: '{taskTitle}, {status}. הקש Enter לעריכה, חץ שמאלה או ימינה לשינוי סטטוס.',
    Kanban_EditTaskAriaLabel: 'עריכת משימה {taskTitle}',
    Kanban_DeleteTaskAriaLabel: 'מחיקת משימה {taskTitle}',

    // ── Dashboard view ──
    Dashboard_TotalTasks: 'סך המשימות',
    Dashboard_Completed: 'הושלמו',
    Dashboard_InProgress: 'בביצוע',
    Dashboard_OnHold: 'בהמתנה',
    Dashboard_NotStarted: 'טרם החל',
    Dashboard_Cancelled: 'בוטלו',
    Dashboard_OverallProgress: 'התקדמות כוללת',
    Dashboard_ProjectManagerLabel: 'מנהל פרויקט: {name}',
    Dashboard_PhaseProgressHeader: 'התקדמות שלבים',
    Dashboard_StatusBreakdownHeader: 'פילוח לפי סטטוס',
    Dashboard_PriorityBreakdownHeader: 'פילוח לפי עדיפות',
    Dashboard_PriorityCritical: 'קריטי',
    Dashboard_PriorityHigh: 'גבוה',
    Dashboard_PriorityMedium: 'בינוני',
    Dashboard_PriorityLow: 'נמוך',
    Dashboard_OverdueHeader: 'באיחור  ({count})',
    Dashboard_DueNext14DaysHeader: 'יעד ב-14 הימים הקרובים  ({count})',
    Dashboard_CompletedThisWeekHeader: 'הושלמו השבוע',
    Dashboard_UpdatedThisWeekHeader: 'עודכנו השבוע',
    Dashboard_Today: 'היום',
    Dashboard_Tomorrow: 'מחר',
    Dashboard_DaysLeft: '{days} ימים',
    Dashboard_EmptyTitle: 'אין עדיין משימות',
    Dashboard_EmptySubtitle: 'הוסף משימות כדי לראות את לוח הבקרה של הפרויקט.',
    Dashboard_AddTaskButton: '+ הוספת משימה',

    // ── Portfolio view ──
    Portfolio_ProjectCount: '{count} פרויקט{plural}',
    Portfolio_OnTrackSummary: '{count} במסלול',
    Portfolio_AtRiskSummary: '{count} בסיכון',
    Portfolio_OverdueSummary: '{count} באיחור',
    Portfolio_DoneSummary: '{count} הושלמו',
    Portfolio_SortLabel: 'מיון:',
    Portfolio_SortAZ: 'א-ת',
    Portfolio_SortHealth: 'מצב בריאות',
    Portfolio_SortStatus: 'סטטוס',
    Portfolio_SortCompletion: 'השלמה',
    Portfolio_RefreshTitle: 'רענון',
    Portfolio_RefreshButton: 'רענון',
    Portfolio_LoadingStats: 'טוען נתונים סטטיסטיים…',
    Portfolio_EmptyTitle: 'אין עדיין פרויקטים',
    Portfolio_CreateFirstProject: '+ יצירת פרויקט ראשון',
    Portfolio_StatsUnavailable: 'הנתונים הסטטיסטיים אינם זמינים',
    Portfolio_StatsUnavailableDetail: 'לא ניתן לטעון נתונים סטטיסטיים עבור פרויקט זה.',
    Portfolio_OverallProgressLabel: 'התקדמות כוללת',
    Portfolio_TaskCountDone: 'הושלמו',
    Portfolio_TaskCountActive: 'פעילות',
    Portfolio_TaskCountAtRisk: 'בסיכון',
    Portfolio_TaskCountOverdue: 'באיחור',
    Portfolio_ViewGanttLink: 'צפייה בגאנט ←',
    Portfolio_TodayTooltip: 'היום',

    // ── Task panel ──
    TaskPanel_EditHeader: 'עריכה: {taskTitle}',
    TaskPanel_NewTaskHeader: 'משימה חדשה',
    TaskPanel_TabBasic: 'בסיסי',
    TaskPanel_TabDetails: 'פרטים',
    TaskPanel_TabLinks: 'קישורים',
    TaskPanel_ProjectLabelPrefix: 'פרויקט: ',
    TaskPanel_TaskNameLabel: 'שם המשימה',
    TaskPanel_TaskNamePlaceholder: 'הזן שם משימה',
    TaskPanel_TaskNameRequired: 'שם המשימה הוא שדה חובה',
    TaskPanel_DescriptionLabel: 'תיאור',
    TaskPanel_DescriptionPlaceholder: 'הזן תיאור',
    TaskPanel_StartDateLabel: 'תאריך התחלה',
    TaskPanel_DueDateLabel: 'תאריך יעד',
    TaskPanel_DueDateError: 'תאריך היעד חייב להיות זהה או מאוחר מתאריך ההתחלה',
    TaskPanel_StatusLabel: 'סטטוס',
    TaskPanel_PriorityLabel: 'עדיפות',
    TaskPanel_PercentCompleteLabel: '% הושלם: {percent}%',
    TaskPanel_AssignedToLabel: 'הוקצה ל',
    TaskPanel_AssignedToPlaceholder: 'חיפוש אנשים…',
    TaskPanel_PhaseLabel: 'שלב',
    TaskPanel_PhasePlaceholder: 'הזן שם שלב',
    TaskPanel_PhaseHint: 'מקבץ משימות יחד בתצוגות גאנט ורשימה.',
    TaskPanel_MilestoneLabel: 'אבן דרך',
    TaskPanel_MilestoneOnText: 'כן',
    TaskPanel_MilestoneOffText: 'לא',
    TaskPanel_CustomBarColorLabel: 'צבע פס מותאם אישית',
    TaskPanel_CustomBarColorOptionalSuffix: ' (אופציונלי)',
    TaskPanel_AutoColorHint: 'צבע אוטומטי לפי הגדרות סטטוס/עדיפות/שלב.',
    TaskPanel_NotesLabel: 'הערות',
    TaskPanel_NotesPlaceholder: 'הזן הערות',
    TaskPanel_ParentTaskLabel: 'משימת אב',
    TaskPanel_ParentTaskNone: '(ללא)',
    TaskPanel_ParentTaskHasChildrenHint: 'למשימה זו יש תת-משימות ולכן לא ניתן להגדיר לה משימת אב משלה.',
    TaskPanel_ParentTaskHint: 'קנן משימה זו תחת משימה אחרת כתת-משימה.',
    TaskPanel_DependsOnLabel: 'תלוי ב',
    TaskPanel_RemoveDependencyTitle: 'הסרת תלות ב-"{taskTitle}"',
    TaskPanel_AddDependencyPlaceholder: 'הוספת תלות…',
    TaskPanel_SelectATaskOption: 'בחר משימה…',
    TaskPanel_DependsOnHint: 'המשימה לא יכולה להתחיל עד שאלו יושלמו.',
    TaskPanel_SavingLabel: 'שומר…',
    TaskPanel_CreatingLabel: 'יוצר…',
    TaskPanel_SaveChangesButton: 'שמירת שינויים',
    TaskPanel_CreateTaskButton: 'יצירת משימה',
    TaskPanel_CancelButton: 'ביטול',
    TaskPanel_DismissAriaLabel: 'סגירה',
    TaskPanel_DiscardUnsavedChangesConfirm: 'לבטל שינויים שלא נשמרו?',
    TaskPanel_SaveFallbackError: 'לא ניתן היה לשמור את המשימה.',

    // ── Project panel ──
    ProjectPanel_EditHeader: 'עריכת פרויקט',
    ProjectPanel_NewHeader: 'פרויקט חדש',
    ProjectPanel_ProjectNameLabel: 'שם הפרויקט',
    ProjectPanel_ProjectNamePlaceholder: 'הזן שם פרויקט',
    ProjectPanel_ProjectNameRequired: 'שם הפרויקט הוא שדה חובה',
    ProjectPanel_DescriptionLabel: 'תיאור',
    ProjectPanel_DescriptionPlaceholder: 'הזן תיאור',
    ProjectPanel_ProjectColorLabel: 'צבע הפרויקט',
    ProjectPanel_StatusLabel: 'סטטוס',
    ProjectPanel_StartDateLabel: 'תאריך התחלה',
    ProjectPanel_DueDateLabel: 'תאריך יעד',
    ProjectPanel_DueDateError: 'תאריך היעד חייב להיות זהה או מאוחר מתאריך ההתחלה',
    ProjectPanel_WhatHappensNextTitle: 'מה קורה בהמשך?',
    ProjectPanel_WhatHappensNextBody: 'לאחר יצירת הפרויקט תוכל להוסיף משימות, להגדיר שלבים ולעקוב אחר ההתקדמות.',
    ProjectPanel_SavingLabel: 'שומר…',
    ProjectPanel_CreatingLabel: 'יוצר…',
    ProjectPanel_SaveChangesButton: 'שמירת שינויים',
    ProjectPanel_CreateProjectButton: 'יצירת פרויקט',
    ProjectPanel_CancelButton: 'ביטול',
    ProjectPanel_DismissAriaLabel: 'סגירה',
    ProjectPanel_DiscardUnsavedChangesConfirm: 'לבטל שינויים שלא נשמרו?',
    ProjectPanel_SaveFallbackError: 'לא ניתן היה לשמור את הפרויקט.',

    // ── Import panel ──
    ImportPanel_SourceExcelTitle: 'קובץ Excel / CSV',
    ImportPanel_SourceExcelSubtitle: 'ייבוא משימות מגיליון אלקטרוני',
    ImportPanel_SourcePlannerTitle: 'Microsoft Planner',
    ImportPanel_SourcePlannerSubtitle: 'ייבוא משימות מתוכנית ב-Planner',
    ImportPanel_ClickToBrowse: 'לחץ לעיון',
    ImportPanel_DragDropSuffix: ' או גרור ושחרר',
    ImportPanel_SupportedExtensions: 'תומך ב-.xlsx, .xls, .csv',
    ImportPanel_RowsColsSummary: 'זוהו {rows} שורות, {cols} עמודות',
    ImportPanel_LoadingPlannerPlans: 'טוען תוכניות Planner…',
    ImportPanel_PlannerLoadError: 'לא ניתן היה לטעון תוכניות Planner.',
    ImportPanel_PlannerPermissionsHintPrefix: 'ודא שיש לך גישה ל-Planner ושהאפליקציה ',
    ImportPanel_PlannerPermissionsHintEmphasis: 'משימות מ-Planner ו-To Do',
    ImportPanel_PlannerPermissionsHintSuffix: ' זמינה לאתר זה.',
    ImportPanel_NoPlannerPlansFoundTitle: 'לא נמצאו תוכניות Planner',
    ImportPanel_NoPlannerPlansFoundBody: 'ייתכן שאין לך גישה לתוכניות Planner כלשהן, או שלא קיימות תוכניות עבור חשבון זה.',
    ImportPanel_TaskCountFoundIn: 'נמצאו {count} משימות ב-"{planName}"',
    ImportPanel_ProjectDetailsIntroPrefix: 'מייבא אל ',
    ImportPanel_ProjectDetailsIntroSuffix: '. עיין בפרטי הפרויקט להלן.',
    ImportPanel_ProjectNameLabel: 'שם הפרויקט',
    ImportPanel_DescriptionLabel: 'תיאור',
    ImportPanel_StatusLabel: 'סטטוס',
    ImportPanel_ColorLabel: 'צבע',
    ImportPanel_MapIntro: 'מפה את העמודות מהקובץ שלך לשדות המשימה.',
    ImportPanel_CreatingProjectStatus: 'יוצר פרויקט…',
    ImportPanel_ImportingTasksStatus: 'מייבא משימות…',
    ImportPanel_ProgressLabel: '{done} מתוך {total}',
    ImportPanel_CouldNotCreateProject: 'לא ניתן היה ליצור את הפרויקט.',
    ImportPanel_ImportCompletedWithErrors: 'הייבוא הושלם עם {count} שגיאות.',
    ImportPanel_ProjectCreatedSuccess: 'הפרויקט נוצר בהצלחה!',
    ImportPanel_ImportSuccessful: 'הייבוא בוצע בהצלחה!',
    ImportPanel_TasksAddedTo: '{count} משימות נוספו ל-"{projectName}"',
    ImportPanel_FailedRowsLabel: 'שורות שנכשלו:',
    ImportPanel_CloseButton: 'סגירה',
    ImportPanel_OpenProjectButton: 'פתיחת הפרויקט',
    ImportPanel_ViewImportedTasksButton: 'הצגת המשימות שיובאו',
    ImportPanel_NextMapColumnsButton: 'הבא: מיפוי עמודות',
    ImportPanel_ImportNTasksButton: 'ייבוא {count} משימות',
    ImportPanel_BackButton: 'הקודם',
    ImportPanel_CancelButton: 'ביטול',
    ImportPanel_NextButton: 'הבא',
    ImportPanel_StepSource: 'מקור',
    ImportPanel_StepProject: 'פרויקט',
    ImportPanel_StepMap: 'מיפוי',
    ImportPanel_StepImport: 'ייבוא',
    ImportPanel_StepDone: 'הושלם',
    ImportPanel_ImportAsNewProjectHeader: 'ייבוא קובץ כפרויקט חדש',
    ImportPanel_ImportIntoProjectHeader: 'ייבוא משימות אל {projectName}',
    ImportPanel_CouldNotParseFile: 'לא ניתן היה לנתח את הקובץ.',
    ImportPanel_CouldNotLoadPlannerTasks: 'לא ניתן היה לטעון משימות מתוכנית זו.',
    ImportPanel_CouldNotCreateProjectDetail: 'לא ניתן היה ליצור פרויקט: {detail}',
    ImportPanel_CouldNotLinkDependencies: 'לא ניתן היה לקשר תלויות: {detail}',
    ImportPanel_UnknownError: 'שגיאה לא ידועה',

    // ── Column mapper (import) ──
    ColumnMapper_TaskNameRequiredBanner: 'יש למפות את שם המשימה כדי להמשיך.',
    ColumnMapper_SkippedColumnsBanner: '{count} עמודות ידולגו.',
    ColumnMapper_SourceColumnHeader: 'עמודת מקור',
    ColumnMapper_TargetFieldHeader: 'שדה יעד',
    ColumnMapper_StatusHeader: 'סטטוס',
    ColumnMapper_SkippedBadge: 'דולג',
    ColumnMapper_AutoMappedBadge: 'מופה אוטומטית',
    ColumnMapper_SetBadge: 'הוגדר',
    ColumnMapper_PreviewTitle: 'תצוגה מקדימה: {columnName}',
    ColumnMapper_EmptyCellDash: '—',

    // ── Import field display names / ImportService ──
    ImportField_TaskName: 'שם משימה',
    ImportField_StartDate: 'תאריך התחלה',
    ImportField_DueDate: 'תאריך יעד',
    ImportField_Status: 'סטטוס',
    ImportField_Priority: 'עדיפות',
    ImportField_AssignedTo: 'הוקצה ל',
    ImportField_AssignedToEmail: 'דוא"ל האחראי',
    ImportField_PercentComplete: '% הושלם',
    ImportField_Phase: 'שלב',
    ImportField_Description: 'תיאור',
    ImportField_Notes: 'הערות',
    ImportField_IsMilestone: 'אבן דרך',
    ImportField_Dependencies: 'תלויות',
    ImportField_SkipColumn: '(דלג על עמודה זו)',
    ImportService_EmptyFileError: 'נראה שהקובץ ריק או שאין בו שורות נתונים.',
    ImportService_ReadErrorDetail: 'לא ניתן היה לקרוא את הקובץ: {detail}.',
    ImportService_FileReadError: 'שגיאת קריאת קובץ.',
    ImportService_RowError: 'שורה {rowNum} ("{title}"): {error}',
    ImportService_AmbiguousDependency: 'התלות "{name}" תואמת ליותר מכותרת משימה אחת — דולגה.',
    ImportService_LinkDependencyError: 'לא ניתן היה לקשר תלויות עבור המשימה {taskId}: {error}',

    // ── Health labels ──
    Health_Done: 'הושלם',
    Health_OnTrack: 'במסלול',
    Health_AtRisk: 'בסיכון',
    Health_Overdue: 'באיחור',

    // ── Status / Priority display labels ──
    Status_NotStarted: 'טרם התחיל',
    Status_InProgress: 'בביצוע',
    Status_Completed: 'הושלם',
    Status_OnHold: 'בהמתנה',
    Status_Cancelled: 'בוטל',
    Priority_Critical: 'קריטי',
    Priority_High: 'גבוה',
    Priority_Medium: 'בינוני',
    Priority_Low: 'נמוך',
    ProjectStatus_Planning: 'בתכנון',
    ProjectStatus_Active: 'פעיל',
    ProjectStatus_OnHold: 'בהמתנה',
    ProjectStatus_Completed: 'הושלם',
    ProjectStatus_Cancelled: 'בוטל',

    // ── Shell (SmartGantt.tsx) ──
    SmartGantt_LoadingProjects: 'טוען פרויקטים…',
    SmartGantt_UnableToLoad: 'לא ניתן לטעון',
    SmartGantt_RetryButton: 'ניסיון חוזר',
    SmartGantt_NoProjectsYet: 'אין עדיין פרויקטים',
    SmartGantt_NoProjectsSubtitle: 'צור את הפרויקט הראשון שלך כדי להתחיל.',
    SmartGantt_CreateFirstProjectButton: '+ יצירת פרויקט ראשון',
    SmartGantt_ImportFromExcelButton: '📥 ייבוא מ-Excel',
    SmartGantt_LoadingTasks: 'טוען משימות…',
    SmartGantt_DismissAriaLabel: 'סגירה',
    SmartGantt_DeleteTaskDialogTitle: 'מחיקת משימה',
    SmartGantt_DeleteTaskDialogSubtext: 'האם אתה בטוח שברצונך למחוק את "{taskTitle}"? פעולה זו אינה ניתנת לביטול.',
    SmartGantt_DeleteButton: 'מחיקה',
    SmartGantt_CancelButton: 'ביטול',
    SmartGantt_ArchiveProjectDialogTitle: 'העברת פרויקט לארכיון',
    SmartGantt_ArchiveProjectDialogSubtext: 'להעביר את "{projectTitle}" לארכיון? ניתן להוציא אותו מהארכיון מאוחר יותר.',
    SmartGantt_ArchiveButton: 'העברה לארכיון',
    SmartGantt_SendToRecycleBinDialogTitle: 'העברה לסל המיחזור',
    SmartGantt_SendToRecycleBinDialogSubtext: 'להעביר את "{projectTitle}" לסל המיחזור של האתר?',
    SmartGantt_SendToRecycleBinButton: 'העברה לסל המיחזור',
    SmartGantt_FailedLoadProjects: 'טעינת הפרויקטים נכשלה. בדוק את הרשאות האתר.',
    SmartGantt_FailedLoadTasks: 'טעינת המשימות עבור פרויקט זה נכשלה.',
    SmartGantt_FailedLoadPortfolioStats: 'טעינת נתוני תיק הפרויקטים נכשלה.',
    SmartGantt_CouldNotSaveProject: 'לא ניתן היה לשמור את הפרויקט: {message}',
    SmartGantt_CouldNotDeleteProject: 'לא ניתן היה למחוק את הפרויקט: {message}',
    SmartGantt_CouldNotArchiveProject: 'לא ניתן היה להעביר את הפרויקט לארכיון: {message}',
    SmartGantt_CouldNotUnarchiveProject: 'לא ניתן היה להוציא את הפרויקט מהארכיון: {message}',
    SmartGantt_CouldNotSaveTask: 'לא ניתן היה לשמור את המשימה: {message}',
    SmartGantt_CouldNotDeleteTask: 'לא ניתן היה למחוק את המשימה: {message}',
    SmartGantt_ImageExportFailed: 'ייצוא התמונה נכשל: {message}',
    SmartGantt_PowerPointExportFailed: 'ייצוא ל-PowerPoint נכשל: {message}',
    SmartGantt_PortfolioExportFailed: 'ייצוא תיק הפרויקטים נכשל: {message}',
    SmartGantt_CouldNotUpdateTask: 'לא ניתן היה לעדכן את המשימה: {message}',

    // ── Common ──
    ColorSwatch_AutoColorAriaLabel: 'צבע אוטומטי',
    ColorSwatch_CustomColorAriaLabel: 'צבע מותאם אישית',
    ColorSwatch_PickCustomColorTitle: 'בחר צבע מותאם אישית',

    // ── Export (Excel / PowerPoint) ──
    Export_ColTaskName: 'שם משימה',
    Export_ColPhase: 'שלב',
    Export_ColStartDate: 'תאריך התחלה',
    Export_ColDueDate: 'תאריך יעד',
    Export_ColStatus: 'סטטוס',
    Export_ColPriority: 'עדיפות',
    Export_ColAssignedTo: 'הוקצה ל',
    Export_ColAssignedToEmail: 'דוא"ל האחראי',
    Export_ColPercentComplete: '% הושלם',
    Export_ColIsMilestone: 'אבן דרך',
    Export_ColDescription: 'תיאור',
    Export_ColNotes: 'הערות',
    Export_Yes: 'כן',
    Export_No: 'לא',
    Export_SheetNameTasks: 'משימות',
    Export_ExcelFileSuffix: ' - משימות.xlsx',
    Export_TaskNameColumnLabel: 'שם המשימה',
    Export_ExportedDateLabel: 'יוצא {date}',
    Export_ProjectReportLabel: 'דוח פרויקט',
    Export_StatusLine: 'סטטוס: {status}',
    Export_DateRangeSeparator: ' עד ',
    Export_ProjectManagerLine: 'מנהל פרויקט: {name}',
    Export_GeneratedDateLine: 'נוצר {date}',
    Export_ProjectSummaryTitle: 'סיכום פרויקט',
    Export_StatTotalTasks: 'סך המשימות',
    Export_StatCompleted: 'הושלמו',
    Export_StatInProgress: 'בביצוע',
    Export_StatOnHold: 'בהמתנה',
    Export_StatNotStarted: 'טרם החל',
    Export_OverallProgressLine: 'התקדמות כוללת',
    Export_OverallProgressPercent: '{percent}%',
    Export_StatusBreakdownTitle: 'פילוח לפי סטטוס',
    Export_StatusBreakdownRow: '{status}: {count} ({percent}%)',
    Export_GanttTimelineTitle: 'ציר זמן גאנט',
    Export_SummaryRecentActivityTitle: 'פעילות אחרונה',
    Export_ProjectOverviewLabel: 'סקירת פרויקט',
    Export_DetailStatusLabel: 'סטטוס',
    Export_DetailStartDateLabel: 'תאריך התחלה',
    Export_DetailDueDateLabel: 'תאריך יעד',
    Export_DetailProjectManagerLabel: 'מנהל פרויקט',
    Export_Past7DaysLabel: '7 הימים האחרונים',
    Export_NoActivityMessage: 'אין פעילות אחרונה.',
    Export_CompletedThisWeekHeader: 'הושלמו השבוע ({count})',
    Export_NewBadge: 'חדש  ',
    Export_CompletedPercentLine: '{percent}% הושלם',
    Export_MoreItemsSuffix: '+ {count} נוספים',
    Export_InProgressUpdatedHeader: 'בביצוע / עודכן',
    Export_StatusPercentLine: '{status} — {percent}%',
    Export_PortfolioReportLabel: 'דוח תיק פרויקטים',
    Export_PortfolioOverviewTitle: 'סקירת תיק הפרויקטים',
    Export_ProjectsCountLine: '{count} פרויקטים',
    Export_HealthSummaryOnTrack: '{count} במסלול',
    Export_HealthSummaryAtRisk: '{count} בסיכון',
    Export_HealthSummaryOverdue: '{count} באיחור',
    Export_ProjectsSummaryHeader: 'סיכום פרויקטים',
    Export_TableProject: 'פרויקט',
    Export_TableStatus: 'סטטוס',
    Export_TableHealth: 'מצב בריאות',
    Export_TableTotal: 'סך הכול',
    Export_TableDone: 'הושלמו',
    Export_TableActive: 'פעילות',
    Export_TableAtRisk: 'בסיכון',
    Export_TableOverdue: 'באיחור',
    Export_TablePctDone: '% הושלם',
    Export_TableDueDate: 'תאריך יעד',
    Export_PortfolioSummaryFileName: 'סיכום תיק פרויקטים.xlsx',
    Export_PortfolioReportFileName: 'דוח תיק פרויקטים.pptx',
    Export_ProjectReportFileName: 'דוח {projectName}.pptx',
    Export_UnavailableLabel: 'לא זמין',
    Export_SheetNamePortfolio: 'תיק',
    Export_ColStart: 'התחלה',
    Export_ColDue: 'יעד',
    Export_ImageGenerationFailed: 'לא ניתן היה ליצור את התמונה — ייתכן שהתרשים גדול מדי לייצוא כתמונה.',
    Export_DrawingContextFailed: 'לא ניתן היה ליצור הקשר ציור לייצוא.',
    Export_SvgRenderFailed: 'עיבוד ה-SVG נכשל',
  };
});
