define([], function () {
  return {
    // ── Property pane ──
    PropertyPane_HeaderDescription: 'स्मार्ट गैंट चार्ट सेटिंग्स',
    PropertyPane_GeneralGroupName: 'सामान्य',
    PropertyPane_TitleFieldLabel: 'वेब पार्ट शीर्षक',
    WebPart_DefaultTitle: 'स्मार्ट गैंट चार्ट',

    // ── Toolbar ──
    Toolbar_ViewDashboard: 'डैशबोर्ड',
    Toolbar_ViewList: 'सूची',
    Toolbar_ViewGantt: 'गैंट',
    Toolbar_ViewKanban: 'कानबन',
    Toolbar_ZoomDay: 'दिन',
    Toolbar_ZoomWeek: 'सप्ताह',
    Toolbar_ZoomMonth: 'महीना',
    Toolbar_ZoomQuarter: 'तिमाही',
    Toolbar_SelectProjectAriaLabel: 'प्रोजेक्ट चुनें',
    Toolbar_PortfolioLabel: 'पोर्टफोलियो',
    Toolbar_SelectAProject: 'एक प्रोजेक्ट चुनें',
    Toolbar_AllProjectsSubtext: 'सभी प्रोजेक्ट',
    Toolbar_NoProjectsYet: 'अभी तक कोई प्रोजेक्ट नहीं',
    Toolbar_ArchivedBadge: 'संग्रहीत',
    Toolbar_ShowArchivedProjects: 'संग्रहीत प्रोजेक्ट दिखाएं',
    Toolbar_NewProject: '+ नया प्रोजेक्ट',
    Toolbar_ImportFileAsNewProject: '📥 फ़ाइल को नए प्रोजेक्ट के रूप में आयात करें…',
    Toolbar_AddTask: '+ कार्य जोड़ें',
    Toolbar_EditProject: 'प्रोजेक्ट संपादित करें',
    Toolbar_OptionsButton: '⚙ विकल्प',
    Toolbar_MoreOptionsTitle: 'अधिक विकल्प',
    Toolbar_ExportToExcel: '📊 Excel में निर्यात करें',
    Toolbar_ExportToPowerPoint: '📑 PowerPoint में निर्यात करें',
    Toolbar_ScrollToTodayTitle: 'आज तक स्क्रॉल करें',
    Toolbar_TodayButton: '◉ आज',
    Toolbar_ImportTasks: '📥 कार्य आयात करें…',
    Toolbar_ExportAsImage: '🖼 छवि के रूप में निर्यात करें (PNG)',
    Toolbar_UnarchiveProject: '📂 प्रोजेक्ट अनआर्काइव करें',
    Toolbar_ArchiveProject: '🗄️ प्रोजेक्ट संग्रहीत करें',
    Toolbar_SendToRecycleBin: '🗑️ रीसायकल बिन में भेजें',

    // ── Filter bar ──
    FilterBar_ClearOption: 'साफ़ करें',
    FilterBar_DueAny: 'कोई भी नियत तिथि',
    FilterBar_DueOverdue: 'अतिदेय',
    FilterBar_DueToday: 'आज नियत',
    FilterBar_DueWeek: '7 दिनों में नियत',
    FilterBar_SearchPlaceholder: 'कार्य खोजें…',
    FilterBar_SearchAriaLabel: 'कार्य खोजें',
    FilterBar_StatusChipLabel: 'स्थिति',
    FilterBar_PriorityChipLabel: 'प्राथमिकता',
    FilterBar_AssigneeChipLabel: 'नियुक्त व्यक्ति',
    FilterBar_PhaseChipLabel: 'चरण',
    FilterBar_DueDateAriaLabel: 'नियत तिथि के अनुसार फ़िल्टर करें',
    FilterBar_MatchCount: '{totalCount} में से {matchCount}',
    FilterBar_ClearFilters: '✕ फ़िल्टर साफ़ करें',
    FilterBar_ChipLabelWithCount: '{label} ({count}) ▾',
    FilterBar_ChipLabelNoCount: '{label} ▾',

    // ── Gantt view ──
    Gantt_TaskColumnHeader: 'कार्य',
    Gantt_DurationColumnHeader: 'अवधि',
    Gantt_AddTaskButton: '+ कार्य जोड़ें',
    Gantt_EmptyTitle: 'अभी तक कोई कार्य नहीं',
    Gantt_EmptySubtitle: 'गैंट चार्ट पर देखने के लिए कार्य जोड़ें।',
    Gantt_AddFirstTask: '+ पहला कार्य जोड़ें',
    Gantt_ImportTasksButton: '📥 कार्य आयात करें',
    Gantt_EditTitle: 'संपादित करें',
    Gantt_DeleteTitle: 'हटाएं',
    Gantt_EditTaskAriaLabel: 'कार्य {taskTitle} संपादित करें',
    Gantt_DeleteTaskAriaLabel: 'कार्य {taskTitle} हटाएं',
    Gantt_ExpandPhaseAriaLabel: 'चरण {phase} को {action} करें',
    Gantt_ExpandAction: 'विस्तार',
    Gantt_CollapseAction: 'संकुचित',
    Gantt_DependencyViolationTooltip: 'सभी निर्भरताएं पूर्ण होने से पहले शुरू हुआ',
    Gantt_MilestoneAriaLabel: '{taskTitle}, माइलस्टोन, {date}',
    Gantt_BarAriaLabel: '{taskTitle}, {startDate} से {dueDate} तक, {percent}% पूर्ण',
    Gantt_PercentCompleteTooltip: '{value}% पूर्ण',

    // ── Gantt options/settings panel ──
    GanttSettings_PanelHeader: '⚙ विकल्प',
    GanttSettings_ColorCodingSection: 'रंग कोडिंग',
    GanttSettings_ByStatus: 'स्थिति के अनुसार',
    GanttSettings_ByPriority: 'प्राथमिकता के अनुसार',
    GanttSettings_ByPhase: 'चरण के अनुसार',
    GanttSettings_ByHealth: 'स्वास्थ्य के अनुसार',
    GanttSettings_HeaderColorSection: 'हेडर रंग',
    GanttSettings_ThemeDark: 'डार्क',
    GanttSettings_ThemeNavy: 'नेवी',
    GanttSettings_ThemeTeal: 'टील',
    GanttSettings_ThemePurple: 'पर्पल',
    GanttSettings_ThemeLight: 'लाइट',
    GanttSettings_HeaderLabelsSection: 'हेडर लेबल',
    GanttSettings_WeekLabelDates: 'तिथियां',
    GanttSettings_WeekLabelDatesDesc: 'जून 3, जून 10…',
    GanttSettings_WeekLabelProject: 'प्रोजेक्ट सप्ताह',
    GanttSettings_WeekLabelProjectDesc: 'W1, W2…',
    GanttSettings_WeekLabelIso: 'कैलेंडर सप्ताह',
    GanttSettings_WeekLabelIsoDesc: 'W23, W24…',
    GanttSettings_ProjectWeeksHint: 'सप्ताह 1 आपके सबसे पहले कार्य के सोमवार से शुरू होता है — प्रस्तुतियों के लिए उत्तम।',
    GanttSettings_BarStyleSection: 'बार शैली',
    GanttSettings_BarStyleGradient: 'ग्रेडिएंट',
    GanttSettings_BarStyleFlat: 'फ्लैट',
    GanttSettings_RowHeightSection: 'पंक्ति ऊंचाई',
    GanttSettings_HeightCompact: 'कॉम्पैक्ट',
    GanttSettings_HeightNormal: 'सामान्य',
    GanttSettings_HeightSpacious: 'विस्तृत',
    GanttSettings_ShowHideSection: 'दिखाएं / छिपाएं',
    GanttSettings_WeekendShading: 'सप्ताहांत छायांकन',
    GanttSettings_DependencyArrows: 'निर्भरता तीर',
    GanttSettings_CriticalPathAlwaysVisible: 'महत्वपूर्ण पथ हमेशा दृश्यमान',
    GanttSettings_AllOthersOnHoverOnly: 'बाकी सभी केवल होवर पर',
    GanttSettings_CriticalPathHighlight: 'महत्वपूर्ण पथ हाइलाइट',
    GanttSettings_ProgressPercentOnBars: 'बार पर प्रगति %',
    GanttSettings_AssigneeNameOnBars: 'बार पर नियुक्त व्यक्ति का नाम',
    GanttSettings_HealthStatusBadges: 'स्वास्थ्य स्थिति बैज',

    // ── List view ──
    ListView_ColTaskName: 'कार्य का नाम',
    ListView_ColStatus: 'स्थिति',
    ListView_ColHealth: 'स्वास्थ्य',
    ListView_ColPriority: 'प्राथमिकता',
    ListView_ColStart: 'प्रारंभ',
    ListView_ColDue: 'नियत तिथि',
    ListView_ColAssignedTo: 'नियुक्त व्यक्ति',
    ListView_ColProgress: 'प्रगति',
    ListView_ColPhase: 'चरण',
    ListView_ColPredecessors: 'पूर्ववर्ती',
    ListView_EmptyTitle: 'अभी तक कोई कार्य नहीं',
    ListView_AddFirstTask: '+ पहला कार्य जोड़ें',
    ListView_AddTaskRow: '+ कार्य जोड़ें',
    ListView_Unassigned: 'अनियुक्त',
    ListView_DependencyViolationTooltip: 'सभी निर्भरताएं पूर्ण होने से पहले शुरू हुआ',
    ListView_StatusAriaLabel: '{taskTitle} की स्थिति',
    ListView_PriorityAriaLabel: '{taskTitle} की प्राथमिकता',
    ListView_EditTaskAriaLabel: 'कार्य {taskTitle} संपादित करें',
    ListView_DeleteTaskAriaLabel: 'कार्य {taskTitle} हटाएं',
    ListView_EditTitle: 'संपादित करें',
    ListView_DeleteTitle: 'हटाएं',

    // ── Kanban view ──
    Kanban_ColumnNotStarted: 'शुरू नहीं हुआ',
    Kanban_ColumnInProgress: 'प्रगति पर',
    Kanban_ColumnOnHold: 'होल्ड पर',
    Kanban_ColumnCompleted: 'पूर्ण',
    Kanban_ColumnCancelled: 'रद्द',
    Kanban_AddTaskButton: '+ कार्य जोड़ें',
    Kanban_EditTitle: 'संपादित करें',
    Kanban_DeleteTitle: 'हटाएं',
    Kanban_CardAriaLabel: '{taskTitle}, {status}। संपादित करने के लिए Enter दबाएं, स्थिति बदलने के लिए बाएं या दाएं तीर दबाएं।',
    Kanban_EditTaskAriaLabel: 'कार्य {taskTitle} संपादित करें',
    Kanban_DeleteTaskAriaLabel: 'कार्य {taskTitle} हटाएं',

    // ── Dashboard view ──
    Dashboard_TotalTasks: 'कुल कार्य',
    Dashboard_Completed: 'पूर्ण',
    Dashboard_InProgress: 'प्रगति पर',
    Dashboard_OnHold: 'होल्ड पर',
    Dashboard_NotStarted: 'शुरू नहीं हुआ',
    Dashboard_Cancelled: 'रद्द',
    Dashboard_OverallProgress: 'समग्र प्रगति',
    Dashboard_ProjectManagerLabel: 'प्रोजेक्ट प्रबंधक: {name}',
    Dashboard_PhaseProgressHeader: 'चरण प्रगति',
    Dashboard_StatusBreakdownHeader: 'स्थिति विवरण',
    Dashboard_PriorityBreakdownHeader: 'प्राथमिकता विवरण',
    Dashboard_PriorityCritical: 'गंभीर',
    Dashboard_PriorityHigh: 'उच्च',
    Dashboard_PriorityMedium: 'मध्यम',
    Dashboard_PriorityLow: 'निम्न',
    Dashboard_OverdueHeader: 'अतिदेय  ({count})',
    Dashboard_DueNext14DaysHeader: 'अगले 14 दिनों में नियत  ({count})',
    Dashboard_CompletedThisWeekHeader: 'इस सप्ताह पूर्ण',
    Dashboard_UpdatedThisWeekHeader: 'इस सप्ताह अपडेट किया गया',
    Dashboard_Today: 'आज',
    Dashboard_Tomorrow: 'कल',
    Dashboard_DaysLeft: '{days}दि',
    Dashboard_EmptyTitle: 'अभी तक कोई कार्य नहीं',
    Dashboard_EmptySubtitle: 'अपना प्रोजेक्ट डैशबोर्ड देखने के लिए कार्य जोड़ें।',
    Dashboard_AddTaskButton: '+ कार्य जोड़ें',

    // ── Portfolio view ──
    Portfolio_ProjectCount: '{count} प्रोजेक्ट{plural}',
    Portfolio_OnTrackSummary: '{count} ट्रैक पर',
    Portfolio_AtRiskSummary: '{count} जोखिम में',
    Portfolio_OverdueSummary: '{count} अतिदेय',
    Portfolio_DoneSummary: '{count} पूर्ण',
    Portfolio_SortLabel: 'क्रमबद्ध करें:',
    Portfolio_SortAZ: 'A-Z',
    Portfolio_SortHealth: 'स्वास्थ्य',
    Portfolio_SortStatus: 'स्थिति',
    Portfolio_SortCompletion: 'पूर्णता',
    Portfolio_RefreshTitle: 'ताज़ा करें',
    Portfolio_RefreshButton: 'ताज़ा करें',
    Portfolio_LoadingStats: 'आंकड़े लोड हो रहे हैं…',
    Portfolio_EmptyTitle: 'अभी तक कोई प्रोजेक्ट नहीं',
    Portfolio_CreateFirstProject: '+ पहला प्रोजेक्ट बनाएं',
    Portfolio_StatsUnavailable: 'आंकड़े अनुपलब्ध',
    Portfolio_StatsUnavailableDetail: 'इस प्रोजेक्ट के लिए आंकड़े लोड नहीं किए जा सके।',
    Portfolio_OverallProgressLabel: 'समग्र प्रगति',
    Portfolio_TaskCountDone: 'पूर्ण',
    Portfolio_TaskCountActive: 'सक्रिय',
    Portfolio_TaskCountAtRisk: 'जोखिम में',
    Portfolio_TaskCountOverdue: 'अतिदेय',
    Portfolio_ViewGanttLink: 'गैंट देखें →',
    Portfolio_TodayTooltip: 'आज',

    // ── Task panel ──
    TaskPanel_EditHeader: 'संपादित करें: {taskTitle}',
    TaskPanel_NewTaskHeader: 'नया कार्य',
    TaskPanel_TabBasic: 'मूल',
    TaskPanel_TabDetails: 'विवरण',
    TaskPanel_TabLinks: 'लिंक',
    TaskPanel_ProjectLabelPrefix: 'प्रोजेक्ट: ',
    TaskPanel_TaskNameLabel: 'कार्य का नाम',
    TaskPanel_TaskNamePlaceholder: 'कार्य का नाम दर्ज करें',
    TaskPanel_TaskNameRequired: 'कार्य का नाम आवश्यक है',
    TaskPanel_DescriptionLabel: 'विवरण',
    TaskPanel_DescriptionPlaceholder: 'विवरण दर्ज करें',
    TaskPanel_StartDateLabel: 'प्रारंभ तिथि',
    TaskPanel_DueDateLabel: 'नियत तिथि',
    TaskPanel_DueDateError: 'नियत तिथि प्रारंभ तिथि के बराबर या उसके बाद होनी चाहिए',
    TaskPanel_StatusLabel: 'स्थिति',
    TaskPanel_PriorityLabel: 'प्राथमिकता',
    TaskPanel_PercentCompleteLabel: '% पूर्ण: {percent}%',
    TaskPanel_AssignedToLabel: 'नियुक्त व्यक्ति',
    TaskPanel_AssignedToPlaceholder: 'लोगों को खोजें…',
    TaskPanel_PhaseLabel: 'चरण',
    TaskPanel_PhasePlaceholder: 'चरण का नाम दर्ज करें',
    TaskPanel_PhaseHint: 'गैंट और सूची दृश्यों में कार्यों को एक साथ समूहित करता है।',
    TaskPanel_MilestoneLabel: 'माइलस्टोन',
    TaskPanel_MilestoneOnText: 'हां',
    TaskPanel_MilestoneOffText: 'नहीं',
    TaskPanel_CustomBarColorLabel: 'कस्टम बार रंग',
    TaskPanel_CustomBarColorOptionalSuffix: ' (वैकल्पिक)',
    TaskPanel_AutoColorHint: 'स्थिति/प्राथमिकता/चरण सेटिंग्स से ऑटो रंग।',
    TaskPanel_NotesLabel: 'टिप्पणियां',
    TaskPanel_NotesPlaceholder: 'टिप्पणियां दर्ज करें',
    TaskPanel_ParentTaskLabel: 'मूल कार्य',
    TaskPanel_ParentTaskNone: '(कोई नहीं)',
    TaskPanel_ParentTaskHasChildrenHint: 'इस कार्य में उप-कार्य हैं और इसका अपना मूल कार्य नहीं हो सकता।',
    TaskPanel_ParentTaskHint: 'इस कार्य को उप-कार्य के रूप में किसी अन्य के अंतर्गत नेस्ट करें।',
    TaskPanel_DependsOnLabel: 'निर्भर करता है',
    TaskPanel_RemoveDependencyTitle: '"{taskTitle}" पर निर्भरता हटाएं',
    TaskPanel_AddDependencyPlaceholder: 'निर्भरता जोड़ें…',
    TaskPanel_SelectATaskOption: 'एक कार्य चुनें…',
    TaskPanel_DependsOnHint: 'जब तक ये पूर्ण नहीं हो जाते, कार्य शुरू नहीं हो सकता।',
    TaskPanel_SavingLabel: 'सहेजा जा रहा है…',
    TaskPanel_CreatingLabel: 'बनाया जा रहा है…',
    TaskPanel_SaveChangesButton: 'परिवर्तन सहेजें',
    TaskPanel_CreateTaskButton: 'कार्य बनाएं',
    TaskPanel_CancelButton: 'रद्द करें',
    TaskPanel_DismissAriaLabel: 'खारिज करें',
    TaskPanel_DiscardUnsavedChangesConfirm: 'असहेजे गए परिवर्तनों को त्यागें?',
    TaskPanel_SaveFallbackError: 'कार्य सहेजा नहीं जा सका।',

    // ── Project panel ──
    ProjectPanel_EditHeader: 'प्रोजेक्ट संपादित करें',
    ProjectPanel_NewHeader: 'नया प्रोजेक्ट',
    ProjectPanel_ProjectNameLabel: 'प्रोजेक्ट का नाम',
    ProjectPanel_ProjectNamePlaceholder: 'प्रोजेक्ट का नाम दर्ज करें',
    ProjectPanel_ProjectNameRequired: 'प्रोजेक्ट का नाम आवश्यक है',
    ProjectPanel_DescriptionLabel: 'विवरण',
    ProjectPanel_DescriptionPlaceholder: 'विवरण दर्ज करें',
    ProjectPanel_ProjectColorLabel: 'प्रोजेक्ट रंग',
    ProjectPanel_StatusLabel: 'स्थिति',
    ProjectPanel_StartDateLabel: 'प्रारंभ तिथि',
    ProjectPanel_DueDateLabel: 'नियत तिथि',
    ProjectPanel_DueDateError: 'नियत तिथि प्रारंभ तिथि के बराबर या उसके बाद होनी चाहिए',
    ProjectPanel_WhatHappensNextTitle: 'आगे क्या होगा?',
    ProjectPanel_WhatHappensNextBody: 'प्रोजेक्ट बनने के बाद आप कार्य जोड़ सकेंगे, चरण सेट कर सकेंगे और प्रगति को ट्रैक कर सकेंगे।',
    ProjectPanel_SavingLabel: 'सहेजा जा रहा है…',
    ProjectPanel_CreatingLabel: 'बनाया जा रहा है…',
    ProjectPanel_SaveChangesButton: 'परिवर्तन सहेजें',
    ProjectPanel_CreateProjectButton: 'प्रोजेक्ट बनाएं',
    ProjectPanel_CancelButton: 'रद्द करें',
    ProjectPanel_DismissAriaLabel: 'खारिज करें',
    ProjectPanel_DiscardUnsavedChangesConfirm: 'असहेजे गए परिवर्तनों को त्यागें?',
    ProjectPanel_SaveFallbackError: 'प्रोजेक्ट सहेजा नहीं जा सका।',

    // ── Import panel ──
    ImportPanel_SourceExcelTitle: 'Excel / CSV फ़ाइल',
    ImportPanel_SourceExcelSubtitle: 'स्प्रेडशीट से कार्य आयात करें',
    ImportPanel_SourcePlannerTitle: 'Microsoft Planner',
    ImportPanel_SourcePlannerSubtitle: 'Planner प्लान से कार्य आयात करें',
    ImportPanel_ClickToBrowse: 'ब्राउज़ करने के लिए क्लिक करें',
    ImportPanel_DragDropSuffix: ' या खींचें और छोड़ें',
    ImportPanel_SupportedExtensions: '.xlsx, .xls, .csv समर्थित हैं',
    ImportPanel_RowsColsSummary: '{rows} पंक्तियां, {cols} कॉलम पाए गए',
    ImportPanel_LoadingPlannerPlans: 'Planner प्लान लोड हो रहे हैं…',
    ImportPanel_PlannerLoadError: 'Planner प्लान लोड नहीं किए जा सके।',
    ImportPanel_PlannerPermissionsHintPrefix: 'सुनिश्चित करें कि आपके पास Planner तक पहुंच है और ',
    ImportPanel_PlannerPermissionsHintEmphasis: 'Tasks by Planner and To Do',
    ImportPanel_PlannerPermissionsHintSuffix: ' इस साइट के लिए उपलब्ध है।',
    ImportPanel_NoPlannerPlansFoundTitle: 'कोई Planner प्लान नहीं मिला',
    ImportPanel_NoPlannerPlansFoundBody: 'हो सकता है आपके पास किसी Planner प्लान तक पहुंच न हो, या इस खाते के लिए कोई मौजूद न हो।',
    ImportPanel_TaskCountFoundIn: '"{planName}" में {count} कार्य पाए गए',
    ImportPanel_ProjectDetailsIntroPrefix: 'इसमें आयात किया जा रहा है ',
    ImportPanel_ProjectDetailsIntroSuffix: '। नीचे प्रोजेक्ट का विवरण देखें।',
    ImportPanel_ProjectNameLabel: 'प्रोजेक्ट का नाम',
    ImportPanel_DescriptionLabel: 'विवरण',
    ImportPanel_StatusLabel: 'स्थिति',
    ImportPanel_ColorLabel: 'रंग',
    ImportPanel_MapIntro: 'अपनी फ़ाइल के कॉलम को कार्य फ़ील्ड से मैप करें।',
    ImportPanel_CreatingProjectStatus: 'प्रोजेक्ट बनाया जा रहा है…',
    ImportPanel_ImportingTasksStatus: 'कार्य आयात किए जा रहे हैं…',
    ImportPanel_ProgressLabel: '{total} में से {done}',
    ImportPanel_CouldNotCreateProject: 'प्रोजेक्ट नहीं बनाया जा सका।',
    ImportPanel_ImportCompletedWithErrors: 'आयात {count} त्रुटि(यों) के साथ पूर्ण हुआ।',
    ImportPanel_ProjectCreatedSuccess: 'प्रोजेक्ट सफलतापूर्वक बनाया गया!',
    ImportPanel_ImportSuccessful: 'आयात सफल हुआ!',
    ImportPanel_TasksAddedTo: '"{projectName}" में {count} कार्य जोड़े गए',
    ImportPanel_FailedRowsLabel: 'असफल पंक्तियां:',
    ImportPanel_CloseButton: 'बंद करें',
    ImportPanel_OpenProjectButton: 'प्रोजेक्ट खोलें',
    ImportPanel_ViewImportedTasksButton: 'आयातित कार्य देखें',
    ImportPanel_NextMapColumnsButton: 'अगला: कॉलम मैप करें',
    ImportPanel_ImportNTasksButton: '{count} कार्य आयात करें',
    ImportPanel_BackButton: 'पीछे',
    ImportPanel_CancelButton: 'रद्द करें',
    ImportPanel_NextButton: 'अगला',
    ImportPanel_StepSource: 'स्रोत',
    ImportPanel_StepProject: 'प्रोजेक्ट',
    ImportPanel_StepMap: 'मैप',
    ImportPanel_StepImport: 'आयात',
    ImportPanel_StepDone: 'पूर्ण',
    ImportPanel_ImportAsNewProjectHeader: 'फ़ाइल को नए प्रोजेक्ट के रूप में आयात करें',
    ImportPanel_ImportIntoProjectHeader: '{projectName} में कार्य आयात करें',
    ImportPanel_CouldNotParseFile: 'फ़ाइल को पार्स नहीं किया जा सका।',
    ImportPanel_CouldNotLoadPlannerTasks: 'इस प्लान से कार्य लोड नहीं किए जा सके।',
    ImportPanel_CouldNotCreateProjectDetail: 'प्रोजेक्ट नहीं बनाया जा सका: {detail}',
    ImportPanel_CouldNotLinkDependencies: 'निर्भरताएं लिंक नहीं की जा सकीं: {detail}',
    ImportPanel_UnknownError: 'अज्ञात त्रुटि',

    // ── Column mapper (import) ──
    ColumnMapper_TaskNameRequiredBanner: 'जारी रखने के लिए कार्य का नाम मैप किया जाना चाहिए।',
    ColumnMapper_SkippedColumnsBanner: '{count} कॉलम छोड़ दिए जाएंगे।',
    ColumnMapper_SourceColumnHeader: 'स्रोत कॉलम',
    ColumnMapper_TargetFieldHeader: 'लक्ष्य फ़ील्ड',
    ColumnMapper_StatusHeader: 'स्थिति',
    ColumnMapper_SkippedBadge: 'छोड़ा गया',
    ColumnMapper_AutoMappedBadge: 'ऑटो-मैप किया गया',
    ColumnMapper_SetBadge: 'सेट',
    ColumnMapper_PreviewTitle: 'पूर्वावलोकन: {columnName}',
    ColumnMapper_EmptyCellDash: '—',

    // ── Import field display names / ImportService ──
    ImportField_TaskName: 'कार्य का नाम',
    ImportField_StartDate: 'प्रारंभ तिथि',
    ImportField_DueDate: 'नियत तिथि',
    ImportField_Status: 'स्थिति',
    ImportField_Priority: 'प्राथमिकता',
    ImportField_AssignedTo: 'नियुक्त व्यक्ति',
    ImportField_AssignedToEmail: 'नियुक्त व्यक्ति का ईमेल',
    ImportField_PercentComplete: '% पूर्ण',
    ImportField_Phase: 'चरण',
    ImportField_Description: 'विवरण',
    ImportField_Notes: 'टिप्पणियां',
    ImportField_IsMilestone: 'माइलस्टोन है',
    ImportField_Dependencies: 'निर्भरताएं',
    ImportField_SkipColumn: '(इस कॉलम को छोड़ें)',
    ImportService_EmptyFileError: 'फ़ाइल खाली प्रतीत होती है या इसमें कोई डेटा पंक्तियां नहीं हैं।',
    ImportService_ReadErrorDetail: 'फ़ाइल नहीं पढ़ी जा सकी: {detail}।',
    ImportService_FileReadError: 'फ़ाइल पढ़ने में त्रुटि।',
    ImportService_RowError: 'पंक्ति {rowNum} ("{title}"): {error}',
    ImportService_AmbiguousDependency: 'निर्भरता "{name}" एक से अधिक कार्य शीर्षकों से मेल खाती है — छोड़ दी गई।',
    ImportService_LinkDependencyError: 'कार्य {taskId} के लिए निर्भरताएं लिंक नहीं की जा सकीं: {error}',

    // ── Health labels ──
    Health_Done: 'पूर्ण',
    Health_OnTrack: 'ट्रैक पर',
    Health_AtRisk: 'जोखिम में',
    Health_Overdue: 'अतिदेय',

    // ── Status / Priority display labels ──
    Status_NotStarted: 'शुरू नहीं हुआ',
    Status_InProgress: 'प्रगति पर',
    Status_Completed: 'पूर्ण',
    Status_OnHold: 'होल्ड पर',
    Status_Cancelled: 'रद्द',
    Priority_Critical: 'गंभीर',
    Priority_High: 'उच्च',
    Priority_Medium: 'मध्यम',
    Priority_Low: 'निम्न',
    ProjectStatus_Planning: 'योजना',
    ProjectStatus_Active: 'सक्रिय',
    ProjectStatus_OnHold: 'होल्ड पर',
    ProjectStatus_Completed: 'पूर्ण',
    ProjectStatus_Cancelled: 'रद्द',

    // ── Shell (SmartGantt.tsx) ──
    SmartGantt_LoadingProjects: 'प्रोजेक्ट लोड हो रहे हैं…',
    SmartGantt_UnableToLoad: 'लोड करने में असमर्थ',
    SmartGantt_RetryButton: 'पुनः प्रयास करें',
    SmartGantt_NoProjectsYet: 'अभी तक कोई प्रोजेक्ट नहीं',
    SmartGantt_NoProjectsSubtitle: 'शुरू करने के लिए अपना पहला प्रोजेक्ट बनाएं।',
    SmartGantt_CreateFirstProjectButton: '+ पहला प्रोजेक्ट बनाएं',
    SmartGantt_ImportFromExcelButton: '📥 Excel से आयात करें',
    SmartGantt_LoadingTasks: 'कार्य लोड हो रहे हैं…',
    SmartGantt_DismissAriaLabel: 'खारिज करें',
    SmartGantt_DeleteTaskDialogTitle: 'कार्य हटाएं',
    SmartGantt_DeleteTaskDialogSubtext: 'क्या आप वाकई "{taskTitle}" को हटाना चाहते हैं? इसे पूर्ववत नहीं किया जा सकता।',
    SmartGantt_DeleteButton: 'हटाएं',
    SmartGantt_CancelButton: 'रद्द करें',
    SmartGantt_ArchiveProjectDialogTitle: 'प्रोजेक्ट संग्रहीत करें',
    SmartGantt_ArchiveProjectDialogSubtext: '"{projectTitle}" को संग्रहीत करें? आप इसे बाद में अनआर्काइव कर सकते हैं।',
    SmartGantt_ArchiveButton: 'संग्रहीत करें',
    SmartGantt_SendToRecycleBinDialogTitle: 'रीसायकल बिन में भेजें',
    SmartGantt_SendToRecycleBinDialogSubtext: '"{projectTitle}" को साइट रीसायकल बिन में भेजें?',
    SmartGantt_SendToRecycleBinButton: 'रीसायकल बिन में भेजें',
    SmartGantt_FailedLoadProjects: 'प्रोजेक्ट लोड करने में विफल। साइट अनुमतियां जांचें।',
    SmartGantt_FailedLoadTasks: 'इस प्रोजेक्ट के लिए कार्य लोड करने में विफल।',
    SmartGantt_FailedLoadPortfolioStats: 'पोर्टफोलियो आंकड़े लोड करने में विफल।',
    SmartGantt_CouldNotSaveProject: 'प्रोजेक्ट सहेजा नहीं जा सका: {message}',
    SmartGantt_CouldNotDeleteProject: 'प्रोजेक्ट हटाया नहीं जा सका: {message}',
    SmartGantt_CouldNotArchiveProject: 'प्रोजेक्ट संग्रहीत नहीं किया जा सका: {message}',
    SmartGantt_CouldNotUnarchiveProject: 'प्रोजेक्ट अनआर्काइव नहीं किया जा सका: {message}',
    SmartGantt_CouldNotSaveTask: 'कार्य सहेजा नहीं जा सका: {message}',
    SmartGantt_CouldNotDeleteTask: 'कार्य हटाया नहीं जा सका: {message}',
    SmartGantt_ImageExportFailed: 'छवि निर्यात विफल हुआ: {message}',
    SmartGantt_PowerPointExportFailed: 'PowerPoint निर्यात विफल हुआ: {message}',
    SmartGantt_PortfolioExportFailed: 'पोर्टफोलियो निर्यात विफल हुआ: {message}',
    SmartGantt_CouldNotUpdateTask: 'कार्य अपडेट नहीं किया जा सका: {message}',

    // ── Common ──
    ColorSwatch_AutoColorAriaLabel: 'ऑटो रंग',
    ColorSwatch_CustomColorAriaLabel: 'कस्टम रंग',
    ColorSwatch_PickCustomColorTitle: 'एक कस्टम रंग चुनें',

    // ── Export (Excel / PowerPoint) ──
    Export_ColTaskName: 'कार्य का नाम',
    Export_ColPhase: 'चरण',
    Export_ColStartDate: 'प्रारंभ तिथि',
    Export_ColDueDate: 'नियत तिथि',
    Export_ColStatus: 'स्थिति',
    Export_ColPriority: 'प्राथमिकता',
    Export_ColAssignedTo: 'नियुक्त व्यक्ति',
    Export_ColAssignedToEmail: 'नियुक्त व्यक्ति का ईमेल',
    Export_ColPercentComplete: '% पूर्ण',
    Export_ColIsMilestone: 'माइलस्टोन है',
    Export_ColDescription: 'विवरण',
    Export_ColNotes: 'टिप्पणियां',
    Export_Yes: 'हां',
    Export_No: 'नहीं',
    Export_SheetNameTasks: 'कार्य',
    Export_ExcelFileSuffix: ' - कार्य.xlsx',
    Export_TaskNameColumnLabel: 'कार्य का नाम',
    Export_ExportedDateLabel: '{date} को निर्यात किया गया',
    Export_ProjectReportLabel: 'प्रोजेक्ट रिपोर्ट',
    Export_StatusLine: 'स्थिति: {status}',
    Export_DateRangeSeparator: ' से ',
    Export_ProjectManagerLine: 'प्रोजेक्ट प्रबंधक: {name}',
    Export_GeneratedDateLine: '{date} को जनरेट किया गया',
    Export_ProjectSummaryTitle: 'प्रोजेक्ट सारांश',
    Export_StatTotalTasks: 'कुल कार्य',
    Export_StatCompleted: 'पूर्ण',
    Export_StatInProgress: 'प्रगति पर',
    Export_StatOnHold: 'होल्ड पर',
    Export_StatNotStarted: 'शुरू नहीं हुआ',
    Export_OverallProgressLine: 'समग्र प्रगति',
    Export_OverallProgressPercent: '{percent}%',
    Export_StatusBreakdownTitle: 'स्थिति विवरण',
    Export_StatusBreakdownRow: '{status}: {count} ({percent}%)',
    Export_GanttTimelineTitle: 'गैंट टाइमलाइन',
    Export_SummaryRecentActivityTitle: 'हाल की गतिविधि',
    Export_ProjectOverviewLabel: 'प्रोजेक्ट अवलोकन',
    Export_DetailStatusLabel: 'स्थिति',
    Export_DetailStartDateLabel: 'प्रारंभ तिथि',
    Export_DetailDueDateLabel: 'नियत तिथि',
    Export_DetailProjectManagerLabel: 'प्रोजेक्ट प्रबंधक',
    Export_Past7DaysLabel: 'पिछले 7 दिन',
    Export_NoActivityMessage: 'कोई हाल की गतिविधि नहीं।',
    Export_CompletedThisWeekHeader: 'इस सप्ताह पूर्ण ({count})',
    Export_NewBadge: 'नया  ',
    Export_CompletedPercentLine: '{percent}% पूर्ण',
    Export_MoreItemsSuffix: '+ {count} और',
    Export_InProgressUpdatedHeader: 'प्रगति पर / अपडेट किया गया',
    Export_StatusPercentLine: '{status} — {percent}%',
    Export_PortfolioReportLabel: 'पोर्टफोलियो रिपोर्ट',
    Export_PortfolioOverviewTitle: 'पोर्टफोलियो अवलोकन',
    Export_ProjectsCountLine: '{count} प्रोजेक्ट',
    Export_HealthSummaryOnTrack: '{count} ट्रैक पर',
    Export_HealthSummaryAtRisk: '{count} जोखिम में',
    Export_HealthSummaryOverdue: '{count} अतिदेय',
    Export_ProjectsSummaryHeader: 'प्रोजेक्ट सारांश',
    Export_TableProject: 'प्रोजेक्ट',
    Export_TableStatus: 'स्थिति',
    Export_TableHealth: 'स्वास्थ्य',
    Export_TableTotal: 'कुल',
    Export_TableDone: 'पूर्ण',
    Export_TableActive: 'सक्रिय',
    Export_TableAtRisk: 'जोखिम में',
    Export_TableOverdue: 'अतिदेय',
    Export_TablePctDone: '% पूर्ण',
    Export_TableDueDate: 'नियत तिथि',
    Export_PortfolioSummaryFileName: 'पोर्टफोलियो सारांश.xlsx',
    Export_PortfolioReportFileName: 'पोर्टफोलियो रिपोर्ट.pptx',
    Export_ProjectReportFileName: '{projectName} रिपोर्ट.pptx',
    Export_UnavailableLabel: 'अनुपलब्ध',
    Export_SheetNamePortfolio: 'पोर्टफोलियो',
    Export_ColStart: 'प्रारंभ',
    Export_ColDue: 'नियत तिथि',
    Export_ImageGenerationFailed: 'छवि जनरेट नहीं की जा सकी — चार्ट छवि के रूप में निर्यात करने के लिए बहुत बड़ा हो सकता है।',
    Export_DrawingContextFailed: 'निर्यात के लिए ड्रॉइंग संदर्भ नहीं बनाया जा सका।',
    Export_SvgRenderFailed: 'SVG रेंडर विफल हुआ',

    // ── Added in v1.5 review ──
    Svc_TooManyDependencies: 'इस कार्य में सहेजने के लिए बहुत अधिक निर्भरताएं हैं (सीमा लगभग 60 है). कुछ हटाएं और पुनः प्रयास करें.',
    Svc_TaskChangedByOthers: 'लोड करने के बाद से इस कार्य को किसी और ने बदल दिया है. रीफ़्रेश करें और पुनः प्रयास करें.',
    Svc_ProjectChangedByOthers: 'खोलने के बाद से इस प्रोजेक्ट को किसी और ने बदल दिया है. रीफ़्रेश करें और पुनः प्रयास करें.',
    Svc_ColumnCreateFailed: 'नई कार्य सूची पर {count} कॉलम नहीं बनाए जा सके: {detail}',
    Svc_BaselineUnavailable: 'इस प्रोजेक्ट के लिए बेसलाइन उपलब्ध नहीं हैं क्योंकि बेसलाइन कॉलम जोड़े नहीं जा सके (सूची संपादित करने की अनुमति आवश्यक हो सकती है).',
    Svc_SubtaskReassignFailed: 'हटाने से पहले इस कार्य के उप-कार्यों को पुनः असाइन नहीं किया जा सका: {detail}',
    Svc_UnresolvedDependency: 'पंक्ति {row} ("{title}"): निर्भरता "{name}" का आयात किए गए किसी कार्य से मिलान नहीं हो सका.',
    Svc_SelfDependency: 'पंक्ति {row} ("{title}"): निर्भरता "{name}" स्वयं कार्य की ओर इंगित करती है और उसे छोड़ दिया गया.',
    Svc_ColId: 'आईडी',
    Svc_ColDependencies: 'निर्भरताएं',
    Svc_ColBaselineStart: 'बेसलाइन प्रारंभ',
    Svc_ColBaselineDue: 'बेसलाइन नियत तिथि',
    Svc_CsvFileSuffix: ' - Tasks.csv',
    Svc_IcsFileSuffix: ' - Milestones.ics',
    Svc_PortfolioCsvFileName: 'Portfolio Summary.csv',
    Svc_PP_DisplayGroup: 'डिफ़ॉल्ट',
    Svc_PP_DefaultView: 'डिफ़ॉल्ट दृश्य',
    Svc_PP_ViewGantt: 'गैंट',
    Svc_PP_ViewList: 'सूची',
    Svc_PP_ViewKanban: 'कानबन',
    Svc_PP_ViewDashboard: 'डैशबोर्ड',
    Svc_PP_ViewPortfolio: 'पोर्टफोलियो',
    Svc_PP_DefaultZoom: 'डिफ़ॉल्ट ज़ूम',
    Svc_PP_ZoomDay: 'दिन',
    Svc_PP_ZoomWeek: 'सप्ताह',
    Svc_PP_ZoomMonth: 'महीना',
    Svc_PP_ZoomQuarter: 'तिमाही',
    Svc_PP_CalendarGroup: 'कार्य कैलेंडर',
    Svc_PP_DaySun: 'रविवार कार्य दिवस है',
    Svc_PP_DayMon: 'सोमवार कार्य दिवस है',
    Svc_PP_DayTue: 'मंगलवार कार्य दिवस है',
    Svc_PP_DayWed: 'बुधवार कार्य दिवस है',
    Svc_PP_DayThu: 'गुरुवार कार्य दिवस है',
    Svc_PP_DayFri: 'शुक्रवार कार्य दिवस है',
    Svc_PP_DaySat: 'शनिवार कार्य दिवस है',
    Svc_PP_Holidays: 'अवकाश (गैर-कार्य तिथियां)',
    Svc_PP_HolidaysHint: 'प्रति पंक्ति एक तिथि, yyyy-MM-dd प्रारूप में (उदाहरण के लिए 2026-12-25).',
    Gantt_TimelineAriaLabel: 'कार्य टाइमलाइन',
    Gantt_DragLabel: '{start} → {end} ({days} दिन)',
    Gantt_KeyboardMoveAnnouncement: '{taskTitle}: {startDate} से {dueDate}',
    Gantt_KeyboardHint: 'कार्य खोलने के लिए Enter दबाएं. बाएं और दाएं तीर कुंजियां इसे एक कार्य दिवस से खिसकाती हैं. तीर कुंजियों के साथ Shift इसकी समाप्ति तिथि बदलता है.',
    Gantt_ParentCycleTooltip: 'यह कार्य अभिभावक और उप-कार्यों की एक चक्रीय शृंखला का हिस्सा है, इसलिए इसे शीर्ष स्तर पर दिखाया गया है',
    Gantt_CollapseAll: 'सभी चरण संकुचित करें',
    Gantt_ExpandAll: 'सभी चरण विस्तृत करें',
    Gantt_BaselineTooltip: 'बेसलाइन: {start} → {due}',
    Gantt_VarianceTooltip: 'समाप्ति विचलन: बेसलाइन की तुलना में {days} दिन',
    Gantt_LinkHandleTitle: 'निर्भरता बनाने के लिए किसी अन्य कार्य पर खींचें',
    Toolbar_FitToProject: 'फ़िट',
    Toolbar_FitToProjectTitle: 'पूरे प्रोजेक्ट के अनुसार ज़ूम करें',
    Toolbar_UndoTitle: 'पूर्ववत करें (Ctrl+Z)',
    Toolbar_RedoTitle: 'फिर से करें (Ctrl+Y)',
    Toolbar_ExportCsv: '📄 कार्यों को CSV में निर्यात करें',
    Toolbar_ExportIcs: '📅 माइलस्टोन निर्यात करें (iCal)',
    Toolbar_Print: '🖨 प्रिंट करें / PDF के रूप में सहेजें',
    Toolbar_SetBaseline: '📐 बेसलाइन सेट करें…',
    Toolbar_CopyLink: '🔗 लिंक कॉपी करें',
    Toolbar_CopyLinkTitle: 'इस दृश्य का लिंक कॉपी करें (प्रोजेक्ट, दृश्य, ज़ूम और फ़िल्टर)',
    App_UndoButton: 'पूर्ववत करें',
    App_Undone: 'परिवर्तन पूर्ववत किया गया.',
    App_Redone: 'परिवर्तन फिर से किया गया.',
    App_DependentsMovedOne: '1 आश्रित कार्य स्थानांतरित किया गया.',
    App_DependentsMovedMany: '{count} आश्रित कार्य स्थानांतरित किए गए.',
    App_TaskConflict: 'इस कार्य को किसी और ने बदल दिया है. नवीनतम कार्य पुनः लोड कर दिए गए हैं — उनकी समीक्षा करें और पुनः प्रयास करें.',
    App_DependencyCycle: 'यह लिंक एक चक्रीय निर्भरता बना देगा.',
    App_DependencyExists: 'ये कार्य पहले से जुड़े हुए हैं.',
    App_LinkCopied: 'लिंक क्लिपबोर्ड पर कॉपी किया गया.',
    App_LinkCopyFailed: 'लिंक कॉपी नहीं किया जा सका: {message}',
    App_PopupBlocked: 'प्रिंट विंडो अवरुद्ध कर दी गई. इस साइट के लिए पॉप-अप की अनुमति दें और पुनः प्रयास करें.',
    App_SetBaselineDialogTitle: 'बेसलाइन सेट करें',
    App_SetBaselineDialogSubtext: 'क्या सभी {count} कार्यों की वर्तमान प्रारंभ और नियत तिथियों को बेसलाइन के रूप में सहेजना है? कोई भी मौजूदा बेसलाइन बदल दी जाएगी.',
    App_SetBaselineButton: 'बेसलाइन सेट करें',
    App_BaselineSaved: 'बेसलाइन सहेजी गई.',
    App_BaselineFailed: 'बेसलाइन सहेजी नहीं जा सकी: {message}',
    App_CsvExportFailed: 'CSV निर्यात विफल: {message}',
    App_IcsExportFailed: 'कैलेंडर निर्यात विफल: {message}',
    App_BulkDeleteDialogTitle: 'कार्य हटाएं',
    App_BulkDeleteDialogSubtext: 'क्या आप वाकई {count} कार्य हटाना चाहते हैं? इसे पूर्ववत नहीं किया जा सकता.',
    Common_PeoplePicker_ClearAriaLabel: 'साफ़ करें',
    Common_PeoplePicker_DirectoryHeader: 'निर्देशिका में लोग',
    Common_PeoplePicker_EmailLabel: 'ईमेल (वैकल्पिक)',
    Common_PeoplePicker_EmailPlaceholder: 'name@company.com',
    Common_PeoplePicker_ExternalHint: 'निर्देशिका में नहीं है. फ़्री टेक्स्ट के रूप में सहेजा गया.',
    Common_PeoplePicker_InvalidEmail: 'कृपया मान्य ईमेल पता दर्ज करें.',
    Common_PeoplePicker_ListAriaLabel: 'लोगों के सुझाव',
    Common_PeoplePicker_RecentHeader: 'हाल ही में उपयोग किए गए',
    Common_PeoplePicker_ResultsAnnouncement: '{count} सुझाव उपलब्ध हैं',
    Common_PeoplePicker_Searching: 'खोज रहे हैं…',
    Common_PeoplePicker_UseExternal: '“{name}” का उपयोग करें (बाहरी / निर्देशिका में नहीं)',
    Import_Mapper_PreviewFirstRows: 'पूर्वावलोकन (पहली {count} पंक्तियां)',
    Import_Mapper_RequiredLegend: 'आवश्यक फ़ील्ड',
    Import_Mapper_RequiredMarkerLabel: 'आवश्यक',
    Import_Mapper_SelectAriaLabel: 'कॉलम {columnName} के लिए लक्ष्य फ़ील्ड',
    Import_Panel_DateOrderAuto: 'स्वतः पहचानें',
    Import_Panel_DateOrderDMY: 'दिन/माह/वर्ष (31/12/2026)',
    Import_Panel_DateOrderDetected: 'आपकी फ़ाइल से पहचाना गया: {order}.',
    Import_Panel_DateOrderHint: 'संख्याओं में लिखी तिथियों पर लागू होता है, जैसे 03/04/2026.',
    Import_Panel_DateOrderLabel: 'तिथि क्रम',
    Import_Panel_DateOrderMDY: 'माह/दिन/वर्ष (12/31/2026)',
    Import_Panel_DropZoneAriaLabel: 'आयात करने के लिए फ़ाइल चुनें. ब्राउज़ करने के लिए Enter दबाएं.',
    Import_Panel_DropZoneChangeAriaLabel: 'चयनित फ़ाइल {fileName}. दूसरी फ़ाइल चुनने के लिए Enter दबाएं.',
    Import_Panel_FailedCount: '{count} विफल',
    Import_Panel_NewProjectIntroMany: 'एक नया प्रोजेक्ट बनाया जाएगा और सभी {count} कार्य उसमें आयात किए जाएंगे. आयात के बाद आप कभी भी ये विवरण बदल सकते हैं.',
    Import_Panel_NewProjectIntroOne: 'एक नया प्रोजेक्ट बनाया जाएगा और {count} कार्य उसमें आयात किया जाएगा. आयात के बाद आप कभी भी ये विवरण बदल सकते हैं.',
    Import_Panel_PlanAriaLabel: '{planName}, {groupName}',
    Import_Panel_ProblemEndBeforeStart: 'नियत तिथि प्रारंभ तिथि से पहले है',
    Import_Panel_ProblemInvalidDueDate: 'नियत तिथि "{value}" मान्य तिथि नहीं है',
    Import_Panel_ProblemInvalidStartDate: 'प्रारंभ तिथि "{value}" मान्य तिथि नहीं है',
    Import_Panel_ProblemMissingTitle: 'कार्य का नाम गुम है',
    Import_Panel_ProgressLabelWithPercent: '{total} में से {done} ({percent}%)',
    Import_Panel_SkipInvalidRows: 'समस्या वाली पंक्तियां छोड़ें',
    Import_Panel_SuccessWithWarningsMany: '{count} चेतावनियों के साथ आयात सफल रहा.',
    Import_Panel_SuccessWithWarningsOne: '{count} चेतावनी के साथ आयात सफल रहा.',
    Import_Panel_ValidationHeader: 'समस्या वाली पंक्तियां',
    Import_Panel_ValidationMore: '…और {count} अन्य',
    Import_Panel_ValidationRow: 'पंक्ति {rowNum}: {problem}',
    Import_Panel_ValidationSummaryMany: '{count} पंक्तियों में समस्याएं हैं',
    Import_Panel_ValidationSummaryOne: '{count} पंक्ति में समस्या है',
    Import_Panel_WarningsLabel: 'चेतावनियां ({count}):',
    Panel_Project_ManagerLabel: 'प्रोजेक्ट मैनेजर',
    Panel_Project_ManagerPlaceholder: 'लोगों को खोजें या नाम टाइप करें…',
    Panel_Task_BaselineDueLabel: 'बेसलाइन समाप्ति',
    Panel_Task_BaselineHeader: 'बेसलाइन',
    Panel_Task_BaselineStartLabel: 'बेसलाइन प्रारंभ',
    Panel_Task_DepTypeFF: 'समाप्ति से समाप्ति (FF)',
    Panel_Task_DepTypeFS: 'समाप्ति से प्रारंभ (FS)',
    Panel_Task_DepTypeSF: 'प्रारंभ से समाप्ति (SF)',
    Panel_Task_DepTypeSS: 'प्रारंभ से प्रारंभ (SS)',
    Panel_Task_LagAriaLabel: '{taskTitle} के लिए कार्य दिवसों में विलंब',
    Panel_Task_LagHint: 'विलंब कार्य दिवसों में है. लीड टाइम के लिए ऋणात्मक संख्या का उपयोग करें.',
    Panel_Task_LinkTypeAriaLabel: '{taskTitle} के लिए लिंक प्रकार',
    Panel_Task_VarianceEarlier: '{days} कार्य दिवस पहले',
    Panel_Task_VarianceLater: '{days} कार्य दिवस बाद',
    Panel_Task_VarianceOnBaseline: 'बेसलाइन के अनुसार',
    View_Dashboard_BurndownActual: 'वास्तविक',
    View_Dashboard_BurndownAria: 'बर्नडाउन चार्ट: {total} में से {remaining} कार्य शेष',
    View_Dashboard_BurndownHeader: 'बर्नडाउन (शेष कार्य)',
    View_Dashboard_BurndownIdeal: 'आदर्श',
    View_Dashboard_BurndownNoData: 'बर्नडाउन बनाने के लिए पर्याप्त तिथि वाले कार्य नहीं हैं.',
    View_Dashboard_CriticalPathHeader: 'क्रिटिकल पाथ  ({count})',
    View_Dashboard_PhaseDoneSummary: '{done}/{total} पूर्ण  •  {percent}%',
    View_Dashboard_TaskRowAriaLabel: 'कार्य {taskTitle} खोलें, {status}',
    View_Dashboard_WorkloadHeader: 'असाइनी के अनुसार कार्यभार',
    View_Dashboard_WorkloadOpen: '{count} खुले',
    View_Dashboard_WorkloadOverdue: '{count} विलंबित',
    View_Kanban_AddTaskInColumnAriaLabel: '{column} में कार्य जोड़ें',
    View_Kanban_CollapseColumn: '{column} कॉलम संकुचित करें',
    View_Kanban_ExpandColumn: '{column} कॉलम विस्तृत करें',
    View_Kanban_LaneHeader: '{name} ({count})',
    View_Kanban_LaneNoPhase: 'कोई चरण नहीं',
    View_Kanban_LaneUnassigned: 'असाइन नहीं किया गया',
    View_Kanban_LanesAssignee: 'नियुक्त व्यक्ति',
    View_Kanban_LanesNone: 'कोई नहीं',
    View_Kanban_LanesPhase: 'चरण',
    View_Kanban_SwimlanesLabel: 'स्विमलेन',
    View_Kanban_WipEditTitle: '{column} के लिए कार्य-प्रगति सीमा सेट करें (कोई सीमा नहीं के लिए 0)',
    View_Kanban_WipExceededTitle: 'WIP सीमा पार हो गई: {limit} में से {count}',
    View_Kanban_WipInputAriaLabel: '{column} के लिए WIP सीमा',
    View_Kanban_WipLabel: 'WIP {count}/{limit}',
    View_Kanban_WipSet: 'WIP',
    View_List_BulkAssignApply: 'असाइन करें',
    View_List_BulkAssigneePlaceholder: 'इन्हें असाइन करें…',
    View_List_BulkBarAriaLabel: 'चयनित कार्यों के लिए सामूहिक कार्रवाइयां',
    View_List_BulkClear: 'चयन साफ़ करें',
    View_List_BulkDelete: 'चयनित हटाएं',
    View_List_BulkPercentApply: '% सेट करें',
    View_List_BulkPercentPlaceholder: '% पूर्ण',
    View_List_BulkPriorityPlaceholder: 'प्राथमिकता सेट करें…',
    View_List_BulkSelectedCount: '{count} चयनित',
    View_List_BulkStatusPlaceholder: 'स्थिति सेट करें…',
    View_List_ExportCsv: 'CSV निर्यात करें',
    View_List_NonWorkingDay: 'गैर-कार्य दिवस',
    View_List_SelectAllAriaLabel: 'सभी कार्य चुनें',
    View_List_SelectRowAriaLabel: '{taskTitle} चुनें',
    View_Portfolio_CardAriaLabel: 'प्रोजेक्ट {projectName} खोलें, {status}',
    View_Portfolio_ClearFilters: 'फ़िल्टर साफ़ करें',
    View_Portfolio_FilteredCount: '{total} में से {shown} प्रोजेक्ट',
    View_Portfolio_HideDone: 'पूर्ण / रद्द छिपाएं',
    View_Portfolio_NoMatches: 'कोई प्रोजेक्ट आपके फ़िल्टर से मेल नहीं खाता.',
    View_Portfolio_ProjectCountMany: '{count} प्रोजेक्ट',
    View_Portfolio_ProjectCountOne: '{count} प्रोजेक्ट',
    View_Portfolio_SearchAriaLabel: 'प्रोजेक्ट खोजें',
    View_Portfolio_SearchPlaceholder: 'प्रोजेक्ट खोजें…',
    Import_Panel_CopyDetails: 'विवरण कॉपी करें',
    Import_Panel_Copied: 'कॉपी किया गया',
  };
});
