define([], function () {
  return {
    // ── Property pane ──
    PropertyPane_HeaderDescription: 'Smart Gantt diagram beállításai',
    PropertyPane_GeneralGroupName: 'Általános',
    PropertyPane_TitleFieldLabel: 'Webrész címe',
    WebPart_DefaultTitle: 'Smart Gantt diagram',

    // ── Toolbar ──
    Toolbar_ViewDashboard: 'Vezérlőpult',
    Toolbar_ViewList: 'Lista',
    Toolbar_ViewGantt: 'Gantt',
    Toolbar_ViewKanban: 'Kanban',
    Toolbar_ZoomDay: 'Nap',
    Toolbar_ZoomWeek: 'Hét',
    Toolbar_ZoomMonth: 'Hónap',
    Toolbar_ZoomQuarter: 'Negyedév',
    Toolbar_SelectProjectAriaLabel: 'Projekt kiválasztása',
    Toolbar_PortfolioLabel: 'Portfólió',
    Toolbar_SelectAProject: 'Válasszon projektet',
    Toolbar_AllProjectsSubtext: 'Összes projekt',
    Toolbar_NoProjectsYet: 'Még nincsenek projektek',
    Toolbar_ArchivedBadge: 'Archiválva',
    Toolbar_ShowArchivedProjects: 'Archivált projektek megjelenítése',
    Toolbar_NewProject: '+ Új projekt',
    Toolbar_ImportFileAsNewProject: '📥 Fájl importálása új projektként…',
    Toolbar_AddTask: '+ Feladat hozzáadása',
    Toolbar_EditProject: 'Projekt szerkesztése',
    Toolbar_OptionsButton: '⚙ Beállítások',
    Toolbar_MoreOptionsTitle: 'További beállítások',
    Toolbar_ExportToExcel: '📊 Exportálás Excelbe',
    Toolbar_ExportToPowerPoint: '📑 Exportálás PowerPointba',
    Toolbar_ScrollToTodayTitle: 'Görgetés a mai napra',
    Toolbar_TodayButton: '◉ Ma',
    Toolbar_ImportTasks: '📥 Feladatok importálása…',
    Toolbar_ExportAsImage: '🖼 Exportálás képként (PNG)',
    Toolbar_UnarchiveProject: '📂 Projekt visszaállítása archívumból',
    Toolbar_ArchiveProject: '🗄️ Projekt archiválása',
    Toolbar_SendToRecycleBin: '🗑️ Áthelyezés a lomtárba',

    // ── Filter bar ──
    FilterBar_ClearOption: 'Törlés',
    FilterBar_DueAny: 'Bármely határidő',
    FilterBar_DueOverdue: 'Lejárt',
    FilterBar_DueToday: 'Ma esedékes',
    FilterBar_DueWeek: '7 napon belül esedékes',
    FilterBar_SearchPlaceholder: 'Feladatok keresése…',
    FilterBar_SearchAriaLabel: 'Feladatok keresése',
    FilterBar_StatusChipLabel: 'Állapot',
    FilterBar_PriorityChipLabel: 'Prioritás',
    FilterBar_AssigneeChipLabel: 'Felelős',
    FilterBar_PhaseChipLabel: 'Fázis',
    FilterBar_DueDateAriaLabel: 'Szűrés határidő szerint',
    FilterBar_MatchCount: '{matchCount} / {totalCount}',
    FilterBar_ClearFilters: '✕ Szűrők törlése',
    FilterBar_ChipLabelWithCount: '{label} ({count}) ▾',
    FilterBar_ChipLabelNoCount: '{label} ▾',

    // ── Gantt view ──
    Gantt_TaskColumnHeader: 'Feladat',
    Gantt_DurationColumnHeader: 'Időtartam',
    Gantt_AddTaskButton: '+ Feladat hozzáadása',
    Gantt_EmptyTitle: 'Még nincsenek feladatok',
    Gantt_EmptySubtitle: 'Adjon hozzá feladatokat, hogy megjelenjenek a Gantt-diagramon.',
    Gantt_AddFirstTask: '+ Első feladat hozzáadása',
    Gantt_ImportTasksButton: '📥 Feladatok importálása',
    Gantt_EditTitle: 'Szerkesztés',
    Gantt_DeleteTitle: 'Törlés',
    Gantt_EditTaskAriaLabel: '{taskTitle} feladat szerkesztése',
    Gantt_DeleteTaskAriaLabel: '{taskTitle} feladat törlése',
    Gantt_ExpandPhaseAriaLabel: '{phase} fázis {action}',
    Gantt_ExpandAction: 'kibontása',
    Gantt_CollapseAction: 'összecsukása',
    Gantt_DependencyViolationTooltip: 'Elindult, mielőtt minden függőség befejeződött volna',
    Gantt_MilestoneAriaLabel: '{taskTitle}, mérföldkő, {date}',
    Gantt_BarAriaLabel: '{taskTitle}, {startDate} – {dueDate}, {percent}% kész',
    Gantt_PercentCompleteTooltip: '{value}% kész',

    // ── Gantt options/settings panel ──
    GanttSettings_PanelHeader: '⚙ Beállítások',
    GanttSettings_ColorCodingSection: 'Színkódolás',
    GanttSettings_ByStatus: 'Állapot szerint',
    GanttSettings_ByPriority: 'Prioritás szerint',
    GanttSettings_ByPhase: 'Fázis szerint',
    GanttSettings_ByHealth: 'Állapotjelző szerint',
    GanttSettings_HeaderColorSection: 'Fejléc színe',
    GanttSettings_ThemeDark: 'Sötét',
    GanttSettings_ThemeNavy: 'Tengerészkék',
    GanttSettings_ThemeTeal: 'Türkiz',
    GanttSettings_ThemePurple: 'Lila',
    GanttSettings_ThemeLight: 'Világos',
    GanttSettings_HeaderLabelsSection: 'Fejlécfeliratok',
    GanttSettings_WeekLabelDates: 'Dátumok',
    GanttSettings_WeekLabelDatesDesc: 'jún. 3., jún. 10…',
    GanttSettings_WeekLabelProject: 'Projekthetek',
    GanttSettings_WeekLabelProjectDesc: '1. hét, 2. hét…',
    GanttSettings_WeekLabelIso: 'Naptári hetek',
    GanttSettings_WeekLabelIsoDesc: '23. hét, 24. hét…',
    GanttSettings_ProjectWeeksHint: 'Az 1. hét a legkorábbi feladat hétfőjével kezdődik – ideális prezentációkhoz.',
    GanttSettings_BarStyleSection: 'Sáv stílusa',
    GanttSettings_BarStyleGradient: 'Színátmenet',
    GanttSettings_BarStyleFlat: 'Egyszínű',
    GanttSettings_RowHeightSection: 'Sormagasság',
    GanttSettings_HeightCompact: 'Kompakt',
    GanttSettings_HeightNormal: 'Normál',
    GanttSettings_HeightSpacious: 'Bőséges',
    GanttSettings_ShowHideSection: 'Megjelenítés / elrejtés',
    GanttSettings_WeekendShading: 'Hétvégék kiemelése',
    GanttSettings_DependencyArrows: 'Függőségi nyilak',
    GanttSettings_CriticalPathAlwaysVisible: 'A kritikus út mindig látható',
    GanttSettings_AllOthersOnHoverOnly: 'Minden más csak rámutatáskor',
    GanttSettings_CriticalPathHighlight: 'Kritikus út kiemelése',
    GanttSettings_ProgressPercentOnBars: 'Előrehaladás % a sávokon',
    GanttSettings_AssigneeNameOnBars: 'Felelős neve a sávokon',
    GanttSettings_HealthStatusBadges: 'Állapotjelző jelvények',

    // ── List view ──
    ListView_ColTaskName: 'Feladat neve',
    ListView_ColStatus: 'Állapot',
    ListView_ColHealth: 'Állapotjelző',
    ListView_ColPriority: 'Prioritás',
    ListView_ColStart: 'Kezdés',
    ListView_ColDue: 'Határidő',
    ListView_ColAssignedTo: 'Felelős',
    ListView_ColProgress: 'Előrehaladás',
    ListView_ColPhase: 'Fázis',
    ListView_ColPredecessors: 'Előzmények',
    ListView_EmptyTitle: 'Még nincsenek feladatok',
    ListView_AddFirstTask: '+ Első feladat hozzáadása',
    ListView_AddTaskRow: '+ Feladat hozzáadása',
    ListView_Unassigned: 'Nincs hozzárendelve',
    ListView_DependencyViolationTooltip: 'Elindult, mielőtt minden függőség befejeződött volna',
    ListView_StatusAriaLabel: '{taskTitle} állapota',
    ListView_PriorityAriaLabel: '{taskTitle} prioritása',
    ListView_EditTaskAriaLabel: '{taskTitle} feladat szerkesztése',
    ListView_DeleteTaskAriaLabel: '{taskTitle} feladat törlése',
    ListView_EditTitle: 'Szerkesztés',
    ListView_DeleteTitle: 'Törlés',

    // ── Kanban view ──
    Kanban_ColumnNotStarted: 'Nem kezdődött el',
    Kanban_ColumnInProgress: 'Folyamatban',
    Kanban_ColumnOnHold: 'Felfüggesztve',
    Kanban_ColumnCompleted: 'Befejezve',
    Kanban_ColumnCancelled: 'Törölve',
    Kanban_AddTaskButton: '+ Feladat hozzáadása',
    Kanban_EditTitle: 'Szerkesztés',
    Kanban_DeleteTitle: 'Törlés',
    Kanban_CardAriaLabel: '{taskTitle}, {status}. Nyomja meg az Enter billentyűt a szerkesztéshez, a bal vagy jobb nyilat az állapot módosításához.',
    Kanban_EditTaskAriaLabel: '{taskTitle} feladat szerkesztése',
    Kanban_DeleteTaskAriaLabel: '{taskTitle} feladat törlése',

    // ── Dashboard view ──
    Dashboard_TotalTasks: 'Feladatok összesen',
    Dashboard_Completed: 'Befejezve',
    Dashboard_InProgress: 'Folyamatban',
    Dashboard_OnHold: 'Felfüggesztve',
    Dashboard_NotStarted: 'Nem kezdődött el',
    Dashboard_Cancelled: 'Törölve',
    Dashboard_OverallProgress: 'Összesített előrehaladás',
    Dashboard_ProjectManagerLabel: 'Projektvezető: {name}',
    Dashboard_PhaseProgressHeader: 'Fázisok előrehaladása',
    Dashboard_StatusBreakdownHeader: 'Állapot szerinti bontás',
    Dashboard_PriorityBreakdownHeader: 'Prioritás szerinti bontás',
    Dashboard_PriorityCritical: 'Kritikus',
    Dashboard_PriorityHigh: 'Magas',
    Dashboard_PriorityMedium: 'Közepes',
    Dashboard_PriorityLow: 'Alacsony',
    Dashboard_OverdueHeader: 'Lejárt  ({count})',
    Dashboard_DueNext14DaysHeader: 'Következő 14 napban esedékes  ({count})',
    Dashboard_CompletedThisWeekHeader: 'E héten befejezve',
    Dashboard_UpdatedThisWeekHeader: 'E héten frissítve',
    Dashboard_Today: 'Ma',
    Dashboard_Tomorrow: 'Holnap',
    Dashboard_DaysLeft: '{days} nap',
    Dashboard_EmptyTitle: 'Még nincsenek feladatok',
    Dashboard_EmptySubtitle: 'Adjon hozzá feladatokat a projekt vezérlőpultjának megtekintéséhez.',
    Dashboard_AddTaskButton: '+ Feladat hozzáadása',

    // ── Portfolio view ──
    Portfolio_ProjectCount: '{count} projekt',
    Portfolio_OnTrackSummary: '{count} ütemben',
    Portfolio_AtRiskSummary: '{count} kockázatos',
    Portfolio_OverdueSummary: '{count} lejárt',
    Portfolio_DoneSummary: '{count} kész',
    Portfolio_SortLabel: 'Rendezés:',
    Portfolio_SortAZ: 'A–Z',
    Portfolio_SortHealth: 'Állapotjelző',
    Portfolio_SortStatus: 'Állapot',
    Portfolio_SortCompletion: 'Készültség',
    Portfolio_RefreshTitle: 'Frissítés',
    Portfolio_RefreshButton: 'Frissítés',
    Portfolio_LoadingStats: 'Statisztikák betöltése…',
    Portfolio_EmptyTitle: 'Még nincsenek projektek',
    Portfolio_CreateFirstProject: '+ Első projekt létrehozása',
    Portfolio_StatsUnavailable: 'A statisztikák nem érhetők el',
    Portfolio_StatsUnavailableDetail: 'Nem sikerült betölteni a projekt statisztikáit.',
    Portfolio_OverallProgressLabel: 'Összesített előrehaladás',
    Portfolio_TaskCountDone: 'Kész',
    Portfolio_TaskCountActive: 'Aktív',
    Portfolio_TaskCountAtRisk: 'Kockázatos',
    Portfolio_TaskCountOverdue: 'Lejárt',
    Portfolio_ViewGanttLink: 'Gantt megtekintése →',
    Portfolio_TodayTooltip: 'Ma',

    // ── Task panel ──
    TaskPanel_EditHeader: 'Szerkesztés: {taskTitle}',
    TaskPanel_NewTaskHeader: 'Új feladat',
    TaskPanel_TabBasic: 'Alapadatok',
    TaskPanel_TabDetails: 'Részletek',
    TaskPanel_TabLinks: 'Kapcsolatok',
    TaskPanel_ProjectLabelPrefix: 'Projekt: ',
    TaskPanel_TaskNameLabel: 'Feladat neve',
    TaskPanel_TaskNamePlaceholder: 'Adja meg a feladat nevét',
    TaskPanel_TaskNameRequired: 'A feladat neve kötelező',
    TaskPanel_DescriptionLabel: 'Leírás',
    TaskPanel_DescriptionPlaceholder: 'Adja meg a leírást',
    TaskPanel_StartDateLabel: 'Kezdés dátuma',
    TaskPanel_DueDateLabel: 'Határidő',
    TaskPanel_DueDateError: 'A határidőnek a kezdés dátumával megegyezőnek vagy annál későbbinek kell lennie',
    TaskPanel_StatusLabel: 'Állapot',
    TaskPanel_PriorityLabel: 'Prioritás',
    TaskPanel_PercentCompleteLabel: 'Készültség: {percent}%',
    TaskPanel_AssignedToLabel: 'Felelős',
    TaskPanel_AssignedToPlaceholder: 'Személyek keresése…',
    TaskPanel_PhaseLabel: 'Fázis',
    TaskPanel_PhasePlaceholder: 'Adja meg a fázis nevét',
    TaskPanel_PhaseHint: 'Csoportosítja a feladatokat a Gantt- és a Lista nézetben.',
    TaskPanel_MilestoneLabel: 'Mérföldkő',
    TaskPanel_MilestoneOnText: 'Igen',
    TaskPanel_MilestoneOffText: 'Nem',
    TaskPanel_CustomBarColorLabel: 'Egyéni sávszín',
    TaskPanel_CustomBarColorOptionalSuffix: ' (nem kötelező)',
    TaskPanel_AutoColorHint: 'Automatikus szín az állapot/prioritás/fázis beállításai alapján.',
    TaskPanel_NotesLabel: 'Megjegyzések',
    TaskPanel_NotesPlaceholder: 'Adja meg a megjegyzéseket',
    TaskPanel_ParentTaskLabel: 'Szülőfeladat',
    TaskPanel_ParentTaskNone: '(nincs)',
    TaskPanel_ParentTaskHasChildrenHint: 'Ennek a feladatnak alfeladatai vannak, ezért nem lehet saját szülője.',
    TaskPanel_ParentTaskHint: 'Ágyazza be ezt a feladatot egy másik alá alfeladatként.',
    TaskPanel_DependsOnLabel: 'Függ ettől',
    TaskPanel_RemoveDependencyTitle: 'Függőség eltávolítása erről: „{taskTitle}”',
    TaskPanel_AddDependencyPlaceholder: 'Függőség hozzáadása…',
    TaskPanel_SelectATaskOption: 'Válasszon feladatot…',
    TaskPanel_DependsOnHint: 'A feladat csak akkor kezdhető el, ha ezek befejeződtek.',
    TaskPanel_SavingLabel: 'Mentés…',
    TaskPanel_CreatingLabel: 'Létrehozás…',
    TaskPanel_SaveChangesButton: 'Módosítások mentése',
    TaskPanel_CreateTaskButton: 'Feladat létrehozása',
    TaskPanel_CancelButton: 'Mégse',
    TaskPanel_DismissAriaLabel: 'Bezárás',
    TaskPanel_DiscardUnsavedChangesConfirm: 'Elveti a nem mentett módosításokat?',
    TaskPanel_SaveFallbackError: 'Nem sikerült menteni a feladatot.',

    // ── Project panel ──
    ProjectPanel_EditHeader: 'Projekt szerkesztése',
    ProjectPanel_NewHeader: 'Új projekt',
    ProjectPanel_ProjectNameLabel: 'Projekt neve',
    ProjectPanel_ProjectNamePlaceholder: 'Adja meg a projekt nevét',
    ProjectPanel_ProjectNameRequired: 'A projekt neve kötelező',
    ProjectPanel_DescriptionLabel: 'Leírás',
    ProjectPanel_DescriptionPlaceholder: 'Adja meg a leírást',
    ProjectPanel_ProjectColorLabel: 'Projekt színe',
    ProjectPanel_StatusLabel: 'Állapot',
    ProjectPanel_StartDateLabel: 'Kezdés dátuma',
    ProjectPanel_DueDateLabel: 'Határidő',
    ProjectPanel_DueDateError: 'A határidőnek a kezdés dátumával megegyezőnek vagy annál későbbinek kell lennie',
    ProjectPanel_WhatHappensNextTitle: 'Mi történik ezután?',
    ProjectPanel_WhatHappensNextBody: 'A projekt létrehozása után hozzáadhat feladatokat, beállíthat fázisokat, és nyomon követheti az előrehaladást.',
    ProjectPanel_SavingLabel: 'Mentés…',
    ProjectPanel_CreatingLabel: 'Létrehozás…',
    ProjectPanel_SaveChangesButton: 'Módosítások mentése',
    ProjectPanel_CreateProjectButton: 'Projekt létrehozása',
    ProjectPanel_CancelButton: 'Mégse',
    ProjectPanel_DismissAriaLabel: 'Bezárás',
    ProjectPanel_DiscardUnsavedChangesConfirm: 'Elveti a nem mentett módosításokat?',
    ProjectPanel_SaveFallbackError: 'Nem sikerült menteni a projektet.',

    // ── Import panel ──
    ImportPanel_SourceExcelTitle: 'Excel / CSV fájl',
    ImportPanel_SourceExcelSubtitle: 'Feladatok importálása egy táblázatból',
    ImportPanel_SourcePlannerTitle: 'Microsoft Planner',
    ImportPanel_SourcePlannerSubtitle: 'Feladatok importálása egy Planner tervből',
    ImportPanel_ClickToBrowse: 'Kattintson a tallózáshoz',
    ImportPanel_DragDropSuffix: ' vagy húzza ide',
    ImportPanel_SupportedExtensions: 'Támogatott formátumok: .xlsx, .xls, .csv',
    ImportPanel_RowsColsSummary: '{rows} sor, {cols} oszlop található',
    ImportPanel_LoadingPlannerPlans: 'Planner tervek betöltése…',
    ImportPanel_PlannerLoadError: 'Nem sikerült betölteni a Planner terveket.',
    ImportPanel_PlannerPermissionsHintPrefix: 'Győződjön meg arról, hogy hozzáférése van a Plannerhez, és hogy a ',
    ImportPanel_PlannerPermissionsHintEmphasis: 'Tasks by Planner and To Do',
    ImportPanel_PlannerPermissionsHintSuffix: ' elérhető ezen a webhelyen.',
    ImportPanel_NoPlannerPlansFoundTitle: 'Nem található Planner terv',
    ImportPanel_NoPlannerPlansFoundBody: 'Lehet, hogy nincs hozzáférése egyetlen Planner tervhez sem, vagy ehhez a fiókhoz nem tartozik egy sem.',
    ImportPanel_TaskCountFoundIn: '{count} feladat található itt: „{planName}”',
    ImportPanel_ProjectDetailsIntroPrefix: 'Importálás ide: ',
    ImportPanel_ProjectDetailsIntroSuffix: '. Tekintse át a projekt adatait alább.',
    ImportPanel_ProjectNameLabel: 'Projekt neve',
    ImportPanel_DescriptionLabel: 'Leírás',
    ImportPanel_StatusLabel: 'Állapot',
    ImportPanel_ColorLabel: 'Szín',
    ImportPanel_MapIntro: 'Rendelje hozzá a fájl oszlopait a feladat mezőihez.',
    ImportPanel_CreatingProjectStatus: 'Projekt létrehozása…',
    ImportPanel_ImportingTasksStatus: 'Feladatok importálása…',
    ImportPanel_ProgressLabel: '{done} / {total}',
    ImportPanel_CouldNotCreateProject: 'Nem sikerült létrehozni a projektet.',
    ImportPanel_ImportCompletedWithErrors: 'Az importálás {count} hibával fejeződött be.',
    ImportPanel_ProjectCreatedSuccess: 'A projekt sikeresen létrejött!',
    ImportPanel_ImportSuccessful: 'Az importálás sikeres volt!',
    ImportPanel_TasksAddedTo: '{count} feladat hozzáadva ehhez: „{projectName}”',
    ImportPanel_FailedRowsLabel: 'Sikertelen sorok:',
    ImportPanel_CloseButton: 'Bezárás',
    ImportPanel_OpenProjectButton: 'Projekt megnyitása',
    ImportPanel_ViewImportedTasksButton: 'Importált feladatok megtekintése',
    ImportPanel_NextMapColumnsButton: 'Következő: Oszlopok hozzárendelése',
    ImportPanel_ImportNTasksButton: '{count} feladat importálása',
    ImportPanel_BackButton: 'Vissza',
    ImportPanel_CancelButton: 'Mégse',
    ImportPanel_NextButton: 'Következő',
    ImportPanel_StepSource: 'Forrás',
    ImportPanel_StepProject: 'Projekt',
    ImportPanel_StepMap: 'Hozzárendelés',
    ImportPanel_StepImport: 'Importálás',
    ImportPanel_StepDone: 'Kész',
    ImportPanel_ImportAsNewProjectHeader: 'Fájl importálása új projektként',
    ImportPanel_ImportIntoProjectHeader: 'Feladatok importálása ide: {projectName}',
    ImportPanel_CouldNotParseFile: 'Nem sikerült feldolgozni a fájlt.',
    ImportPanel_CouldNotLoadPlannerTasks: 'Nem sikerült betölteni a feladatokat ebből a tervből.',
    ImportPanel_CouldNotCreateProjectDetail: 'Nem sikerült létrehozni a projektet: {detail}',
    ImportPanel_CouldNotLinkDependencies: 'Nem sikerült összekapcsolni a függőségeket: {detail}',
    ImportPanel_UnknownError: 'ismeretlen hiba',

    // ── Column mapper (import) ──
    ColumnMapper_TaskNameRequiredBanner: 'A folytatáshoz hozzá kell rendelni a Feladat neve mezőt.',
    ColumnMapper_SkippedColumnsBanner: '{count} oszlop ki lesz hagyva.',
    ColumnMapper_SourceColumnHeader: 'Forrásoszlop',
    ColumnMapper_TargetFieldHeader: 'Célmező',
    ColumnMapper_StatusHeader: 'Állapot',
    ColumnMapper_SkippedBadge: 'Kihagyva',
    ColumnMapper_AutoMappedBadge: 'Automatikusan hozzárendelve',
    ColumnMapper_SetBadge: 'Beállítva',
    ColumnMapper_PreviewTitle: 'Előnézet: {columnName}',
    ColumnMapper_EmptyCellDash: '—',

    // ── Import field display names / ImportService ──
    ImportField_TaskName: 'Feladat neve',
    ImportField_StartDate: 'Kezdés dátuma',
    ImportField_DueDate: 'Határidő',
    ImportField_Status: 'Állapot',
    ImportField_Priority: 'Prioritás',
    ImportField_AssignedTo: 'Felelős',
    ImportField_AssignedToEmail: 'Felelős e-mail-címe',
    ImportField_PercentComplete: 'Készültség %',
    ImportField_Phase: 'Fázis',
    ImportField_Description: 'Leírás',
    ImportField_Notes: 'Megjegyzések',
    ImportField_IsMilestone: 'Mérföldkő',
    ImportField_Dependencies: 'Függőségek',
    ImportField_SkipColumn: '(Oszlop kihagyása)',
    ImportService_EmptyFileError: 'Úgy tűnik, a fájl üres, vagy nem tartalmaz adatsorokat.',
    ImportService_ReadErrorDetail: 'Nem sikerült beolvasni a fájlt: {detail}.',
    ImportService_FileReadError: 'Fájlolvasási hiba.',
    ImportService_RowError: '{rowNum}. sor („{title}”): {error}',
    ImportService_AmbiguousDependency: 'A(z) „{name}” függőség több feladat címére is illik – kihagyva.',
    ImportService_LinkDependencyError: 'Nem sikerült összekapcsolni a(z) {taskId} feladat függőségeit: {error}',

    // ── Health labels ──
    Health_Done: 'Kész',
    Health_OnTrack: 'Ütemben',
    Health_AtRisk: 'Kockázatos',
    Health_Overdue: 'Lejárt',

    // ── Status / Priority display labels ──
    Status_NotStarted: 'Nem kezdődött el',
    Status_InProgress: 'Folyamatban',
    Status_Completed: 'Befejezve',
    Status_OnHold: 'Felfüggesztve',
    Status_Cancelled: 'Törölve',
    Priority_Critical: 'Kritikus',
    Priority_High: 'Magas',
    Priority_Medium: 'Közepes',
    Priority_Low: 'Alacsony',
    ProjectStatus_Planning: 'Tervezés',
    ProjectStatus_Active: 'Aktív',
    ProjectStatus_OnHold: 'Felfüggesztve',
    ProjectStatus_Completed: 'Befejezve',
    ProjectStatus_Cancelled: 'Törölve',

    // ── Shell (SmartGantt.tsx) ──
    SmartGantt_LoadingProjects: 'Projektek betöltése…',
    SmartGantt_UnableToLoad: 'Nem sikerült betölteni',
    SmartGantt_RetryButton: 'Újrapróbálkozás',
    SmartGantt_NoProjectsYet: 'Még nincsenek projektek',
    SmartGantt_NoProjectsSubtitle: 'A kezdéshez hozza létre az első projektet.',
    SmartGantt_CreateFirstProjectButton: '+ Első projekt létrehozása',
    SmartGantt_ImportFromExcelButton: '📥 Importálás Excelből',
    SmartGantt_LoadingTasks: 'Feladatok betöltése…',
    SmartGantt_DismissAriaLabel: 'Bezárás',
    SmartGantt_DeleteTaskDialogTitle: 'Feladat törlése',
    SmartGantt_DeleteTaskDialogSubtext: 'Biztosan törli a(z) „{taskTitle}” feladatot? Ez a művelet nem vonható vissza.',
    SmartGantt_DeleteButton: 'Törlés',
    SmartGantt_CancelButton: 'Mégse',
    SmartGantt_ArchiveProjectDialogTitle: 'Projekt archiválása',
    SmartGantt_ArchiveProjectDialogSubtext: 'Archiválja a(z) „{projectTitle}” projektet? Később visszaállíthatja.',
    SmartGantt_ArchiveButton: 'Archiválás',
    SmartGantt_SendToRecycleBinDialogTitle: 'Áthelyezés a lomtárba',
    SmartGantt_SendToRecycleBinDialogSubtext: 'Áthelyezi a(z) „{projectTitle}” projektet a webhely lomtárába?',
    SmartGantt_SendToRecycleBinButton: 'Áthelyezés a lomtárba',
    SmartGantt_FailedLoadProjects: 'Nem sikerült betölteni a projekteket. Ellenőrizze a webhely jogosultságait.',
    SmartGantt_FailedLoadTasks: 'Nem sikerült betölteni ennek a projektnek a feladatait.',
    SmartGantt_FailedLoadPortfolioStats: 'Nem sikerült betölteni a portfólió statisztikáit.',
    SmartGantt_CouldNotSaveProject: 'Nem sikerült menteni a projektet: {message}',
    SmartGantt_CouldNotDeleteProject: 'Nem sikerült törölni a projektet: {message}',
    SmartGantt_CouldNotArchiveProject: 'Nem sikerült archiválni a projektet: {message}',
    SmartGantt_CouldNotUnarchiveProject: 'Nem sikerült visszaállítani a projektet az archívumból: {message}',
    SmartGantt_CouldNotSaveTask: 'Nem sikerült menteni a feladatot: {message}',
    SmartGantt_CouldNotDeleteTask: 'Nem sikerült törölni a feladatot: {message}',
    SmartGantt_ImageExportFailed: 'A kép exportálása sikertelen: {message}',
    SmartGantt_PowerPointExportFailed: 'A PowerPoint-exportálás sikertelen: {message}',
    SmartGantt_PortfolioExportFailed: 'A portfólió exportálása sikertelen: {message}',
    SmartGantt_CouldNotUpdateTask: 'Nem sikerült frissíteni a feladatot: {message}',

    // ── Common ──
    ColorSwatch_AutoColorAriaLabel: 'Automatikus szín',
    ColorSwatch_CustomColorAriaLabel: 'Egyéni szín',
    ColorSwatch_PickCustomColorTitle: 'Egyéni szín kiválasztása',

    // ── Export (Excel / PowerPoint) ──
    Export_ColTaskName: 'Feladat neve',
    Export_ColPhase: 'Fázis',
    Export_ColStartDate: 'Kezdés dátuma',
    Export_ColDueDate: 'Határidő',
    Export_ColStatus: 'Állapot',
    Export_ColPriority: 'Prioritás',
    Export_ColAssignedTo: 'Felelős',
    Export_ColAssignedToEmail: 'Felelős e-mail-címe',
    Export_ColPercentComplete: 'Készültség %',
    Export_ColIsMilestone: 'Mérföldkő',
    Export_ColDescription: 'Leírás',
    Export_ColNotes: 'Megjegyzések',
    Export_Yes: 'Igen',
    Export_No: 'Nem',
    Export_SheetNameTasks: 'Feladatok',
    Export_ExcelFileSuffix: ' - Feladatok.xlsx',
    Export_TaskNameColumnLabel: 'FELADAT NEVE',
    Export_ExportedDateLabel: 'Exportálva: {date}',
    Export_ProjectReportLabel: 'PROJEKTJELENTÉS',
    Export_StatusLine: 'Állapot: {status}',
    Export_DateRangeSeparator: ' – ',
    Export_ProjectManagerLine: 'Projektvezető: {name}',
    Export_GeneratedDateLine: 'Létrehozva: {date}',
    Export_ProjectSummaryTitle: 'Projektösszegzés',
    Export_StatTotalTasks: 'Feladatok összesen',
    Export_StatCompleted: 'Befejezve',
    Export_StatInProgress: 'Folyamatban',
    Export_StatOnHold: 'Felfüggesztve',
    Export_StatNotStarted: 'Nem kezdődött el',
    Export_OverallProgressLine: 'Összesített előrehaladás',
    Export_OverallProgressPercent: '{percent}%',
    Export_StatusBreakdownTitle: 'Állapot szerinti bontás',
    Export_StatusBreakdownRow: '{status}: {count} ({percent}%)',
    Export_GanttTimelineTitle: 'Gantt idővonal',
    Export_SummaryRecentActivityTitle: 'Legutóbbi tevékenység',
    Export_ProjectOverviewLabel: 'Projekt áttekintése',
    Export_DetailStatusLabel: 'Állapot',
    Export_DetailStartDateLabel: 'Kezdés dátuma',
    Export_DetailDueDateLabel: 'Határidő',
    Export_DetailProjectManagerLabel: 'Projektvezető',
    Export_Past7DaysLabel: 'Elmúlt 7 nap',
    Export_NoActivityMessage: 'Nincs legutóbbi tevékenység.',
    Export_CompletedThisWeekHeader: 'E héten befejezve ({count})',
    Export_NewBadge: 'ÚJ  ',
    Export_CompletedPercentLine: '{percent}% kész',
    Export_MoreItemsSuffix: '+ {count} további',
    Export_InProgressUpdatedHeader: 'Folyamatban / frissítve',
    Export_StatusPercentLine: '{status} — {percent}%',
    Export_PortfolioReportLabel: 'PORTFÓLIÓJELENTÉS',
    Export_PortfolioOverviewTitle: 'Portfólió áttekintése',
    Export_ProjectsCountLine: '{count} projekt',
    Export_HealthSummaryOnTrack: '{count} ütemben',
    Export_HealthSummaryAtRisk: '{count} kockázatos',
    Export_HealthSummaryOverdue: '{count} lejárt',
    Export_ProjectsSummaryHeader: 'Projektek összegzése',
    Export_TableProject: 'Projekt',
    Export_TableStatus: 'Állapot',
    Export_TableHealth: 'Állapotjelző',
    Export_TableTotal: 'Összesen',
    Export_TableDone: 'Kész',
    Export_TableActive: 'Aktív',
    Export_TableAtRisk: 'Kockázatos',
    Export_TableOverdue: 'Lejárt',
    Export_TablePctDone: 'Készültség %',
    Export_TableDueDate: 'Határidő',
    Export_PortfolioSummaryFileName: 'Portfólió összegzés.xlsx',
    Export_PortfolioReportFileName: 'Portfóliójelentés.pptx',
    Export_ProjectReportFileName: '{projectName} jelentés.pptx',
    Export_UnavailableLabel: 'Nem érhető el',
    Export_SheetNamePortfolio: 'Portfólió',
    Export_ColStart: 'Kezdés',
    Export_ColDue: 'Határidő',
    Export_ImageGenerationFailed: 'Nem sikerült létrehozni a képet – a diagram túl nagy lehet ahhoz, hogy képként exportálható legyen.',
    Export_DrawingContextFailed: 'Nem sikerült rajzolási kontextust létrehozni az exportáláshoz.',
    Export_SvgRenderFailed: 'Az SVG renderelése sikertelen',

    // ── Added in v1.5 review ──
    Svc_TooManyDependencies: 'A feladatnak túl sok függősége van a mentéshez (a korlát körülbelül 60). Távolítson el néhányat, és próbálja újra.',
    Svc_TaskChangedByOthers: 'A feladatot valaki más módosította a betöltése óta. Frissítsen, és próbálja újra.',
    Svc_ProjectChangedByOthers: 'A projektet valaki más módosította a megnyitása óta. Frissítsen, és próbálja újra.',
    Svc_ColumnCreateFailed: 'Nem sikerült {count} oszlopot létrehozni az új feladatlistán: {detail}',
    Svc_BaselineUnavailable: 'Az alaptervek nem érhetők el ehhez a projekthez, mert az alapterv-oszlopokat nem sikerült hozzáadni (lehet, hogy a lista szerkesztéséhez engedély szükséges).',
    Svc_SubtaskReassignFailed: 'Nem sikerült újra hozzárendelni a feladat részfeladatait a törlés előtt: {detail}',
    Svc_UnresolvedDependency: '{row}. sor („{title}”): a(z) „{name}” függőséget nem sikerült egyeztetni importált feladattal.',
    Svc_SelfDependency: '{row}. sor („{title}”): a(z) „{name}” függőség magára a feladatra mutat, ezért kimaradt.',
    Svc_ColId: 'Azonosító',
    Svc_ColDependencies: 'Függőségek',
    Svc_ColBaselineStart: 'Alapterv kezdete',
    Svc_ColBaselineDue: 'Alapterv határideje',
    Svc_CsvFileSuffix: ' - Feladatok.csv',
    Svc_IcsFileSuffix: ' - Mérföldkövek.ics',
    Svc_PortfolioCsvFileName: 'Portfólió-összesítő.csv',
    Svc_PP_DisplayGroup: 'Alapértelmezések',
    Svc_PP_DefaultView: 'Alapértelmezett nézet',
    Svc_PP_ViewGantt: 'Gantt',
    Svc_PP_ViewList: 'Lista',
    Svc_PP_ViewKanban: 'Kanban',
    Svc_PP_ViewDashboard: 'Vezérlőpult',
    Svc_PP_ViewPortfolio: 'Portfólió',
    Svc_PP_DefaultZoom: 'Alapértelmezett nagyítás',
    Svc_PP_ZoomDay: 'Nap',
    Svc_PP_ZoomWeek: 'Hét',
    Svc_PP_ZoomMonth: 'Hónap',
    Svc_PP_ZoomQuarter: 'Negyedév',
    Svc_PP_CalendarGroup: 'Munkanaptár',
    Svc_PP_DaySun: 'A vasárnap munkanap',
    Svc_PP_DayMon: 'A hétfő munkanap',
    Svc_PP_DayTue: 'A kedd munkanap',
    Svc_PP_DayWed: 'A szerda munkanap',
    Svc_PP_DayThu: 'A csütörtök munkanap',
    Svc_PP_DayFri: 'A péntek munkanap',
    Svc_PP_DaySat: 'A szombat munkanap',
    Svc_PP_Holidays: 'Ünnepnapok (munkaszüneti napok)',
    Svc_PP_HolidaysHint: 'Soronként egy dátum éééé-HH-nn formátumban (például 2026-12-25).',
    Gantt_TimelineAriaLabel: 'Feladatidővonal',
    Gantt_DragLabel: '{start} → {end} ({days} n)',
    Gantt_KeyboardMoveAnnouncement: '{taskTitle}: {startDate} – {dueDate}',
    Gantt_KeyboardHint: 'A feladat megnyitásához nyomja meg az Enter billentyűt. A balra és jobbra nyíl egy munkanappal tolja el. A Shift és a nyílbillentyűk a befejezési dátumot módosítják.',
    Gantt_ParentCycleTooltip: 'Ez a feladat egy körkörös szülő–részfeladat láncolat része, ezért legfelső szinten jelenik meg',
    Gantt_CollapseAll: 'Minden fázis összecsukása',
    Gantt_ExpandAll: 'Minden fázis kibontása',
    Gantt_BaselineTooltip: 'Alapterv: {start} → {due}',
    Gantt_VarianceTooltip: 'Befejezési eltérés: {days} nap az alaptervhez képest',
    Gantt_LinkHandleTitle: 'Húzza egy másik feladatra függőség létrehozásához',
    Toolbar_FitToProject: 'Illesztés',
    Toolbar_FitToProjectTitle: 'Nagyítás a teljes projekt megjelenítéséhez',
    Toolbar_UndoTitle: 'Visszavonás (Ctrl+Z)',
    Toolbar_RedoTitle: 'Újra (Ctrl+Y)',
    Toolbar_ExportCsv: '📄 Feladatok exportálása CSV-be',
    Toolbar_ExportIcs: '📅 Mérföldkövek exportálása (iCal)',
    Toolbar_Print: '🖨 Nyomtatás / Mentés PDF-ként',
    Toolbar_SetBaseline: '📐 Alapterv beállítása…',
    Toolbar_CopyLink: '🔗 Hivatkozás másolása',
    Toolbar_CopyLinkTitle: 'Hivatkozás másolása ehhez a nézethez (projekt, nézet, nagyítás és szűrők)',
    App_UndoButton: 'Visszavonás',
    App_Undone: 'A módosítás visszavonva.',
    App_Redone: 'A módosítás újra végrehajtva.',
    App_DependentsMovedOne: '1 függő feladat áthelyezve.',
    App_DependentsMovedMany: '{count} függő feladat áthelyezve.',
    App_TaskConflict: 'A feladatot valaki más módosította. A legfrissebb feladatok újra betöltődtek – ellenőrizze őket, és próbálja újra.',
    App_DependencyCycle: 'Ez a kapcsolat körkörös függőséget hozna létre.',
    App_DependencyExists: 'Ezek a feladatok már össze vannak kapcsolva.',
    App_LinkCopied: 'A hivatkozás a vágólapra másolva.',
    App_LinkCopyFailed: 'Nem sikerült a hivatkozás másolása: {message}',
    App_PopupBlocked: 'A nyomtatási ablakot letiltotta a böngésző. Engedélyezze az előugró ablakokat ezen a webhelyen, és próbálja újra.',
    App_SetBaselineDialogTitle: 'Alapterv beállítása',
    App_SetBaselineDialogSubtext: 'Menti mind a(z) {count} feladat jelenlegi kezdő és határidő dátumát alaptervként? A meglévő alapterv felülíródik.',
    App_SetBaselineButton: 'Alapterv beállítása',
    App_BaselineSaved: 'Az alapterv mentve.',
    App_BaselineFailed: 'Nem sikerült menteni az alaptervet: {message}',
    App_CsvExportFailed: 'A CSV-exportálás sikertelen: {message}',
    App_IcsExportFailed: 'A naptár exportálása sikertelen: {message}',
    App_BulkDeleteDialogTitle: 'Feladatok törlése',
    App_BulkDeleteDialogSubtext: 'Biztosan törli a(z) {count} feladatot? Ez a művelet nem vonható vissza.',
    Common_PeoplePicker_ClearAriaLabel: 'Törlés',
    Common_PeoplePicker_DirectoryHeader: 'Személyek a címtárban',
    Common_PeoplePicker_EmailLabel: 'E-mail (nem kötelező)',
    Common_PeoplePicker_EmailPlaceholder: 'nev@cegnev.hu',
    Common_PeoplePicker_ExternalHint: 'Nincs a címtárban. Szabad szövegként lesz mentve.',
    Common_PeoplePicker_InvalidEmail: 'Adjon meg érvényes e-mail-címet.',
    Common_PeoplePicker_ListAriaLabel: 'Javasolt személyek',
    Common_PeoplePicker_RecentHeader: 'Nemrég használt',
    Common_PeoplePicker_ResultsAnnouncement: '{count} javaslat érhető el',
    Common_PeoplePicker_Searching: 'Keresés…',
    Common_PeoplePicker_UseExternal: '„{name}” használata (külső / nincs a címtárban)',
    Import_Mapper_PreviewFirstRows: 'Előnézet (az első {count} sor)',
    Import_Mapper_RequiredLegend: 'Kötelező mező',
    Import_Mapper_RequiredMarkerLabel: 'Kötelező',
    Import_Mapper_SelectAriaLabel: 'Célmező a(z) {columnName} oszlophoz',
    Import_Panel_DateOrderAuto: 'Automatikus felismerés',
    Import_Panel_DateOrderDMY: 'Nap/hónap/év (31/12/2026)',
    Import_Panel_DateOrderDetected: 'A fájl alapján felismerve: {order}.',
    Import_Panel_DateOrderHint: 'A számokkal írt dátumokra vonatkozik, például 03/04/2026.',
    Import_Panel_DateOrderLabel: 'Dátumsorrend',
    Import_Panel_DateOrderMDY: 'Hónap/nap/év (12/31/2026)',
    Import_Panel_DropZoneAriaLabel: 'Válasszon importálandó fájlt. A tallózáshoz nyomja meg az Enter billentyűt.',
    Import_Panel_DropZoneChangeAriaLabel: 'Kiválasztott fájl: {fileName}. Másik fájl kiválasztásához nyomja meg az Enter billentyűt.',
    Import_Panel_FailedCount: '{count} sikertelen',
    Import_Panel_NewProjectIntroMany: 'Új projekt jön létre, és mind a(z) {count} feladat importálásra kerül bele. Ezeket az adatokat az importálás után bármikor módosíthatja.',
    Import_Panel_NewProjectIntroOne: 'Új projekt jön létre, és a(z) {count} feladat importálásra kerül bele. Ezeket az adatokat az importálás után bármikor módosíthatja.',
    Import_Panel_PlanAriaLabel: '{planName}, {groupName}',
    Import_Panel_ProblemEndBeforeStart: 'A határidő a kezdési dátum előtt van',
    Import_Panel_ProblemInvalidDueDate: 'A(z) „{value}” határidő nem érvényes dátum',
    Import_Panel_ProblemInvalidStartDate: 'A(z) „{value}” kezdési dátum nem érvényes dátum',
    Import_Panel_ProblemMissingTitle: 'A feladat neve hiányzik',
    Import_Panel_ProgressLabelWithPercent: '{done} / {total} ({percent}%)',
    Import_Panel_SkipInvalidRows: 'Hibás sorok kihagyása',
    Import_Panel_SuccessWithWarningsMany: 'Az importálás sikeres, {count} figyelmeztetéssel.',
    Import_Panel_SuccessWithWarningsOne: 'Az importálás sikeres, {count} figyelmeztetéssel.',
    Import_Panel_ValidationHeader: 'Hibás sorok',
    Import_Panel_ValidationMore: '…és még {count}',
    Import_Panel_ValidationRow: '{rowNum}. sor: {problem}',
    Import_Panel_ValidationSummaryMany: '{count} sorban van hiba',
    Import_Panel_ValidationSummaryOne: '{count} sorban van hiba',
    Import_Panel_WarningsLabel: 'Figyelmeztetések ({count}):',
    Panel_Project_ManagerLabel: 'Projektmenedzser',
    Panel_Project_ManagerPlaceholder: 'Keressen személyeket, vagy írjon be egy nevet…',
    Panel_Task_BaselineDueLabel: 'Alapterv szerinti befejezés',
    Panel_Task_BaselineHeader: 'Alapterv',
    Panel_Task_BaselineStartLabel: 'Alapterv szerinti kezdés',
    Panel_Task_DepTypeFF: 'Befejezéstől befejezésig (FF)',
    Panel_Task_DepTypeFS: 'Befejezéstől kezdésig (FS)',
    Panel_Task_DepTypeSF: 'Kezdéstől befejezésig (SF)',
    Panel_Task_DepTypeSS: 'Kezdéstől kezdésig (SS)',
    Panel_Task_LagAriaLabel: 'Csúszás munkanapokban: {taskTitle}',
    Panel_Task_LagHint: 'A csúszás munkanapokban értendő. Előrehozáshoz használjon negatív számot.',
    Panel_Task_LinkTypeAriaLabel: 'Kapcsolat típusa: {taskTitle}',
    Panel_Task_VarianceEarlier: '{days} munkanappal korábban',
    Panel_Task_VarianceLater: '{days} munkanappal később',
    Panel_Task_VarianceOnBaseline: 'az alaptervnek megfelelő',
    View_Dashboard_BurndownActual: 'Tényleges',
    View_Dashboard_BurndownAria: 'Burndown diagram: {remaining} / {total} feladat van hátra',
    View_Dashboard_BurndownHeader: 'Burndown (hátralévő feladatok)',
    View_Dashboard_BurndownIdeal: 'Ideális',
    View_Dashboard_BurndownNoData: 'Nincs elég dátummal rendelkező feladat a burndown megrajzolásához.',
    View_Dashboard_CriticalPathHeader: 'Kritikus út  ({count})',
    View_Dashboard_PhaseDoneSummary: '{done}/{total} kész  •  {percent}%',
    View_Dashboard_TaskRowAriaLabel: '{taskTitle} feladat megnyitása, {status}',
    View_Dashboard_WorkloadHeader: 'Terhelés felelősönként',
    View_Dashboard_WorkloadOpen: '{count} nyitott',
    View_Dashboard_WorkloadOverdue: '{count} késésben',
    View_Kanban_AddTaskInColumnAriaLabel: 'Feladat hozzáadása ehhez az oszlophoz: {column}',
    View_Kanban_CollapseColumn: '{column} oszlop összecsukása',
    View_Kanban_ExpandColumn: '{column} oszlop kibontása',
    View_Kanban_LaneHeader: '{name} ({count})',
    View_Kanban_LaneNoPhase: 'Nincs fázis',
    View_Kanban_LaneUnassigned: 'Nincs hozzárendelve',
    View_Kanban_LanesAssignee: 'Felelős',
    View_Kanban_LanesNone: 'Nincs',
    View_Kanban_LanesPhase: 'Fázis',
    View_Kanban_SwimlanesLabel: 'Swimlane-ek',
    View_Kanban_WipEditTitle: 'Folyamatban lévő munka korlátjának beállítása: {column} (0 = nincs korlát)',
    View_Kanban_WipExceededTitle: 'A WIP-korlát túllépve: {count} / {limit}',
    View_Kanban_WipInputAriaLabel: 'WIP-korlát: {column}',
    View_Kanban_WipLabel: 'WIP {count}/{limit}',
    View_Kanban_WipSet: 'WIP',
    View_List_BulkAssignApply: 'Hozzárendelés',
    View_List_BulkAssigneePlaceholder: 'Hozzárendelés…',
    View_List_BulkBarAriaLabel: 'Tömeges műveletek a kijelölt feladatokhoz',
    View_List_BulkClear: 'Kijelölés törlése',
    View_List_BulkDelete: 'Kijelöltek törlése',
    View_List_BulkPercentApply: '% beállítása',
    View_List_BulkPercentPlaceholder: '% kész',
    View_List_BulkPriorityPlaceholder: 'Prioritás beállítása…',
    View_List_BulkSelectedCount: '{count} kijelölve',
    View_List_BulkStatusPlaceholder: 'Állapot beállítása…',
    View_List_ExportCsv: 'CSV exportálása',
    View_List_NonWorkingDay: 'Munkaszüneti nap',
    View_List_SelectAllAriaLabel: 'Az összes feladat kijelölése',
    View_List_SelectRowAriaLabel: '{taskTitle} kijelölése',
    View_Portfolio_CardAriaLabel: '{projectName} projekt megnyitása, {status}',
    View_Portfolio_ClearFilters: 'Szűrők törlése',
    View_Portfolio_FilteredCount: '{shown} / {total} projekt',
    View_Portfolio_HideDone: 'Befejezett / törölt elemek elrejtése',
    View_Portfolio_NoMatches: 'Egy projekt sem felel meg a szűrőknek.',
    View_Portfolio_ProjectCountMany: '{count} projekt',
    View_Portfolio_ProjectCountOne: '{count} projekt',
    View_Portfolio_SearchAriaLabel: 'Projektek keresése',
    View_Portfolio_SearchPlaceholder: 'Projektek keresése…',
    Import_Panel_CopyDetails: 'Részletek másolása',
    Import_Panel_Copied: 'Másolva',
  };
});
