define([], function () {
  return {
    // ── Property pane ──
    PropertyPane_HeaderDescription: 'Pengaturan Smart Gantt Chart',
    PropertyPane_GeneralGroupName: 'Umum',
    PropertyPane_TitleFieldLabel: 'Judul Web Part',
    WebPart_DefaultTitle: 'Smart Gantt Chart',

    // ── Toolbar ──
    Toolbar_ViewDashboard: 'Dasbor',
    Toolbar_ViewList: 'Daftar',
    Toolbar_ViewGantt: 'Gantt',
    Toolbar_ViewKanban: 'Kanban',
    Toolbar_ZoomDay: 'Hari',
    Toolbar_ZoomWeek: 'Minggu',
    Toolbar_ZoomMonth: 'Bulan',
    Toolbar_ZoomQuarter: 'Kuartal',
    Toolbar_SelectProjectAriaLabel: 'Pilih proyek',
    Toolbar_PortfolioLabel: 'Portofolio',
    Toolbar_SelectAProject: 'Pilih Proyek',
    Toolbar_AllProjectsSubtext: 'Semua proyek',
    Toolbar_NoProjectsYet: 'Belum ada proyek',
    Toolbar_ArchivedBadge: 'Diarsipkan',
    Toolbar_ShowArchivedProjects: 'Tampilkan proyek yang diarsipkan',
    Toolbar_NewProject: '+ Proyek Baru',
    Toolbar_ImportFileAsNewProject: '📥 Impor File sebagai Proyek Baru…',
    Toolbar_AddTask: '+ Tambah Tugas',
    Toolbar_EditProject: 'Edit Proyek',
    Toolbar_OptionsButton: '⚙ Opsi',
    Toolbar_MoreOptionsTitle: 'Opsi lainnya',
    Toolbar_ExportToExcel: '📊 Ekspor ke Excel',
    Toolbar_ExportToPowerPoint: '📑 Ekspor ke PowerPoint',
    Toolbar_ScrollToTodayTitle: 'Gulir ke hari ini',
    Toolbar_TodayButton: '◉ Hari Ini',
    Toolbar_ImportTasks: '📥 Impor Tugas…',
    Toolbar_ExportAsImage: '🖼 Ekspor sebagai Gambar (PNG)',
    Toolbar_UnarchiveProject: '📂 Batalkan Arsip Proyek',
    Toolbar_ArchiveProject: '🗄️ Arsipkan Proyek',
    Toolbar_SendToRecycleBin: '🗑️ Pindahkan ke Recycle Bin',

    // ── Filter bar ──
    FilterBar_ClearOption: 'Hapus',
    FilterBar_DueAny: 'Semua tanggal jatuh tempo',
    FilterBar_DueOverdue: 'Terlambat',
    FilterBar_DueToday: 'Jatuh tempo hari ini',
    FilterBar_DueWeek: 'Jatuh tempo dalam 7 hari',
    FilterBar_SearchPlaceholder: 'Cari tugas…',
    FilterBar_SearchAriaLabel: 'Cari tugas',
    FilterBar_StatusChipLabel: 'Status',
    FilterBar_PriorityChipLabel: 'Prioritas',
    FilterBar_AssigneeChipLabel: 'Ditugaskan Kepada',
    FilterBar_PhaseChipLabel: 'Fase',
    FilterBar_DueDateAriaLabel: 'Filter berdasarkan tanggal jatuh tempo',
    FilterBar_MatchCount: '{matchCount} dari {totalCount}',
    FilterBar_ClearFilters: '✕ Hapus filter',
    FilterBar_ChipLabelWithCount: '{label} ({count}) ▾',
    FilterBar_ChipLabelNoCount: '{label} ▾',

    // ── Gantt view ──
    Gantt_TaskColumnHeader: 'Tugas',
    Gantt_DurationColumnHeader: 'Durasi',
    Gantt_AddTaskButton: '+ Tambah Tugas',
    Gantt_EmptyTitle: 'Belum ada tugas',
    Gantt_EmptySubtitle: 'Tambahkan tugas untuk melihatnya pada Gantt chart.',
    Gantt_AddFirstTask: '+ Tambah Tugas Pertama',
    Gantt_ImportTasksButton: '📥 Impor Tugas',
    Gantt_EditTitle: 'Edit',
    Gantt_DeleteTitle: 'Hapus',
    Gantt_EditTaskAriaLabel: 'Edit tugas {taskTitle}',
    Gantt_DeleteTaskAriaLabel: 'Hapus tugas {taskTitle}',
    Gantt_ExpandPhaseAriaLabel: '{action} fase {phase}',
    Gantt_ExpandAction: 'Perluas',
    Gantt_CollapseAction: 'Ciutkan',
    Gantt_DependencyViolationTooltip: 'Dimulai sebelum semua dependensi selesai',
    Gantt_MilestoneAriaLabel: '{taskTitle}, milestone, {date}',
    Gantt_BarAriaLabel: '{taskTitle}, {startDate} hingga {dueDate}, {percent}% selesai',
    Gantt_PercentCompleteTooltip: '{value}% selesai',

    // ── Gantt options/settings panel ──
    GanttSettings_PanelHeader: '⚙ Opsi',
    GanttSettings_ColorCodingSection: 'Pengodean Warna',
    GanttSettings_ByStatus: 'Berdasarkan Status',
    GanttSettings_ByPriority: 'Berdasarkan Prioritas',
    GanttSettings_ByPhase: 'Berdasarkan Fase',
    GanttSettings_ByHealth: 'Berdasarkan Kesehatan',
    GanttSettings_HeaderColorSection: 'Warna Header',
    GanttSettings_ThemeDark: 'Gelap',
    GanttSettings_ThemeNavy: 'Navy',
    GanttSettings_ThemeTeal: 'Teal',
    GanttSettings_ThemePurple: 'Ungu',
    GanttSettings_ThemeLight: 'Terang',
    GanttSettings_HeaderLabelsSection: 'Label Header',
    GanttSettings_WeekLabelDates: 'Tanggal',
    GanttSettings_WeekLabelDatesDesc: '3 Jun, 10 Jun…',
    GanttSettings_WeekLabelProject: 'Minggu Proyek',
    GanttSettings_WeekLabelProjectDesc: 'M1, M2…',
    GanttSettings_WeekLabelIso: 'Minggu Kalender',
    GanttSettings_WeekLabelIsoDesc: 'M23, M24…',
    GanttSettings_ProjectWeeksHint: 'Minggu 1 dimulai dari hari Senin tugas paling awal Anda — cocok untuk presentasi.',
    GanttSettings_BarStyleSection: 'Gaya Batang',
    GanttSettings_BarStyleGradient: 'Gradien',
    GanttSettings_BarStyleFlat: 'Datar',
    GanttSettings_RowHeightSection: 'Tinggi Baris',
    GanttSettings_HeightCompact: 'Kompak',
    GanttSettings_HeightNormal: 'Normal',
    GanttSettings_HeightSpacious: 'Lega',
    GanttSettings_ShowHideSection: 'Tampilkan / Sembunyikan',
    GanttSettings_WeekendShading: 'Bayangan akhir pekan',
    GanttSettings_DependencyArrows: 'Panah dependensi',
    GanttSettings_CriticalPathAlwaysVisible: 'Jalur kritis selalu terlihat',
    GanttSettings_AllOthersOnHoverOnly: 'Lainnya hanya saat kursor diarahkan',
    GanttSettings_CriticalPathHighlight: 'Sorotan jalur kritis',
    GanttSettings_ProgressPercentOnBars: 'Persentase progres pada batang',
    GanttSettings_AssigneeNameOnBars: 'Nama penerima tugas pada batang',
    GanttSettings_HealthStatusBadges: 'Lencana status kesehatan',

    // ── List view ──
    ListView_ColTaskName: 'Nama Tugas',
    ListView_ColStatus: 'Status',
    ListView_ColHealth: 'Kesehatan',
    ListView_ColPriority: 'Prioritas',
    ListView_ColStart: 'Mulai',
    ListView_ColDue: 'Jatuh Tempo',
    ListView_ColAssignedTo: 'Ditugaskan Kepada',
    ListView_ColProgress: 'Progres',
    ListView_ColPhase: 'Fase',
    ListView_ColPredecessors: 'Pendahulu',
    ListView_EmptyTitle: 'Belum ada tugas',
    ListView_AddFirstTask: '+ Tambah Tugas Pertama',
    ListView_AddTaskRow: '+ Tambah Tugas',
    ListView_Unassigned: 'Belum Ditugaskan',
    ListView_DependencyViolationTooltip: 'Dimulai sebelum semua dependensi selesai',
    ListView_StatusAriaLabel: 'Status {taskTitle}',
    ListView_PriorityAriaLabel: 'Prioritas {taskTitle}',
    ListView_EditTaskAriaLabel: 'Edit tugas {taskTitle}',
    ListView_DeleteTaskAriaLabel: 'Hapus tugas {taskTitle}',
    ListView_EditTitle: 'Edit',
    ListView_DeleteTitle: 'Hapus',

    // ── Kanban view ──
    Kanban_ColumnNotStarted: 'Belum Dimulai',
    Kanban_ColumnInProgress: 'Sedang Berlangsung',
    Kanban_ColumnOnHold: 'Ditahan',
    Kanban_ColumnCompleted: 'Selesai',
    Kanban_ColumnCancelled: 'Dibatalkan',
    Kanban_AddTaskButton: '+ Tambah Tugas',
    Kanban_EditTitle: 'Edit',
    Kanban_DeleteTitle: 'Hapus',
    Kanban_CardAriaLabel: '{taskTitle}, {status}. Tekan Enter untuk mengedit, panah Kiri atau Kanan untuk mengubah status.',
    Kanban_EditTaskAriaLabel: 'Edit tugas {taskTitle}',
    Kanban_DeleteTaskAriaLabel: 'Hapus tugas {taskTitle}',

    // ── Dashboard view ──
    Dashboard_TotalTasks: 'Total Tugas',
    Dashboard_Completed: 'Selesai',
    Dashboard_InProgress: 'Sedang Berlangsung',
    Dashboard_OnHold: 'Ditahan',
    Dashboard_NotStarted: 'Belum Dimulai',
    Dashboard_Cancelled: 'Dibatalkan',
    Dashboard_OverallProgress: 'Progres Keseluruhan',
    Dashboard_ProjectManagerLabel: 'Manajer Proyek: {name}',
    Dashboard_PhaseProgressHeader: 'Progres Fase',
    Dashboard_StatusBreakdownHeader: 'Rincian Status',
    Dashboard_PriorityBreakdownHeader: 'Rincian Prioritas',
    Dashboard_PriorityCritical: 'Kritis',
    Dashboard_PriorityHigh: 'Tinggi',
    Dashboard_PriorityMedium: 'Sedang',
    Dashboard_PriorityLow: 'Rendah',
    Dashboard_OverdueHeader: 'Terlambat  ({count})',
    Dashboard_DueNext14DaysHeader: 'Jatuh tempo dalam 14 hari ke depan  ({count})',
    Dashboard_CompletedThisWeekHeader: 'Selesai Minggu Ini',
    Dashboard_UpdatedThisWeekHeader: 'Diperbarui Minggu Ini',
    Dashboard_Today: 'Hari Ini',
    Dashboard_Tomorrow: 'Besok',
    Dashboard_DaysLeft: '{days}h',
    Dashboard_EmptyTitle: 'Belum ada tugas',
    Dashboard_EmptySubtitle: 'Tambahkan tugas untuk melihat dasbor proyek Anda.',
    Dashboard_AddTaskButton: '+ Tambah Tugas',

    // ── Portfolio view ──
    Portfolio_ProjectCount: '{count} Proyek{plural}',
    Portfolio_OnTrackSummary: '{count} Sesuai Rencana',
    Portfolio_AtRiskSummary: '{count} Berisiko',
    Portfolio_OverdueSummary: '{count} Terlambat',
    Portfolio_DoneSummary: '{count} Selesai',
    Portfolio_SortLabel: 'Urutkan:',
    Portfolio_SortAZ: 'A-Z',
    Portfolio_SortHealth: 'Kesehatan',
    Portfolio_SortStatus: 'Status',
    Portfolio_SortCompletion: 'Penyelesaian',
    Portfolio_RefreshTitle: 'Segarkan',
    Portfolio_RefreshButton: 'Segarkan',
    Portfolio_LoadingStats: 'Memuat statistik…',
    Portfolio_EmptyTitle: 'Belum ada proyek',
    Portfolio_CreateFirstProject: '+ Buat Proyek Pertama',
    Portfolio_StatsUnavailable: 'Statistik tidak tersedia',
    Portfolio_StatsUnavailableDetail: 'Tidak dapat memuat statistik untuk proyek ini.',
    Portfolio_OverallProgressLabel: 'Progres Keseluruhan',
    Portfolio_TaskCountDone: 'Selesai',
    Portfolio_TaskCountActive: 'Aktif',
    Portfolio_TaskCountAtRisk: 'Berisiko',
    Portfolio_TaskCountOverdue: 'Terlambat',
    Portfolio_ViewGanttLink: 'Lihat Gantt →',
    Portfolio_TodayTooltip: 'Hari Ini',

    // ── Task panel ──
    TaskPanel_EditHeader: 'Edit: {taskTitle}',
    TaskPanel_NewTaskHeader: 'Tugas Baru',
    TaskPanel_TabBasic: 'Dasar',
    TaskPanel_TabDetails: 'Detail',
    TaskPanel_TabLinks: 'Tautan',
    TaskPanel_ProjectLabelPrefix: 'Proyek: ',
    TaskPanel_TaskNameLabel: 'Nama Tugas',
    TaskPanel_TaskNamePlaceholder: 'Masukkan nama tugas',
    TaskPanel_TaskNameRequired: 'Nama tugas wajib diisi',
    TaskPanel_DescriptionLabel: 'Deskripsi',
    TaskPanel_DescriptionPlaceholder: 'Masukkan deskripsi',
    TaskPanel_StartDateLabel: 'Tanggal Mulai',
    TaskPanel_DueDateLabel: 'Tanggal Jatuh Tempo',
    TaskPanel_DueDateError: 'Tanggal jatuh tempo harus sama dengan atau setelah tanggal mulai',
    TaskPanel_StatusLabel: 'Status',
    TaskPanel_PriorityLabel: 'Prioritas',
    TaskPanel_PercentCompleteLabel: '% Selesai: {percent}%',
    TaskPanel_AssignedToLabel: 'Ditugaskan Kepada',
    TaskPanel_AssignedToPlaceholder: 'Cari orang…',
    TaskPanel_PhaseLabel: 'Fase',
    TaskPanel_PhasePlaceholder: 'Masukkan nama fase',
    TaskPanel_PhaseHint: 'Mengelompokkan tugas bersama di tampilan Gantt dan Daftar.',
    TaskPanel_MilestoneLabel: 'Milestone',
    TaskPanel_MilestoneOnText: 'Ya',
    TaskPanel_MilestoneOffText: 'Tidak',
    TaskPanel_CustomBarColorLabel: 'Warna Batang Kustom',
    TaskPanel_CustomBarColorOptionalSuffix: ' (opsional)',
    TaskPanel_AutoColorHint: 'Warna otomatis dari pengaturan status/prioritas/fase.',
    TaskPanel_NotesLabel: 'Catatan',
    TaskPanel_NotesPlaceholder: 'Masukkan catatan',
    TaskPanel_ParentTaskLabel: 'Tugas Induk',
    TaskPanel_ParentTaskNone: '(tidak ada)',
    TaskPanel_ParentTaskHasChildrenHint: 'Tugas ini memiliki sub-tugas dan tidak dapat memiliki induknya sendiri.',
    TaskPanel_ParentTaskHint: 'Sematkan tugas ini di bawah tugas lain sebagai sub-tugas.',
    TaskPanel_DependsOnLabel: 'Bergantung Pada',
    TaskPanel_RemoveDependencyTitle: 'Hapus dependensi pada "{taskTitle}"',
    TaskPanel_AddDependencyPlaceholder: 'Tambahkan dependensi…',
    TaskPanel_SelectATaskOption: 'Pilih tugas…',
    TaskPanel_DependsOnHint: 'Tugas tidak dapat dimulai sampai tugas-tugas ini selesai.',
    TaskPanel_SavingLabel: 'Menyimpan…',
    TaskPanel_CreatingLabel: 'Membuat…',
    TaskPanel_SaveChangesButton: 'Simpan Perubahan',
    TaskPanel_CreateTaskButton: 'Buat Tugas',
    TaskPanel_CancelButton: 'Batal',
    TaskPanel_DismissAriaLabel: 'Tutup',
    TaskPanel_DiscardUnsavedChangesConfirm: 'Buang perubahan yang belum disimpan?',
    TaskPanel_SaveFallbackError: 'Tidak dapat menyimpan tugas.',

    // ── Project panel ──
    ProjectPanel_EditHeader: 'Edit Proyek',
    ProjectPanel_NewHeader: 'Proyek Baru',
    ProjectPanel_ProjectNameLabel: 'Nama Proyek',
    ProjectPanel_ProjectNamePlaceholder: 'Masukkan nama proyek',
    ProjectPanel_ProjectNameRequired: 'Nama proyek wajib diisi',
    ProjectPanel_DescriptionLabel: 'Deskripsi',
    ProjectPanel_DescriptionPlaceholder: 'Masukkan deskripsi',
    ProjectPanel_ProjectColorLabel: 'Warna Proyek',
    ProjectPanel_StatusLabel: 'Status',
    ProjectPanel_StartDateLabel: 'Tanggal Mulai',
    ProjectPanel_DueDateLabel: 'Tanggal Jatuh Tempo',
    ProjectPanel_DueDateError: 'Tanggal jatuh tempo harus sama dengan atau setelah tanggal mulai',
    ProjectPanel_WhatHappensNextTitle: 'Apa yang terjadi selanjutnya?',
    ProjectPanel_WhatHappensNextBody: 'Anda akan dapat menambahkan tugas, menyiapkan fase, dan melacak progres setelah proyek dibuat.',
    ProjectPanel_SavingLabel: 'Menyimpan…',
    ProjectPanel_CreatingLabel: 'Membuat…',
    ProjectPanel_SaveChangesButton: 'Simpan Perubahan',
    ProjectPanel_CreateProjectButton: 'Buat Proyek',
    ProjectPanel_CancelButton: 'Batal',
    ProjectPanel_DismissAriaLabel: 'Tutup',
    ProjectPanel_DiscardUnsavedChangesConfirm: 'Buang perubahan yang belum disimpan?',
    ProjectPanel_SaveFallbackError: 'Tidak dapat menyimpan proyek.',

    // ── Import panel ──
    ImportPanel_SourceExcelTitle: 'File Excel / CSV',
    ImportPanel_SourceExcelSubtitle: 'Impor tugas dari spreadsheet',
    ImportPanel_SourcePlannerTitle: 'Microsoft Planner',
    ImportPanel_SourcePlannerSubtitle: 'Impor tugas dari rencana Planner',
    ImportPanel_ClickToBrowse: 'Klik untuk menelusuri',
    ImportPanel_DragDropSuffix: ' atau seret dan lepas',
    ImportPanel_SupportedExtensions: 'Mendukung .xlsx, .xls, .csv',
    ImportPanel_RowsColsSummary: '{rows} baris, {cols} kolom terdeteksi',
    ImportPanel_LoadingPlannerPlans: 'Memuat rencana Planner…',
    ImportPanel_PlannerLoadError: 'Tidak dapat memuat rencana Planner.',
    ImportPanel_PlannerPermissionsHintPrefix: 'Pastikan Anda memiliki akses ke Planner dan bahwa ',
    ImportPanel_PlannerPermissionsHintEmphasis: 'Tasks by Planner and To Do',
    ImportPanel_PlannerPermissionsHintSuffix: ' tersedia di situs ini.',
    ImportPanel_NoPlannerPlansFoundTitle: 'Tidak ada rencana Planner ditemukan',
    ImportPanel_NoPlannerPlansFoundBody: 'Anda mungkin tidak memiliki akses ke rencana Planner apa pun, atau tidak ada yang tersedia untuk akun ini.',
    ImportPanel_TaskCountFoundIn: '{count} tugas ditemukan di "{planName}"',
    ImportPanel_ProjectDetailsIntroPrefix: 'Mengimpor ke ',
    ImportPanel_ProjectDetailsIntroSuffix: '. Tinjau detail proyek di bawah ini.',
    ImportPanel_ProjectNameLabel: 'Nama Proyek',
    ImportPanel_DescriptionLabel: 'Deskripsi',
    ImportPanel_StatusLabel: 'Status',
    ImportPanel_ColorLabel: 'Warna',
    ImportPanel_MapIntro: 'Petakan kolom dari file Anda ke bidang tugas.',
    ImportPanel_CreatingProjectStatus: 'Membuat proyek…',
    ImportPanel_ImportingTasksStatus: 'Mengimpor tugas…',
    ImportPanel_ProgressLabel: '{done} dari {total}',
    ImportPanel_CouldNotCreateProject: 'Tidak dapat membuat proyek.',
    ImportPanel_ImportCompletedWithErrors: 'Impor selesai dengan {count} kesalahan.',
    ImportPanel_ProjectCreatedSuccess: 'Proyek berhasil dibuat!',
    ImportPanel_ImportSuccessful: 'Impor berhasil!',
    ImportPanel_TasksAddedTo: '{count} tugas ditambahkan ke "{projectName}"',
    ImportPanel_FailedRowsLabel: 'Baris yang gagal:',
    ImportPanel_CloseButton: 'Tutup',
    ImportPanel_OpenProjectButton: 'Buka Proyek',
    ImportPanel_ViewImportedTasksButton: 'Lihat Tugas yang Diimpor',
    ImportPanel_NextMapColumnsButton: 'Selanjutnya: Petakan Kolom',
    ImportPanel_ImportNTasksButton: 'Impor {count} Tugas',
    ImportPanel_BackButton: 'Kembali',
    ImportPanel_CancelButton: 'Batal',
    ImportPanel_NextButton: 'Selanjutnya',
    ImportPanel_StepSource: 'Sumber',
    ImportPanel_StepProject: 'Proyek',
    ImportPanel_StepMap: 'Peta',
    ImportPanel_StepImport: 'Impor',
    ImportPanel_StepDone: 'Selesai',
    ImportPanel_ImportAsNewProjectHeader: 'Impor File sebagai Proyek Baru',
    ImportPanel_ImportIntoProjectHeader: 'Impor Tugas ke {projectName}',
    ImportPanel_CouldNotParseFile: 'Tidak dapat mengurai file.',
    ImportPanel_CouldNotLoadPlannerTasks: 'Tidak dapat memuat tugas dari rencana ini.',
    ImportPanel_CouldNotCreateProjectDetail: 'Tidak dapat membuat proyek: {detail}',
    ImportPanel_CouldNotLinkDependencies: 'Tidak dapat menautkan dependensi: {detail}',
    ImportPanel_UnknownError: 'kesalahan tidak diketahui',

    // ── Column mapper (import) ──
    ColumnMapper_TaskNameRequiredBanner: 'Nama Tugas harus dipetakan untuk melanjutkan.',
    ColumnMapper_SkippedColumnsBanner: '{count} kolom akan dilewati.',
    ColumnMapper_SourceColumnHeader: 'Kolom Sumber',
    ColumnMapper_TargetFieldHeader: 'Bidang Tujuan',
    ColumnMapper_StatusHeader: 'Status',
    ColumnMapper_SkippedBadge: 'Dilewati',
    ColumnMapper_AutoMappedBadge: 'Dipetakan Otomatis',
    ColumnMapper_SetBadge: 'Diatur',
    ColumnMapper_PreviewTitle: 'Pratinjau: {columnName}',
    ColumnMapper_EmptyCellDash: '—',

    // ── Import field display names / ImportService ──
    ImportField_TaskName: 'Nama Tugas',
    ImportField_StartDate: 'Tanggal Mulai',
    ImportField_DueDate: 'Tanggal Jatuh Tempo',
    ImportField_Status: 'Status',
    ImportField_Priority: 'Prioritas',
    ImportField_AssignedTo: 'Ditugaskan Kepada',
    ImportField_AssignedToEmail: 'Email Penerima Tugas',
    ImportField_PercentComplete: '% Selesai',
    ImportField_Phase: 'Fase',
    ImportField_Description: 'Deskripsi',
    ImportField_Notes: 'Catatan',
    ImportField_IsMilestone: 'Adalah Milestone',
    ImportField_Dependencies: 'Dependensi',
    ImportField_SkipColumn: '(Lewati kolom ini)',
    ImportService_EmptyFileError: 'File tampaknya kosong atau tidak memiliki baris data.',
    ImportService_ReadErrorDetail: 'Tidak dapat membaca file: {detail}.',
    ImportService_FileReadError: 'Kesalahan pembacaan file.',
    ImportService_RowError: 'Baris {rowNum} ("{title}"): {error}',
    ImportService_AmbiguousDependency: 'Dependensi "{name}" cocok dengan lebih dari satu judul tugas — dilewati.',
    ImportService_LinkDependencyError: 'Tidak dapat menautkan dependensi untuk tugas {taskId}: {error}',

    // ── Health labels ──
    Health_Done: 'Selesai',
    Health_OnTrack: 'Sesuai Rencana',
    Health_AtRisk: 'Berisiko',
    Health_Overdue: 'Terlambat',

    // ── Status / Priority display labels ──
    Status_NotStarted: 'Belum Dimulai',
    Status_InProgress: 'Sedang Berlangsung',
    Status_Completed: 'Selesai',
    Status_OnHold: 'Ditahan',
    Status_Cancelled: 'Dibatalkan',
    Priority_Critical: 'Kritis',
    Priority_High: 'Tinggi',
    Priority_Medium: 'Sedang',
    Priority_Low: 'Rendah',
    ProjectStatus_Planning: 'Perencanaan',
    ProjectStatus_Active: 'Aktif',
    ProjectStatus_OnHold: 'Ditahan',
    ProjectStatus_Completed: 'Selesai',
    ProjectStatus_Cancelled: 'Dibatalkan',

    // ── Shell (SmartGantt.tsx) ──
    SmartGantt_LoadingProjects: 'Memuat proyek…',
    SmartGantt_UnableToLoad: 'Tidak dapat memuat',
    SmartGantt_RetryButton: 'Coba Lagi',
    SmartGantt_NoProjectsYet: 'Belum ada proyek',
    SmartGantt_NoProjectsSubtitle: 'Buat proyek pertama Anda untuk memulai.',
    SmartGantt_CreateFirstProjectButton: '+ Buat Proyek Pertama',
    SmartGantt_ImportFromExcelButton: '📥 Impor dari Excel',
    SmartGantt_LoadingTasks: 'Memuat tugas…',
    SmartGantt_DismissAriaLabel: 'Tutup',
    SmartGantt_DeleteTaskDialogTitle: 'Hapus Tugas',
    SmartGantt_DeleteTaskDialogSubtext: 'Anda yakin ingin menghapus "{taskTitle}"? Tindakan ini tidak dapat dibatalkan.',
    SmartGantt_DeleteButton: 'Hapus',
    SmartGantt_CancelButton: 'Batal',
    SmartGantt_ArchiveProjectDialogTitle: 'Arsipkan Proyek',
    SmartGantt_ArchiveProjectDialogSubtext: 'Arsipkan "{projectTitle}"? Anda dapat membatalkan pengarsipan nanti.',
    SmartGantt_ArchiveButton: 'Arsipkan',
    SmartGantt_SendToRecycleBinDialogTitle: 'Pindahkan ke Recycle Bin',
    SmartGantt_SendToRecycleBinDialogSubtext: 'Pindahkan "{projectTitle}" ke recycle bin situs?',
    SmartGantt_SendToRecycleBinButton: 'Pindahkan ke Recycle Bin',
    SmartGantt_FailedLoadProjects: 'Gagal memuat proyek. Periksa izin situs.',
    SmartGantt_FailedLoadTasks: 'Gagal memuat tugas untuk proyek ini.',
    SmartGantt_FailedLoadPortfolioStats: 'Gagal memuat statistik portofolio.',
    SmartGantt_CouldNotSaveProject: 'Tidak dapat menyimpan proyek: {message}',
    SmartGantt_CouldNotDeleteProject: 'Tidak dapat menghapus proyek: {message}',
    SmartGantt_CouldNotArchiveProject: 'Tidak dapat mengarsipkan proyek: {message}',
    SmartGantt_CouldNotUnarchiveProject: 'Tidak dapat membatalkan pengarsipan proyek: {message}',
    SmartGantt_CouldNotSaveTask: 'Tidak dapat menyimpan tugas: {message}',
    SmartGantt_CouldNotDeleteTask: 'Tidak dapat menghapus tugas: {message}',
    SmartGantt_ImageExportFailed: 'Ekspor gambar gagal: {message}',
    SmartGantt_PowerPointExportFailed: 'Ekspor PowerPoint gagal: {message}',
    SmartGantt_PortfolioExportFailed: 'Ekspor portofolio gagal: {message}',
    SmartGantt_CouldNotUpdateTask: 'Tidak dapat memperbarui tugas: {message}',

    // ── Common ──
    ColorSwatch_AutoColorAriaLabel: 'Warna otomatis',
    ColorSwatch_CustomColorAriaLabel: 'Warna kustom',
    ColorSwatch_PickCustomColorTitle: 'Pilih warna kustom',

    // ── Export (Excel / PowerPoint) ──
    Export_ColTaskName: 'Nama Tugas',
    Export_ColPhase: 'Fase',
    Export_ColStartDate: 'Tanggal Mulai',
    Export_ColDueDate: 'Tanggal Jatuh Tempo',
    Export_ColStatus: 'Status',
    Export_ColPriority: 'Prioritas',
    Export_ColAssignedTo: 'Ditugaskan Kepada',
    Export_ColAssignedToEmail: 'Email Penerima Tugas',
    Export_ColPercentComplete: '% Selesai',
    Export_ColIsMilestone: 'Adalah Milestone',
    Export_ColDescription: 'Deskripsi',
    Export_ColNotes: 'Catatan',
    Export_Yes: 'Ya',
    Export_No: 'Tidak',
    Export_SheetNameTasks: 'Tugas',
    Export_ExcelFileSuffix: ' - Tugas.xlsx',
    Export_TaskNameColumnLabel: 'NAMA TUGAS',
    Export_ExportedDateLabel: 'Diekspor {date}',
    Export_ProjectReportLabel: 'LAPORAN PROYEK',
    Export_StatusLine: 'Status: {status}',
    Export_DateRangeSeparator: ' hingga ',
    Export_ProjectManagerLine: 'Manajer Proyek: {name}',
    Export_GeneratedDateLine: 'Dibuat {date}',
    Export_ProjectSummaryTitle: 'Ringkasan Proyek',
    Export_StatTotalTasks: 'Total Tugas',
    Export_StatCompleted: 'Selesai',
    Export_StatInProgress: 'Sedang Berlangsung',
    Export_StatOnHold: 'Ditahan',
    Export_StatNotStarted: 'Belum Dimulai',
    Export_OverallProgressLine: 'Progres Keseluruhan',
    Export_OverallProgressPercent: '{percent}%',
    Export_StatusBreakdownTitle: 'Rincian Status',
    Export_StatusBreakdownRow: '{status}: {count} ({percent}%)',
    Export_GanttTimelineTitle: 'Garis Waktu Gantt',
    Export_SummaryRecentActivityTitle: 'Aktivitas Terbaru',
    Export_ProjectOverviewLabel: 'Ikhtisar Proyek',
    Export_DetailStatusLabel: 'Status',
    Export_DetailStartDateLabel: 'Tanggal Mulai',
    Export_DetailDueDateLabel: 'Tanggal Jatuh Tempo',
    Export_DetailProjectManagerLabel: 'Manajer Proyek',
    Export_Past7DaysLabel: '7 Hari Terakhir',
    Export_NoActivityMessage: 'Tidak ada aktivitas terbaru.',
    Export_CompletedThisWeekHeader: 'Selesai Minggu Ini ({count})',
    Export_NewBadge: 'BARU  ',
    Export_CompletedPercentLine: '{percent}% selesai',
    Export_MoreItemsSuffix: '+ {count} lainnya',
    Export_InProgressUpdatedHeader: 'Sedang Berlangsung / Diperbarui',
    Export_StatusPercentLine: '{status} — {percent}%',
    Export_PortfolioReportLabel: 'LAPORAN PORTOFOLIO',
    Export_PortfolioOverviewTitle: 'Ikhtisar Portofolio',
    Export_ProjectsCountLine: '{count} Proyek',
    Export_HealthSummaryOnTrack: '{count} Sesuai Rencana',
    Export_HealthSummaryAtRisk: '{count} Berisiko',
    Export_HealthSummaryOverdue: '{count} Terlambat',
    Export_ProjectsSummaryHeader: 'Ringkasan Proyek',
    Export_TableProject: 'Proyek',
    Export_TableStatus: 'Status',
    Export_TableHealth: 'Kesehatan',
    Export_TableTotal: 'Total',
    Export_TableDone: 'Selesai',
    Export_TableActive: 'Aktif',
    Export_TableAtRisk: 'Berisiko',
    Export_TableOverdue: 'Terlambat',
    Export_TablePctDone: '% Selesai',
    Export_TableDueDate: 'Tanggal Jatuh Tempo',
    Export_PortfolioSummaryFileName: 'Ringkasan Portofolio.xlsx',
    Export_PortfolioReportFileName: 'Laporan Portofolio.pptx',
    Export_ProjectReportFileName: 'Laporan {projectName}.pptx',
    Export_UnavailableLabel: 'Tidak Tersedia',
    Export_SheetNamePortfolio: 'Portofolio',
    Export_ColStart: 'Mulai',
    Export_ColDue: 'Jatuh Tempo',
    Export_ImageGenerationFailed: 'Tidak dapat membuat gambar — bagan mungkin terlalu besar untuk diekspor sebagai gambar.',
    Export_DrawingContextFailed: 'Tidak dapat membuat konteks gambar untuk ekspor.',
    Export_SvgRenderFailed: 'Rendering SVG gagal',
  };
});
