define([], function () {
  return {
    // ── Property pane ──
    PropertyPane_HeaderDescription: 'Impostazioni di Smart Gantt Chart',
    PropertyPane_GeneralGroupName: 'Generale',
    PropertyPane_TitleFieldLabel: 'Titolo del web part',
    WebPart_DefaultTitle: 'Smart Gantt Chart',

    // ── Toolbar ──
    Toolbar_ViewDashboard: 'Dashboard',
    Toolbar_ViewList: 'Elenco',
    Toolbar_ViewGantt: 'Gantt',
    Toolbar_ViewKanban: 'Kanban',
    Toolbar_ZoomDay: 'Giorno',
    Toolbar_ZoomWeek: 'Settimana',
    Toolbar_ZoomMonth: 'Mese',
    Toolbar_ZoomQuarter: 'Trimestre',
    Toolbar_SelectProjectAriaLabel: 'Seleziona progetto',
    Toolbar_PortfolioLabel: 'Portafoglio',
    Toolbar_SelectAProject: 'Seleziona un progetto',
    Toolbar_AllProjectsSubtext: 'Tutti i progetti',
    Toolbar_NoProjectsYet: 'Nessun progetto ancora',
    Toolbar_ArchivedBadge: 'Archiviato',
    Toolbar_ShowArchivedProjects: 'Mostra progetti archiviati',
    Toolbar_NewProject: '+ Nuovo progetto',
    Toolbar_ImportFileAsNewProject: '📥 Importa file come nuovo progetto…',
    Toolbar_AddTask: '+ Aggiungi attività',
    Toolbar_EditProject: 'Modifica progetto',
    Toolbar_OptionsButton: '⚙ Opzioni',
    Toolbar_MoreOptionsTitle: 'Altre opzioni',
    Toolbar_ExportToExcel: '📊 Esporta in Excel',
    Toolbar_ExportToPowerPoint: '📑 Esporta in PowerPoint',
    Toolbar_ScrollToTodayTitle: 'Vai a oggi',
    Toolbar_TodayButton: '◉ Oggi',
    Toolbar_ImportTasks: '📥 Importa attività…',
    Toolbar_ExportAsImage: '🖼 Esporta come immagine (PNG)',
    Toolbar_UnarchiveProject: '📂 Ripristina progetto',
    Toolbar_ArchiveProject: '🗄️ Archivia progetto',
    Toolbar_SendToRecycleBin: '🗑️ Sposta nel cestino',

    // ── Filter bar ──
    FilterBar_ClearOption: 'Cancella',
    FilterBar_DueAny: 'Qualsiasi scadenza',
    FilterBar_DueOverdue: 'In ritardo',
    FilterBar_DueToday: 'In scadenza oggi',
    FilterBar_DueWeek: 'In scadenza tra 7 giorni',
    FilterBar_SearchPlaceholder: 'Cerca attività…',
    FilterBar_SearchAriaLabel: 'Cerca attività',
    FilterBar_StatusChipLabel: 'Stato',
    FilterBar_PriorityChipLabel: 'Priorità',
    FilterBar_AssigneeChipLabel: 'Assegnatario',
    FilterBar_PhaseChipLabel: 'Fase',
    FilterBar_DueDateAriaLabel: 'Filtra per data di scadenza',
    FilterBar_MatchCount: '{matchCount} di {totalCount}',
    FilterBar_ClearFilters: '✕ Cancella filtri',
    FilterBar_ChipLabelWithCount: '{label} ({count}) ▾',
    FilterBar_ChipLabelNoCount: '{label} ▾',

    // ── Gantt view ──
    Gantt_TaskColumnHeader: 'Attività',
    Gantt_DurationColumnHeader: 'Durata',
    Gantt_AddTaskButton: '+ Aggiungi attività',
    Gantt_EmptyTitle: 'Nessuna attività ancora',
    Gantt_EmptySubtitle: 'Aggiungi attività per visualizzarle nel diagramma di Gantt.',
    Gantt_AddFirstTask: '+ Aggiungi la prima attività',
    Gantt_ImportTasksButton: '📥 Importa attività',
    Gantt_EditTitle: 'Modifica',
    Gantt_DeleteTitle: 'Elimina',
    Gantt_EditTaskAriaLabel: 'Modifica attività {taskTitle}',
    Gantt_DeleteTaskAriaLabel: 'Elimina attività {taskTitle}',
    Gantt_ExpandPhaseAriaLabel: '{action} fase {phase}',
    Gantt_ExpandAction: 'Espandi',
    Gantt_CollapseAction: 'Comprimi',
    Gantt_DependencyViolationTooltip: 'Avviata prima che tutte le dipendenze fossero completate',
    Gantt_MilestoneAriaLabel: '{taskTitle}, milestone, {date}',
    Gantt_BarAriaLabel: '{taskTitle}, da {startDate} a {dueDate}, {percent}% completato',
    Gantt_PercentCompleteTooltip: '{value}% completato',

    // ── Gantt options/settings panel ──
    GanttSettings_PanelHeader: '⚙ Opzioni',
    GanttSettings_ColorCodingSection: 'Codifica colori',
    GanttSettings_ByStatus: 'Per stato',
    GanttSettings_ByPriority: 'Per priorità',
    GanttSettings_ByPhase: 'Per fase',
    GanttSettings_ByHealth: 'Per stato di salute',
    GanttSettings_HeaderColorSection: 'Colore intestazione',
    GanttSettings_ThemeDark: 'Scuro',
    GanttSettings_ThemeNavy: 'Blu navy',
    GanttSettings_ThemeTeal: 'Turchese',
    GanttSettings_ThemePurple: 'Viola',
    GanttSettings_ThemeLight: 'Chiaro',
    GanttSettings_HeaderLabelsSection: 'Etichette intestazione',
    GanttSettings_WeekLabelDates: 'Date',
    GanttSettings_WeekLabelDatesDesc: '3 giu, 10 giu…',
    GanttSettings_WeekLabelProject: 'Settimane del progetto',
    GanttSettings_WeekLabelProjectDesc: 'S1, S2…',
    GanttSettings_WeekLabelIso: 'Settimane di calendario',
    GanttSettings_WeekLabelIsoDesc: 'S23, S24…',
    GanttSettings_ProjectWeeksHint: 'La settimana 1 inizia dal lunedì della prima attività: ideale per le presentazioni.',
    GanttSettings_BarStyleSection: 'Stile barre',
    GanttSettings_BarStyleGradient: 'Sfumato',
    GanttSettings_BarStyleFlat: 'Piatto',
    GanttSettings_RowHeightSection: 'Altezza riga',
    GanttSettings_HeightCompact: 'Compatta',
    GanttSettings_HeightNormal: 'Normale',
    GanttSettings_HeightSpacious: 'Ampia',
    GanttSettings_ShowHideSection: 'Mostra / Nascondi',
    GanttSettings_WeekendShading: 'Evidenziazione weekend',
    GanttSettings_DependencyArrows: 'Frecce di dipendenza',
    GanttSettings_CriticalPathAlwaysVisible: 'Percorso critico sempre visibile',
    GanttSettings_AllOthersOnHoverOnly: 'Tutti gli altri solo al passaggio del mouse',
    GanttSettings_CriticalPathHighlight: 'Evidenziazione percorso critico',
    GanttSettings_ProgressPercentOnBars: '% di avanzamento sulle barre',
    GanttSettings_AssigneeNameOnBars: 'Nome assegnatario sulle barre',
    GanttSettings_HealthStatusBadges: 'Badge stato di salute',

    // ── List view ──
    ListView_ColTaskName: 'Nome attività',
    ListView_ColStatus: 'Stato',
    ListView_ColHealth: 'Stato di salute',
    ListView_ColPriority: 'Priorità',
    ListView_ColStart: 'Inizio',
    ListView_ColDue: 'Scadenza',
    ListView_ColAssignedTo: 'Assegnato a',
    ListView_ColProgress: 'Avanzamento',
    ListView_ColPhase: 'Fase',
    ListView_ColPredecessors: 'Predecessori',
    ListView_EmptyTitle: 'Nessuna attività ancora',
    ListView_AddFirstTask: '+ Aggiungi la prima attività',
    ListView_AddTaskRow: '+ Aggiungi attività',
    ListView_Unassigned: 'Non assegnato',
    ListView_DependencyViolationTooltip: 'Avviata prima che tutte le dipendenze fossero completate',
    ListView_StatusAriaLabel: 'Stato di {taskTitle}',
    ListView_PriorityAriaLabel: 'Priorità di {taskTitle}',
    ListView_EditTaskAriaLabel: 'Modifica attività {taskTitle}',
    ListView_DeleteTaskAriaLabel: 'Elimina attività {taskTitle}',
    ListView_EditTitle: 'Modifica',
    ListView_DeleteTitle: 'Elimina',

    // ── Kanban view ──
    Kanban_ColumnNotStarted: 'Non iniziata',
    Kanban_ColumnInProgress: 'In corso',
    Kanban_ColumnOnHold: 'In sospeso',
    Kanban_ColumnCompleted: 'Completata',
    Kanban_ColumnCancelled: 'Annullata',
    Kanban_AddTaskButton: '+ Aggiungi attività',
    Kanban_EditTitle: 'Modifica',
    Kanban_DeleteTitle: 'Elimina',
    Kanban_CardAriaLabel: '{taskTitle}, {status}. Premi Invio per modificare, freccia sinistra o destra per cambiare stato.',
    Kanban_EditTaskAriaLabel: 'Modifica attività {taskTitle}',
    Kanban_DeleteTaskAriaLabel: 'Elimina attività {taskTitle}',

    // ── Dashboard view ──
    Dashboard_TotalTasks: 'Attività totali',
    Dashboard_Completed: 'Completate',
    Dashboard_InProgress: 'In corso',
    Dashboard_OnHold: 'In sospeso',
    Dashboard_NotStarted: 'Non iniziate',
    Dashboard_Cancelled: 'Annullate',
    Dashboard_OverallProgress: 'Avanzamento complessivo',
    Dashboard_ProjectManagerLabel: 'Project manager: {name}',
    Dashboard_PhaseProgressHeader: 'Avanzamento per fase',
    Dashboard_StatusBreakdownHeader: 'Ripartizione per stato',
    Dashboard_PriorityBreakdownHeader: 'Ripartizione per priorità',
    Dashboard_PriorityCritical: 'Critica',
    Dashboard_PriorityHigh: 'Alta',
    Dashboard_PriorityMedium: 'Media',
    Dashboard_PriorityLow: 'Bassa',
    Dashboard_OverdueHeader: 'In ritardo  ({count})',
    Dashboard_DueNext14DaysHeader: 'In scadenza nei prossimi 14 giorni  ({count})',
    Dashboard_CompletedThisWeekHeader: 'Completate questa settimana',
    Dashboard_UpdatedThisWeekHeader: 'Aggiornate questa settimana',
    Dashboard_Today: 'Oggi',
    Dashboard_Tomorrow: 'Domani',
    Dashboard_DaysLeft: '{days}g',
    Dashboard_EmptyTitle: 'Nessuna attività ancora',
    Dashboard_EmptySubtitle: 'Aggiungi attività per vedere la dashboard del progetto.',
    Dashboard_AddTaskButton: '+ Aggiungi attività',

    // ── Portfolio view ──
    Portfolio_ProjectCount: '{count} progett{plural}',
    Portfolio_OnTrackSummary: '{count} in linea',
    Portfolio_AtRiskSummary: '{count} a rischio',
    Portfolio_OverdueSummary: '{count} in ritardo',
    Portfolio_DoneSummary: '{count} completati',
    Portfolio_SortLabel: 'Ordina:',
    Portfolio_SortAZ: 'A-Z',
    Portfolio_SortHealth: 'Stato di salute',
    Portfolio_SortStatus: 'Stato',
    Portfolio_SortCompletion: 'Completamento',
    Portfolio_RefreshTitle: 'Aggiorna',
    Portfolio_RefreshButton: 'Aggiorna',
    Portfolio_LoadingStats: 'Caricamento statistiche…',
    Portfolio_EmptyTitle: 'Nessun progetto ancora',
    Portfolio_CreateFirstProject: '+ Crea il primo progetto',
    Portfolio_StatsUnavailable: 'Statistiche non disponibili',
    Portfolio_StatsUnavailableDetail: 'Impossibile caricare le statistiche per questo progetto.',
    Portfolio_OverallProgressLabel: 'Avanzamento complessivo',
    Portfolio_TaskCountDone: 'Completate',
    Portfolio_TaskCountActive: 'Attive',
    Portfolio_TaskCountAtRisk: 'A rischio',
    Portfolio_TaskCountOverdue: 'In ritardo',
    Portfolio_ViewGanttLink: 'Visualizza Gantt →',
    Portfolio_TodayTooltip: 'Oggi',

    // ── Task panel ──
    TaskPanel_EditHeader: 'Modifica: {taskTitle}',
    TaskPanel_NewTaskHeader: 'Nuova attività',
    TaskPanel_TabBasic: 'Base',
    TaskPanel_TabDetails: 'Dettagli',
    TaskPanel_TabLinks: 'Collegamenti',
    TaskPanel_ProjectLabelPrefix: 'Progetto: ',
    TaskPanel_TaskNameLabel: 'Nome attività',
    TaskPanel_TaskNamePlaceholder: 'Inserisci il nome dell\'attività',
    TaskPanel_TaskNameRequired: 'Il nome dell\'attività è obbligatorio',
    TaskPanel_DescriptionLabel: 'Descrizione',
    TaskPanel_DescriptionPlaceholder: 'Inserisci una descrizione',
    TaskPanel_StartDateLabel: 'Data di inizio',
    TaskPanel_DueDateLabel: 'Data di scadenza',
    TaskPanel_DueDateError: 'La data di scadenza deve essere uguale o successiva alla data di inizio',
    TaskPanel_StatusLabel: 'Stato',
    TaskPanel_PriorityLabel: 'Priorità',
    TaskPanel_PercentCompleteLabel: '% Completamento: {percent}%',
    TaskPanel_AssignedToLabel: 'Assegnato a',
    TaskPanel_AssignedToPlaceholder: 'Cerca persone…',
    TaskPanel_PhaseLabel: 'Fase',
    TaskPanel_PhasePlaceholder: 'Inserisci il nome della fase',
    TaskPanel_PhaseHint: 'Raggruppa le attività nelle viste Gantt ed Elenco.',
    TaskPanel_MilestoneLabel: 'Milestone',
    TaskPanel_MilestoneOnText: 'Sì',
    TaskPanel_MilestoneOffText: 'No',
    TaskPanel_CustomBarColorLabel: 'Colore barra personalizzato',
    TaskPanel_CustomBarColorOptionalSuffix: ' (facoltativo)',
    TaskPanel_AutoColorHint: 'Colore automatico in base alle impostazioni di stato/priorità/fase.',
    TaskPanel_NotesLabel: 'Note',
    TaskPanel_NotesPlaceholder: 'Inserisci note',
    TaskPanel_ParentTaskLabel: 'Attività principale',
    TaskPanel_ParentTaskNone: '(nessuna)',
    TaskPanel_ParentTaskHasChildrenHint: 'Questa attività ha sotto-attività e non può avere a sua volta un\'attività principale.',
    TaskPanel_ParentTaskHint: 'Annida questa attività sotto un\'altra come sotto-attività.',
    TaskPanel_DependsOnLabel: 'Dipende da',
    TaskPanel_RemoveDependencyTitle: 'Rimuovi la dipendenza da "{taskTitle}"',
    TaskPanel_AddDependencyPlaceholder: 'Aggiungi una dipendenza…',
    TaskPanel_SelectATaskOption: 'Seleziona un\'attività…',
    TaskPanel_DependsOnHint: 'L\'attività non può iniziare finché queste non sono completate.',
    TaskPanel_SavingLabel: 'Salvataggio…',
    TaskPanel_CreatingLabel: 'Creazione…',
    TaskPanel_SaveChangesButton: 'Salva modifiche',
    TaskPanel_CreateTaskButton: 'Crea attività',
    TaskPanel_CancelButton: 'Annulla',
    TaskPanel_DismissAriaLabel: 'Ignora',
    TaskPanel_DiscardUnsavedChangesConfirm: 'Ignorare le modifiche non salvate?',
    TaskPanel_SaveFallbackError: 'Impossibile salvare l\'attività.',

    // ── Project panel ──
    ProjectPanel_EditHeader: 'Modifica progetto',
    ProjectPanel_NewHeader: 'Nuovo progetto',
    ProjectPanel_ProjectNameLabel: 'Nome progetto',
    ProjectPanel_ProjectNamePlaceholder: 'Inserisci il nome del progetto',
    ProjectPanel_ProjectNameRequired: 'Il nome del progetto è obbligatorio',
    ProjectPanel_DescriptionLabel: 'Descrizione',
    ProjectPanel_DescriptionPlaceholder: 'Inserisci una descrizione',
    ProjectPanel_ProjectColorLabel: 'Colore progetto',
    ProjectPanel_StatusLabel: 'Stato',
    ProjectPanel_StartDateLabel: 'Data di inizio',
    ProjectPanel_DueDateLabel: 'Data di scadenza',
    ProjectPanel_DueDateError: 'La data di scadenza deve essere uguale o successiva alla data di inizio',
    ProjectPanel_WhatHappensNextTitle: 'Cosa succede dopo?',
    ProjectPanel_WhatHappensNextBody: 'Una volta creato il progetto potrai aggiungere attività, configurare le fasi e monitorare l\'avanzamento.',
    ProjectPanel_SavingLabel: 'Salvataggio…',
    ProjectPanel_CreatingLabel: 'Creazione…',
    ProjectPanel_SaveChangesButton: 'Salva modifiche',
    ProjectPanel_CreateProjectButton: 'Crea progetto',
    ProjectPanel_CancelButton: 'Annulla',
    ProjectPanel_DismissAriaLabel: 'Ignora',
    ProjectPanel_DiscardUnsavedChangesConfirm: 'Ignorare le modifiche non salvate?',
    ProjectPanel_SaveFallbackError: 'Impossibile salvare il progetto.',

    // ── Import panel ──
    ImportPanel_SourceExcelTitle: 'File Excel / CSV',
    ImportPanel_SourceExcelSubtitle: 'Importa attività da un foglio di calcolo',
    ImportPanel_SourcePlannerTitle: 'Microsoft Planner',
    ImportPanel_SourcePlannerSubtitle: 'Importa attività da un piano di Planner',
    ImportPanel_ClickToBrowse: 'Fai clic per sfogliare',
    ImportPanel_DragDropSuffix: ' oppure trascina e rilascia',
    ImportPanel_SupportedExtensions: 'Supporta .xlsx, .xls, .csv',
    ImportPanel_RowsColsSummary: '{rows} righe, {cols} colonne rilevate',
    ImportPanel_LoadingPlannerPlans: 'Caricamento piani Planner…',
    ImportPanel_PlannerLoadError: 'Impossibile caricare i piani Planner.',
    ImportPanel_PlannerPermissionsHintPrefix: 'Assicurati di avere accesso a Planner e che ',
    ImportPanel_PlannerPermissionsHintEmphasis: 'Attività di Planner e To Do',
    ImportPanel_PlannerPermissionsHintSuffix: ' sia disponibile in questo sito.',
    ImportPanel_NoPlannerPlansFoundTitle: 'Nessun piano Planner trovato',
    ImportPanel_NoPlannerPlansFoundBody: 'Potresti non avere accesso ad alcun piano Planner, oppure non ne esiste nessuno per questo account.',
    ImportPanel_TaskCountFoundIn: '{count} attività trovate in "{planName}"',
    ImportPanel_ProjectDetailsIntroPrefix: 'Importazione in ',
    ImportPanel_ProjectDetailsIntroSuffix: '. Rivedi i dettagli del progetto di seguito.',
    ImportPanel_ProjectNameLabel: 'Nome progetto',
    ImportPanel_DescriptionLabel: 'Descrizione',
    ImportPanel_StatusLabel: 'Stato',
    ImportPanel_ColorLabel: 'Colore',
    ImportPanel_MapIntro: 'Associa le colonne del file ai campi dell\'attività.',
    ImportPanel_CreatingProjectStatus: 'Creazione del progetto…',
    ImportPanel_ImportingTasksStatus: 'Importazione attività…',
    ImportPanel_ProgressLabel: '{done} di {total}',
    ImportPanel_CouldNotCreateProject: 'Impossibile creare il progetto.',
    ImportPanel_ImportCompletedWithErrors: 'Importazione completata con {count} errore/i.',
    ImportPanel_ProjectCreatedSuccess: 'Progetto creato con successo!',
    ImportPanel_ImportSuccessful: 'Importazione riuscita!',
    ImportPanel_TasksAddedTo: '{count} attività aggiunte a "{projectName}"',
    ImportPanel_FailedRowsLabel: 'Righe non riuscite:',
    ImportPanel_CloseButton: 'Chiudi',
    ImportPanel_OpenProjectButton: 'Apri progetto',
    ImportPanel_ViewImportedTasksButton: 'Visualizza attività importate',
    ImportPanel_NextMapColumnsButton: 'Avanti: associa colonne',
    ImportPanel_ImportNTasksButton: 'Importa {count} attività',
    ImportPanel_BackButton: 'Indietro',
    ImportPanel_CancelButton: 'Annulla',
    ImportPanel_NextButton: 'Avanti',
    ImportPanel_StepSource: 'Origine',
    ImportPanel_StepProject: 'Progetto',
    ImportPanel_StepMap: 'Associazione',
    ImportPanel_StepImport: 'Importazione',
    ImportPanel_StepDone: 'Fine',
    ImportPanel_ImportAsNewProjectHeader: 'Importa file come nuovo progetto',
    ImportPanel_ImportIntoProjectHeader: 'Importa attività in {projectName}',
    ImportPanel_CouldNotParseFile: 'Impossibile analizzare il file.',
    ImportPanel_CouldNotLoadPlannerTasks: 'Impossibile caricare le attività da questo piano.',
    ImportPanel_CouldNotCreateProjectDetail: 'Impossibile creare il progetto: {detail}',
    ImportPanel_CouldNotLinkDependencies: 'Impossibile collegare le dipendenze: {detail}',
    ImportPanel_UnknownError: 'errore sconosciuto',

    // ── Column mapper (import) ──
    ColumnMapper_TaskNameRequiredBanner: 'Il nome dell\'attività deve essere associato per continuare.',
    ColumnMapper_SkippedColumnsBanner: '{count} colonna/e verranno ignorate.',
    ColumnMapper_SourceColumnHeader: 'Colonna di origine',
    ColumnMapper_TargetFieldHeader: 'Campo di destinazione',
    ColumnMapper_StatusHeader: 'Stato',
    ColumnMapper_SkippedBadge: 'Ignorata',
    ColumnMapper_AutoMappedBadge: 'Associata automaticamente',
    ColumnMapper_SetBadge: 'Impostata',
    ColumnMapper_PreviewTitle: 'Anteprima: {columnName}',
    ColumnMapper_EmptyCellDash: '—',

    // ── Import field display names / ImportService ──
    ImportField_TaskName: 'Nome attività',
    ImportField_StartDate: 'Data di inizio',
    ImportField_DueDate: 'Data di scadenza',
    ImportField_Status: 'Stato',
    ImportField_Priority: 'Priorità',
    ImportField_AssignedTo: 'Assegnato a',
    ImportField_AssignedToEmail: 'Email dell\'assegnatario',
    ImportField_PercentComplete: '% Completamento',
    ImportField_Phase: 'Fase',
    ImportField_Description: 'Descrizione',
    ImportField_Notes: 'Note',
    ImportField_IsMilestone: 'È una milestone',
    ImportField_Dependencies: 'Dipendenze',
    ImportField_SkipColumn: '(Ignora questa colonna)',
    ImportService_EmptyFileError: 'Il file sembra essere vuoto o non contiene righe di dati.',
    ImportService_ReadErrorDetail: 'Impossibile leggere il file: {detail}.',
    ImportService_FileReadError: 'Errore di lettura del file.',
    ImportService_RowError: 'Riga {rowNum} ("{title}"): {error}',
    ImportService_AmbiguousDependency: 'La dipendenza "{name}" corrisponde a più di un titolo di attività: ignorata.',
    ImportService_LinkDependencyError: 'Impossibile collegare le dipendenze per l\'attività {taskId}: {error}',

    // ── Health labels (shared: healthUtils.ts and ExportService.ts both use this set; also replaces the duplicated Export_PortfolioHealthLabel* keys) ──
    Health_Done: 'Completato',
    Health_OnTrack: 'In linea',
    Health_AtRisk: 'A rischio',
    Health_Overdue: 'In ritardo',

    // ── Status / Priority display labels (DISPLAY-ONLY — stored SharePoint Choice values remain unchanged/English) ──
    Status_NotStarted: 'Non iniziata',
    Status_InProgress: 'In corso',
    Status_Completed: 'Completata',
    Status_OnHold: 'In sospeso',
    Status_Cancelled: 'Annullata',
    Priority_Critical: 'Critica',
    Priority_High: 'Alta',
    Priority_Medium: 'Media',
    Priority_Low: 'Bassa',
    ProjectStatus_Planning: 'Pianificazione',
    ProjectStatus_Active: 'Attivo',
    ProjectStatus_OnHold: 'In sospeso',
    ProjectStatus_Completed: 'Completato',
    ProjectStatus_Cancelled: 'Annullato',

    // ── Shell (SmartGantt.tsx) ──
    SmartGantt_LoadingProjects: 'Caricamento progetti…',
    SmartGantt_UnableToLoad: 'Impossibile caricare',
    SmartGantt_RetryButton: 'Riprova',
    SmartGantt_NoProjectsYet: 'Nessun progetto ancora',
    SmartGantt_NoProjectsSubtitle: 'Crea il tuo primo progetto per iniziare.',
    SmartGantt_CreateFirstProjectButton: '+ Crea il primo progetto',
    SmartGantt_ImportFromExcelButton: '📥 Importa da Excel',
    SmartGantt_LoadingTasks: 'Caricamento attività…',
    SmartGantt_DismissAriaLabel: 'Ignora',
    SmartGantt_DeleteTaskDialogTitle: 'Elimina attività',
    SmartGantt_DeleteTaskDialogSubtext: 'Eliminare "{taskTitle}"? Questa azione non può essere annullata.',
    SmartGantt_DeleteButton: 'Elimina',
    SmartGantt_CancelButton: 'Annulla',
    SmartGantt_ArchiveProjectDialogTitle: 'Archivia progetto',
    SmartGantt_ArchiveProjectDialogSubtext: 'Archiviare "{projectTitle}"? Potrai ripristinarlo in seguito.',
    SmartGantt_ArchiveButton: 'Archivia',
    SmartGantt_SendToRecycleBinDialogTitle: 'Sposta nel cestino',
    SmartGantt_SendToRecycleBinDialogSubtext: 'Spostare "{projectTitle}" nel cestino del sito?',
    SmartGantt_SendToRecycleBinButton: 'Sposta nel cestino',
    SmartGantt_FailedLoadProjects: 'Impossibile caricare i progetti. Verifica le autorizzazioni del sito.',
    SmartGantt_FailedLoadTasks: 'Impossibile caricare le attività di questo progetto.',
    SmartGantt_FailedLoadPortfolioStats: 'Impossibile caricare le statistiche del portafoglio.',
    SmartGantt_CouldNotSaveProject: 'Impossibile salvare il progetto: {message}',
    SmartGantt_CouldNotDeleteProject: 'Impossibile eliminare il progetto: {message}',
    SmartGantt_CouldNotArchiveProject: 'Impossibile archiviare il progetto: {message}',
    SmartGantt_CouldNotUnarchiveProject: 'Impossibile ripristinare il progetto: {message}',
    SmartGantt_CouldNotSaveTask: 'Impossibile salvare l\'attività: {message}',
    SmartGantt_CouldNotDeleteTask: 'Impossibile eliminare l\'attività: {message}',
    SmartGantt_ImageExportFailed: 'Esportazione immagine non riuscita: {message}',
    SmartGantt_PowerPointExportFailed: 'Esportazione PowerPoint non riuscita: {message}',
    SmartGantt_PortfolioExportFailed: 'Esportazione portafoglio non riuscita: {message}',
    SmartGantt_CouldNotUpdateTask: 'Impossibile aggiornare l\'attività: {message}',

    // ── Common ──
    ColorSwatch_AutoColorAriaLabel: 'Colore automatico',
    ColorSwatch_CustomColorAriaLabel: 'Colore personalizzato',
    ColorSwatch_PickCustomColorTitle: 'Scegli un colore personalizzato',

    // ── Export (Excel / PowerPoint) ──
    Export_ColTaskName: 'Nome attività',
    Export_ColPhase: 'Fase',
    Export_ColStartDate: 'Data di inizio',
    Export_ColDueDate: 'Data di scadenza',
    Export_ColStatus: 'Stato',
    Export_ColPriority: 'Priorità',
    Export_ColAssignedTo: 'Assegnato a',
    Export_ColAssignedToEmail: 'Email dell\'assegnatario',
    Export_ColPercentComplete: '% Completamento',
    Export_ColIsMilestone: 'È una milestone',
    Export_ColDescription: 'Descrizione',
    Export_ColNotes: 'Note',
    Export_Yes: 'Sì',
    Export_No: 'No',
    Export_SheetNameTasks: 'Attività',
    Export_ExcelFileSuffix: ' - Attività.xlsx',
    Export_TaskNameColumnLabel: 'NOME ATTIVITÀ',
    Export_ExportedDateLabel: 'Esportato il {date}',
    Export_ProjectReportLabel: 'REPORT DI PROGETTO',
    Export_StatusLine: 'Stato: {status}',
    Export_DateRangeSeparator: ' a ',
    Export_ProjectManagerLine: 'Project manager: {name}',
    Export_GeneratedDateLine: 'Generato il {date}',
    Export_ProjectSummaryTitle: 'Riepilogo progetto',
    Export_StatTotalTasks: 'Attività totali',
    Export_StatCompleted: 'Completate',
    Export_StatInProgress: 'In corso',
    Export_StatOnHold: 'In sospeso',
    Export_StatNotStarted: 'Non iniziate',
    Export_OverallProgressLine: 'Avanzamento complessivo',
    Export_OverallProgressPercent: '{percent}%',
    Export_StatusBreakdownTitle: 'Ripartizione per stato',
    Export_StatusBreakdownRow: '{status}: {count} ({percent}%)',
    Export_GanttTimelineTitle: 'Cronologia Gantt',
    Export_SummaryRecentActivityTitle: 'Attività recenti',
    Export_ProjectOverviewLabel: 'Panoramica progetto',
    Export_DetailStatusLabel: 'Stato',
    Export_DetailStartDateLabel: 'Data di inizio',
    Export_DetailDueDateLabel: 'Data di scadenza',
    Export_DetailProjectManagerLabel: 'Project manager',
    Export_Past7DaysLabel: 'Ultimi 7 giorni',
    Export_NoActivityMessage: 'Nessuna attività recente.',
    Export_CompletedThisWeekHeader: 'Completate questa settimana ({count})',
    Export_NewBadge: 'NUOVO  ',
    Export_CompletedPercentLine: '{percent}% completato',
    Export_MoreItemsSuffix: '+ altri {count}',
    Export_InProgressUpdatedHeader: 'In corso / Aggiornate',
    Export_StatusPercentLine: '{status} — {percent}%',
    Export_PortfolioReportLabel: 'REPORT DI PORTAFOGLIO',
    Export_PortfolioOverviewTitle: 'Panoramica portafoglio',
    Export_ProjectsCountLine: '{count} progetti',
    Export_HealthSummaryOnTrack: '{count} in linea',
    Export_HealthSummaryAtRisk: '{count} a rischio',
    Export_HealthSummaryOverdue: '{count} in ritardo',
    Export_ProjectsSummaryHeader: 'Riepilogo progetti',
    Export_TableProject: 'Progetto',
    Export_TableStatus: 'Stato',
    Export_TableHealth: 'Stato di salute',
    Export_TableTotal: 'Totale',
    Export_TableDone: 'Completate',
    Export_TableActive: 'Attive',
    Export_TableAtRisk: 'A rischio',
    Export_TableOverdue: 'In ritardo',
    Export_TablePctDone: '% Completate',
    Export_TableDueDate: 'Data di scadenza',
    Export_PortfolioSummaryFileName: 'Riepilogo portafoglio.xlsx',
    Export_PortfolioReportFileName: 'Report portafoglio.pptx',
    Export_ProjectReportFileName: 'Report {projectName}.pptx',
    Export_UnavailableLabel: 'Non disponibile',
    Export_SheetNamePortfolio: 'Portafoglio',
    Export_ColStart: 'Inizio',
    Export_ColDue: 'Scadenza',
    Export_ImageGenerationFailed: 'Impossibile generare l\'immagine: il grafico potrebbe essere troppo grande per l\'esportazione come immagine.',
    Export_DrawingContextFailed: 'Impossibile creare un contesto di disegno per l\'esportazione.',
    Export_SvgRenderFailed: 'Rendering SVG non riuscito',

    // ── Added in v1.5 review ──
    Svc_TooManyDependencies: 'Questa attività ha troppe dipendenze per essere salvata (il limite è circa 60). Rimuovine alcune e riprova.',
    Svc_TaskChangedByOthers: 'Questa attività è stata modificata da un altro utente dopo il caricamento. Aggiorna e riprova.',
    Svc_ProjectChangedByOthers: 'Questo progetto è stato modificato da un altro utente dopo l\'apertura. Aggiorna e riprova.',
    Svc_ColumnCreateFailed: 'Impossibile creare {count} colonna/e nel nuovo elenco attività: {detail}',
    Svc_BaselineUnavailable: 'Le baseline non sono disponibili per questo progetto perché non è stato possibile aggiungere le colonne della baseline (potrebbe essere necessaria l\'autorizzazione per modificare l\'elenco).',
    Svc_SubtaskReassignFailed: 'Impossibile riassegnare le sottoattività di questa attività prima di eliminarla: {detail}',
    Svc_UnresolvedDependency: 'Riga {row} ("{title}"): non è stato possibile associare la dipendenza "{name}" a un\'attività importata.',
    Svc_SelfDependency: 'Riga {row} ("{title}"): la dipendenza "{name}" punta all\'attività stessa ed è stata ignorata.',
    Svc_ColId: 'ID',
    Svc_ColDependencies: 'Dipendenze',
    Svc_ColBaselineStart: 'Inizio baseline',
    Svc_ColBaselineDue: 'Scadenza baseline',
    Svc_CsvFileSuffix: ' - Tasks.csv',
    Svc_IcsFileSuffix: ' - Milestones.ics',
    Svc_PortfolioCsvFileName: 'Portfolio Summary.csv',
    Svc_PP_DisplayGroup: 'Impostazioni predefinite',
    Svc_PP_DefaultView: 'Vista predefinita',
    Svc_PP_ViewGantt: 'Gantt',
    Svc_PP_ViewList: 'Elenco',
    Svc_PP_ViewKanban: 'Kanban',
    Svc_PP_ViewDashboard: 'Dashboard',
    Svc_PP_ViewPortfolio: 'Portfolio',
    Svc_PP_DefaultZoom: 'Zoom predefinito',
    Svc_PP_ZoomDay: 'Giorno',
    Svc_PP_ZoomWeek: 'Settimana',
    Svc_PP_ZoomMonth: 'Mese',
    Svc_PP_ZoomQuarter: 'Trimestre',
    Svc_PP_CalendarGroup: 'Calendario lavorativo',
    Svc_PP_DaySun: 'La domenica è un giorno lavorativo',
    Svc_PP_DayMon: 'Il lunedì è un giorno lavorativo',
    Svc_PP_DayTue: 'Il martedì è un giorno lavorativo',
    Svc_PP_DayWed: 'Il mercoledì è un giorno lavorativo',
    Svc_PP_DayThu: 'Il giovedì è un giorno lavorativo',
    Svc_PP_DayFri: 'Il venerdì è un giorno lavorativo',
    Svc_PP_DaySat: 'Il sabato è un giorno lavorativo',
    Svc_PP_Holidays: 'Festività (date non lavorative)',
    Svc_PP_HolidaysHint: 'Una data per riga, nel formato aaaa-MM-gg (ad esempio 2026-12-25).',
    Gantt_TimelineAriaLabel: 'Sequenza temporale delle attività',
    Gantt_DragLabel: '{start} → {end} ({days} g)',
    Gantt_KeyboardMoveAnnouncement: '{taskTitle}: dal {startDate} al {dueDate}',
    Gantt_KeyboardHint: 'Premi Invio per aprire l\'attività. I tasti freccia sinistra e destra la spostano di un giorno lavorativo. Maiusc con i tasti freccia modifica la data di fine.',
    Gantt_ParentCycleTooltip: 'Questa attività fa parte di una catena circolare di attività padre e sottoattività, quindi viene mostrata al livello superiore',
    Gantt_CollapseAll: 'Comprimi tutte le fasi',
    Gantt_ExpandAll: 'Espandi tutte le fasi',
    Gantt_BaselineTooltip: 'Baseline: {start} → {due}',
    Gantt_VarianceTooltip: 'Scostamento della fine: {days} giorni rispetto alla baseline',
    Gantt_LinkHandleTitle: 'Trascina su un\'altra attività per creare una dipendenza',
    Toolbar_FitToProject: 'Adatta',
    Toolbar_FitToProjectTitle: 'Adatta lo zoom all\'intero progetto',
    Toolbar_UndoTitle: 'Annulla (Ctrl+Z)',
    Toolbar_RedoTitle: 'Ripeti (Ctrl+Y)',
    Toolbar_ExportCsv: '📄 Esporta attività in CSV',
    Toolbar_ExportIcs: '📅 Esporta milestone (iCal)',
    Toolbar_Print: '🖨 Stampa / Salva come PDF',
    Toolbar_SetBaseline: '📐 Imposta baseline…',
    Toolbar_CopyLink: '🔗 Copia collegamento',
    Toolbar_CopyLinkTitle: 'Copia un collegamento a questa vista (progetto, vista, zoom e filtri)',
    App_UndoButton: 'Annulla',
    App_Undone: 'Modifica annullata.',
    App_Redone: 'Modifica ripristinata.',
    App_DependentsMovedOne: 'È stata spostata 1 attività dipendente.',
    App_DependentsMovedMany: 'Sono state spostate {count} attività dipendenti.',
    App_TaskConflict: 'Questa attività è stata modificata da un altro utente. Le attività più recenti sono state ricaricate: verificale e riprova.',
    App_DependencyCycle: 'Questo collegamento creerebbe una dipendenza circolare.',
    App_DependencyExists: 'Queste attività sono già collegate.',
    App_LinkCopied: 'Collegamento copiato negli Appunti.',
    App_LinkCopyFailed: 'Impossibile copiare il collegamento: {message}',
    App_PopupBlocked: 'La finestra di stampa è stata bloccata. Consenti i popup per questo sito e riprova.',
    App_SetBaselineDialogTitle: 'Imposta baseline',
    App_SetBaselineDialogSubtext: 'Salvare come baseline le date di inizio e di scadenza correnti di tutte le {count} attività? Qualsiasi baseline esistente verrà sostituita.',
    App_SetBaselineButton: 'Imposta baseline',
    App_BaselineSaved: 'Baseline salvata.',
    App_BaselineFailed: 'Impossibile salvare la baseline: {message}',
    App_CsvExportFailed: 'Esportazione CSV non riuscita: {message}',
    App_IcsExportFailed: 'Esportazione del calendario non riuscita: {message}',
    App_BulkDeleteDialogTitle: 'Elimina attività',
    App_BulkDeleteDialogSubtext: 'Eliminare {count} attività? Questa operazione non può essere annullata.',
    Common_PeoplePicker_ClearAriaLabel: 'Cancella',
    Common_PeoplePicker_DirectoryHeader: 'Persone nella directory',
    Common_PeoplePicker_EmailLabel: 'E-mail (facoltativa)',
    Common_PeoplePicker_EmailPlaceholder: 'name@company.com',
    Common_PeoplePicker_ExternalHint: 'Non presente nella directory. Salvato come testo libero.',
    Common_PeoplePicker_InvalidEmail: 'Inserisci un indirizzo e-mail valido.',
    Common_PeoplePicker_ListAriaLabel: 'Suggerimenti di persone',
    Common_PeoplePicker_RecentHeader: 'Usati di recente',
    Common_PeoplePicker_ResultsAnnouncement: '{count} suggerimenti disponibili',
    Common_PeoplePicker_Searching: 'Ricerca in corso…',
    Common_PeoplePicker_UseExternal: 'Usa “{name}” (esterno / non presente nella directory)',
    Import_Mapper_PreviewFirstRows: 'Anteprima (prime {count} righe)',
    Import_Mapper_RequiredLegend: 'Campo obbligatorio',
    Import_Mapper_RequiredMarkerLabel: 'Obbligatorio',
    Import_Mapper_SelectAriaLabel: 'Campo di destinazione per la colonna {columnName}',
    Import_Panel_DateOrderAuto: 'Rilevamento automatico',
    Import_Panel_DateOrderDMY: 'Giorno/Mese/Anno (31/12/2026)',
    Import_Panel_DateOrderDetected: 'Rilevato dal file: {order}.',
    Import_Panel_DateOrderHint: 'Si applica alle date scritte con numeri, ad esempio 03/04/2026.',
    Import_Panel_DateOrderLabel: 'Ordine delle date',
    Import_Panel_DateOrderMDY: 'Mese/Giorno/Anno (12/31/2026)',
    Import_Panel_DropZoneAriaLabel: 'Scegli un file da importare. Premi Invio per sfogliare.',
    Import_Panel_DropZoneChangeAriaLabel: 'File selezionato: {fileName}. Premi Invio per scegliere un altro file.',
    Import_Panel_FailedCount: '{count} non riuscite',
    Import_Panel_NewProjectIntroMany: 'Verrà creato un nuovo progetto e tutte le {count} attività verranno importate al suo interno. Potrai modificare questi dettagli in qualsiasi momento dopo l\'importazione.',
    Import_Panel_NewProjectIntroOne: 'Verrà creato un nuovo progetto e {count} attività verrà importata al suo interno. Potrai modificare questi dettagli in qualsiasi momento dopo l\'importazione.',
    Import_Panel_PlanAriaLabel: '{planName}, {groupName}',
    Import_Panel_ProblemEndBeforeStart: 'La data di scadenza è precedente alla data di inizio',
    Import_Panel_ProblemInvalidDueDate: 'La data di scadenza "{value}" non è una data valida',
    Import_Panel_ProblemInvalidStartDate: 'La data di inizio "{value}" non è una data valida',
    Import_Panel_ProblemMissingTitle: 'Manca il nome dell\'attività',
    Import_Panel_ProgressLabelWithPercent: '{done} di {total} ({percent}%)',
    Import_Panel_SkipInvalidRows: 'Ignora le righe con problemi',
    Import_Panel_SuccessWithWarningsMany: 'Importazione riuscita con {count} avvisi.',
    Import_Panel_SuccessWithWarningsOne: 'Importazione riuscita con {count} avviso.',
    Import_Panel_ValidationHeader: 'Righe con problemi',
    Import_Panel_ValidationMore: '…e altre {count}',
    Import_Panel_ValidationRow: 'Riga {rowNum}: {problem}',
    Import_Panel_ValidationSummaryMany: '{count} righe presentano problemi',
    Import_Panel_ValidationSummaryOne: '{count} riga presenta un problema',
    Import_Panel_WarningsLabel: 'Avvisi ({count}):',
    Panel_Project_ManagerLabel: 'Responsabile del progetto',
    Panel_Project_ManagerPlaceholder: 'Cerca persone o digita un nome…',
    Panel_Task_BaselineDueLabel: 'Fine baseline',
    Panel_Task_BaselineHeader: 'Baseline',
    Panel_Task_BaselineStartLabel: 'Inizio baseline',
    Panel_Task_DepTypeFF: 'Fine-Fine (FF)',
    Panel_Task_DepTypeFS: 'Fine-Inizio (FS)',
    Panel_Task_DepTypeSF: 'Inizio-Fine (SF)',
    Panel_Task_DepTypeSS: 'Inizio-Inizio (SS)',
    Panel_Task_LagAriaLabel: 'Ritardo in giorni lavorativi per {taskTitle}',
    Panel_Task_LagHint: 'Il ritardo è espresso in giorni lavorativi. Usa un numero negativo per un anticipo.',
    Panel_Task_LinkTypeAriaLabel: 'Tipo di collegamento per {taskTitle}',
    Panel_Task_VarianceEarlier: '{days} giorno/i lavorativo/i in anticipo',
    Panel_Task_VarianceLater: '{days} giorno/i lavorativo/i in ritardo',
    Panel_Task_VarianceOnBaseline: 'in linea con la baseline',
    View_Dashboard_BurndownActual: 'Effettivo',
    View_Dashboard_BurndownAria: 'Grafico burndown: {remaining} attività rimanenti su {total}',
    View_Dashboard_BurndownHeader: 'Burndown (attività rimanenti)',
    View_Dashboard_BurndownIdeal: 'Ideale',
    View_Dashboard_BurndownNoData: 'Attività con date insufficienti per disegnare un burndown.',
    View_Dashboard_CriticalPathHeader: 'Percorso critico  ({count})',
    View_Dashboard_PhaseDoneSummary: '{done}/{total} completate  •  {percent}%',
    View_Dashboard_TaskRowAriaLabel: 'Apri l\'attività {taskTitle}, {status}',
    View_Dashboard_WorkloadHeader: 'Carico di lavoro per assegnatario',
    View_Dashboard_WorkloadOpen: '{count} aperte',
    View_Dashboard_WorkloadOverdue: '{count} in ritardo',
    View_Kanban_AddTaskInColumnAriaLabel: 'Aggiungi attività a {column}',
    View_Kanban_CollapseColumn: 'Comprimi la colonna {column}',
    View_Kanban_ExpandColumn: 'Espandi la colonna {column}',
    View_Kanban_LaneHeader: '{name} ({count})',
    View_Kanban_LaneNoPhase: 'Nessuna fase',
    View_Kanban_LaneUnassigned: 'Non assegnato',
    View_Kanban_LanesAssignee: 'Assegnatario',
    View_Kanban_LanesNone: 'Nessuna',
    View_Kanban_LanesPhase: 'Fase',
    View_Kanban_SwimlanesLabel: 'Corsie',
    View_Kanban_WipEditTitle: 'Imposta il limite di lavoro in corso per {column} (0 per nessun limite)',
    View_Kanban_WipExceededTitle: 'Limite WIP superato: {count} su {limit}',
    View_Kanban_WipInputAriaLabel: 'Limite WIP per {column}',
    View_Kanban_WipLabel: 'WIP {count}/{limit}',
    View_Kanban_WipSet: 'WIP',
    View_List_BulkAssignApply: 'Assegna',
    View_List_BulkAssigneePlaceholder: 'Assegna a…',
    View_List_BulkBarAriaLabel: 'Azioni in blocco per le attività selezionate',
    View_List_BulkClear: 'Cancella selezione',
    View_List_BulkDelete: 'Elimina selezionate',
    View_List_BulkPercentApply: 'Imposta %',
    View_List_BulkPercentPlaceholder: '% completamento',
    View_List_BulkPriorityPlaceholder: 'Imposta priorità…',
    View_List_BulkSelectedCount: '{count} selezionate',
    View_List_BulkStatusPlaceholder: 'Imposta stato…',
    View_List_ExportCsv: 'Esporta CSV',
    View_List_NonWorkingDay: 'Giorno non lavorativo',
    View_List_SelectAllAriaLabel: 'Seleziona tutte le attività',
    View_List_SelectRowAriaLabel: 'Seleziona {taskTitle}',
    View_Portfolio_CardAriaLabel: 'Apri il progetto {projectName}, {status}',
    View_Portfolio_ClearFilters: 'Cancella filtri',
    View_Portfolio_FilteredCount: '{shown} di {total} progetti',
    View_Portfolio_HideDone: 'Nascondi completati / annullati',
    View_Portfolio_NoMatches: 'Nessun progetto corrisponde ai filtri.',
    View_Portfolio_ProjectCountMany: '{count} progetti',
    View_Portfolio_ProjectCountOne: '{count} progetto',
    View_Portfolio_SearchAriaLabel: 'Cerca progetti',
    View_Portfolio_SearchPlaceholder: 'Cerca progetti…',
    Import_Panel_CopyDetails: 'Copia dettagli',
    Import_Panel_Copied: 'Copiato',
  };
});
