define([], function () {
  return {
    // ── Property pane ──
    PropertyPane_HeaderDescription: 'Smart Gantt Chart の設定',
    PropertyPane_GeneralGroupName: '全般',
    PropertyPane_TitleFieldLabel: 'Web パーツのタイトル',
    WebPart_DefaultTitle: 'Smart Gantt Chart',

    // ── Toolbar ──
    Toolbar_ViewDashboard: 'ダッシュボード',
    Toolbar_ViewList: 'リスト',
    Toolbar_ViewGantt: 'ガント',
    Toolbar_ViewKanban: 'かんばん',
    Toolbar_ZoomDay: '日',
    Toolbar_ZoomWeek: '週',
    Toolbar_ZoomMonth: '月',
    Toolbar_ZoomQuarter: '四半期',
    Toolbar_SelectProjectAriaLabel: 'プロジェクトを選択',
    Toolbar_PortfolioLabel: 'ポートフォリオ',
    Toolbar_SelectAProject: 'プロジェクトを選択',
    Toolbar_AllProjectsSubtext: 'すべてのプロジェクト',
    Toolbar_NoProjectsYet: 'まだプロジェクトがありません',
    Toolbar_ArchivedBadge: 'アーカイブ済み',
    Toolbar_ShowArchivedProjects: 'アーカイブ済みプロジェクトを表示',
    Toolbar_NewProject: '+ 新しいプロジェクト',
    Toolbar_ImportFileAsNewProject: '📥 ファイルを新しいプロジェクトとしてインポート…',
    Toolbar_AddTask: '+ タスクを追加',
    Toolbar_EditProject: 'プロジェクトを編集',
    Toolbar_OptionsButton: '⚙ オプション',
    Toolbar_MoreOptionsTitle: 'その他のオプション',
    Toolbar_ExportToExcel: '📊 Excel にエクスポート',
    Toolbar_ExportToPowerPoint: '📑 PowerPoint にエクスポート',
    Toolbar_ScrollToTodayTitle: '今日の位置へ移動',
    Toolbar_TodayButton: '◉ 今日',
    Toolbar_ImportTasks: '📥 タスクをインポート…',
    Toolbar_ExportAsImage: '🖼 画像としてエクスポート (PNG)',
    Toolbar_UnarchiveProject: '📂 プロジェクトのアーカイブを解除',
    Toolbar_ArchiveProject: '🗄️ プロジェクトをアーカイブ',
    Toolbar_SendToRecycleBin: '🗑️ ごみ箱へ移動',

    // ── Filter bar ──
    FilterBar_ClearOption: 'クリア',
    FilterBar_DueAny: 'すべての期限',
    FilterBar_DueOverdue: '期限超過',
    FilterBar_DueToday: '今日が期限',
    FilterBar_DueWeek: '7日以内に期限',
    FilterBar_SearchPlaceholder: 'タスクを検索…',
    FilterBar_SearchAriaLabel: 'タスクを検索',
    FilterBar_StatusChipLabel: 'ステータス',
    FilterBar_PriorityChipLabel: '優先度',
    FilterBar_AssigneeChipLabel: '担当者',
    FilterBar_PhaseChipLabel: 'フェーズ',
    FilterBar_DueDateAriaLabel: '期限でフィルター',
    FilterBar_MatchCount: '{totalCount} 件中 {matchCount} 件',
    FilterBar_ClearFilters: '✕ フィルターをクリア',
    FilterBar_ChipLabelWithCount: '{label} ({count}) ▾',
    FilterBar_ChipLabelNoCount: '{label} ▾',

    // ── Gantt view ──
    Gantt_TaskColumnHeader: 'タスク',
    Gantt_DurationColumnHeader: '期間',
    Gantt_AddTaskButton: '+ タスクを追加',
    Gantt_EmptyTitle: 'まだタスクがありません',
    Gantt_EmptySubtitle: 'タスクを追加するとガントチャートに表示されます。',
    Gantt_AddFirstTask: '+ 最初のタスクを追加',
    Gantt_ImportTasksButton: '📥 タスクをインポート',
    Gantt_EditTitle: '編集',
    Gantt_DeleteTitle: '削除',
    Gantt_EditTaskAriaLabel: 'タスク {taskTitle} を編集',
    Gantt_DeleteTaskAriaLabel: 'タスク {taskTitle} を削除',
    Gantt_ExpandPhaseAriaLabel: 'フェーズ {phase} を{action}',
    Gantt_ExpandAction: '展開',
    Gantt_CollapseAction: '折りたたみ',
    Gantt_DependencyViolationTooltip: 'すべての依存タスクが完了する前に開始されました',
    Gantt_MilestoneAriaLabel: '{taskTitle}、マイルストーン、{date}',
    Gantt_BarAriaLabel: '{taskTitle}、{startDate} から {dueDate}、{percent}% 完了',
    Gantt_PercentCompleteTooltip: '{value}% 完了',

    // ── Gantt options/settings panel ──
    GanttSettings_PanelHeader: '⚙ オプション',
    GanttSettings_ColorCodingSection: 'カラーコーディング',
    GanttSettings_ByStatus: 'ステータス別',
    GanttSettings_ByPriority: '優先度別',
    GanttSettings_ByPhase: 'フェーズ別',
    GanttSettings_ByHealth: '健全性別',
    GanttSettings_HeaderColorSection: 'ヘッダーの色',
    GanttSettings_ThemeDark: 'ダーク',
    GanttSettings_ThemeNavy: 'ネイビー',
    GanttSettings_ThemeTeal: 'ティール',
    GanttSettings_ThemePurple: 'パープル',
    GanttSettings_ThemeLight: 'ライト',
    GanttSettings_HeaderLabelsSection: 'ヘッダーラベル',
    GanttSettings_WeekLabelDates: '日付',
    GanttSettings_WeekLabelDatesDesc: '6月3日、6月10日…',
    GanttSettings_WeekLabelProject: 'プロジェクト週',
    GanttSettings_WeekLabelProjectDesc: 'W1、W2…',
    GanttSettings_WeekLabelIso: 'カレンダー週',
    GanttSettings_WeekLabelIsoDesc: 'W23、W24…',
    GanttSettings_ProjectWeeksHint: '第1週は最初のタスクの月曜日から始まります。プレゼンテーションに最適です。',
    GanttSettings_BarStyleSection: 'バーのスタイル',
    GanttSettings_BarStyleGradient: 'グラデーション',
    GanttSettings_BarStyleFlat: 'フラット',
    GanttSettings_RowHeightSection: '行の高さ',
    GanttSettings_HeightCompact: 'コンパクト',
    GanttSettings_HeightNormal: '標準',
    GanttSettings_HeightSpacious: 'ゆったり',
    GanttSettings_ShowHideSection: '表示 / 非表示',
    GanttSettings_WeekendShading: '週末の網掛け',
    GanttSettings_DependencyArrows: '依存関係の矢印',
    GanttSettings_CriticalPathAlwaysVisible: 'クリティカルパスを常に表示',
    GanttSettings_AllOthersOnHoverOnly: '他はホバー時のみ表示',
    GanttSettings_CriticalPathHighlight: 'クリティカルパスの強調表示',
    GanttSettings_ProgressPercentOnBars: 'バーに進捗率を表示',
    GanttSettings_AssigneeNameOnBars: 'バーに担当者名を表示',
    GanttSettings_HealthStatusBadges: '健全性ステータスバッジ',

    // ── List view ──
    ListView_ColTaskName: 'タスク名',
    ListView_ColStatus: 'ステータス',
    ListView_ColHealth: '健全性',
    ListView_ColPriority: '優先度',
    ListView_ColStart: '開始日',
    ListView_ColDue: '期限',
    ListView_ColAssignedTo: '担当者',
    ListView_ColProgress: '進捗',
    ListView_ColPhase: 'フェーズ',
    ListView_ColPredecessors: '先行タスク',
    ListView_EmptyTitle: 'まだタスクがありません',
    ListView_AddFirstTask: '+ 最初のタスクを追加',
    ListView_AddTaskRow: '+ タスクを追加',
    ListView_Unassigned: '未割り当て',
    ListView_DependencyViolationTooltip: 'すべての依存タスクが完了する前に開始されました',
    ListView_StatusAriaLabel: '{taskTitle} のステータス',
    ListView_PriorityAriaLabel: '{taskTitle} の優先度',
    ListView_EditTaskAriaLabel: 'タスク {taskTitle} を編集',
    ListView_DeleteTaskAriaLabel: 'タスク {taskTitle} を削除',
    ListView_EditTitle: '編集',
    ListView_DeleteTitle: '削除',

    // ── Kanban view ──
    Kanban_ColumnNotStarted: '未着手',
    Kanban_ColumnInProgress: '進行中',
    Kanban_ColumnOnHold: '保留中',
    Kanban_ColumnCompleted: '完了',
    Kanban_ColumnCancelled: 'キャンセル',
    Kanban_AddTaskButton: '+ タスクを追加',
    Kanban_EditTitle: '編集',
    Kanban_DeleteTitle: '削除',
    Kanban_CardAriaLabel: '{taskTitle}、{status}。Enter キーで編集、左右矢印キーでステータスを変更します。',
    Kanban_EditTaskAriaLabel: 'タスク {taskTitle} を編集',
    Kanban_DeleteTaskAriaLabel: 'タスク {taskTitle} を削除',

    // ── Dashboard view ──
    Dashboard_TotalTasks: 'タスク総数',
    Dashboard_Completed: '完了',
    Dashboard_InProgress: '進行中',
    Dashboard_OnHold: '保留中',
    Dashboard_NotStarted: '未着手',
    Dashboard_Cancelled: 'キャンセル',
    Dashboard_OverallProgress: '全体の進捗',
    Dashboard_ProjectManagerLabel: 'プロジェクトマネージャー: {name}',
    Dashboard_PhaseProgressHeader: 'フェーズ別進捗',
    Dashboard_StatusBreakdownHeader: 'ステータス内訳',
    Dashboard_PriorityBreakdownHeader: '優先度内訳',
    Dashboard_PriorityCritical: '最重要',
    Dashboard_PriorityHigh: '高',
    Dashboard_PriorityMedium: '中',
    Dashboard_PriorityLow: '低',
    Dashboard_OverdueHeader: '期限超過  ({count})',
    Dashboard_DueNext14DaysHeader: '今後14日以内の期限  ({count})',
    Dashboard_CompletedThisWeekHeader: '今週完了',
    Dashboard_UpdatedThisWeekHeader: '今週更新',
    Dashboard_Today: '今日',
    Dashboard_Tomorrow: '明日',
    Dashboard_DaysLeft: '残り{days}日',
    Dashboard_EmptyTitle: 'まだタスクがありません',
    Dashboard_EmptySubtitle: 'タスクを追加するとプロジェクトダッシュボードが表示されます。',
    Dashboard_AddTaskButton: '+ タスクを追加',

    // ── Portfolio view ──
    Portfolio_ProjectCount: '{count} 件のプロジェクト',
    Portfolio_OnTrackSummary: '順調 {count} 件',
    Portfolio_AtRiskSummary: 'リスクあり {count} 件',
    Portfolio_OverdueSummary: '期限超過 {count} 件',
    Portfolio_DoneSummary: '完了 {count} 件',
    Portfolio_SortLabel: '並べ替え:',
    Portfolio_SortAZ: 'A-Z',
    Portfolio_SortHealth: '健全性',
    Portfolio_SortStatus: 'ステータス',
    Portfolio_SortCompletion: '完了率',
    Portfolio_RefreshTitle: '更新',
    Portfolio_RefreshButton: '更新',
    Portfolio_LoadingStats: '統計情報を読み込み中…',
    Portfolio_EmptyTitle: 'まだプロジェクトがありません',
    Portfolio_CreateFirstProject: '+ 最初のプロジェクトを作成',
    Portfolio_StatsUnavailable: '統計情報を利用できません',
    Portfolio_StatsUnavailableDetail: 'このプロジェクトの統計情報を読み込めませんでした。',
    Portfolio_OverallProgressLabel: '全体の進捗',
    Portfolio_TaskCountDone: '完了',
    Portfolio_TaskCountActive: '対応中',
    Portfolio_TaskCountAtRisk: 'リスクあり',
    Portfolio_TaskCountOverdue: '期限超過',
    Portfolio_ViewGanttLink: 'ガントを表示 →',
    Portfolio_TodayTooltip: '今日',

    // ── Task panel ──
    TaskPanel_EditHeader: '編集: {taskTitle}',
    TaskPanel_NewTaskHeader: '新しいタスク',
    TaskPanel_TabBasic: '基本情報',
    TaskPanel_TabDetails: '詳細',
    TaskPanel_TabLinks: 'リンク',
    TaskPanel_ProjectLabelPrefix: 'プロジェクト: ',
    TaskPanel_TaskNameLabel: 'タスク名',
    TaskPanel_TaskNamePlaceholder: 'タスク名を入力',
    TaskPanel_TaskNameRequired: 'タスク名は必須です',
    TaskPanel_DescriptionLabel: '説明',
    TaskPanel_DescriptionPlaceholder: '説明を入力',
    TaskPanel_StartDateLabel: '開始日',
    TaskPanel_DueDateLabel: '期限',
    TaskPanel_DueDateError: '期限は開始日以降にしてください',
    TaskPanel_StatusLabel: 'ステータス',
    TaskPanel_PriorityLabel: '優先度',
    TaskPanel_PercentCompleteLabel: '進捗率: {percent}%',
    TaskPanel_AssignedToLabel: '担当者',
    TaskPanel_AssignedToPlaceholder: '担当者を検索…',
    TaskPanel_PhaseLabel: 'フェーズ',
    TaskPanel_PhasePlaceholder: 'フェーズ名を入力',
    TaskPanel_PhaseHint: 'ガントおよびリストビューでタスクをグループ化します。',
    TaskPanel_MilestoneLabel: 'マイルストーン',
    TaskPanel_MilestoneOnText: 'はい',
    TaskPanel_MilestoneOffText: 'いいえ',
    TaskPanel_CustomBarColorLabel: 'カスタムバーの色',
    TaskPanel_CustomBarColorOptionalSuffix: '（任意）',
    TaskPanel_AutoColorHint: 'ステータス／優先度／フェーズの設定に基づいて自動的に色を設定します。',
    TaskPanel_NotesLabel: 'メモ',
    TaskPanel_NotesPlaceholder: 'メモを入力',
    TaskPanel_ParentTaskLabel: '親タスク',
    TaskPanel_ParentTaskNone: '（なし）',
    TaskPanel_ParentTaskHasChildrenHint: 'このタスクにはサブタスクがあるため、親タスクを設定できません。',
    TaskPanel_ParentTaskHint: 'このタスクを別のタスクの下にサブタスクとしてネストします。',
    TaskPanel_DependsOnLabel: '依存関係',
    TaskPanel_RemoveDependencyTitle: '"{taskTitle}" への依存を削除',
    TaskPanel_AddDependencyPlaceholder: '依存関係を追加…',
    TaskPanel_SelectATaskOption: 'タスクを選択…',
    TaskPanel_DependsOnHint: 'これらのタスクが完了するまで、このタスクは開始できません。',
    TaskPanel_SavingLabel: '保存中…',
    TaskPanel_CreatingLabel: '作成中…',
    TaskPanel_SaveChangesButton: '変更を保存',
    TaskPanel_CreateTaskButton: 'タスクを作成',
    TaskPanel_CancelButton: 'キャンセル',
    TaskPanel_DismissAriaLabel: '閉じる',
    TaskPanel_DiscardUnsavedChangesConfirm: '保存されていない変更を破棄しますか?',
    TaskPanel_SaveFallbackError: 'タスクを保存できませんでした。',

    // ── Project panel ──
    ProjectPanel_EditHeader: 'プロジェクトを編集',
    ProjectPanel_NewHeader: '新しいプロジェクト',
    ProjectPanel_ProjectNameLabel: 'プロジェクト名',
    ProjectPanel_ProjectNamePlaceholder: 'プロジェクト名を入力',
    ProjectPanel_ProjectNameRequired: 'プロジェクト名は必須です',
    ProjectPanel_DescriptionLabel: '説明',
    ProjectPanel_DescriptionPlaceholder: '説明を入力',
    ProjectPanel_ProjectColorLabel: 'プロジェクトの色',
    ProjectPanel_StatusLabel: 'ステータス',
    ProjectPanel_StartDateLabel: '開始日',
    ProjectPanel_DueDateLabel: '期限',
    ProjectPanel_DueDateError: '期限は開始日以降にしてください',
    ProjectPanel_WhatHappensNextTitle: '次に何が起こりますか?',
    ProjectPanel_WhatHappensNextBody: 'プロジェクトを作成すると、タスクの追加、フェーズの設定、進捗の追跡ができるようになります。',
    ProjectPanel_SavingLabel: '保存中…',
    ProjectPanel_CreatingLabel: '作成中…',
    ProjectPanel_SaveChangesButton: '変更を保存',
    ProjectPanel_CreateProjectButton: 'プロジェクトを作成',
    ProjectPanel_CancelButton: 'キャンセル',
    ProjectPanel_DismissAriaLabel: '閉じる',
    ProjectPanel_DiscardUnsavedChangesConfirm: '保存されていない変更を破棄しますか?',
    ProjectPanel_SaveFallbackError: 'プロジェクトを保存できませんでした。',

    // ── Import panel ──
    ImportPanel_SourceExcelTitle: 'Excel / CSV ファイル',
    ImportPanel_SourceExcelSubtitle: 'スプレッドシートからタスクをインポート',
    ImportPanel_SourcePlannerTitle: 'Microsoft Planner',
    ImportPanel_SourcePlannerSubtitle: 'Planner のプランからタスクをインポート',
    ImportPanel_ClickToBrowse: 'クリックして参照',
    ImportPanel_DragDropSuffix: '、またはドラッグ アンド ドロップ',
    ImportPanel_SupportedExtensions: '.xlsx、.xls、.csv に対応',
    ImportPanel_RowsColsSummary: '{rows} 行、{cols} 列を検出しました',
    ImportPanel_LoadingPlannerPlans: 'Planner のプランを読み込み中…',
    ImportPanel_PlannerLoadError: 'Planner のプランを読み込めませんでした。',
    ImportPanel_PlannerPermissionsHintPrefix: 'Planner へのアクセス権があること、および ',
    ImportPanel_PlannerPermissionsHintEmphasis: 'Planner と To Do によるタスク',
    ImportPanel_PlannerPermissionsHintSuffix: ' がこのサイトで利用可能であることを確認してください。',
    ImportPanel_NoPlannerPlansFoundTitle: 'Planner のプランが見つかりません',
    ImportPanel_NoPlannerPlansFoundBody: 'Planner のプランへのアクセス権がないか、このアカウントにはプランが存在しない可能性があります。',
    ImportPanel_TaskCountFoundIn: '"{planName}" に {count} 件のタスクが見つかりました',
    ImportPanel_ProjectDetailsIntroPrefix: 'インポート先: ',
    ImportPanel_ProjectDetailsIntroSuffix: '。以下のプロジェクト詳細を確認してください。',
    ImportPanel_ProjectNameLabel: 'プロジェクト名',
    ImportPanel_DescriptionLabel: '説明',
    ImportPanel_StatusLabel: 'ステータス',
    ImportPanel_ColorLabel: '色',
    ImportPanel_MapIntro: 'ファイルの列をタスクのフィールドにマッピングします。',
    ImportPanel_CreatingProjectStatus: 'プロジェクトを作成中…',
    ImportPanel_ImportingTasksStatus: 'タスクをインポート中…',
    ImportPanel_ProgressLabel: '{total} 件中 {done} 件',
    ImportPanel_CouldNotCreateProject: 'プロジェクトを作成できませんでした。',
    ImportPanel_ImportCompletedWithErrors: 'インポートが完了しましたが、{count} 件のエラーがあります。',
    ImportPanel_ProjectCreatedSuccess: 'プロジェクトを作成しました。',
    ImportPanel_ImportSuccessful: 'インポートが完了しました。',
    ImportPanel_TasksAddedTo: '{count} 件のタスクを "{projectName}" に追加しました',
    ImportPanel_FailedRowsLabel: '失敗した行:',
    ImportPanel_CloseButton: '閉じる',
    ImportPanel_OpenProjectButton: 'プロジェクトを開く',
    ImportPanel_ViewImportedTasksButton: 'インポートしたタスクを表示',
    ImportPanel_NextMapColumnsButton: '次へ: 列をマッピング',
    ImportPanel_ImportNTasksButton: '{count} 件のタスクをインポート',
    ImportPanel_BackButton: '戻る',
    ImportPanel_CancelButton: 'キャンセル',
    ImportPanel_NextButton: '次へ',
    ImportPanel_StepSource: 'ソース',
    ImportPanel_StepProject: 'プロジェクト',
    ImportPanel_StepMap: 'マッピング',
    ImportPanel_StepImport: 'インポート',
    ImportPanel_StepDone: '完了',
    ImportPanel_ImportAsNewProjectHeader: 'ファイルを新しいプロジェクトとしてインポート',
    ImportPanel_ImportIntoProjectHeader: '{projectName} にタスクをインポート',
    ImportPanel_CouldNotParseFile: 'ファイルを解析できませんでした。',
    ImportPanel_CouldNotLoadPlannerTasks: 'このプランからタスクを読み込めませんでした。',
    ImportPanel_CouldNotCreateProjectDetail: 'プロジェクトを作成できませんでした: {detail}',
    ImportPanel_CouldNotLinkDependencies: '依存関係をリンクできませんでした: {detail}',
    ImportPanel_UnknownError: '不明なエラー',

    // ── Column mapper (import) ──
    ColumnMapper_TaskNameRequiredBanner: '続行するにはタスク名をマッピングする必要があります。',
    ColumnMapper_SkippedColumnsBanner: '{count} 個の列がスキップされます。',
    ColumnMapper_SourceColumnHeader: '元の列',
    ColumnMapper_TargetFieldHeader: '対象フィールド',
    ColumnMapper_StatusHeader: 'ステータス',
    ColumnMapper_SkippedBadge: 'スキップ',
    ColumnMapper_AutoMappedBadge: '自動マッピング済み',
    ColumnMapper_SetBadge: '設定済み',
    ColumnMapper_PreviewTitle: 'プレビュー: {columnName}',
    ColumnMapper_EmptyCellDash: '—',

    // ── Import field display names / ImportService ──
    ImportField_TaskName: 'タスク名',
    ImportField_StartDate: '開始日',
    ImportField_DueDate: '期限',
    ImportField_Status: 'ステータス',
    ImportField_Priority: '優先度',
    ImportField_AssignedTo: '担当者',
    ImportField_AssignedToEmail: '担当者のメールアドレス',
    ImportField_PercentComplete: '進捗率',
    ImportField_Phase: 'フェーズ',
    ImportField_Description: '説明',
    ImportField_Notes: 'メモ',
    ImportField_IsMilestone: 'マイルストーンかどうか',
    ImportField_Dependencies: '依存関係',
    ImportField_SkipColumn: '（この列をスキップ）',
    ImportService_EmptyFileError: 'ファイルが空か、データ行が含まれていないようです。',
    ImportService_ReadErrorDetail: 'ファイルを読み込めませんでした: {detail}。',
    ImportService_FileReadError: 'ファイルの読み込みエラーです。',
    ImportService_RowError: '行 {rowNum} ("{title}"): {error}',
    ImportService_AmbiguousDependency: '依存関係 "{name}" が複数のタスク名と一致するため、スキップしました。',
    ImportService_LinkDependencyError: 'タスク {taskId} の依存関係をリンクできませんでした: {error}',

    // ── Health labels (shared: healthUtils.ts and ExportService.ts both use this set; also replaces the duplicated Export_PortfolioHealthLabel* keys) ──
    Health_Done: '完了',
    Health_OnTrack: '順調',
    Health_AtRisk: 'リスクあり',
    Health_Overdue: '期限超過',

    // ── Status / Priority display labels (DISPLAY-ONLY — stored SharePoint Choice values remain unchanged/English) ──
    Status_NotStarted: '未着手',
    Status_InProgress: '進行中',
    Status_Completed: '完了',
    Status_OnHold: '保留中',
    Status_Cancelled: 'キャンセル',
    Priority_Critical: '最重要',
    Priority_High: '高',
    Priority_Medium: '中',
    Priority_Low: '低',
    ProjectStatus_Planning: '計画中',
    ProjectStatus_Active: '進行中',
    ProjectStatus_OnHold: '保留中',
    ProjectStatus_Completed: '完了',
    ProjectStatus_Cancelled: 'キャンセル',

    // ── Shell (SmartGantt.tsx) ──
    SmartGantt_LoadingProjects: 'プロジェクトを読み込み中…',
    SmartGantt_UnableToLoad: '読み込めません',
    SmartGantt_RetryButton: '再試行',
    SmartGantt_NoProjectsYet: 'まだプロジェクトがありません',
    SmartGantt_NoProjectsSubtitle: '最初のプロジェクトを作成して始めましょう。',
    SmartGantt_CreateFirstProjectButton: '+ 最初のプロジェクトを作成',
    SmartGantt_ImportFromExcelButton: '📥 Excel からインポート',
    SmartGantt_LoadingTasks: 'タスクを読み込み中…',
    SmartGantt_DismissAriaLabel: '閉じる',
    SmartGantt_DeleteTaskDialogTitle: 'タスクを削除',
    SmartGantt_DeleteTaskDialogSubtext: '"{taskTitle}" を削除しますか? この操作は元に戻せません。',
    SmartGantt_DeleteButton: '削除',
    SmartGantt_CancelButton: 'キャンセル',
    SmartGantt_ArchiveProjectDialogTitle: 'プロジェクトをアーカイブ',
    SmartGantt_ArchiveProjectDialogSubtext: '"{projectTitle}" をアーカイブしますか? 後で解除できます。',
    SmartGantt_ArchiveButton: 'アーカイブ',
    SmartGantt_SendToRecycleBinDialogTitle: 'ごみ箱へ移動',
    SmartGantt_SendToRecycleBinDialogSubtext: '"{projectTitle}" をサイトのごみ箱へ移動しますか?',
    SmartGantt_SendToRecycleBinButton: 'ごみ箱へ移動',
    SmartGantt_FailedLoadProjects: 'プロジェクトを読み込めませんでした。サイトのアクセス許可を確認してください。',
    SmartGantt_FailedLoadTasks: 'このプロジェクトのタスクを読み込めませんでした。',
    SmartGantt_FailedLoadPortfolioStats: 'ポートフォリオの統計情報を読み込めませんでした。',
    SmartGantt_CouldNotSaveProject: 'プロジェクトを保存できませんでした: {message}',
    SmartGantt_CouldNotDeleteProject: 'プロジェクトを削除できませんでした: {message}',
    SmartGantt_CouldNotArchiveProject: 'プロジェクトをアーカイブできませんでした: {message}',
    SmartGantt_CouldNotUnarchiveProject: 'プロジェクトのアーカイブを解除できませんでした: {message}',
    SmartGantt_CouldNotSaveTask: 'タスクを保存できませんでした: {message}',
    SmartGantt_CouldNotDeleteTask: 'タスクを削除できませんでした: {message}',
    SmartGantt_ImageExportFailed: '画像のエクスポートに失敗しました: {message}',
    SmartGantt_PowerPointExportFailed: 'PowerPoint のエクスポートに失敗しました: {message}',
    SmartGantt_PortfolioExportFailed: 'ポートフォリオのエクスポートに失敗しました: {message}',
    SmartGantt_CouldNotUpdateTask: 'タスクを更新できませんでした: {message}',

    // ── Common ──
    ColorSwatch_AutoColorAriaLabel: '自動色',
    ColorSwatch_CustomColorAriaLabel: 'カスタムカラー',
    ColorSwatch_PickCustomColorTitle: 'カスタムカラーを選択',

    // ── Export (Excel / PowerPoint) ──
    Export_ColTaskName: 'タスク名',
    Export_ColPhase: 'フェーズ',
    Export_ColStartDate: '開始日',
    Export_ColDueDate: '期限',
    Export_ColStatus: 'ステータス',
    Export_ColPriority: '優先度',
    Export_ColAssignedTo: '担当者',
    Export_ColAssignedToEmail: '担当者のメールアドレス',
    Export_ColPercentComplete: '進捗率',
    Export_ColIsMilestone: 'マイルストーンかどうか',
    Export_ColDescription: '説明',
    Export_ColNotes: 'メモ',
    Export_Yes: 'はい',
    Export_No: 'いいえ',
    Export_SheetNameTasks: 'タスク',
    Export_ExcelFileSuffix: ' - タスク.xlsx',
    Export_TaskNameColumnLabel: 'タスク名',
    Export_ExportedDateLabel: 'エクスポート日: {date}',
    Export_ProjectReportLabel: 'プロジェクトレポート',
    Export_StatusLine: 'ステータス: {status}',
    Export_DateRangeSeparator: ' ～ ',
    Export_ProjectManagerLine: 'プロジェクトマネージャー: {name}',
    Export_GeneratedDateLine: '生成日: {date}',
    Export_ProjectSummaryTitle: 'プロジェクト概要',
    Export_StatTotalTasks: 'タスク総数',
    Export_StatCompleted: '完了',
    Export_StatInProgress: '進行中',
    Export_StatOnHold: '保留中',
    Export_StatNotStarted: '未着手',
    Export_OverallProgressLine: '全体の進捗',
    Export_OverallProgressPercent: '{percent}%',
    Export_StatusBreakdownTitle: 'ステータス内訳',
    Export_StatusBreakdownRow: '{status}: {count} ({percent}%)',
    Export_GanttTimelineTitle: 'ガントタイムライン',
    Export_SummaryRecentActivityTitle: '最近の活動',
    Export_ProjectOverviewLabel: 'プロジェクト概要',
    Export_DetailStatusLabel: 'ステータス',
    Export_DetailStartDateLabel: '開始日',
    Export_DetailDueDateLabel: '期限',
    Export_DetailProjectManagerLabel: 'プロジェクトマネージャー',
    Export_Past7DaysLabel: '過去7日間',
    Export_NoActivityMessage: '最近の活動はありません。',
    Export_CompletedThisWeekHeader: '今週完了 ({count})',
    Export_NewBadge: '新規  ',
    Export_CompletedPercentLine: '{percent}% 完了',
    Export_MoreItemsSuffix: '他 {count} 件',
    Export_InProgressUpdatedHeader: '進行中 / 更新済み',
    Export_StatusPercentLine: '{status} — {percent}%',
    Export_PortfolioReportLabel: 'ポートフォリオレポート',
    Export_PortfolioOverviewTitle: 'ポートフォリオ概要',
    Export_ProjectsCountLine: '{count} 件のプロジェクト',
    Export_HealthSummaryOnTrack: '順調 {count} 件',
    Export_HealthSummaryAtRisk: 'リスクあり {count} 件',
    Export_HealthSummaryOverdue: '期限超過 {count} 件',
    Export_ProjectsSummaryHeader: 'プロジェクト概要',
    Export_TableProject: 'プロジェクト',
    Export_TableStatus: 'ステータス',
    Export_TableHealth: '健全性',
    Export_TableTotal: '合計',
    Export_TableDone: '完了',
    Export_TableActive: '対応中',
    Export_TableAtRisk: 'リスクあり',
    Export_TableOverdue: '期限超過',
    Export_TablePctDone: '完了率',
    Export_TableDueDate: '期限',
    Export_PortfolioSummaryFileName: 'ポートフォリオ概要.xlsx',
    Export_PortfolioReportFileName: 'ポートフォリオレポート.pptx',
    Export_ProjectReportFileName: '{projectName} レポート.pptx',
    Export_UnavailableLabel: '利用できません',
    Export_SheetNamePortfolio: 'ポートフォリオ',
    Export_ColStart: '開始日',
    Export_ColDue: '期限',
    Export_ImageGenerationFailed: '画像を生成できませんでした。チャートが大きすぎて画像として書き出せない可能性があります。',
    Export_DrawingContextFailed: 'エクスポート用の描画コンテキストを作成できませんでした。',
    Export_SvgRenderFailed: 'SVGのレンダリングに失敗しました',

    // ── Added in v1.5 review ──
    Svc_TooManyDependencies: 'このタスクは依存関係が多すぎるため保存できません (上限は約 60 件)。いくつか削除してからもう一度お試しください。',
    Svc_TaskChangedByOthers: 'このタスクは、読み込み後に他のユーザーによって変更されました。更新してからもう一度お試しください。',
    Svc_ProjectChangedByOthers: 'このプロジェクトは、開いた後に他のユーザーによって変更されました。更新してからもう一度お試しください。',
    Svc_ColumnCreateFailed: '新しいタスク リストに {count} 個の列を作成できませんでした: {detail}',
    Svc_BaselineUnavailable: 'ベースライン列を追加できなかったため、このプロジェクトではベースラインを使用できません (リストを編集するためのアクセス許可が必要な場合があります)。',
    Svc_SubtaskReassignFailed: 'このタスクを削除する前に、サブタスクを再割り当てできませんでした: {detail}',
    Svc_UnresolvedDependency: '行 {row} ("{title}"): 依存関係 "{name}" をインポートしたタスクと照合できませんでした。',
    Svc_SelfDependency: '行 {row} ("{title}"): 依存関係 "{name}" はタスク自身を指しているため、スキップされました。',
    Svc_ColId: 'ID',
    Svc_ColDependencies: '依存関係',
    Svc_ColBaselineStart: 'ベースライン開始日',
    Svc_ColBaselineDue: 'ベースライン期限',
    Svc_CsvFileSuffix: ' - Tasks.csv',
    Svc_IcsFileSuffix: ' - Milestones.ics',
    Svc_PortfolioCsvFileName: 'Portfolio Summary.csv',
    Svc_PP_DisplayGroup: '既定値',
    Svc_PP_DefaultView: '既定のビュー',
    Svc_PP_ViewGantt: 'ガント',
    Svc_PP_ViewList: 'リスト',
    Svc_PP_ViewKanban: 'かんばん',
    Svc_PP_ViewDashboard: 'ダッシュボード',
    Svc_PP_ViewPortfolio: 'ポートフォリオ',
    Svc_PP_DefaultZoom: '既定のズーム',
    Svc_PP_ZoomDay: '日',
    Svc_PP_ZoomWeek: '週',
    Svc_PP_ZoomMonth: '月',
    Svc_PP_ZoomQuarter: '四半期',
    Svc_PP_CalendarGroup: '稼働カレンダー',
    Svc_PP_DaySun: '日曜日は稼働日',
    Svc_PP_DayMon: '月曜日は稼働日',
    Svc_PP_DayTue: '火曜日は稼働日',
    Svc_PP_DayWed: '水曜日は稼働日',
    Svc_PP_DayThu: '木曜日は稼働日',
    Svc_PP_DayFri: '金曜日は稼働日',
    Svc_PP_DaySat: '土曜日は稼働日',
    Svc_PP_Holidays: '休日 (非稼働日)',
    Svc_PP_HolidaysHint: '1 行に 1 つの日付を yyyy-MM-dd 形式で入力してください (例: 2026-12-25)。',
    Gantt_TimelineAriaLabel: 'タスク タイムライン',
    Gantt_DragLabel: '{start} → {end} ({days}日)',
    Gantt_KeyboardMoveAnnouncement: '{taskTitle}: {startDate} から {dueDate}',
    Gantt_KeyboardHint: 'Enter キーでタスクを開きます。左右の方向キーで 1 稼働日ずつ移動します。Shift キーと方向キーで終了日を変更します。',
    Gantt_ParentCycleTooltip: 'このタスクは親タスクとサブタスクの循環チェーンに含まれているため、最上位レベルに表示されています',
    Gantt_CollapseAll: 'すべてのフェーズを折りたたむ',
    Gantt_ExpandAll: 'すべてのフェーズを展開',
    Gantt_BaselineTooltip: 'ベースライン: {start} → {due}',
    Gantt_VarianceTooltip: '完了日の差異: ベースラインとの差 {days} 日',
    Gantt_LinkHandleTitle: '別のタスクにドラッグして依存関係を作成',
    Toolbar_FitToProject: '全体表示',
    Toolbar_FitToProjectTitle: 'プロジェクト全体が収まるようにズーム',
    Toolbar_UndoTitle: '元に戻す (Ctrl+Z)',
    Toolbar_RedoTitle: 'やり直し (Ctrl+Y)',
    Toolbar_ExportCsv: '📄 タスクを CSV にエクスポート',
    Toolbar_ExportIcs: '📅 マイルストーンをエクスポート (iCal)',
    Toolbar_Print: '🖨 印刷 / PDF として保存',
    Toolbar_SetBaseline: '📐 ベースラインを設定…',
    Toolbar_CopyLink: '🔗 リンクをコピー',
    Toolbar_CopyLinkTitle: 'このビュー (プロジェクト、ビュー、ズーム、フィルター) へのリンクをコピー',
    App_UndoButton: '元に戻す',
    App_Undone: '変更を元に戻しました。',
    App_Redone: '変更をやり直しました。',
    App_DependentsMovedOne: '後続タスク 1 件を移動しました。',
    App_DependentsMovedMany: '後続タスク {count} 件を移動しました。',
    App_TaskConflict: 'このタスクは他のユーザーによって変更されました。最新のタスクを再読み込みしました。内容を確認してからもう一度お試しください。',
    App_DependencyCycle: 'そのリンクを作成すると循環依存になります。',
    App_DependencyExists: 'これらのタスクは既にリンクされています。',
    App_LinkCopied: 'リンクをクリップボードにコピーしました。',
    App_LinkCopyFailed: 'リンクをコピーできませんでした: {message}',
    App_PopupBlocked: '印刷ウィンドウがブロックされました。このサイトのポップアップを許可してからもう一度お試しください。',
    App_SetBaselineDialogTitle: 'ベースラインを設定',
    App_SetBaselineDialogSubtext: '全 {count} 件のタスクの現在の開始日と期限をベースラインとして保存しますか? 既存のベースラインは置き換えられます。',
    App_SetBaselineButton: 'ベースラインを設定',
    App_BaselineSaved: 'ベースラインを保存しました。',
    App_BaselineFailed: 'ベースラインを保存できませんでした: {message}',
    App_CsvExportFailed: 'CSV のエクスポートに失敗しました: {message}',
    App_IcsExportFailed: 'カレンダーのエクスポートに失敗しました: {message}',
    App_BulkDeleteDialogTitle: 'タスクを削除',
    App_BulkDeleteDialogSubtext: '{count} 件のタスクを削除してもよろしいですか? この操作は元に戻せません。',
    Common_PeoplePicker_ClearAriaLabel: 'クリア',
    Common_PeoplePicker_DirectoryHeader: 'ディレクトリ内のユーザー',
    Common_PeoplePicker_EmailLabel: 'メール (省略可)',
    Common_PeoplePicker_EmailPlaceholder: 'name@company.com',
    Common_PeoplePicker_ExternalHint: 'ディレクトリにありません。テキストとして保存されます。',
    Common_PeoplePicker_InvalidEmail: '有効なメール アドレスを入力してください。',
    Common_PeoplePicker_ListAriaLabel: 'ユーザーの候補',
    Common_PeoplePicker_RecentHeader: '最近使用したユーザー',
    Common_PeoplePicker_ResultsAnnouncement: '{count} 件の候補があります',
    Common_PeoplePicker_Searching: '検索中…',
    Common_PeoplePicker_UseExternal: '“{name}” を使用 (外部 / ディレクトリにありません)',
    Import_Mapper_PreviewFirstRows: 'プレビュー (先頭 {count} 行)',
    Import_Mapper_RequiredLegend: '必須フィールド',
    Import_Mapper_RequiredMarkerLabel: '必須',
    Import_Mapper_SelectAriaLabel: '列 {columnName} の対象フィールド',
    Import_Panel_DateOrderAuto: '自動検出',
    Import_Panel_DateOrderDMY: '日/月/年 (31/12/2026)',
    Import_Panel_DateOrderDetected: 'ファイルから検出: {order}。',
    Import_Panel_DateOrderHint: '03/04/2026 のように数字で書かれた日付に適用されます。',
    Import_Panel_DateOrderLabel: '日付の順序',
    Import_Panel_DateOrderMDY: '月/日/年 (12/31/2026)',
    Import_Panel_DropZoneAriaLabel: 'インポートするファイルを選択します。Enter キーで参照します。',
    Import_Panel_DropZoneChangeAriaLabel: '選択したファイル {fileName}。Enter キーで別のファイルを選択します。',
    Import_Panel_FailedCount: '{count} 件失敗',
    Import_Panel_NewProjectIntroMany: '新しいプロジェクトが作成され、{count} 件のタスクすべてがインポートされます。これらの詳細はインポート後いつでも変更できます。',
    Import_Panel_NewProjectIntroOne: '新しいプロジェクトが作成され、{count} 件のタスクがインポートされます。これらの詳細はインポート後いつでも変更できます。',
    Import_Panel_PlanAriaLabel: '{planName}、{groupName}',
    Import_Panel_ProblemEndBeforeStart: '期限が開始日より前になっています',
    Import_Panel_ProblemInvalidDueDate: '期限 "{value}" は有効な日付ではありません',
    Import_Panel_ProblemInvalidStartDate: '開始日 "{value}" は有効な日付ではありません',
    Import_Panel_ProblemMissingTitle: 'タスク名がありません',
    Import_Panel_ProgressLabelWithPercent: '{done} / {total} ({percent}%)',
    Import_Panel_SkipInvalidRows: '問題のある行をスキップ',
    Import_Panel_SuccessWithWarningsMany: 'インポートに成功しました (警告 {count} 件)。',
    Import_Panel_SuccessWithWarningsOne: 'インポートに成功しました (警告 {count} 件)。',
    Import_Panel_ValidationHeader: '問題のある行',
    Import_Panel_ValidationMore: '…ほか {count} 件',
    Import_Panel_ValidationRow: '行 {rowNum}: {problem}',
    Import_Panel_ValidationSummaryMany: '{count} 行に問題があります',
    Import_Panel_ValidationSummaryOne: '{count} 行に問題があります',
    Import_Panel_WarningsLabel: '警告 ({count}):',
    Panel_Project_ManagerLabel: 'プロジェクト マネージャー',
    Panel_Project_ManagerPlaceholder: 'ユーザーを検索するか、名前を入力…',
    Panel_Task_BaselineDueLabel: 'ベースライン完了日',
    Panel_Task_BaselineHeader: 'ベースライン',
    Panel_Task_BaselineStartLabel: 'ベースライン開始日',
    Panel_Task_DepTypeFF: '終了-終了 (FF)',
    Panel_Task_DepTypeFS: '終了-開始 (FS)',
    Panel_Task_DepTypeSF: '開始-終了 (SF)',
    Panel_Task_DepTypeSS: '開始-開始 (SS)',
    Panel_Task_LagAriaLabel: '{taskTitle} の遅延 (稼働日)',
    Panel_Task_LagHint: '遅延は稼働日で指定します。先行させる場合は負の数を使用します。',
    Panel_Task_LinkTypeAriaLabel: '{taskTitle} のリンクの種類',
    Panel_Task_VarianceEarlier: '{days} 稼働日早い',
    Panel_Task_VarianceLater: '{days} 稼働日遅れ',
    Panel_Task_VarianceOnBaseline: 'ベースライン通り',
    View_Dashboard_BurndownActual: '実績',
    View_Dashboard_BurndownAria: 'バーンダウン チャート: {total} 件中 {remaining} 件のタスクが残っています',
    View_Dashboard_BurndownHeader: 'バーンダウン (残りのタスク)',
    View_Dashboard_BurndownIdeal: '理想',
    View_Dashboard_BurndownNoData: 'バーンダウンを描画するのに十分な日付付きタスクがありません。',
    View_Dashboard_CriticalPathHeader: 'クリティカル パス  ({count})',
    View_Dashboard_PhaseDoneSummary: '{done}/{total} 完了  •  {percent}%',
    View_Dashboard_TaskRowAriaLabel: 'タスク {taskTitle} を開く、{status}',
    View_Dashboard_WorkloadHeader: '担当者別の作業量',
    View_Dashboard_WorkloadOpen: '未完了 {count} 件',
    View_Dashboard_WorkloadOverdue: '期限超過 {count} 件',
    View_Kanban_AddTaskInColumnAriaLabel: '{column} にタスクを追加',
    View_Kanban_CollapseColumn: '{column} 列を折りたたむ',
    View_Kanban_ExpandColumn: '{column} 列を展開',
    View_Kanban_LaneHeader: '{name} ({count})',
    View_Kanban_LaneNoPhase: 'フェーズなし',
    View_Kanban_LaneUnassigned: '未割り当て',
    View_Kanban_LanesAssignee: '担当者',
    View_Kanban_LanesNone: 'なし',
    View_Kanban_LanesPhase: 'フェーズ',
    View_Kanban_SwimlanesLabel: 'スイムレーン',
    View_Kanban_WipEditTitle: '{column} の仕掛り作業 (WIP) 制限を設定 (0 で制限なし)',
    View_Kanban_WipExceededTitle: 'WIP 制限超過: {limit} 件中 {count} 件',
    View_Kanban_WipInputAriaLabel: '{column} の WIP 制限',
    View_Kanban_WipLabel: 'WIP {count}/{limit}',
    View_Kanban_WipSet: 'WIP',
    View_List_BulkAssignApply: '割り当て',
    View_List_BulkAssigneePlaceholder: '割り当て先…',
    View_List_BulkBarAriaLabel: '選択したタスクの一括操作',
    View_List_BulkClear: '選択を解除',
    View_List_BulkDelete: '選択項目を削除',
    View_List_BulkPercentApply: '% を設定',
    View_List_BulkPercentPlaceholder: '進捗率 (%)',
    View_List_BulkPriorityPlaceholder: '優先度を設定…',
    View_List_BulkSelectedCount: '{count} 件選択中',
    View_List_BulkStatusPlaceholder: 'ステータスを設定…',
    View_List_ExportCsv: 'CSV をエクスポート',
    View_List_NonWorkingDay: '非稼働日',
    View_List_SelectAllAriaLabel: 'すべてのタスクを選択',
    View_List_SelectRowAriaLabel: '{taskTitle} を選択',
    View_Portfolio_CardAriaLabel: 'プロジェクト {projectName} を開く、{status}',
    View_Portfolio_ClearFilters: 'フィルターをクリア',
    View_Portfolio_FilteredCount: '{total} 件中 {shown} 件のプロジェクト',
    View_Portfolio_HideDone: '完了/キャンセル済みを非表示',
    View_Portfolio_NoMatches: 'フィルターに一致するプロジェクトがありません。',
    View_Portfolio_ProjectCountMany: '{count} 件のプロジェクト',
    View_Portfolio_ProjectCountOne: '{count} 件のプロジェクト',
    View_Portfolio_SearchAriaLabel: 'プロジェクトを検索',
    View_Portfolio_SearchPlaceholder: 'プロジェクトを検索…',
    Import_Panel_CopyDetails: '詳細をコピー',
    Import_Panel_Copied: 'コピーしました',
  };
});
