define([], function () {
  return {
    // ── Property pane ──
    PropertyPane_HeaderDescription: 'Smart Gantt Chart 설정',
    PropertyPane_GeneralGroupName: '일반',
    PropertyPane_TitleFieldLabel: '웹 파트 제목',
    WebPart_DefaultTitle: 'Smart Gantt Chart',

    // ── Toolbar ──
    Toolbar_ViewDashboard: '대시보드',
    Toolbar_ViewList: '목록',
    Toolbar_ViewGantt: '간트',
    Toolbar_ViewKanban: '칸반',
    Toolbar_ZoomDay: '일',
    Toolbar_ZoomWeek: '주',
    Toolbar_ZoomMonth: '월',
    Toolbar_ZoomQuarter: '분기',
    Toolbar_SelectProjectAriaLabel: '프로젝트 선택',
    Toolbar_PortfolioLabel: '포트폴리오',
    Toolbar_SelectAProject: '프로젝트 선택',
    Toolbar_AllProjectsSubtext: '모든 프로젝트',
    Toolbar_NoProjectsYet: '아직 프로젝트가 없습니다',
    Toolbar_ArchivedBadge: '보관됨',
    Toolbar_ShowArchivedProjects: '보관된 프로젝트 표시',
    Toolbar_NewProject: '+ 새 프로젝트',
    Toolbar_ImportFileAsNewProject: '📥 파일을 새 프로젝트로 가져오기…',
    Toolbar_AddTask: '+ 작업 추가',
    Toolbar_EditProject: '프로젝트 편집',
    Toolbar_OptionsButton: '⚙ 옵션',
    Toolbar_MoreOptionsTitle: '추가 옵션',
    Toolbar_ExportToExcel: '📊 Excel로 내보내기',
    Toolbar_ExportToPowerPoint: '📑 PowerPoint로 내보내기',
    Toolbar_ScrollToTodayTitle: '오늘로 이동',
    Toolbar_TodayButton: '◉ 오늘',
    Toolbar_ImportTasks: '📥 작업 가져오기…',
    Toolbar_ExportAsImage: '🖼 이미지로 내보내기 (PNG)',
    Toolbar_UnarchiveProject: '📂 프로젝트 보관 취소',
    Toolbar_ArchiveProject: '🗄️ 프로젝트 보관',
    Toolbar_SendToRecycleBin: '🗑️ 휴지통으로 이동',

    // ── Filter bar ──
    FilterBar_ClearOption: '지우기',
    FilterBar_DueAny: '모든 마감일',
    FilterBar_DueOverdue: '기한 초과',
    FilterBar_DueToday: '오늘 마감',
    FilterBar_DueWeek: '7일 이내 마감',
    FilterBar_SearchPlaceholder: '작업 검색…',
    FilterBar_SearchAriaLabel: '작업 검색',
    FilterBar_StatusChipLabel: '상태',
    FilterBar_PriorityChipLabel: '우선순위',
    FilterBar_AssigneeChipLabel: '담당자',
    FilterBar_PhaseChipLabel: '단계',
    FilterBar_DueDateAriaLabel: '마감일로 필터링',
    FilterBar_MatchCount: '{totalCount}개 중 {matchCount}개',
    FilterBar_ClearFilters: '✕ 필터 지우기',
    FilterBar_ChipLabelWithCount: '{label} ({count}) ▾',
    FilterBar_ChipLabelNoCount: '{label} ▾',

    // ── Gantt view ──
    Gantt_TaskColumnHeader: '작업',
    Gantt_DurationColumnHeader: '기간',
    Gantt_AddTaskButton: '+ 작업 추가',
    Gantt_EmptyTitle: '아직 작업이 없습니다',
    Gantt_EmptySubtitle: '작업을 추가하면 간트 차트에 표시됩니다.',
    Gantt_AddFirstTask: '+ 첫 작업 추가',
    Gantt_ImportTasksButton: '📥 작업 가져오기',
    Gantt_EditTitle: '편집',
    Gantt_DeleteTitle: '삭제',
    Gantt_EditTaskAriaLabel: '{taskTitle} 작업 편집',
    Gantt_DeleteTaskAriaLabel: '{taskTitle} 작업 삭제',
    Gantt_ExpandPhaseAriaLabel: '{phase} 단계 {action}',
    Gantt_ExpandAction: '펼치기',
    Gantt_CollapseAction: '접기',
    Gantt_DependencyViolationTooltip: '모든 종속 작업이 완료되기 전에 시작되었습니다',
    Gantt_MilestoneAriaLabel: '{taskTitle}, 마일스톤, {date}',
    Gantt_BarAriaLabel: '{taskTitle}, {startDate}부터 {dueDate}까지, {percent}% 완료',
    Gantt_PercentCompleteTooltip: '{value}% 완료',

    // ── Gantt options/settings panel ──
    GanttSettings_PanelHeader: '⚙ 옵션',
    GanttSettings_ColorCodingSection: '색상 코딩',
    GanttSettings_ByStatus: '상태별',
    GanttSettings_ByPriority: '우선순위별',
    GanttSettings_ByPhase: '단계별',
    GanttSettings_ByHealth: '상태 지표별',
    GanttSettings_HeaderColorSection: '헤더 색상',
    GanttSettings_ThemeDark: '다크',
    GanttSettings_ThemeNavy: '네이비',
    GanttSettings_ThemeTeal: '틸',
    GanttSettings_ThemePurple: '퍼플',
    GanttSettings_ThemeLight: '라이트',
    GanttSettings_HeaderLabelsSection: '헤더 레이블',
    GanttSettings_WeekLabelDates: '날짜',
    GanttSettings_WeekLabelDatesDesc: '6월 3일, 6월 10일…',
    GanttSettings_WeekLabelProject: '프로젝트 주차',
    GanttSettings_WeekLabelProjectDesc: 'W1, W2…',
    GanttSettings_WeekLabelIso: '달력 주차',
    GanttSettings_WeekLabelIsoDesc: 'W23, W24…',
    GanttSettings_ProjectWeeksHint: '1주차는 가장 이른 작업의 월요일부터 시작합니다. 프레젠테이션에 적합합니다.',
    GanttSettings_BarStyleSection: '막대 스타일',
    GanttSettings_BarStyleGradient: '그라데이션',
    GanttSettings_BarStyleFlat: '단색',
    GanttSettings_RowHeightSection: '행 높이',
    GanttSettings_HeightCompact: '좁게',
    GanttSettings_HeightNormal: '보통',
    GanttSettings_HeightSpacious: '넓게',
    GanttSettings_ShowHideSection: '표시 / 숨기기',
    GanttSettings_WeekendShading: '주말 음영 표시',
    GanttSettings_DependencyArrows: '종속성 화살표',
    GanttSettings_CriticalPathAlwaysVisible: 'critical path 항상 표시',
    GanttSettings_AllOthersOnHoverOnly: '나머지는 마우스오버 시에만 표시',
    GanttSettings_CriticalPathHighlight: 'critical path 강조 표시',
    GanttSettings_ProgressPercentOnBars: '막대에 진행률 % 표시',
    GanttSettings_AssigneeNameOnBars: '막대에 담당자 이름 표시',
    GanttSettings_HealthStatusBadges: '상태 지표 배지',

    // ── List view ──
    ListView_ColTaskName: '작업 이름',
    ListView_ColStatus: '상태',
    ListView_ColHealth: '상태 지표',
    ListView_ColPriority: '우선순위',
    ListView_ColStart: '시작일',
    ListView_ColDue: '마감일',
    ListView_ColAssignedTo: '담당자',
    ListView_ColProgress: '진행률',
    ListView_ColPhase: '단계',
    ListView_ColPredecessors: '선행 작업',
    ListView_EmptyTitle: '아직 작업이 없습니다',
    ListView_AddFirstTask: '+ 첫 작업 추가',
    ListView_AddTaskRow: '+ 작업 추가',
    ListView_Unassigned: '담당자 없음',
    ListView_DependencyViolationTooltip: '모든 종속 작업이 완료되기 전에 시작되었습니다',
    ListView_StatusAriaLabel: '{taskTitle}의 상태',
    ListView_PriorityAriaLabel: '{taskTitle}의 우선순위',
    ListView_EditTaskAriaLabel: '{taskTitle} 작업 편집',
    ListView_DeleteTaskAriaLabel: '{taskTitle} 작업 삭제',
    ListView_EditTitle: '편집',
    ListView_DeleteTitle: '삭제',

    // ── Kanban view ──
    Kanban_ColumnNotStarted: '시작 전',
    Kanban_ColumnInProgress: '진행 중',
    Kanban_ColumnOnHold: '보류',
    Kanban_ColumnCompleted: '완료',
    Kanban_ColumnCancelled: '취소됨',
    Kanban_AddTaskButton: '+ 작업 추가',
    Kanban_EditTitle: '편집',
    Kanban_DeleteTitle: '삭제',
    Kanban_CardAriaLabel: '{taskTitle}, {status}. 편집하려면 Enter 키를, 상태를 변경하려면 왼쪽 또는 오른쪽 화살표 키를 누르세요.',
    Kanban_EditTaskAriaLabel: '{taskTitle} 작업 편집',
    Kanban_DeleteTaskAriaLabel: '{taskTitle} 작업 삭제',

    // ── Dashboard view ──
    Dashboard_TotalTasks: '전체 작업',
    Dashboard_Completed: '완료',
    Dashboard_InProgress: '진행 중',
    Dashboard_OnHold: '보류',
    Dashboard_NotStarted: '시작 전',
    Dashboard_Cancelled: '취소됨',
    Dashboard_OverallProgress: '전체 진행률',
    Dashboard_ProjectManagerLabel: '프로젝트 관리자: {name}',
    Dashboard_PhaseProgressHeader: '단계별 진행률',
    Dashboard_StatusBreakdownHeader: '상태별 분석',
    Dashboard_PriorityBreakdownHeader: '우선순위별 분석',
    Dashboard_PriorityCritical: '긴급',
    Dashboard_PriorityHigh: '높음',
    Dashboard_PriorityMedium: '보통',
    Dashboard_PriorityLow: '낮음',
    Dashboard_OverdueHeader: '기한 초과  ({count})',
    Dashboard_DueNext14DaysHeader: '향후 14일 이내 마감  ({count})',
    Dashboard_CompletedThisWeekHeader: '이번 주 완료',
    Dashboard_UpdatedThisWeekHeader: '이번 주 업데이트',
    Dashboard_Today: '오늘',
    Dashboard_Tomorrow: '내일',
    Dashboard_DaysLeft: '{days}일',
    Dashboard_EmptyTitle: '아직 작업이 없습니다',
    Dashboard_EmptySubtitle: '작업을 추가하면 프로젝트 대시보드를 볼 수 있습니다.',
    Dashboard_AddTaskButton: '+ 작업 추가',

    // ── Portfolio view ──
    Portfolio_ProjectCount: '프로젝트 {count}개',
    Portfolio_OnTrackSummary: '정상 {count}개',
    Portfolio_AtRiskSummary: '위험 {count}개',
    Portfolio_OverdueSummary: '기한 초과 {count}개',
    Portfolio_DoneSummary: '완료 {count}개',
    Portfolio_SortLabel: '정렬:',
    Portfolio_SortAZ: 'A-Z',
    Portfolio_SortHealth: '상태 지표',
    Portfolio_SortStatus: '상태',
    Portfolio_SortCompletion: '완료율',
    Portfolio_RefreshTitle: '새로 고침',
    Portfolio_RefreshButton: '새로 고침',
    Portfolio_LoadingStats: '통계를 불러오는 중…',
    Portfolio_EmptyTitle: '아직 프로젝트가 없습니다',
    Portfolio_CreateFirstProject: '+ 첫 프로젝트 만들기',
    Portfolio_StatsUnavailable: '통계를 사용할 수 없음',
    Portfolio_StatsUnavailableDetail: '이 프로젝트의 통계를 불러올 수 없습니다.',
    Portfolio_OverallProgressLabel: '전체 진행률',
    Portfolio_TaskCountDone: '완료',
    Portfolio_TaskCountActive: '진행 중',
    Portfolio_TaskCountAtRisk: '위험',
    Portfolio_TaskCountOverdue: '기한 초과',
    Portfolio_ViewGanttLink: '간트 보기 →',
    Portfolio_TodayTooltip: '오늘',

    // ── Task panel ──
    TaskPanel_EditHeader: '편집: {taskTitle}',
    TaskPanel_NewTaskHeader: '새 작업',
    TaskPanel_TabBasic: '기본',
    TaskPanel_TabDetails: '세부 정보',
    TaskPanel_TabLinks: '링크',
    TaskPanel_ProjectLabelPrefix: '프로젝트: ',
    TaskPanel_TaskNameLabel: '작업 이름',
    TaskPanel_TaskNamePlaceholder: '작업 이름을 입력하세요',
    TaskPanel_TaskNameRequired: '작업 이름은 필수입니다',
    TaskPanel_DescriptionLabel: '설명',
    TaskPanel_DescriptionPlaceholder: '설명을 입력하세요',
    TaskPanel_StartDateLabel: '시작일',
    TaskPanel_DueDateLabel: '마감일',
    TaskPanel_DueDateError: '마감일은 시작일과 같거나 그 이후여야 합니다',
    TaskPanel_StatusLabel: '상태',
    TaskPanel_PriorityLabel: '우선순위',
    TaskPanel_PercentCompleteLabel: '진행률: {percent}%',
    TaskPanel_AssignedToLabel: '담당자',
    TaskPanel_AssignedToPlaceholder: '담당자 검색…',
    TaskPanel_PhaseLabel: '단계',
    TaskPanel_PhasePlaceholder: '단계 이름을 입력하세요',
    TaskPanel_PhaseHint: '간트 및 목록 보기에서 작업을 그룹화합니다.',
    TaskPanel_MilestoneLabel: '마일스톤',
    TaskPanel_MilestoneOnText: '예',
    TaskPanel_MilestoneOffText: '아니요',
    TaskPanel_CustomBarColorLabel: '사용자 지정 막대 색상',
    TaskPanel_CustomBarColorOptionalSuffix: ' (선택 사항)',
    TaskPanel_AutoColorHint: '상태/우선순위/단계 설정에 따라 자동으로 색상이 지정됩니다.',
    TaskPanel_NotesLabel: '메모',
    TaskPanel_NotesPlaceholder: '메모를 입력하세요',
    TaskPanel_ParentTaskLabel: '상위 작업',
    TaskPanel_ParentTaskNone: '(없음)',
    TaskPanel_ParentTaskHasChildrenHint: '이 작업에는 하위 작업이 있어 자체 상위 작업을 가질 수 없습니다.',
    TaskPanel_ParentTaskHint: '이 작업을 다른 작업의 하위 작업으로 중첩합니다.',
    TaskPanel_DependsOnLabel: '종속 작업',
    TaskPanel_RemoveDependencyTitle: '"{taskTitle}"에 대한 종속성 제거',
    TaskPanel_AddDependencyPlaceholder: '종속성 추가…',
    TaskPanel_SelectATaskOption: '작업 선택…',
    TaskPanel_DependsOnHint: '이 작업은 아래 작업이 완료될 때까지 시작할 수 없습니다.',
    TaskPanel_SavingLabel: '저장 중…',
    TaskPanel_CreatingLabel: '생성 중…',
    TaskPanel_SaveChangesButton: '변경 사항 저장',
    TaskPanel_CreateTaskButton: '작업 만들기',
    TaskPanel_CancelButton: '취소',
    TaskPanel_DismissAriaLabel: '닫기',
    TaskPanel_DiscardUnsavedChangesConfirm: '저장하지 않은 변경 사항을 취소하시겠습니까?',
    TaskPanel_SaveFallbackError: '작업을 저장할 수 없습니다.',

    // ── Project panel ──
    ProjectPanel_EditHeader: '프로젝트 편집',
    ProjectPanel_NewHeader: '새 프로젝트',
    ProjectPanel_ProjectNameLabel: '프로젝트 이름',
    ProjectPanel_ProjectNamePlaceholder: '프로젝트 이름을 입력하세요',
    ProjectPanel_ProjectNameRequired: '프로젝트 이름은 필수입니다',
    ProjectPanel_DescriptionLabel: '설명',
    ProjectPanel_DescriptionPlaceholder: '설명을 입력하세요',
    ProjectPanel_ProjectColorLabel: '프로젝트 색상',
    ProjectPanel_StatusLabel: '상태',
    ProjectPanel_StartDateLabel: '시작일',
    ProjectPanel_DueDateLabel: '마감일',
    ProjectPanel_DueDateError: '마감일은 시작일과 같거나 그 이후여야 합니다',
    ProjectPanel_WhatHappensNextTitle: '다음에는 무엇을 하나요?',
    ProjectPanel_WhatHappensNextBody: '프로젝트가 생성되면 작업 추가, 단계 설정, 진행 상황 추적이 가능합니다.',
    ProjectPanel_SavingLabel: '저장 중…',
    ProjectPanel_CreatingLabel: '생성 중…',
    ProjectPanel_SaveChangesButton: '변경 사항 저장',
    ProjectPanel_CreateProjectButton: '프로젝트 만들기',
    ProjectPanel_CancelButton: '취소',
    ProjectPanel_DismissAriaLabel: '닫기',
    ProjectPanel_DiscardUnsavedChangesConfirm: '저장하지 않은 변경 사항을 취소하시겠습니까?',
    ProjectPanel_SaveFallbackError: '프로젝트를 저장할 수 없습니다.',

    // ── Import panel ──
    ImportPanel_SourceExcelTitle: 'Excel / CSV 파일',
    ImportPanel_SourceExcelSubtitle: '스프레드시트에서 작업 가져오기',
    ImportPanel_SourcePlannerTitle: 'Microsoft Planner',
    ImportPanel_SourcePlannerSubtitle: 'Planner 계획에서 작업 가져오기',
    ImportPanel_ClickToBrowse: '클릭하여 찾아보기',
    ImportPanel_DragDropSuffix: ' 또는 끌어서 놓기',
    ImportPanel_SupportedExtensions: '.xlsx, .xls, .csv 지원',
    ImportPanel_RowsColsSummary: '{rows}개 행, {cols}개 열이 감지되었습니다',
    ImportPanel_LoadingPlannerPlans: 'Planner 계획을 불러오는 중…',
    ImportPanel_PlannerLoadError: 'Planner 계획을 불러올 수 없습니다.',
    ImportPanel_PlannerPermissionsHintPrefix: 'Planner에 대한 액세스 권한이 있는지, 그리고 ',
    ImportPanel_PlannerPermissionsHintEmphasis: 'Planner 및 To Do 작업',
    ImportPanel_PlannerPermissionsHintSuffix: '이(가) 이 사이트에서 사용 가능한지 확인하세요.',
    ImportPanel_NoPlannerPlansFoundTitle: 'Planner 계획을 찾을 수 없습니다',
    ImportPanel_NoPlannerPlansFoundBody: 'Planner 계획에 대한 액세스 권한이 없거나 이 계정에 계획이 존재하지 않을 수 있습니다.',
    ImportPanel_TaskCountFoundIn: '"{planName}"에서 {count}개의 작업을 찾았습니다',
    ImportPanel_ProjectDetailsIntroPrefix: '가져오기 대상: ',
    ImportPanel_ProjectDetailsIntroSuffix: '. 아래 프로젝트 세부 정보를 검토하세요.',
    ImportPanel_ProjectNameLabel: '프로젝트 이름',
    ImportPanel_DescriptionLabel: '설명',
    ImportPanel_StatusLabel: '상태',
    ImportPanel_ColorLabel: '색상',
    ImportPanel_MapIntro: '파일의 열을 작업 필드에 매핑하세요.',
    ImportPanel_CreatingProjectStatus: '프로젝트 생성 중…',
    ImportPanel_ImportingTasksStatus: '작업 가져오는 중…',
    ImportPanel_ProgressLabel: '{total}개 중 {done}개',
    ImportPanel_CouldNotCreateProject: '프로젝트를 만들 수 없습니다.',
    ImportPanel_ImportCompletedWithErrors: '가져오기가 완료되었지만 {count}개의 오류가 있습니다.',
    ImportPanel_ProjectCreatedSuccess: '프로젝트가 성공적으로 생성되었습니다!',
    ImportPanel_ImportSuccessful: '가져오기에 성공했습니다!',
    ImportPanel_TasksAddedTo: '{count}개의 작업이 "{projectName}"에 추가되었습니다',
    ImportPanel_FailedRowsLabel: '실패한 행:',
    ImportPanel_CloseButton: '닫기',
    ImportPanel_OpenProjectButton: '프로젝트 열기',
    ImportPanel_ViewImportedTasksButton: '가져온 작업 보기',
    ImportPanel_NextMapColumnsButton: '다음: 열 매핑',
    ImportPanel_ImportNTasksButton: '{count}개 작업 가져오기',
    ImportPanel_BackButton: '뒤로',
    ImportPanel_CancelButton: '취소',
    ImportPanel_NextButton: '다음',
    ImportPanel_StepSource: '원본',
    ImportPanel_StepProject: '프로젝트',
    ImportPanel_StepMap: '매핑',
    ImportPanel_StepImport: '가져오기',
    ImportPanel_StepDone: '완료',
    ImportPanel_ImportAsNewProjectHeader: '파일을 새 프로젝트로 가져오기',
    ImportPanel_ImportIntoProjectHeader: '{projectName}에 작업 가져오기',
    ImportPanel_CouldNotParseFile: '파일을 구문 분석할 수 없습니다.',
    ImportPanel_CouldNotLoadPlannerTasks: '이 계획에서 작업을 불러올 수 없습니다.',
    ImportPanel_CouldNotCreateProjectDetail: '프로젝트를 만들 수 없습니다: {detail}',
    ImportPanel_CouldNotLinkDependencies: '종속성을 연결할 수 없습니다: {detail}',
    ImportPanel_UnknownError: '알 수 없는 오류',

    // ── Column mapper (import) ──
    ColumnMapper_TaskNameRequiredBanner: '계속하려면 작업 이름을 매핑해야 합니다.',
    ColumnMapper_SkippedColumnsBanner: '{count}개의 열이 건너뛰어집니다.',
    ColumnMapper_SourceColumnHeader: '원본 열',
    ColumnMapper_TargetFieldHeader: '대상 필드',
    ColumnMapper_StatusHeader: '상태',
    ColumnMapper_SkippedBadge: '건너뜀',
    ColumnMapper_AutoMappedBadge: '자동 매핑됨',
    ColumnMapper_SetBadge: '설정됨',
    ColumnMapper_PreviewTitle: '미리보기: {columnName}',
    ColumnMapper_EmptyCellDash: '—',

    // ── Import field display names / ImportService ──
    ImportField_TaskName: '작업 이름',
    ImportField_StartDate: '시작일',
    ImportField_DueDate: '마감일',
    ImportField_Status: '상태',
    ImportField_Priority: '우선순위',
    ImportField_AssignedTo: '담당자',
    ImportField_AssignedToEmail: '담당자 이메일',
    ImportField_PercentComplete: '진행률',
    ImportField_Phase: '단계',
    ImportField_Description: '설명',
    ImportField_Notes: '메모',
    ImportField_IsMilestone: '마일스톤 여부',
    ImportField_Dependencies: '종속성',
    ImportField_SkipColumn: '(이 열 건너뛰기)',
    ImportService_EmptyFileError: '파일이 비어 있거나 데이터 행이 없는 것 같습니다.',
    ImportService_ReadErrorDetail: '파일을 읽을 수 없습니다: {detail}.',
    ImportService_FileReadError: '파일 읽기 오류입니다.',
    ImportService_RowError: '{rowNum}행 ("{title}"): {error}',
    ImportService_AmbiguousDependency: '종속성 "{name}"이(가) 둘 이상의 작업 이름과 일치하여 건너뛰었습니다.',
    ImportService_LinkDependencyError: '작업 {taskId}의 종속성을 연결할 수 없습니다: {error}',

    // ── Health labels (shared: healthUtils.ts and ExportService.ts both use this set; also replaces the duplicated Export_PortfolioHealthLabel* keys) ──
    Health_Done: '완료',
    Health_OnTrack: '정상',
    Health_AtRisk: '위험',
    Health_Overdue: '기한 초과',

    // ── Status / Priority display labels (DISPLAY-ONLY — stored SharePoint Choice values remain unchanged/English) ──
    Status_NotStarted: '시작 전',
    Status_InProgress: '진행 중',
    Status_Completed: '완료',
    Status_OnHold: '보류',
    Status_Cancelled: '취소됨',
    Priority_Critical: '긴급',
    Priority_High: '높음',
    Priority_Medium: '보통',
    Priority_Low: '낮음',
    ProjectStatus_Planning: '계획 중',
    ProjectStatus_Active: '진행 중',
    ProjectStatus_OnHold: '보류',
    ProjectStatus_Completed: '완료',
    ProjectStatus_Cancelled: '취소됨',

    // ── Shell (SmartGantt.tsx) ──
    SmartGantt_LoadingProjects: '프로젝트를 불러오는 중…',
    SmartGantt_UnableToLoad: '불러올 수 없습니다',
    SmartGantt_RetryButton: '다시 시도',
    SmartGantt_NoProjectsYet: '아직 프로젝트가 없습니다',
    SmartGantt_NoProjectsSubtitle: '첫 프로젝트를 만들어 시작하세요.',
    SmartGantt_CreateFirstProjectButton: '+ 첫 프로젝트 만들기',
    SmartGantt_ImportFromExcelButton: '📥 Excel에서 가져오기',
    SmartGantt_LoadingTasks: '작업을 불러오는 중…',
    SmartGantt_DismissAriaLabel: '닫기',
    SmartGantt_DeleteTaskDialogTitle: '작업 삭제',
    SmartGantt_DeleteTaskDialogSubtext: '"{taskTitle}"을(를) 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.',
    SmartGantt_DeleteButton: '삭제',
    SmartGantt_CancelButton: '취소',
    SmartGantt_ArchiveProjectDialogTitle: '프로젝트 보관',
    SmartGantt_ArchiveProjectDialogSubtext: '"{projectTitle}"을(를) 보관하시겠습니까? 나중에 보관을 취소할 수 있습니다.',
    SmartGantt_ArchiveButton: '보관',
    SmartGantt_SendToRecycleBinDialogTitle: '휴지통으로 이동',
    SmartGantt_SendToRecycleBinDialogSubtext: '"{projectTitle}"을(를) 사이트 휴지통으로 이동하시겠습니까?',
    SmartGantt_SendToRecycleBinButton: '휴지통으로 이동',
    SmartGantt_FailedLoadProjects: '프로젝트를 불러오지 못했습니다. 사이트 권한을 확인하세요.',
    SmartGantt_FailedLoadTasks: '이 프로젝트의 작업을 불러오지 못했습니다.',
    SmartGantt_FailedLoadPortfolioStats: '포트폴리오 통계를 불러오지 못했습니다.',
    SmartGantt_CouldNotSaveProject: '프로젝트를 저장할 수 없습니다: {message}',
    SmartGantt_CouldNotDeleteProject: '프로젝트를 삭제할 수 없습니다: {message}',
    SmartGantt_CouldNotArchiveProject: '프로젝트를 보관할 수 없습니다: {message}',
    SmartGantt_CouldNotUnarchiveProject: '프로젝트 보관을 취소할 수 없습니다: {message}',
    SmartGantt_CouldNotSaveTask: '작업을 저장할 수 없습니다: {message}',
    SmartGantt_CouldNotDeleteTask: '작업을 삭제할 수 없습니다: {message}',
    SmartGantt_ImageExportFailed: '이미지 내보내기에 실패했습니다: {message}',
    SmartGantt_PowerPointExportFailed: 'PowerPoint 내보내기에 실패했습니다: {message}',
    SmartGantt_PortfolioExportFailed: '포트폴리오 내보내기에 실패했습니다: {message}',
    SmartGantt_CouldNotUpdateTask: '작업을 업데이트할 수 없습니다: {message}',

    // ── Common ──
    ColorSwatch_AutoColorAriaLabel: '자동 색상',
    ColorSwatch_CustomColorAriaLabel: '사용자 지정 색상',
    ColorSwatch_PickCustomColorTitle: '사용자 지정 색상 선택',

    // ── Export (Excel / PowerPoint) ──
    Export_ColTaskName: '작업 이름',
    Export_ColPhase: '단계',
    Export_ColStartDate: '시작일',
    Export_ColDueDate: '마감일',
    Export_ColStatus: '상태',
    Export_ColPriority: '우선순위',
    Export_ColAssignedTo: '담당자',
    Export_ColAssignedToEmail: '담당자 이메일',
    Export_ColPercentComplete: '진행률',
    Export_ColIsMilestone: '마일스톤 여부',
    Export_ColDescription: '설명',
    Export_ColNotes: '메모',
    Export_Yes: '예',
    Export_No: '아니요',
    Export_SheetNameTasks: '작업',
    Export_ExcelFileSuffix: ' - 작업.xlsx',
    Export_TaskNameColumnLabel: '작업 이름',
    Export_ExportedDateLabel: '내보낸 날짜: {date}',
    Export_ProjectReportLabel: '프로젝트 보고서',
    Export_StatusLine: '상태: {status}',
    Export_DateRangeSeparator: ' ~ ',
    Export_ProjectManagerLine: '프로젝트 관리자: {name}',
    Export_GeneratedDateLine: '생성 날짜: {date}',
    Export_ProjectSummaryTitle: '프로젝트 요약',
    Export_StatTotalTasks: '전체 작업',
    Export_StatCompleted: '완료',
    Export_StatInProgress: '진행 중',
    Export_StatOnHold: '보류',
    Export_StatNotStarted: '시작 전',
    Export_OverallProgressLine: '전체 진행률',
    Export_OverallProgressPercent: '{percent}%',
    Export_StatusBreakdownTitle: '상태별 분석',
    Export_StatusBreakdownRow: '{status}: {count} ({percent}%)',
    Export_GanttTimelineTitle: '간트 타임라인',
    Export_SummaryRecentActivityTitle: '최근 활동',
    Export_ProjectOverviewLabel: '프로젝트 개요',
    Export_DetailStatusLabel: '상태',
    Export_DetailStartDateLabel: '시작일',
    Export_DetailDueDateLabel: '마감일',
    Export_DetailProjectManagerLabel: '프로젝트 관리자',
    Export_Past7DaysLabel: '지난 7일',
    Export_NoActivityMessage: '최근 활동이 없습니다.',
    Export_CompletedThisWeekHeader: '이번 주 완료 ({count})',
    Export_NewBadge: '신규  ',
    Export_CompletedPercentLine: '{percent}% 완료',
    Export_MoreItemsSuffix: '외 {count}개',
    Export_InProgressUpdatedHeader: '진행 중 / 업데이트됨',
    Export_StatusPercentLine: '{status} — {percent}%',
    Export_PortfolioReportLabel: '포트폴리오 보고서',
    Export_PortfolioOverviewTitle: '포트폴리오 개요',
    Export_ProjectsCountLine: '프로젝트 {count}개',
    Export_HealthSummaryOnTrack: '정상 {count}개',
    Export_HealthSummaryAtRisk: '위험 {count}개',
    Export_HealthSummaryOverdue: '기한 초과 {count}개',
    Export_ProjectsSummaryHeader: '프로젝트 요약',
    Export_TableProject: '프로젝트',
    Export_TableStatus: '상태',
    Export_TableHealth: '상태 지표',
    Export_TableTotal: '합계',
    Export_TableDone: '완료',
    Export_TableActive: '진행 중',
    Export_TableAtRisk: '위험',
    Export_TableOverdue: '기한 초과',
    Export_TablePctDone: '완료율',
    Export_TableDueDate: '마감일',
    Export_PortfolioSummaryFileName: '포트폴리오 요약.xlsx',
    Export_PortfolioReportFileName: '포트폴리오 보고서.pptx',
    Export_ProjectReportFileName: '{projectName} 보고서.pptx',
    Export_UnavailableLabel: '사용할 수 없음',
    Export_SheetNamePortfolio: '포트폴리오',
    Export_ColStart: '시작일',
    Export_ColDue: '마감일',
    Export_ImageGenerationFailed: '이미지를 생성할 수 없습니다. 차트가 너무 커서 이미지로 내보낼 수 없을 수 있습니다.',
    Export_DrawingContextFailed: '내보내기용 드로잉 컨텍스트를 만들 수 없습니다.',
    Export_SvgRenderFailed: 'SVG 렌더링에 실패했습니다',
  };
});
