define([], function () {
  return {
    // ── Property pane ──
    PropertyPane_HeaderDescription: 'Innstillinger for Smart Gantt Chart',
    PropertyPane_GeneralGroupName: 'Generelt',
    PropertyPane_TitleFieldLabel: 'Tittel på webdelen',
    WebPart_DefaultTitle: 'Smart Gantt Chart',

    // ── Toolbar ──
    Toolbar_ViewDashboard: 'Dashbord',
    Toolbar_ViewList: 'Liste',
    Toolbar_ViewGantt: 'Gantt',
    Toolbar_ViewKanban: 'Kanban',
    Toolbar_ZoomDay: 'Dag',
    Toolbar_ZoomWeek: 'Uke',
    Toolbar_ZoomMonth: 'Måned',
    Toolbar_ZoomQuarter: 'Kvartal',
    Toolbar_SelectProjectAriaLabel: 'Velg prosjekt',
    Toolbar_PortfolioLabel: 'Portefølje',
    Toolbar_SelectAProject: 'Velg et prosjekt',
    Toolbar_AllProjectsSubtext: 'Alle prosjekter',
    Toolbar_NoProjectsYet: 'Ingen prosjekter ennå',
    Toolbar_ArchivedBadge: 'Arkivert',
    Toolbar_ShowArchivedProjects: 'Vis arkiverte prosjekter',
    Toolbar_NewProject: '+ Nytt prosjekt',
    Toolbar_ImportFileAsNewProject: '📥 Importer fil som nytt prosjekt…',
    Toolbar_AddTask: '+ Legg til oppgave',
    Toolbar_EditProject: 'Rediger prosjekt',
    Toolbar_OptionsButton: '⚙ Alternativer',
    Toolbar_MoreOptionsTitle: 'Flere alternativer',
    Toolbar_ExportToExcel: '📊 Eksporter til Excel',
    Toolbar_ExportToPowerPoint: '📑 Eksporter til PowerPoint',
    Toolbar_ScrollToTodayTitle: 'Gå til i dag',
    Toolbar_TodayButton: '◉ I dag',
    Toolbar_ImportTasks: '📥 Importer oppgaver…',
    Toolbar_ExportAsImage: '🖼 Eksporter som bilde (PNG)',
    Toolbar_UnarchiveProject: '📂 Gjenopprett prosjekt fra arkiv',
    Toolbar_ArchiveProject: '🗄️ Arkiver prosjekt',
    Toolbar_SendToRecycleBin: '🗑️ Send til papirkurven',

    // ── Filter bar ──
    FilterBar_ClearOption: 'Fjern',
    FilterBar_DueAny: 'Alle forfallsdatoer',
    FilterBar_DueOverdue: 'Forfalt',
    FilterBar_DueToday: 'Forfaller i dag',
    FilterBar_DueWeek: 'Forfaller om 7 dager',
    FilterBar_SearchPlaceholder: 'Søk i oppgaver…',
    FilterBar_SearchAriaLabel: 'Søk i oppgaver',
    FilterBar_StatusChipLabel: 'Status',
    FilterBar_PriorityChipLabel: 'Prioritet',
    FilterBar_AssigneeChipLabel: 'Tildelt til',
    FilterBar_PhaseChipLabel: 'Fase',
    FilterBar_DueDateAriaLabel: 'Filtrer etter forfallsdato',
    FilterBar_MatchCount: '{matchCount} av {totalCount}',
    FilterBar_ClearFilters: '✕ Fjern filtre',
    FilterBar_ChipLabelWithCount: '{label} ({count}) ▾',
    FilterBar_ChipLabelNoCount: '{label} ▾',

    // ── Gantt view ──
    Gantt_TaskColumnHeader: 'Oppgave',
    Gantt_DurationColumnHeader: 'Varighet',
    Gantt_AddTaskButton: '+ Legg til oppgave',
    Gantt_EmptyTitle: 'Ingen oppgaver ennå',
    Gantt_EmptySubtitle: 'Legg til oppgaver for å se dem i Gantt-diagrammet.',
    Gantt_AddFirstTask: '+ Legg til første oppgave',
    Gantt_ImportTasksButton: '📥 Importer oppgaver',
    Gantt_EditTitle: 'Rediger',
    Gantt_DeleteTitle: 'Slett',
    Gantt_EditTaskAriaLabel: 'Rediger oppgaven {taskTitle}',
    Gantt_DeleteTaskAriaLabel: 'Slett oppgaven {taskTitle}',
    Gantt_ExpandPhaseAriaLabel: '{action} fasen {phase}',
    Gantt_ExpandAction: 'Utvid',
    Gantt_CollapseAction: 'Skjul',
    Gantt_DependencyViolationTooltip: 'Startet før alle avhengigheter var fullført',
    Gantt_MilestoneAriaLabel: '{taskTitle}, milepæl, {date}',
    Gantt_BarAriaLabel: '{taskTitle}, {startDate} til {dueDate}, {percent}% fullført',
    Gantt_PercentCompleteTooltip: '{value}% fullført',

    // ── Gantt options/settings panel ──
    GanttSettings_PanelHeader: '⚙ Alternativer',
    GanttSettings_ColorCodingSection: 'Fargekoding',
    GanttSettings_ByStatus: 'Etter status',
    GanttSettings_ByPriority: 'Etter prioritet',
    GanttSettings_ByPhase: 'Etter fase',
    GanttSettings_ByHealth: 'Etter helsetilstand',
    GanttSettings_HeaderColorSection: 'Overskriftsfarge',
    GanttSettings_ThemeDark: 'Mørk',
    GanttSettings_ThemeNavy: 'Marineblå',
    GanttSettings_ThemeTeal: 'Turkis',
    GanttSettings_ThemePurple: 'Lilla',
    GanttSettings_ThemeLight: 'Lys',
    GanttSettings_HeaderLabelsSection: 'Overskriftsetiketter',
    GanttSettings_WeekLabelDates: 'Datoer',
    GanttSettings_WeekLabelDatesDesc: '3. jun, 10. jun…',
    GanttSettings_WeekLabelProject: 'Prosjektuker',
    GanttSettings_WeekLabelProjectDesc: 'U1, U2…',
    GanttSettings_WeekLabelIso: 'Kalenderuker',
    GanttSettings_WeekLabelIsoDesc: 'U23, U24…',
    GanttSettings_ProjectWeeksHint: 'Uke 1 starter på mandagen til den tidligste oppgaven din – flott for presentasjoner.',
    GanttSettings_BarStyleSection: 'Stolpestil',
    GanttSettings_BarStyleGradient: 'Fargeovergang',
    GanttSettings_BarStyleFlat: 'Flat',
    GanttSettings_RowHeightSection: 'Radhøyde',
    GanttSettings_HeightCompact: 'Kompakt',
    GanttSettings_HeightNormal: 'Normal',
    GanttSettings_HeightSpacious: 'Romslig',
    GanttSettings_ShowHideSection: 'Vis / Skjul',
    GanttSettings_WeekendShading: 'Skyggelegging av helg',
    GanttSettings_DependencyArrows: 'Avhengighetspiler',
    GanttSettings_CriticalPathAlwaysVisible: 'Kritisk sti alltid synlig',
    GanttSettings_AllOthersOnHoverOnly: 'Alle andre kun ved museover',
    GanttSettings_CriticalPathHighlight: 'Fremhev kritisk sti',
    GanttSettings_ProgressPercentOnBars: 'Fremdrift i % på stolpene',
    GanttSettings_AssigneeNameOnBars: 'Navn på ansvarlig på stolpene',
    GanttSettings_HealthStatusBadges: 'Merker for helsetilstand',

    // ── List view ──
    ListView_ColTaskName: 'Oppgavenavn',
    ListView_ColStatus: 'Status',
    ListView_ColHealth: 'Helsetilstand',
    ListView_ColPriority: 'Prioritet',
    ListView_ColStart: 'Start',
    ListView_ColDue: 'Forfall',
    ListView_ColAssignedTo: 'Tildelt til',
    ListView_ColProgress: 'Fremdrift',
    ListView_ColPhase: 'Fase',
    ListView_ColPredecessors: 'Forgjengere',
    ListView_EmptyTitle: 'Ingen oppgaver ennå',
    ListView_AddFirstTask: '+ Legg til første oppgave',
    ListView_AddTaskRow: '+ Legg til oppgave',
    ListView_Unassigned: 'Ikke tildelt',
    ListView_DependencyViolationTooltip: 'Startet før alle avhengigheter var fullført',
    ListView_StatusAriaLabel: 'Status for {taskTitle}',
    ListView_PriorityAriaLabel: 'Prioritet for {taskTitle}',
    ListView_EditTaskAriaLabel: 'Rediger oppgaven {taskTitle}',
    ListView_DeleteTaskAriaLabel: 'Slett oppgaven {taskTitle}',
    ListView_EditTitle: 'Rediger',
    ListView_DeleteTitle: 'Slett',

    // ── Kanban view ──
    Kanban_ColumnNotStarted: 'Ikke startet',
    Kanban_ColumnInProgress: 'Pågår',
    Kanban_ColumnOnHold: 'På vent',
    Kanban_ColumnCompleted: 'Fullført',
    Kanban_ColumnCancelled: 'Avbrutt',
    Kanban_AddTaskButton: '+ Legg til oppgave',
    Kanban_EditTitle: 'Rediger',
    Kanban_DeleteTitle: 'Slett',
    Kanban_CardAriaLabel: '{taskTitle}, {status}. Trykk Enter for å redigere, venstre eller høyre pil for å endre status.',
    Kanban_EditTaskAriaLabel: 'Rediger oppgaven {taskTitle}',
    Kanban_DeleteTaskAriaLabel: 'Slett oppgaven {taskTitle}',

    // ── Dashboard view ──
    Dashboard_TotalTasks: 'Oppgaver totalt',
    Dashboard_Completed: 'Fullført',
    Dashboard_InProgress: 'Pågår',
    Dashboard_OnHold: 'På vent',
    Dashboard_NotStarted: 'Ikke startet',
    Dashboard_Cancelled: 'Avbrutt',
    Dashboard_OverallProgress: 'Samlet fremdrift',
    Dashboard_ProjectManagerLabel: 'Prosjektleder: {name}',
    Dashboard_PhaseProgressHeader: 'Fremdrift per fase',
    Dashboard_StatusBreakdownHeader: 'Statusfordeling',
    Dashboard_PriorityBreakdownHeader: 'Prioritetsfordeling',
    Dashboard_PriorityCritical: 'Kritisk',
    Dashboard_PriorityHigh: 'Høy',
    Dashboard_PriorityMedium: 'Middels',
    Dashboard_PriorityLow: 'Lav',
    Dashboard_OverdueHeader: 'Forfalt  ({count})',
    Dashboard_DueNext14DaysHeader: 'Forfaller innen 14 dager  ({count})',
    Dashboard_CompletedThisWeekHeader: 'Fullført denne uken',
    Dashboard_UpdatedThisWeekHeader: 'Oppdatert denne uken',
    Dashboard_Today: 'I dag',
    Dashboard_Tomorrow: 'I morgen',
    Dashboard_DaysLeft: '{days}d',
    Dashboard_EmptyTitle: 'Ingen oppgaver ennå',
    Dashboard_EmptySubtitle: 'Legg til oppgaver for å se prosjektdashbordet.',
    Dashboard_AddTaskButton: '+ Legg til oppgave',

    // ── Portfolio view ──
    Portfolio_ProjectCount: '{count} prosjekt{plural}',
    Portfolio_OnTrackSummary: '{count} på sporet',
    Portfolio_AtRiskSummary: '{count} i faresonen',
    Portfolio_OverdueSummary: '{count} forfalt',
    Portfolio_DoneSummary: '{count} ferdig',
    Portfolio_SortLabel: 'Sorter:',
    Portfolio_SortAZ: 'A-Å',
    Portfolio_SortHealth: 'Helsetilstand',
    Portfolio_SortStatus: 'Status',
    Portfolio_SortCompletion: 'Fullføring',
    Portfolio_RefreshTitle: 'Oppdater',
    Portfolio_RefreshButton: 'Oppdater',
    Portfolio_LoadingStats: 'Laster statistikk…',
    Portfolio_EmptyTitle: 'Ingen prosjekter ennå',
    Portfolio_CreateFirstProject: '+ Opprett første prosjekt',
    Portfolio_StatsUnavailable: 'Statistikk utilgjengelig',
    Portfolio_StatsUnavailableDetail: 'Kunne ikke laste statistikk for dette prosjektet.',
    Portfolio_OverallProgressLabel: 'Samlet fremdrift',
    Portfolio_TaskCountDone: 'Ferdig',
    Portfolio_TaskCountActive: 'Aktive',
    Portfolio_TaskCountAtRisk: 'I faresonen',
    Portfolio_TaskCountOverdue: 'Forfalt',
    Portfolio_ViewGanttLink: 'Vis Gantt →',
    Portfolio_TodayTooltip: 'I dag',

    // ── Task panel ──
    TaskPanel_EditHeader: 'Rediger: {taskTitle}',
    TaskPanel_NewTaskHeader: 'Ny oppgave',
    TaskPanel_TabBasic: 'Grunnleggende',
    TaskPanel_TabDetails: 'Detaljer',
    TaskPanel_TabLinks: 'Koblinger',
    TaskPanel_ProjectLabelPrefix: 'Prosjekt: ',
    TaskPanel_TaskNameLabel: 'Oppgavenavn',
    TaskPanel_TaskNamePlaceholder: 'Skriv inn oppgavenavn',
    TaskPanel_TaskNameRequired: 'Oppgavenavn er obligatorisk',
    TaskPanel_DescriptionLabel: 'Beskrivelse',
    TaskPanel_DescriptionPlaceholder: 'Skriv inn beskrivelse',
    TaskPanel_StartDateLabel: 'Startdato',
    TaskPanel_DueDateLabel: 'Forfallsdato',
    TaskPanel_DueDateError: 'Forfallsdatoen må være lik eller etter startdatoen',
    TaskPanel_StatusLabel: 'Status',
    TaskPanel_PriorityLabel: 'Prioritet',
    TaskPanel_PercentCompleteLabel: '% Fullført: {percent}%',
    TaskPanel_AssignedToLabel: 'Tildelt til',
    TaskPanel_AssignedToPlaceholder: 'Søk etter personer…',
    TaskPanel_PhaseLabel: 'Fase',
    TaskPanel_PhasePlaceholder: 'Skriv inn fasenavn',
    TaskPanel_PhaseHint: 'Grupperer oppgaver sammen i Gantt- og listevisning.',
    TaskPanel_MilestoneLabel: 'Milepæl',
    TaskPanel_MilestoneOnText: 'Ja',
    TaskPanel_MilestoneOffText: 'Nei',
    TaskPanel_CustomBarColorLabel: 'Egendefinert stolpefarge',
    TaskPanel_CustomBarColorOptionalSuffix: ' (valgfritt)',
    TaskPanel_AutoColorHint: 'Automatisk farge basert på innstillinger for status/prioritet/fase.',
    TaskPanel_NotesLabel: 'Notater',
    TaskPanel_NotesPlaceholder: 'Skriv inn notater',
    TaskPanel_ParentTaskLabel: 'Overordnet oppgave',
    TaskPanel_ParentTaskNone: '(ingen)',
    TaskPanel_ParentTaskHasChildrenHint: 'Denne oppgaven har underoppgaver og kan ikke ha en egen overordnet oppgave.',
    TaskPanel_ParentTaskHint: 'Legg denne oppgaven under en annen som en underoppgave.',
    TaskPanel_DependsOnLabel: 'Avhenger av',
    TaskPanel_RemoveDependencyTitle: 'Fjern avhengighet til "{taskTitle}"',
    TaskPanel_AddDependencyPlaceholder: 'Legg til en avhengighet…',
    TaskPanel_SelectATaskOption: 'Velg en oppgave…',
    TaskPanel_DependsOnHint: 'Oppgaven kan ikke starte før disse er fullført.',
    TaskPanel_SavingLabel: 'Lagrer…',
    TaskPanel_CreatingLabel: 'Oppretter…',
    TaskPanel_SaveChangesButton: 'Lagre endringer',
    TaskPanel_CreateTaskButton: 'Opprett oppgave',
    TaskPanel_CancelButton: 'Avbryt',
    TaskPanel_DismissAriaLabel: 'Lukk',
    TaskPanel_DiscardUnsavedChangesConfirm: 'Forkaste ulagrede endringer?',
    TaskPanel_SaveFallbackError: 'Kunne ikke lagre oppgaven.',

    // ── Project panel ──
    ProjectPanel_EditHeader: 'Rediger prosjekt',
    ProjectPanel_NewHeader: 'Nytt prosjekt',
    ProjectPanel_ProjectNameLabel: 'Prosjektnavn',
    ProjectPanel_ProjectNamePlaceholder: 'Skriv inn prosjektnavn',
    ProjectPanel_ProjectNameRequired: 'Prosjektnavn er obligatorisk',
    ProjectPanel_DescriptionLabel: 'Beskrivelse',
    ProjectPanel_DescriptionPlaceholder: 'Skriv inn beskrivelse',
    ProjectPanel_ProjectColorLabel: 'Prosjektfarge',
    ProjectPanel_StatusLabel: 'Status',
    ProjectPanel_StartDateLabel: 'Startdato',
    ProjectPanel_DueDateLabel: 'Forfallsdato',
    ProjectPanel_DueDateError: 'Forfallsdatoen må være lik eller etter startdatoen',
    ProjectPanel_WhatHappensNextTitle: 'Hva skjer videre?',
    ProjectPanel_WhatHappensNextBody: 'Du kan legge til oppgaver, sette opp faser og følge fremdriften når prosjektet er opprettet.',
    ProjectPanel_SavingLabel: 'Lagrer…',
    ProjectPanel_CreatingLabel: 'Oppretter…',
    ProjectPanel_SaveChangesButton: 'Lagre endringer',
    ProjectPanel_CreateProjectButton: 'Opprett prosjekt',
    ProjectPanel_CancelButton: 'Avbryt',
    ProjectPanel_DismissAriaLabel: 'Lukk',
    ProjectPanel_DiscardUnsavedChangesConfirm: 'Forkaste ulagrede endringer?',
    ProjectPanel_SaveFallbackError: 'Kunne ikke lagre prosjektet.',

    // ── Import panel ──
    ImportPanel_SourceExcelTitle: 'Excel-/CSV-fil',
    ImportPanel_SourceExcelSubtitle: 'Importer oppgaver fra et regneark',
    ImportPanel_SourcePlannerTitle: 'Microsoft Planner',
    ImportPanel_SourcePlannerSubtitle: 'Importer oppgaver fra en Planner-plan',
    ImportPanel_ClickToBrowse: 'Klikk for å bla gjennom',
    ImportPanel_DragDropSuffix: ' eller dra og slipp',
    ImportPanel_SupportedExtensions: 'Støtter .xlsx, .xls, .csv',
    ImportPanel_RowsColsSummary: '{rows} rader, {cols} kolonner oppdaget',
    ImportPanel_LoadingPlannerPlans: 'Laster Planner-planer…',
    ImportPanel_PlannerLoadError: 'Kunne ikke laste Planner-planer.',
    ImportPanel_PlannerPermissionsHintPrefix: 'Kontroller at du har tilgang til Planner, og at ',
    ImportPanel_PlannerPermissionsHintEmphasis: 'Oppgaver av Planner og To Do',
    ImportPanel_PlannerPermissionsHintSuffix: ' er tilgjengelig for dette nettstedet.',
    ImportPanel_NoPlannerPlansFoundTitle: 'Fant ingen Planner-planer',
    ImportPanel_NoPlannerPlansFoundBody: 'Du har kanskje ikke tilgang til noen Planner-planer, eller ingen finnes for denne kontoen.',
    ImportPanel_TaskCountFoundIn: '{count} oppgaver funnet i "{planName}"',
    ImportPanel_ProjectDetailsIntroPrefix: 'Importerer til ',
    ImportPanel_ProjectDetailsIntroSuffix: '. Se gjennom prosjektdetaljene nedenfor.',
    ImportPanel_ProjectNameLabel: 'Prosjektnavn',
    ImportPanel_DescriptionLabel: 'Beskrivelse',
    ImportPanel_StatusLabel: 'Status',
    ImportPanel_ColorLabel: 'Farge',
    ImportPanel_MapIntro: 'Koble kolonnene i filen til oppgavefeltene.',
    ImportPanel_CreatingProjectStatus: 'Oppretter prosjekt…',
    ImportPanel_ImportingTasksStatus: 'Importerer oppgaver…',
    ImportPanel_ProgressLabel: '{done} av {total}',
    ImportPanel_CouldNotCreateProject: 'Kunne ikke opprette prosjektet.',
    ImportPanel_ImportCompletedWithErrors: 'Import fullført med {count} feil.',
    ImportPanel_ProjectCreatedSuccess: 'Prosjektet ble opprettet!',
    ImportPanel_ImportSuccessful: 'Import vellykket!',
    ImportPanel_TasksAddedTo: '{count} oppgaver lagt til i "{projectName}"',
    ImportPanel_FailedRowsLabel: 'Mislykkede rader:',
    ImportPanel_CloseButton: 'Lukk',
    ImportPanel_OpenProjectButton: 'Åpne prosjekt',
    ImportPanel_ViewImportedTasksButton: 'Vis importerte oppgaver',
    ImportPanel_NextMapColumnsButton: 'Neste: Koble kolonner',
    ImportPanel_ImportNTasksButton: 'Importer {count} oppgaver',
    ImportPanel_BackButton: 'Tilbake',
    ImportPanel_CancelButton: 'Avbryt',
    ImportPanel_NextButton: 'Neste',
    ImportPanel_StepSource: 'Kilde',
    ImportPanel_StepProject: 'Prosjekt',
    ImportPanel_StepMap: 'Koble',
    ImportPanel_StepImport: 'Importer',
    ImportPanel_StepDone: 'Ferdig',
    ImportPanel_ImportAsNewProjectHeader: 'Importer fil som nytt prosjekt',
    ImportPanel_ImportIntoProjectHeader: 'Importer oppgaver til {projectName}',
    ImportPanel_CouldNotParseFile: 'Kunne ikke tolke filen.',
    ImportPanel_CouldNotLoadPlannerTasks: 'Kunne ikke laste oppgaver fra denne planen.',
    ImportPanel_CouldNotCreateProjectDetail: 'Kunne ikke opprette prosjekt: {detail}',
    ImportPanel_CouldNotLinkDependencies: 'Kunne ikke koble avhengigheter: {detail}',
    ImportPanel_UnknownError: 'ukjent feil',

    // ── Column mapper (import) ──
    ColumnMapper_TaskNameRequiredBanner: 'Oppgavenavn må kobles for å fortsette.',
    ColumnMapper_SkippedColumnsBanner: '{count} kolonne(r) vil bli hoppet over.',
    ColumnMapper_SourceColumnHeader: 'Kildekolonne',
    ColumnMapper_TargetFieldHeader: 'Målfelt',
    ColumnMapper_StatusHeader: 'Status',
    ColumnMapper_SkippedBadge: 'Hoppet over',
    ColumnMapper_AutoMappedBadge: 'Autokoblet',
    ColumnMapper_SetBadge: 'Angitt',
    ColumnMapper_PreviewTitle: 'Forhåndsvisning: {columnName}',
    ColumnMapper_EmptyCellDash: '—',

    // ── Import field display names / ImportService ──
    ImportField_TaskName: 'Oppgavenavn',
    ImportField_StartDate: 'Startdato',
    ImportField_DueDate: 'Forfallsdato',
    ImportField_Status: 'Status',
    ImportField_Priority: 'Prioritet',
    ImportField_AssignedTo: 'Tildelt til',
    ImportField_AssignedToEmail: 'E-post til ansvarlig',
    ImportField_PercentComplete: '% Fullført',
    ImportField_Phase: 'Fase',
    ImportField_Description: 'Beskrivelse',
    ImportField_Notes: 'Notater',
    ImportField_IsMilestone: 'Er milepæl',
    ImportField_Dependencies: 'Avhengigheter',
    ImportField_SkipColumn: '(Hopp over denne kolonnen)',
    ImportService_EmptyFileError: 'Filen ser ut til å være tom eller har ingen datarader.',
    ImportService_ReadErrorDetail: 'Kunne ikke lese filen: {detail}.',
    ImportService_FileReadError: 'Feil ved lesing av fil.',
    ImportService_RowError: 'Rad {rowNum} ("{title}"): {error}',
    ImportService_AmbiguousDependency: 'Avhengigheten "{name}" samsvarer med mer enn én oppgavetittel – hoppet over.',
    ImportService_LinkDependencyError: 'Kunne ikke koble avhengigheter for oppgave {taskId}: {error}',

    // ── Health labels (shared: healthUtils.ts and ExportService.ts both use this set; also replaces the duplicated Export_PortfolioHealthLabel* keys) ──
    Health_Done: 'Ferdig',
    Health_OnTrack: 'På sporet',
    Health_AtRisk: 'I faresonen',
    Health_Overdue: 'Forfalt',

    // ── Status / Priority display labels (DISPLAY-ONLY — stored SharePoint Choice values remain unchanged/English) ──
    Status_NotStarted: 'Ikke startet',
    Status_InProgress: 'Pågår',
    Status_Completed: 'Fullført',
    Status_OnHold: 'På vent',
    Status_Cancelled: 'Avbrutt',
    Priority_Critical: 'Kritisk',
    Priority_High: 'Høy',
    Priority_Medium: 'Middels',
    Priority_Low: 'Lav',
    ProjectStatus_Planning: 'Planlegging',
    ProjectStatus_Active: 'Aktivt',
    ProjectStatus_OnHold: 'På vent',
    ProjectStatus_Completed: 'Fullført',
    ProjectStatus_Cancelled: 'Avbrutt',

    // ── Shell (SmartGantt.tsx) ──
    SmartGantt_LoadingProjects: 'Laster prosjekter…',
    SmartGantt_UnableToLoad: 'Kan ikke laste',
    SmartGantt_RetryButton: 'Prøv igjen',
    SmartGantt_NoProjectsYet: 'Ingen prosjekter ennå',
    SmartGantt_NoProjectsSubtitle: 'Opprett ditt første prosjekt for å komme i gang.',
    SmartGantt_CreateFirstProjectButton: '+ Opprett første prosjekt',
    SmartGantt_ImportFromExcelButton: '📥 Importer fra Excel',
    SmartGantt_LoadingTasks: 'Laster oppgaver…',
    SmartGantt_DismissAriaLabel: 'Lukk',
    SmartGantt_DeleteTaskDialogTitle: 'Slett oppgave',
    SmartGantt_DeleteTaskDialogSubtext: 'Er du sikker på at du vil slette "{taskTitle}"? Dette kan ikke angres.',
    SmartGantt_DeleteButton: 'Slett',
    SmartGantt_CancelButton: 'Avbryt',
    SmartGantt_ArchiveProjectDialogTitle: 'Arkiver prosjekt',
    SmartGantt_ArchiveProjectDialogSubtext: 'Arkivere "{projectTitle}"? Du kan gjenopprette det senere.',
    SmartGantt_ArchiveButton: 'Arkiver',
    SmartGantt_SendToRecycleBinDialogTitle: 'Send til papirkurven',
    SmartGantt_SendToRecycleBinDialogSubtext: 'Sende "{projectTitle}" til nettstedets papirkurv?',
    SmartGantt_SendToRecycleBinButton: 'Send til papirkurven',
    SmartGantt_FailedLoadProjects: 'Kunne ikke laste prosjekter. Kontroller nettstedstillatelsene.',
    SmartGantt_FailedLoadTasks: 'Kunne ikke laste oppgaver for dette prosjektet.',
    SmartGantt_FailedLoadPortfolioStats: 'Kunne ikke laste porteføljestatistikk.',
    SmartGantt_CouldNotSaveProject: 'Kunne ikke lagre prosjektet: {message}',
    SmartGantt_CouldNotDeleteProject: 'Kunne ikke slette prosjektet: {message}',
    SmartGantt_CouldNotArchiveProject: 'Kunne ikke arkivere prosjektet: {message}',
    SmartGantt_CouldNotUnarchiveProject: 'Kunne ikke gjenopprette prosjektet fra arkiv: {message}',
    SmartGantt_CouldNotSaveTask: 'Kunne ikke lagre oppgaven: {message}',
    SmartGantt_CouldNotDeleteTask: 'Kunne ikke slette oppgaven: {message}',
    SmartGantt_ImageExportFailed: 'Bildeeksport mislyktes: {message}',
    SmartGantt_PowerPointExportFailed: 'PowerPoint-eksport mislyktes: {message}',
    SmartGantt_PortfolioExportFailed: 'Porteføljeeksport mislyktes: {message}',
    SmartGantt_CouldNotUpdateTask: 'Kunne ikke oppdatere oppgaven: {message}',

    // ── Common ──
    ColorSwatch_AutoColorAriaLabel: 'Automatisk farge',
    ColorSwatch_CustomColorAriaLabel: 'Egendefinert farge',
    ColorSwatch_PickCustomColorTitle: 'Velg en egendefinert farge',

    // ── Export (Excel / PowerPoint) ──
    Export_ColTaskName: 'Oppgavenavn',
    Export_ColPhase: 'Fase',
    Export_ColStartDate: 'Startdato',
    Export_ColDueDate: 'Forfallsdato',
    Export_ColStatus: 'Status',
    Export_ColPriority: 'Prioritet',
    Export_ColAssignedTo: 'Tildelt til',
    Export_ColAssignedToEmail: 'E-post til ansvarlig',
    Export_ColPercentComplete: '% Fullført',
    Export_ColIsMilestone: 'Er milepæl',
    Export_ColDescription: 'Beskrivelse',
    Export_ColNotes: 'Notater',
    Export_Yes: 'Ja',
    Export_No: 'Nei',
    Export_SheetNameTasks: 'Oppgaver',
    Export_ExcelFileSuffix: ' - Oppgaver.xlsx',
    Export_TaskNameColumnLabel: 'OPPGAVENAVN',
    Export_ExportedDateLabel: 'Eksportert {date}',
    Export_ProjectReportLabel: 'PROSJEKTRAPPORT',
    Export_StatusLine: 'Status: {status}',
    Export_DateRangeSeparator: ' til ',
    Export_ProjectManagerLine: 'Prosjektleder: {name}',
    Export_GeneratedDateLine: 'Generert {date}',
    Export_ProjectSummaryTitle: 'Prosjektsammendrag',
    Export_StatTotalTasks: 'Oppgaver totalt',
    Export_StatCompleted: 'Fullført',
    Export_StatInProgress: 'Pågår',
    Export_StatOnHold: 'På vent',
    Export_StatNotStarted: 'Ikke startet',
    Export_OverallProgressLine: 'Samlet fremdrift',
    Export_OverallProgressPercent: '{percent}%',
    Export_StatusBreakdownTitle: 'Statusfordeling',
    Export_StatusBreakdownRow: '{status}: {count} ({percent}%)',
    Export_GanttTimelineTitle: 'Gantt-tidslinje',
    Export_SummaryRecentActivityTitle: 'Nylig aktivitet',
    Export_ProjectOverviewLabel: 'Prosjektoversikt',
    Export_DetailStatusLabel: 'Status',
    Export_DetailStartDateLabel: 'Startdato',
    Export_DetailDueDateLabel: 'Forfallsdato',
    Export_DetailProjectManagerLabel: 'Prosjektleder',
    Export_Past7DaysLabel: 'Siste 7 dager',
    Export_NoActivityMessage: 'Ingen nylig aktivitet.',
    Export_CompletedThisWeekHeader: 'Fullført denne uken ({count})',
    Export_NewBadge: 'NY  ',
    Export_CompletedPercentLine: '{percent}% fullført',
    Export_MoreItemsSuffix: '+ {count} til',
    Export_InProgressUpdatedHeader: 'Pågår / Oppdatert',
    Export_StatusPercentLine: '{status} — {percent}%',
    Export_PortfolioReportLabel: 'PORTEFØLJERAPPORT',
    Export_PortfolioOverviewTitle: 'Porteføljeoversikt',
    Export_ProjectsCountLine: '{count} prosjekter',
    Export_HealthSummaryOnTrack: '{count} på sporet',
    Export_HealthSummaryAtRisk: '{count} i faresonen',
    Export_HealthSummaryOverdue: '{count} forfalt',
    Export_ProjectsSummaryHeader: 'Prosjektsammendrag',
    Export_TableProject: 'Prosjekt',
    Export_TableStatus: 'Status',
    Export_TableHealth: 'Helsetilstand',
    Export_TableTotal: 'Totalt',
    Export_TableDone: 'Ferdig',
    Export_TableActive: 'Aktive',
    Export_TableAtRisk: 'I faresonen',
    Export_TableOverdue: 'Forfalt',
    Export_TablePctDone: '% Ferdig',
    Export_TableDueDate: 'Forfallsdato',
    Export_PortfolioSummaryFileName: 'Porteføljesammendrag.xlsx',
    Export_PortfolioReportFileName: 'Porteføljerapport.pptx',
    Export_ProjectReportFileName: '{projectName} rapport.pptx',
    Export_UnavailableLabel: 'Utilgjengelig',
    Export_SheetNamePortfolio: 'Portefølje',
    Export_ColStart: 'Start',
    Export_ColDue: 'Forfall',
    Export_ImageGenerationFailed: 'Kunne ikke generere bildet – diagrammet kan være for stort til å eksporteres som bilde.',
    Export_DrawingContextFailed: 'Kunne ikke opprette en tegnekontekst for eksporten.',
    Export_SvgRenderFailed: 'SVG-rendering mislyktes',

    // ── Added in v1.5 review ──
    Svc_TooManyDependencies: 'Denne oppgaven har for mange avhengigheter til å kunne lagres (grensen er rundt 60). Fjern noen og prøv igjen.',
    Svc_TaskChangedByOthers: 'Denne oppgaven er endret av noen andre siden du lastet den inn. Oppdater og prøv igjen.',
    Svc_ProjectChangedByOthers: 'Dette prosjektet er endret av noen andre siden du åpnet det. Oppdater og prøv igjen.',
    Svc_ColumnCreateFailed: 'Kunne ikke opprette {count} kolonne(r) i den nye oppgavelisten: {detail}',
    Svc_BaselineUnavailable: 'Baselines er ikke tilgjengelige for dette prosjektet fordi baseline-kolonnene ikke kunne legges til (du trenger kanskje tillatelse til å redigere listen).',
    Svc_SubtaskReassignFailed: 'Kunne ikke tilordne underoppgavene til denne oppgaven på nytt før sletting: {detail}',
    Svc_UnresolvedDependency: 'Rad {row} («{title}»): avhengigheten «{name}» kunne ikke kobles til en importert oppgave.',
    Svc_SelfDependency: 'Rad {row} («{title}»): avhengigheten «{name}» peker på selve oppgaven og ble hoppet over.',
    Svc_ColId: 'ID',
    Svc_ColDependencies: 'Avhengigheter',
    Svc_ColBaselineStart: 'Baseline-start',
    Svc_ColBaselineDue: 'Baseline-frist',
    Svc_CsvFileSuffix: ' - Oppgaver.csv',
    Svc_IcsFileSuffix: ' - Milepæler.ics',
    Svc_PortfolioCsvFileName: 'Porteføljeoversikt.csv',
    Svc_PP_DisplayGroup: 'Standarder',
    Svc_PP_DefaultView: 'Standardvisning',
    Svc_PP_ViewGantt: 'Gantt',
    Svc_PP_ViewList: 'Liste',
    Svc_PP_ViewKanban: 'Kanban',
    Svc_PP_ViewDashboard: 'Dashbord',
    Svc_PP_ViewPortfolio: 'Portefølje',
    Svc_PP_DefaultZoom: 'Standardzoom',
    Svc_PP_ZoomDay: 'Dag',
    Svc_PP_ZoomWeek: 'Uke',
    Svc_PP_ZoomMonth: 'Måned',
    Svc_PP_ZoomQuarter: 'Kvartal',
    Svc_PP_CalendarGroup: 'Arbeidskalender',
    Svc_PP_DaySun: 'Søndag er en arbeidsdag',
    Svc_PP_DayMon: 'Mandag er en arbeidsdag',
    Svc_PP_DayTue: 'Tirsdag er en arbeidsdag',
    Svc_PP_DayWed: 'Onsdag er en arbeidsdag',
    Svc_PP_DayThu: 'Torsdag er en arbeidsdag',
    Svc_PP_DayFri: 'Fredag er en arbeidsdag',
    Svc_PP_DaySat: 'Lørdag er en arbeidsdag',
    Svc_PP_Holidays: 'Helligdager (fridager)',
    Svc_PP_HolidaysHint: 'Én dato per linje i formatet åååå-MM-dd (for eksempel 2026-12-25).',
    Gantt_TimelineAriaLabel: 'Oppgavetidslinje',
    Gantt_DragLabel: '{start} → {end} ({days} d)',
    Gantt_KeyboardMoveAnnouncement: '{taskTitle}: {startDate} til {dueDate}',
    Gantt_KeyboardHint: 'Trykk Enter for å åpne oppgaven. Venstre- og høyrepil flytter den én arbeidsdag. Shift sammen med piltastene endrer sluttdatoen.',
    Gantt_ParentCycleTooltip: 'Denne oppgaven er en del av en sirkulær kjede av overordnede oppgaver og underoppgaver, så den vises på øverste nivå',
    Gantt_CollapseAll: 'Skjul alle faser',
    Gantt_ExpandAll: 'Vis alle faser',
    Gantt_BaselineTooltip: 'Baseline: {start} → {due}',
    Gantt_VarianceTooltip: 'Avvik i ferdigstillelse: {days} dager i forhold til baseline',
    Gantt_LinkHandleTitle: 'Dra til en annen oppgave for å opprette en avhengighet',
    Toolbar_FitToProject: 'Tilpass',
    Toolbar_FitToProjectTitle: 'Zoom for å vise hele prosjektet',
    Toolbar_UndoTitle: 'Angre (Ctrl+Z)',
    Toolbar_RedoTitle: 'Gjør om (Ctrl+Y)',
    Toolbar_ExportCsv: '📄 Eksporter oppgaver til CSV',
    Toolbar_ExportIcs: '📅 Eksporter milepæler (iCal)',
    Toolbar_Print: '🖨 Skriv ut / Lagre som PDF',
    Toolbar_SetBaseline: '📐 Angi baseline…',
    Toolbar_CopyLink: '🔗 Kopier kobling',
    Toolbar_CopyLinkTitle: 'Kopier en kobling til denne visningen (prosjekt, visning, zoom og filtre)',
    App_UndoButton: 'Angre',
    App_Undone: 'Endringen er angret.',
    App_Redone: 'Endringen er gjort om.',
    App_DependentsMovedOne: '1 avhengig oppgave ble flyttet.',
    App_DependentsMovedMany: '{count} avhengige oppgaver ble flyttet.',
    App_TaskConflict: 'Denne oppgaven er endret av noen andre. De nyeste oppgavene er lastet inn på nytt – se over dem og prøv igjen.',
    App_DependencyCycle: 'Denne koblingen ville skapt en sirkulær avhengighet.',
    App_DependencyExists: 'Disse oppgavene er allerede koblet sammen.',
    App_LinkCopied: 'Koblingen er kopiert til utklippstavlen.',
    App_LinkCopyFailed: 'Kunne ikke kopiere koblingen: {message}',
    App_PopupBlocked: 'Utskriftsvinduet ble blokkert. Tillat popup-vinduer for dette nettstedet og prøv igjen.',
    App_SetBaselineDialogTitle: 'Angi baseline',
    App_SetBaselineDialogSubtext: 'Vil du lagre gjeldende start- og forfallsdatoer for alle {count} oppgaver som baseline? Eventuell eksisterende baseline erstattes.',
    App_SetBaselineButton: 'Angi baseline',
    App_BaselineSaved: 'Baseline er lagret.',
    App_BaselineFailed: 'Kunne ikke lagre baseline: {message}',
    App_CsvExportFailed: 'CSV-eksport mislyktes: {message}',
    App_IcsExportFailed: 'Kalendereksport mislyktes: {message}',
    App_BulkDeleteDialogTitle: 'Slett oppgaver',
    App_BulkDeleteDialogSubtext: 'Er du sikker på at du vil slette {count} oppgaver? Dette kan ikke angres.',
    Common_PeoplePicker_ClearAriaLabel: 'Tøm',
    Common_PeoplePicker_DirectoryHeader: 'Personer i katalogen',
    Common_PeoplePicker_EmailLabel: 'E-post (valgfritt)',
    Common_PeoplePicker_EmailPlaceholder: 'navn@firma.no',
    Common_PeoplePicker_ExternalHint: 'Ikke i katalogen. Lagres som fritekst.',
    Common_PeoplePicker_InvalidEmail: 'Skriv inn en gyldig e-postadresse.',
    Common_PeoplePicker_ListAriaLabel: 'Personforslag',
    Common_PeoplePicker_RecentHeader: 'Nylig brukt',
    Common_PeoplePicker_ResultsAnnouncement: '{count} forslag tilgjengelig',
    Common_PeoplePicker_Searching: 'Søker…',
    Common_PeoplePicker_UseExternal: 'Bruk «{name}» (ekstern / ikke i katalogen)',
    Import_Mapper_PreviewFirstRows: 'Forhåndsvisning (første {count} rader)',
    Import_Mapper_RequiredLegend: 'Obligatorisk felt',
    Import_Mapper_RequiredMarkerLabel: 'Obligatorisk',
    Import_Mapper_SelectAriaLabel: 'Målfelt for kolonnen {columnName}',
    Import_Panel_DateOrderAuto: 'Registrer automatisk',
    Import_Panel_DateOrderDMY: 'Dag/måned/år (31/12/2026)',
    Import_Panel_DateOrderDetected: 'Registrert fra filen din: {order}.',
    Import_Panel_DateOrderHint: 'Gjelder datoer skrevet med tall, for eksempel 03/04/2026.',
    Import_Panel_DateOrderLabel: 'Datorekkefølge',
    Import_Panel_DateOrderMDY: 'Måned/dag/år (12/31/2026)',
    Import_Panel_DropZoneAriaLabel: 'Velg en fil du vil importere. Trykk Enter for å bla.',
    Import_Panel_DropZoneChangeAriaLabel: 'Valgt fil {fileName}. Trykk Enter for å velge en annen fil.',
    Import_Panel_FailedCount: '{count} mislyktes',
    Import_Panel_NewProjectIntroMany: 'Et nytt prosjekt opprettes, og alle {count} oppgaver importeres til det. Du kan endre disse detaljene når som helst etter importen.',
    Import_Panel_NewProjectIntroOne: 'Et nytt prosjekt opprettes, og {count} oppgave importeres til det. Du kan endre disse detaljene når som helst etter importen.',
    Import_Panel_PlanAriaLabel: '{planName}, {groupName}',
    Import_Panel_ProblemEndBeforeStart: 'Forfallsdatoen er før startdatoen',
    Import_Panel_ProblemInvalidDueDate: 'Forfallsdatoen «{value}» er ikke en gyldig dato',
    Import_Panel_ProblemInvalidStartDate: 'Startdatoen «{value}» er ikke en gyldig dato',
    Import_Panel_ProblemMissingTitle: 'Oppgavenavn mangler',
    Import_Panel_ProgressLabelWithPercent: '{done} av {total} ({percent} %)',
    Import_Panel_SkipInvalidRows: 'Hopp over rader med problemer',
    Import_Panel_SuccessWithWarningsMany: 'Importen var vellykket med {count} advarsler.',
    Import_Panel_SuccessWithWarningsOne: 'Importen var vellykket med {count} advarsel.',
    Import_Panel_ValidationHeader: 'Rader med problemer',
    Import_Panel_ValidationMore: '…og {count} til',
    Import_Panel_ValidationRow: 'Rad {rowNum}: {problem}',
    Import_Panel_ValidationSummaryMany: '{count} rader har problemer',
    Import_Panel_ValidationSummaryOne: '{count} rad har et problem',
    Import_Panel_WarningsLabel: 'Advarsler ({count}):',
    Panel_Project_ManagerLabel: 'Prosjektleder',
    Panel_Project_ManagerPlaceholder: 'Søk etter personer eller skriv et navn…',
    Panel_Task_BaselineDueLabel: 'Baseline-ferdigstillelse',
    Panel_Task_BaselineHeader: 'Baseline',
    Panel_Task_BaselineStartLabel: 'Baseline-start',
    Panel_Task_DepTypeFF: 'Slutt til slutt (FF)',
    Panel_Task_DepTypeFS: 'Slutt til start (FS)',
    Panel_Task_DepTypeSF: 'Start til slutt (SF)',
    Panel_Task_DepTypeSS: 'Start til start (SS)',
    Panel_Task_LagAriaLabel: 'Forsinkelse i arbeidsdager for {taskTitle}',
    Panel_Task_LagHint: 'Forsinkelse oppgis i arbeidsdager. Bruk et negativt tall for framskyndelse.',
    Panel_Task_LinkTypeAriaLabel: 'Koblingstype for {taskTitle}',
    Panel_Task_VarianceEarlier: '{days} arbeidsdag(er) tidligere',
    Panel_Task_VarianceLater: '{days} arbeidsdag(er) senere',
    Panel_Task_VarianceOnBaseline: 'på baseline',
    View_Dashboard_BurndownActual: 'Faktisk',
    View_Dashboard_BurndownAria: 'Burndown-diagram: {remaining} av {total} oppgaver gjenstår',
    View_Dashboard_BurndownHeader: 'Burndown (gjenstående oppgaver)',
    View_Dashboard_BurndownIdeal: 'Ideell',
    View_Dashboard_BurndownNoData: 'Ikke nok oppgaver med datoer til å tegne et burndown.',
    View_Dashboard_CriticalPathHeader: 'Kritisk linje  ({count})',
    View_Dashboard_PhaseDoneSummary: '{done}/{total} ferdig  •  {percent} %',
    View_Dashboard_TaskRowAriaLabel: 'Åpne oppgaven {taskTitle}, {status}',
    View_Dashboard_WorkloadHeader: 'Arbeidsmengde per ansvarlig',
    View_Dashboard_WorkloadOpen: '{count} åpne',
    View_Dashboard_WorkloadOverdue: '{count} forfalt',
    View_Kanban_AddTaskInColumnAriaLabel: 'Legg til oppgave i {column}',
    View_Kanban_CollapseColumn: 'Skjul kolonnen {column}',
    View_Kanban_ExpandColumn: 'Vis kolonnen {column}',
    View_Kanban_LaneHeader: '{name} ({count})',
    View_Kanban_LaneNoPhase: 'Ingen fase',
    View_Kanban_LaneUnassigned: 'Ikke tilordnet',
    View_Kanban_LanesAssignee: 'Ansvarlig',
    View_Kanban_LanesNone: 'Ingen',
    View_Kanban_LanesPhase: 'Fase',
    View_Kanban_SwimlanesLabel: 'Swimlanes',
    View_Kanban_WipEditTitle: 'Angi grense for pågående arbeid for {column} (0 for ingen grense)',
    View_Kanban_WipExceededTitle: 'WIP-grensen er overskredet: {count} av {limit}',
    View_Kanban_WipInputAriaLabel: 'WIP-grense for {column}',
    View_Kanban_WipLabel: 'WIP {count}/{limit}',
    View_Kanban_WipSet: 'WIP',
    View_List_BulkAssignApply: 'Tilordne',
    View_List_BulkAssigneePlaceholder: 'Tilordne til…',
    View_List_BulkBarAriaLabel: 'Massehandlinger for valgte oppgaver',
    View_List_BulkClear: 'Fjern utvalg',
    View_List_BulkDelete: 'Slett valgte',
    View_List_BulkPercentApply: 'Angi %',
    View_List_BulkPercentPlaceholder: '% fullført',
    View_List_BulkPriorityPlaceholder: 'Angi prioritet…',
    View_List_BulkSelectedCount: '{count} valgt',
    View_List_BulkStatusPlaceholder: 'Angi status…',
    View_List_ExportCsv: 'Eksporter CSV',
    View_List_NonWorkingDay: 'Fridag',
    View_List_SelectAllAriaLabel: 'Velg alle oppgaver',
    View_List_SelectRowAriaLabel: 'Velg {taskTitle}',
    View_Portfolio_CardAriaLabel: 'Åpne prosjektet {projectName}, {status}',
    View_Portfolio_ClearFilters: 'Fjern filtre',
    View_Portfolio_FilteredCount: '{shown} av {total} prosjekter',
    View_Portfolio_HideDone: 'Skjul fullførte / avbrutte',
    View_Portfolio_NoMatches: 'Ingen prosjekter samsvarer med filtrene dine.',
    View_Portfolio_ProjectCountMany: '{count} prosjekter',
    View_Portfolio_ProjectCountOne: '{count} prosjekt',
    View_Portfolio_SearchAriaLabel: 'Søk etter prosjekter',
    View_Portfolio_SearchPlaceholder: 'Søk etter prosjekter…',
    Import_Panel_CopyDetails: 'Kopier detaljer',
    Import_Panel_Copied: 'Kopiert',
  };
});
