define([], function () {
  return {
    // ── Property pane ──
    PropertyPane_HeaderDescription: 'Instellingen voor Smart Gantt Chart',
    PropertyPane_GeneralGroupName: 'Algemeen',
    PropertyPane_TitleFieldLabel: 'Titel van de webonderdeel',
    WebPart_DefaultTitle: 'Smart Gantt Chart',

    // ── Toolbar ──
    Toolbar_ViewDashboard: 'Dashboard',
    Toolbar_ViewList: 'Lijst',
    Toolbar_ViewGantt: 'Gantt',
    Toolbar_ViewKanban: 'Kanban',
    Toolbar_ZoomDay: 'Dag',
    Toolbar_ZoomWeek: 'Week',
    Toolbar_ZoomMonth: 'Maand',
    Toolbar_ZoomQuarter: 'Kwartaal',
    Toolbar_SelectProjectAriaLabel: 'Project selecteren',
    Toolbar_PortfolioLabel: 'Portfolio',
    Toolbar_SelectAProject: 'Selecteer een project',
    Toolbar_AllProjectsSubtext: 'Alle projecten',
    Toolbar_NoProjectsYet: 'Nog geen projecten',
    Toolbar_ArchivedBadge: 'Gearchiveerd',
    Toolbar_ShowArchivedProjects: 'Gearchiveerde projecten weergeven',
    Toolbar_NewProject: '+ Nieuw project',
    Toolbar_ImportFileAsNewProject: '📥 Bestand importeren als nieuw project…',
    Toolbar_AddTask: '+ Taak toevoegen',
    Toolbar_EditProject: 'Project bewerken',
    Toolbar_OptionsButton: '⚙ Opties',
    Toolbar_MoreOptionsTitle: 'Meer opties',
    Toolbar_ExportToExcel: '📊 Exporteren naar Excel',
    Toolbar_ExportToPowerPoint: '📑 Exporteren naar PowerPoint',
    Toolbar_ScrollToTodayTitle: 'Ga naar vandaag',
    Toolbar_TodayButton: '◉ Vandaag',
    Toolbar_ImportTasks: '📥 Taken importeren…',
    Toolbar_ExportAsImage: '🖼 Exporteren als afbeelding (PNG)',
    Toolbar_UnarchiveProject: '📂 Project uit archief halen',
    Toolbar_ArchiveProject: '🗄️ Project archiveren',
    Toolbar_SendToRecycleBin: '🗑️ Naar prullenbak verplaatsen',

    // ── Filter bar ──
    FilterBar_ClearOption: 'Wissen',
    FilterBar_DueAny: 'Elke vervaldatum',
    FilterBar_DueOverdue: 'Te laat',
    FilterBar_DueToday: 'Vervalt vandaag',
    FilterBar_DueWeek: 'Vervalt binnen 7 dagen',
    FilterBar_SearchPlaceholder: 'Taken zoeken…',
    FilterBar_SearchAriaLabel: 'Taken zoeken',
    FilterBar_StatusChipLabel: 'Status',
    FilterBar_PriorityChipLabel: 'Prioriteit',
    FilterBar_AssigneeChipLabel: 'Toegewezen aan',
    FilterBar_PhaseChipLabel: 'Fase',
    FilterBar_DueDateAriaLabel: 'Filteren op vervaldatum',
    FilterBar_MatchCount: '{matchCount} van {totalCount}',
    FilterBar_ClearFilters: '✕ Filters wissen',
    FilterBar_ChipLabelWithCount: '{label} ({count}) ▾',
    FilterBar_ChipLabelNoCount: '{label} ▾',

    // ── Gantt view ──
    Gantt_TaskColumnHeader: 'Taak',
    Gantt_DurationColumnHeader: 'Duur',
    Gantt_AddTaskButton: '+ Taak toevoegen',
    Gantt_EmptyTitle: 'Nog geen taken',
    Gantt_EmptySubtitle: 'Voeg taken toe om ze in het Gantt-diagram te zien.',
    Gantt_AddFirstTask: '+ Eerste taak toevoegen',
    Gantt_ImportTasksButton: '📥 Taken importeren',
    Gantt_EditTitle: 'Bewerken',
    Gantt_DeleteTitle: 'Verwijderen',
    Gantt_EditTaskAriaLabel: 'Taak {taskTitle} bewerken',
    Gantt_DeleteTaskAriaLabel: 'Taak {taskTitle} verwijderen',
    Gantt_ExpandPhaseAriaLabel: 'Fase {phase} {action}',
    Gantt_ExpandAction: 'uitvouwen',
    Gantt_CollapseAction: 'samenvouwen',
    Gantt_DependencyViolationTooltip: 'Gestart voordat alle afhankelijkheden waren voltooid',
    Gantt_MilestoneAriaLabel: '{taskTitle}, mijlpaal, {date}',
    Gantt_BarAriaLabel: '{taskTitle}, {startDate} tot {dueDate}, {percent}% voltooid',
    Gantt_PercentCompleteTooltip: '{value}% voltooid',

    // ── Gantt options/settings panel ──
    GanttSettings_PanelHeader: '⚙ Opties',
    GanttSettings_ColorCodingSection: 'Kleurcodering',
    GanttSettings_ByStatus: 'Op status',
    GanttSettings_ByPriority: 'Op prioriteit',
    GanttSettings_ByPhase: 'Op fase',
    GanttSettings_ByHealth: 'Op gezondheidsstatus',
    GanttSettings_HeaderColorSection: 'Koptekstkleur',
    GanttSettings_ThemeDark: 'Donker',
    GanttSettings_ThemeNavy: 'Marineblauw',
    GanttSettings_ThemeTeal: 'Petrolblauw',
    GanttSettings_ThemePurple: 'Paars',
    GanttSettings_ThemeLight: 'Licht',
    GanttSettings_HeaderLabelsSection: 'Koptekstlabels',
    GanttSettings_WeekLabelDates: 'Datums',
    GanttSettings_WeekLabelDatesDesc: '3 jun, 10 jun…',
    GanttSettings_WeekLabelProject: 'Projectweken',
    GanttSettings_WeekLabelProjectDesc: 'W1, W2…',
    GanttSettings_WeekLabelIso: 'Kalenderweken',
    GanttSettings_WeekLabelIsoDesc: 'W23, W24…',
    GanttSettings_ProjectWeeksHint: 'Week 1 begint op de maandag van uw vroegste taak, ideaal voor presentaties.',
    GanttSettings_BarStyleSection: 'Balkstijl',
    GanttSettings_BarStyleGradient: 'Verloop',
    GanttSettings_BarStyleFlat: 'Vlak',
    GanttSettings_RowHeightSection: 'Rijhoogte',
    GanttSettings_HeightCompact: 'Compact',
    GanttSettings_HeightNormal: 'Normaal',
    GanttSettings_HeightSpacious: 'Ruim',
    GanttSettings_ShowHideSection: 'Weergeven / Verbergen',
    GanttSettings_WeekendShading: 'Weekendmarkering',
    GanttSettings_DependencyArrows: 'Afhankelijkheidspijlen',
    GanttSettings_CriticalPathAlwaysVisible: 'Kritiek pad altijd zichtbaar',
    GanttSettings_AllOthersOnHoverOnly: 'Overige alleen bij aanwijzen',
    GanttSettings_CriticalPathHighlight: 'Kritiek pad markeren',
    GanttSettings_ProgressPercentOnBars: 'Voortgang % op balken',
    GanttSettings_AssigneeNameOnBars: 'Naam van toegewezene op balken',
    GanttSettings_HealthStatusBadges: 'Badges voor gezondheidsstatus',

    // ── List view ──
    ListView_ColTaskName: 'Taaknaam',
    ListView_ColStatus: 'Status',
    ListView_ColHealth: 'Gezondheidsstatus',
    ListView_ColPriority: 'Prioriteit',
    ListView_ColStart: 'Start',
    ListView_ColDue: 'Vervaldatum',
    ListView_ColAssignedTo: 'Toegewezen aan',
    ListView_ColProgress: 'Voortgang',
    ListView_ColPhase: 'Fase',
    ListView_ColPredecessors: 'Voorgangers',
    ListView_EmptyTitle: 'Nog geen taken',
    ListView_AddFirstTask: '+ Eerste taak toevoegen',
    ListView_AddTaskRow: '+ Taak toevoegen',
    ListView_Unassigned: 'Niet toegewezen',
    ListView_DependencyViolationTooltip: 'Gestart voordat alle afhankelijkheden waren voltooid',
    ListView_StatusAriaLabel: 'Status van {taskTitle}',
    ListView_PriorityAriaLabel: 'Prioriteit van {taskTitle}',
    ListView_EditTaskAriaLabel: 'Taak {taskTitle} bewerken',
    ListView_DeleteTaskAriaLabel: 'Taak {taskTitle} verwijderen',
    ListView_EditTitle: 'Bewerken',
    ListView_DeleteTitle: 'Verwijderen',

    // ── Kanban view ──
    Kanban_ColumnNotStarted: 'Niet gestart',
    Kanban_ColumnInProgress: 'Bezig',
    Kanban_ColumnOnHold: 'In de wacht',
    Kanban_ColumnCompleted: 'Voltooid',
    Kanban_ColumnCancelled: 'Geannuleerd',
    Kanban_AddTaskButton: '+ Taak toevoegen',
    Kanban_EditTitle: 'Bewerken',
    Kanban_DeleteTitle: 'Verwijderen',
    Kanban_CardAriaLabel: '{taskTitle}, {status}. Druk op Enter om te bewerken, pijl links of rechts om de status te wijzigen.',
    Kanban_EditTaskAriaLabel: 'Taak {taskTitle} bewerken',
    Kanban_DeleteTaskAriaLabel: 'Taak {taskTitle} verwijderen',

    // ── Dashboard view ──
    Dashboard_TotalTasks: 'Totaal aantal taken',
    Dashboard_Completed: 'Voltooid',
    Dashboard_InProgress: 'Bezig',
    Dashboard_OnHold: 'In de wacht',
    Dashboard_NotStarted: 'Niet gestart',
    Dashboard_Cancelled: 'Geannuleerd',
    Dashboard_OverallProgress: 'Totale voortgang',
    Dashboard_ProjectManagerLabel: 'Projectmanager: {name}',
    Dashboard_PhaseProgressHeader: 'Voortgang per fase',
    Dashboard_StatusBreakdownHeader: 'Statusverdeling',
    Dashboard_PriorityBreakdownHeader: 'Prioriteitsverdeling',
    Dashboard_PriorityCritical: 'Kritiek',
    Dashboard_PriorityHigh: 'Hoog',
    Dashboard_PriorityMedium: 'Gemiddeld',
    Dashboard_PriorityLow: 'Laag',
    Dashboard_OverdueHeader: 'Te laat  ({count})',
    Dashboard_DueNext14DaysHeader: 'Vervalt binnen 14 dagen  ({count})',
    Dashboard_CompletedThisWeekHeader: 'Deze week voltooid',
    Dashboard_UpdatedThisWeekHeader: 'Deze week bijgewerkt',
    Dashboard_Today: 'Vandaag',
    Dashboard_Tomorrow: 'Morgen',
    Dashboard_DaysLeft: '{days}d',
    Dashboard_EmptyTitle: 'Nog geen taken',
    Dashboard_EmptySubtitle: 'Voeg taken toe om het projectdashboard te zien.',
    Dashboard_AddTaskButton: '+ Taak toevoegen',

    // ── Portfolio view ──
    Portfolio_ProjectCount: '{count} project{plural}',
    Portfolio_OnTrackSummary: '{count} op schema',
    Portfolio_AtRiskSummary: '{count} risicovol',
    Portfolio_OverdueSummary: '{count} te laat',
    Portfolio_DoneSummary: '{count} klaar',
    Portfolio_SortLabel: 'Sorteren:',
    Portfolio_SortAZ: 'A-Z',
    Portfolio_SortHealth: 'Gezondheidsstatus',
    Portfolio_SortStatus: 'Status',
    Portfolio_SortCompletion: 'Voltooiing',
    Portfolio_RefreshTitle: 'Vernieuwen',
    Portfolio_RefreshButton: 'Vernieuwen',
    Portfolio_LoadingStats: 'Statistieken laden…',
    Portfolio_EmptyTitle: 'Nog geen projecten',
    Portfolio_CreateFirstProject: '+ Eerste project maken',
    Portfolio_StatsUnavailable: 'Statistieken niet beschikbaar',
    Portfolio_StatsUnavailableDetail: 'Kon de statistieken voor dit project niet laden.',
    Portfolio_OverallProgressLabel: 'Totale voortgang',
    Portfolio_TaskCountDone: 'Klaar',
    Portfolio_TaskCountActive: 'Actief',
    Portfolio_TaskCountAtRisk: 'Risicovol',
    Portfolio_TaskCountOverdue: 'Te laat',
    Portfolio_ViewGanttLink: 'Gantt weergeven →',
    Portfolio_TodayTooltip: 'Vandaag',

    // ── Task panel ──
    TaskPanel_EditHeader: 'Bewerken: {taskTitle}',
    TaskPanel_NewTaskHeader: 'Nieuwe taak',
    TaskPanel_TabBasic: 'Basis',
    TaskPanel_TabDetails: 'Details',
    TaskPanel_TabLinks: 'Koppelingen',
    TaskPanel_ProjectLabelPrefix: 'Project: ',
    TaskPanel_TaskNameLabel: 'Taaknaam',
    TaskPanel_TaskNamePlaceholder: 'Voer de taaknaam in',
    TaskPanel_TaskNameRequired: 'Taaknaam is verplicht',
    TaskPanel_DescriptionLabel: 'Beschrijving',
    TaskPanel_DescriptionPlaceholder: 'Voer een beschrijving in',
    TaskPanel_StartDateLabel: 'Startdatum',
    TaskPanel_DueDateLabel: 'Vervaldatum',
    TaskPanel_DueDateError: 'De vervaldatum moet op of na de startdatum liggen',
    TaskPanel_StatusLabel: 'Status',
    TaskPanel_PriorityLabel: 'Prioriteit',
    TaskPanel_PercentCompleteLabel: '% Voltooid: {percent}%',
    TaskPanel_AssignedToLabel: 'Toegewezen aan',
    TaskPanel_AssignedToPlaceholder: 'Personen zoeken…',
    TaskPanel_PhaseLabel: 'Fase',
    TaskPanel_PhasePlaceholder: 'Voer de fasenaam in',
    TaskPanel_PhaseHint: 'Groepeert taken in de Gantt- en lijstweergave.',
    TaskPanel_MilestoneLabel: 'Mijlpaal',
    TaskPanel_MilestoneOnText: 'Ja',
    TaskPanel_MilestoneOffText: 'Nee',
    TaskPanel_CustomBarColorLabel: 'Aangepaste balkkleur',
    TaskPanel_CustomBarColorOptionalSuffix: ' (optioneel)',
    TaskPanel_AutoColorHint: 'Automatische kleur op basis van instellingen voor status/prioriteit/fase.',
    TaskPanel_NotesLabel: 'Notities',
    TaskPanel_NotesPlaceholder: 'Voer notities in',
    TaskPanel_ParentTaskLabel: 'Bovenliggende taak',
    TaskPanel_ParentTaskNone: '(geen)',
    TaskPanel_ParentTaskHasChildrenHint: 'Deze taak heeft subtaken en kan daarom geen eigen bovenliggende taak hebben.',
    TaskPanel_ParentTaskHint: 'Nest deze taak onder een andere als subtaak.',
    TaskPanel_DependsOnLabel: 'Afhankelijk van',
    TaskPanel_RemoveDependencyTitle: 'Afhankelijkheid van "{taskTitle}" verwijderen',
    TaskPanel_AddDependencyPlaceholder: 'Een afhankelijkheid toevoegen…',
    TaskPanel_SelectATaskOption: 'Selecteer een taak…',
    TaskPanel_DependsOnHint: 'De taak kan pas starten als deze zijn voltooid.',
    TaskPanel_SavingLabel: 'Opslaan…',
    TaskPanel_CreatingLabel: 'Maken…',
    TaskPanel_SaveChangesButton: 'Wijzigingen opslaan',
    TaskPanel_CreateTaskButton: 'Taak maken',
    TaskPanel_CancelButton: 'Annuleren',
    TaskPanel_DismissAriaLabel: 'Sluiten',
    TaskPanel_DiscardUnsavedChangesConfirm: 'Niet-opgeslagen wijzigingen negeren?',
    TaskPanel_SaveFallbackError: 'Kon de taak niet opslaan.',

    // ── Project panel ──
    ProjectPanel_EditHeader: 'Project bewerken',
    ProjectPanel_NewHeader: 'Nieuw project',
    ProjectPanel_ProjectNameLabel: 'Projectnaam',
    ProjectPanel_ProjectNamePlaceholder: 'Voer de projectnaam in',
    ProjectPanel_ProjectNameRequired: 'Projectnaam is verplicht',
    ProjectPanel_DescriptionLabel: 'Beschrijving',
    ProjectPanel_DescriptionPlaceholder: 'Voer een beschrijving in',
    ProjectPanel_ProjectColorLabel: 'Projectkleur',
    ProjectPanel_StatusLabel: 'Status',
    ProjectPanel_StartDateLabel: 'Startdatum',
    ProjectPanel_DueDateLabel: 'Vervaldatum',
    ProjectPanel_DueDateError: 'De vervaldatum moet op of na de startdatum liggen',
    ProjectPanel_WhatHappensNextTitle: 'Wat gebeurt er daarna?',
    ProjectPanel_WhatHappensNextBody: 'Zodra het project is aangemaakt, kunt u taken toevoegen, fases instellen en de voortgang volgen.',
    ProjectPanel_SavingLabel: 'Opslaan…',
    ProjectPanel_CreatingLabel: 'Maken…',
    ProjectPanel_SaveChangesButton: 'Wijzigingen opslaan',
    ProjectPanel_CreateProjectButton: 'Project maken',
    ProjectPanel_CancelButton: 'Annuleren',
    ProjectPanel_DismissAriaLabel: 'Sluiten',
    ProjectPanel_DiscardUnsavedChangesConfirm: 'Niet-opgeslagen wijzigingen negeren?',
    ProjectPanel_SaveFallbackError: 'Kon het project niet opslaan.',

    // ── Import panel ──
    ImportPanel_SourceExcelTitle: 'Excel-/CSV-bestand',
    ImportPanel_SourceExcelSubtitle: 'Taken importeren uit een spreadsheet',
    ImportPanel_SourcePlannerTitle: 'Microsoft Planner',
    ImportPanel_SourcePlannerSubtitle: 'Taken importeren uit een Planner-plan',
    ImportPanel_ClickToBrowse: 'Klik om te bladeren',
    ImportPanel_DragDropSuffix: ' of slepen en neerzetten',
    ImportPanel_SupportedExtensions: 'Ondersteunt .xlsx, .xls, .csv',
    ImportPanel_RowsColsSummary: '{rows} rijen, {cols} kolommen gedetecteerd',
    ImportPanel_LoadingPlannerPlans: 'Planner-plannen laden…',
    ImportPanel_PlannerLoadError: 'Kon Planner-plannen niet laden.',
    ImportPanel_PlannerPermissionsHintPrefix: 'Zorg ervoor dat u toegang hebt tot Planner en dat ',
    ImportPanel_PlannerPermissionsHintEmphasis: 'Taken door Planner en To Do',
    ImportPanel_PlannerPermissionsHintSuffix: ' beschikbaar is voor deze site.',
    ImportPanel_NoPlannerPlansFoundTitle: 'Geen Planner-plannen gevonden',
    ImportPanel_NoPlannerPlansFoundBody: 'Mogelijk hebt u geen toegang tot Planner-plannen, of bestaan er geen voor dit account.',
    ImportPanel_TaskCountFoundIn: '{count} taken gevonden in "{planName}"',
    ImportPanel_ProjectDetailsIntroPrefix: 'Importeren naar ',
    ImportPanel_ProjectDetailsIntroSuffix: '. Controleer hieronder de projectgegevens.',
    ImportPanel_ProjectNameLabel: 'Projectnaam',
    ImportPanel_DescriptionLabel: 'Beschrijving',
    ImportPanel_StatusLabel: 'Status',
    ImportPanel_ColorLabel: 'Kleur',
    ImportPanel_MapIntro: 'Koppel de kolommen uit uw bestand aan taakvelden.',
    ImportPanel_CreatingProjectStatus: 'Project maken…',
    ImportPanel_ImportingTasksStatus: 'Taken importeren…',
    ImportPanel_ProgressLabel: '{done} van {total}',
    ImportPanel_CouldNotCreateProject: 'Kon het project niet maken.',
    ImportPanel_ImportCompletedWithErrors: 'Import voltooid met {count} fout(en).',
    ImportPanel_ProjectCreatedSuccess: 'Project succesvol aangemaakt!',
    ImportPanel_ImportSuccessful: 'Import geslaagd!',
    ImportPanel_TasksAddedTo: '{count} taken toegevoegd aan "{projectName}"',
    ImportPanel_FailedRowsLabel: 'Mislukte rijen:',
    ImportPanel_CloseButton: 'Sluiten',
    ImportPanel_OpenProjectButton: 'Project openen',
    ImportPanel_ViewImportedTasksButton: 'Geïmporteerde taken bekijken',
    ImportPanel_NextMapColumnsButton: 'Volgende: kolommen koppelen',
    ImportPanel_ImportNTasksButton: '{count} taken importeren',
    ImportPanel_BackButton: 'Terug',
    ImportPanel_CancelButton: 'Annuleren',
    ImportPanel_NextButton: 'Volgende',
    ImportPanel_StepSource: 'Bron',
    ImportPanel_StepProject: 'Project',
    ImportPanel_StepMap: 'Koppelen',
    ImportPanel_StepImport: 'Importeren',
    ImportPanel_StepDone: 'Gereed',
    ImportPanel_ImportAsNewProjectHeader: 'Bestand importeren als nieuw project',
    ImportPanel_ImportIntoProjectHeader: 'Taken importeren in {projectName}',
    ImportPanel_CouldNotParseFile: 'Kon het bestand niet verwerken.',
    ImportPanel_CouldNotLoadPlannerTasks: 'Kon geen taken laden uit dit plan.',
    ImportPanel_CouldNotCreateProjectDetail: 'Kon het project niet maken: {detail}',
    ImportPanel_CouldNotLinkDependencies: 'Kon de afhankelijkheden niet koppelen: {detail}',
    ImportPanel_UnknownError: 'onbekende fout',

    // ── Column mapper (import) ──
    ColumnMapper_TaskNameRequiredBanner: 'Taaknaam moet worden gekoppeld om door te gaan.',
    ColumnMapper_SkippedColumnsBanner: '{count} kolom(men) worden overgeslagen.',
    ColumnMapper_SourceColumnHeader: 'Bronkolom',
    ColumnMapper_TargetFieldHeader: 'Doelveld',
    ColumnMapper_StatusHeader: 'Status',
    ColumnMapper_SkippedBadge: 'Overgeslagen',
    ColumnMapper_AutoMappedBadge: 'Automatisch gekoppeld',
    ColumnMapper_SetBadge: 'Ingesteld',
    ColumnMapper_PreviewTitle: 'Voorbeeld: {columnName}',
    ColumnMapper_EmptyCellDash: '—',

    // ── Import field display names / ImportService ──
    ImportField_TaskName: 'Taaknaam',
    ImportField_StartDate: 'Startdatum',
    ImportField_DueDate: 'Vervaldatum',
    ImportField_Status: 'Status',
    ImportField_Priority: 'Prioriteit',
    ImportField_AssignedTo: 'Toegewezen aan',
    ImportField_AssignedToEmail: 'E-mail van toegewezene',
    ImportField_PercentComplete: '% Voltooid',
    ImportField_Phase: 'Fase',
    ImportField_Description: 'Beschrijving',
    ImportField_Notes: 'Notities',
    ImportField_IsMilestone: 'Is mijlpaal',
    ImportField_Dependencies: 'Afhankelijkheden',
    ImportField_SkipColumn: '(Deze kolom overslaan)',
    ImportService_EmptyFileError: 'Het bestand lijkt leeg te zijn of bevat geen gegevensrijen.',
    ImportService_ReadErrorDetail: 'Kon het bestand niet lezen: {detail}.',
    ImportService_FileReadError: 'Fout bij het lezen van het bestand.',
    ImportService_RowError: 'Rij {rowNum} ("{title}"): {error}',
    ImportService_AmbiguousDependency: 'Afhankelijkheid "{name}" komt overeen met meer dan één taaktitel — overgeslagen.',
    ImportService_LinkDependencyError: 'Kon de afhankelijkheden voor taak {taskId} niet koppelen: {error}',

    // ── Health labels (shared: healthUtils.ts and ExportService.ts both use this set; also replaces the duplicated Export_PortfolioHealthLabel* keys) ──
    Health_Done: 'Klaar',
    Health_OnTrack: 'Op schema',
    Health_AtRisk: 'Risicovol',
    Health_Overdue: 'Te laat',

    // ── Status / Priority display labels (DISPLAY-ONLY — stored SharePoint Choice values remain unchanged/English) ──
    Status_NotStarted: 'Niet gestart',
    Status_InProgress: 'Bezig',
    Status_Completed: 'Voltooid',
    Status_OnHold: 'In de wacht',
    Status_Cancelled: 'Geannuleerd',
    Priority_Critical: 'Kritiek',
    Priority_High: 'Hoog',
    Priority_Medium: 'Gemiddeld',
    Priority_Low: 'Laag',
    ProjectStatus_Planning: 'Planning',
    ProjectStatus_Active: 'Actief',
    ProjectStatus_OnHold: 'In de wacht',
    ProjectStatus_Completed: 'Voltooid',
    ProjectStatus_Cancelled: 'Geannuleerd',

    // ── Shell (SmartGantt.tsx) ──
    SmartGantt_LoadingProjects: 'Projecten laden…',
    SmartGantt_UnableToLoad: 'Kan niet laden',
    SmartGantt_RetryButton: 'Opnieuw proberen',
    SmartGantt_NoProjectsYet: 'Nog geen projecten',
    SmartGantt_NoProjectsSubtitle: 'Maak uw eerste project aan om te beginnen.',
    SmartGantt_CreateFirstProjectButton: '+ Eerste project maken',
    SmartGantt_ImportFromExcelButton: '📥 Importeren vanuit Excel',
    SmartGantt_LoadingTasks: 'Taken laden…',
    SmartGantt_DismissAriaLabel: 'Sluiten',
    SmartGantt_DeleteTaskDialogTitle: 'Taak verwijderen',
    SmartGantt_DeleteTaskDialogSubtext: 'Weet u zeker dat u "{taskTitle}" wilt verwijderen? Dit kan niet ongedaan worden gemaakt.',
    SmartGantt_DeleteButton: 'Verwijderen',
    SmartGantt_CancelButton: 'Annuleren',
    SmartGantt_ArchiveProjectDialogTitle: 'Project archiveren',
    SmartGantt_ArchiveProjectDialogSubtext: '"{projectTitle}" archiveren? U kunt het later weer terugzetten.',
    SmartGantt_ArchiveButton: 'Archiveren',
    SmartGantt_SendToRecycleBinDialogTitle: 'Naar prullenbak verplaatsen',
    SmartGantt_SendToRecycleBinDialogSubtext: '"{projectTitle}" naar de prullenbak van de site verplaatsen?',
    SmartGantt_SendToRecycleBinButton: 'Naar prullenbak verplaatsen',
    SmartGantt_FailedLoadProjects: 'Kon projecten niet laden. Controleer de sitemachtigingen.',
    SmartGantt_FailedLoadTasks: 'Kon de taken voor dit project niet laden.',
    SmartGantt_FailedLoadPortfolioStats: 'Kon de portfoliostatistieken niet laden.',
    SmartGantt_CouldNotSaveProject: 'Kon het project niet opslaan: {message}',
    SmartGantt_CouldNotDeleteProject: 'Kon het project niet verwijderen: {message}',
    SmartGantt_CouldNotArchiveProject: 'Kon het project niet archiveren: {message}',
    SmartGantt_CouldNotUnarchiveProject: 'Kon het project niet terugzetten uit het archief: {message}',
    SmartGantt_CouldNotSaveTask: 'Kon de taak niet opslaan: {message}',
    SmartGantt_CouldNotDeleteTask: 'Kon de taak niet verwijderen: {message}',
    SmartGantt_ImageExportFailed: 'Afbeeldingsexport mislukt: {message}',
    SmartGantt_PowerPointExportFailed: 'PowerPoint-export mislukt: {message}',
    SmartGantt_PortfolioExportFailed: 'Portfolio-export mislukt: {message}',
    SmartGantt_CouldNotUpdateTask: 'Kon de taak niet bijwerken: {message}',

    // ── Common ──
    ColorSwatch_AutoColorAriaLabel: 'Automatische kleur',
    ColorSwatch_CustomColorAriaLabel: 'Aangepaste kleur',
    ColorSwatch_PickCustomColorTitle: 'Kies een aangepaste kleur',

    // ── Export (Excel / PowerPoint) ──
    Export_ColTaskName: 'Taaknaam',
    Export_ColPhase: 'Fase',
    Export_ColStartDate: 'Startdatum',
    Export_ColDueDate: 'Vervaldatum',
    Export_ColStatus: 'Status',
    Export_ColPriority: 'Prioriteit',
    Export_ColAssignedTo: 'Toegewezen aan',
    Export_ColAssignedToEmail: 'E-mail van toegewezene',
    Export_ColPercentComplete: '% Voltooid',
    Export_ColIsMilestone: 'Is mijlpaal',
    Export_ColDescription: 'Beschrijving',
    Export_ColNotes: 'Notities',
    Export_Yes: 'Ja',
    Export_No: 'Nee',
    Export_SheetNameTasks: 'Taken',
    Export_ExcelFileSuffix: ' - Taken.xlsx',
    Export_TaskNameColumnLabel: 'TAAKNAAM',
    Export_ExportedDateLabel: 'Geëxporteerd op {date}',
    Export_ProjectReportLabel: 'PROJECTRAPPORT',
    Export_StatusLine: 'Status: {status}',
    Export_DateRangeSeparator: ' tot ',
    Export_ProjectManagerLine: 'Projectmanager: {name}',
    Export_GeneratedDateLine: 'Gegenereerd op {date}',
    Export_ProjectSummaryTitle: 'Projectoverzicht',
    Export_StatTotalTasks: 'Totaal aantal taken',
    Export_StatCompleted: 'Voltooid',
    Export_StatInProgress: 'Bezig',
    Export_StatOnHold: 'In de wacht',
    Export_StatNotStarted: 'Niet gestart',
    Export_OverallProgressLine: 'Totale voortgang',
    Export_OverallProgressPercent: '{percent}%',
    Export_StatusBreakdownTitle: 'Statusverdeling',
    Export_StatusBreakdownRow: '{status}: {count} ({percent}%)',
    Export_GanttTimelineTitle: 'Gantt-tijdlijn',
    Export_SummaryRecentActivityTitle: 'Recente activiteit',
    Export_ProjectOverviewLabel: 'Projectoverzicht',
    Export_DetailStatusLabel: 'Status',
    Export_DetailStartDateLabel: 'Startdatum',
    Export_DetailDueDateLabel: 'Vervaldatum',
    Export_DetailProjectManagerLabel: 'Projectmanager',
    Export_Past7DaysLabel: 'Afgelopen 7 dagen',
    Export_NoActivityMessage: 'Geen recente activiteit.',
    Export_CompletedThisWeekHeader: 'Deze week voltooid ({count})',
    Export_NewBadge: 'NIEUW  ',
    Export_CompletedPercentLine: '{percent}% voltooid',
    Export_MoreItemsSuffix: '+ {count} meer',
    Export_InProgressUpdatedHeader: 'Bezig / Bijgewerkt',
    Export_StatusPercentLine: '{status} — {percent}%',
    Export_PortfolioReportLabel: 'PORTFOLIORAPPORT',
    Export_PortfolioOverviewTitle: 'Portfolio-overzicht',
    Export_ProjectsCountLine: '{count} projecten',
    Export_HealthSummaryOnTrack: '{count} op schema',
    Export_HealthSummaryAtRisk: '{count} risicovol',
    Export_HealthSummaryOverdue: '{count} te laat',
    Export_ProjectsSummaryHeader: 'Projectenoverzicht',
    Export_TableProject: 'Project',
    Export_TableStatus: 'Status',
    Export_TableHealth: 'Gezondheidsstatus',
    Export_TableTotal: 'Totaal',
    Export_TableDone: 'Klaar',
    Export_TableActive: 'Actief',
    Export_TableAtRisk: 'Risicovol',
    Export_TableOverdue: 'Te laat',
    Export_TablePctDone: '% Klaar',
    Export_TableDueDate: 'Vervaldatum',
    Export_PortfolioSummaryFileName: 'Portfolio-overzicht.xlsx',
    Export_PortfolioReportFileName: 'Portfoliorapport.pptx',
    Export_ProjectReportFileName: '{projectName} rapport.pptx',
    Export_UnavailableLabel: 'Niet beschikbaar',
    Export_SheetNamePortfolio: 'Portfolio',
    Export_ColStart: 'Start',
    Export_ColDue: 'Vervaldatum',
    Export_ImageGenerationFailed: 'Kon de afbeelding niet genereren – de grafiek is mogelijk te groot om als afbeelding te exporteren.',
    Export_DrawingContextFailed: 'Kon geen tekencontext maken voor de export.',
    Export_SvgRenderFailed: 'SVG-weergave mislukt',
  };
});
