define([], function () {
  return {
    // ── Property pane ──
    PropertyPane_HeaderDescription: 'Ustawienia Smart Gantt Chart',
    PropertyPane_GeneralGroupName: 'Ogólne',
    PropertyPane_TitleFieldLabel: 'Tytuł składnika Web Part',
    WebPart_DefaultTitle: 'Smart Gantt Chart',

    // ── Toolbar ──
    Toolbar_ViewDashboard: 'Pulpit',
    Toolbar_ViewList: 'Lista',
    Toolbar_ViewGantt: 'Gantt',
    Toolbar_ViewKanban: 'Kanban',
    Toolbar_ZoomDay: 'Dzień',
    Toolbar_ZoomWeek: 'Tydzień',
    Toolbar_ZoomMonth: 'Miesiąc',
    Toolbar_ZoomQuarter: 'Kwartał',
    Toolbar_SelectProjectAriaLabel: 'Wybierz projekt',
    Toolbar_PortfolioLabel: 'Portfel',
    Toolbar_SelectAProject: 'Wybierz projekt',
    Toolbar_AllProjectsSubtext: 'Wszystkie projekty',
    Toolbar_NoProjectsYet: 'Brak projektów',
    Toolbar_ArchivedBadge: 'Zarchiwizowany',
    Toolbar_ShowArchivedProjects: 'Pokaż zarchiwizowane projekty',
    Toolbar_NewProject: '+ Nowy projekt',
    Toolbar_ImportFileAsNewProject: '📥 Importuj plik jako nowy projekt…',
    Toolbar_AddTask: '+ Dodaj zadanie',
    Toolbar_EditProject: 'Edytuj projekt',
    Toolbar_OptionsButton: '⚙ Opcje',
    Toolbar_MoreOptionsTitle: 'Więcej opcji',
    Toolbar_ExportToExcel: '📊 Eksportuj do programu Excel',
    Toolbar_ExportToPowerPoint: '📑 Eksportuj do programu PowerPoint',
    Toolbar_ScrollToTodayTitle: 'Przejdź do dzisiaj',
    Toolbar_TodayButton: '◉ Dzisiaj',
    Toolbar_ImportTasks: '📥 Importuj zadania…',
    Toolbar_ExportAsImage: '🖼 Eksportuj jako obraz (PNG)',
    Toolbar_UnarchiveProject: '📂 Przywróć projekt z archiwum',
    Toolbar_ArchiveProject: '🗄️ Archiwizuj projekt',
    Toolbar_SendToRecycleBin: '🗑️ Przenieś do kosza',

    // ── Filter bar ──
    FilterBar_ClearOption: 'Wyczyść',
    FilterBar_DueAny: 'Dowolny termin',
    FilterBar_DueOverdue: 'Po terminie',
    FilterBar_DueToday: 'Termin dzisiaj',
    FilterBar_DueWeek: 'Termin w ciągu 7 dni',
    FilterBar_SearchPlaceholder: 'Szukaj zadań…',
    FilterBar_SearchAriaLabel: 'Szukaj zadań',
    FilterBar_StatusChipLabel: 'Status',
    FilterBar_PriorityChipLabel: 'Priorytet',
    FilterBar_AssigneeChipLabel: 'Przypisano do',
    FilterBar_PhaseChipLabel: 'Faza',
    FilterBar_DueDateAriaLabel: 'Filtruj według terminu',
    FilterBar_MatchCount: '{matchCount} z {totalCount}',
    FilterBar_ClearFilters: '✕ Wyczyść filtry',
    FilterBar_ChipLabelWithCount: '{label} ({count}) ▾',
    FilterBar_ChipLabelNoCount: '{label} ▾',

    // ── Gantt view ──
    Gantt_TaskColumnHeader: 'Zadanie',
    Gantt_DurationColumnHeader: 'Czas trwania',
    Gantt_AddTaskButton: '+ Dodaj zadanie',
    Gantt_EmptyTitle: 'Brak zadań',
    Gantt_EmptySubtitle: 'Dodaj zadania, aby zobaczyć je na wykresie Gantta.',
    Gantt_AddFirstTask: '+ Dodaj pierwsze zadanie',
    Gantt_ImportTasksButton: '📥 Importuj zadania',
    Gantt_EditTitle: 'Edytuj',
    Gantt_DeleteTitle: 'Usuń',
    Gantt_EditTaskAriaLabel: 'Edytuj zadanie {taskTitle}',
    Gantt_DeleteTaskAriaLabel: 'Usuń zadanie {taskTitle}',
    Gantt_ExpandPhaseAriaLabel: '{action} fazę {phase}',
    Gantt_ExpandAction: 'Rozwiń',
    Gantt_CollapseAction: 'Zwiń',
    Gantt_DependencyViolationTooltip: 'Rozpoczęto, zanim wszystkie zależności zostały zakończone',
    Gantt_MilestoneAriaLabel: '{taskTitle}, kamień milowy, {date}',
    Gantt_BarAriaLabel: '{taskTitle}, od {startDate} do {dueDate}, ukończono {percent}%',
    Gantt_PercentCompleteTooltip: 'Ukończono {value}%',

    // ── Gantt options/settings panel ──
    GanttSettings_PanelHeader: '⚙ Opcje',
    GanttSettings_ColorCodingSection: 'Kodowanie kolorami',
    GanttSettings_ByStatus: 'Według statusu',
    GanttSettings_ByPriority: 'Według priorytetu',
    GanttSettings_ByPhase: 'Według fazy',
    GanttSettings_ByHealth: 'Według stanu realizacji',
    GanttSettings_HeaderColorSection: 'Kolor nagłówka',
    GanttSettings_ThemeDark: 'Ciemny',
    GanttSettings_ThemeNavy: 'Granatowy',
    GanttSettings_ThemeTeal: 'Morski',
    GanttSettings_ThemePurple: 'Fioletowy',
    GanttSettings_ThemeLight: 'Jasny',
    GanttSettings_HeaderLabelsSection: 'Etykiety nagłówka',
    GanttSettings_WeekLabelDates: 'Daty',
    GanttSettings_WeekLabelDatesDesc: '3 cze, 10 cze…',
    GanttSettings_WeekLabelProject: 'Tygodnie projektu',
    GanttSettings_WeekLabelProjectDesc: 'T1, T2…',
    GanttSettings_WeekLabelIso: 'Tygodnie kalendarzowe',
    GanttSettings_WeekLabelIsoDesc: 'T23, T24…',
    GanttSettings_ProjectWeeksHint: 'Tydzień 1 zaczyna się od poniedziałku najwcześniejszego zadania — świetne rozwiązanie do prezentacji.',
    GanttSettings_BarStyleSection: 'Styl pasków',
    GanttSettings_BarStyleGradient: 'Gradient',
    GanttSettings_BarStyleFlat: 'Płaski',
    GanttSettings_RowHeightSection: 'Wysokość wiersza',
    GanttSettings_HeightCompact: 'Kompaktowa',
    GanttSettings_HeightNormal: 'Normalna',
    GanttSettings_HeightSpacious: 'Przestronna',
    GanttSettings_ShowHideSection: 'Pokaż / Ukryj',
    GanttSettings_WeekendShading: 'Wyróżnianie weekendów',
    GanttSettings_DependencyArrows: 'Strzałki zależności',
    GanttSettings_CriticalPathAlwaysVisible: 'Ścieżka krytyczna zawsze widoczna',
    GanttSettings_AllOthersOnHoverOnly: 'Pozostałe tylko po najechaniu kursorem',
    GanttSettings_CriticalPathHighlight: 'Wyróżnianie ścieżki krytycznej',
    GanttSettings_ProgressPercentOnBars: 'Postęp % na paskach',
    GanttSettings_AssigneeNameOnBars: 'Nazwa osoby przypisanej na paskach',
    GanttSettings_HealthStatusBadges: 'Odznaki stanu realizacji',

    // ── List view ──
    ListView_ColTaskName: 'Nazwa zadania',
    ListView_ColStatus: 'Status',
    ListView_ColHealth: 'Stan realizacji',
    ListView_ColPriority: 'Priorytet',
    ListView_ColStart: 'Rozpoczęcie',
    ListView_ColDue: 'Termin',
    ListView_ColAssignedTo: 'Przypisano do',
    ListView_ColProgress: 'Postęp',
    ListView_ColPhase: 'Faza',
    ListView_ColPredecessors: 'Poprzedniki',
    ListView_EmptyTitle: 'Brak zadań',
    ListView_AddFirstTask: '+ Dodaj pierwsze zadanie',
    ListView_AddTaskRow: '+ Dodaj zadanie',
    ListView_Unassigned: 'Nieprzypisane',
    ListView_DependencyViolationTooltip: 'Rozpoczęto, zanim wszystkie zależności zostały zakończone',
    ListView_StatusAriaLabel: 'Status zadania {taskTitle}',
    ListView_PriorityAriaLabel: 'Priorytet zadania {taskTitle}',
    ListView_EditTaskAriaLabel: 'Edytuj zadanie {taskTitle}',
    ListView_DeleteTaskAriaLabel: 'Usuń zadanie {taskTitle}',
    ListView_EditTitle: 'Edytuj',
    ListView_DeleteTitle: 'Usuń',

    // ── Kanban view ──
    Kanban_ColumnNotStarted: 'Nierozpoczęte',
    Kanban_ColumnInProgress: 'W toku',
    Kanban_ColumnOnHold: 'Wstrzymane',
    Kanban_ColumnCompleted: 'Ukończone',
    Kanban_ColumnCancelled: 'Anulowane',
    Kanban_AddTaskButton: '+ Dodaj zadanie',
    Kanban_EditTitle: 'Edytuj',
    Kanban_DeleteTitle: 'Usuń',
    Kanban_CardAriaLabel: '{taskTitle}, {status}. Naciśnij Enter, aby edytować, lub strzałkę w lewo/prawo, aby zmienić status.',
    Kanban_EditTaskAriaLabel: 'Edytuj zadanie {taskTitle}',
    Kanban_DeleteTaskAriaLabel: 'Usuń zadanie {taskTitle}',

    // ── Dashboard view ──
    Dashboard_TotalTasks: 'Wszystkie zadania',
    Dashboard_Completed: 'Ukończone',
    Dashboard_InProgress: 'W toku',
    Dashboard_OnHold: 'Wstrzymane',
    Dashboard_NotStarted: 'Nierozpoczęte',
    Dashboard_Cancelled: 'Anulowane',
    Dashboard_OverallProgress: 'Postęp ogólny',
    Dashboard_ProjectManagerLabel: 'Kierownik projektu: {name}',
    Dashboard_PhaseProgressHeader: 'Postęp według fazy',
    Dashboard_StatusBreakdownHeader: 'Podział według statusu',
    Dashboard_PriorityBreakdownHeader: 'Podział według priorytetu',
    Dashboard_PriorityCritical: 'Krytyczny',
    Dashboard_PriorityHigh: 'Wysoki',
    Dashboard_PriorityMedium: 'Średni',
    Dashboard_PriorityLow: 'Niski',
    Dashboard_OverdueHeader: 'Po terminie  ({count})',
    Dashboard_DueNext14DaysHeader: 'Termin w ciągu 14 dni  ({count})',
    Dashboard_CompletedThisWeekHeader: 'Ukończone w tym tygodniu',
    Dashboard_UpdatedThisWeekHeader: 'Zaktualizowane w tym tygodniu',
    Dashboard_Today: 'Dzisiaj',
    Dashboard_Tomorrow: 'Jutro',
    Dashboard_DaysLeft: '{days} dni',
    Dashboard_EmptyTitle: 'Brak zadań',
    Dashboard_EmptySubtitle: 'Dodaj zadania, aby zobaczyć pulpit projektu.',
    Dashboard_AddTaskButton: '+ Dodaj zadanie',

    // ── Portfolio view ──
    Portfolio_ProjectCount: '{count} projekt{plural}',
    Portfolio_OnTrackSummary: '{count} zgodnie z planem',
    Portfolio_AtRiskSummary: '{count} zagrożonych',
    Portfolio_OverdueSummary: '{count} po terminie',
    Portfolio_DoneSummary: '{count} ukończonych',
    Portfolio_SortLabel: 'Sortuj:',
    Portfolio_SortAZ: 'A-Z',
    Portfolio_SortHealth: 'Stan realizacji',
    Portfolio_SortStatus: 'Status',
    Portfolio_SortCompletion: 'Ukończenie',
    Portfolio_RefreshTitle: 'Odśwież',
    Portfolio_RefreshButton: 'Odśwież',
    Portfolio_LoadingStats: 'Ładowanie statystyk…',
    Portfolio_EmptyTitle: 'Brak projektów',
    Portfolio_CreateFirstProject: '+ Utwórz pierwszy projekt',
    Portfolio_StatsUnavailable: 'Statystyki niedostępne',
    Portfolio_StatsUnavailableDetail: 'Nie można załadować statystyk dla tego projektu.',
    Portfolio_OverallProgressLabel: 'Postęp ogólny',
    Portfolio_TaskCountDone: 'Ukończone',
    Portfolio_TaskCountActive: 'Aktywne',
    Portfolio_TaskCountAtRisk: 'Zagrożone',
    Portfolio_TaskCountOverdue: 'Po terminie',
    Portfolio_ViewGanttLink: 'Wyświetl wykres Gantta →',
    Portfolio_TodayTooltip: 'Dzisiaj',

    // ── Task panel ──
    TaskPanel_EditHeader: 'Edytuj: {taskTitle}',
    TaskPanel_NewTaskHeader: 'Nowe zadanie',
    TaskPanel_TabBasic: 'Podstawowe',
    TaskPanel_TabDetails: 'Szczegóły',
    TaskPanel_TabLinks: 'Łącza',
    TaskPanel_ProjectLabelPrefix: 'Projekt: ',
    TaskPanel_TaskNameLabel: 'Nazwa zadania',
    TaskPanel_TaskNamePlaceholder: 'Wprowadź nazwę zadania',
    TaskPanel_TaskNameRequired: 'Nazwa zadania jest wymagana',
    TaskPanel_DescriptionLabel: 'Opis',
    TaskPanel_DescriptionPlaceholder: 'Wprowadź opis',
    TaskPanel_StartDateLabel: 'Data rozpoczęcia',
    TaskPanel_DueDateLabel: 'Termin',
    TaskPanel_DueDateError: 'Termin musi przypadać w dniu rozpoczęcia lub po nim',
    TaskPanel_StatusLabel: 'Status',
    TaskPanel_PriorityLabel: 'Priorytet',
    TaskPanel_PercentCompleteLabel: '% ukończenia: {percent}%',
    TaskPanel_AssignedToLabel: 'Przypisano do',
    TaskPanel_AssignedToPlaceholder: 'Wyszukaj osoby…',
    TaskPanel_PhaseLabel: 'Faza',
    TaskPanel_PhasePlaceholder: 'Wprowadź nazwę fazy',
    TaskPanel_PhaseHint: 'Grupuje zadania w widokach Gantta i listy.',
    TaskPanel_MilestoneLabel: 'Kamień milowy',
    TaskPanel_MilestoneOnText: 'Tak',
    TaskPanel_MilestoneOffText: 'Nie',
    TaskPanel_CustomBarColorLabel: 'Niestandardowy kolor paska',
    TaskPanel_CustomBarColorOptionalSuffix: ' (opcjonalnie)',
    TaskPanel_AutoColorHint: 'Kolor automatyczny na podstawie ustawień statusu/priorytetu/fazy.',
    TaskPanel_NotesLabel: 'Notatki',
    TaskPanel_NotesPlaceholder: 'Wprowadź notatki',
    TaskPanel_ParentTaskLabel: 'Zadanie nadrzędne',
    TaskPanel_ParentTaskNone: '(brak)',
    TaskPanel_ParentTaskHasChildrenHint: 'To zadanie ma podzadania i nie może mieć własnego zadania nadrzędnego.',
    TaskPanel_ParentTaskHint: 'Zagnieźdź to zadanie pod innym jako podzadanie.',
    TaskPanel_DependsOnLabel: 'Zależy od',
    TaskPanel_RemoveDependencyTitle: 'Usuń zależność od „{taskTitle}”',
    TaskPanel_AddDependencyPlaceholder: 'Dodaj zależność…',
    TaskPanel_SelectATaskOption: 'Wybierz zadanie…',
    TaskPanel_DependsOnHint: 'Zadanie nie może się rozpocząć, dopóki te zadania nie zostaną ukończone.',
    TaskPanel_SavingLabel: 'Zapisywanie…',
    TaskPanel_CreatingLabel: 'Tworzenie…',
    TaskPanel_SaveChangesButton: 'Zapisz zmiany',
    TaskPanel_CreateTaskButton: 'Utwórz zadanie',
    TaskPanel_CancelButton: 'Anuluj',
    TaskPanel_DismissAriaLabel: 'Zamknij',
    TaskPanel_DiscardUnsavedChangesConfirm: 'Odrzucić niezapisane zmiany?',
    TaskPanel_SaveFallbackError: 'Nie można zapisać zadania.',

    // ── Project panel ──
    ProjectPanel_EditHeader: 'Edytuj projekt',
    ProjectPanel_NewHeader: 'Nowy projekt',
    ProjectPanel_ProjectNameLabel: 'Nazwa projektu',
    ProjectPanel_ProjectNamePlaceholder: 'Wprowadź nazwę projektu',
    ProjectPanel_ProjectNameRequired: 'Nazwa projektu jest wymagana',
    ProjectPanel_DescriptionLabel: 'Opis',
    ProjectPanel_DescriptionPlaceholder: 'Wprowadź opis',
    ProjectPanel_ProjectColorLabel: 'Kolor projektu',
    ProjectPanel_StatusLabel: 'Status',
    ProjectPanel_StartDateLabel: 'Data rozpoczęcia',
    ProjectPanel_DueDateLabel: 'Termin',
    ProjectPanel_DueDateError: 'Termin musi przypadać w dniu rozpoczęcia lub po nim',
    ProjectPanel_WhatHappensNextTitle: 'Co dalej?',
    ProjectPanel_WhatHappensNextBody: 'Po utworzeniu projektu będzie można dodawać zadania, konfigurować fazy i śledzić postęp.',
    ProjectPanel_SavingLabel: 'Zapisywanie…',
    ProjectPanel_CreatingLabel: 'Tworzenie…',
    ProjectPanel_SaveChangesButton: 'Zapisz zmiany',
    ProjectPanel_CreateProjectButton: 'Utwórz projekt',
    ProjectPanel_CancelButton: 'Anuluj',
    ProjectPanel_DismissAriaLabel: 'Zamknij',
    ProjectPanel_DiscardUnsavedChangesConfirm: 'Odrzucić niezapisane zmiany?',
    ProjectPanel_SaveFallbackError: 'Nie można zapisać projektu.',

    // ── Import panel ──
    ImportPanel_SourceExcelTitle: 'Plik Excel / CSV',
    ImportPanel_SourceExcelSubtitle: 'Importuj zadania z arkusza kalkulacyjnego',
    ImportPanel_SourcePlannerTitle: 'Microsoft Planner',
    ImportPanel_SourcePlannerSubtitle: 'Importuj zadania z planu w aplikacji Planner',
    ImportPanel_ClickToBrowse: 'Kliknij, aby przeglądać',
    ImportPanel_DragDropSuffix: ' lub przeciągnij i upuść',
    ImportPanel_SupportedExtensions: 'Obsługuje pliki .xlsx, .xls, .csv',
    ImportPanel_RowsColsSummary: 'Wykryto {rows} wierszy, {cols} kolumn',
    ImportPanel_LoadingPlannerPlans: 'Ładowanie planów aplikacji Planner…',
    ImportPanel_PlannerLoadError: 'Nie można załadować planów aplikacji Planner.',
    ImportPanel_PlannerPermissionsHintPrefix: 'Upewnij się, że masz dostęp do aplikacji Planner oraz że ',
    ImportPanel_PlannerPermissionsHintEmphasis: 'Zadania w aplikacjach Planner i To Do',
    ImportPanel_PlannerPermissionsHintSuffix: ' są dostępne w tej witrynie.',
    ImportPanel_NoPlannerPlansFoundTitle: 'Nie znaleziono planów aplikacji Planner',
    ImportPanel_NoPlannerPlansFoundBody: 'Może nie mieć dostępu do żadnych planów aplikacji Planner lub żaden nie istnieje dla tego konta.',
    ImportPanel_TaskCountFoundIn: 'Znaleziono {count} zadań w planie „{planName}”',
    ImportPanel_ProjectDetailsIntroPrefix: 'Importowanie do ',
    ImportPanel_ProjectDetailsIntroSuffix: '. Sprawdź poniższe szczegóły projektu.',
    ImportPanel_ProjectNameLabel: 'Nazwa projektu',
    ImportPanel_DescriptionLabel: 'Opis',
    ImportPanel_StatusLabel: 'Status',
    ImportPanel_ColorLabel: 'Kolor',
    ImportPanel_MapIntro: 'Zmapuj kolumny z pliku na pola zadania.',
    ImportPanel_CreatingProjectStatus: 'Tworzenie projektu…',
    ImportPanel_ImportingTasksStatus: 'Importowanie zadań…',
    ImportPanel_ProgressLabel: '{done} z {total}',
    ImportPanel_CouldNotCreateProject: 'Nie można utworzyć projektu.',
    ImportPanel_ImportCompletedWithErrors: 'Import zakończony z liczbą błędów: {count}.',
    ImportPanel_ProjectCreatedSuccess: 'Projekt został pomyślnie utworzony!',
    ImportPanel_ImportSuccessful: 'Import zakończony powodzeniem!',
    ImportPanel_TasksAddedTo: 'Dodano {count} zadań do „{projectName}”',
    ImportPanel_FailedRowsLabel: 'Wiersze zakończone niepowodzeniem:',
    ImportPanel_CloseButton: 'Zamknij',
    ImportPanel_OpenProjectButton: 'Otwórz projekt',
    ImportPanel_ViewImportedTasksButton: 'Wyświetl zaimportowane zadania',
    ImportPanel_NextMapColumnsButton: 'Dalej: zmapuj kolumny',
    ImportPanel_ImportNTasksButton: 'Importuj {count} zadań',
    ImportPanel_BackButton: 'Wstecz',
    ImportPanel_CancelButton: 'Anuluj',
    ImportPanel_NextButton: 'Dalej',
    ImportPanel_StepSource: 'Źródło',
    ImportPanel_StepProject: 'Projekt',
    ImportPanel_StepMap: 'Mapowanie',
    ImportPanel_StepImport: 'Import',
    ImportPanel_StepDone: 'Gotowe',
    ImportPanel_ImportAsNewProjectHeader: 'Importuj plik jako nowy projekt',
    ImportPanel_ImportIntoProjectHeader: 'Importuj zadania do projektu {projectName}',
    ImportPanel_CouldNotParseFile: 'Nie można przeanalizować pliku.',
    ImportPanel_CouldNotLoadPlannerTasks: 'Nie można załadować zadań z tego planu.',
    ImportPanel_CouldNotCreateProjectDetail: 'Nie można utworzyć projektu: {detail}',
    ImportPanel_CouldNotLinkDependencies: 'Nie można powiązać zależności: {detail}',
    ImportPanel_UnknownError: 'nieznany błąd',

    // ── Column mapper (import) ──
    ColumnMapper_TaskNameRequiredBanner: 'Aby kontynuować, należy zmapować nazwę zadania.',
    ColumnMapper_SkippedColumnsBanner: 'Liczba pominiętych kolumn: {count}.',
    ColumnMapper_SourceColumnHeader: 'Kolumna źródłowa',
    ColumnMapper_TargetFieldHeader: 'Pole docelowe',
    ColumnMapper_StatusHeader: 'Status',
    ColumnMapper_SkippedBadge: 'Pominięto',
    ColumnMapper_AutoMappedBadge: 'Zmapowano automatycznie',
    ColumnMapper_SetBadge: 'Ustawiono',
    ColumnMapper_PreviewTitle: 'Podgląd: {columnName}',
    ColumnMapper_EmptyCellDash: '—',

    // ── Import field display names / ImportService ──
    ImportField_TaskName: 'Nazwa zadania',
    ImportField_StartDate: 'Data rozpoczęcia',
    ImportField_DueDate: 'Termin',
    ImportField_Status: 'Status',
    ImportField_Priority: 'Priorytet',
    ImportField_AssignedTo: 'Przypisano do',
    ImportField_AssignedToEmail: 'E-mail osoby przypisanej',
    ImportField_PercentComplete: '% ukończenia',
    ImportField_Phase: 'Faza',
    ImportField_Description: 'Opis',
    ImportField_Notes: 'Notatki',
    ImportField_IsMilestone: 'Jest kamieniem milowym',
    ImportField_Dependencies: 'Zależności',
    ImportField_SkipColumn: '(Pomiń tę kolumnę)',
    ImportService_EmptyFileError: 'Plik wydaje się być pusty lub nie zawiera wierszy danych.',
    ImportService_ReadErrorDetail: 'Nie można odczytać pliku: {detail}.',
    ImportService_FileReadError: 'Błąd odczytu pliku.',
    ImportService_RowError: 'Wiersz {rowNum} („{title}”): {error}',
    ImportService_AmbiguousDependency: 'Zależność „{name}” pasuje do więcej niż jednego tytułu zadania — pominięto.',
    ImportService_LinkDependencyError: 'Nie można powiązać zależności dla zadania {taskId}: {error}',

    // ── Health labels (shared: healthUtils.ts and ExportService.ts both use this set; also replaces the duplicated Export_PortfolioHealthLabel* keys) ──
    Health_Done: 'Ukończono',
    Health_OnTrack: 'Zgodnie z planem',
    Health_AtRisk: 'Zagrożone',
    Health_Overdue: 'Po terminie',

    // ── Status / Priority display labels (DISPLAY-ONLY — stored SharePoint Choice values remain unchanged/English) ──
    Status_NotStarted: 'Nierozpoczęte',
    Status_InProgress: 'W toku',
    Status_Completed: 'Ukończone',
    Status_OnHold: 'Wstrzymane',
    Status_Cancelled: 'Anulowane',
    Priority_Critical: 'Krytyczny',
    Priority_High: 'Wysoki',
    Priority_Medium: 'Średni',
    Priority_Low: 'Niski',
    ProjectStatus_Planning: 'Planowanie',
    ProjectStatus_Active: 'Aktywny',
    ProjectStatus_OnHold: 'Wstrzymany',
    ProjectStatus_Completed: 'Ukończony',
    ProjectStatus_Cancelled: 'Anulowany',

    // ── Shell (SmartGantt.tsx) ──
    SmartGantt_LoadingProjects: 'Ładowanie projektów…',
    SmartGantt_UnableToLoad: 'Nie można załadować',
    SmartGantt_RetryButton: 'Ponów próbę',
    SmartGantt_NoProjectsYet: 'Brak projektów',
    SmartGantt_NoProjectsSubtitle: 'Utwórz pierwszy projekt, aby rozpocząć.',
    SmartGantt_CreateFirstProjectButton: '+ Utwórz pierwszy projekt',
    SmartGantt_ImportFromExcelButton: '📥 Importuj z programu Excel',
    SmartGantt_LoadingTasks: 'Ładowanie zadań…',
    SmartGantt_DismissAriaLabel: 'Zamknij',
    SmartGantt_DeleteTaskDialogTitle: 'Usuń zadanie',
    SmartGantt_DeleteTaskDialogSubtext: 'Czy na pewno chcesz usunąć „{taskTitle}”? Tej operacji nie można cofnąć.',
    SmartGantt_DeleteButton: 'Usuń',
    SmartGantt_CancelButton: 'Anuluj',
    SmartGantt_ArchiveProjectDialogTitle: 'Archiwizuj projekt',
    SmartGantt_ArchiveProjectDialogSubtext: 'Zarchiwizować „{projectTitle}”? Można to później cofnąć.',
    SmartGantt_ArchiveButton: 'Archiwizuj',
    SmartGantt_SendToRecycleBinDialogTitle: 'Przenieś do kosza',
    SmartGantt_SendToRecycleBinDialogSubtext: 'Przenieść „{projectTitle}” do kosza witryny?',
    SmartGantt_SendToRecycleBinButton: 'Przenieś do kosza',
    SmartGantt_FailedLoadProjects: 'Nie udało się załadować projektów. Sprawdź uprawnienia witryny.',
    SmartGantt_FailedLoadTasks: 'Nie udało się załadować zadań dla tego projektu.',
    SmartGantt_FailedLoadPortfolioStats: 'Nie udało się załadować statystyk portfela.',
    SmartGantt_CouldNotSaveProject: 'Nie można zapisać projektu: {message}',
    SmartGantt_CouldNotDeleteProject: 'Nie można usunąć projektu: {message}',
    SmartGantt_CouldNotArchiveProject: 'Nie można zarchiwizować projektu: {message}',
    SmartGantt_CouldNotUnarchiveProject: 'Nie można przywrócić projektu z archiwum: {message}',
    SmartGantt_CouldNotSaveTask: 'Nie można zapisać zadania: {message}',
    SmartGantt_CouldNotDeleteTask: 'Nie można usunąć zadania: {message}',
    SmartGantt_ImageExportFailed: 'Eksport obrazu nie powiódł się: {message}',
    SmartGantt_PowerPointExportFailed: 'Eksport do programu PowerPoint nie powiódł się: {message}',
    SmartGantt_PortfolioExportFailed: 'Eksport portfela nie powiódł się: {message}',
    SmartGantt_CouldNotUpdateTask: 'Nie można zaktualizować zadania: {message}',

    // ── Common ──
    ColorSwatch_AutoColorAriaLabel: 'Kolor automatyczny',
    ColorSwatch_CustomColorAriaLabel: 'Kolor niestandardowy',
    ColorSwatch_PickCustomColorTitle: 'Wybierz kolor niestandardowy',

    // ── Export (Excel / PowerPoint) ──
    Export_ColTaskName: 'Nazwa zadania',
    Export_ColPhase: 'Faza',
    Export_ColStartDate: 'Data rozpoczęcia',
    Export_ColDueDate: 'Termin',
    Export_ColStatus: 'Status',
    Export_ColPriority: 'Priorytet',
    Export_ColAssignedTo: 'Przypisano do',
    Export_ColAssignedToEmail: 'E-mail osoby przypisanej',
    Export_ColPercentComplete: '% ukończenia',
    Export_ColIsMilestone: 'Jest kamieniem milowym',
    Export_ColDescription: 'Opis',
    Export_ColNotes: 'Notatki',
    Export_Yes: 'Tak',
    Export_No: 'Nie',
    Export_SheetNameTasks: 'Zadania',
    Export_ExcelFileSuffix: ' - Zadania.xlsx',
    Export_TaskNameColumnLabel: 'NAZWA ZADANIA',
    Export_ExportedDateLabel: 'Wyeksportowano {date}',
    Export_ProjectReportLabel: 'RAPORT PROJEKTU',
    Export_StatusLine: 'Status: {status}',
    Export_DateRangeSeparator: ' do ',
    Export_ProjectManagerLine: 'Kierownik projektu: {name}',
    Export_GeneratedDateLine: 'Wygenerowano {date}',
    Export_ProjectSummaryTitle: 'Podsumowanie projektu',
    Export_StatTotalTasks: 'Wszystkie zadania',
    Export_StatCompleted: 'Ukończone',
    Export_StatInProgress: 'W toku',
    Export_StatOnHold: 'Wstrzymane',
    Export_StatNotStarted: 'Nierozpoczęte',
    Export_OverallProgressLine: 'Postęp ogólny',
    Export_OverallProgressPercent: '{percent}%',
    Export_StatusBreakdownTitle: 'Podział według statusu',
    Export_StatusBreakdownRow: '{status}: {count} ({percent}%)',
    Export_GanttTimelineTitle: 'Oś czasu wykresu Gantta',
    Export_SummaryRecentActivityTitle: 'Ostatnia aktywność',
    Export_ProjectOverviewLabel: 'Przegląd projektu',
    Export_DetailStatusLabel: 'Status',
    Export_DetailStartDateLabel: 'Data rozpoczęcia',
    Export_DetailDueDateLabel: 'Termin',
    Export_DetailProjectManagerLabel: 'Kierownik projektu',
    Export_Past7DaysLabel: 'Ostatnie 7 dni',
    Export_NoActivityMessage: 'Brak ostatniej aktywności.',
    Export_CompletedThisWeekHeader: 'Ukończone w tym tygodniu ({count})',
    Export_NewBadge: 'NOWE  ',
    Export_CompletedPercentLine: 'Ukończono {percent}%',
    Export_MoreItemsSuffix: '+ jeszcze {count}',
    Export_InProgressUpdatedHeader: 'W toku / Zaktualizowane',
    Export_StatusPercentLine: '{status} — {percent}%',
    Export_PortfolioReportLabel: 'RAPORT PORTFELA',
    Export_PortfolioOverviewTitle: 'Przegląd portfela',
    Export_ProjectsCountLine: '{count} projektów',
    Export_HealthSummaryOnTrack: '{count} zgodnie z planem',
    Export_HealthSummaryAtRisk: '{count} zagrożonych',
    Export_HealthSummaryOverdue: '{count} po terminie',
    Export_ProjectsSummaryHeader: 'Podsumowanie projektów',
    Export_TableProject: 'Projekt',
    Export_TableStatus: 'Status',
    Export_TableHealth: 'Stan realizacji',
    Export_TableTotal: 'Razem',
    Export_TableDone: 'Ukończone',
    Export_TableActive: 'Aktywne',
    Export_TableAtRisk: 'Zagrożone',
    Export_TableOverdue: 'Po terminie',
    Export_TablePctDone: '% ukończenia',
    Export_TableDueDate: 'Termin',
    Export_PortfolioSummaryFileName: 'Podsumowanie portfela.xlsx',
    Export_PortfolioReportFileName: 'Raport portfela.pptx',
    Export_ProjectReportFileName: 'Raport {projectName}.pptx',
    Export_UnavailableLabel: 'Niedostępne',
    Export_SheetNamePortfolio: 'Portfolio',
    Export_ColStart: 'Rozpoczęcie',
    Export_ColDue: 'Termin',
    Export_ImageGenerationFailed: 'Nie można wygenerować obrazu – wykres może być zbyt duży, aby wyeksportować go jako obraz.',
    Export_DrawingContextFailed: 'Nie można utworzyć kontekstu rysowania na potrzeby eksportu.',
    Export_SvgRenderFailed: 'Renderowanie SVG nie powiodło się',
  };
});
