define([], function () {
  return {
    // ── Property pane ──
    PropertyPane_HeaderDescription: 'Configurações do Smart Gantt Chart',
    PropertyPane_GeneralGroupName: 'Geral',
    PropertyPane_TitleFieldLabel: 'Título do Web Part',
    WebPart_DefaultTitle: 'Smart Gantt Chart',

    // ── Toolbar ──
    Toolbar_ViewDashboard: 'Painel',
    Toolbar_ViewList: 'Lista',
    Toolbar_ViewGantt: 'Gantt',
    Toolbar_ViewKanban: 'Kanban',
    Toolbar_ZoomDay: 'Dia',
    Toolbar_ZoomWeek: 'Semana',
    Toolbar_ZoomMonth: 'Mês',
    Toolbar_ZoomQuarter: 'Trimestre',
    Toolbar_SelectProjectAriaLabel: 'Selecionar projeto',
    Toolbar_PortfolioLabel: 'Portfólio',
    Toolbar_SelectAProject: 'Selecione um Projeto',
    Toolbar_AllProjectsSubtext: 'Todos os projetos',
    Toolbar_NoProjectsYet: 'Ainda não há projetos',
    Toolbar_ArchivedBadge: 'Arquivado',
    Toolbar_ShowArchivedProjects: 'Mostrar projetos arquivados',
    Toolbar_NewProject: '+ Novo Projeto',
    Toolbar_ImportFileAsNewProject: '📥 Importar Arquivo como Novo Projeto…',
    Toolbar_AddTask: '+ Adicionar Tarefa',
    Toolbar_EditProject: 'Editar Projeto',
    Toolbar_OptionsButton: '⚙ Opções',
    Toolbar_MoreOptionsTitle: 'Mais opções',
    Toolbar_ExportToExcel: '📊 Exportar para Excel',
    Toolbar_ExportToPowerPoint: '📑 Exportar para PowerPoint',
    Toolbar_ScrollToTodayTitle: 'Rolar até hoje',
    Toolbar_TodayButton: '◉ Hoje',
    Toolbar_ImportTasks: '📥 Importar Tarefas…',
    Toolbar_ExportAsImage: '🖼 Exportar como Imagem (PNG)',
    Toolbar_UnarchiveProject: '📂 Desarquivar Projeto',
    Toolbar_ArchiveProject: '🗄️ Arquivar Projeto',
    Toolbar_SendToRecycleBin: '🗑️ Enviar para a Lixeira',

    // ── Filter bar ──
    FilterBar_ClearOption: 'Limpar',
    FilterBar_DueAny: 'Qualquer data de vencimento',
    FilterBar_DueOverdue: 'Atrasado',
    FilterBar_DueToday: 'Vence hoje',
    FilterBar_DueWeek: 'Vence em 7 dias',
    FilterBar_SearchPlaceholder: 'Pesquisar tarefas…',
    FilterBar_SearchAriaLabel: 'Pesquisar tarefas',
    FilterBar_StatusChipLabel: 'Status',
    FilterBar_PriorityChipLabel: 'Prioridade',
    FilterBar_AssigneeChipLabel: 'Responsável',
    FilterBar_PhaseChipLabel: 'Fase',
    FilterBar_DueDateAriaLabel: 'Filtrar por data de vencimento',
    FilterBar_MatchCount: '{matchCount} de {totalCount}',
    FilterBar_ClearFilters: '✕ Limpar filtros',
    FilterBar_ChipLabelWithCount: '{label} ({count}) ▾',
    FilterBar_ChipLabelNoCount: '{label} ▾',

    // ── Gantt view ──
    Gantt_TaskColumnHeader: 'Tarefa',
    Gantt_DurationColumnHeader: 'Dur.',
    Gantt_AddTaskButton: '+ Adicionar Tarefa',
    Gantt_EmptyTitle: 'Ainda não há tarefas',
    Gantt_EmptySubtitle: 'Adicione tarefas para vê-las no gráfico de Gantt.',
    Gantt_AddFirstTask: '+ Adicionar Primeira Tarefa',
    Gantt_ImportTasksButton: '📥 Importar Tarefas',
    Gantt_EditTitle: 'Editar',
    Gantt_DeleteTitle: 'Excluir',
    Gantt_EditTaskAriaLabel: 'Editar tarefa {taskTitle}',
    Gantt_DeleteTaskAriaLabel: 'Excluir tarefa {taskTitle}',
    Gantt_ExpandPhaseAriaLabel: '{action} fase {phase}',
    Gantt_ExpandAction: 'Expandir',
    Gantt_CollapseAction: 'Recolher',
    Gantt_DependencyViolationTooltip: 'Iniciada antes de todas as dependências serem concluídas',
    Gantt_MilestoneAriaLabel: '{taskTitle}, marco, {date}',
    Gantt_BarAriaLabel: '{taskTitle}, {startDate} até {dueDate}, {percent}% concluído',
    Gantt_PercentCompleteTooltip: '{value}% concluído',

    // ── Gantt options/settings panel ──
    GanttSettings_PanelHeader: '⚙ Opções',
    GanttSettings_ColorCodingSection: 'Codificação por Cores',
    GanttSettings_ByStatus: 'Por Status',
    GanttSettings_ByPriority: 'Por Prioridade',
    GanttSettings_ByPhase: 'Por Fase',
    GanttSettings_ByHealth: 'Por Saúde',
    GanttSettings_HeaderColorSection: 'Cor do Cabeçalho',
    GanttSettings_ThemeDark: 'Escuro',
    GanttSettings_ThemeNavy: 'Azul-marinho',
    GanttSettings_ThemeTeal: 'Verde-azulado',
    GanttSettings_ThemePurple: 'Roxo',
    GanttSettings_ThemeLight: 'Claro',
    GanttSettings_HeaderLabelsSection: 'Rótulos do Cabeçalho',
    GanttSettings_WeekLabelDates: 'Datas',
    GanttSettings_WeekLabelDatesDesc: '3 de jun, 10 de jun…',
    GanttSettings_WeekLabelProject: 'Semanas do Projeto',
    GanttSettings_WeekLabelProjectDesc: 'S1, S2…',
    GanttSettings_WeekLabelIso: 'Semanas do Calendário',
    GanttSettings_WeekLabelIsoDesc: 'S23, S24…',
    GanttSettings_ProjectWeeksHint: 'A Semana 1 começa na segunda-feira da sua tarefa mais antiga — ótimo para apresentações.',
    GanttSettings_BarStyleSection: 'Estilo da Barra',
    GanttSettings_BarStyleGradient: 'Gradiente',
    GanttSettings_BarStyleFlat: 'Sólido',
    GanttSettings_RowHeightSection: 'Altura da Linha',
    GanttSettings_HeightCompact: 'Compacta',
    GanttSettings_HeightNormal: 'Normal',
    GanttSettings_HeightSpacious: 'Espaçosa',
    GanttSettings_ShowHideSection: 'Mostrar / Ocultar',
    GanttSettings_WeekendShading: 'Sombreamento de fim de semana',
    GanttSettings_DependencyArrows: 'Setas de dependência',
    GanttSettings_CriticalPathAlwaysVisible: 'Caminho crítico sempre visível',
    GanttSettings_AllOthersOnHoverOnly: 'Demais apenas ao passar o mouse',
    GanttSettings_CriticalPathHighlight: 'Destaque do caminho crítico',
    GanttSettings_ProgressPercentOnBars: '% de progresso nas barras',
    GanttSettings_AssigneeNameOnBars: 'Nome do responsável nas barras',
    GanttSettings_HealthStatusBadges: 'Selos de status de saúde',

    // ── List view ──
    ListView_ColTaskName: 'Nome da Tarefa',
    ListView_ColStatus: 'Status',
    ListView_ColHealth: 'Saúde',
    ListView_ColPriority: 'Prioridade',
    ListView_ColStart: 'Início',
    ListView_ColDue: 'Vencimento',
    ListView_ColAssignedTo: 'Atribuído a',
    ListView_ColProgress: 'Progresso',
    ListView_ColPhase: 'Fase',
    ListView_ColPredecessors: 'Predecessoras',
    ListView_EmptyTitle: 'Ainda não há tarefas',
    ListView_AddFirstTask: '+ Adicionar Primeira Tarefa',
    ListView_AddTaskRow: '+ Adicionar Tarefa',
    ListView_Unassigned: 'Não atribuído',
    ListView_DependencyViolationTooltip: 'Iniciada antes de todas as dependências serem concluídas',
    ListView_StatusAriaLabel: 'Status de {taskTitle}',
    ListView_PriorityAriaLabel: 'Prioridade de {taskTitle}',
    ListView_EditTaskAriaLabel: 'Editar tarefa {taskTitle}',
    ListView_DeleteTaskAriaLabel: 'Excluir tarefa {taskTitle}',
    ListView_EditTitle: 'Editar',
    ListView_DeleteTitle: 'Excluir',

    // ── Kanban view ──
    Kanban_ColumnNotStarted: 'Não Iniciado',
    Kanban_ColumnInProgress: 'Em Andamento',
    Kanban_ColumnOnHold: 'Em Espera',
    Kanban_ColumnCompleted: 'Concluído',
    Kanban_ColumnCancelled: 'Cancelado',
    Kanban_AddTaskButton: '+ Adicionar Tarefa',
    Kanban_EditTitle: 'Editar',
    Kanban_DeleteTitle: 'Excluir',
    Kanban_CardAriaLabel: '{taskTitle}, {status}. Pressione Enter para editar, seta Esquerda ou Direita para alterar o status.',
    Kanban_EditTaskAriaLabel: 'Editar tarefa {taskTitle}',
    Kanban_DeleteTaskAriaLabel: 'Excluir tarefa {taskTitle}',

    // ── Dashboard view ──
    Dashboard_TotalTasks: 'Total de Tarefas',
    Dashboard_Completed: 'Concluído',
    Dashboard_InProgress: 'Em Andamento',
    Dashboard_OnHold: 'Em Espera',
    Dashboard_NotStarted: 'Não Iniciado',
    Dashboard_Cancelled: 'Cancelado',
    Dashboard_OverallProgress: 'Progresso Geral',
    Dashboard_ProjectManagerLabel: 'Gerente de Projeto: {name}',
    Dashboard_PhaseProgressHeader: 'Progresso por Fase',
    Dashboard_StatusBreakdownHeader: 'Detalhamento por Status',
    Dashboard_PriorityBreakdownHeader: 'Detalhamento por Prioridade',
    Dashboard_PriorityCritical: 'Crítica',
    Dashboard_PriorityHigh: 'Alta',
    Dashboard_PriorityMedium: 'Média',
    Dashboard_PriorityLow: 'Baixa',
    Dashboard_OverdueHeader: 'Atrasadas  ({count})',
    Dashboard_DueNext14DaysHeader: 'Vencem nos próximos 14 dias  ({count})',
    Dashboard_CompletedThisWeekHeader: 'Concluídas Esta Semana',
    Dashboard_UpdatedThisWeekHeader: 'Atualizadas Esta Semana',
    Dashboard_Today: 'Hoje',
    Dashboard_Tomorrow: 'Amanhã',
    Dashboard_DaysLeft: '{days}d',
    Dashboard_EmptyTitle: 'Ainda não há tarefas',
    Dashboard_EmptySubtitle: 'Adicione tarefas para ver o painel do seu projeto.',
    Dashboard_AddTaskButton: '+ Adicionar Tarefa',

    // ── Portfolio view ──
    Portfolio_ProjectCount: '{count} Projeto{plural}',
    Portfolio_OnTrackSummary: '{count} No Prazo',
    Portfolio_AtRiskSummary: '{count} Em Risco',
    Portfolio_OverdueSummary: '{count} Atrasado',
    Portfolio_DoneSummary: '{count} Concluído',
    Portfolio_SortLabel: 'Ordenar:',
    Portfolio_SortAZ: 'A-Z',
    Portfolio_SortHealth: 'Saúde',
    Portfolio_SortStatus: 'Status',
    Portfolio_SortCompletion: 'Conclusão',
    Portfolio_RefreshTitle: 'Atualizar',
    Portfolio_RefreshButton: 'Atualizar',
    Portfolio_LoadingStats: 'Carregando estatísticas…',
    Portfolio_EmptyTitle: 'Ainda não há projetos',
    Portfolio_CreateFirstProject: '+ Criar Primeiro Projeto',
    Portfolio_StatsUnavailable: 'Estatísticas indisponíveis',
    Portfolio_StatsUnavailableDetail: 'Não foi possível carregar as estatísticas deste projeto.',
    Portfolio_OverallProgressLabel: 'Progresso Geral',
    Portfolio_TaskCountDone: 'Concluído',
    Portfolio_TaskCountActive: 'Ativo',
    Portfolio_TaskCountAtRisk: 'Em Risco',
    Portfolio_TaskCountOverdue: 'Atrasado',
    Portfolio_ViewGanttLink: 'Ver Gantt →',
    Portfolio_TodayTooltip: 'Hoje',

    // ── Task panel ──
    TaskPanel_EditHeader: 'Editar: {taskTitle}',
    TaskPanel_NewTaskHeader: 'Nova Tarefa',
    TaskPanel_TabBasic: 'Básico',
    TaskPanel_TabDetails: 'Detalhes',
    TaskPanel_TabLinks: 'Vínculos',
    TaskPanel_ProjectLabelPrefix: 'Projeto: ',
    TaskPanel_TaskNameLabel: 'Nome da Tarefa',
    TaskPanel_TaskNamePlaceholder: 'Digite o nome da tarefa',
    TaskPanel_TaskNameRequired: 'O nome da tarefa é obrigatório',
    TaskPanel_DescriptionLabel: 'Descrição',
    TaskPanel_DescriptionPlaceholder: 'Digite a descrição',
    TaskPanel_StartDateLabel: 'Data de Início',
    TaskPanel_DueDateLabel: 'Data de Vencimento',
    TaskPanel_DueDateError: 'A data de vencimento deve ser igual ou posterior à data de início',
    TaskPanel_StatusLabel: 'Status',
    TaskPanel_PriorityLabel: 'Prioridade',
    TaskPanel_PercentCompleteLabel: '% Concluído: {percent}%',
    TaskPanel_AssignedToLabel: 'Atribuído a',
    TaskPanel_AssignedToPlaceholder: 'Pesquisar pessoas…',
    TaskPanel_PhaseLabel: 'Fase',
    TaskPanel_PhasePlaceholder: 'Digite o nome da fase',
    TaskPanel_PhaseHint: 'Agrupa tarefas nas visões Gantt e Lista.',
    TaskPanel_MilestoneLabel: 'Marco',
    TaskPanel_MilestoneOnText: 'Sim',
    TaskPanel_MilestoneOffText: 'Não',
    TaskPanel_CustomBarColorLabel: 'Cor Personalizada da Barra',
    TaskPanel_CustomBarColorOptionalSuffix: ' (opcional)',
    TaskPanel_AutoColorHint: 'Cor automática a partir das configurações de status/prioridade/fase.',
    TaskPanel_NotesLabel: 'Observações',
    TaskPanel_NotesPlaceholder: 'Digite observações',
    TaskPanel_ParentTaskLabel: 'Tarefa Pai',
    TaskPanel_ParentTaskNone: '(nenhuma)',
    TaskPanel_ParentTaskHasChildrenHint: 'Esta tarefa tem subtarefas e não pode ter uma tarefa pai própria.',
    TaskPanel_ParentTaskHint: 'Aninhe esta tarefa sob outra como subtarefa.',
    TaskPanel_DependsOnLabel: 'Depende De',
    TaskPanel_RemoveDependencyTitle: 'Remover dependência de "{taskTitle}"',
    TaskPanel_AddDependencyPlaceholder: 'Adicionar uma dependência…',
    TaskPanel_SelectATaskOption: 'Selecione uma tarefa…',
    TaskPanel_DependsOnHint: 'A tarefa não pode começar até que estas sejam concluídas.',
    TaskPanel_SavingLabel: 'Salvando…',
    TaskPanel_CreatingLabel: 'Criando…',
    TaskPanel_SaveChangesButton: 'Salvar Alterações',
    TaskPanel_CreateTaskButton: 'Criar Tarefa',
    TaskPanel_CancelButton: 'Cancelar',
    TaskPanel_DismissAriaLabel: 'Dispensar',
    TaskPanel_DiscardUnsavedChangesConfirm: 'Descartar alterações não salvas?',
    TaskPanel_SaveFallbackError: 'Não foi possível salvar a tarefa.',

    // ── Project panel ──
    ProjectPanel_EditHeader: 'Editar Projeto',
    ProjectPanel_NewHeader: 'Novo Projeto',
    ProjectPanel_ProjectNameLabel: 'Nome do Projeto',
    ProjectPanel_ProjectNamePlaceholder: 'Digite o nome do projeto',
    ProjectPanel_ProjectNameRequired: 'O nome do projeto é obrigatório',
    ProjectPanel_DescriptionLabel: 'Descrição',
    ProjectPanel_DescriptionPlaceholder: 'Digite a descrição',
    ProjectPanel_ProjectColorLabel: 'Cor do Projeto',
    ProjectPanel_StatusLabel: 'Status',
    ProjectPanel_StartDateLabel: 'Data de Início',
    ProjectPanel_DueDateLabel: 'Data de Vencimento',
    ProjectPanel_DueDateError: 'A data de vencimento deve ser igual ou posterior à data de início',
    ProjectPanel_WhatHappensNextTitle: 'O que acontece a seguir?',
    ProjectPanel_WhatHappensNextBody: 'Você poderá adicionar tarefas, configurar fases e acompanhar o progresso assim que o projeto for criado.',
    ProjectPanel_SavingLabel: 'Salvando…',
    ProjectPanel_CreatingLabel: 'Criando…',
    ProjectPanel_SaveChangesButton: 'Salvar Alterações',
    ProjectPanel_CreateProjectButton: 'Criar Projeto',
    ProjectPanel_CancelButton: 'Cancelar',
    ProjectPanel_DismissAriaLabel: 'Dispensar',
    ProjectPanel_DiscardUnsavedChangesConfirm: 'Descartar alterações não salvas?',
    ProjectPanel_SaveFallbackError: 'Não foi possível salvar o projeto.',

    // ── Import panel ──
    ImportPanel_SourceExcelTitle: 'Arquivo Excel / CSV',
    ImportPanel_SourceExcelSubtitle: 'Importar tarefas de uma planilha',
    ImportPanel_SourcePlannerTitle: 'Microsoft Planner',
    ImportPanel_SourcePlannerSubtitle: 'Importar tarefas de um plano do Planner',
    ImportPanel_ClickToBrowse: 'Clique para procurar',
    ImportPanel_DragDropSuffix: ' ou arraste e solte',
    ImportPanel_SupportedExtensions: 'Suporta .xlsx, .xls, .csv',
    ImportPanel_RowsColsSummary: '{rows} linhas, {cols} colunas detectadas',
    ImportPanel_LoadingPlannerPlans: 'Carregando planos do Planner…',
    ImportPanel_PlannerLoadError: 'Não foi possível carregar os planos do Planner.',
    ImportPanel_PlannerPermissionsHintPrefix: 'Verifique se você tem acesso ao Planner e se ',
    ImportPanel_PlannerPermissionsHintEmphasis: 'Tarefas do Planner e To Do',
    ImportPanel_PlannerPermissionsHintSuffix: ' está disponível neste site.',
    ImportPanel_NoPlannerPlansFoundTitle: 'Nenhum plano do Planner encontrado',
    ImportPanel_NoPlannerPlansFoundBody: 'Você pode não ter acesso a nenhum plano do Planner, ou nenhum existe para esta conta.',
    ImportPanel_TaskCountFoundIn: '{count} tarefas encontradas em "{planName}"',
    ImportPanel_ProjectDetailsIntroPrefix: 'Importando para ',
    ImportPanel_ProjectDetailsIntroSuffix: '. Revise os detalhes do projeto abaixo.',
    ImportPanel_ProjectNameLabel: 'Nome do Projeto',
    ImportPanel_DescriptionLabel: 'Descrição',
    ImportPanel_StatusLabel: 'Status',
    ImportPanel_ColorLabel: 'Cor',
    ImportPanel_MapIntro: 'Mapeie as colunas do seu arquivo para os campos da tarefa.',
    ImportPanel_CreatingProjectStatus: 'Criando projeto…',
    ImportPanel_ImportingTasksStatus: 'Importando tarefas…',
    ImportPanel_ProgressLabel: '{done} de {total}',
    ImportPanel_CouldNotCreateProject: 'Não foi possível criar o projeto.',
    ImportPanel_ImportCompletedWithErrors: 'Importação concluída com {count} erro(s).',
    ImportPanel_ProjectCreatedSuccess: 'Projeto criado com sucesso!',
    ImportPanel_ImportSuccessful: 'Importação bem-sucedida!',
    ImportPanel_TasksAddedTo: '{count} tarefas adicionadas a "{projectName}"',
    ImportPanel_FailedRowsLabel: 'Linhas com falha:',
    ImportPanel_CloseButton: 'Fechar',
    ImportPanel_OpenProjectButton: 'Abrir Projeto',
    ImportPanel_ViewImportedTasksButton: 'Ver Tarefas Importadas',
    ImportPanel_NextMapColumnsButton: 'Próximo: Mapear Colunas',
    ImportPanel_ImportNTasksButton: 'Importar {count} Tarefas',
    ImportPanel_BackButton: 'Voltar',
    ImportPanel_CancelButton: 'Cancelar',
    ImportPanel_NextButton: 'Próximo',
    ImportPanel_StepSource: 'Origem',
    ImportPanel_StepProject: 'Projeto',
    ImportPanel_StepMap: 'Mapear',
    ImportPanel_StepImport: 'Importar',
    ImportPanel_StepDone: 'Concluído',
    ImportPanel_ImportAsNewProjectHeader: 'Importar Arquivo como Novo Projeto',
    ImportPanel_ImportIntoProjectHeader: 'Importar Tarefas para {projectName}',
    ImportPanel_CouldNotParseFile: 'Não foi possível processar o arquivo.',
    ImportPanel_CouldNotLoadPlannerTasks: 'Não foi possível carregar as tarefas deste plano.',
    ImportPanel_CouldNotCreateProjectDetail: 'Não foi possível criar o projeto: {detail}',
    ImportPanel_CouldNotLinkDependencies: 'Não foi possível vincular as dependências: {detail}',
    ImportPanel_UnknownError: 'erro desconhecido',

    // ── Column mapper (import) ──
    ColumnMapper_TaskNameRequiredBanner: 'O Nome da Tarefa deve ser mapeado para continuar.',
    ColumnMapper_SkippedColumnsBanner: '{count} coluna(s) serão ignoradas.',
    ColumnMapper_SourceColumnHeader: 'Coluna de Origem',
    ColumnMapper_TargetFieldHeader: 'Campo de Destino',
    ColumnMapper_StatusHeader: 'Status',
    ColumnMapper_SkippedBadge: 'Ignorada',
    ColumnMapper_AutoMappedBadge: 'Mapeada automaticamente',
    ColumnMapper_SetBadge: 'Definida',
    ColumnMapper_PreviewTitle: 'Pré-visualização: {columnName}',
    ColumnMapper_EmptyCellDash: '—',

    // ── Import field display names / ImportService ──
    ImportField_TaskName: 'Nome da Tarefa',
    ImportField_StartDate: 'Data de Início',
    ImportField_DueDate: 'Data de Vencimento',
    ImportField_Status: 'Status',
    ImportField_Priority: 'Prioridade',
    ImportField_AssignedTo: 'Atribuído a',
    ImportField_AssignedToEmail: 'E-mail do Atribuído',
    ImportField_PercentComplete: '% Concluído',
    ImportField_Phase: 'Fase',
    ImportField_Description: 'Descrição',
    ImportField_Notes: 'Observações',
    ImportField_IsMilestone: 'É Marco',
    ImportField_Dependencies: 'Dependências',
    ImportField_SkipColumn: '(Ignorar esta coluna)',
    ImportService_EmptyFileError: 'O arquivo parece estar vazio ou não possui linhas de dados.',
    ImportService_ReadErrorDetail: 'Não foi possível ler o arquivo: {detail}.',
    ImportService_FileReadError: 'Erro de leitura do arquivo.',
    ImportService_RowError: 'Linha {rowNum} ("{title}"): {error}',
    ImportService_AmbiguousDependency: 'A dependência "{name}" corresponde a mais de um título de tarefa — ignorada.',
    ImportService_LinkDependencyError: 'Não foi possível vincular as dependências da tarefa {taskId}: {error}',

    // ── Health labels (shared: healthUtils.ts and ExportService.ts both use this set; also replaces the duplicated Export_PortfolioHealthLabel* keys) ──
    Health_Done: 'Concluído',
    Health_OnTrack: 'No Prazo',
    Health_AtRisk: 'Em Risco',
    Health_Overdue: 'Atrasado',

    // ── Status / Priority display labels (DISPLAY-ONLY — stored SharePoint Choice values remain unchanged/English) ──
    Status_NotStarted: 'Não Iniciado',
    Status_InProgress: 'Em Andamento',
    Status_Completed: 'Concluído',
    Status_OnHold: 'Em Espera',
    Status_Cancelled: 'Cancelado',
    Priority_Critical: 'Crítica',
    Priority_High: 'Alta',
    Priority_Medium: 'Média',
    Priority_Low: 'Baixa',
    ProjectStatus_Planning: 'Planejamento',
    ProjectStatus_Active: 'Ativo',
    ProjectStatus_OnHold: 'Em Espera',
    ProjectStatus_Completed: 'Concluído',
    ProjectStatus_Cancelled: 'Cancelado',

    // ── Shell (SmartGantt.tsx) ──
    SmartGantt_LoadingProjects: 'Carregando projetos…',
    SmartGantt_UnableToLoad: 'Não foi possível carregar',
    SmartGantt_RetryButton: 'Tentar Novamente',
    SmartGantt_NoProjectsYet: 'Ainda não há projetos',
    SmartGantt_NoProjectsSubtitle: 'Crie seu primeiro projeto para começar.',
    SmartGantt_CreateFirstProjectButton: '+ Criar Primeiro Projeto',
    SmartGantt_ImportFromExcelButton: '📥 Importar do Excel',
    SmartGantt_LoadingTasks: 'Carregando tarefas…',
    SmartGantt_DismissAriaLabel: 'Dispensar',
    SmartGantt_DeleteTaskDialogTitle: 'Excluir Tarefa',
    SmartGantt_DeleteTaskDialogSubtext: 'Tem certeza de que deseja excluir "{taskTitle}"? Esta ação não pode ser desfeita.',
    SmartGantt_DeleteButton: 'Excluir',
    SmartGantt_CancelButton: 'Cancelar',
    SmartGantt_ArchiveProjectDialogTitle: 'Arquivar Projeto',
    SmartGantt_ArchiveProjectDialogSubtext: 'Arquivar "{projectTitle}"? Você pode desarquivá-lo depois.',
    SmartGantt_ArchiveButton: 'Arquivar',
    SmartGantt_SendToRecycleBinDialogTitle: 'Enviar para a Lixeira',
    SmartGantt_SendToRecycleBinDialogSubtext: 'Enviar "{projectTitle}" para a lixeira do site?',
    SmartGantt_SendToRecycleBinButton: 'Enviar para a Lixeira',
    SmartGantt_FailedLoadProjects: 'Falha ao carregar os projetos. Verifique as permissões do site.',
    SmartGantt_FailedLoadTasks: 'Falha ao carregar as tarefas deste projeto.',
    SmartGantt_FailedLoadPortfolioStats: 'Falha ao carregar as estatísticas do portfólio.',
    SmartGantt_CouldNotSaveProject: 'Não foi possível salvar o projeto: {message}',
    SmartGantt_CouldNotDeleteProject: 'Não foi possível excluir o projeto: {message}',
    SmartGantt_CouldNotArchiveProject: 'Não foi possível arquivar o projeto: {message}',
    SmartGantt_CouldNotUnarchiveProject: 'Não foi possível desarquivar o projeto: {message}',
    SmartGantt_CouldNotSaveTask: 'Não foi possível salvar a tarefa: {message}',
    SmartGantt_CouldNotDeleteTask: 'Não foi possível excluir a tarefa: {message}',
    SmartGantt_ImageExportFailed: 'Falha na exportação da imagem: {message}',
    SmartGantt_PowerPointExportFailed: 'Falha na exportação para PowerPoint: {message}',
    SmartGantt_PortfolioExportFailed: 'Falha na exportação do portfólio: {message}',
    SmartGantt_CouldNotUpdateTask: 'Não foi possível atualizar a tarefa: {message}',

    // ── Common ──
    ColorSwatch_AutoColorAriaLabel: 'Cor automática',
    ColorSwatch_CustomColorAriaLabel: 'Cor personalizada',
    ColorSwatch_PickCustomColorTitle: 'Escolher uma cor personalizada',

    // ── Export (Excel / PowerPoint) ──
    Export_ColTaskName: 'Nome da Tarefa',
    Export_ColPhase: 'Fase',
    Export_ColStartDate: 'Data de Início',
    Export_ColDueDate: 'Data de Vencimento',
    Export_ColStatus: 'Status',
    Export_ColPriority: 'Prioridade',
    Export_ColAssignedTo: 'Atribuído a',
    Export_ColAssignedToEmail: 'E-mail do Atribuído',
    Export_ColPercentComplete: '% Concluído',
    Export_ColIsMilestone: 'É Marco',
    Export_ColDescription: 'Descrição',
    Export_ColNotes: 'Observações',
    Export_Yes: 'Sim',
    Export_No: 'Não',
    Export_SheetNameTasks: 'Tarefas',
    Export_ExcelFileSuffix: ' - Tarefas.xlsx',
    Export_TaskNameColumnLabel: 'NOME DA TAREFA',
    Export_ExportedDateLabel: 'Exportado em {date}',
    Export_ProjectReportLabel: 'RELATÓRIO DO PROJETO',
    Export_StatusLine: 'Status: {status}',
    Export_DateRangeSeparator: ' até ',
    Export_ProjectManagerLine: 'Gerente de Projeto: {name}',
    Export_GeneratedDateLine: 'Gerado em {date}',
    Export_ProjectSummaryTitle: 'Resumo do Projeto',
    Export_StatTotalTasks: 'Total de Tarefas',
    Export_StatCompleted: 'Concluído',
    Export_StatInProgress: 'Em Andamento',
    Export_StatOnHold: 'Em Espera',
    Export_StatNotStarted: 'Não Iniciado',
    Export_OverallProgressLine: 'Progresso Geral',
    Export_OverallProgressPercent: '{percent}%',
    Export_StatusBreakdownTitle: 'Detalhamento por Status',
    Export_StatusBreakdownRow: '{status}: {count} ({percent}%)',
    Export_GanttTimelineTitle: 'Cronograma Gantt',
    Export_SummaryRecentActivityTitle: 'Atividade Recente',
    Export_ProjectOverviewLabel: 'Visão Geral do Projeto',
    Export_DetailStatusLabel: 'Status',
    Export_DetailStartDateLabel: 'Data de Início',
    Export_DetailDueDateLabel: 'Data de Vencimento',
    Export_DetailProjectManagerLabel: 'Gerente de Projeto',
    Export_Past7DaysLabel: 'Últimos 7 Dias',
    Export_NoActivityMessage: 'Nenhuma atividade recente.',
    Export_CompletedThisWeekHeader: 'Concluídas Esta Semana ({count})',
    Export_NewBadge: 'NOVO  ',
    Export_CompletedPercentLine: '{percent}% concluído',
    Export_MoreItemsSuffix: '+ {count} mais',
    Export_InProgressUpdatedHeader: 'Em Andamento / Atualizadas',
    Export_StatusPercentLine: '{status} — {percent}%',
    Export_PortfolioReportLabel: 'RELATÓRIO DE PORTFÓLIO',
    Export_PortfolioOverviewTitle: 'Visão Geral do Portfólio',
    Export_ProjectsCountLine: '{count} Projetos',
    Export_HealthSummaryOnTrack: '{count} No Prazo',
    Export_HealthSummaryAtRisk: '{count} Em Risco',
    Export_HealthSummaryOverdue: '{count} Atrasado',
    Export_ProjectsSummaryHeader: 'Resumo dos Projetos',
    Export_TableProject: 'Projeto',
    Export_TableStatus: 'Status',
    Export_TableHealth: 'Saúde',
    Export_TableTotal: 'Total',
    Export_TableDone: 'Concluído',
    Export_TableActive: 'Ativo',
    Export_TableAtRisk: 'Em Risco',
    Export_TableOverdue: 'Atrasado',
    Export_TablePctDone: '% Concluído',
    Export_TableDueDate: 'Data de Vencimento',
    Export_PortfolioSummaryFileName: 'Resumo do Portfólio.xlsx',
    Export_PortfolioReportFileName: 'Relatório do Portfólio.pptx',
    Export_ProjectReportFileName: 'Relatório de {projectName}.pptx',
    Export_UnavailableLabel: 'Indisponível',
    Export_SheetNamePortfolio: 'Portfólio',
    Export_ColStart: 'Início',
    Export_ColDue: 'Vencimento',
    Export_ImageGenerationFailed: 'Não foi possível gerar a imagem — o gráfico pode ser grande demais para ser exportado como imagem.',
    Export_DrawingContextFailed: 'Não foi possível criar um contexto de desenho para a exportação.',
    Export_SvgRenderFailed: 'Falha ao renderizar o SVG',
  };
});
