define([], function () {
  return {
    // ── Property pane ──
    PropertyPane_HeaderDescription: 'Definições do Smart Gantt Chart',
    PropertyPane_GeneralGroupName: 'Geral',
    PropertyPane_TitleFieldLabel: 'Título do Web Part',
    WebPart_DefaultTitle: 'Smart Gantt Chart',

    // ── Toolbar ──
    Toolbar_ViewDashboard: 'Painel',
    Toolbar_ViewList: 'Lista',
    Toolbar_ViewGantt: 'Gantt',
    Toolbar_ViewKanban: 'Kanban',
    Toolbar_ZoomDay: 'Dia',
    Toolbar_ZoomWeek: 'Semana',
    Toolbar_ZoomMonth: 'Mês',
    Toolbar_ZoomQuarter: 'Trimestre',
    Toolbar_SelectProjectAriaLabel: 'Selecionar projeto',
    Toolbar_PortfolioLabel: 'Portefólio',
    Toolbar_SelectAProject: 'Selecione um Projeto',
    Toolbar_AllProjectsSubtext: 'Todos os projetos',
    Toolbar_NoProjectsYet: 'Ainda não existem projetos',
    Toolbar_ArchivedBadge: 'Arquivado',
    Toolbar_ShowArchivedProjects: 'Mostrar projetos arquivados',
    Toolbar_NewProject: '+ Novo Projeto',
    Toolbar_ImportFileAsNewProject: '📥 Importar Ficheiro como Novo Projeto…',
    Toolbar_AddTask: '+ Adicionar Tarefa',
    Toolbar_EditProject: 'Editar Projeto',
    Toolbar_OptionsButton: '⚙ Opções',
    Toolbar_MoreOptionsTitle: 'Mais opções',
    Toolbar_ExportToExcel: '📊 Exportar para Excel',
    Toolbar_ExportToPowerPoint: '📑 Exportar para PowerPoint',
    Toolbar_ScrollToTodayTitle: 'Deslocar para hoje',
    Toolbar_TodayButton: '◉ Hoje',
    Toolbar_ImportTasks: '📥 Importar Tarefas…',
    Toolbar_ExportAsImage: '🖼 Exportar como Imagem (PNG)',
    Toolbar_UnarchiveProject: '📂 Desarquivar Projeto',
    Toolbar_ArchiveProject: '🗄️ Arquivar Projeto',
    Toolbar_SendToRecycleBin: '🗑️ Enviar para a Reciclagem',

    // ── Filter bar ──
    FilterBar_ClearOption: 'Limpar',
    FilterBar_DueAny: 'Qualquer data de conclusão',
    FilterBar_DueOverdue: 'Em atraso',
    FilterBar_DueToday: 'Termina hoje',
    FilterBar_DueWeek: 'Termina em 7 dias',
    FilterBar_SearchPlaceholder: 'Pesquisar tarefas…',
    FilterBar_SearchAriaLabel: 'Pesquisar tarefas',
    FilterBar_StatusChipLabel: 'Estado',
    FilterBar_PriorityChipLabel: 'Prioridade',
    FilterBar_AssigneeChipLabel: 'Responsável',
    FilterBar_PhaseChipLabel: 'Fase',
    FilterBar_DueDateAriaLabel: 'Filtrar por data de conclusão',
    FilterBar_MatchCount: '{matchCount} de {totalCount}',
    FilterBar_ClearFilters: '✕ Limpar filtros',
    FilterBar_ChipLabelWithCount: '{label} ({count}) ▾',
    FilterBar_ChipLabelNoCount: '{label} ▾',

    // ── Gantt view ──
    Gantt_TaskColumnHeader: 'Tarefa',
    Gantt_DurationColumnHeader: 'Dur.',
    Gantt_AddTaskButton: '+ Adicionar Tarefa',
    Gantt_EmptyTitle: 'Ainda não existem tarefas',
    Gantt_EmptySubtitle: 'Adicione tarefas para as ver no gráfico de Gantt.',
    Gantt_AddFirstTask: '+ Adicionar Primeira Tarefa',
    Gantt_ImportTasksButton: '📥 Importar Tarefas',
    Gantt_EditTitle: 'Editar',
    Gantt_DeleteTitle: 'Eliminar',
    Gantt_EditTaskAriaLabel: 'Editar tarefa {taskTitle}',
    Gantt_DeleteTaskAriaLabel: 'Eliminar tarefa {taskTitle}',
    Gantt_ExpandPhaseAriaLabel: '{action} fase {phase}',
    Gantt_ExpandAction: 'Expandir',
    Gantt_CollapseAction: 'Recolher',
    Gantt_DependencyViolationTooltip: 'Iniciada antes de todas as dependências estarem concluídas',
    Gantt_MilestoneAriaLabel: '{taskTitle}, marco, {date}',
    Gantt_BarAriaLabel: '{taskTitle}, {startDate} a {dueDate}, {percent}% concluído',
    Gantt_PercentCompleteTooltip: '{value}% concluído',

    // ── Gantt options/settings panel ──
    GanttSettings_PanelHeader: '⚙ Opções',
    GanttSettings_ColorCodingSection: 'Codificação por Cores',
    GanttSettings_ByStatus: 'Por Estado',
    GanttSettings_ByPriority: 'Por Prioridade',
    GanttSettings_ByPhase: 'Por Fase',
    GanttSettings_ByHealth: 'Por Estado de Saúde',
    GanttSettings_HeaderColorSection: 'Cor do Cabeçalho',
    GanttSettings_ThemeDark: 'Escuro',
    GanttSettings_ThemeNavy: 'Azul-marinho',
    GanttSettings_ThemeTeal: 'Verde-azulado',
    GanttSettings_ThemePurple: 'Roxo',
    GanttSettings_ThemeLight: 'Claro',
    GanttSettings_HeaderLabelsSection: 'Rótulos do Cabeçalho',
    GanttSettings_WeekLabelDates: 'Datas',
    GanttSettings_WeekLabelDatesDesc: '3 jun, 10 jun…',
    GanttSettings_WeekLabelProject: 'Semanas do Projeto',
    GanttSettings_WeekLabelProjectDesc: 'S1, S2…',
    GanttSettings_WeekLabelIso: 'Semanas do Calendário',
    GanttSettings_WeekLabelIsoDesc: 'S23, S24…',
    GanttSettings_ProjectWeeksHint: 'A Semana 1 começa na segunda-feira da tarefa mais antiga — ótimo para apresentações.',
    GanttSettings_BarStyleSection: 'Estilo da Barra',
    GanttSettings_BarStyleGradient: 'Gradiente',
    GanttSettings_BarStyleFlat: 'Uniforme',
    GanttSettings_RowHeightSection: 'Altura da Linha',
    GanttSettings_HeightCompact: 'Compacta',
    GanttSettings_HeightNormal: 'Normal',
    GanttSettings_HeightSpacious: 'Espaçosa',
    GanttSettings_ShowHideSection: 'Mostrar / Ocultar',
    GanttSettings_WeekendShading: 'Sombreado de fim de semana',
    GanttSettings_DependencyArrows: 'Setas de dependência',
    GanttSettings_CriticalPathAlwaysVisible: 'Caminho crítico sempre visível',
    GanttSettings_AllOthersOnHoverOnly: 'Restantes apenas ao pairar com o rato',
    GanttSettings_CriticalPathHighlight: 'Destaque do caminho crítico',
    GanttSettings_ProgressPercentOnBars: '% de progresso nas barras',
    GanttSettings_AssigneeNameOnBars: 'Nome do responsável nas barras',
    GanttSettings_HealthStatusBadges: 'Emblemas de estado de saúde',

    // ── List view ──
    ListView_ColTaskName: 'Nome da Tarefa',
    ListView_ColStatus: 'Estado',
    ListView_ColHealth: 'Saúde',
    ListView_ColPriority: 'Prioridade',
    ListView_ColStart: 'Início',
    ListView_ColDue: 'Conclusão',
    ListView_ColAssignedTo: 'Atribuído a',
    ListView_ColProgress: 'Progresso',
    ListView_ColPhase: 'Fase',
    ListView_ColPredecessors: 'Predecessoras',
    ListView_EmptyTitle: 'Ainda não existem tarefas',
    ListView_AddFirstTask: '+ Adicionar Primeira Tarefa',
    ListView_AddTaskRow: '+ Adicionar Tarefa',
    ListView_Unassigned: 'Sem atribuição',
    ListView_DependencyViolationTooltip: 'Iniciada antes de todas as dependências estarem concluídas',
    ListView_StatusAriaLabel: 'Estado de {taskTitle}',
    ListView_PriorityAriaLabel: 'Prioridade de {taskTitle}',
    ListView_EditTaskAriaLabel: 'Editar tarefa {taskTitle}',
    ListView_DeleteTaskAriaLabel: 'Eliminar tarefa {taskTitle}',
    ListView_EditTitle: 'Editar',
    ListView_DeleteTitle: 'Eliminar',

    // ── Kanban view ──
    Kanban_ColumnNotStarted: 'Não Iniciada',
    Kanban_ColumnInProgress: 'Em Curso',
    Kanban_ColumnOnHold: 'Em Pausa',
    Kanban_ColumnCompleted: 'Concluída',
    Kanban_ColumnCancelled: 'Cancelada',
    Kanban_AddTaskButton: '+ Adicionar Tarefa',
    Kanban_EditTitle: 'Editar',
    Kanban_DeleteTitle: 'Eliminar',
    Kanban_CardAriaLabel: '{taskTitle}, {status}. Prima Enter para editar, seta Esquerda ou Direita para alterar o estado.',
    Kanban_EditTaskAriaLabel: 'Editar tarefa {taskTitle}',
    Kanban_DeleteTaskAriaLabel: 'Eliminar tarefa {taskTitle}',

    // ── Dashboard view ──
    Dashboard_TotalTasks: 'Total de Tarefas',
    Dashboard_Completed: 'Concluídas',
    Dashboard_InProgress: 'Em Curso',
    Dashboard_OnHold: 'Em Pausa',
    Dashboard_NotStarted: 'Não Iniciadas',
    Dashboard_Cancelled: 'Canceladas',
    Dashboard_OverallProgress: 'Progresso Global',
    Dashboard_ProjectManagerLabel: 'Gestor de Projeto: {name}',
    Dashboard_PhaseProgressHeader: 'Progresso por Fase',
    Dashboard_StatusBreakdownHeader: 'Distribuição por Estado',
    Dashboard_PriorityBreakdownHeader: 'Distribuição por Prioridade',
    Dashboard_PriorityCritical: 'Crítica',
    Dashboard_PriorityHigh: 'Alta',
    Dashboard_PriorityMedium: 'Média',
    Dashboard_PriorityLow: 'Baixa',
    Dashboard_OverdueHeader: 'Em Atraso  ({count})',
    Dashboard_DueNext14DaysHeader: 'A terminar nos próximos 14 dias  ({count})',
    Dashboard_CompletedThisWeekHeader: 'Concluídas Esta Semana',
    Dashboard_UpdatedThisWeekHeader: 'Atualizadas Esta Semana',
    Dashboard_Today: 'Hoje',
    Dashboard_Tomorrow: 'Amanhã',
    Dashboard_DaysLeft: '{days}d',
    Dashboard_EmptyTitle: 'Ainda não existem tarefas',
    Dashboard_EmptySubtitle: 'Adicione tarefas para ver o painel do seu projeto.',
    Dashboard_AddTaskButton: '+ Adicionar Tarefa',

    // ── Portfolio view ──
    Portfolio_ProjectCount: '{count} Projeto{plural}',
    Portfolio_OnTrackSummary: '{count} Dentro do Prazo',
    Portfolio_AtRiskSummary: '{count} Em Risco',
    Portfolio_OverdueSummary: '{count} Em Atraso',
    Portfolio_DoneSummary: '{count} Concluído',
    Portfolio_SortLabel: 'Ordenar:',
    Portfolio_SortAZ: 'A-Z',
    Portfolio_SortHealth: 'Saúde',
    Portfolio_SortStatus: 'Estado',
    Portfolio_SortCompletion: 'Conclusão',
    Portfolio_RefreshTitle: 'Atualizar',
    Portfolio_RefreshButton: 'Atualizar',
    Portfolio_LoadingStats: 'A carregar estatísticas…',
    Portfolio_EmptyTitle: 'Ainda não existem projetos',
    Portfolio_CreateFirstProject: '+ Criar Primeiro Projeto',
    Portfolio_StatsUnavailable: 'Estatísticas indisponíveis',
    Portfolio_StatsUnavailableDetail: 'Não foi possível carregar as estatísticas deste projeto.',
    Portfolio_OverallProgressLabel: 'Progresso Global',
    Portfolio_TaskCountDone: 'Concluídas',
    Portfolio_TaskCountActive: 'Ativas',
    Portfolio_TaskCountAtRisk: 'Em Risco',
    Portfolio_TaskCountOverdue: 'Em Atraso',
    Portfolio_ViewGanttLink: 'Ver Gantt →',
    Portfolio_TodayTooltip: 'Hoje',

    // ── Task panel ──
    TaskPanel_EditHeader: 'Editar: {taskTitle}',
    TaskPanel_NewTaskHeader: 'Nova Tarefa',
    TaskPanel_TabBasic: 'Básico',
    TaskPanel_TabDetails: 'Detalhes',
    TaskPanel_TabLinks: 'Ligações',
    TaskPanel_ProjectLabelPrefix: 'Projeto: ',
    TaskPanel_TaskNameLabel: 'Nome da Tarefa',
    TaskPanel_TaskNamePlaceholder: 'Introduza o nome da tarefa',
    TaskPanel_TaskNameRequired: 'O nome da tarefa é obrigatório',
    TaskPanel_DescriptionLabel: 'Descrição',
    TaskPanel_DescriptionPlaceholder: 'Introduza a descrição',
    TaskPanel_StartDateLabel: 'Data de Início',
    TaskPanel_DueDateLabel: 'Data de Conclusão',
    TaskPanel_DueDateError: 'A data de conclusão deve ser igual ou posterior à data de início',
    TaskPanel_StatusLabel: 'Estado',
    TaskPanel_PriorityLabel: 'Prioridade',
    TaskPanel_PercentCompleteLabel: '% Concluído: {percent}%',
    TaskPanel_AssignedToLabel: 'Atribuído a',
    TaskPanel_AssignedToPlaceholder: 'Pesquisar pessoas…',
    TaskPanel_PhaseLabel: 'Fase',
    TaskPanel_PhasePlaceholder: 'Introduza o nome da fase',
    TaskPanel_PhaseHint: 'Agrupa tarefas nas vistas de Gantt e de Lista.',
    TaskPanel_MilestoneLabel: 'Marco',
    TaskPanel_MilestoneOnText: 'Sim',
    TaskPanel_MilestoneOffText: 'Não',
    TaskPanel_CustomBarColorLabel: 'Cor Personalizada da Barra',
    TaskPanel_CustomBarColorOptionalSuffix: ' (opcional)',
    TaskPanel_AutoColorHint: 'Cor automática a partir das definições de estado/prioridade/fase.',
    TaskPanel_NotesLabel: 'Notas',
    TaskPanel_NotesPlaceholder: 'Introduza notas',
    TaskPanel_ParentTaskLabel: 'Tarefa-Mãe',
    TaskPanel_ParentTaskNone: '(nenhuma)',
    TaskPanel_ParentTaskHasChildrenHint: 'Esta tarefa tem subtarefas e não pode ter uma tarefa-mãe própria.',
    TaskPanel_ParentTaskHint: 'Aninhe esta tarefa sob outra como subtarefa.',
    TaskPanel_DependsOnLabel: 'Depende De',
    TaskPanel_RemoveDependencyTitle: 'Remover dependência de "{taskTitle}"',
    TaskPanel_AddDependencyPlaceholder: 'Adicionar uma dependência…',
    TaskPanel_SelectATaskOption: 'Selecione uma tarefa…',
    TaskPanel_DependsOnHint: 'A tarefa não pode começar enquanto estas não estiverem concluídas.',
    TaskPanel_SavingLabel: 'A guardar…',
    TaskPanel_CreatingLabel: 'A criar…',
    TaskPanel_SaveChangesButton: 'Guardar Alterações',
    TaskPanel_CreateTaskButton: 'Criar Tarefa',
    TaskPanel_CancelButton: 'Cancelar',
    TaskPanel_DismissAriaLabel: 'Dispensar',
    TaskPanel_DiscardUnsavedChangesConfirm: 'Rejeitar alterações não guardadas?',
    TaskPanel_SaveFallbackError: 'Não foi possível guardar a tarefa.',

    // ── Project panel ──
    ProjectPanel_EditHeader: 'Editar Projeto',
    ProjectPanel_NewHeader: 'Novo Projeto',
    ProjectPanel_ProjectNameLabel: 'Nome do Projeto',
    ProjectPanel_ProjectNamePlaceholder: 'Introduza o nome do projeto',
    ProjectPanel_ProjectNameRequired: 'O nome do projeto é obrigatório',
    ProjectPanel_DescriptionLabel: 'Descrição',
    ProjectPanel_DescriptionPlaceholder: 'Introduza a descrição',
    ProjectPanel_ProjectColorLabel: 'Cor do Projeto',
    ProjectPanel_StatusLabel: 'Estado',
    ProjectPanel_StartDateLabel: 'Data de Início',
    ProjectPanel_DueDateLabel: 'Data de Conclusão',
    ProjectPanel_DueDateError: 'A data de conclusão deve ser igual ou posterior à data de início',
    ProjectPanel_WhatHappensNextTitle: 'O que acontece a seguir?',
    ProjectPanel_WhatHappensNextBody: 'Poderá adicionar tarefas, configurar fases e acompanhar o progresso assim que o projeto for criado.',
    ProjectPanel_SavingLabel: 'A guardar…',
    ProjectPanel_CreatingLabel: 'A criar…',
    ProjectPanel_SaveChangesButton: 'Guardar Alterações',
    ProjectPanel_CreateProjectButton: 'Criar Projeto',
    ProjectPanel_CancelButton: 'Cancelar',
    ProjectPanel_DismissAriaLabel: 'Dispensar',
    ProjectPanel_DiscardUnsavedChangesConfirm: 'Rejeitar alterações não guardadas?',
    ProjectPanel_SaveFallbackError: 'Não foi possível guardar o projeto.',

    // ── Import panel ──
    ImportPanel_SourceExcelTitle: 'Ficheiro Excel / CSV',
    ImportPanel_SourceExcelSubtitle: 'Importar tarefas de uma folha de cálculo',
    ImportPanel_SourcePlannerTitle: 'Microsoft Planner',
    ImportPanel_SourcePlannerSubtitle: 'Importar tarefas de um plano do Planner',
    ImportPanel_ClickToBrowse: 'Clique para procurar',
    ImportPanel_DragDropSuffix: ' ou arraste e largue',
    ImportPanel_SupportedExtensions: 'Suporta .xlsx, .xls, .csv',
    ImportPanel_RowsColsSummary: '{rows} linhas, {cols} colunas detetadas',
    ImportPanel_LoadingPlannerPlans: 'A carregar planos do Planner…',
    ImportPanel_PlannerLoadError: 'Não foi possível carregar os planos do Planner.',
    ImportPanel_PlannerPermissionsHintPrefix: 'Certifique-se de que tem acesso ao Planner e de que ',
    ImportPanel_PlannerPermissionsHintEmphasis: 'Tarefas do Planner e do To Do',
    ImportPanel_PlannerPermissionsHintSuffix: ' está disponível neste site.',
    ImportPanel_NoPlannerPlansFoundTitle: 'Nenhum plano do Planner encontrado',
    ImportPanel_NoPlannerPlansFoundBody: 'Pode não ter acesso a nenhum plano do Planner, ou não existe nenhum para esta conta.',
    ImportPanel_TaskCountFoundIn: '{count} tarefas encontradas em "{planName}"',
    ImportPanel_ProjectDetailsIntroPrefix: 'A importar para ',
    ImportPanel_ProjectDetailsIntroSuffix: '. Reveja os detalhes do projeto abaixo.',
    ImportPanel_ProjectNameLabel: 'Nome do Projeto',
    ImportPanel_DescriptionLabel: 'Descrição',
    ImportPanel_StatusLabel: 'Estado',
    ImportPanel_ColorLabel: 'Cor',
    ImportPanel_MapIntro: 'Associe as colunas do seu ficheiro aos campos da tarefa.',
    ImportPanel_CreatingProjectStatus: 'A criar projeto…',
    ImportPanel_ImportingTasksStatus: 'A importar tarefas…',
    ImportPanel_ProgressLabel: '{done} de {total}',
    ImportPanel_CouldNotCreateProject: 'Não foi possível criar o projeto.',
    ImportPanel_ImportCompletedWithErrors: 'Importação concluída com {count} erro(s).',
    ImportPanel_ProjectCreatedSuccess: 'Projeto criado com sucesso!',
    ImportPanel_ImportSuccessful: 'Importação bem-sucedida!',
    ImportPanel_TasksAddedTo: '{count} tarefas adicionadas a "{projectName}"',
    ImportPanel_FailedRowsLabel: 'Linhas com falha:',
    ImportPanel_CloseButton: 'Fechar',
    ImportPanel_OpenProjectButton: 'Abrir Projeto',
    ImportPanel_ViewImportedTasksButton: 'Ver Tarefas Importadas',
    ImportPanel_NextMapColumnsButton: 'Seguinte: Associar Colunas',
    ImportPanel_ImportNTasksButton: 'Importar {count} Tarefas',
    ImportPanel_BackButton: 'Anterior',
    ImportPanel_CancelButton: 'Cancelar',
    ImportPanel_NextButton: 'Seguinte',
    ImportPanel_StepSource: 'Origem',
    ImportPanel_StepProject: 'Projeto',
    ImportPanel_StepMap: 'Associar',
    ImportPanel_StepImport: 'Importar',
    ImportPanel_StepDone: 'Concluído',
    ImportPanel_ImportAsNewProjectHeader: 'Importar Ficheiro como Novo Projeto',
    ImportPanel_ImportIntoProjectHeader: 'Importar Tarefas para {projectName}',
    ImportPanel_CouldNotParseFile: 'Não foi possível processar o ficheiro.',
    ImportPanel_CouldNotLoadPlannerTasks: 'Não foi possível carregar as tarefas deste plano.',
    ImportPanel_CouldNotCreateProjectDetail: 'Não foi possível criar o projeto: {detail}',
    ImportPanel_CouldNotLinkDependencies: 'Não foi possível associar as dependências: {detail}',
    ImportPanel_UnknownError: 'erro desconhecido',

    // ── Column mapper (import) ──
    ColumnMapper_TaskNameRequiredBanner: 'O Nome da Tarefa tem de estar associado para continuar.',
    ColumnMapper_SkippedColumnsBanner: '{count} coluna(s) serão ignoradas.',
    ColumnMapper_SourceColumnHeader: 'Coluna de Origem',
    ColumnMapper_TargetFieldHeader: 'Campo de Destino',
    ColumnMapper_StatusHeader: 'Estado',
    ColumnMapper_SkippedBadge: 'Ignorada',
    ColumnMapper_AutoMappedBadge: 'Associada automaticamente',
    ColumnMapper_SetBadge: 'Definida',
    ColumnMapper_PreviewTitle: 'Pré-visualização: {columnName}',
    ColumnMapper_EmptyCellDash: '—',

    // ── Import field display names / ImportService ──
    ImportField_TaskName: 'Nome da Tarefa',
    ImportField_StartDate: 'Data de Início',
    ImportField_DueDate: 'Data de Conclusão',
    ImportField_Status: 'Estado',
    ImportField_Priority: 'Prioridade',
    ImportField_AssignedTo: 'Atribuído a',
    ImportField_AssignedToEmail: 'E-mail do Atribuído',
    ImportField_PercentComplete: '% Concluído',
    ImportField_Phase: 'Fase',
    ImportField_Description: 'Descrição',
    ImportField_Notes: 'Notas',
    ImportField_IsMilestone: 'É Marco',
    ImportField_Dependencies: 'Dependências',
    ImportField_SkipColumn: '(Ignorar esta coluna)',
    ImportService_EmptyFileError: 'O ficheiro parece estar vazio ou não tem linhas de dados.',
    ImportService_ReadErrorDetail: 'Não foi possível ler o ficheiro: {detail}.',
    ImportService_FileReadError: 'Erro de leitura do ficheiro.',
    ImportService_RowError: 'Linha {rowNum} ("{title}"): {error}',
    ImportService_AmbiguousDependency: 'A dependência "{name}" corresponde a mais do que um título de tarefa — ignorada.',
    ImportService_LinkDependencyError: 'Não foi possível associar as dependências da tarefa {taskId}: {error}',

    // ── Health labels (shared: healthUtils.ts and ExportService.ts both use this set; also replaces the duplicated Export_PortfolioHealthLabel* keys) ──
    Health_Done: 'Concluído',
    Health_OnTrack: 'Dentro do Prazo',
    Health_AtRisk: 'Em Risco',
    Health_Overdue: 'Em Atraso',

    // ── Status / Priority display labels (DISPLAY-ONLY — stored SharePoint Choice values remain unchanged/English) ──
    Status_NotStarted: 'Não Iniciada',
    Status_InProgress: 'Em Curso',
    Status_Completed: 'Concluída',
    Status_OnHold: 'Em Pausa',
    Status_Cancelled: 'Cancelada',
    Priority_Critical: 'Crítica',
    Priority_High: 'Alta',
    Priority_Medium: 'Média',
    Priority_Low: 'Baixa',
    ProjectStatus_Planning: 'Planeamento',
    ProjectStatus_Active: 'Ativo',
    ProjectStatus_OnHold: 'Em Pausa',
    ProjectStatus_Completed: 'Concluído',
    ProjectStatus_Cancelled: 'Cancelado',

    // ── Shell (SmartGantt.tsx) ──
    SmartGantt_LoadingProjects: 'A carregar projetos…',
    SmartGantt_UnableToLoad: 'Não foi possível carregar',
    SmartGantt_RetryButton: 'Tentar Novamente',
    SmartGantt_NoProjectsYet: 'Ainda não existem projetos',
    SmartGantt_NoProjectsSubtitle: 'Crie o seu primeiro projeto para começar.',
    SmartGantt_CreateFirstProjectButton: '+ Criar Primeiro Projeto',
    SmartGantt_ImportFromExcelButton: '📥 Importar do Excel',
    SmartGantt_LoadingTasks: 'A carregar tarefas…',
    SmartGantt_DismissAriaLabel: 'Dispensar',
    SmartGantt_DeleteTaskDialogTitle: 'Eliminar Tarefa',
    SmartGantt_DeleteTaskDialogSubtext: 'Tem a certeza de que pretende eliminar "{taskTitle}"? Esta ação não pode ser anulada.',
    SmartGantt_DeleteButton: 'Eliminar',
    SmartGantt_CancelButton: 'Cancelar',
    SmartGantt_ArchiveProjectDialogTitle: 'Arquivar Projeto',
    SmartGantt_ArchiveProjectDialogSubtext: 'Arquivar "{projectTitle}"? Pode desarquivá-lo mais tarde.',
    SmartGantt_ArchiveButton: 'Arquivar',
    SmartGantt_SendToRecycleBinDialogTitle: 'Enviar para a Reciclagem',
    SmartGantt_SendToRecycleBinDialogSubtext: 'Enviar "{projectTitle}" para a reciclagem do site?',
    SmartGantt_SendToRecycleBinButton: 'Enviar para a Reciclagem',
    SmartGantt_FailedLoadProjects: 'Falha ao carregar os projetos. Verifique as permissões do site.',
    SmartGantt_FailedLoadTasks: 'Falha ao carregar as tarefas deste projeto.',
    SmartGantt_FailedLoadPortfolioStats: 'Falha ao carregar as estatísticas do portefólio.',
    SmartGantt_CouldNotSaveProject: 'Não foi possível guardar o projeto: {message}',
    SmartGantt_CouldNotDeleteProject: 'Não foi possível eliminar o projeto: {message}',
    SmartGantt_CouldNotArchiveProject: 'Não foi possível arquivar o projeto: {message}',
    SmartGantt_CouldNotUnarchiveProject: 'Não foi possível desarquivar o projeto: {message}',
    SmartGantt_CouldNotSaveTask: 'Não foi possível guardar a tarefa: {message}',
    SmartGantt_CouldNotDeleteTask: 'Não foi possível eliminar a tarefa: {message}',
    SmartGantt_ImageExportFailed: 'Falha na exportação da imagem: {message}',
    SmartGantt_PowerPointExportFailed: 'Falha na exportação para PowerPoint: {message}',
    SmartGantt_PortfolioExportFailed: 'Falha na exportação do portefólio: {message}',
    SmartGantt_CouldNotUpdateTask: 'Não foi possível atualizar a tarefa: {message}',

    // ── Common ──
    ColorSwatch_AutoColorAriaLabel: 'Cor automática',
    ColorSwatch_CustomColorAriaLabel: 'Cor personalizada',
    ColorSwatch_PickCustomColorTitle: 'Escolher uma cor personalizada',

    // ── Export (Excel / PowerPoint) ──
    Export_ColTaskName: 'Nome da Tarefa',
    Export_ColPhase: 'Fase',
    Export_ColStartDate: 'Data de Início',
    Export_ColDueDate: 'Data de Conclusão',
    Export_ColStatus: 'Estado',
    Export_ColPriority: 'Prioridade',
    Export_ColAssignedTo: 'Atribuído a',
    Export_ColAssignedToEmail: 'E-mail do Atribuído',
    Export_ColPercentComplete: '% Concluído',
    Export_ColIsMilestone: 'É Marco',
    Export_ColDescription: 'Descrição',
    Export_ColNotes: 'Notas',
    Export_Yes: 'Sim',
    Export_No: 'Não',
    Export_SheetNameTasks: 'Tarefas',
    Export_ExcelFileSuffix: ' - Tarefas.xlsx',
    Export_TaskNameColumnLabel: 'NOME DA TAREFA',
    Export_ExportedDateLabel: 'Exportado em {date}',
    Export_ProjectReportLabel: 'RELATÓRIO DO PROJETO',
    Export_StatusLine: 'Estado: {status}',
    Export_DateRangeSeparator: ' a ',
    Export_ProjectManagerLine: 'Gestor de Projeto: {name}',
    Export_GeneratedDateLine: 'Gerado em {date}',
    Export_ProjectSummaryTitle: 'Resumo do Projeto',
    Export_StatTotalTasks: 'Total de Tarefas',
    Export_StatCompleted: 'Concluídas',
    Export_StatInProgress: 'Em Curso',
    Export_StatOnHold: 'Em Pausa',
    Export_StatNotStarted: 'Não Iniciadas',
    Export_OverallProgressLine: 'Progresso Global',
    Export_OverallProgressPercent: '{percent}%',
    Export_StatusBreakdownTitle: 'Distribuição por Estado',
    Export_StatusBreakdownRow: '{status}: {count} ({percent}%)',
    Export_GanttTimelineTitle: 'Cronograma Gantt',
    Export_SummaryRecentActivityTitle: 'Atividade Recente',
    Export_ProjectOverviewLabel: 'Visão Geral do Projeto',
    Export_DetailStatusLabel: 'Estado',
    Export_DetailStartDateLabel: 'Data de Início',
    Export_DetailDueDateLabel: 'Data de Conclusão',
    Export_DetailProjectManagerLabel: 'Gestor de Projeto',
    Export_Past7DaysLabel: 'Últimos 7 Dias',
    Export_NoActivityMessage: 'Sem atividade recente.',
    Export_CompletedThisWeekHeader: 'Concluídas Esta Semana ({count})',
    Export_NewBadge: 'NOVO  ',
    Export_CompletedPercentLine: '{percent}% concluído',
    Export_MoreItemsSuffix: '+ {count} mais',
    Export_InProgressUpdatedHeader: 'Em Curso / Atualizadas',
    Export_StatusPercentLine: '{status} — {percent}%',
    Export_PortfolioReportLabel: 'RELATÓRIO DE PORTEFÓLIO',
    Export_PortfolioOverviewTitle: 'Visão Geral do Portefólio',
    Export_ProjectsCountLine: '{count} Projetos',
    Export_HealthSummaryOnTrack: '{count} Dentro do Prazo',
    Export_HealthSummaryAtRisk: '{count} Em Risco',
    Export_HealthSummaryOverdue: '{count} Em Atraso',
    Export_ProjectsSummaryHeader: 'Resumo dos Projetos',
    Export_TableProject: 'Projeto',
    Export_TableStatus: 'Estado',
    Export_TableHealth: 'Saúde',
    Export_TableTotal: 'Total',
    Export_TableDone: 'Concluídas',
    Export_TableActive: 'Ativas',
    Export_TableAtRisk: 'Em Risco',
    Export_TableOverdue: 'Em Atraso',
    Export_TablePctDone: '% Concluído',
    Export_TableDueDate: 'Data de Conclusão',
    Export_PortfolioSummaryFileName: 'Resumo do Portefólio.xlsx',
    Export_PortfolioReportFileName: 'Relatório do Portefólio.pptx',
    Export_ProjectReportFileName: 'Relatório de {projectName}.pptx',
    Export_UnavailableLabel: 'Indisponível',
    Export_SheetNamePortfolio: 'Portefólio',
    Export_ColStart: 'Início',
    Export_ColDue: 'Conclusão',
    Export_ImageGenerationFailed: 'Não foi possível gerar a imagem — o gráfico pode ser demasiado grande para ser exportado como imagem.',
    Export_DrawingContextFailed: 'Não foi possível criar um contexto de desenho para a exportação.',
    Export_SvgRenderFailed: 'Falha ao renderizar o SVG',

    // ── Added in v1.5 review ──
    Svc_TooManyDependencies: 'Esta tarefa tem demasiadas dependências para ser guardada (o limite é de cerca de 60). Remova algumas e tente novamente.',
    Svc_TaskChangedByOthers: 'Esta tarefa foi alterada por outra pessoa desde que a carregou. Atualize e tente novamente.',
    Svc_ProjectChangedByOthers: 'Este projeto foi alterado por outra pessoa desde que o abriu. Atualize e tente novamente.',
    Svc_ColumnCreateFailed: 'Não foi possível criar {count} coluna(s) na nova lista de tarefas: {detail}',
    Svc_BaselineUnavailable: 'As linhas de base não estão disponíveis para este projeto porque não foi possível adicionar as colunas de linha de base (poderá ser necessária permissão para editar a lista).',
    Svc_SubtaskReassignFailed: 'Não foi possível reatribuir as subtarefas desta tarefa antes de a eliminar: {detail}',
    Svc_UnresolvedDependency: 'Linha {row} ("{title}"): não foi possível associar a dependência "{name}" a uma tarefa importada.',
    Svc_SelfDependency: 'Linha {row} ("{title}"): a dependência "{name}" aponta para a própria tarefa e foi ignorada.',
    Svc_ColId: 'ID',
    Svc_ColDependencies: 'Dependências',
    Svc_ColBaselineStart: 'Início da linha de base',
    Svc_ColBaselineDue: 'Data limite da linha de base',
    Svc_CsvFileSuffix: ' - Tasks.csv',
    Svc_IcsFileSuffix: ' - Milestones.ics',
    Svc_PortfolioCsvFileName: 'Portfolio Summary.csv',
    Svc_PP_DisplayGroup: 'Predefinições',
    Svc_PP_DefaultView: 'Vista predefinida',
    Svc_PP_ViewGantt: 'Gantt',
    Svc_PP_ViewList: 'Lista',
    Svc_PP_ViewKanban: 'Kanban',
    Svc_PP_ViewDashboard: 'Painel',
    Svc_PP_ViewPortfolio: 'Portefólio',
    Svc_PP_DefaultZoom: 'Zoom predefinido',
    Svc_PP_ZoomDay: 'Dia',
    Svc_PP_ZoomWeek: 'Semana',
    Svc_PP_ZoomMonth: 'Mês',
    Svc_PP_ZoomQuarter: 'Trimestre',
    Svc_PP_CalendarGroup: 'Calendário de trabalho',
    Svc_PP_DaySun: 'O domingo é dia útil',
    Svc_PP_DayMon: 'A segunda-feira é dia útil',
    Svc_PP_DayTue: 'A terça-feira é dia útil',
    Svc_PP_DayWed: 'A quarta-feira é dia útil',
    Svc_PP_DayThu: 'A quinta-feira é dia útil',
    Svc_PP_DayFri: 'A sexta-feira é dia útil',
    Svc_PP_DaySat: 'O sábado é dia útil',
    Svc_PP_Holidays: 'Feriados (datas não úteis)',
    Svc_PP_HolidaysHint: 'Uma data por linha, no formato aaaa-MM-dd (por exemplo, 2026-12-25).',
    Gantt_TimelineAriaLabel: 'Cronograma das tarefas',
    Gantt_DragLabel: '{start} → {end} ({days} d)',
    Gantt_KeyboardMoveAnnouncement: '{taskTitle}: de {startDate} a {dueDate}',
    Gantt_KeyboardHint: 'Prima Enter para abrir a tarefa. As teclas de seta para a esquerda e para a direita movem-na um dia útil. Shift com as setas altera a data de fim.',
    Gantt_ParentCycleTooltip: 'Esta tarefa faz parte de uma cadeia circular de tarefa principal e subtarefas, pelo que é apresentada ao nível superior',
    Gantt_CollapseAll: 'Recolher todas as fases',
    Gantt_ExpandAll: 'Expandir todas as fases',
    Gantt_BaselineTooltip: 'Linha de base: {start} → {due}',
    Gantt_VarianceTooltip: 'Desvio de conclusão: {days} dias em relação à linha de base',
    Gantt_LinkHandleTitle: 'Arraste para outra tarefa para criar uma dependência',
    Toolbar_FitToProject: 'Ajustar',
    Toolbar_FitToProjectTitle: 'Ajustar o zoom a todo o projeto',
    Toolbar_UndoTitle: 'Anular (Ctrl+Z)',
    Toolbar_RedoTitle: 'Refazer (Ctrl+Y)',
    Toolbar_ExportCsv: '📄 Exportar Tarefas para CSV',
    Toolbar_ExportIcs: '📅 Exportar Marcos (iCal)',
    Toolbar_Print: '🖨 Imprimir / Guardar como PDF',
    Toolbar_SetBaseline: '📐 Definir Linha de Base…',
    Toolbar_CopyLink: '🔗 Copiar Ligação',
    Toolbar_CopyLinkTitle: 'Copiar uma ligação para esta vista (projeto, vista, zoom e filtros)',
    App_UndoButton: 'Anular',
    App_Undone: 'Alteração anulada.',
    App_Redone: 'Alteração refeita.',
    App_DependentsMovedOne: '1 tarefa dependente foi movida.',
    App_DependentsMovedMany: '{count} tarefas dependentes foram movidas.',
    App_TaskConflict: 'Esta tarefa foi alterada por outra pessoa. As tarefas mais recentes foram recarregadas; reveja-as e tente novamente.',
    App_DependencyCycle: 'Essa ligação criaria uma dependência circular.',
    App_DependencyExists: 'Essas tarefas já estão ligadas.',
    App_LinkCopied: 'Ligação copiada para a área de transferência.',
    App_LinkCopyFailed: 'Não foi possível copiar a ligação: {message}',
    App_PopupBlocked: 'A janela de impressão foi bloqueada. Permita os pop-ups para este site e tente novamente.',
    App_SetBaselineDialogTitle: 'Definir Linha de Base',
    App_SetBaselineDialogSubtext: 'Guardar as datas atuais de início e de fim de todas as {count} tarefas como linha de base? Qualquer linha de base existente será substituída.',
    App_SetBaselineButton: 'Definir Linha de Base',
    App_BaselineSaved: 'Linha de base guardada.',
    App_BaselineFailed: 'Não foi possível guardar a linha de base: {message}',
    App_CsvExportFailed: 'A exportação para CSV falhou: {message}',
    App_IcsExportFailed: 'A exportação do calendário falhou: {message}',
    App_BulkDeleteDialogTitle: 'Eliminar Tarefas',
    App_BulkDeleteDialogSubtext: 'Tem a certeza de que pretende eliminar {count} tarefas? Esta ação não pode ser anulada.',
    Common_PeoplePicker_ClearAriaLabel: 'Limpar',
    Common_PeoplePicker_DirectoryHeader: 'Pessoas no diretório',
    Common_PeoplePicker_EmailLabel: 'E-mail (opcional)',
    Common_PeoplePicker_EmailPlaceholder: 'name@company.com',
    Common_PeoplePicker_ExternalHint: 'Não está no diretório. Guardado como texto livre.',
    Common_PeoplePicker_InvalidEmail: 'Introduza um endereço de e-mail válido.',
    Common_PeoplePicker_ListAriaLabel: 'Sugestões de pessoas',
    Common_PeoplePicker_RecentHeader: 'Usados recentemente',
    Common_PeoplePicker_ResultsAnnouncement: '{count} sugestões disponíveis',
    Common_PeoplePicker_Searching: 'A pesquisar…',
    Common_PeoplePicker_UseExternal: 'Utilizar “{name}” (externo / não está no diretório)',
    Import_Mapper_PreviewFirstRows: 'Pré-visualização (primeiras {count} linhas)',
    Import_Mapper_RequiredLegend: 'Campo obrigatório',
    Import_Mapper_RequiredMarkerLabel: 'Obrigatório',
    Import_Mapper_SelectAriaLabel: 'Campo de destino para a coluna {columnName}',
    Import_Panel_DateOrderAuto: 'Deteção automática',
    Import_Panel_DateOrderDMY: 'Dia/Mês/Ano (31/12/2026)',
    Import_Panel_DateOrderDetected: 'Detetado no seu ficheiro: {order}.',
    Import_Panel_DateOrderHint: 'Aplica-se a datas escritas com números, como 03/04/2026.',
    Import_Panel_DateOrderLabel: 'Ordem da data',
    Import_Panel_DateOrderMDY: 'Mês/Dia/Ano (12/31/2026)',
    Import_Panel_DropZoneAriaLabel: 'Escolha um ficheiro para importar. Prima Enter para procurar.',
    Import_Panel_DropZoneChangeAriaLabel: 'Ficheiro selecionado: {fileName}. Prima Enter para escolher outro ficheiro.',
    Import_Panel_FailedCount: '{count} com falha',
    Import_Panel_NewProjectIntroMany: 'Será criado um novo projeto e todas as {count} tarefas serão importadas para o mesmo. Pode alterar estes detalhes em qualquer altura após a importação.',
    Import_Panel_NewProjectIntroOne: 'Será criado um novo projeto e {count} tarefa será importada para o mesmo. Pode alterar estes detalhes em qualquer altura após a importação.',
    Import_Panel_PlanAriaLabel: '{planName}, {groupName}',
    Import_Panel_ProblemEndBeforeStart: 'A data limite é anterior à data de início',
    Import_Panel_ProblemInvalidDueDate: 'A data limite "{value}" não é uma data válida',
    Import_Panel_ProblemInvalidStartDate: 'A data de início "{value}" não é uma data válida',
    Import_Panel_ProblemMissingTitle: 'O nome da tarefa está em falta',
    Import_Panel_ProgressLabelWithPercent: '{done} de {total} ({percent}%)',
    Import_Panel_SkipInvalidRows: 'Ignorar linhas com problemas',
    Import_Panel_SuccessWithWarningsMany: 'Importação bem-sucedida com {count} avisos.',
    Import_Panel_SuccessWithWarningsOne: 'Importação bem-sucedida com {count} aviso.',
    Import_Panel_ValidationHeader: 'Linhas com problemas',
    Import_Panel_ValidationMore: '…e mais {count}',
    Import_Panel_ValidationRow: 'Linha {rowNum}: {problem}',
    Import_Panel_ValidationSummaryMany: '{count} linhas têm problemas',
    Import_Panel_ValidationSummaryOne: '{count} linha tem um problema',
    Import_Panel_WarningsLabel: 'Avisos ({count}):',
    Panel_Project_ManagerLabel: 'Gestor do Projeto',
    Panel_Project_ManagerPlaceholder: 'Pesquise pessoas ou escreva um nome…',
    Panel_Task_BaselineDueLabel: 'Fim da linha de base',
    Panel_Task_BaselineHeader: 'Linha de base',
    Panel_Task_BaselineStartLabel: 'Início da linha de base',
    Panel_Task_DepTypeFF: 'Fim a Fim (FF)',
    Panel_Task_DepTypeFS: 'Fim a Início (FS)',
    Panel_Task_DepTypeSF: 'Início a Fim (SF)',
    Panel_Task_DepTypeSS: 'Início a Início (SS)',
    Panel_Task_LagAriaLabel: 'Atraso em dias úteis para {taskTitle}',
    Panel_Task_LagHint: 'O atraso é em dias úteis. Utilize um número negativo para antecipação.',
    Panel_Task_LinkTypeAriaLabel: 'Tipo de ligação para {taskTitle}',
    Panel_Task_VarianceEarlier: '{days} dia(s) útil(eis) mais cedo',
    Panel_Task_VarianceLater: '{days} dia(s) útil(eis) mais tarde',
    Panel_Task_VarianceOnBaseline: 'na linha de base',
    View_Dashboard_BurndownActual: 'Real',
    View_Dashboard_BurndownAria: 'Gráfico de burndown: {remaining} de {total} tarefas por concluir',
    View_Dashboard_BurndownHeader: 'Burndown (Tarefas Restantes)',
    View_Dashboard_BurndownIdeal: 'Ideal',
    View_Dashboard_BurndownNoData: 'Não existem tarefas com datas suficientes para desenhar um burndown.',
    View_Dashboard_CriticalPathHeader: 'Caminho Crítico  ({count})',
    View_Dashboard_PhaseDoneSummary: '{done}/{total} concluídas  •  {percent}%',
    View_Dashboard_TaskRowAriaLabel: 'Abrir tarefa {taskTitle}, {status}',
    View_Dashboard_WorkloadHeader: 'Carga de Trabalho por Responsável',
    View_Dashboard_WorkloadOpen: '{count} em aberto',
    View_Dashboard_WorkloadOverdue: '{count} em atraso',
    View_Kanban_AddTaskInColumnAriaLabel: 'Adicionar tarefa a {column}',
    View_Kanban_CollapseColumn: 'Recolher a coluna {column}',
    View_Kanban_ExpandColumn: 'Expandir a coluna {column}',
    View_Kanban_LaneHeader: '{name} ({count})',
    View_Kanban_LaneNoPhase: 'Sem fase',
    View_Kanban_LaneUnassigned: 'Não atribuído',
    View_Kanban_LanesAssignee: 'Responsável',
    View_Kanban_LanesNone: 'Nenhum',
    View_Kanban_LanesPhase: 'Fase',
    View_Kanban_SwimlanesLabel: 'Faixas',
    View_Kanban_WipEditTitle: 'Definir o limite de trabalho em curso para {column} (0 para sem limite)',
    View_Kanban_WipExceededTitle: 'Limite de WIP excedido: {count} de {limit}',
    View_Kanban_WipInputAriaLabel: 'Limite de WIP para {column}',
    View_Kanban_WipLabel: 'WIP {count}/{limit}',
    View_Kanban_WipSet: 'WIP',
    View_List_BulkAssignApply: 'Atribuir',
    View_List_BulkAssigneePlaceholder: 'Atribuir a…',
    View_List_BulkBarAriaLabel: 'Ações em massa para as tarefas selecionadas',
    View_List_BulkClear: 'Limpar seleção',
    View_List_BulkDelete: 'Eliminar selecionadas',
    View_List_BulkPercentApply: 'Definir %',
    View_List_BulkPercentPlaceholder: '% concluído',
    View_List_BulkPriorityPlaceholder: 'Definir prioridade…',
    View_List_BulkSelectedCount: '{count} selecionadas',
    View_List_BulkStatusPlaceholder: 'Definir estado…',
    View_List_ExportCsv: 'Exportar CSV',
    View_List_NonWorkingDay: 'Dia não útil',
    View_List_SelectAllAriaLabel: 'Selecionar todas as tarefas',
    View_List_SelectRowAriaLabel: 'Selecionar {taskTitle}',
    View_Portfolio_CardAriaLabel: 'Abrir projeto {projectName}, {status}',
    View_Portfolio_ClearFilters: 'Limpar filtros',
    View_Portfolio_FilteredCount: '{shown} de {total} Projetos',
    View_Portfolio_HideDone: 'Ocultar concluídos / cancelados',
    View_Portfolio_NoMatches: 'Nenhum projeto corresponde aos seus filtros.',
    View_Portfolio_ProjectCountMany: '{count} Projetos',
    View_Portfolio_ProjectCountOne: '{count} Projeto',
    View_Portfolio_SearchAriaLabel: 'Pesquisar projetos',
    View_Portfolio_SearchPlaceholder: 'Pesquisar projetos…',
    Import_Panel_CopyDetails: 'Copiar detalhes',
    Import_Panel_Copied: 'Copiado',
  };
});
