define([], function () {
  return {
    // ── Property pane ──
    PropertyPane_HeaderDescription: 'Setări Smart Gantt Chart',
    PropertyPane_GeneralGroupName: 'General',
    PropertyPane_TitleFieldLabel: 'Titlul Web Part-ului',
    WebPart_DefaultTitle: 'Smart Gantt Chart',

    // ── Toolbar ──
    Toolbar_ViewDashboard: 'Tablou de bord',
    Toolbar_ViewList: 'Listă',
    Toolbar_ViewGantt: 'Gantt',
    Toolbar_ViewKanban: 'Kanban',
    Toolbar_ZoomDay: 'Zi',
    Toolbar_ZoomWeek: 'Săptămână',
    Toolbar_ZoomMonth: 'Lună',
    Toolbar_ZoomQuarter: 'Trimestru',
    Toolbar_SelectProjectAriaLabel: 'Selectați proiectul',
    Toolbar_PortfolioLabel: 'Portofoliu',
    Toolbar_SelectAProject: 'Selectați un Proiect',
    Toolbar_AllProjectsSubtext: 'Toate proiectele',
    Toolbar_NoProjectsYet: 'Încă nu există proiecte',
    Toolbar_ArchivedBadge: 'Arhivat',
    Toolbar_ShowArchivedProjects: 'Afișați proiectele arhivate',
    Toolbar_NewProject: '+ Proiect Nou',
    Toolbar_ImportFileAsNewProject: '📥 Importați Fișier ca Proiect Nou…',
    Toolbar_AddTask: '+ Adăugați Sarcină',
    Toolbar_EditProject: 'Editați Proiectul',
    Toolbar_OptionsButton: '⚙ Opțiuni',
    Toolbar_MoreOptionsTitle: 'Mai multe opțiuni',
    Toolbar_ExportToExcel: '📊 Exportați în Excel',
    Toolbar_ExportToPowerPoint: '📑 Exportați în PowerPoint',
    Toolbar_ScrollToTodayTitle: 'Derulați la ziua de azi',
    Toolbar_TodayButton: '◉ Astăzi',
    Toolbar_ImportTasks: '📥 Importați Sarcini…',
    Toolbar_ExportAsImage: '🖼 Exportați ca Imagine (PNG)',
    Toolbar_UnarchiveProject: '📂 Dezarhivați Proiectul',
    Toolbar_ArchiveProject: '🗄️ Arhivați Proiectul',
    Toolbar_SendToRecycleBin: '🗑️ Trimiteți la Coșul de Reciclare',

    // ── Filter bar ──
    FilterBar_ClearOption: 'Ștergeți',
    FilterBar_DueAny: 'Orice dată scadentă',
    FilterBar_DueOverdue: 'Restant',
    FilterBar_DueToday: 'Scadent azi',
    FilterBar_DueWeek: 'Scadent în 7 zile',
    FilterBar_SearchPlaceholder: 'Căutați sarcini…',
    FilterBar_SearchAriaLabel: 'Căutați sarcini',
    FilterBar_StatusChipLabel: 'Stare',
    FilterBar_PriorityChipLabel: 'Prioritate',
    FilterBar_AssigneeChipLabel: 'Responsabil',
    FilterBar_PhaseChipLabel: 'Fază',
    FilterBar_DueDateAriaLabel: 'Filtrați după data scadentă',
    FilterBar_MatchCount: '{matchCount} din {totalCount}',
    FilterBar_ClearFilters: '✕ Ștergeți filtrele',
    FilterBar_ChipLabelWithCount: '{label} ({count}) ▾',
    FilterBar_ChipLabelNoCount: '{label} ▾',

    // ── Gantt view ──
    Gantt_TaskColumnHeader: 'Sarcină',
    Gantt_DurationColumnHeader: 'Dur.',
    Gantt_AddTaskButton: '+ Adăugați Sarcină',
    Gantt_EmptyTitle: 'Încă nu există sarcini',
    Gantt_EmptySubtitle: 'Adăugați sarcini pentru a le vedea în diagrama Gantt.',
    Gantt_AddFirstTask: '+ Adăugați Prima Sarcină',
    Gantt_ImportTasksButton: '📥 Importați Sarcini',
    Gantt_EditTitle: 'Editați',
    Gantt_DeleteTitle: 'Ștergeți',
    Gantt_EditTaskAriaLabel: 'Editați sarcina {taskTitle}',
    Gantt_DeleteTaskAriaLabel: 'Ștergeți sarcina {taskTitle}',
    Gantt_ExpandPhaseAriaLabel: '{action} faza {phase}',
    Gantt_ExpandAction: 'Extindeți',
    Gantt_CollapseAction: 'Restrângeți',
    Gantt_DependencyViolationTooltip: 'Începută înainte ca toate dependențele să fi fost finalizate',
    Gantt_MilestoneAriaLabel: '{taskTitle}, reper, {date}',
    Gantt_BarAriaLabel: '{taskTitle}, {startDate} până la {dueDate}, {percent}% finalizat',
    Gantt_PercentCompleteTooltip: '{value}% finalizat',

    // ── Gantt options/settings panel ──
    GanttSettings_PanelHeader: '⚙ Opțiuni',
    GanttSettings_ColorCodingSection: 'Codificare prin culori',
    GanttSettings_ByStatus: 'După stare',
    GanttSettings_ByPriority: 'După prioritate',
    GanttSettings_ByPhase: 'După fază',
    GanttSettings_ByHealth: 'După stare de sănătate',
    GanttSettings_HeaderColorSection: 'Culoarea antetului',
    GanttSettings_ThemeDark: 'Întunecat',
    GanttSettings_ThemeNavy: 'Bleumarin',
    GanttSettings_ThemeTeal: 'Turcoaz',
    GanttSettings_ThemePurple: 'Mov',
    GanttSettings_ThemeLight: 'Luminos',
    GanttSettings_HeaderLabelsSection: 'Etichete antet',
    GanttSettings_WeekLabelDates: 'Date',
    GanttSettings_WeekLabelDatesDesc: '3 iun, 10 iun…',
    GanttSettings_WeekLabelProject: 'Săptămâni ale proiectului',
    GanttSettings_WeekLabelProjectDesc: 'S1, S2…',
    GanttSettings_WeekLabelIso: 'Săptămâni calendaristice',
    GanttSettings_WeekLabelIsoDesc: 'S23, S24…',
    GanttSettings_ProjectWeeksHint: 'Săptămâna 1 începe de luni, din cea mai timpurie sarcină — ideal pentru prezentări.',
    GanttSettings_BarStyleSection: 'Stil bară',
    GanttSettings_BarStyleGradient: 'Degrade',
    GanttSettings_BarStyleFlat: 'Uniform',
    GanttSettings_RowHeightSection: 'Înălțimea rândului',
    GanttSettings_HeightCompact: 'Compact',
    GanttSettings_HeightNormal: 'Normal',
    GanttSettings_HeightSpacious: 'Spațios',
    GanttSettings_ShowHideSection: 'Afișare / Ascundere',
    GanttSettings_WeekendShading: 'Evidențiere weekend',
    GanttSettings_DependencyArrows: 'Săgeți de dependență',
    GanttSettings_CriticalPathAlwaysVisible: 'Traseul critic mereu vizibil',
    GanttSettings_AllOthersOnHoverOnly: 'Toate celelalte doar la survolare',
    GanttSettings_CriticalPathHighlight: 'Evidențierea traseului critic',
    GanttSettings_ProgressPercentOnBars: '% de progres pe bare',
    GanttSettings_AssigneeNameOnBars: 'Numele responsabilului pe bare',
    GanttSettings_HealthStatusBadges: 'Insigne de stare a sănătății',

    // ── List view ──
    ListView_ColTaskName: 'Denumire Sarcină',
    ListView_ColStatus: 'Stare',
    ListView_ColHealth: 'Sănătate',
    ListView_ColPriority: 'Prioritate',
    ListView_ColStart: 'Început',
    ListView_ColDue: 'Scadență',
    ListView_ColAssignedTo: 'Atribuit lui',
    ListView_ColProgress: 'Progres',
    ListView_ColPhase: 'Fază',
    ListView_ColPredecessors: 'Predecesori',
    ListView_EmptyTitle: 'Încă nu există sarcini',
    ListView_AddFirstTask: '+ Adăugați Prima Sarcină',
    ListView_AddTaskRow: '+ Adăugați Sarcină',
    ListView_Unassigned: 'Neatribuit',
    ListView_DependencyViolationTooltip: 'Începută înainte ca toate dependențele să fi fost finalizate',
    ListView_StatusAriaLabel: 'Starea sarcinii {taskTitle}',
    ListView_PriorityAriaLabel: 'Prioritatea sarcinii {taskTitle}',
    ListView_EditTaskAriaLabel: 'Editați sarcina {taskTitle}',
    ListView_DeleteTaskAriaLabel: 'Ștergeți sarcina {taskTitle}',
    ListView_EditTitle: 'Editați',
    ListView_DeleteTitle: 'Ștergeți',

    // ── Kanban view ──
    Kanban_ColumnNotStarted: 'Neînceput',
    Kanban_ColumnInProgress: 'În desfășurare',
    Kanban_ColumnOnHold: 'În așteptare',
    Kanban_ColumnCompleted: 'Finalizat',
    Kanban_ColumnCancelled: 'Anulat',
    Kanban_AddTaskButton: '+ Adăugați Sarcină',
    Kanban_EditTitle: 'Editați',
    Kanban_DeleteTitle: 'Ștergeți',
    Kanban_CardAriaLabel: '{taskTitle}, {status}. Apăsați Enter pentru a edita, săgeata Stânga sau Dreapta pentru a schimba starea.',
    Kanban_EditTaskAriaLabel: 'Editați sarcina {taskTitle}',
    Kanban_DeleteTaskAriaLabel: 'Ștergeți sarcina {taskTitle}',

    // ── Dashboard view ──
    Dashboard_TotalTasks: 'Total sarcini',
    Dashboard_Completed: 'Finalizate',
    Dashboard_InProgress: 'În desfășurare',
    Dashboard_OnHold: 'În așteptare',
    Dashboard_NotStarted: 'Neîncepute',
    Dashboard_Cancelled: 'Anulate',
    Dashboard_OverallProgress: 'Progres global',
    Dashboard_ProjectManagerLabel: 'Manager de proiect: {name}',
    Dashboard_PhaseProgressHeader: 'Progresul fazelor',
    Dashboard_StatusBreakdownHeader: 'Distribuție pe stare',
    Dashboard_PriorityBreakdownHeader: 'Distribuție pe prioritate',
    Dashboard_PriorityCritical: 'Critică',
    Dashboard_PriorityHigh: 'Ridicată',
    Dashboard_PriorityMedium: 'Medie',
    Dashboard_PriorityLow: 'Scăzută',
    Dashboard_OverdueHeader: 'Restante  ({count})',
    Dashboard_DueNext14DaysHeader: 'Scadente în următoarele 14 zile  ({count})',
    Dashboard_CompletedThisWeekHeader: 'Finalizate săptămâna aceasta',
    Dashboard_UpdatedThisWeekHeader: 'Actualizate săptămâna aceasta',
    Dashboard_Today: 'Astăzi',
    Dashboard_Tomorrow: 'Mâine',
    Dashboard_DaysLeft: '{days}z',
    Dashboard_EmptyTitle: 'Încă nu există sarcini',
    Dashboard_EmptySubtitle: 'Adăugați sarcini pentru a vedea tabloul de bord al proiectului.',
    Dashboard_AddTaskButton: '+ Adăugați Sarcină',

    // ── Portfolio view ──
    Portfolio_ProjectCount: '{count} Proiect{plural}',
    Portfolio_OnTrackSummary: '{count} Conform planificării',
    Portfolio_AtRiskSummary: '{count} În risc',
    Portfolio_OverdueSummary: '{count} Restante',
    Portfolio_DoneSummary: '{count} Finalizate',
    Portfolio_SortLabel: 'Sortare:',
    Portfolio_SortAZ: 'A-Z',
    Portfolio_SortHealth: 'Sănătate',
    Portfolio_SortStatus: 'Stare',
    Portfolio_SortCompletion: 'Finalizare',
    Portfolio_RefreshTitle: 'Reîmprospătați',
    Portfolio_RefreshButton: 'Reîmprospătați',
    Portfolio_LoadingStats: 'Se încarcă statisticile…',
    Portfolio_EmptyTitle: 'Încă nu există proiecte',
    Portfolio_CreateFirstProject: '+ Creați Primul Proiect',
    Portfolio_StatsUnavailable: 'Statistici indisponibile',
    Portfolio_StatsUnavailableDetail: 'Nu s-au putut încărca statisticile pentru acest proiect.',
    Portfolio_OverallProgressLabel: 'Progres global',
    Portfolio_TaskCountDone: 'Finalizate',
    Portfolio_TaskCountActive: 'Active',
    Portfolio_TaskCountAtRisk: 'În risc',
    Portfolio_TaskCountOverdue: 'Restante',
    Portfolio_ViewGanttLink: 'Vedeți Gantt →',
    Portfolio_TodayTooltip: 'Astăzi',

    // ── Task panel ──
    TaskPanel_EditHeader: 'Editați: {taskTitle}',
    TaskPanel_NewTaskHeader: 'Sarcină Nouă',
    TaskPanel_TabBasic: 'De bază',
    TaskPanel_TabDetails: 'Detalii',
    TaskPanel_TabLinks: 'Legături',
    TaskPanel_ProjectLabelPrefix: 'Proiect: ',
    TaskPanel_TaskNameLabel: 'Denumire Sarcină',
    TaskPanel_TaskNamePlaceholder: 'Introduceți denumirea sarcinii',
    TaskPanel_TaskNameRequired: 'Denumirea sarcinii este obligatorie',
    TaskPanel_DescriptionLabel: 'Descriere',
    TaskPanel_DescriptionPlaceholder: 'Introduceți descrierea',
    TaskPanel_StartDateLabel: 'Data de început',
    TaskPanel_DueDateLabel: 'Data scadentă',
    TaskPanel_DueDateError: 'Data scadentă trebuie să fie egală sau ulterioară datei de început',
    TaskPanel_StatusLabel: 'Stare',
    TaskPanel_PriorityLabel: 'Prioritate',
    TaskPanel_PercentCompleteLabel: '% Finalizat: {percent}%',
    TaskPanel_AssignedToLabel: 'Atribuit lui',
    TaskPanel_AssignedToPlaceholder: 'Căutați persoane…',
    TaskPanel_PhaseLabel: 'Fază',
    TaskPanel_PhasePlaceholder: 'Introduceți denumirea fazei',
    TaskPanel_PhaseHint: 'Grupează sarcinile în vizualizările Gantt și Listă.',
    TaskPanel_MilestoneLabel: 'Reper',
    TaskPanel_MilestoneOnText: 'Da',
    TaskPanel_MilestoneOffText: 'Nu',
    TaskPanel_CustomBarColorLabel: 'Culoare personalizată a barei',
    TaskPanel_CustomBarColorOptionalSuffix: ' (opțional)',
    TaskPanel_AutoColorHint: 'Culoare automată din setările de stare/prioritate/fază.',
    TaskPanel_NotesLabel: 'Note',
    TaskPanel_NotesPlaceholder: 'Introduceți note',
    TaskPanel_ParentTaskLabel: 'Sarcină părinte',
    TaskPanel_ParentTaskNone: '(niciuna)',
    TaskPanel_ParentTaskHasChildrenHint: 'Această sarcină are subsarcini și nu poate avea propria sarcină părinte.',
    TaskPanel_ParentTaskHint: 'Includeți această sarcină sub alta, ca subsarcină.',
    TaskPanel_DependsOnLabel: 'Depinde de',
    TaskPanel_RemoveDependencyTitle: 'Eliminați dependența de "{taskTitle}"',
    TaskPanel_AddDependencyPlaceholder: 'Adăugați o dependență…',
    TaskPanel_SelectATaskOption: 'Selectați o sarcină…',
    TaskPanel_DependsOnHint: 'Sarcina nu poate începe până când acestea nu sunt finalizate.',
    TaskPanel_SavingLabel: 'Se salvează…',
    TaskPanel_CreatingLabel: 'Se creează…',
    TaskPanel_SaveChangesButton: 'Salvați Modificările',
    TaskPanel_CreateTaskButton: 'Creați Sarcina',
    TaskPanel_CancelButton: 'Anulați',
    TaskPanel_DismissAriaLabel: 'Închideți',
    TaskPanel_DiscardUnsavedChangesConfirm: 'Renunțați la modificările nesalvate?',
    TaskPanel_SaveFallbackError: 'Sarcina nu a putut fi salvată.',

    // ── Project panel ──
    ProjectPanel_EditHeader: 'Editați Proiectul',
    ProjectPanel_NewHeader: 'Proiect Nou',
    ProjectPanel_ProjectNameLabel: 'Denumire Proiect',
    ProjectPanel_ProjectNamePlaceholder: 'Introduceți denumirea proiectului',
    ProjectPanel_ProjectNameRequired: 'Denumirea proiectului este obligatorie',
    ProjectPanel_DescriptionLabel: 'Descriere',
    ProjectPanel_DescriptionPlaceholder: 'Introduceți descrierea',
    ProjectPanel_ProjectColorLabel: 'Culoarea proiectului',
    ProjectPanel_StatusLabel: 'Stare',
    ProjectPanel_StartDateLabel: 'Data de început',
    ProjectPanel_DueDateLabel: 'Data scadentă',
    ProjectPanel_DueDateError: 'Data scadentă trebuie să fie egală sau ulterioară datei de început',
    ProjectPanel_WhatHappensNextTitle: 'Ce urmează?',
    ProjectPanel_WhatHappensNextBody: 'Veți putea adăuga sarcini, configura faze și urmări progresul odată ce proiectul este creat.',
    ProjectPanel_SavingLabel: 'Se salvează…',
    ProjectPanel_CreatingLabel: 'Se creează…',
    ProjectPanel_SaveChangesButton: 'Salvați Modificările',
    ProjectPanel_CreateProjectButton: 'Creați Proiectul',
    ProjectPanel_CancelButton: 'Anulați',
    ProjectPanel_DismissAriaLabel: 'Închideți',
    ProjectPanel_DiscardUnsavedChangesConfirm: 'Renunțați la modificările nesalvate?',
    ProjectPanel_SaveFallbackError: 'Proiectul nu a putut fi salvat.',

    // ── Import panel ──
    ImportPanel_SourceExcelTitle: 'Fișier Excel / CSV',
    ImportPanel_SourceExcelSubtitle: 'Importați sarcini dintr-o foaie de calcul',
    ImportPanel_SourcePlannerTitle: 'Microsoft Planner',
    ImportPanel_SourcePlannerSubtitle: 'Importați sarcini dintr-un plan Planner',
    ImportPanel_ClickToBrowse: 'Faceți clic pentru a răsfoi',
    ImportPanel_DragDropSuffix: ' sau trageți și plasați',
    ImportPanel_SupportedExtensions: 'Acceptă .xlsx, .xls, .csv',
    ImportPanel_RowsColsSummary: '{rows} rânduri, {cols} coloane detectate',
    ImportPanel_LoadingPlannerPlans: 'Se încarcă planurile Planner…',
    ImportPanel_PlannerLoadError: 'Planurile Planner nu au putut fi încărcate.',
    ImportPanel_PlannerPermissionsHintPrefix: 'Asigurați-vă că aveți acces la Planner și că ',
    ImportPanel_PlannerPermissionsHintEmphasis: 'Sarcini prin Planner și To Do',
    ImportPanel_PlannerPermissionsHintSuffix: ' este disponibil pentru acest site.',
    ImportPanel_NoPlannerPlansFoundTitle: 'Nu s-a găsit niciun plan Planner',
    ImportPanel_NoPlannerPlansFoundBody: 'Este posibil să nu aveți acces la niciun plan Planner sau să nu existe niciunul pentru acest cont.',
    ImportPanel_TaskCountFoundIn: '{count} sarcini găsite în "{planName}"',
    ImportPanel_ProjectDetailsIntroPrefix: 'Se importă în ',
    ImportPanel_ProjectDetailsIntroSuffix: '. Verificați detaliile proiectului mai jos.',
    ImportPanel_ProjectNameLabel: 'Denumire Proiect',
    ImportPanel_DescriptionLabel: 'Descriere',
    ImportPanel_StatusLabel: 'Stare',
    ImportPanel_ColorLabel: 'Culoare',
    ImportPanel_MapIntro: 'Asociați coloanele din fișierul dvs. cu câmpurile sarcinii.',
    ImportPanel_CreatingProjectStatus: 'Se creează proiectul…',
    ImportPanel_ImportingTasksStatus: 'Se importă sarcinile…',
    ImportPanel_ProgressLabel: '{done} din {total}',
    ImportPanel_CouldNotCreateProject: 'Proiectul nu a putut fi creat.',
    ImportPanel_ImportCompletedWithErrors: 'Import finalizat cu {count} eroare(erori).',
    ImportPanel_ProjectCreatedSuccess: 'Proiect creat cu succes!',
    ImportPanel_ImportSuccessful: 'Import reușit!',
    ImportPanel_TasksAddedTo: '{count} sarcini adăugate la "{projectName}"',
    ImportPanel_FailedRowsLabel: 'Rânduri eșuate:',
    ImportPanel_CloseButton: 'Închideți',
    ImportPanel_OpenProjectButton: 'Deschideți Proiectul',
    ImportPanel_ViewImportedTasksButton: 'Vedeți Sarcinile Importate',
    ImportPanel_NextMapColumnsButton: 'Următorul: Asociați Coloanele',
    ImportPanel_ImportNTasksButton: 'Importați {count} Sarcini',
    ImportPanel_BackButton: 'Înapoi',
    ImportPanel_CancelButton: 'Anulați',
    ImportPanel_NextButton: 'Următorul',
    ImportPanel_StepSource: 'Sursă',
    ImportPanel_StepProject: 'Proiect',
    ImportPanel_StepMap: 'Asociere',
    ImportPanel_StepImport: 'Import',
    ImportPanel_StepDone: 'Finalizat',
    ImportPanel_ImportAsNewProjectHeader: 'Importați Fișierul ca Proiect Nou',
    ImportPanel_ImportIntoProjectHeader: 'Importați Sarcini în {projectName}',
    ImportPanel_CouldNotParseFile: 'Fișierul nu a putut fi procesat.',
    ImportPanel_CouldNotLoadPlannerTasks: 'Sarcinile din acest plan nu au putut fi încărcate.',
    ImportPanel_CouldNotCreateProjectDetail: 'Proiectul nu a putut fi creat: {detail}',
    ImportPanel_CouldNotLinkDependencies: 'Dependențele nu au putut fi asociate: {detail}',
    ImportPanel_UnknownError: 'eroare necunoscută',

    // ── Column mapper (import) ──
    ColumnMapper_TaskNameRequiredBanner: 'Denumirea Sarcinii trebuie asociată pentru a continua.',
    ColumnMapper_SkippedColumnsBanner: '{count} coloană(e) vor fi ignorate.',
    ColumnMapper_SourceColumnHeader: 'Coloană Sursă',
    ColumnMapper_TargetFieldHeader: 'Câmp Țintă',
    ColumnMapper_StatusHeader: 'Stare',
    ColumnMapper_SkippedBadge: 'Ignorată',
    ColumnMapper_AutoMappedBadge: 'Asociată automat',
    ColumnMapper_SetBadge: 'Setată',
    ColumnMapper_PreviewTitle: 'Previzualizare: {columnName}',
    ColumnMapper_EmptyCellDash: '—',

    // ── Import field display names / ImportService ──
    ImportField_TaskName: 'Denumire Sarcină',
    ImportField_StartDate: 'Data de început',
    ImportField_DueDate: 'Data scadentă',
    ImportField_Status: 'Stare',
    ImportField_Priority: 'Prioritate',
    ImportField_AssignedTo: 'Atribuit lui',
    ImportField_AssignedToEmail: 'E-mailul persoanei atribuite',
    ImportField_PercentComplete: '% Finalizat',
    ImportField_Phase: 'Fază',
    ImportField_Description: 'Descriere',
    ImportField_Notes: 'Note',
    ImportField_IsMilestone: 'Este Reper',
    ImportField_Dependencies: 'Dependențe',
    ImportField_SkipColumn: '(Ignorați această coloană)',
    ImportService_EmptyFileError: 'Fișierul pare a fi gol sau nu conține rânduri de date.',
    ImportService_ReadErrorDetail: 'Fișierul nu a putut fi citit: {detail}.',
    ImportService_FileReadError: 'Eroare la citirea fișierului.',
    ImportService_RowError: 'Rândul {rowNum} ("{title}"): {error}',
    ImportService_AmbiguousDependency: 'Dependența "{name}" se potrivește cu mai multe denumiri de sarcini — a fost ignorată.',
    ImportService_LinkDependencyError: 'Dependențele pentru sarcina {taskId} nu au putut fi asociate: {error}',

    // ── Health labels (shared: healthUtils.ts and ExportService.ts both use this set; also replaces the duplicated Export_PortfolioHealthLabel* keys) ──
    Health_Done: 'Finalizat',
    Health_OnTrack: 'Conform planificării',
    Health_AtRisk: 'În risc',
    Health_Overdue: 'Restant',

    // ── Status / Priority display labels (DISPLAY-ONLY — stored SharePoint Choice values remain unchanged/English) ──
    Status_NotStarted: 'Neînceput',
    Status_InProgress: 'În desfășurare',
    Status_Completed: 'Finalizat',
    Status_OnHold: 'În așteptare',
    Status_Cancelled: 'Anulat',
    Priority_Critical: 'Critică',
    Priority_High: 'Ridicată',
    Priority_Medium: 'Medie',
    Priority_Low: 'Scăzută',
    ProjectStatus_Planning: 'Planificare',
    ProjectStatus_Active: 'Activ',
    ProjectStatus_OnHold: 'În așteptare',
    ProjectStatus_Completed: 'Finalizat',
    ProjectStatus_Cancelled: 'Anulat',

    // ── Shell (SmartGantt.tsx) ──
    SmartGantt_LoadingProjects: 'Se încarcă proiectele…',
    SmartGantt_UnableToLoad: 'Nu se poate încărca',
    SmartGantt_RetryButton: 'Reîncercați',
    SmartGantt_NoProjectsYet: 'Încă nu există proiecte',
    SmartGantt_NoProjectsSubtitle: 'Creați primul dvs. proiect pentru a începe.',
    SmartGantt_CreateFirstProjectButton: '+ Creați Primul Proiect',
    SmartGantt_ImportFromExcelButton: '📥 Importați din Excel',
    SmartGantt_LoadingTasks: 'Se încarcă sarcinile…',
    SmartGantt_DismissAriaLabel: 'Închideți',
    SmartGantt_DeleteTaskDialogTitle: 'Ștergeți Sarcina',
    SmartGantt_DeleteTaskDialogSubtext: 'Sigur doriți să ștergeți "{taskTitle}"? Această acțiune nu poate fi anulată.',
    SmartGantt_DeleteButton: 'Ștergeți',
    SmartGantt_CancelButton: 'Anulați',
    SmartGantt_ArchiveProjectDialogTitle: 'Arhivați Proiectul',
    SmartGantt_ArchiveProjectDialogSubtext: 'Arhivați "{projectTitle}"? Îl puteți dezarhiva ulterior.',
    SmartGantt_ArchiveButton: 'Arhivați',
    SmartGantt_SendToRecycleBinDialogTitle: 'Trimiteți la Coșul de Reciclare',
    SmartGantt_SendToRecycleBinDialogSubtext: 'Trimiteți "{projectTitle}" la coșul de reciclare al site-ului?',
    SmartGantt_SendToRecycleBinButton: 'Trimiteți la Coșul de Reciclare',
    SmartGantt_FailedLoadProjects: 'Încărcarea proiectelor a eșuat. Verificați permisiunile site-ului.',
    SmartGantt_FailedLoadTasks: 'Încărcarea sarcinilor pentru acest proiect a eșuat.',
    SmartGantt_FailedLoadPortfolioStats: 'Încărcarea statisticilor portofoliului a eșuat.',
    SmartGantt_CouldNotSaveProject: 'Proiectul nu a putut fi salvat: {message}',
    SmartGantt_CouldNotDeleteProject: 'Proiectul nu a putut fi șters: {message}',
    SmartGantt_CouldNotArchiveProject: 'Proiectul nu a putut fi arhivat: {message}',
    SmartGantt_CouldNotUnarchiveProject: 'Proiectul nu a putut fi dezarhivat: {message}',
    SmartGantt_CouldNotSaveTask: 'Sarcina nu a putut fi salvată: {message}',
    SmartGantt_CouldNotDeleteTask: 'Sarcina nu a putut fi ștearsă: {message}',
    SmartGantt_ImageExportFailed: 'Exportul imaginii a eșuat: {message}',
    SmartGantt_PowerPointExportFailed: 'Exportul în PowerPoint a eșuat: {message}',
    SmartGantt_PortfolioExportFailed: 'Exportul portofoliului a eșuat: {message}',
    SmartGantt_CouldNotUpdateTask: 'Sarcina nu a putut fi actualizată: {message}',

    // ── Common ──
    ColorSwatch_AutoColorAriaLabel: 'Culoare automată',
    ColorSwatch_CustomColorAriaLabel: 'Culoare personalizată',
    ColorSwatch_PickCustomColorTitle: 'Alegeți o culoare personalizată',

    // ── Export (Excel / PowerPoint) ──
    Export_ColTaskName: 'Denumire Sarcină',
    Export_ColPhase: 'Fază',
    Export_ColStartDate: 'Data de început',
    Export_ColDueDate: 'Data scadentă',
    Export_ColStatus: 'Stare',
    Export_ColPriority: 'Prioritate',
    Export_ColAssignedTo: 'Atribuit lui',
    Export_ColAssignedToEmail: 'E-mailul persoanei atribuite',
    Export_ColPercentComplete: '% Finalizat',
    Export_ColIsMilestone: 'Este Reper',
    Export_ColDescription: 'Descriere',
    Export_ColNotes: 'Note',
    Export_Yes: 'Da',
    Export_No: 'Nu',
    Export_SheetNameTasks: 'Sarcini',
    Export_ExcelFileSuffix: ' - Sarcini.xlsx',
    Export_TaskNameColumnLabel: 'DENUMIRE SARCINĂ',
    Export_ExportedDateLabel: 'Exportat la {date}',
    Export_ProjectReportLabel: 'RAPORT DE PROIECT',
    Export_StatusLine: 'Stare: {status}',
    Export_DateRangeSeparator: ' până la ',
    Export_ProjectManagerLine: 'Manager de proiect: {name}',
    Export_GeneratedDateLine: 'Generat la {date}',
    Export_ProjectSummaryTitle: 'Rezumatul Proiectului',
    Export_StatTotalTasks: 'Total sarcini',
    Export_StatCompleted: 'Finalizate',
    Export_StatInProgress: 'În desfășurare',
    Export_StatOnHold: 'În așteptare',
    Export_StatNotStarted: 'Neîncepute',
    Export_OverallProgressLine: 'Progres global',
    Export_OverallProgressPercent: '{percent}%',
    Export_StatusBreakdownTitle: 'Distribuție pe stare',
    Export_StatusBreakdownRow: '{status}: {count} ({percent}%)',
    Export_GanttTimelineTitle: 'Cronologie Gantt',
    Export_SummaryRecentActivityTitle: 'Activitate recentă',
    Export_ProjectOverviewLabel: 'Prezentare generală a proiectului',
    Export_DetailStatusLabel: 'Stare',
    Export_DetailStartDateLabel: 'Data de început',
    Export_DetailDueDateLabel: 'Data scadentă',
    Export_DetailProjectManagerLabel: 'Manager de proiect',
    Export_Past7DaysLabel: 'Ultimele 7 zile',
    Export_NoActivityMessage: 'Nicio activitate recentă.',
    Export_CompletedThisWeekHeader: 'Finalizate săptămâna aceasta ({count})',
    Export_NewBadge: 'NOU  ',
    Export_CompletedPercentLine: '{percent}% finalizat',
    Export_MoreItemsSuffix: '+ încă {count}',
    Export_InProgressUpdatedHeader: 'În desfășurare / Actualizate',
    Export_StatusPercentLine: '{status} — {percent}%',
    Export_PortfolioReportLabel: 'RAPORT DE PORTOFOLIU',
    Export_PortfolioOverviewTitle: 'Prezentare generală a portofoliului',
    Export_ProjectsCountLine: '{count} Proiecte',
    Export_HealthSummaryOnTrack: '{count} Conform planificării',
    Export_HealthSummaryAtRisk: '{count} În risc',
    Export_HealthSummaryOverdue: '{count} Restante',
    Export_ProjectsSummaryHeader: 'Rezumatul Proiectelor',
    Export_TableProject: 'Proiect',
    Export_TableStatus: 'Stare',
    Export_TableHealth: 'Sănătate',
    Export_TableTotal: 'Total',
    Export_TableDone: 'Finalizate',
    Export_TableActive: 'Active',
    Export_TableAtRisk: 'În risc',
    Export_TableOverdue: 'Restante',
    Export_TablePctDone: '% Finalizat',
    Export_TableDueDate: 'Data scadentă',
    Export_PortfolioSummaryFileName: 'Rezumat Portofoliu.xlsx',
    Export_PortfolioReportFileName: 'Raport Portofoliu.pptx',
    Export_ProjectReportFileName: 'Raport {projectName}.pptx',
    Export_UnavailableLabel: 'Indisponibil',
    Export_SheetNamePortfolio: 'Portofoliu',
    Export_ColStart: 'Început',
    Export_ColDue: 'Scadență',
    Export_ImageGenerationFailed: 'Imaginea nu a putut fi generată — graficul poate fi prea mare pentru a fi exportat ca imagine.',
    Export_DrawingContextFailed: 'Nu s-a putut crea un context de desenare pentru export.',
    Export_SvgRenderFailed: 'Randarea SVG a eșuat',

    // ── Added in v1.5 review ──
    Svc_TooManyDependencies: 'Această sarcină are prea multe dependențe pentru a fi salvată (limita este de aproximativ 60). Eliminați câteva și încercați din nou.',
    Svc_TaskChangedByOthers: 'Această sarcină a fost modificată de altcineva de când ați încărcat-o. Reîmprospătați pagina și încercați din nou.',
    Svc_ProjectChangedByOthers: 'Acest proiect a fost modificat de altcineva de când l-ați deschis. Reîmprospătați pagina și încercați din nou.',
    Svc_ColumnCreateFailed: 'Nu s-au putut crea {count} coloană(e) în noua listă de sarcini: {detail}',
    Svc_BaselineUnavailable: 'Liniile de bază nu sunt disponibile pentru acest proiect deoarece coloanele liniei de bază nu au putut fi adăugate (este posibil să aveți nevoie de permisiunea de a edita lista).',
    Svc_SubtaskReassignFailed: 'Nu s-au putut realoca subsarcinile acestei sarcini înainte de ștergere: {detail}',
    Svc_UnresolvedDependency: 'Rândul {row} („{title}”): dependența „{name}” nu a putut fi asociată cu o sarcină importată.',
    Svc_SelfDependency: 'Rândul {row} („{title}”): dependența „{name}” trimite la sarcina însăși și a fost omisă.',
    Svc_ColId: 'ID',
    Svc_ColDependencies: 'Dependențe',
    Svc_ColBaselineStart: 'Început linie de bază',
    Svc_ColBaselineDue: 'Scadență linie de bază',
    Svc_CsvFileSuffix: ' - Tasks.csv',
    Svc_IcsFileSuffix: ' - Milestones.ics',
    Svc_PortfolioCsvFileName: 'Portfolio Summary.csv',
    Svc_PP_DisplayGroup: 'Valori implicite',
    Svc_PP_DefaultView: 'Vizualizare implicită',
    Svc_PP_ViewGantt: 'Gantt',
    Svc_PP_ViewList: 'Listă',
    Svc_PP_ViewKanban: 'Kanban',
    Svc_PP_ViewDashboard: 'Tablou de bord',
    Svc_PP_ViewPortfolio: 'Portofoliu',
    Svc_PP_DefaultZoom: 'Mărire implicită',
    Svc_PP_ZoomDay: 'Zi',
    Svc_PP_ZoomWeek: 'Săptămână',
    Svc_PP_ZoomMonth: 'Lună',
    Svc_PP_ZoomQuarter: 'Trimestru',
    Svc_PP_CalendarGroup: 'Calendar de lucru',
    Svc_PP_DaySun: 'Duminica este zi lucrătoare',
    Svc_PP_DayMon: 'Luni este zi lucrătoare',
    Svc_PP_DayTue: 'Marți este zi lucrătoare',
    Svc_PP_DayWed: 'Miercuri este zi lucrătoare',
    Svc_PP_DayThu: 'Joi este zi lucrătoare',
    Svc_PP_DayFri: 'Vineri este zi lucrătoare',
    Svc_PP_DaySat: 'Sâmbăta este zi lucrătoare',
    Svc_PP_Holidays: 'Sărbători legale (zile nelucrătoare)',
    Svc_PP_HolidaysHint: 'O dată pe rând, în format yyyy-MM-dd (de exemplu 2026-12-25).',
    Gantt_TimelineAriaLabel: 'Cronologia sarcinilor',
    Gantt_DragLabel: '{start} → {end} ({days} z)',
    Gantt_KeyboardMoveAnnouncement: '{taskTitle}: {startDate} până la {dueDate}',
    Gantt_KeyboardHint: 'Apăsați Enter pentru a deschide sarcina. Tastele săgeată stânga și dreapta o mută cu o zi lucrătoare. Shift cu tastele săgeți modifică data de încheiere.',
    Gantt_ParentCycleTooltip: 'Această sarcină face parte dintr-un lanț circular de sarcini părinte și subsarcini, așa că este afișată la nivelul superior',
    Gantt_CollapseAll: 'Restrângeți toate fazele',
    Gantt_ExpandAll: 'Extindeți toate fazele',
    Gantt_BaselineTooltip: 'Linie de bază: {start} → {due}',
    Gantt_VarianceTooltip: 'Abatere la finalizare: {days} zile față de linia de bază',
    Gantt_LinkHandleTitle: 'Trageți peste altă sarcină pentru a crea o dependență',
    Toolbar_FitToProject: 'Potrivire',
    Toolbar_FitToProjectTitle: 'Mărire pentru a încadra întregul proiect',
    Toolbar_UndoTitle: 'Anulare (Ctrl+Z)',
    Toolbar_RedoTitle: 'Refacere (Ctrl+Y)',
    Toolbar_ExportCsv: '📄 Exportați sarcinile în CSV',
    Toolbar_ExportIcs: '📅 Exportați reperele (iCal)',
    Toolbar_Print: '🖨 Imprimare / Salvare ca PDF',
    Toolbar_SetBaseline: '📐 Setați linia de bază…',
    Toolbar_CopyLink: '🔗 Copiați linkul',
    Toolbar_CopyLinkTitle: 'Copiați un link către această vizualizare (proiect, vizualizare, mărire și filtre)',
    App_UndoButton: 'Anulare',
    App_Undone: 'Modificarea a fost anulată.',
    App_Redone: 'Modificarea a fost refăcută.',
    App_DependentsMovedOne: 'O sarcină dependentă a fost mutată.',
    App_DependentsMovedMany: '{count} sarcini dependente au fost mutate.',
    App_TaskConflict: 'Această sarcină a fost modificată de altcineva. Cele mai recente sarcini au fost reîncărcate — verificați-le și încercați din nou.',
    App_DependencyCycle: 'Acea legătură ar crea o dependență circulară.',
    App_DependencyExists: 'Aceste sarcini sunt deja legate.',
    App_LinkCopied: 'Linkul a fost copiat în clipboard.',
    App_LinkCopyFailed: 'Nu s-a putut copia linkul: {message}',
    App_PopupBlocked: 'Fereastra de imprimare a fost blocată. Permiteți ferestrele pop-up pentru acest site și încercați din nou.',
    App_SetBaselineDialogTitle: 'Setare linie de bază',
    App_SetBaselineDialogSubtext: 'Salvați datele curente de început și de scadență ale tuturor celor {count} sarcini ca linie de bază? Orice linie de bază existentă este înlocuită.',
    App_SetBaselineButton: 'Setați linia de bază',
    App_BaselineSaved: 'Linia de bază a fost salvată.',
    App_BaselineFailed: 'Nu s-a putut salva linia de bază: {message}',
    App_CsvExportFailed: 'Exportul CSV a eșuat: {message}',
    App_IcsExportFailed: 'Exportul calendarului a eșuat: {message}',
    App_BulkDeleteDialogTitle: 'Ștergere sarcini',
    App_BulkDeleteDialogSubtext: 'Sigur doriți să ștergeți {count} sarcini? Această acțiune nu poate fi anulată.',
    Common_PeoplePicker_ClearAriaLabel: 'Golire',
    Common_PeoplePicker_DirectoryHeader: 'Persoane din director',
    Common_PeoplePicker_EmailLabel: 'E-mail (opțional)',
    Common_PeoplePicker_EmailPlaceholder: 'name@company.com',
    Common_PeoplePicker_ExternalHint: 'Nu se află în director. Salvat ca text liber.',
    Common_PeoplePicker_InvalidEmail: 'Introduceți o adresă de e-mail validă.',
    Common_PeoplePicker_ListAriaLabel: 'Sugestii de persoane',
    Common_PeoplePicker_RecentHeader: 'Utilizate recent',
    Common_PeoplePicker_ResultsAnnouncement: '{count} sugestii disponibile',
    Common_PeoplePicker_Searching: 'Se caută…',
    Common_PeoplePicker_UseExternal: 'Utilizați „{name}” (extern / nu se află în director)',
    Import_Mapper_PreviewFirstRows: 'Previzualizare (primele {count} rânduri)',
    Import_Mapper_RequiredLegend: 'Câmp obligatoriu',
    Import_Mapper_RequiredMarkerLabel: 'Obligatoriu',
    Import_Mapper_SelectAriaLabel: 'Câmp țintă pentru coloana {columnName}',
    Import_Panel_DateOrderAuto: 'Detectare automată',
    Import_Panel_DateOrderDMY: 'Zi/Lună/An (31/12/2026)',
    Import_Panel_DateOrderDetected: 'Detectat din fișierul dvs.: {order}.',
    Import_Panel_DateOrderHint: 'Se aplică datelor scrise cu cifre, cum ar fi 03/04/2026.',
    Import_Panel_DateOrderLabel: 'Ordinea datei',
    Import_Panel_DateOrderMDY: 'Lună/Zi/An (12/31/2026)',
    Import_Panel_DropZoneAriaLabel: 'Alegeți un fișier de importat. Apăsați Enter pentru a răsfoi.',
    Import_Panel_DropZoneChangeAriaLabel: 'Fișier selectat {fileName}. Apăsați Enter pentru a alege alt fișier.',
    Import_Panel_FailedCount: '{count} eșuate',
    Import_Panel_NewProjectIntroMany: 'Se va crea un proiect nou și toate cele {count} sarcini vor fi importate în el. Puteți modifica aceste detalii oricând după import.',
    Import_Panel_NewProjectIntroOne: 'Se va crea un proiect nou și {count} sarcină va fi importată în el. Puteți modifica aceste detalii oricând după import.',
    Import_Panel_PlanAriaLabel: '{planName}, {groupName}',
    Import_Panel_ProblemEndBeforeStart: 'Data scadenței este înaintea datei de început',
    Import_Panel_ProblemInvalidDueDate: 'Data scadenței „{value}” nu este o dată validă',
    Import_Panel_ProblemInvalidStartDate: 'Data de început „{value}” nu este o dată validă',
    Import_Panel_ProblemMissingTitle: 'Lipsește numele sarcinii',
    Import_Panel_ProgressLabelWithPercent: '{done} din {total} ({percent}%)',
    Import_Panel_SkipInvalidRows: 'Omiteți rândurile cu probleme',
    Import_Panel_SuccessWithWarningsMany: 'Import reușit cu {count} avertismente.',
    Import_Panel_SuccessWithWarningsOne: 'Import reușit cu {count} avertisment.',
    Import_Panel_ValidationHeader: 'Rânduri cu probleme',
    Import_Panel_ValidationMore: '…și încă {count}',
    Import_Panel_ValidationRow: 'Rândul {rowNum}: {problem}',
    Import_Panel_ValidationSummaryMany: '{count} rânduri au probleme',
    Import_Panel_ValidationSummaryOne: '{count} rând are o problemă',
    Import_Panel_WarningsLabel: 'Avertismente ({count}):',
    Panel_Project_ManagerLabel: 'Manager de proiect',
    Panel_Project_ManagerPlaceholder: 'Căutați persoane sau tastați un nume…',
    Panel_Task_BaselineDueLabel: 'Finalizare linie de bază',
    Panel_Task_BaselineHeader: 'Linie de bază',
    Panel_Task_BaselineStartLabel: 'Început linie de bază',
    Panel_Task_DepTypeFF: 'Finalizare la finalizare (FF)',
    Panel_Task_DepTypeFS: 'Finalizare la început (FS)',
    Panel_Task_DepTypeSF: 'Început la finalizare (SF)',
    Panel_Task_DepTypeSS: 'Început la început (SS)',
    Panel_Task_LagAriaLabel: 'Întârziere în zile lucrătoare pentru {taskTitle}',
    Panel_Task_LagHint: 'Întârzierea se exprimă în zile lucrătoare. Folosiți un număr negativ pentru avans.',
    Panel_Task_LinkTypeAriaLabel: 'Tip de legătură pentru {taskTitle}',
    Panel_Task_VarianceEarlier: 'Cu {days} zi(le) lucrătoare mai devreme',
    Panel_Task_VarianceLater: 'Cu {days} zi(le) lucrătoare mai târziu',
    Panel_Task_VarianceOnBaseline: 'conform liniei de bază',
    View_Dashboard_BurndownActual: 'Real',
    View_Dashboard_BurndownAria: 'Grafic burndown: {remaining} din {total} sarcini rămase',
    View_Dashboard_BurndownHeader: 'Burndown (sarcini rămase)',
    View_Dashboard_BurndownIdeal: 'Ideal',
    View_Dashboard_BurndownNoData: 'Nu există suficiente sarcini cu date pentru a desena un burndown.',
    View_Dashboard_CriticalPathHeader: 'Drum critic  ({count})',
    View_Dashboard_PhaseDoneSummary: '{done}/{total} finalizate  •  {percent}%',
    View_Dashboard_TaskRowAriaLabel: 'Deschideți sarcina {taskTitle}, {status}',
    View_Dashboard_WorkloadHeader: 'Încărcare pe persoană asignată',
    View_Dashboard_WorkloadOpen: '{count} deschise',
    View_Dashboard_WorkloadOverdue: '{count} restante',
    View_Kanban_AddTaskInColumnAriaLabel: 'Adăugați o sarcină în {column}',
    View_Kanban_CollapseColumn: 'Restrângeți coloana {column}',
    View_Kanban_ExpandColumn: 'Extindeți coloana {column}',
    View_Kanban_LaneHeader: '{name} ({count})',
    View_Kanban_LaneNoPhase: 'Fără fază',
    View_Kanban_LaneUnassigned: 'Neasignate',
    View_Kanban_LanesAssignee: 'Persoană asignată',
    View_Kanban_LanesNone: 'Niciuna',
    View_Kanban_LanesPhase: 'Fază',
    View_Kanban_SwimlanesLabel: 'Culoare (swimlanes)',
    View_Kanban_WipEditTitle: 'Setați limita de lucru în curs pentru {column} (0 pentru fără limită)',
    View_Kanban_WipExceededTitle: 'Limita WIP depășită: {count} din {limit}',
    View_Kanban_WipInputAriaLabel: 'Limită WIP pentru {column}',
    View_Kanban_WipLabel: 'WIP {count}/{limit}',
    View_Kanban_WipSet: 'WIP',
    View_List_BulkAssignApply: 'Asignați',
    View_List_BulkAssigneePlaceholder: 'Asignați către…',
    View_List_BulkBarAriaLabel: 'Acțiuni în bloc pentru sarcinile selectate',
    View_List_BulkClear: 'Golire selecție',
    View_List_BulkDelete: 'Ștergeți selecția',
    View_List_BulkPercentApply: 'Setați %',
    View_List_BulkPercentPlaceholder: '% finalizat',
    View_List_BulkPriorityPlaceholder: 'Setați prioritatea…',
    View_List_BulkSelectedCount: '{count} selectate',
    View_List_BulkStatusPlaceholder: 'Setați starea…',
    View_List_ExportCsv: 'Exportați CSV',
    View_List_NonWorkingDay: 'Zi nelucrătoare',
    View_List_SelectAllAriaLabel: 'Selectați toate sarcinile',
    View_List_SelectRowAriaLabel: 'Selectați {taskTitle}',
    View_Portfolio_CardAriaLabel: 'Deschideți proiectul {projectName}, {status}',
    View_Portfolio_ClearFilters: 'Ștergeți filtrele',
    View_Portfolio_FilteredCount: '{shown} din {total} proiecte',
    View_Portfolio_HideDone: 'Ascundeți finalizate / anulate',
    View_Portfolio_NoMatches: 'Niciun proiect nu corespunde filtrelor dvs.',
    View_Portfolio_ProjectCountMany: '{count} proiecte',
    View_Portfolio_ProjectCountOne: '{count} proiect',
    View_Portfolio_SearchAriaLabel: 'Căutați proiecte',
    View_Portfolio_SearchPlaceholder: 'Căutați proiecte…',
    Import_Panel_CopyDetails: 'Copiază detaliile',
    Import_Panel_Copied: 'Copiat',
  };
});
