define([], function () {
  return {
    // ── Property pane ──
    PropertyPane_HeaderDescription: 'Настройки Smart Gantt Chart',
    PropertyPane_GeneralGroupName: 'Общие',
    PropertyPane_TitleFieldLabel: 'Заголовок веб-части',
    WebPart_DefaultTitle: 'Smart Gantt Chart',

    // ── Toolbar ──
    Toolbar_ViewDashboard: 'Панель мониторинга',
    Toolbar_ViewList: 'Список',
    Toolbar_ViewGantt: 'Диаграмма Ганта',
    Toolbar_ViewKanban: 'Канбан',
    Toolbar_ZoomDay: 'День',
    Toolbar_ZoomWeek: 'Неделя',
    Toolbar_ZoomMonth: 'Месяц',
    Toolbar_ZoomQuarter: 'Квартал',
    Toolbar_SelectProjectAriaLabel: 'Выбрать проект',
    Toolbar_PortfolioLabel: 'Портфель',
    Toolbar_SelectAProject: 'Выберите проект',
    Toolbar_AllProjectsSubtext: 'Все проекты',
    Toolbar_NoProjectsYet: 'Пока нет проектов',
    Toolbar_ArchivedBadge: 'Архивирован',
    Toolbar_ShowArchivedProjects: 'Показать архивные проекты',
    Toolbar_NewProject: '+ Новый проект',
    Toolbar_ImportFileAsNewProject: '📥 Импортировать файл как новый проект…',
    Toolbar_AddTask: '+ Добавить задачу',
    Toolbar_EditProject: 'Изменить проект',
    Toolbar_OptionsButton: '⚙ Параметры',
    Toolbar_MoreOptionsTitle: 'Дополнительные параметры',
    Toolbar_ExportToExcel: '📊 Экспорт в Excel',
    Toolbar_ExportToPowerPoint: '📑 Экспорт в PowerPoint',
    Toolbar_ScrollToTodayTitle: 'Прокрутить к сегодняшнему дню',
    Toolbar_TodayButton: '◉ Сегодня',
    Toolbar_ImportTasks: '📥 Импортировать задачи…',
    Toolbar_ExportAsImage: '🖼 Экспорт как изображение (PNG)',
    Toolbar_UnarchiveProject: '📂 Восстановить из архива',
    Toolbar_ArchiveProject: '🗄️ Архивировать проект',
    Toolbar_SendToRecycleBin: '🗑️ Отправить в корзину',

    // ── Filter bar ──
    FilterBar_ClearOption: 'Очистить',
    FilterBar_DueAny: 'Любой срок',
    FilterBar_DueOverdue: 'Просрочено',
    FilterBar_DueToday: 'Срок сегодня',
    FilterBar_DueWeek: 'Срок через 7 дней',
    FilterBar_SearchPlaceholder: 'Поиск задач…',
    FilterBar_SearchAriaLabel: 'Поиск задач',
    FilterBar_StatusChipLabel: 'Статус',
    FilterBar_PriorityChipLabel: 'Приоритет',
    FilterBar_AssigneeChipLabel: 'Исполнитель',
    FilterBar_PhaseChipLabel: 'Этап',
    FilterBar_DueDateAriaLabel: 'Фильтр по сроку выполнения',
    FilterBar_MatchCount: '{matchCount} из {totalCount}',
    FilterBar_ClearFilters: '✕ Очистить фильтры',
    FilterBar_ChipLabelWithCount: '{label} ({count}) ▾',
    FilterBar_ChipLabelNoCount: '{label} ▾',

    // ── Gantt view ──
    Gantt_TaskColumnHeader: 'Задача',
    Gantt_DurationColumnHeader: 'Длит.',
    Gantt_AddTaskButton: '+ Добавить задачу',
    Gantt_EmptyTitle: 'Пока нет задач',
    Gantt_EmptySubtitle: 'Добавьте задачи, чтобы увидеть их на диаграмме Ганта.',
    Gantt_AddFirstTask: '+ Добавить первую задачу',
    Gantt_ImportTasksButton: '📥 Импортировать задачи',
    Gantt_EditTitle: 'Изменить',
    Gantt_DeleteTitle: 'Удалить',
    Gantt_EditTaskAriaLabel: 'Изменить задачу {taskTitle}',
    Gantt_DeleteTaskAriaLabel: 'Удалить задачу {taskTitle}',
    Gantt_ExpandPhaseAriaLabel: '{action} этап {phase}',
    Gantt_ExpandAction: 'Развернуть',
    Gantt_CollapseAction: 'Свернуть',
    Gantt_DependencyViolationTooltip: 'Начата до завершения всех зависимостей',
    Gantt_MilestoneAriaLabel: '{taskTitle}, веха, {date}',
    Gantt_BarAriaLabel: '{taskTitle}, с {startDate} по {dueDate}, выполнено на {percent}%',
    Gantt_PercentCompleteTooltip: 'Выполнено на {value}%',

    // ── Gantt options/settings panel ──
    GanttSettings_PanelHeader: '⚙ Параметры',
    GanttSettings_ColorCodingSection: 'Цветовая кодировка',
    GanttSettings_ByStatus: 'По статусу',
    GanttSettings_ByPriority: 'По приоритету',
    GanttSettings_ByPhase: 'По этапу',
    GanttSettings_ByHealth: 'По состоянию',
    GanttSettings_HeaderColorSection: 'Цвет заголовка',
    GanttSettings_ThemeDark: 'Тёмная',
    GanttSettings_ThemeNavy: 'Тёмно-синяя',
    GanttSettings_ThemeTeal: 'Бирюзовая',
    GanttSettings_ThemePurple: 'Фиолетовая',
    GanttSettings_ThemeLight: 'Светлая',
    GanttSettings_HeaderLabelsSection: 'Подписи заголовка',
    GanttSettings_WeekLabelDates: 'Даты',
    GanttSettings_WeekLabelDatesDesc: '3 июн, 10 июн…',
    GanttSettings_WeekLabelProject: 'Недели проекта',
    GanttSettings_WeekLabelProjectDesc: 'Н1, Н2…',
    GanttSettings_WeekLabelIso: 'Календарные недели',
    GanttSettings_WeekLabelIsoDesc: 'Н23, Н24…',
    GanttSettings_ProjectWeeksHint: 'Неделя 1 начинается с понедельника вашей самой ранней задачи — отлично подходит для презентаций.',
    GanttSettings_BarStyleSection: 'Стиль полосы',
    GanttSettings_BarStyleGradient: 'Градиент',
    GanttSettings_BarStyleFlat: 'Сплошной',
    GanttSettings_RowHeightSection: 'Высота строки',
    GanttSettings_HeightCompact: 'Компактная',
    GanttSettings_HeightNormal: 'Обычная',
    GanttSettings_HeightSpacious: 'Просторная',
    GanttSettings_ShowHideSection: 'Показать / скрыть',
    GanttSettings_WeekendShading: 'Затенение выходных',
    GanttSettings_DependencyArrows: 'Стрелки зависимостей',
    GanttSettings_CriticalPathAlwaysVisible: 'Критический путь всегда виден',
    GanttSettings_AllOthersOnHoverOnly: 'Остальные — только при наведении',
    GanttSettings_CriticalPathHighlight: 'Выделение критического пути',
    GanttSettings_ProgressPercentOnBars: 'Процент выполнения на полосах',
    GanttSettings_AssigneeNameOnBars: 'Имя исполнителя на полосах',
    GanttSettings_HealthStatusBadges: 'Значки состояния',

    // ── List view ──
    ListView_ColTaskName: 'Название задачи',
    ListView_ColStatus: 'Статус',
    ListView_ColHealth: 'Состояние',
    ListView_ColPriority: 'Приоритет',
    ListView_ColStart: 'Начало',
    ListView_ColDue: 'Срок',
    ListView_ColAssignedTo: 'Исполнитель',
    ListView_ColProgress: 'Прогресс',
    ListView_ColPhase: 'Этап',
    ListView_ColPredecessors: 'Предшественники',
    ListView_EmptyTitle: 'Пока нет задач',
    ListView_AddFirstTask: '+ Добавить первую задачу',
    ListView_AddTaskRow: '+ Добавить задачу',
    ListView_Unassigned: 'Не назначено',
    ListView_DependencyViolationTooltip: 'Начата до завершения всех зависимостей',
    ListView_StatusAriaLabel: 'Статус задачи {taskTitle}',
    ListView_PriorityAriaLabel: 'Приоритет задачи {taskTitle}',
    ListView_EditTaskAriaLabel: 'Изменить задачу {taskTitle}',
    ListView_DeleteTaskAriaLabel: 'Удалить задачу {taskTitle}',
    ListView_EditTitle: 'Изменить',
    ListView_DeleteTitle: 'Удалить',

    // ── Kanban view ──
    Kanban_ColumnNotStarted: 'Не начато',
    Kanban_ColumnInProgress: 'В работе',
    Kanban_ColumnOnHold: 'Приостановлено',
    Kanban_ColumnCompleted: 'Завершено',
    Kanban_ColumnCancelled: 'Отменено',
    Kanban_AddTaskButton: '+ Добавить задачу',
    Kanban_EditTitle: 'Изменить',
    Kanban_DeleteTitle: 'Удалить',
    Kanban_CardAriaLabel: '{taskTitle}, {status}. Нажмите Enter для редактирования, стрелку влево или вправо для изменения статуса.',
    Kanban_EditTaskAriaLabel: 'Изменить задачу {taskTitle}',
    Kanban_DeleteTaskAriaLabel: 'Удалить задачу {taskTitle}',

    // ── Dashboard view ──
    Dashboard_TotalTasks: 'Всего задач',
    Dashboard_Completed: 'Завершено',
    Dashboard_InProgress: 'В работе',
    Dashboard_OnHold: 'Приостановлено',
    Dashboard_NotStarted: 'Не начато',
    Dashboard_Cancelled: 'Отменено',
    Dashboard_OverallProgress: 'Общий прогресс',
    Dashboard_ProjectManagerLabel: 'Руководитель проекта: {name}',
    Dashboard_PhaseProgressHeader: 'Прогресс по этапам',
    Dashboard_StatusBreakdownHeader: 'Распределение по статусу',
    Dashboard_PriorityBreakdownHeader: 'Распределение по приоритету',
    Dashboard_PriorityCritical: 'Критический',
    Dashboard_PriorityHigh: 'Высокий',
    Dashboard_PriorityMedium: 'Средний',
    Dashboard_PriorityLow: 'Низкий',
    Dashboard_OverdueHeader: 'Просрочено  ({count})',
    Dashboard_DueNext14DaysHeader: 'Срок в ближайшие 14 дней  ({count})',
    Dashboard_CompletedThisWeekHeader: 'Завершено на этой неделе',
    Dashboard_UpdatedThisWeekHeader: 'Обновлено на этой неделе',
    Dashboard_Today: 'Сегодня',
    Dashboard_Tomorrow: 'Завтра',
    Dashboard_DaysLeft: '{days} дн.',
    Dashboard_EmptyTitle: 'Пока нет задач',
    Dashboard_EmptySubtitle: 'Добавьте задачи, чтобы увидеть панель мониторинга проекта.',
    Dashboard_AddTaskButton: '+ Добавить задачу',

    // ── Portfolio view ──
    Portfolio_ProjectCount: '{count} проект{plural}',
    Portfolio_OnTrackSummary: '{count} по плану',
    Portfolio_AtRiskSummary: '{count} под угрозой',
    Portfolio_OverdueSummary: '{count} просрочено',
    Portfolio_DoneSummary: '{count} завершено',
    Portfolio_SortLabel: 'Сортировка:',
    Portfolio_SortAZ: 'А-Я',
    Portfolio_SortHealth: 'Состояние',
    Portfolio_SortStatus: 'Статус',
    Portfolio_SortCompletion: 'Завершённость',
    Portfolio_RefreshTitle: 'Обновить',
    Portfolio_RefreshButton: 'Обновить',
    Portfolio_LoadingStats: 'Загрузка статистики…',
    Portfolio_EmptyTitle: 'Пока нет проектов',
    Portfolio_CreateFirstProject: '+ Создать первый проект',
    Portfolio_StatsUnavailable: 'Статистика недоступна',
    Portfolio_StatsUnavailableDetail: 'Не удалось загрузить статистику для этого проекта.',
    Portfolio_OverallProgressLabel: 'Общий прогресс',
    Portfolio_TaskCountDone: 'Завершено',
    Portfolio_TaskCountActive: 'Активно',
    Portfolio_TaskCountAtRisk: 'Под угрозой',
    Portfolio_TaskCountOverdue: 'Просрочено',
    Portfolio_ViewGanttLink: 'Открыть диаграмму Ганта →',
    Portfolio_TodayTooltip: 'Сегодня',

    // ── Task panel ──
    TaskPanel_EditHeader: 'Изменение: {taskTitle}',
    TaskPanel_NewTaskHeader: 'Новая задача',
    TaskPanel_TabBasic: 'Основное',
    TaskPanel_TabDetails: 'Подробности',
    TaskPanel_TabLinks: 'Связи',
    TaskPanel_ProjectLabelPrefix: 'Проект: ',
    TaskPanel_TaskNameLabel: 'Название задачи',
    TaskPanel_TaskNamePlaceholder: 'Введите название задачи',
    TaskPanel_TaskNameRequired: 'Название задачи обязательно',
    TaskPanel_DescriptionLabel: 'Описание',
    TaskPanel_DescriptionPlaceholder: 'Введите описание',
    TaskPanel_StartDateLabel: 'Дата начала',
    TaskPanel_DueDateLabel: 'Срок выполнения',
    TaskPanel_DueDateError: 'Срок выполнения должен быть не раньше даты начала',
    TaskPanel_StatusLabel: 'Статус',
    TaskPanel_PriorityLabel: 'Приоритет',
    TaskPanel_PercentCompleteLabel: '% выполнения: {percent}%',
    TaskPanel_AssignedToLabel: 'Исполнитель',
    TaskPanel_AssignedToPlaceholder: 'Поиск людей…',
    TaskPanel_PhaseLabel: 'Этап',
    TaskPanel_PhasePlaceholder: 'Введите название этапа',
    TaskPanel_PhaseHint: 'Группирует задачи в представлениях Ганта и Списка.',
    TaskPanel_MilestoneLabel: 'Веха',
    TaskPanel_MilestoneOnText: 'Да',
    TaskPanel_MilestoneOffText: 'Нет',
    TaskPanel_CustomBarColorLabel: 'Пользовательский цвет полосы',
    TaskPanel_CustomBarColorOptionalSuffix: ' (необязательно)',
    TaskPanel_AutoColorHint: 'Автоматический цвет на основе настроек статуса/приоритета/этапа.',
    TaskPanel_NotesLabel: 'Заметки',
    TaskPanel_NotesPlaceholder: 'Введите заметки',
    TaskPanel_ParentTaskLabel: 'Родительская задача',
    TaskPanel_ParentTaskNone: '(нет)',
    TaskPanel_ParentTaskHasChildrenHint: 'У этой задачи есть подзадачи, поэтому у неё не может быть собственной родительской задачи.',
    TaskPanel_ParentTaskHint: 'Вложите эту задачу в другую в качестве подзадачи.',
    TaskPanel_DependsOnLabel: 'Зависит от',
    TaskPanel_RemoveDependencyTitle: 'Удалить зависимость от "{taskTitle}"',
    TaskPanel_AddDependencyPlaceholder: 'Добавить зависимость…',
    TaskPanel_SelectATaskOption: 'Выберите задачу…',
    TaskPanel_DependsOnHint: 'Задача не может начаться, пока эти задачи не завершены.',
    TaskPanel_SavingLabel: 'Сохранение…',
    TaskPanel_CreatingLabel: 'Создание…',
    TaskPanel_SaveChangesButton: 'Сохранить изменения',
    TaskPanel_CreateTaskButton: 'Создать задачу',
    TaskPanel_CancelButton: 'Отмена',
    TaskPanel_DismissAriaLabel: 'Закрыть',
    TaskPanel_DiscardUnsavedChangesConfirm: 'Отменить несохранённые изменения?',
    TaskPanel_SaveFallbackError: 'Не удалось сохранить задачу.',

    // ── Project panel ──
    ProjectPanel_EditHeader: 'Изменить проект',
    ProjectPanel_NewHeader: 'Новый проект',
    ProjectPanel_ProjectNameLabel: 'Название проекта',
    ProjectPanel_ProjectNamePlaceholder: 'Введите название проекта',
    ProjectPanel_ProjectNameRequired: 'Название проекта обязательно',
    ProjectPanel_DescriptionLabel: 'Описание',
    ProjectPanel_DescriptionPlaceholder: 'Введите описание',
    ProjectPanel_ProjectColorLabel: 'Цвет проекта',
    ProjectPanel_StatusLabel: 'Статус',
    ProjectPanel_StartDateLabel: 'Дата начала',
    ProjectPanel_DueDateLabel: 'Срок выполнения',
    ProjectPanel_DueDateError: 'Срок выполнения должен быть не раньше даты начала',
    ProjectPanel_WhatHappensNextTitle: 'Что будет дальше?',
    ProjectPanel_WhatHappensNextBody: 'После создания проекта вы сможете добавлять задачи, настраивать этапы и отслеживать прогресс.',
    ProjectPanel_SavingLabel: 'Сохранение…',
    ProjectPanel_CreatingLabel: 'Создание…',
    ProjectPanel_SaveChangesButton: 'Сохранить изменения',
    ProjectPanel_CreateProjectButton: 'Создать проект',
    ProjectPanel_CancelButton: 'Отмена',
    ProjectPanel_DismissAriaLabel: 'Закрыть',
    ProjectPanel_DiscardUnsavedChangesConfirm: 'Отменить несохранённые изменения?',
    ProjectPanel_SaveFallbackError: 'Не удалось сохранить проект.',

    // ── Import panel ──
    ImportPanel_SourceExcelTitle: 'Файл Excel / CSV',
    ImportPanel_SourceExcelSubtitle: 'Импорт задач из таблицы',
    ImportPanel_SourcePlannerTitle: 'Microsoft Planner',
    ImportPanel_SourcePlannerSubtitle: 'Импорт задач из плана Planner',
    ImportPanel_ClickToBrowse: 'Нажмите, чтобы выбрать файл',
    ImportPanel_DragDropSuffix: ' или перетащите файл сюда',
    ImportPanel_SupportedExtensions: 'Поддерживаются форматы .xlsx, .xls, .csv',
    ImportPanel_RowsColsSummary: 'Обнаружено строк: {rows}, столбцов: {cols}',
    ImportPanel_LoadingPlannerPlans: 'Загрузка планов Planner…',
    ImportPanel_PlannerLoadError: 'Не удалось загрузить планы Planner.',
    ImportPanel_PlannerPermissionsHintPrefix: 'Убедитесь, что у вас есть доступ к Planner и что ',
    ImportPanel_PlannerPermissionsHintEmphasis: 'приложение "Задачи от Planner и To Do"',
    ImportPanel_PlannerPermissionsHintSuffix: ' доступно на этом сайте.',
    ImportPanel_NoPlannerPlansFoundTitle: 'Планы Planner не найдены',
    ImportPanel_NoPlannerPlansFoundBody: 'Возможно, у вас нет доступа ни к одному плану Planner, либо для этой учётной записи их не существует.',
    ImportPanel_TaskCountFoundIn: 'Найдено задач: {count} в плане "{planName}"',
    ImportPanel_ProjectDetailsIntroPrefix: 'Импорт в проект ',
    ImportPanel_ProjectDetailsIntroSuffix: '. Проверьте сведения о проекте ниже.',
    ImportPanel_ProjectNameLabel: 'Название проекта',
    ImportPanel_DescriptionLabel: 'Описание',
    ImportPanel_StatusLabel: 'Статус',
    ImportPanel_ColorLabel: 'Цвет',
    ImportPanel_MapIntro: 'Сопоставьте столбцы вашего файла с полями задач.',
    ImportPanel_CreatingProjectStatus: 'Создание проекта…',
    ImportPanel_ImportingTasksStatus: 'Импорт задач…',
    ImportPanel_ProgressLabel: '{done} из {total}',
    ImportPanel_CouldNotCreateProject: 'Не удалось создать проект.',
    ImportPanel_ImportCompletedWithErrors: 'Импорт завершён с ошибками ({count}).',
    ImportPanel_ProjectCreatedSuccess: 'Проект успешно создан!',
    ImportPanel_ImportSuccessful: 'Импорт выполнен успешно!',
    ImportPanel_TasksAddedTo: 'Задач добавлено: {count} в проект "{projectName}"',
    ImportPanel_FailedRowsLabel: 'Строки с ошибками:',
    ImportPanel_CloseButton: 'Закрыть',
    ImportPanel_OpenProjectButton: 'Открыть проект',
    ImportPanel_ViewImportedTasksButton: 'Просмотреть импортированные задачи',
    ImportPanel_NextMapColumnsButton: 'Далее: сопоставление столбцов',
    ImportPanel_ImportNTasksButton: 'Импортировать задачи: {count}',
    ImportPanel_BackButton: 'Назад',
    ImportPanel_CancelButton: 'Отмена',
    ImportPanel_NextButton: 'Далее',
    ImportPanel_StepSource: 'Источник',
    ImportPanel_StepProject: 'Проект',
    ImportPanel_StepMap: 'Сопоставление',
    ImportPanel_StepImport: 'Импорт',
    ImportPanel_StepDone: 'Готово',
    ImportPanel_ImportAsNewProjectHeader: 'Импорт файла как нового проекта',
    ImportPanel_ImportIntoProjectHeader: 'Импорт задач в проект {projectName}',
    ImportPanel_CouldNotParseFile: 'Не удалось обработать файл.',
    ImportPanel_CouldNotLoadPlannerTasks: 'Не удалось загрузить задачи из этого плана.',
    ImportPanel_CouldNotCreateProjectDetail: 'Не удалось создать проект: {detail}',
    ImportPanel_CouldNotLinkDependencies: 'Не удалось связать зависимости: {detail}',
    ImportPanel_UnknownError: 'неизвестная ошибка',

    // ── Column mapper (import) ──
    ColumnMapper_TaskNameRequiredBanner: 'Для продолжения необходимо сопоставить поле "Название задачи".',
    ColumnMapper_SkippedColumnsBanner: 'Будет пропущено столбцов: {count}.',
    ColumnMapper_SourceColumnHeader: 'Исходный столбец',
    ColumnMapper_TargetFieldHeader: 'Целевое поле',
    ColumnMapper_StatusHeader: 'Статус',
    ColumnMapper_SkippedBadge: 'Пропущено',
    ColumnMapper_AutoMappedBadge: 'Сопоставлено автоматически',
    ColumnMapper_SetBadge: 'Задано',
    ColumnMapper_PreviewTitle: 'Предпросмотр: {columnName}',
    ColumnMapper_EmptyCellDash: '—',

    // ── Import field display names / ImportService ──
    ImportField_TaskName: 'Название задачи',
    ImportField_StartDate: 'Дата начала',
    ImportField_DueDate: 'Срок выполнения',
    ImportField_Status: 'Статус',
    ImportField_Priority: 'Приоритет',
    ImportField_AssignedTo: 'Исполнитель',
    ImportField_AssignedToEmail: 'Email исполнителя',
    ImportField_PercentComplete: '% выполнения',
    ImportField_Phase: 'Этап',
    ImportField_Description: 'Описание',
    ImportField_Notes: 'Заметки',
    ImportField_IsMilestone: 'Является вехой',
    ImportField_Dependencies: 'Зависимости',
    ImportField_SkipColumn: '(Пропустить этот столбец)',
    ImportService_EmptyFileError: 'Файл, похоже, пуст или не содержит строк с данными.',
    ImportService_ReadErrorDetail: 'Не удалось прочитать файл: {detail}.',
    ImportService_FileReadError: 'Ошибка чтения файла.',
    ImportService_RowError: 'Строка {rowNum} ("{title}"): {error}',
    ImportService_AmbiguousDependency: 'Зависимость "{name}" соответствует нескольким названиям задач — пропущена.',
    ImportService_LinkDependencyError: 'Не удалось связать зависимости для задачи {taskId}: {error}',

    // ── Health labels (shared: healthUtils.ts and ExportService.ts both use this set; also replaces the duplicated Export_PortfolioHealthLabel* keys) ──
    Health_Done: 'Завершено',
    Health_OnTrack: 'По плану',
    Health_AtRisk: 'Под угрозой',
    Health_Overdue: 'Просрочено',

    // ── Status / Priority display labels (DISPLAY-ONLY — stored SharePoint Choice values remain unchanged/English) ──
    Status_NotStarted: 'Не начато',
    Status_InProgress: 'В работе',
    Status_Completed: 'Завершено',
    Status_OnHold: 'Приостановлено',
    Status_Cancelled: 'Отменено',
    Priority_Critical: 'Критический',
    Priority_High: 'Высокий',
    Priority_Medium: 'Средний',
    Priority_Low: 'Низкий',
    ProjectStatus_Planning: 'Планирование',
    ProjectStatus_Active: 'Активен',
    ProjectStatus_OnHold: 'Приостановлен',
    ProjectStatus_Completed: 'Завершён',
    ProjectStatus_Cancelled: 'Отменён',

    // ── Shell (SmartGantt.tsx) ──
    SmartGantt_LoadingProjects: 'Загрузка проектов…',
    SmartGantt_UnableToLoad: 'Не удалось загрузить',
    SmartGantt_RetryButton: 'Повторить',
    SmartGantt_NoProjectsYet: 'Пока нет проектов',
    SmartGantt_NoProjectsSubtitle: 'Создайте свой первый проект, чтобы начать.',
    SmartGantt_CreateFirstProjectButton: '+ Создать первый проект',
    SmartGantt_ImportFromExcelButton: '📥 Импорт из Excel',
    SmartGantt_LoadingTasks: 'Загрузка задач…',
    SmartGantt_DismissAriaLabel: 'Закрыть',
    SmartGantt_DeleteTaskDialogTitle: 'Удаление задачи',
    SmartGantt_DeleteTaskDialogSubtext: 'Вы уверены, что хотите удалить "{taskTitle}"? Это действие нельзя отменить.',
    SmartGantt_DeleteButton: 'Удалить',
    SmartGantt_CancelButton: 'Отмена',
    SmartGantt_ArchiveProjectDialogTitle: 'Архивирование проекта',
    SmartGantt_ArchiveProjectDialogSubtext: 'Архивировать проект "{projectTitle}"? Вы сможете восстановить его позже.',
    SmartGantt_ArchiveButton: 'Архивировать',
    SmartGantt_SendToRecycleBinDialogTitle: 'Отправка в корзину',
    SmartGantt_SendToRecycleBinDialogSubtext: 'Отправить проект "{projectTitle}" в корзину сайта?',
    SmartGantt_SendToRecycleBinButton: 'Отправить в корзину',
    SmartGantt_FailedLoadProjects: 'Не удалось загрузить проекты. Проверьте разрешения сайта.',
    SmartGantt_FailedLoadTasks: 'Не удалось загрузить задачи для этого проекта.',
    SmartGantt_FailedLoadPortfolioStats: 'Не удалось загрузить статистику портфеля.',
    SmartGantt_CouldNotSaveProject: 'Не удалось сохранить проект: {message}',
    SmartGantt_CouldNotDeleteProject: 'Не удалось удалить проект: {message}',
    SmartGantt_CouldNotArchiveProject: 'Не удалось архивировать проект: {message}',
    SmartGantt_CouldNotUnarchiveProject: 'Не удалось восстановить проект из архива: {message}',
    SmartGantt_CouldNotSaveTask: 'Не удалось сохранить задачу: {message}',
    SmartGantt_CouldNotDeleteTask: 'Не удалось удалить задачу: {message}',
    SmartGantt_ImageExportFailed: 'Не удалось экспортировать изображение: {message}',
    SmartGantt_PowerPointExportFailed: 'Не удалось выполнить экспорт в PowerPoint: {message}',
    SmartGantt_PortfolioExportFailed: 'Не удалось выполнить экспорт портфеля: {message}',
    SmartGantt_CouldNotUpdateTask: 'Не удалось обновить задачу: {message}',

    // ── Common ──
    ColorSwatch_AutoColorAriaLabel: 'Автоматический цвет',
    ColorSwatch_CustomColorAriaLabel: 'Пользовательский цвет',
    ColorSwatch_PickCustomColorTitle: 'Выбрать пользовательский цвет',

    // ── Export (Excel / PowerPoint) ──
    Export_ColTaskName: 'Название задачи',
    Export_ColPhase: 'Этап',
    Export_ColStartDate: 'Дата начала',
    Export_ColDueDate: 'Срок выполнения',
    Export_ColStatus: 'Статус',
    Export_ColPriority: 'Приоритет',
    Export_ColAssignedTo: 'Исполнитель',
    Export_ColAssignedToEmail: 'Email исполнителя',
    Export_ColPercentComplete: '% выполнения',
    Export_ColIsMilestone: 'Является вехой',
    Export_ColDescription: 'Описание',
    Export_ColNotes: 'Заметки',
    Export_Yes: 'Да',
    Export_No: 'Нет',
    Export_SheetNameTasks: 'Задачи',
    Export_ExcelFileSuffix: ' - Задачи.xlsx',
    Export_TaskNameColumnLabel: 'НАЗВАНИЕ ЗАДАЧИ',
    Export_ExportedDateLabel: 'Экспортировано {date}',
    Export_ProjectReportLabel: 'ОТЧЁТ ПО ПРОЕКТУ',
    Export_StatusLine: 'Статус: {status}',
    Export_DateRangeSeparator: ' по ',
    Export_ProjectManagerLine: 'Руководитель проекта: {name}',
    Export_GeneratedDateLine: 'Сформировано {date}',
    Export_ProjectSummaryTitle: 'Сводка по проекту',
    Export_StatTotalTasks: 'Всего задач',
    Export_StatCompleted: 'Завершено',
    Export_StatInProgress: 'В работе',
    Export_StatOnHold: 'Приостановлено',
    Export_StatNotStarted: 'Не начато',
    Export_OverallProgressLine: 'Общий прогресс',
    Export_OverallProgressPercent: '{percent}%',
    Export_StatusBreakdownTitle: 'Распределение по статусу',
    Export_StatusBreakdownRow: '{status}: {count} ({percent}%)',
    Export_GanttTimelineTitle: 'Временная шкала Ганта',
    Export_SummaryRecentActivityTitle: 'Недавняя активность',
    Export_ProjectOverviewLabel: 'Обзор проекта',
    Export_DetailStatusLabel: 'Статус',
    Export_DetailStartDateLabel: 'Дата начала',
    Export_DetailDueDateLabel: 'Срок выполнения',
    Export_DetailProjectManagerLabel: 'Руководитель проекта',
    Export_Past7DaysLabel: 'Последние 7 дней',
    Export_NoActivityMessage: 'Недавняя активность отсутствует.',
    Export_CompletedThisWeekHeader: 'Завершено на этой неделе ({count})',
    Export_NewBadge: 'НОВОЕ  ',
    Export_CompletedPercentLine: 'Выполнено на {percent}%',
    Export_MoreItemsSuffix: '+ ещё {count}',
    Export_InProgressUpdatedHeader: 'В работе / обновлено',
    Export_StatusPercentLine: '{status} — {percent}%',
    Export_PortfolioReportLabel: 'ОТЧЁТ ПО ПОРТФЕЛЮ',
    Export_PortfolioOverviewTitle: 'Обзор портфеля',
    Export_ProjectsCountLine: 'Проектов: {count}',
    Export_HealthSummaryOnTrack: '{count} по плану',
    Export_HealthSummaryAtRisk: '{count} под угрозой',
    Export_HealthSummaryOverdue: '{count} просрочено',
    Export_ProjectsSummaryHeader: 'Сводка по проектам',
    Export_TableProject: 'Проект',
    Export_TableStatus: 'Статус',
    Export_TableHealth: 'Состояние',
    Export_TableTotal: 'Всего',
    Export_TableDone: 'Завершено',
    Export_TableActive: 'Активно',
    Export_TableAtRisk: 'Под угрозой',
    Export_TableOverdue: 'Просрочено',
    Export_TablePctDone: '% завершения',
    Export_TableDueDate: 'Срок выполнения',
    Export_PortfolioSummaryFileName: 'Сводка по портфелю.xlsx',
    Export_PortfolioReportFileName: 'Отчёт по портфелю.pptx',
    Export_ProjectReportFileName: 'Отчёт по проекту {projectName}.pptx',
    Export_UnavailableLabel: 'Недоступно',
    Export_SheetNamePortfolio: 'Портфель',
    Export_ColStart: 'Начало',
    Export_ColDue: 'Срок',
    Export_ImageGenerationFailed: 'Не удалось создать изображение — диаграмма может быть слишком большой для экспорта в виде изображения.',
    Export_DrawingContextFailed: 'Не удалось создать контекст рисования для экспорта.',
    Export_SvgRenderFailed: 'Не удалось выполнить рендеринг SVG',
  };
});
