define([], function () {
  return {
    // ── Property pane ──
    PropertyPane_HeaderDescription: 'Inställningar för Smart Gantt Chart',
    PropertyPane_GeneralGroupName: 'Allmänt',
    PropertyPane_TitleFieldLabel: 'Webbdelens titel',
    WebPart_DefaultTitle: 'Smart Gantt Chart',

    // ── Toolbar ──
    Toolbar_ViewDashboard: 'Instrumentpanel',
    Toolbar_ViewList: 'Lista',
    Toolbar_ViewGantt: 'Gantt',
    Toolbar_ViewKanban: 'Kanban',
    Toolbar_ZoomDay: 'Dag',
    Toolbar_ZoomWeek: 'Vecka',
    Toolbar_ZoomMonth: 'Månad',
    Toolbar_ZoomQuarter: 'Kvartal',
    Toolbar_SelectProjectAriaLabel: 'Välj projekt',
    Toolbar_PortfolioLabel: 'Portfölj',
    Toolbar_SelectAProject: 'Välj ett projekt',
    Toolbar_AllProjectsSubtext: 'Alla projekt',
    Toolbar_NoProjectsYet: 'Inga projekt än',
    Toolbar_ArchivedBadge: 'Arkiverat',
    Toolbar_ShowArchivedProjects: 'Visa arkiverade projekt',
    Toolbar_NewProject: '+ Nytt projekt',
    Toolbar_ImportFileAsNewProject: '📥 Importera fil som nytt projekt…',
    Toolbar_AddTask: '+ Lägg till uppgift',
    Toolbar_EditProject: 'Redigera projekt',
    Toolbar_OptionsButton: '⚙ Alternativ',
    Toolbar_MoreOptionsTitle: 'Fler alternativ',
    Toolbar_ExportToExcel: '📊 Exportera till Excel',
    Toolbar_ExportToPowerPoint: '📑 Exportera till PowerPoint',
    Toolbar_ScrollToTodayTitle: 'Rulla till idag',
    Toolbar_TodayButton: '◉ Idag',
    Toolbar_ImportTasks: '📥 Importera uppgifter…',
    Toolbar_ExportAsImage: '🖼 Exportera som bild (PNG)',
    Toolbar_UnarchiveProject: '📂 Återställ från arkiv',
    Toolbar_ArchiveProject: '🗄️ Arkivera projekt',
    Toolbar_SendToRecycleBin: '🗑️ Skicka till papperskorgen',

    // ── Filter bar ──
    FilterBar_ClearOption: 'Rensa',
    FilterBar_DueAny: 'Alla förfallodatum',
    FilterBar_DueOverdue: 'Försenad',
    FilterBar_DueToday: 'Förfaller idag',
    FilterBar_DueWeek: 'Förfaller inom 7 dagar',
    FilterBar_SearchPlaceholder: 'Sök uppgifter…',
    FilterBar_SearchAriaLabel: 'Sök uppgifter',
    FilterBar_StatusChipLabel: 'Status',
    FilterBar_PriorityChipLabel: 'Prioritet',
    FilterBar_AssigneeChipLabel: 'Ansvarig',
    FilterBar_PhaseChipLabel: 'Fas',
    FilterBar_DueDateAriaLabel: 'Filtrera efter förfallodatum',
    FilterBar_MatchCount: '{matchCount} av {totalCount}',
    FilterBar_ClearFilters: '✕ Rensa filter',
    FilterBar_ChipLabelWithCount: '{label} ({count}) ▾',
    FilterBar_ChipLabelNoCount: '{label} ▾',

    // ── Gantt view ──
    Gantt_TaskColumnHeader: 'Uppgift',
    Gantt_DurationColumnHeader: 'Varakt.',
    Gantt_AddTaskButton: '+ Lägg till uppgift',
    Gantt_EmptyTitle: 'Inga uppgifter än',
    Gantt_EmptySubtitle: 'Lägg till uppgifter för att se dem i Gantt-schemat.',
    Gantt_AddFirstTask: '+ Lägg till första uppgiften',
    Gantt_ImportTasksButton: '📥 Importera uppgifter',
    Gantt_EditTitle: 'Redigera',
    Gantt_DeleteTitle: 'Ta bort',
    Gantt_EditTaskAriaLabel: 'Redigera uppgiften {taskTitle}',
    Gantt_DeleteTaskAriaLabel: 'Ta bort uppgiften {taskTitle}',
    Gantt_ExpandPhaseAriaLabel: '{action} fasen {phase}',
    Gantt_ExpandAction: 'Utöka',
    Gantt_CollapseAction: 'Komprimera',
    Gantt_DependencyViolationTooltip: 'Påbörjad innan alla beroenden var klara',
    Gantt_MilestoneAriaLabel: '{taskTitle}, milstolpe, {date}',
    Gantt_BarAriaLabel: '{taskTitle}, {startDate} till {dueDate}, {percent}% klart',
    Gantt_PercentCompleteTooltip: '{value}% klart',

    // ── Gantt options/settings panel ──
    GanttSettings_PanelHeader: '⚙ Alternativ',
    GanttSettings_ColorCodingSection: 'Färgkodning',
    GanttSettings_ByStatus: 'Efter status',
    GanttSettings_ByPriority: 'Efter prioritet',
    GanttSettings_ByPhase: 'Efter fas',
    GanttSettings_ByHealth: 'Efter hälsostatus',
    GanttSettings_HeaderColorSection: 'Rubrikfärg',
    GanttSettings_ThemeDark: 'Mörkt',
    GanttSettings_ThemeNavy: 'Marinblått',
    GanttSettings_ThemeTeal: 'Petrol',
    GanttSettings_ThemePurple: 'Lila',
    GanttSettings_ThemeLight: 'Ljust',
    GanttSettings_HeaderLabelsSection: 'Rubriketiketter',
    GanttSettings_WeekLabelDates: 'Datum',
    GanttSettings_WeekLabelDatesDesc: '3 jun, 10 jun…',
    GanttSettings_WeekLabelProject: 'Projektveckor',
    GanttSettings_WeekLabelProjectDesc: 'V1, V2…',
    GanttSettings_WeekLabelIso: 'Kalenderveckor',
    GanttSettings_WeekLabelIsoDesc: 'V23, V24…',
    GanttSettings_ProjectWeeksHint: 'Vecka 1 börjar på måndagen för din tidigaste uppgift — perfekt för presentationer.',
    GanttSettings_BarStyleSection: 'Stapelstil',
    GanttSettings_BarStyleGradient: 'Toning',
    GanttSettings_BarStyleFlat: 'Enfärgad',
    GanttSettings_RowHeightSection: 'Radhöjd',
    GanttSettings_HeightCompact: 'Kompakt',
    GanttSettings_HeightNormal: 'Normal',
    GanttSettings_HeightSpacious: 'Rymlig',
    GanttSettings_ShowHideSection: 'Visa / dölj',
    GanttSettings_WeekendShading: 'Helgmarkering',
    GanttSettings_DependencyArrows: 'Beroendepilar',
    GanttSettings_CriticalPathAlwaysVisible: 'Kritisk linje alltid synlig',
    GanttSettings_AllOthersOnHoverOnly: 'Övriga endast vid hovring',
    GanttSettings_CriticalPathHighlight: 'Markering av kritisk linje',
    GanttSettings_ProgressPercentOnBars: 'Procentandel klart på staplar',
    GanttSettings_AssigneeNameOnBars: 'Ansvarigs namn på staplar',
    GanttSettings_HealthStatusBadges: 'Hälsostatusmärken',

    // ── List view ──
    ListView_ColTaskName: 'Uppgiftsnamn',
    ListView_ColStatus: 'Status',
    ListView_ColHealth: 'Hälsostatus',
    ListView_ColPriority: 'Prioritet',
    ListView_ColStart: 'Start',
    ListView_ColDue: 'Förfaller',
    ListView_ColAssignedTo: 'Tilldelad till',
    ListView_ColProgress: 'Förlopp',
    ListView_ColPhase: 'Fas',
    ListView_ColPredecessors: 'Föregångare',
    ListView_EmptyTitle: 'Inga uppgifter än',
    ListView_AddFirstTask: '+ Lägg till första uppgiften',
    ListView_AddTaskRow: '+ Lägg till uppgift',
    ListView_Unassigned: 'Ej tilldelad',
    ListView_DependencyViolationTooltip: 'Påbörjad innan alla beroenden var klara',
    ListView_StatusAriaLabel: 'Status för {taskTitle}',
    ListView_PriorityAriaLabel: 'Prioritet för {taskTitle}',
    ListView_EditTaskAriaLabel: 'Redigera uppgiften {taskTitle}',
    ListView_DeleteTaskAriaLabel: 'Ta bort uppgiften {taskTitle}',
    ListView_EditTitle: 'Redigera',
    ListView_DeleteTitle: 'Ta bort',

    // ── Kanban view ──
    Kanban_ColumnNotStarted: 'Ej påbörjad',
    Kanban_ColumnInProgress: 'Pågår',
    Kanban_ColumnOnHold: 'Pausad',
    Kanban_ColumnCompleted: 'Slutförd',
    Kanban_ColumnCancelled: 'Avbruten',
    Kanban_AddTaskButton: '+ Lägg till uppgift',
    Kanban_EditTitle: 'Redigera',
    Kanban_DeleteTitle: 'Ta bort',
    Kanban_CardAriaLabel: '{taskTitle}, {status}. Tryck på Retur för att redigera, vänster- eller högerpil för att ändra status.',
    Kanban_EditTaskAriaLabel: 'Redigera uppgiften {taskTitle}',
    Kanban_DeleteTaskAriaLabel: 'Ta bort uppgiften {taskTitle}',

    // ── Dashboard view ──
    Dashboard_TotalTasks: 'Totalt antal uppgifter',
    Dashboard_Completed: 'Slutförda',
    Dashboard_InProgress: 'Pågår',
    Dashboard_OnHold: 'Pausade',
    Dashboard_NotStarted: 'Ej påbörjade',
    Dashboard_Cancelled: 'Avbrutna',
    Dashboard_OverallProgress: 'Totalt förlopp',
    Dashboard_ProjectManagerLabel: 'Projektledare: {name}',
    Dashboard_PhaseProgressHeader: 'Fasförlopp',
    Dashboard_StatusBreakdownHeader: 'Statusfördelning',
    Dashboard_PriorityBreakdownHeader: 'Prioritetsfördelning',
    Dashboard_PriorityCritical: 'Kritisk',
    Dashboard_PriorityHigh: 'Hög',
    Dashboard_PriorityMedium: 'Medel',
    Dashboard_PriorityLow: 'Låg',
    Dashboard_OverdueHeader: 'Försenade  ({count})',
    Dashboard_DueNext14DaysHeader: 'Förfaller inom 14 dagar  ({count})',
    Dashboard_CompletedThisWeekHeader: 'Slutförda denna vecka',
    Dashboard_UpdatedThisWeekHeader: 'Uppdaterade denna vecka',
    Dashboard_Today: 'Idag',
    Dashboard_Tomorrow: 'Imorgon',
    Dashboard_DaysLeft: '{days}d',
    Dashboard_EmptyTitle: 'Inga uppgifter än',
    Dashboard_EmptySubtitle: 'Lägg till uppgifter för att se din projektöversikt.',
    Dashboard_AddTaskButton: '+ Lägg till uppgift',

    // ── Portfolio view ──
    Portfolio_ProjectCount: '{count} projekt{plural}',
    Portfolio_OnTrackSummary: '{count} enligt plan',
    Portfolio_AtRiskSummary: '{count} i riskzonen',
    Portfolio_OverdueSummary: '{count} försenade',
    Portfolio_DoneSummary: '{count} klara',
    Portfolio_SortLabel: 'Sortera:',
    Portfolio_SortAZ: 'A-Ö',
    Portfolio_SortHealth: 'Hälsostatus',
    Portfolio_SortStatus: 'Status',
    Portfolio_SortCompletion: 'Klart',
    Portfolio_RefreshTitle: 'Uppdatera',
    Portfolio_RefreshButton: 'Uppdatera',
    Portfolio_LoadingStats: 'Läser in statistik…',
    Portfolio_EmptyTitle: 'Inga projekt än',
    Portfolio_CreateFirstProject: '+ Skapa första projektet',
    Portfolio_StatsUnavailable: 'Statistik ej tillgänglig',
    Portfolio_StatsUnavailableDetail: 'Det gick inte att läsa in statistik för detta projekt.',
    Portfolio_OverallProgressLabel: 'Totalt förlopp',
    Portfolio_TaskCountDone: 'Klara',
    Portfolio_TaskCountActive: 'Aktiva',
    Portfolio_TaskCountAtRisk: 'I riskzonen',
    Portfolio_TaskCountOverdue: 'Försenade',
    Portfolio_ViewGanttLink: 'Visa Gantt →',
    Portfolio_TodayTooltip: 'Idag',

    // ── Task panel ──
    TaskPanel_EditHeader: 'Redigera: {taskTitle}',
    TaskPanel_NewTaskHeader: 'Ny uppgift',
    TaskPanel_TabBasic: 'Grundläggande',
    TaskPanel_TabDetails: 'Detaljer',
    TaskPanel_TabLinks: 'Länkar',
    TaskPanel_ProjectLabelPrefix: 'Projekt: ',
    TaskPanel_TaskNameLabel: 'Uppgiftsnamn',
    TaskPanel_TaskNamePlaceholder: 'Ange uppgiftsnamn',
    TaskPanel_TaskNameRequired: 'Uppgiftsnamn krävs',
    TaskPanel_DescriptionLabel: 'Beskrivning',
    TaskPanel_DescriptionPlaceholder: 'Ange beskrivning',
    TaskPanel_StartDateLabel: 'Startdatum',
    TaskPanel_DueDateLabel: 'Förfallodatum',
    TaskPanel_DueDateError: 'Förfallodatumet måste vara samma dag som eller efter startdatumet',
    TaskPanel_StatusLabel: 'Status',
    TaskPanel_PriorityLabel: 'Prioritet',
    TaskPanel_PercentCompleteLabel: '% klart: {percent}%',
    TaskPanel_AssignedToLabel: 'Tilldelad till',
    TaskPanel_AssignedToPlaceholder: 'Sök personer…',
    TaskPanel_PhaseLabel: 'Fas',
    TaskPanel_PhasePlaceholder: 'Ange fasnamn',
    TaskPanel_PhaseHint: 'Grupperar uppgifter i Gantt- och listvyerna.',
    TaskPanel_MilestoneLabel: 'Milstolpe',
    TaskPanel_MilestoneOnText: 'Ja',
    TaskPanel_MilestoneOffText: 'Nej',
    TaskPanel_CustomBarColorLabel: 'Anpassad stapelfärg',
    TaskPanel_CustomBarColorOptionalSuffix: ' (valfritt)',
    TaskPanel_AutoColorHint: 'Automatisk färg utifrån inställningar för status/prioritet/fas.',
    TaskPanel_NotesLabel: 'Anteckningar',
    TaskPanel_NotesPlaceholder: 'Ange anteckningar',
    TaskPanel_ParentTaskLabel: 'Överordnad uppgift',
    TaskPanel_ParentTaskNone: '(ingen)',
    TaskPanel_ParentTaskHasChildrenHint: 'Denna uppgift har underuppgifter och kan inte ha en egen överordnad uppgift.',
    TaskPanel_ParentTaskHint: 'Placera denna uppgift under en annan som en underuppgift.',
    TaskPanel_DependsOnLabel: 'Beror på',
    TaskPanel_RemoveDependencyTitle: 'Ta bort beroendet till "{taskTitle}"',
    TaskPanel_AddDependencyPlaceholder: 'Lägg till ett beroende…',
    TaskPanel_SelectATaskOption: 'Välj en uppgift…',
    TaskPanel_DependsOnHint: 'Uppgiften kan inte påbörjas förrän dessa är slutförda.',
    TaskPanel_SavingLabel: 'Sparar…',
    TaskPanel_CreatingLabel: 'Skapar…',
    TaskPanel_SaveChangesButton: 'Spara ändringar',
    TaskPanel_CreateTaskButton: 'Skapa uppgift',
    TaskPanel_CancelButton: 'Avbryt',
    TaskPanel_DismissAriaLabel: 'Stäng',
    TaskPanel_DiscardUnsavedChangesConfirm: 'Vill du förkasta osparade ändringar?',
    TaskPanel_SaveFallbackError: 'Det gick inte att spara uppgiften.',

    // ── Project panel ──
    ProjectPanel_EditHeader: 'Redigera projekt',
    ProjectPanel_NewHeader: 'Nytt projekt',
    ProjectPanel_ProjectNameLabel: 'Projektnamn',
    ProjectPanel_ProjectNamePlaceholder: 'Ange projektnamn',
    ProjectPanel_ProjectNameRequired: 'Projektnamn krävs',
    ProjectPanel_DescriptionLabel: 'Beskrivning',
    ProjectPanel_DescriptionPlaceholder: 'Ange beskrivning',
    ProjectPanel_ProjectColorLabel: 'Projektfärg',
    ProjectPanel_StatusLabel: 'Status',
    ProjectPanel_StartDateLabel: 'Startdatum',
    ProjectPanel_DueDateLabel: 'Förfallodatum',
    ProjectPanel_DueDateError: 'Förfallodatumet måste vara samma dag som eller efter startdatumet',
    ProjectPanel_WhatHappensNextTitle: 'Vad händer sedan?',
    ProjectPanel_WhatHappensNextBody: 'Du kommer att kunna lägga till uppgifter, konfigurera faser och följa upp förloppet när projektet har skapats.',
    ProjectPanel_SavingLabel: 'Sparar…',
    ProjectPanel_CreatingLabel: 'Skapar…',
    ProjectPanel_SaveChangesButton: 'Spara ändringar',
    ProjectPanel_CreateProjectButton: 'Skapa projekt',
    ProjectPanel_CancelButton: 'Avbryt',
    ProjectPanel_DismissAriaLabel: 'Stäng',
    ProjectPanel_DiscardUnsavedChangesConfirm: 'Vill du förkasta osparade ändringar?',
    ProjectPanel_SaveFallbackError: 'Det gick inte att spara projektet.',

    // ── Import panel ──
    ImportPanel_SourceExcelTitle: 'Excel-/CSV-fil',
    ImportPanel_SourceExcelSubtitle: 'Importera uppgifter från ett kalkylblad',
    ImportPanel_SourcePlannerTitle: 'Microsoft Planner',
    ImportPanel_SourcePlannerSubtitle: 'Importera uppgifter från en Planner-plan',
    ImportPanel_ClickToBrowse: 'Klicka för att bläddra',
    ImportPanel_DragDropSuffix: ' eller dra och släpp',
    ImportPanel_SupportedExtensions: 'Stöder .xlsx, .xls, .csv',
    ImportPanel_RowsColsSummary: '{rows} rader, {cols} kolumner hittades',
    ImportPanel_LoadingPlannerPlans: 'Läser in Planner-planer…',
    ImportPanel_PlannerLoadError: 'Det gick inte att läsa in Planner-planer.',
    ImportPanel_PlannerPermissionsHintPrefix: 'Kontrollera att du har åtkomst till Planner och att ',
    ImportPanel_PlannerPermissionsHintEmphasis: 'Uppgifter från Planner och To Do',
    ImportPanel_PlannerPermissionsHintSuffix: ' är tillgänglig på denna webbplats.',
    ImportPanel_NoPlannerPlansFoundTitle: 'Inga Planner-planer hittades',
    ImportPanel_NoPlannerPlansFoundBody: 'Du kanske inte har åtkomst till några Planner-planer, eller så finns inga för detta konto.',
    ImportPanel_TaskCountFoundIn: '{count} uppgifter hittades i "{planName}"',
    ImportPanel_ProjectDetailsIntroPrefix: 'Importerar till ',
    ImportPanel_ProjectDetailsIntroSuffix: '. Granska projektdetaljerna nedan.',
    ImportPanel_ProjectNameLabel: 'Projektnamn',
    ImportPanel_DescriptionLabel: 'Beskrivning',
    ImportPanel_StatusLabel: 'Status',
    ImportPanel_ColorLabel: 'Färg',
    ImportPanel_MapIntro: 'Koppla kolumnerna i din fil till uppgiftsfälten.',
    ImportPanel_CreatingProjectStatus: 'Skapar projekt…',
    ImportPanel_ImportingTasksStatus: 'Importerar uppgifter…',
    ImportPanel_ProgressLabel: '{done} av {total}',
    ImportPanel_CouldNotCreateProject: 'Det gick inte att skapa projektet.',
    ImportPanel_ImportCompletedWithErrors: 'Importen slutfördes med {count} fel.',
    ImportPanel_ProjectCreatedSuccess: 'Projektet skapades!',
    ImportPanel_ImportSuccessful: 'Importen lyckades!',
    ImportPanel_TasksAddedTo: '{count} uppgifter tillagda i "{projectName}"',
    ImportPanel_FailedRowsLabel: 'Rader som misslyckades:',
    ImportPanel_CloseButton: 'Stäng',
    ImportPanel_OpenProjectButton: 'Öppna projekt',
    ImportPanel_ViewImportedTasksButton: 'Visa importerade uppgifter',
    ImportPanel_NextMapColumnsButton: 'Nästa: Koppla kolumner',
    ImportPanel_ImportNTasksButton: 'Importera {count} uppgifter',
    ImportPanel_BackButton: 'Tillbaka',
    ImportPanel_CancelButton: 'Avbryt',
    ImportPanel_NextButton: 'Nästa',
    ImportPanel_StepSource: 'Källa',
    ImportPanel_StepProject: 'Projekt',
    ImportPanel_StepMap: 'Koppling',
    ImportPanel_StepImport: 'Import',
    ImportPanel_StepDone: 'Klart',
    ImportPanel_ImportAsNewProjectHeader: 'Importera fil som nytt projekt',
    ImportPanel_ImportIntoProjectHeader: 'Importera uppgifter till {projectName}',
    ImportPanel_CouldNotParseFile: 'Det gick inte att tolka filen.',
    ImportPanel_CouldNotLoadPlannerTasks: 'Det gick inte att läsa in uppgifter från denna plan.',
    ImportPanel_CouldNotCreateProjectDetail: 'Det gick inte att skapa projektet: {detail}',
    ImportPanel_CouldNotLinkDependencies: 'Det gick inte att koppla beroenden: {detail}',
    ImportPanel_UnknownError: 'okänt fel',

    // ── Column mapper (import) ──
    ColumnMapper_TaskNameRequiredBanner: 'Uppgiftsnamn måste kopplas för att fortsätta.',
    ColumnMapper_SkippedColumnsBanner: '{count} kolumn(er) kommer att hoppas över.',
    ColumnMapper_SourceColumnHeader: 'Källkolumn',
    ColumnMapper_TargetFieldHeader: 'Målfält',
    ColumnMapper_StatusHeader: 'Status',
    ColumnMapper_SkippedBadge: 'Överhoppad',
    ColumnMapper_AutoMappedBadge: 'Automatiskt kopplad',
    ColumnMapper_SetBadge: 'Angiven',
    ColumnMapper_PreviewTitle: 'Förhandsgranskning: {columnName}',
    ColumnMapper_EmptyCellDash: '—',

    // ── Import field display names / ImportService ──
    ImportField_TaskName: 'Uppgiftsnamn',
    ImportField_StartDate: 'Startdatum',
    ImportField_DueDate: 'Förfallodatum',
    ImportField_Status: 'Status',
    ImportField_Priority: 'Prioritet',
    ImportField_AssignedTo: 'Tilldelad till',
    ImportField_AssignedToEmail: 'E-post för tilldelad',
    ImportField_PercentComplete: '% klart',
    ImportField_Phase: 'Fas',
    ImportField_Description: 'Beskrivning',
    ImportField_Notes: 'Anteckningar',
    ImportField_IsMilestone: 'Är milstolpe',
    ImportField_Dependencies: 'Beroenden',
    ImportField_SkipColumn: '(Hoppa över denna kolumn)',
    ImportService_EmptyFileError: 'Filen verkar vara tom eller saknar datarader.',
    ImportService_ReadErrorDetail: 'Det gick inte att läsa filen: {detail}.',
    ImportService_FileReadError: 'Fel vid filläsning.',
    ImportService_RowError: 'Rad {rowNum} ("{title}"): {error}',
    ImportService_AmbiguousDependency: 'Beroendet "{name}" matchar fler än ett uppgiftsnamn — hoppades över.',
    ImportService_LinkDependencyError: 'Det gick inte att koppla beroenden för uppgift {taskId}: {error}',

    // ── Health labels (shared: healthUtils.ts and ExportService.ts both use this set; also replaces the duplicated Export_PortfolioHealthLabel* keys) ──
    Health_Done: 'Klart',
    Health_OnTrack: 'Enligt plan',
    Health_AtRisk: 'I riskzonen',
    Health_Overdue: 'Försenad',

    // ── Status / Priority display labels (DISPLAY-ONLY — stored SharePoint Choice values remain unchanged/English) ──
    Status_NotStarted: 'Ej påbörjad',
    Status_InProgress: 'Pågår',
    Status_Completed: 'Slutförd',
    Status_OnHold: 'Pausad',
    Status_Cancelled: 'Avbruten',
    Priority_Critical: 'Kritisk',
    Priority_High: 'Hög',
    Priority_Medium: 'Medel',
    Priority_Low: 'Låg',
    ProjectStatus_Planning: 'Planering',
    ProjectStatus_Active: 'Aktivt',
    ProjectStatus_OnHold: 'Pausat',
    ProjectStatus_Completed: 'Slutfört',
    ProjectStatus_Cancelled: 'Avbrutet',

    // ── Shell (SmartGantt.tsx) ──
    SmartGantt_LoadingProjects: 'Läser in projekt…',
    SmartGantt_UnableToLoad: 'Det går inte att läsa in',
    SmartGantt_RetryButton: 'Försök igen',
    SmartGantt_NoProjectsYet: 'Inga projekt än',
    SmartGantt_NoProjectsSubtitle: 'Skapa ditt första projekt för att komma igång.',
    SmartGantt_CreateFirstProjectButton: '+ Skapa första projektet',
    SmartGantt_ImportFromExcelButton: '📥 Importera från Excel',
    SmartGantt_LoadingTasks: 'Läser in uppgifter…',
    SmartGantt_DismissAriaLabel: 'Stäng',
    SmartGantt_DeleteTaskDialogTitle: 'Ta bort uppgift',
    SmartGantt_DeleteTaskDialogSubtext: 'Är du säker på att du vill ta bort "{taskTitle}"? Detta kan inte ångras.',
    SmartGantt_DeleteButton: 'Ta bort',
    SmartGantt_CancelButton: 'Avbryt',
    SmartGantt_ArchiveProjectDialogTitle: 'Arkivera projekt',
    SmartGantt_ArchiveProjectDialogSubtext: 'Arkivera "{projectTitle}"? Du kan återställa det senare.',
    SmartGantt_ArchiveButton: 'Arkivera',
    SmartGantt_SendToRecycleBinDialogTitle: 'Skicka till papperskorgen',
    SmartGantt_SendToRecycleBinDialogSubtext: 'Skicka "{projectTitle}" till webbplatsens papperskorg?',
    SmartGantt_SendToRecycleBinButton: 'Skicka till papperskorgen',
    SmartGantt_FailedLoadProjects: 'Det gick inte att läsa in projekt. Kontrollera webbplatsens behörigheter.',
    SmartGantt_FailedLoadTasks: 'Det gick inte att läsa in uppgifter för detta projekt.',
    SmartGantt_FailedLoadPortfolioStats: 'Det gick inte att läsa in portföljstatistik.',
    SmartGantt_CouldNotSaveProject: 'Det gick inte att spara projektet: {message}',
    SmartGantt_CouldNotDeleteProject: 'Det gick inte att ta bort projektet: {message}',
    SmartGantt_CouldNotArchiveProject: 'Det gick inte att arkivera projektet: {message}',
    SmartGantt_CouldNotUnarchiveProject: 'Det gick inte att återställa projektet: {message}',
    SmartGantt_CouldNotSaveTask: 'Det gick inte att spara uppgiften: {message}',
    SmartGantt_CouldNotDeleteTask: 'Det gick inte att ta bort uppgiften: {message}',
    SmartGantt_ImageExportFailed: 'Bildexporten misslyckades: {message}',
    SmartGantt_PowerPointExportFailed: 'PowerPoint-exporten misslyckades: {message}',
    SmartGantt_PortfolioExportFailed: 'Portföljexporten misslyckades: {message}',
    SmartGantt_CouldNotUpdateTask: 'Det gick inte att uppdatera uppgiften: {message}',

    // ── Common ──
    ColorSwatch_AutoColorAriaLabel: 'Automatisk färg',
    ColorSwatch_CustomColorAriaLabel: 'Anpassad färg',
    ColorSwatch_PickCustomColorTitle: 'Välj en anpassad färg',

    // ── Export (Excel / PowerPoint) ──
    Export_ColTaskName: 'Uppgiftsnamn',
    Export_ColPhase: 'Fas',
    Export_ColStartDate: 'Startdatum',
    Export_ColDueDate: 'Förfallodatum',
    Export_ColStatus: 'Status',
    Export_ColPriority: 'Prioritet',
    Export_ColAssignedTo: 'Tilldelad till',
    Export_ColAssignedToEmail: 'E-post för tilldelad',
    Export_ColPercentComplete: '% klart',
    Export_ColIsMilestone: 'Är milstolpe',
    Export_ColDescription: 'Beskrivning',
    Export_ColNotes: 'Anteckningar',
    Export_Yes: 'Ja',
    Export_No: 'Nej',
    Export_SheetNameTasks: 'Uppgifter',
    Export_ExcelFileSuffix: ' - Uppgifter.xlsx',
    Export_TaskNameColumnLabel: 'UPPGIFTSNAMN',
    Export_ExportedDateLabel: 'Exporterad {date}',
    Export_ProjectReportLabel: 'PROJEKTRAPPORT',
    Export_StatusLine: 'Status: {status}',
    Export_DateRangeSeparator: ' till ',
    Export_ProjectManagerLine: 'Projektledare: {name}',
    Export_GeneratedDateLine: 'Genererad {date}',
    Export_ProjectSummaryTitle: 'Projektsammanfattning',
    Export_StatTotalTasks: 'Totalt antal uppgifter',
    Export_StatCompleted: 'Slutförda',
    Export_StatInProgress: 'Pågår',
    Export_StatOnHold: 'Pausade',
    Export_StatNotStarted: 'Ej påbörjade',
    Export_OverallProgressLine: 'Totalt förlopp',
    Export_OverallProgressPercent: '{percent}%',
    Export_StatusBreakdownTitle: 'Statusfördelning',
    Export_StatusBreakdownRow: '{status}: {count} ({percent}%)',
    Export_GanttTimelineTitle: 'Gantt-tidslinje',
    Export_SummaryRecentActivityTitle: 'Senaste aktivitet',
    Export_ProjectOverviewLabel: 'Projektöversikt',
    Export_DetailStatusLabel: 'Status',
    Export_DetailStartDateLabel: 'Startdatum',
    Export_DetailDueDateLabel: 'Förfallodatum',
    Export_DetailProjectManagerLabel: 'Projektledare',
    Export_Past7DaysLabel: 'Senaste 7 dagarna',
    Export_NoActivityMessage: 'Ingen senaste aktivitet.',
    Export_CompletedThisWeekHeader: 'Slutförda denna vecka ({count})',
    Export_NewBadge: 'NYTT  ',
    Export_CompletedPercentLine: '{percent}% klart',
    Export_MoreItemsSuffix: '+ {count} till',
    Export_InProgressUpdatedHeader: 'Pågår / Uppdaterade',
    Export_StatusPercentLine: '{status} — {percent}%',
    Export_PortfolioReportLabel: 'PORTFÖLJRAPPORT',
    Export_PortfolioOverviewTitle: 'Portföljöversikt',
    Export_ProjectsCountLine: '{count} projekt',
    Export_HealthSummaryOnTrack: '{count} enligt plan',
    Export_HealthSummaryAtRisk: '{count} i riskzonen',
    Export_HealthSummaryOverdue: '{count} försenade',
    Export_ProjectsSummaryHeader: 'Projektsammanfattning',
    Export_TableProject: 'Projekt',
    Export_TableStatus: 'Status',
    Export_TableHealth: 'Hälsostatus',
    Export_TableTotal: 'Totalt',
    Export_TableDone: 'Klara',
    Export_TableActive: 'Aktiva',
    Export_TableAtRisk: 'I riskzonen',
    Export_TableOverdue: 'Försenade',
    Export_TablePctDone: '% klart',
    Export_TableDueDate: 'Förfallodatum',
    Export_PortfolioSummaryFileName: 'Portföljsammanfattning.xlsx',
    Export_PortfolioReportFileName: 'Portföljrapport.pptx',
    Export_ProjectReportFileName: '{projectName} rapport.pptx',
    Export_UnavailableLabel: 'Ej tillgängligt',
    Export_SheetNamePortfolio: 'Portfölj',
    Export_ColStart: 'Start',
    Export_ColDue: 'Förfaller',
    Export_ImageGenerationFailed: 'Det gick inte att generera bilden – diagrammet kan vara för stort för att exporteras som en bild.',
    Export_DrawingContextFailed: 'Det gick inte att skapa en ritkontext för exporten.',
    Export_SvgRenderFailed: 'SVG-rendering misslyckades',
  };
});
