define([], function () {
  return {
    // ── Property pane ──
    PropertyPane_HeaderDescription: 'การตั้งค่า Smart Gantt Chart',
    PropertyPane_GeneralGroupName: 'ทั่วไป',
    PropertyPane_TitleFieldLabel: 'ชื่อเว็บพาร์ต',
    WebPart_DefaultTitle: 'Smart Gantt Chart',

    // ── Toolbar ──
    Toolbar_ViewDashboard: 'แดชบอร์ด',
    Toolbar_ViewList: 'รายการ',
    Toolbar_ViewGantt: 'แกนต์',
    Toolbar_ViewKanban: 'คัมบัง',
    Toolbar_ZoomDay: 'วัน',
    Toolbar_ZoomWeek: 'สัปดาห์',
    Toolbar_ZoomMonth: 'เดือน',
    Toolbar_ZoomQuarter: 'ไตรมาส',
    Toolbar_SelectProjectAriaLabel: 'เลือกโครงการ',
    Toolbar_PortfolioLabel: 'พอร์ตโฟลิโอ',
    Toolbar_SelectAProject: 'เลือกโครงการ',
    Toolbar_AllProjectsSubtext: 'โครงการทั้งหมด',
    Toolbar_NoProjectsYet: 'ยังไม่มีโครงการ',
    Toolbar_ArchivedBadge: 'เก็บถาวรแล้ว',
    Toolbar_ShowArchivedProjects: 'แสดงโครงการที่เก็บถาวร',
    Toolbar_NewProject: '+ โครงการใหม่',
    Toolbar_ImportFileAsNewProject: '📥 นำเข้าไฟล์เป็นโครงการใหม่…',
    Toolbar_AddTask: '+ เพิ่มงาน',
    Toolbar_EditProject: 'แก้ไขโครงการ',
    Toolbar_OptionsButton: '⚙ ตัวเลือก',
    Toolbar_MoreOptionsTitle: 'ตัวเลือกเพิ่มเติม',
    Toolbar_ExportToExcel: '📊 ส่งออกไปยัง Excel',
    Toolbar_ExportToPowerPoint: '📑 ส่งออกไปยัง PowerPoint',
    Toolbar_ScrollToTodayTitle: 'เลื่อนไปยังวันนี้',
    Toolbar_TodayButton: '◉ วันนี้',
    Toolbar_ImportTasks: '📥 นำเข้างาน…',
    Toolbar_ExportAsImage: '🖼 ส่งออกเป็นรูปภาพ (PNG)',
    Toolbar_UnarchiveProject: '📂 ยกเลิกการเก็บถาวรโครงการ',
    Toolbar_ArchiveProject: '🗄️ เก็บถาวรโครงการ',
    Toolbar_SendToRecycleBin: '🗑️ ส่งไปยังถังรีไซเคิล',

    // ── Filter bar ──
    FilterBar_ClearOption: 'ล้าง',
    FilterBar_DueAny: 'วันครบกำหนดใดก็ได้',
    FilterBar_DueOverdue: 'เกินกำหนด',
    FilterBar_DueToday: 'ครบกำหนดวันนี้',
    FilterBar_DueWeek: 'ครบกำหนดใน 7 วัน',
    FilterBar_SearchPlaceholder: 'ค้นหางาน…',
    FilterBar_SearchAriaLabel: 'ค้นหางาน',
    FilterBar_StatusChipLabel: 'สถานะ',
    FilterBar_PriorityChipLabel: 'ลำดับความสำคัญ',
    FilterBar_AssigneeChipLabel: 'ผู้รับผิดชอบ',
    FilterBar_PhaseChipLabel: 'ระยะ',
    FilterBar_DueDateAriaLabel: 'กรองตามวันครบกำหนด',
    FilterBar_MatchCount: '{matchCount} จาก {totalCount}',
    FilterBar_ClearFilters: '✕ ล้างตัวกรอง',
    FilterBar_ChipLabelWithCount: '{label} ({count}) ▾',
    FilterBar_ChipLabelNoCount: '{label} ▾',

    // ── Gantt view ──
    Gantt_TaskColumnHeader: 'งาน',
    Gantt_DurationColumnHeader: 'ระยะเวลา',
    Gantt_AddTaskButton: '+ เพิ่มงาน',
    Gantt_EmptyTitle: 'ยังไม่มีงาน',
    Gantt_EmptySubtitle: 'เพิ่มงานเพื่อดูในแผนภูมิแกนต์',
    Gantt_AddFirstTask: '+ เพิ่มงานแรก',
    Gantt_ImportTasksButton: '📥 นำเข้างาน',
    Gantt_EditTitle: 'แก้ไข',
    Gantt_DeleteTitle: 'ลบ',
    Gantt_EditTaskAriaLabel: 'แก้ไขงาน {taskTitle}',
    Gantt_DeleteTaskAriaLabel: 'ลบงาน {taskTitle}',
    Gantt_ExpandPhaseAriaLabel: '{action}ระยะ {phase}',
    Gantt_ExpandAction: 'ขยาย',
    Gantt_CollapseAction: 'ยุบ',
    Gantt_DependencyViolationTooltip: 'เริ่มต้นก่อนที่งานที่เกี่ยวข้องทั้งหมดจะเสร็จสิ้น',
    Gantt_MilestoneAriaLabel: '{taskTitle}, เหตุการณ์สำคัญ, {date}',
    Gantt_BarAriaLabel: '{taskTitle}, {startDate} ถึง {dueDate}, เสร็จสมบูรณ์ {percent}%',
    Gantt_PercentCompleteTooltip: 'เสร็จสมบูรณ์ {value}%',

    // ── Gantt options/settings panel ──
    GanttSettings_PanelHeader: '⚙ ตัวเลือก',
    GanttSettings_ColorCodingSection: 'การกำหนดสี',
    GanttSettings_ByStatus: 'ตามสถานะ',
    GanttSettings_ByPriority: 'ตามลำดับความสำคัญ',
    GanttSettings_ByPhase: 'ตามระยะ',
    GanttSettings_ByHealth: 'ตามสถานะความคืบหน้า',
    GanttSettings_HeaderColorSection: 'สีส่วนหัว',
    GanttSettings_ThemeDark: 'มืด',
    GanttSettings_ThemeNavy: 'กรมท่า',
    GanttSettings_ThemeTeal: 'เขียวอมฟ้า',
    GanttSettings_ThemePurple: 'ม่วง',
    GanttSettings_ThemeLight: 'สว่าง',
    GanttSettings_HeaderLabelsSection: 'ป้ายกำกับส่วนหัว',
    GanttSettings_WeekLabelDates: 'วันที่',
    GanttSettings_WeekLabelDatesDesc: '3 มิ.ย., 10 มิ.ย.…',
    GanttSettings_WeekLabelProject: 'สัปดาห์ของโครงการ',
    GanttSettings_WeekLabelProjectDesc: 'W1, W2…',
    GanttSettings_WeekLabelIso: 'สัปดาห์ปฏิทิน',
    GanttSettings_WeekLabelIsoDesc: 'W23, W24…',
    GanttSettings_ProjectWeeksHint: 'สัปดาห์ที่ 1 เริ่มต้นวันจันทร์ของงานแรกสุดของคุณ — เหมาะสำหรับการนำเสนอ',
    GanttSettings_BarStyleSection: 'รูปแบบแท่ง',
    GanttSettings_BarStyleGradient: 'ไล่ระดับสี',
    GanttSettings_BarStyleFlat: 'สีเรียบ',
    GanttSettings_RowHeightSection: 'ความสูงของแถว',
    GanttSettings_HeightCompact: 'กะทัดรัด',
    GanttSettings_HeightNormal: 'ปกติ',
    GanttSettings_HeightSpacious: 'กว้างขวาง',
    GanttSettings_ShowHideSection: 'แสดง / ซ่อน',
    GanttSettings_WeekendShading: 'แรเงาวันหยุดสุดสัปดาห์',
    GanttSettings_DependencyArrows: 'ลูกศรแสดงความสัมพันธ์',
    GanttSettings_CriticalPathAlwaysVisible: 'แสดงเส้นทางวิกฤตตลอดเวลา',
    GanttSettings_AllOthersOnHoverOnly: 'แสดงรายการอื่นเมื่อวางเมาส์เท่านั้น',
    GanttSettings_CriticalPathHighlight: 'ไฮไลต์เส้นทางวิกฤต',
    GanttSettings_ProgressPercentOnBars: 'แสดง % ความคืบหน้าบนแท่ง',
    GanttSettings_AssigneeNameOnBars: 'แสดงชื่อผู้รับผิดชอบบนแท่ง',
    GanttSettings_HealthStatusBadges: 'ป้ายสถานะความคืบหน้า',

    // ── List view ──
    ListView_ColTaskName: 'ชื่องาน',
    ListView_ColStatus: 'สถานะ',
    ListView_ColHealth: 'สถานะความคืบหน้า',
    ListView_ColPriority: 'ลำดับความสำคัญ',
    ListView_ColStart: 'เริ่มต้น',
    ListView_ColDue: 'ครบกำหนด',
    ListView_ColAssignedTo: 'มอบหมายให้',
    ListView_ColProgress: 'ความคืบหน้า',
    ListView_ColPhase: 'ระยะ',
    ListView_ColPredecessors: 'งานก่อนหน้า',
    ListView_EmptyTitle: 'ยังไม่มีงาน',
    ListView_AddFirstTask: '+ เพิ่มงานแรก',
    ListView_AddTaskRow: '+ เพิ่มงาน',
    ListView_Unassigned: 'ยังไม่ได้มอบหมาย',
    ListView_DependencyViolationTooltip: 'เริ่มต้นก่อนที่งานที่เกี่ยวข้องทั้งหมดจะเสร็จสิ้น',
    ListView_StatusAriaLabel: 'สถานะของ {taskTitle}',
    ListView_PriorityAriaLabel: 'ลำดับความสำคัญของ {taskTitle}',
    ListView_EditTaskAriaLabel: 'แก้ไขงาน {taskTitle}',
    ListView_DeleteTaskAriaLabel: 'ลบงาน {taskTitle}',
    ListView_EditTitle: 'แก้ไข',
    ListView_DeleteTitle: 'ลบ',

    // ── Kanban view ──
    Kanban_ColumnNotStarted: 'ยังไม่เริ่ม',
    Kanban_ColumnInProgress: 'กำลังดำเนินการ',
    Kanban_ColumnOnHold: 'ระงับชั่วคราว',
    Kanban_ColumnCompleted: 'เสร็จสมบูรณ์',
    Kanban_ColumnCancelled: 'ยกเลิกแล้ว',
    Kanban_AddTaskButton: '+ เพิ่มงาน',
    Kanban_EditTitle: 'แก้ไข',
    Kanban_DeleteTitle: 'ลบ',
    Kanban_CardAriaLabel: '{taskTitle}, {status} กด Enter เพื่อแก้ไข กดลูกศรซ้ายหรือขวาเพื่อเปลี่ยนสถานะ',
    Kanban_EditTaskAriaLabel: 'แก้ไขงาน {taskTitle}',
    Kanban_DeleteTaskAriaLabel: 'ลบงาน {taskTitle}',

    // ── Dashboard view ──
    Dashboard_TotalTasks: 'งานทั้งหมด',
    Dashboard_Completed: 'เสร็จสมบูรณ์',
    Dashboard_InProgress: 'กำลังดำเนินการ',
    Dashboard_OnHold: 'ระงับชั่วคราว',
    Dashboard_NotStarted: 'ยังไม่เริ่ม',
    Dashboard_Cancelled: 'ยกเลิกแล้ว',
    Dashboard_OverallProgress: 'ความคืบหน้าโดยรวม',
    Dashboard_ProjectManagerLabel: 'ผู้จัดการโครงการ: {name}',
    Dashboard_PhaseProgressHeader: 'ความคืบหน้าตามระยะ',
    Dashboard_StatusBreakdownHeader: 'สรุปตามสถานะ',
    Dashboard_PriorityBreakdownHeader: 'สรุปตามลำดับความสำคัญ',
    Dashboard_PriorityCritical: 'วิกฤต',
    Dashboard_PriorityHigh: 'สูง',
    Dashboard_PriorityMedium: 'ปานกลาง',
    Dashboard_PriorityLow: 'ต่ำ',
    Dashboard_OverdueHeader: 'เกินกำหนด  ({count})',
    Dashboard_DueNext14DaysHeader: 'ครบกำหนดภายใน 14 วัน  ({count})',
    Dashboard_CompletedThisWeekHeader: 'เสร็จสมบูรณ์สัปดาห์นี้',
    Dashboard_UpdatedThisWeekHeader: 'อัปเดตสัปดาห์นี้',
    Dashboard_Today: 'วันนี้',
    Dashboard_Tomorrow: 'พรุ่งนี้',
    Dashboard_DaysLeft: '{days} วัน',
    Dashboard_EmptyTitle: 'ยังไม่มีงาน',
    Dashboard_EmptySubtitle: 'เพิ่มงานเพื่อดูแดชบอร์ดโครงการของคุณ',
    Dashboard_AddTaskButton: '+ เพิ่มงาน',

    // ── Portfolio view ──
    Portfolio_ProjectCount: '{count} โครงการ{plural}',
    Portfolio_OnTrackSummary: '{count} เป็นไปตามแผน',
    Portfolio_AtRiskSummary: '{count} มีความเสี่ยง',
    Portfolio_OverdueSummary: '{count} เกินกำหนด',
    Portfolio_DoneSummary: '{count} เสร็จสิ้น',
    Portfolio_SortLabel: 'เรียงลำดับ:',
    Portfolio_SortAZ: 'ก-ฮ',
    Portfolio_SortHealth: 'สถานะความคืบหน้า',
    Portfolio_SortStatus: 'สถานะ',
    Portfolio_SortCompletion: 'ความสำเร็จ',
    Portfolio_RefreshTitle: 'รีเฟรช',
    Portfolio_RefreshButton: 'รีเฟรช',
    Portfolio_LoadingStats: 'กำลังโหลดสถิติ…',
    Portfolio_EmptyTitle: 'ยังไม่มีโครงการ',
    Portfolio_CreateFirstProject: '+ สร้างโครงการแรก',
    Portfolio_StatsUnavailable: 'ไม่มีสถิติให้แสดง',
    Portfolio_StatsUnavailableDetail: 'ไม่สามารถโหลดสถิติของโครงการนี้ได้',
    Portfolio_OverallProgressLabel: 'ความคืบหน้าโดยรวม',
    Portfolio_TaskCountDone: 'เสร็จสิ้น',
    Portfolio_TaskCountActive: 'กำลังดำเนินการ',
    Portfolio_TaskCountAtRisk: 'มีความเสี่ยง',
    Portfolio_TaskCountOverdue: 'เกินกำหนด',
    Portfolio_ViewGanttLink: 'ดูแผนภูมิแกนต์ →',
    Portfolio_TodayTooltip: 'วันนี้',

    // ── Task panel ──
    TaskPanel_EditHeader: 'แก้ไข: {taskTitle}',
    TaskPanel_NewTaskHeader: 'งานใหม่',
    TaskPanel_TabBasic: 'พื้นฐาน',
    TaskPanel_TabDetails: 'รายละเอียด',
    TaskPanel_TabLinks: 'ลิงก์',
    TaskPanel_ProjectLabelPrefix: 'โครงการ: ',
    TaskPanel_TaskNameLabel: 'ชื่องาน',
    TaskPanel_TaskNamePlaceholder: 'ป้อนชื่องาน',
    TaskPanel_TaskNameRequired: 'จำเป็นต้องระบุชื่องาน',
    TaskPanel_DescriptionLabel: 'คำอธิบาย',
    TaskPanel_DescriptionPlaceholder: 'ป้อนคำอธิบาย',
    TaskPanel_StartDateLabel: 'วันที่เริ่มต้น',
    TaskPanel_DueDateLabel: 'วันครบกำหนด',
    TaskPanel_DueDateError: 'วันครบกำหนดต้องเป็นวันเดียวกับหรือหลังวันที่เริ่มต้น',
    TaskPanel_StatusLabel: 'สถานะ',
    TaskPanel_PriorityLabel: 'ลำดับความสำคัญ',
    TaskPanel_PercentCompleteLabel: '% เสร็จสมบูรณ์: {percent}%',
    TaskPanel_AssignedToLabel: 'มอบหมายให้',
    TaskPanel_AssignedToPlaceholder: 'ค้นหาบุคคล…',
    TaskPanel_PhaseLabel: 'ระยะ',
    TaskPanel_PhasePlaceholder: 'ป้อนชื่อระยะ',
    TaskPanel_PhaseHint: 'จัดกลุ่มงานในมุมมองแกนต์และรายการ',
    TaskPanel_MilestoneLabel: 'เหตุการณ์สำคัญ',
    TaskPanel_MilestoneOnText: 'ใช่',
    TaskPanel_MilestoneOffText: 'ไม่ใช่',
    TaskPanel_CustomBarColorLabel: 'สีแท่งกำหนดเอง',
    TaskPanel_CustomBarColorOptionalSuffix: ' (ไม่บังคับ)',
    TaskPanel_AutoColorHint: 'สีอัตโนมัติจากการตั้งค่าสถานะ/ลำดับความสำคัญ/ระยะ',
    TaskPanel_NotesLabel: 'บันทึกย่อ',
    TaskPanel_NotesPlaceholder: 'ป้อนบันทึกย่อ',
    TaskPanel_ParentTaskLabel: 'งานหลัก',
    TaskPanel_ParentTaskNone: '(ไม่มี)',
    TaskPanel_ParentTaskHasChildrenHint: 'งานนี้มีงานย่อยแล้ว จึงไม่สามารถมีงานหลักของตัวเองได้',
    TaskPanel_ParentTaskHint: 'ทำให้งานนี้เป็นงานย่อยภายใต้งานอื่น',
    TaskPanel_DependsOnLabel: 'ขึ้นอยู่กับ',
    TaskPanel_RemoveDependencyTitle: 'นำการอ้างอิงถึง "{taskTitle}" ออก',
    TaskPanel_AddDependencyPlaceholder: 'เพิ่มการอ้างอิง…',
    TaskPanel_SelectATaskOption: 'เลือกงาน…',
    TaskPanel_DependsOnHint: 'งานนี้จะเริ่มไม่ได้จนกว่างานที่ระบุจะเสร็จสิ้น',
    TaskPanel_SavingLabel: 'กำลังบันทึก…',
    TaskPanel_CreatingLabel: 'กำลังสร้าง…',
    TaskPanel_SaveChangesButton: 'บันทึกการเปลี่ยนแปลง',
    TaskPanel_CreateTaskButton: 'สร้างงาน',
    TaskPanel_CancelButton: 'ยกเลิก',
    TaskPanel_DismissAriaLabel: 'ปิด',
    TaskPanel_DiscardUnsavedChangesConfirm: 'ต้องการละทิ้งการเปลี่ยนแปลงที่ยังไม่บันทึกหรือไม่?',
    TaskPanel_SaveFallbackError: 'ไม่สามารถบันทึกงานได้',

    // ── Project panel ──
    ProjectPanel_EditHeader: 'แก้ไขโครงการ',
    ProjectPanel_NewHeader: 'โครงการใหม่',
    ProjectPanel_ProjectNameLabel: 'ชื่อโครงการ',
    ProjectPanel_ProjectNamePlaceholder: 'ป้อนชื่อโครงการ',
    ProjectPanel_ProjectNameRequired: 'จำเป็นต้องระบุชื่อโครงการ',
    ProjectPanel_DescriptionLabel: 'คำอธิบาย',
    ProjectPanel_DescriptionPlaceholder: 'ป้อนคำอธิบาย',
    ProjectPanel_ProjectColorLabel: 'สีของโครงการ',
    ProjectPanel_StatusLabel: 'สถานะ',
    ProjectPanel_StartDateLabel: 'วันที่เริ่มต้น',
    ProjectPanel_DueDateLabel: 'วันครบกำหนด',
    ProjectPanel_DueDateError: 'วันครบกำหนดต้องเป็นวันเดียวกับหรือหลังวันที่เริ่มต้น',
    ProjectPanel_WhatHappensNextTitle: 'ขั้นตอนต่อไปคืออะไร?',
    ProjectPanel_WhatHappensNextBody: 'เมื่อสร้างโครงการแล้ว คุณจะสามารถเพิ่มงาน กำหนดระยะ และติดตามความคืบหน้าได้',
    ProjectPanel_SavingLabel: 'กำลังบันทึก…',
    ProjectPanel_CreatingLabel: 'กำลังสร้าง…',
    ProjectPanel_SaveChangesButton: 'บันทึกการเปลี่ยนแปลง',
    ProjectPanel_CreateProjectButton: 'สร้างโครงการ',
    ProjectPanel_CancelButton: 'ยกเลิก',
    ProjectPanel_DismissAriaLabel: 'ปิด',
    ProjectPanel_DiscardUnsavedChangesConfirm: 'ต้องการละทิ้งการเปลี่ยนแปลงที่ยังไม่บันทึกหรือไม่?',
    ProjectPanel_SaveFallbackError: 'ไม่สามารถบันทึกโครงการได้',

    // ── Import panel ──
    ImportPanel_SourceExcelTitle: 'ไฟล์ Excel / CSV',
    ImportPanel_SourceExcelSubtitle: 'นำเข้างานจากสเปรดชีต',
    ImportPanel_SourcePlannerTitle: 'Microsoft Planner',
    ImportPanel_SourcePlannerSubtitle: 'นำเข้างานจากแผนของ Planner',
    ImportPanel_ClickToBrowse: 'คลิกเพื่อเรียกดู',
    ImportPanel_DragDropSuffix: ' หรือลากและวาง',
    ImportPanel_SupportedExtensions: 'รองรับ .xlsx, .xls, .csv',
    ImportPanel_RowsColsSummary: 'พบ {rows} แถว {cols} คอลัมน์',
    ImportPanel_LoadingPlannerPlans: 'กำลังโหลดแผนของ Planner…',
    ImportPanel_PlannerLoadError: 'ไม่สามารถโหลดแผนของ Planner ได้',
    ImportPanel_PlannerPermissionsHintPrefix: 'ตรวจสอบให้แน่ใจว่าคุณมีสิทธิ์เข้าถึง Planner และ ',
    ImportPanel_PlannerPermissionsHintEmphasis: 'งานจาก Planner และ To Do',
    ImportPanel_PlannerPermissionsHintSuffix: ' พร้อมใช้งานในไซต์นี้',
    ImportPanel_NoPlannerPlansFoundTitle: 'ไม่พบแผนของ Planner',
    ImportPanel_NoPlannerPlansFoundBody: 'คุณอาจไม่มีสิทธิ์เข้าถึงแผนของ Planner ใด ๆ หรือไม่มีแผนสำหรับบัญชีนี้',
    ImportPanel_TaskCountFoundIn: 'พบงาน {count} รายการใน "{planName}"',
    ImportPanel_ProjectDetailsIntroPrefix: 'กำลังนำเข้าไปยัง ',
    ImportPanel_ProjectDetailsIntroSuffix: ' โปรดตรวจสอบรายละเอียดโครงการด้านล่าง',
    ImportPanel_ProjectNameLabel: 'ชื่อโครงการ',
    ImportPanel_DescriptionLabel: 'คำอธิบาย',
    ImportPanel_StatusLabel: 'สถานะ',
    ImportPanel_ColorLabel: 'สี',
    ImportPanel_MapIntro: 'จับคู่คอลัมน์จากไฟล์ของคุณกับฟิลด์ของงาน',
    ImportPanel_CreatingProjectStatus: 'กำลังสร้างโครงการ…',
    ImportPanel_ImportingTasksStatus: 'กำลังนำเข้างาน…',
    ImportPanel_ProgressLabel: '{done} จาก {total}',
    ImportPanel_CouldNotCreateProject: 'ไม่สามารถสร้างโครงการได้',
    ImportPanel_ImportCompletedWithErrors: 'การนำเข้าเสร็จสิ้นโดยมีข้อผิดพลาด {count} รายการ',
    ImportPanel_ProjectCreatedSuccess: 'สร้างโครงการสำเร็จแล้ว!',
    ImportPanel_ImportSuccessful: 'นำเข้าสำเร็จ!',
    ImportPanel_TasksAddedTo: 'เพิ่มงาน {count} รายการไปยัง "{projectName}"',
    ImportPanel_FailedRowsLabel: 'แถวที่ล้มเหลว:',
    ImportPanel_CloseButton: 'ปิด',
    ImportPanel_OpenProjectButton: 'เปิดโครงการ',
    ImportPanel_ViewImportedTasksButton: 'ดูงานที่นำเข้า',
    ImportPanel_NextMapColumnsButton: 'ถัดไป: จับคู่คอลัมน์',
    ImportPanel_ImportNTasksButton: 'นำเข้างาน {count} รายการ',
    ImportPanel_BackButton: 'ย้อนกลับ',
    ImportPanel_CancelButton: 'ยกเลิก',
    ImportPanel_NextButton: 'ถัดไป',
    ImportPanel_StepSource: 'แหล่งที่มา',
    ImportPanel_StepProject: 'โครงการ',
    ImportPanel_StepMap: 'จับคู่',
    ImportPanel_StepImport: 'นำเข้า',
    ImportPanel_StepDone: 'เสร็จสิ้น',
    ImportPanel_ImportAsNewProjectHeader: 'นำเข้าไฟล์เป็นโครงการใหม่',
    ImportPanel_ImportIntoProjectHeader: 'นำเข้างานไปยัง {projectName}',
    ImportPanel_CouldNotParseFile: 'ไม่สามารถประมวลผลไฟล์ได้',
    ImportPanel_CouldNotLoadPlannerTasks: 'ไม่สามารถโหลดงานจากแผนนี้ได้',
    ImportPanel_CouldNotCreateProjectDetail: 'ไม่สามารถสร้างโครงการได้: {detail}',
    ImportPanel_CouldNotLinkDependencies: 'ไม่สามารถเชื่อมโยงการอ้างอิงได้: {detail}',
    ImportPanel_UnknownError: 'ข้อผิดพลาดที่ไม่ทราบสาเหตุ',

    // ── Column mapper (import) ──
    ColumnMapper_TaskNameRequiredBanner: 'ต้องจับคู่ชื่องานก่อนจึงจะดำเนินการต่อได้',
    ColumnMapper_SkippedColumnsBanner: 'จะข้าม {count} คอลัมน์',
    ColumnMapper_SourceColumnHeader: 'คอลัมน์ต้นทาง',
    ColumnMapper_TargetFieldHeader: 'ฟิลด์ปลายทาง',
    ColumnMapper_StatusHeader: 'สถานะ',
    ColumnMapper_SkippedBadge: 'ข้ามแล้ว',
    ColumnMapper_AutoMappedBadge: 'จับคู่อัตโนมัติ',
    ColumnMapper_SetBadge: 'กำหนดแล้ว',
    ColumnMapper_PreviewTitle: 'ตัวอย่าง: {columnName}',
    ColumnMapper_EmptyCellDash: '—',

    // ── Import field display names / ImportService ──
    ImportField_TaskName: 'ชื่องาน',
    ImportField_StartDate: 'วันที่เริ่มต้น',
    ImportField_DueDate: 'วันครบกำหนด',
    ImportField_Status: 'สถานะ',
    ImportField_Priority: 'ลำดับความสำคัญ',
    ImportField_AssignedTo: 'มอบหมายให้',
    ImportField_AssignedToEmail: 'อีเมลของผู้ได้รับมอบหมาย',
    ImportField_PercentComplete: '% เสร็จสมบูรณ์',
    ImportField_Phase: 'ระยะ',
    ImportField_Description: 'คำอธิบาย',
    ImportField_Notes: 'บันทึกย่อ',
    ImportField_IsMilestone: 'เป็นเหตุการณ์สำคัญ',
    ImportField_Dependencies: 'การอ้างอิง',
    ImportField_SkipColumn: '(ข้ามคอลัมน์นี้)',
    ImportService_EmptyFileError: 'ไฟล์ดูเหมือนจะว่างเปล่าหรือไม่มีแถวข้อมูล',
    ImportService_ReadErrorDetail: 'ไม่สามารถอ่านไฟล์ได้: {detail}',
    ImportService_FileReadError: 'เกิดข้อผิดพลาดในการอ่านไฟล์',
    ImportService_RowError: 'แถว {rowNum} ("{title}"): {error}',
    ImportService_AmbiguousDependency: 'การอ้างอิง "{name}" ตรงกับชื่องานมากกว่าหนึ่งรายการ — ถูกข้ามไป',
    ImportService_LinkDependencyError: 'ไม่สามารถเชื่อมโยงการอ้างอิงสำหรับงาน {taskId} ได้: {error}',

    // ── Health labels (shared: healthUtils.ts and ExportService.ts both use this set; also replaces the duplicated Export_PortfolioHealthLabel* keys) ──
    Health_Done: 'เสร็จสิ้น',
    Health_OnTrack: 'เป็นไปตามแผน',
    Health_AtRisk: 'มีความเสี่ยง',
    Health_Overdue: 'เกินกำหนด',

    // ── Status / Priority display labels (DISPLAY-ONLY — stored SharePoint Choice values remain unchanged/English) ──
    Status_NotStarted: 'ยังไม่เริ่ม',
    Status_InProgress: 'กำลังดำเนินการ',
    Status_Completed: 'เสร็จสมบูรณ์',
    Status_OnHold: 'ระงับชั่วคราว',
    Status_Cancelled: 'ยกเลิกแล้ว',
    Priority_Critical: 'วิกฤต',
    Priority_High: 'สูง',
    Priority_Medium: 'ปานกลาง',
    Priority_Low: 'ต่ำ',
    ProjectStatus_Planning: 'วางแผน',
    ProjectStatus_Active: 'ดำเนินการอยู่',
    ProjectStatus_OnHold: 'ระงับชั่วคราว',
    ProjectStatus_Completed: 'เสร็จสมบูรณ์',
    ProjectStatus_Cancelled: 'ยกเลิกแล้ว',

    // ── Shell (SmartGantt.tsx) ──
    SmartGantt_LoadingProjects: 'กำลังโหลดโครงการ…',
    SmartGantt_UnableToLoad: 'ไม่สามารถโหลดได้',
    SmartGantt_RetryButton: 'ลองอีกครั้ง',
    SmartGantt_NoProjectsYet: 'ยังไม่มีโครงการ',
    SmartGantt_NoProjectsSubtitle: 'สร้างโครงการแรกของคุณเพื่อเริ่มต้น',
    SmartGantt_CreateFirstProjectButton: '+ สร้างโครงการแรก',
    SmartGantt_ImportFromExcelButton: '📥 นำเข้าจาก Excel',
    SmartGantt_LoadingTasks: 'กำลังโหลดงาน…',
    SmartGantt_DismissAriaLabel: 'ปิด',
    SmartGantt_DeleteTaskDialogTitle: 'ลบงาน',
    SmartGantt_DeleteTaskDialogSubtext: 'คุณแน่ใจหรือไม่ว่าต้องการลบ "{taskTitle}"? การกระทำนี้ไม่สามารถยกเลิกได้',
    SmartGantt_DeleteButton: 'ลบ',
    SmartGantt_CancelButton: 'ยกเลิก',
    SmartGantt_ArchiveProjectDialogTitle: 'เก็บถาวรโครงการ',
    SmartGantt_ArchiveProjectDialogSubtext: 'เก็บถาวร "{projectTitle}" หรือไม่? คุณสามารถยกเลิกการเก็บถาวรได้ในภายหลัง',
    SmartGantt_ArchiveButton: 'เก็บถาวร',
    SmartGantt_SendToRecycleBinDialogTitle: 'ส่งไปยังถังรีไซเคิล',
    SmartGantt_SendToRecycleBinDialogSubtext: 'ส่ง "{projectTitle}" ไปยังถังรีไซเคิลของไซต์หรือไม่?',
    SmartGantt_SendToRecycleBinButton: 'ส่งไปยังถังรีไซเคิล',
    SmartGantt_FailedLoadProjects: 'โหลดโครงการไม่สำเร็จ โปรดตรวจสอบสิทธิ์ของไซต์',
    SmartGantt_FailedLoadTasks: 'โหลดงานสำหรับโครงการนี้ไม่สำเร็จ',
    SmartGantt_FailedLoadPortfolioStats: 'โหลดสถิติพอร์ตโฟลิโอไม่สำเร็จ',
    SmartGantt_CouldNotSaveProject: 'ไม่สามารถบันทึกโครงการได้: {message}',
    SmartGantt_CouldNotDeleteProject: 'ไม่สามารถลบโครงการได้: {message}',
    SmartGantt_CouldNotArchiveProject: 'ไม่สามารถเก็บถาวรโครงการได้: {message}',
    SmartGantt_CouldNotUnarchiveProject: 'ไม่สามารถยกเลิกการเก็บถาวรโครงการได้: {message}',
    SmartGantt_CouldNotSaveTask: 'ไม่สามารถบันทึกงานได้: {message}',
    SmartGantt_CouldNotDeleteTask: 'ไม่สามารถลบงานได้: {message}',
    SmartGantt_ImageExportFailed: 'ส่งออกรูปภาพไม่สำเร็จ: {message}',
    SmartGantt_PowerPointExportFailed: 'ส่งออกไปยัง PowerPoint ไม่สำเร็จ: {message}',
    SmartGantt_PortfolioExportFailed: 'ส่งออกพอร์ตโฟลิโอไม่สำเร็จ: {message}',
    SmartGantt_CouldNotUpdateTask: 'ไม่สามารถอัปเดตงานได้: {message}',

    // ── Common ──
    ColorSwatch_AutoColorAriaLabel: 'สีอัตโนมัติ',
    ColorSwatch_CustomColorAriaLabel: 'สีกำหนดเอง',
    ColorSwatch_PickCustomColorTitle: 'เลือกสีกำหนดเอง',

    // ── Export (Excel / PowerPoint) ──
    Export_ColTaskName: 'ชื่องาน',
    Export_ColPhase: 'ระยะ',
    Export_ColStartDate: 'วันที่เริ่มต้น',
    Export_ColDueDate: 'วันครบกำหนด',
    Export_ColStatus: 'สถานะ',
    Export_ColPriority: 'ลำดับความสำคัญ',
    Export_ColAssignedTo: 'มอบหมายให้',
    Export_ColAssignedToEmail: 'อีเมลของผู้ได้รับมอบหมาย',
    Export_ColPercentComplete: '% เสร็จสมบูรณ์',
    Export_ColIsMilestone: 'เป็นเหตุการณ์สำคัญ',
    Export_ColDescription: 'คำอธิบาย',
    Export_ColNotes: 'บันทึกย่อ',
    Export_Yes: 'ใช่',
    Export_No: 'ไม่ใช่',
    Export_SheetNameTasks: 'งาน',
    Export_ExcelFileSuffix: ' - งาน.xlsx',
    Export_TaskNameColumnLabel: 'ชื่องาน',
    Export_ExportedDateLabel: 'ส่งออกเมื่อ {date}',
    Export_ProjectReportLabel: 'รายงานโครงการ',
    Export_StatusLine: 'สถานะ: {status}',
    Export_DateRangeSeparator: ' ถึง ',
    Export_ProjectManagerLine: 'ผู้จัดการโครงการ: {name}',
    Export_GeneratedDateLine: 'สร้างเมื่อ {date}',
    Export_ProjectSummaryTitle: 'สรุปโครงการ',
    Export_StatTotalTasks: 'งานทั้งหมด',
    Export_StatCompleted: 'เสร็จสมบูรณ์',
    Export_StatInProgress: 'กำลังดำเนินการ',
    Export_StatOnHold: 'ระงับชั่วคราว',
    Export_StatNotStarted: 'ยังไม่เริ่ม',
    Export_OverallProgressLine: 'ความคืบหน้าโดยรวม',
    Export_OverallProgressPercent: '{percent}%',
    Export_StatusBreakdownTitle: 'สรุปตามสถานะ',
    Export_StatusBreakdownRow: '{status}: {count} ({percent}%)',
    Export_GanttTimelineTitle: 'ไทม์ไลน์แกนต์',
    Export_SummaryRecentActivityTitle: 'กิจกรรมล่าสุด',
    Export_ProjectOverviewLabel: 'ภาพรวมโครงการ',
    Export_DetailStatusLabel: 'สถานะ',
    Export_DetailStartDateLabel: 'วันที่เริ่มต้น',
    Export_DetailDueDateLabel: 'วันครบกำหนด',
    Export_DetailProjectManagerLabel: 'ผู้จัดการโครงการ',
    Export_Past7DaysLabel: '7 วันที่ผ่านมา',
    Export_NoActivityMessage: 'ไม่มีกิจกรรมล่าสุด',
    Export_CompletedThisWeekHeader: 'เสร็จสมบูรณ์สัปดาห์นี้ ({count})',
    Export_NewBadge: 'ใหม่  ',
    Export_CompletedPercentLine: 'เสร็จสมบูรณ์ {percent}%',
    Export_MoreItemsSuffix: '+ อีก {count} รายการ',
    Export_InProgressUpdatedHeader: 'กำลังดำเนินการ / อัปเดตแล้ว',
    Export_StatusPercentLine: '{status} — {percent}%',
    Export_PortfolioReportLabel: 'รายงานพอร์ตโฟลิโอ',
    Export_PortfolioOverviewTitle: 'ภาพรวมพอร์ตโฟลิโอ',
    Export_ProjectsCountLine: '{count} โครงการ',
    Export_HealthSummaryOnTrack: '{count} เป็นไปตามแผน',
    Export_HealthSummaryAtRisk: '{count} มีความเสี่ยง',
    Export_HealthSummaryOverdue: '{count} เกินกำหนด',
    Export_ProjectsSummaryHeader: 'สรุปโครงการ',
    Export_TableProject: 'โครงการ',
    Export_TableStatus: 'สถานะ',
    Export_TableHealth: 'สถานะความคืบหน้า',
    Export_TableTotal: 'ทั้งหมด',
    Export_TableDone: 'เสร็จสิ้น',
    Export_TableActive: 'ดำเนินการอยู่',
    Export_TableAtRisk: 'มีความเสี่ยง',
    Export_TableOverdue: 'เกินกำหนด',
    Export_TablePctDone: '% เสร็จสิ้น',
    Export_TableDueDate: 'วันครบกำหนด',
    Export_PortfolioSummaryFileName: 'สรุปพอร์ตโฟลิโอ.xlsx',
    Export_PortfolioReportFileName: 'รายงานพอร์ตโฟลิโอ.pptx',
    Export_ProjectReportFileName: 'รายงาน {projectName}.pptx',
    Export_UnavailableLabel: 'ไม่พร้อมใช้งาน',
    Export_SheetNamePortfolio: 'พอร์ตโฟลิโอ',
    Export_ColStart: 'เริ่มต้น',
    Export_ColDue: 'ครบกำหนด',
    Export_ImageGenerationFailed: 'ไม่สามารถสร้างรูปภาพได้ — แผนภูมิอาจมีขนาดใหญ่เกินไปสำหรับการส่งออกเป็นรูปภาพ',
    Export_DrawingContextFailed: 'ไม่สามารถสร้างบริบทการวาดภาพสำหรับการส่งออกได้',
    Export_SvgRenderFailed: 'การเรนเดอร์ SVG ล้มเหลว',
  };
});
