define([], function () {
  return {
    // ── Property pane ──
    PropertyPane_HeaderDescription: 'การตั้งค่า Smart Gantt Chart',
    PropertyPane_GeneralGroupName: 'ทั่วไป',
    PropertyPane_TitleFieldLabel: 'ชื่อเว็บพาร์ต',
    WebPart_DefaultTitle: 'Smart Gantt Chart',

    // ── Toolbar ──
    Toolbar_ViewDashboard: 'แดชบอร์ด',
    Toolbar_ViewList: 'รายการ',
    Toolbar_ViewGantt: 'แกนต์',
    Toolbar_ViewKanban: 'คัมบัง',
    Toolbar_ZoomDay: 'วัน',
    Toolbar_ZoomWeek: 'สัปดาห์',
    Toolbar_ZoomMonth: 'เดือน',
    Toolbar_ZoomQuarter: 'ไตรมาส',
    Toolbar_SelectProjectAriaLabel: 'เลือกโครงการ',
    Toolbar_PortfolioLabel: 'พอร์ตโฟลิโอ',
    Toolbar_SelectAProject: 'เลือกโครงการ',
    Toolbar_AllProjectsSubtext: 'โครงการทั้งหมด',
    Toolbar_NoProjectsYet: 'ยังไม่มีโครงการ',
    Toolbar_ArchivedBadge: 'เก็บถาวรแล้ว',
    Toolbar_ShowArchivedProjects: 'แสดงโครงการที่เก็บถาวร',
    Toolbar_NewProject: '+ โครงการใหม่',
    Toolbar_ImportFileAsNewProject: '📥 นำเข้าไฟล์เป็นโครงการใหม่…',
    Toolbar_AddTask: '+ เพิ่มงาน',
    Toolbar_EditProject: 'แก้ไขโครงการ',
    Toolbar_OptionsButton: '⚙ ตัวเลือก',
    Toolbar_MoreOptionsTitle: 'ตัวเลือกเพิ่มเติม',
    Toolbar_ExportToExcel: '📊 ส่งออกไปยัง Excel',
    Toolbar_ExportToPowerPoint: '📑 ส่งออกไปยัง PowerPoint',
    Toolbar_ScrollToTodayTitle: 'เลื่อนไปยังวันนี้',
    Toolbar_TodayButton: '◉ วันนี้',
    Toolbar_ImportTasks: '📥 นำเข้างาน…',
    Toolbar_ExportAsImage: '🖼 ส่งออกเป็นรูปภาพ (PNG)',
    Toolbar_UnarchiveProject: '📂 ยกเลิกการเก็บถาวรโครงการ',
    Toolbar_ArchiveProject: '🗄️ เก็บถาวรโครงการ',
    Toolbar_SendToRecycleBin: '🗑️ ส่งไปยังถังรีไซเคิล',

    // ── Filter bar ──
    FilterBar_ClearOption: 'ล้าง',
    FilterBar_DueAny: 'วันครบกำหนดใดก็ได้',
    FilterBar_DueOverdue: 'เกินกำหนด',
    FilterBar_DueToday: 'ครบกำหนดวันนี้',
    FilterBar_DueWeek: 'ครบกำหนดใน 7 วัน',
    FilterBar_SearchPlaceholder: 'ค้นหางาน…',
    FilterBar_SearchAriaLabel: 'ค้นหางาน',
    FilterBar_StatusChipLabel: 'สถานะ',
    FilterBar_PriorityChipLabel: 'ลำดับความสำคัญ',
    FilterBar_AssigneeChipLabel: 'ผู้รับผิดชอบ',
    FilterBar_PhaseChipLabel: 'ระยะ',
    FilterBar_DueDateAriaLabel: 'กรองตามวันครบกำหนด',
    FilterBar_MatchCount: '{matchCount} จาก {totalCount}',
    FilterBar_ClearFilters: '✕ ล้างตัวกรอง',
    FilterBar_ChipLabelWithCount: '{label} ({count}) ▾',
    FilterBar_ChipLabelNoCount: '{label} ▾',

    // ── Gantt view ──
    Gantt_TaskColumnHeader: 'งาน',
    Gantt_DurationColumnHeader: 'ระยะเวลา',
    Gantt_AddTaskButton: '+ เพิ่มงาน',
    Gantt_EmptyTitle: 'ยังไม่มีงาน',
    Gantt_EmptySubtitle: 'เพิ่มงานเพื่อดูในแผนภูมิแกนต์',
    Gantt_AddFirstTask: '+ เพิ่มงานแรก',
    Gantt_ImportTasksButton: '📥 นำเข้างาน',
    Gantt_EditTitle: 'แก้ไข',
    Gantt_DeleteTitle: 'ลบ',
    Gantt_EditTaskAriaLabel: 'แก้ไขงาน {taskTitle}',
    Gantt_DeleteTaskAriaLabel: 'ลบงาน {taskTitle}',
    Gantt_ExpandPhaseAriaLabel: '{action}ระยะ {phase}',
    Gantt_ExpandAction: 'ขยาย',
    Gantt_CollapseAction: 'ยุบ',
    Gantt_DependencyViolationTooltip: 'เริ่มต้นก่อนที่งานที่เกี่ยวข้องทั้งหมดจะเสร็จสิ้น',
    Gantt_MilestoneAriaLabel: '{taskTitle}, เหตุการณ์สำคัญ, {date}',
    Gantt_BarAriaLabel: '{taskTitle}, {startDate} ถึง {dueDate}, เสร็จสมบูรณ์ {percent}%',
    Gantt_PercentCompleteTooltip: 'เสร็จสมบูรณ์ {value}%',

    // ── Gantt options/settings panel ──
    GanttSettings_PanelHeader: '⚙ ตัวเลือก',
    GanttSettings_ColorCodingSection: 'การกำหนดสี',
    GanttSettings_ByStatus: 'ตามสถานะ',
    GanttSettings_ByPriority: 'ตามลำดับความสำคัญ',
    GanttSettings_ByPhase: 'ตามระยะ',
    GanttSettings_ByHealth: 'ตามสถานะความคืบหน้า',
    GanttSettings_HeaderColorSection: 'สีส่วนหัว',
    GanttSettings_ThemeDark: 'มืด',
    GanttSettings_ThemeNavy: 'กรมท่า',
    GanttSettings_ThemeTeal: 'เขียวอมฟ้า',
    GanttSettings_ThemePurple: 'ม่วง',
    GanttSettings_ThemeLight: 'สว่าง',
    GanttSettings_HeaderLabelsSection: 'ป้ายกำกับส่วนหัว',
    GanttSettings_WeekLabelDates: 'วันที่',
    GanttSettings_WeekLabelDatesDesc: '3 มิ.ย., 10 มิ.ย.…',
    GanttSettings_WeekLabelProject: 'สัปดาห์ของโครงการ',
    GanttSettings_WeekLabelProjectDesc: 'W1, W2…',
    GanttSettings_WeekLabelIso: 'สัปดาห์ปฏิทิน',
    GanttSettings_WeekLabelIsoDesc: 'W23, W24…',
    GanttSettings_ProjectWeeksHint: 'สัปดาห์ที่ 1 เริ่มต้นวันจันทร์ของงานแรกสุดของคุณ — เหมาะสำหรับการนำเสนอ',
    GanttSettings_BarStyleSection: 'รูปแบบแท่ง',
    GanttSettings_BarStyleGradient: 'ไล่ระดับสี',
    GanttSettings_BarStyleFlat: 'สีเรียบ',
    GanttSettings_RowHeightSection: 'ความสูงของแถว',
    GanttSettings_HeightCompact: 'กะทัดรัด',
    GanttSettings_HeightNormal: 'ปกติ',
    GanttSettings_HeightSpacious: 'กว้างขวาง',
    GanttSettings_ShowHideSection: 'แสดง / ซ่อน',
    GanttSettings_WeekendShading: 'แรเงาวันหยุดสุดสัปดาห์',
    GanttSettings_DependencyArrows: 'ลูกศรแสดงความสัมพันธ์',
    GanttSettings_CriticalPathAlwaysVisible: 'แสดงเส้นทางวิกฤตตลอดเวลา',
    GanttSettings_AllOthersOnHoverOnly: 'แสดงรายการอื่นเมื่อวางเมาส์เท่านั้น',
    GanttSettings_CriticalPathHighlight: 'ไฮไลต์เส้นทางวิกฤต',
    GanttSettings_ProgressPercentOnBars: 'แสดง % ความคืบหน้าบนแท่ง',
    GanttSettings_AssigneeNameOnBars: 'แสดงชื่อผู้รับผิดชอบบนแท่ง',
    GanttSettings_HealthStatusBadges: 'ป้ายสถานะความคืบหน้า',

    // ── List view ──
    ListView_ColTaskName: 'ชื่องาน',
    ListView_ColStatus: 'สถานะ',
    ListView_ColHealth: 'สถานะความคืบหน้า',
    ListView_ColPriority: 'ลำดับความสำคัญ',
    ListView_ColStart: 'เริ่มต้น',
    ListView_ColDue: 'ครบกำหนด',
    ListView_ColAssignedTo: 'มอบหมายให้',
    ListView_ColProgress: 'ความคืบหน้า',
    ListView_ColPhase: 'ระยะ',
    ListView_ColPredecessors: 'งานก่อนหน้า',
    ListView_EmptyTitle: 'ยังไม่มีงาน',
    ListView_AddFirstTask: '+ เพิ่มงานแรก',
    ListView_AddTaskRow: '+ เพิ่มงาน',
    ListView_Unassigned: 'ยังไม่ได้มอบหมาย',
    ListView_DependencyViolationTooltip: 'เริ่มต้นก่อนที่งานที่เกี่ยวข้องทั้งหมดจะเสร็จสิ้น',
    ListView_StatusAriaLabel: 'สถานะของ {taskTitle}',
    ListView_PriorityAriaLabel: 'ลำดับความสำคัญของ {taskTitle}',
    ListView_EditTaskAriaLabel: 'แก้ไขงาน {taskTitle}',
    ListView_DeleteTaskAriaLabel: 'ลบงาน {taskTitle}',
    ListView_EditTitle: 'แก้ไข',
    ListView_DeleteTitle: 'ลบ',

    // ── Kanban view ──
    Kanban_ColumnNotStarted: 'ยังไม่เริ่ม',
    Kanban_ColumnInProgress: 'กำลังดำเนินการ',
    Kanban_ColumnOnHold: 'ระงับชั่วคราว',
    Kanban_ColumnCompleted: 'เสร็จสมบูรณ์',
    Kanban_ColumnCancelled: 'ยกเลิกแล้ว',
    Kanban_AddTaskButton: '+ เพิ่มงาน',
    Kanban_EditTitle: 'แก้ไข',
    Kanban_DeleteTitle: 'ลบ',
    Kanban_CardAriaLabel: '{taskTitle}, {status} กด Enter เพื่อแก้ไข กดลูกศรซ้ายหรือขวาเพื่อเปลี่ยนสถานะ',
    Kanban_EditTaskAriaLabel: 'แก้ไขงาน {taskTitle}',
    Kanban_DeleteTaskAriaLabel: 'ลบงาน {taskTitle}',

    // ── Dashboard view ──
    Dashboard_TotalTasks: 'งานทั้งหมด',
    Dashboard_Completed: 'เสร็จสมบูรณ์',
    Dashboard_InProgress: 'กำลังดำเนินการ',
    Dashboard_OnHold: 'ระงับชั่วคราว',
    Dashboard_NotStarted: 'ยังไม่เริ่ม',
    Dashboard_Cancelled: 'ยกเลิกแล้ว',
    Dashboard_OverallProgress: 'ความคืบหน้าโดยรวม',
    Dashboard_ProjectManagerLabel: 'ผู้จัดการโครงการ: {name}',
    Dashboard_PhaseProgressHeader: 'ความคืบหน้าตามระยะ',
    Dashboard_StatusBreakdownHeader: 'สรุปตามสถานะ',
    Dashboard_PriorityBreakdownHeader: 'สรุปตามลำดับความสำคัญ',
    Dashboard_PriorityCritical: 'วิกฤต',
    Dashboard_PriorityHigh: 'สูง',
    Dashboard_PriorityMedium: 'ปานกลาง',
    Dashboard_PriorityLow: 'ต่ำ',
    Dashboard_OverdueHeader: 'เกินกำหนด  ({count})',
    Dashboard_DueNext14DaysHeader: 'ครบกำหนดภายใน 14 วัน  ({count})',
    Dashboard_CompletedThisWeekHeader: 'เสร็จสมบูรณ์สัปดาห์นี้',
    Dashboard_UpdatedThisWeekHeader: 'อัปเดตสัปดาห์นี้',
    Dashboard_Today: 'วันนี้',
    Dashboard_Tomorrow: 'พรุ่งนี้',
    Dashboard_DaysLeft: '{days} วัน',
    Dashboard_EmptyTitle: 'ยังไม่มีงาน',
    Dashboard_EmptySubtitle: 'เพิ่มงานเพื่อดูแดชบอร์ดโครงการของคุณ',
    Dashboard_AddTaskButton: '+ เพิ่มงาน',

    // ── Portfolio view ──
    Portfolio_ProjectCount: '{count} โครงการ{plural}',
    Portfolio_OnTrackSummary: '{count} เป็นไปตามแผน',
    Portfolio_AtRiskSummary: '{count} มีความเสี่ยง',
    Portfolio_OverdueSummary: '{count} เกินกำหนด',
    Portfolio_DoneSummary: '{count} เสร็จสิ้น',
    Portfolio_SortLabel: 'เรียงลำดับ:',
    Portfolio_SortAZ: 'ก-ฮ',
    Portfolio_SortHealth: 'สถานะความคืบหน้า',
    Portfolio_SortStatus: 'สถานะ',
    Portfolio_SortCompletion: 'ความสำเร็จ',
    Portfolio_RefreshTitle: 'รีเฟรช',
    Portfolio_RefreshButton: 'รีเฟรช',
    Portfolio_LoadingStats: 'กำลังโหลดสถิติ…',
    Portfolio_EmptyTitle: 'ยังไม่มีโครงการ',
    Portfolio_CreateFirstProject: '+ สร้างโครงการแรก',
    Portfolio_StatsUnavailable: 'ไม่มีสถิติให้แสดง',
    Portfolio_StatsUnavailableDetail: 'ไม่สามารถโหลดสถิติของโครงการนี้ได้',
    Portfolio_OverallProgressLabel: 'ความคืบหน้าโดยรวม',
    Portfolio_TaskCountDone: 'เสร็จสิ้น',
    Portfolio_TaskCountActive: 'กำลังดำเนินการ',
    Portfolio_TaskCountAtRisk: 'มีความเสี่ยง',
    Portfolio_TaskCountOverdue: 'เกินกำหนด',
    Portfolio_ViewGanttLink: 'ดูแผนภูมิแกนต์ →',
    Portfolio_TodayTooltip: 'วันนี้',

    // ── Task panel ──
    TaskPanel_EditHeader: 'แก้ไข: {taskTitle}',
    TaskPanel_NewTaskHeader: 'งานใหม่',
    TaskPanel_TabBasic: 'พื้นฐาน',
    TaskPanel_TabDetails: 'รายละเอียด',
    TaskPanel_TabLinks: 'ลิงก์',
    TaskPanel_ProjectLabelPrefix: 'โครงการ: ',
    TaskPanel_TaskNameLabel: 'ชื่องาน',
    TaskPanel_TaskNamePlaceholder: 'ป้อนชื่องาน',
    TaskPanel_TaskNameRequired: 'จำเป็นต้องระบุชื่องาน',
    TaskPanel_DescriptionLabel: 'คำอธิบาย',
    TaskPanel_DescriptionPlaceholder: 'ป้อนคำอธิบาย',
    TaskPanel_StartDateLabel: 'วันที่เริ่มต้น',
    TaskPanel_DueDateLabel: 'วันครบกำหนด',
    TaskPanel_DueDateError: 'วันครบกำหนดต้องเป็นวันเดียวกับหรือหลังวันที่เริ่มต้น',
    TaskPanel_StatusLabel: 'สถานะ',
    TaskPanel_PriorityLabel: 'ลำดับความสำคัญ',
    TaskPanel_PercentCompleteLabel: '% เสร็จสมบูรณ์: {percent}%',
    TaskPanel_AssignedToLabel: 'มอบหมายให้',
    TaskPanel_AssignedToPlaceholder: 'ค้นหาบุคคล…',
    TaskPanel_PhaseLabel: 'ระยะ',
    TaskPanel_PhasePlaceholder: 'ป้อนชื่อระยะ',
    TaskPanel_PhaseHint: 'จัดกลุ่มงานในมุมมองแกนต์และรายการ',
    TaskPanel_MilestoneLabel: 'เหตุการณ์สำคัญ',
    TaskPanel_MilestoneOnText: 'ใช่',
    TaskPanel_MilestoneOffText: 'ไม่ใช่',
    TaskPanel_CustomBarColorLabel: 'สีแท่งกำหนดเอง',
    TaskPanel_CustomBarColorOptionalSuffix: ' (ไม่บังคับ)',
    TaskPanel_AutoColorHint: 'สีอัตโนมัติจากการตั้งค่าสถานะ/ลำดับความสำคัญ/ระยะ',
    TaskPanel_NotesLabel: 'บันทึกย่อ',
    TaskPanel_NotesPlaceholder: 'ป้อนบันทึกย่อ',
    TaskPanel_ParentTaskLabel: 'งานหลัก',
    TaskPanel_ParentTaskNone: '(ไม่มี)',
    TaskPanel_ParentTaskHasChildrenHint: 'งานนี้มีงานย่อยแล้ว จึงไม่สามารถมีงานหลักของตัวเองได้',
    TaskPanel_ParentTaskHint: 'ทำให้งานนี้เป็นงานย่อยภายใต้งานอื่น',
    TaskPanel_DependsOnLabel: 'ขึ้นอยู่กับ',
    TaskPanel_RemoveDependencyTitle: 'นำการอ้างอิงถึง "{taskTitle}" ออก',
    TaskPanel_AddDependencyPlaceholder: 'เพิ่มการอ้างอิง…',
    TaskPanel_SelectATaskOption: 'เลือกงาน…',
    TaskPanel_DependsOnHint: 'งานนี้จะเริ่มไม่ได้จนกว่างานที่ระบุจะเสร็จสิ้น',
    TaskPanel_SavingLabel: 'กำลังบันทึก…',
    TaskPanel_CreatingLabel: 'กำลังสร้าง…',
    TaskPanel_SaveChangesButton: 'บันทึกการเปลี่ยนแปลง',
    TaskPanel_CreateTaskButton: 'สร้างงาน',
    TaskPanel_CancelButton: 'ยกเลิก',
    TaskPanel_DismissAriaLabel: 'ปิด',
    TaskPanel_DiscardUnsavedChangesConfirm: 'ต้องการละทิ้งการเปลี่ยนแปลงที่ยังไม่บันทึกหรือไม่?',
    TaskPanel_SaveFallbackError: 'ไม่สามารถบันทึกงานได้',

    // ── Project panel ──
    ProjectPanel_EditHeader: 'แก้ไขโครงการ',
    ProjectPanel_NewHeader: 'โครงการใหม่',
    ProjectPanel_ProjectNameLabel: 'ชื่อโครงการ',
    ProjectPanel_ProjectNamePlaceholder: 'ป้อนชื่อโครงการ',
    ProjectPanel_ProjectNameRequired: 'จำเป็นต้องระบุชื่อโครงการ',
    ProjectPanel_DescriptionLabel: 'คำอธิบาย',
    ProjectPanel_DescriptionPlaceholder: 'ป้อนคำอธิบาย',
    ProjectPanel_ProjectColorLabel: 'สีของโครงการ',
    ProjectPanel_StatusLabel: 'สถานะ',
    ProjectPanel_StartDateLabel: 'วันที่เริ่มต้น',
    ProjectPanel_DueDateLabel: 'วันครบกำหนด',
    ProjectPanel_DueDateError: 'วันครบกำหนดต้องเป็นวันเดียวกับหรือหลังวันที่เริ่มต้น',
    ProjectPanel_WhatHappensNextTitle: 'ขั้นตอนต่อไปคืออะไร?',
    ProjectPanel_WhatHappensNextBody: 'เมื่อสร้างโครงการแล้ว คุณจะสามารถเพิ่มงาน กำหนดระยะ และติดตามความคืบหน้าได้',
    ProjectPanel_SavingLabel: 'กำลังบันทึก…',
    ProjectPanel_CreatingLabel: 'กำลังสร้าง…',
    ProjectPanel_SaveChangesButton: 'บันทึกการเปลี่ยนแปลง',
    ProjectPanel_CreateProjectButton: 'สร้างโครงการ',
    ProjectPanel_CancelButton: 'ยกเลิก',
    ProjectPanel_DismissAriaLabel: 'ปิด',
    ProjectPanel_DiscardUnsavedChangesConfirm: 'ต้องการละทิ้งการเปลี่ยนแปลงที่ยังไม่บันทึกหรือไม่?',
    ProjectPanel_SaveFallbackError: 'ไม่สามารถบันทึกโครงการได้',

    // ── Import panel ──
    ImportPanel_SourceExcelTitle: 'ไฟล์ Excel / CSV',
    ImportPanel_SourceExcelSubtitle: 'นำเข้างานจากสเปรดชีต',
    ImportPanel_SourcePlannerTitle: 'Microsoft Planner',
    ImportPanel_SourcePlannerSubtitle: 'นำเข้างานจากแผนของ Planner',
    ImportPanel_ClickToBrowse: 'คลิกเพื่อเรียกดู',
    ImportPanel_DragDropSuffix: ' หรือลากและวาง',
    ImportPanel_SupportedExtensions: 'รองรับ .xlsx, .xls, .csv',
    ImportPanel_RowsColsSummary: 'พบ {rows} แถว {cols} คอลัมน์',
    ImportPanel_LoadingPlannerPlans: 'กำลังโหลดแผนของ Planner…',
    ImportPanel_PlannerLoadError: 'ไม่สามารถโหลดแผนของ Planner ได้',
    ImportPanel_PlannerPermissionsHintPrefix: 'ตรวจสอบให้แน่ใจว่าคุณมีสิทธิ์เข้าถึง Planner และ ',
    ImportPanel_PlannerPermissionsHintEmphasis: 'งานจาก Planner และ To Do',
    ImportPanel_PlannerPermissionsHintSuffix: ' พร้อมใช้งานในไซต์นี้',
    ImportPanel_NoPlannerPlansFoundTitle: 'ไม่พบแผนของ Planner',
    ImportPanel_NoPlannerPlansFoundBody: 'คุณอาจไม่มีสิทธิ์เข้าถึงแผนของ Planner ใด ๆ หรือไม่มีแผนสำหรับบัญชีนี้',
    ImportPanel_TaskCountFoundIn: 'พบงาน {count} รายการใน "{planName}"',
    ImportPanel_ProjectDetailsIntroPrefix: 'กำลังนำเข้าไปยัง ',
    ImportPanel_ProjectDetailsIntroSuffix: ' โปรดตรวจสอบรายละเอียดโครงการด้านล่าง',
    ImportPanel_ProjectNameLabel: 'ชื่อโครงการ',
    ImportPanel_DescriptionLabel: 'คำอธิบาย',
    ImportPanel_StatusLabel: 'สถานะ',
    ImportPanel_ColorLabel: 'สี',
    ImportPanel_MapIntro: 'จับคู่คอลัมน์จากไฟล์ของคุณกับฟิลด์ของงาน',
    ImportPanel_CreatingProjectStatus: 'กำลังสร้างโครงการ…',
    ImportPanel_ImportingTasksStatus: 'กำลังนำเข้างาน…',
    ImportPanel_ProgressLabel: '{done} จาก {total}',
    ImportPanel_CouldNotCreateProject: 'ไม่สามารถสร้างโครงการได้',
    ImportPanel_ImportCompletedWithErrors: 'การนำเข้าเสร็จสิ้นโดยมีข้อผิดพลาด {count} รายการ',
    ImportPanel_ProjectCreatedSuccess: 'สร้างโครงการสำเร็จแล้ว!',
    ImportPanel_ImportSuccessful: 'นำเข้าสำเร็จ!',
    ImportPanel_TasksAddedTo: 'เพิ่มงาน {count} รายการไปยัง "{projectName}"',
    ImportPanel_FailedRowsLabel: 'แถวที่ล้มเหลว:',
    ImportPanel_CloseButton: 'ปิด',
    ImportPanel_OpenProjectButton: 'เปิดโครงการ',
    ImportPanel_ViewImportedTasksButton: 'ดูงานที่นำเข้า',
    ImportPanel_NextMapColumnsButton: 'ถัดไป: จับคู่คอลัมน์',
    ImportPanel_ImportNTasksButton: 'นำเข้างาน {count} รายการ',
    ImportPanel_BackButton: 'ย้อนกลับ',
    ImportPanel_CancelButton: 'ยกเลิก',
    ImportPanel_NextButton: 'ถัดไป',
    ImportPanel_StepSource: 'แหล่งที่มา',
    ImportPanel_StepProject: 'โครงการ',
    ImportPanel_StepMap: 'จับคู่',
    ImportPanel_StepImport: 'นำเข้า',
    ImportPanel_StepDone: 'เสร็จสิ้น',
    ImportPanel_ImportAsNewProjectHeader: 'นำเข้าไฟล์เป็นโครงการใหม่',
    ImportPanel_ImportIntoProjectHeader: 'นำเข้างานไปยัง {projectName}',
    ImportPanel_CouldNotParseFile: 'ไม่สามารถประมวลผลไฟล์ได้',
    ImportPanel_CouldNotLoadPlannerTasks: 'ไม่สามารถโหลดงานจากแผนนี้ได้',
    ImportPanel_CouldNotCreateProjectDetail: 'ไม่สามารถสร้างโครงการได้: {detail}',
    ImportPanel_CouldNotLinkDependencies: 'ไม่สามารถเชื่อมโยงการอ้างอิงได้: {detail}',
    ImportPanel_UnknownError: 'ข้อผิดพลาดที่ไม่ทราบสาเหตุ',

    // ── Column mapper (import) ──
    ColumnMapper_TaskNameRequiredBanner: 'ต้องจับคู่ชื่องานก่อนจึงจะดำเนินการต่อได้',
    ColumnMapper_SkippedColumnsBanner: 'จะข้าม {count} คอลัมน์',
    ColumnMapper_SourceColumnHeader: 'คอลัมน์ต้นทาง',
    ColumnMapper_TargetFieldHeader: 'ฟิลด์ปลายทาง',
    ColumnMapper_StatusHeader: 'สถานะ',
    ColumnMapper_SkippedBadge: 'ข้ามแล้ว',
    ColumnMapper_AutoMappedBadge: 'จับคู่อัตโนมัติ',
    ColumnMapper_SetBadge: 'กำหนดแล้ว',
    ColumnMapper_PreviewTitle: 'ตัวอย่าง: {columnName}',
    ColumnMapper_EmptyCellDash: '—',

    // ── Import field display names / ImportService ──
    ImportField_TaskName: 'ชื่องาน',
    ImportField_StartDate: 'วันที่เริ่มต้น',
    ImportField_DueDate: 'วันครบกำหนด',
    ImportField_Status: 'สถานะ',
    ImportField_Priority: 'ลำดับความสำคัญ',
    ImportField_AssignedTo: 'มอบหมายให้',
    ImportField_AssignedToEmail: 'อีเมลของผู้ได้รับมอบหมาย',
    ImportField_PercentComplete: '% เสร็จสมบูรณ์',
    ImportField_Phase: 'ระยะ',
    ImportField_Description: 'คำอธิบาย',
    ImportField_Notes: 'บันทึกย่อ',
    ImportField_IsMilestone: 'เป็นเหตุการณ์สำคัญ',
    ImportField_Dependencies: 'การอ้างอิง',
    ImportField_SkipColumn: '(ข้ามคอลัมน์นี้)',
    ImportService_EmptyFileError: 'ไฟล์ดูเหมือนจะว่างเปล่าหรือไม่มีแถวข้อมูล',
    ImportService_ReadErrorDetail: 'ไม่สามารถอ่านไฟล์ได้: {detail}',
    ImportService_FileReadError: 'เกิดข้อผิดพลาดในการอ่านไฟล์',
    ImportService_RowError: 'แถว {rowNum} ("{title}"): {error}',
    ImportService_AmbiguousDependency: 'การอ้างอิง "{name}" ตรงกับชื่องานมากกว่าหนึ่งรายการ — ถูกข้ามไป',
    ImportService_LinkDependencyError: 'ไม่สามารถเชื่อมโยงการอ้างอิงสำหรับงาน {taskId} ได้: {error}',

    // ── Health labels (shared: healthUtils.ts and ExportService.ts both use this set; also replaces the duplicated Export_PortfolioHealthLabel* keys) ──
    Health_Done: 'เสร็จสิ้น',
    Health_OnTrack: 'เป็นไปตามแผน',
    Health_AtRisk: 'มีความเสี่ยง',
    Health_Overdue: 'เกินกำหนด',

    // ── Status / Priority display labels (DISPLAY-ONLY — stored SharePoint Choice values remain unchanged/English) ──
    Status_NotStarted: 'ยังไม่เริ่ม',
    Status_InProgress: 'กำลังดำเนินการ',
    Status_Completed: 'เสร็จสมบูรณ์',
    Status_OnHold: 'ระงับชั่วคราว',
    Status_Cancelled: 'ยกเลิกแล้ว',
    Priority_Critical: 'วิกฤต',
    Priority_High: 'สูง',
    Priority_Medium: 'ปานกลาง',
    Priority_Low: 'ต่ำ',
    ProjectStatus_Planning: 'วางแผน',
    ProjectStatus_Active: 'ดำเนินการอยู่',
    ProjectStatus_OnHold: 'ระงับชั่วคราว',
    ProjectStatus_Completed: 'เสร็จสมบูรณ์',
    ProjectStatus_Cancelled: 'ยกเลิกแล้ว',

    // ── Shell (SmartGantt.tsx) ──
    SmartGantt_LoadingProjects: 'กำลังโหลดโครงการ…',
    SmartGantt_UnableToLoad: 'ไม่สามารถโหลดได้',
    SmartGantt_RetryButton: 'ลองอีกครั้ง',
    SmartGantt_NoProjectsYet: 'ยังไม่มีโครงการ',
    SmartGantt_NoProjectsSubtitle: 'สร้างโครงการแรกของคุณเพื่อเริ่มต้น',
    SmartGantt_CreateFirstProjectButton: '+ สร้างโครงการแรก',
    SmartGantt_ImportFromExcelButton: '📥 นำเข้าจาก Excel',
    SmartGantt_LoadingTasks: 'กำลังโหลดงาน…',
    SmartGantt_DismissAriaLabel: 'ปิด',
    SmartGantt_DeleteTaskDialogTitle: 'ลบงาน',
    SmartGantt_DeleteTaskDialogSubtext: 'คุณแน่ใจหรือไม่ว่าต้องการลบ "{taskTitle}"? การกระทำนี้ไม่สามารถยกเลิกได้',
    SmartGantt_DeleteButton: 'ลบ',
    SmartGantt_CancelButton: 'ยกเลิก',
    SmartGantt_ArchiveProjectDialogTitle: 'เก็บถาวรโครงการ',
    SmartGantt_ArchiveProjectDialogSubtext: 'เก็บถาวร "{projectTitle}" หรือไม่? คุณสามารถยกเลิกการเก็บถาวรได้ในภายหลัง',
    SmartGantt_ArchiveButton: 'เก็บถาวร',
    SmartGantt_SendToRecycleBinDialogTitle: 'ส่งไปยังถังรีไซเคิล',
    SmartGantt_SendToRecycleBinDialogSubtext: 'ส่ง "{projectTitle}" ไปยังถังรีไซเคิลของไซต์หรือไม่?',
    SmartGantt_SendToRecycleBinButton: 'ส่งไปยังถังรีไซเคิล',
    SmartGantt_FailedLoadProjects: 'โหลดโครงการไม่สำเร็จ โปรดตรวจสอบสิทธิ์ของไซต์',
    SmartGantt_FailedLoadTasks: 'โหลดงานสำหรับโครงการนี้ไม่สำเร็จ',
    SmartGantt_FailedLoadPortfolioStats: 'โหลดสถิติพอร์ตโฟลิโอไม่สำเร็จ',
    SmartGantt_CouldNotSaveProject: 'ไม่สามารถบันทึกโครงการได้: {message}',
    SmartGantt_CouldNotDeleteProject: 'ไม่สามารถลบโครงการได้: {message}',
    SmartGantt_CouldNotArchiveProject: 'ไม่สามารถเก็บถาวรโครงการได้: {message}',
    SmartGantt_CouldNotUnarchiveProject: 'ไม่สามารถยกเลิกการเก็บถาวรโครงการได้: {message}',
    SmartGantt_CouldNotSaveTask: 'ไม่สามารถบันทึกงานได้: {message}',
    SmartGantt_CouldNotDeleteTask: 'ไม่สามารถลบงานได้: {message}',
    SmartGantt_ImageExportFailed: 'ส่งออกรูปภาพไม่สำเร็จ: {message}',
    SmartGantt_PowerPointExportFailed: 'ส่งออกไปยัง PowerPoint ไม่สำเร็จ: {message}',
    SmartGantt_PortfolioExportFailed: 'ส่งออกพอร์ตโฟลิโอไม่สำเร็จ: {message}',
    SmartGantt_CouldNotUpdateTask: 'ไม่สามารถอัปเดตงานได้: {message}',

    // ── Common ──
    ColorSwatch_AutoColorAriaLabel: 'สีอัตโนมัติ',
    ColorSwatch_CustomColorAriaLabel: 'สีกำหนดเอง',
    ColorSwatch_PickCustomColorTitle: 'เลือกสีกำหนดเอง',

    // ── Export (Excel / PowerPoint) ──
    Export_ColTaskName: 'ชื่องาน',
    Export_ColPhase: 'ระยะ',
    Export_ColStartDate: 'วันที่เริ่มต้น',
    Export_ColDueDate: 'วันครบกำหนด',
    Export_ColStatus: 'สถานะ',
    Export_ColPriority: 'ลำดับความสำคัญ',
    Export_ColAssignedTo: 'มอบหมายให้',
    Export_ColAssignedToEmail: 'อีเมลของผู้ได้รับมอบหมาย',
    Export_ColPercentComplete: '% เสร็จสมบูรณ์',
    Export_ColIsMilestone: 'เป็นเหตุการณ์สำคัญ',
    Export_ColDescription: 'คำอธิบาย',
    Export_ColNotes: 'บันทึกย่อ',
    Export_Yes: 'ใช่',
    Export_No: 'ไม่ใช่',
    Export_SheetNameTasks: 'งาน',
    Export_ExcelFileSuffix: ' - งาน.xlsx',
    Export_TaskNameColumnLabel: 'ชื่องาน',
    Export_ExportedDateLabel: 'ส่งออกเมื่อ {date}',
    Export_ProjectReportLabel: 'รายงานโครงการ',
    Export_StatusLine: 'สถานะ: {status}',
    Export_DateRangeSeparator: ' ถึง ',
    Export_ProjectManagerLine: 'ผู้จัดการโครงการ: {name}',
    Export_GeneratedDateLine: 'สร้างเมื่อ {date}',
    Export_ProjectSummaryTitle: 'สรุปโครงการ',
    Export_StatTotalTasks: 'งานทั้งหมด',
    Export_StatCompleted: 'เสร็จสมบูรณ์',
    Export_StatInProgress: 'กำลังดำเนินการ',
    Export_StatOnHold: 'ระงับชั่วคราว',
    Export_StatNotStarted: 'ยังไม่เริ่ม',
    Export_OverallProgressLine: 'ความคืบหน้าโดยรวม',
    Export_OverallProgressPercent: '{percent}%',
    Export_StatusBreakdownTitle: 'สรุปตามสถานะ',
    Export_StatusBreakdownRow: '{status}: {count} ({percent}%)',
    Export_GanttTimelineTitle: 'ไทม์ไลน์แกนต์',
    Export_SummaryRecentActivityTitle: 'กิจกรรมล่าสุด',
    Export_ProjectOverviewLabel: 'ภาพรวมโครงการ',
    Export_DetailStatusLabel: 'สถานะ',
    Export_DetailStartDateLabel: 'วันที่เริ่มต้น',
    Export_DetailDueDateLabel: 'วันครบกำหนด',
    Export_DetailProjectManagerLabel: 'ผู้จัดการโครงการ',
    Export_Past7DaysLabel: '7 วันที่ผ่านมา',
    Export_NoActivityMessage: 'ไม่มีกิจกรรมล่าสุด',
    Export_CompletedThisWeekHeader: 'เสร็จสมบูรณ์สัปดาห์นี้ ({count})',
    Export_NewBadge: 'ใหม่  ',
    Export_CompletedPercentLine: 'เสร็จสมบูรณ์ {percent}%',
    Export_MoreItemsSuffix: '+ อีก {count} รายการ',
    Export_InProgressUpdatedHeader: 'กำลังดำเนินการ / อัปเดตแล้ว',
    Export_StatusPercentLine: '{status} — {percent}%',
    Export_PortfolioReportLabel: 'รายงานพอร์ตโฟลิโอ',
    Export_PortfolioOverviewTitle: 'ภาพรวมพอร์ตโฟลิโอ',
    Export_ProjectsCountLine: '{count} โครงการ',
    Export_HealthSummaryOnTrack: '{count} เป็นไปตามแผน',
    Export_HealthSummaryAtRisk: '{count} มีความเสี่ยง',
    Export_HealthSummaryOverdue: '{count} เกินกำหนด',
    Export_ProjectsSummaryHeader: 'สรุปโครงการ',
    Export_TableProject: 'โครงการ',
    Export_TableStatus: 'สถานะ',
    Export_TableHealth: 'สถานะความคืบหน้า',
    Export_TableTotal: 'ทั้งหมด',
    Export_TableDone: 'เสร็จสิ้น',
    Export_TableActive: 'ดำเนินการอยู่',
    Export_TableAtRisk: 'มีความเสี่ยง',
    Export_TableOverdue: 'เกินกำหนด',
    Export_TablePctDone: '% เสร็จสิ้น',
    Export_TableDueDate: 'วันครบกำหนด',
    Export_PortfolioSummaryFileName: 'สรุปพอร์ตโฟลิโอ.xlsx',
    Export_PortfolioReportFileName: 'รายงานพอร์ตโฟลิโอ.pptx',
    Export_ProjectReportFileName: 'รายงาน {projectName}.pptx',
    Export_UnavailableLabel: 'ไม่พร้อมใช้งาน',
    Export_SheetNamePortfolio: 'พอร์ตโฟลิโอ',
    Export_ColStart: 'เริ่มต้น',
    Export_ColDue: 'ครบกำหนด',
    Export_ImageGenerationFailed: 'ไม่สามารถสร้างรูปภาพได้ — แผนภูมิอาจมีขนาดใหญ่เกินไปสำหรับการส่งออกเป็นรูปภาพ',
    Export_DrawingContextFailed: 'ไม่สามารถสร้างบริบทการวาดภาพสำหรับการส่งออกได้',
    Export_SvgRenderFailed: 'การเรนเดอร์ SVG ล้มเหลว',

    // ── Added in v1.5 review ──
    Svc_TooManyDependencies: 'งานนี้มีความเกี่ยวข้องมากเกินกว่าจะบันทึกได้ (ขีดจำกัดประมาณ 60) โปรดลบบางรายการออกแล้วลองอีกครั้ง',
    Svc_TaskChangedByOthers: 'งานนี้ถูกผู้อื่นเปลี่ยนแปลงตั้งแต่คุณโหลดข้อมูล โปรดรีเฟรชแล้วลองอีกครั้ง',
    Svc_ProjectChangedByOthers: 'โครงการนี้ถูกผู้อื่นเปลี่ยนแปลงตั้งแต่คุณเปิดขึ้นมา โปรดรีเฟรชแล้วลองอีกครั้ง',
    Svc_ColumnCreateFailed: 'ไม่สามารถสร้าง {count} คอลัมน์ในรายการงานใหม่ได้: {detail}',
    Svc_BaselineUnavailable: 'ไม่สามารถใช้เส้นฐานกับโครงการนี้ได้ เนื่องจากไม่สามารถเพิ่มคอลัมน์เส้นฐาน (คุณอาจต้องมีสิทธิ์แก้ไขรายการ)',
    Svc_SubtaskReassignFailed: 'ไม่สามารถมอบหมายงานย่อยของงานนี้ใหม่ก่อนลบได้: {detail}',
    Svc_UnresolvedDependency: 'แถว {row} ("{title}"): ไม่สามารถจับคู่งานที่เกี่ยวข้อง "{name}" กับงานที่นำเข้าได้',
    Svc_SelfDependency: 'แถว {row} ("{title}"): งานที่เกี่ยวข้อง "{name}" ชี้ไปยังงานตัวเองและถูกข้ามไป',
    Svc_ColId: 'ID',
    Svc_ColDependencies: 'งานที่เกี่ยวข้อง',
    Svc_ColBaselineStart: 'เริ่มต้นตามเส้นฐาน',
    Svc_ColBaselineDue: 'กำหนดเสร็จตามเส้นฐาน',
    Svc_CsvFileSuffix: ' - Tasks.csv',
    Svc_IcsFileSuffix: ' - Milestones.ics',
    Svc_PortfolioCsvFileName: 'Portfolio Summary.csv',
    Svc_PP_DisplayGroup: 'ค่าเริ่มต้น',
    Svc_PP_DefaultView: 'มุมมองเริ่มต้น',
    Svc_PP_ViewGantt: 'แกนต์',
    Svc_PP_ViewList: 'รายการ',
    Svc_PP_ViewKanban: 'คัมบัง',
    Svc_PP_ViewDashboard: 'แดชบอร์ด',
    Svc_PP_ViewPortfolio: 'พอร์ตโฟลิโอ',
    Svc_PP_DefaultZoom: 'การซูมเริ่มต้น',
    Svc_PP_ZoomDay: 'วัน',
    Svc_PP_ZoomWeek: 'สัปดาห์',
    Svc_PP_ZoomMonth: 'เดือน',
    Svc_PP_ZoomQuarter: 'ไตรมาส',
    Svc_PP_CalendarGroup: 'ปฏิทินการทำงาน',
    Svc_PP_DaySun: 'วันอาทิตย์เป็นวันทำงาน',
    Svc_PP_DayMon: 'วันจันทร์เป็นวันทำงาน',
    Svc_PP_DayTue: 'วันอังคารเป็นวันทำงาน',
    Svc_PP_DayWed: 'วันพุธเป็นวันทำงาน',
    Svc_PP_DayThu: 'วันพฤหัสบดีเป็นวันทำงาน',
    Svc_PP_DayFri: 'วันศุกร์เป็นวันทำงาน',
    Svc_PP_DaySat: 'วันเสาร์เป็นวันทำงาน',
    Svc_PP_Holidays: 'วันหยุด (วันที่ไม่ใช่วันทำงาน)',
    Svc_PP_HolidaysHint: 'หนึ่งวันที่ต่อบรรทัด ในรูปแบบ yyyy-MM-dd (เช่น 2026-12-25)',
    Gantt_TimelineAriaLabel: 'ไทม์ไลน์ของงาน',
    Gantt_DragLabel: '{start} → {end} ({days} วัน)',
    Gantt_KeyboardMoveAnnouncement: '{taskTitle}: {startDate} ถึง {dueDate}',
    Gantt_KeyboardHint: 'กด Enter เพื่อเปิดงาน ปุ่มลูกศรซ้ายและขวาจะเลื่อนงานทีละหนึ่งวันทำงาน กด Shift พร้อมปุ่มลูกศรเพื่อเปลี่ยนวันที่สิ้นสุด',
    Gantt_ParentCycleTooltip: 'งานนี้เป็นส่วนหนึ่งของลำดับงานหลักและงานย่อยที่วนกลับเป็นวงกลม จึงแสดงที่ระดับบนสุด',
    Gantt_CollapseAll: 'ยุบทุกระยะ',
    Gantt_ExpandAll: 'ขยายทุกระยะ',
    Gantt_BaselineTooltip: 'เส้นฐาน: {start} → {due}',
    Gantt_VarianceTooltip: 'ความแปรปรวนของวันเสร็จ: {days} วันเทียบกับเส้นฐาน',
    Gantt_LinkHandleTitle: 'ลากไปวางบนงานอื่นเพื่อสร้างความเกี่ยวข้อง',
    Toolbar_FitToProject: 'พอดี',
    Toolbar_FitToProjectTitle: 'ซูมให้พอดีกับทั้งโครงการ',
    Toolbar_UndoTitle: 'เลิกทำ (Ctrl+Z)',
    Toolbar_RedoTitle: 'ทำซ้ำ (Ctrl+Y)',
    Toolbar_ExportCsv: '📄 ส่งออกงานเป็น CSV',
    Toolbar_ExportIcs: '📅 ส่งออกเหตุการณ์สำคัญ (iCal)',
    Toolbar_Print: '🖨 พิมพ์ / บันทึกเป็น PDF',
    Toolbar_SetBaseline: '📐 ตั้งค่าเส้นฐาน…',
    Toolbar_CopyLink: '🔗 คัดลอกลิงก์',
    Toolbar_CopyLinkTitle: 'คัดลอกลิงก์ไปยังมุมมองนี้ (โครงการ มุมมอง การซูม และตัวกรอง)',
    App_UndoButton: 'เลิกทำ',
    App_Undone: 'เลิกทำการเปลี่ยนแปลงแล้ว',
    App_Redone: 'ทำซ้ำการเปลี่ยนแปลงแล้ว',
    App_DependentsMovedOne: 'ย้ายงานที่ขึ้นต่อกัน 1 งานแล้ว',
    App_DependentsMovedMany: 'ย้ายงานที่ขึ้นต่อกัน {count} งานแล้ว',
    App_TaskConflict: 'งานนี้ถูกผู้อื่นเปลี่ยนแปลง โหลดงานล่าสุดใหม่แล้ว โปรดตรวจสอบและลองอีกครั้ง',
    App_DependencyCycle: 'การเชื่อมโยงนี้จะทำให้เกิดความเกี่ยวข้องแบบวนซ้ำ',
    App_DependencyExists: 'งานเหล่านั้นเชื่อมโยงกันอยู่แล้ว',
    App_LinkCopied: 'คัดลอกลิงก์ไปยังคลิปบอร์ดแล้ว',
    App_LinkCopyFailed: 'ไม่สามารถคัดลอกลิงก์ได้: {message}',
    App_PopupBlocked: 'หน้าต่างพิมพ์ถูกบล็อก โปรดอนุญาตป๊อปอัปสำหรับไซต์นี้แล้วลองอีกครั้ง',
    App_SetBaselineDialogTitle: 'ตั้งค่าเส้นฐาน',
    App_SetBaselineDialogSubtext: 'บันทึกวันที่เริ่มต้นและวันที่กำหนดเสร็จปัจจุบันของงานทั้งหมด {count} งานเป็นเส้นฐานหรือไม่ เส้นฐานที่มีอยู่จะถูกแทนที่',
    App_SetBaselineButton: 'ตั้งค่าเส้นฐาน',
    App_BaselineSaved: 'บันทึกเส้นฐานแล้ว',
    App_BaselineFailed: 'ไม่สามารถบันทึกเส้นฐานได้: {message}',
    App_CsvExportFailed: 'ส่งออก CSV ไม่สำเร็จ: {message}',
    App_IcsExportFailed: 'ส่งออกปฏิทินไม่สำเร็จ: {message}',
    App_BulkDeleteDialogTitle: 'ลบงาน',
    App_BulkDeleteDialogSubtext: 'คุณแน่ใจหรือไม่ว่าต้องการลบ {count} งาน การดำเนินการนี้ไม่สามารถยกเลิกได้',
    Common_PeoplePicker_ClearAriaLabel: 'ล้าง',
    Common_PeoplePicker_DirectoryHeader: 'บุคคลในไดเรกทอรี',
    Common_PeoplePicker_EmailLabel: 'อีเมล (ไม่บังคับ)',
    Common_PeoplePicker_EmailPlaceholder: 'name@company.com',
    Common_PeoplePicker_ExternalHint: 'ไม่อยู่ในไดเรกทอรี บันทึกเป็นข้อความอิสระ',
    Common_PeoplePicker_InvalidEmail: 'โปรดป้อนที่อยู่อีเมลที่ถูกต้อง',
    Common_PeoplePicker_ListAriaLabel: 'คำแนะนำบุคคล',
    Common_PeoplePicker_RecentHeader: 'ใช้ล่าสุด',
    Common_PeoplePicker_ResultsAnnouncement: 'มีคำแนะนำ {count} รายการ',
    Common_PeoplePicker_Searching: 'กำลังค้นหา…',
    Common_PeoplePicker_UseExternal: 'ใช้ “{name}” (ภายนอก / ไม่อยู่ในไดเรกทอรี)',
    Import_Mapper_PreviewFirstRows: 'ตัวอย่าง ({count} แถวแรก)',
    Import_Mapper_RequiredLegend: 'ช่องที่จำเป็น',
    Import_Mapper_RequiredMarkerLabel: 'จำเป็น',
    Import_Mapper_SelectAriaLabel: 'ช่องเป้าหมายสำหรับคอลัมน์ {columnName}',
    Import_Panel_DateOrderAuto: 'ตรวจหาอัตโนมัติ',
    Import_Panel_DateOrderDMY: 'วัน/เดือน/ปี (31/12/2026)',
    Import_Panel_DateOrderDetected: 'ตรวจพบจากไฟล์ของคุณ: {order}',
    Import_Panel_DateOrderHint: 'ใช้กับวันที่ที่เขียนเป็นตัวเลข เช่น 03/04/2026',
    Import_Panel_DateOrderLabel: 'ลำดับวันที่',
    Import_Panel_DateOrderMDY: 'เดือน/วัน/ปี (12/31/2026)',
    Import_Panel_DropZoneAriaLabel: 'เลือกไฟล์ที่จะนำเข้า กด Enter เพื่อเรียกดู',
    Import_Panel_DropZoneChangeAriaLabel: 'ไฟล์ที่เลือก {fileName} กด Enter เพื่อเลือกไฟล์อื่น',
    Import_Panel_FailedCount: 'ไม่สำเร็จ {count}',
    Import_Panel_NewProjectIntroMany: 'จะสร้างโครงการใหม่และนำเข้างานทั้งหมด {count} งานลงในโครงการนั้น คุณสามารถเปลี่ยนรายละเอียดเหล่านี้ได้ทุกเมื่อหลังจากนำเข้า',
    Import_Panel_NewProjectIntroOne: 'จะสร้างโครงการใหม่และนำเข้างาน {count} งานลงในโครงการนั้น คุณสามารถเปลี่ยนรายละเอียดเหล่านี้ได้ทุกเมื่อหลังจากนำเข้า',
    Import_Panel_PlanAriaLabel: '{planName}, {groupName}',
    Import_Panel_ProblemEndBeforeStart: 'วันที่กำหนดเสร็จอยู่ก่อนวันที่เริ่มต้น',
    Import_Panel_ProblemInvalidDueDate: 'วันที่กำหนดเสร็จ "{value}" ไม่ใช่วันที่ที่ถูกต้อง',
    Import_Panel_ProblemInvalidStartDate: 'วันที่เริ่มต้น "{value}" ไม่ใช่วันที่ที่ถูกต้อง',
    Import_Panel_ProblemMissingTitle: 'ไม่มีชื่องาน',
    Import_Panel_ProgressLabelWithPercent: '{done} จาก {total} ({percent}%)',
    Import_Panel_SkipInvalidRows: 'ข้ามแถวที่มีปัญหา',
    Import_Panel_SuccessWithWarningsMany: 'นำเข้าสำเร็จโดยมีคำเตือน {count} รายการ',
    Import_Panel_SuccessWithWarningsOne: 'นำเข้าสำเร็จโดยมีคำเตือน {count} รายการ',
    Import_Panel_ValidationHeader: 'แถวที่มีปัญหา',
    Import_Panel_ValidationMore: '…และอีก {count} รายการ',
    Import_Panel_ValidationRow: 'แถว {rowNum}: {problem}',
    Import_Panel_ValidationSummaryMany: '{count} แถวมีปัญหา',
    Import_Panel_ValidationSummaryOne: '{count} แถวมีปัญหา',
    Import_Panel_WarningsLabel: 'คำเตือน ({count}):',
    Panel_Project_ManagerLabel: 'ผู้จัดการโครงการ',
    Panel_Project_ManagerPlaceholder: 'ค้นหาบุคคลหรือพิมพ์ชื่อ…',
    Panel_Task_BaselineDueLabel: 'กำหนดเสร็จตามเส้นฐาน',
    Panel_Task_BaselineHeader: 'เส้นฐาน',
    Panel_Task_BaselineStartLabel: 'เริ่มต้นตามเส้นฐาน',
    Panel_Task_DepTypeFF: 'เสร็จต่อเสร็จ (FF)',
    Panel_Task_DepTypeFS: 'เสร็จต่อเริ่ม (FS)',
    Panel_Task_DepTypeSF: 'เริ่มต่อเสร็จ (SF)',
    Panel_Task_DepTypeSS: 'เริ่มต่อเริ่ม (SS)',
    Panel_Task_LagAriaLabel: 'ระยะหน่วงเป็นวันทำงานสำหรับ {taskTitle}',
    Panel_Task_LagHint: 'ระยะหน่วงนับเป็นวันทำงาน ใช้ตัวเลขติดลบสำหรับระยะเร่ง',
    Panel_Task_LinkTypeAriaLabel: 'ประเภทการเชื่อมโยงสำหรับ {taskTitle}',
    Panel_Task_VarianceEarlier: 'เร็วกว่า {days} วันทำงาน',
    Panel_Task_VarianceLater: 'ช้ากว่า {days} วันทำงาน',
    Panel_Task_VarianceOnBaseline: 'ตรงตามเส้นฐาน',
    View_Dashboard_BurndownActual: 'จริง',
    View_Dashboard_BurndownAria: 'แผนภูมิ Burndown: เหลืองาน {remaining} จาก {total} งาน',
    View_Dashboard_BurndownHeader: 'Burndown (งานที่เหลือ)',
    View_Dashboard_BurndownIdeal: 'อุดมคติ',
    View_Dashboard_BurndownNoData: 'มีงานที่ระบุวันที่ไม่เพียงพอสำหรับการวาด Burndown',
    View_Dashboard_CriticalPathHeader: 'เส้นทางวิกฤต  ({count})',
    View_Dashboard_PhaseDoneSummary: 'เสร็จ {done}/{total}  •  {percent}%',
    View_Dashboard_TaskRowAriaLabel: 'เปิดงาน {taskTitle}, {status}',
    View_Dashboard_WorkloadHeader: 'ปริมาณงานตามผู้รับผิดชอบ',
    View_Dashboard_WorkloadOpen: 'เปิดอยู่ {count}',
    View_Dashboard_WorkloadOverdue: 'เลยกำหนด {count}',
    View_Kanban_AddTaskInColumnAriaLabel: 'เพิ่มงานลงใน {column}',
    View_Kanban_CollapseColumn: 'ยุบคอลัมน์ {column}',
    View_Kanban_ExpandColumn: 'ขยายคอลัมน์ {column}',
    View_Kanban_LaneHeader: '{name} ({count})',
    View_Kanban_LaneNoPhase: 'ไม่มีระยะ',
    View_Kanban_LaneUnassigned: 'ยังไม่ได้มอบหมาย',
    View_Kanban_LanesAssignee: 'ผู้รับผิดชอบ',
    View_Kanban_LanesNone: 'ไม่มี',
    View_Kanban_LanesPhase: 'ระยะ',
    View_Kanban_SwimlanesLabel: 'เลน',
    View_Kanban_WipEditTitle: 'ตั้งค่าขีดจำกัดงานที่กำลังดำเนินการสำหรับ {column} (0 หมายถึงไม่จำกัด)',
    View_Kanban_WipExceededTitle: 'เกินขีดจำกัด WIP: {count} จาก {limit}',
    View_Kanban_WipInputAriaLabel: 'ขีดจำกัด WIP สำหรับ {column}',
    View_Kanban_WipLabel: 'WIP {count}/{limit}',
    View_Kanban_WipSet: 'WIP',
    View_List_BulkAssignApply: 'มอบหมาย',
    View_List_BulkAssigneePlaceholder: 'มอบหมายให้…',
    View_List_BulkBarAriaLabel: 'การดำเนินการแบบกลุ่มสำหรับงานที่เลือก',
    View_List_BulkClear: 'ล้างการเลือก',
    View_List_BulkDelete: 'ลบที่เลือก',
    View_List_BulkPercentApply: 'ตั้งค่า %',
    View_List_BulkPercentPlaceholder: '% ที่เสร็จ',
    View_List_BulkPriorityPlaceholder: 'ตั้งค่าลำดับความสำคัญ…',
    View_List_BulkSelectedCount: 'เลือก {count} งาน',
    View_List_BulkStatusPlaceholder: 'ตั้งค่าสถานะ…',
    View_List_ExportCsv: 'ส่งออก CSV',
    View_List_NonWorkingDay: 'วันที่ไม่ใช่วันทำงาน',
    View_List_SelectAllAriaLabel: 'เลือกงานทั้งหมด',
    View_List_SelectRowAriaLabel: 'เลือก {taskTitle}',
    View_Portfolio_CardAriaLabel: 'เปิดโครงการ {projectName}, {status}',
    View_Portfolio_ClearFilters: 'ล้างตัวกรอง',
    View_Portfolio_FilteredCount: '{shown} จาก {total} โครงการ',
    View_Portfolio_HideDone: 'ซ่อนที่เสร็จสมบูรณ์ / ยกเลิกแล้ว',
    View_Portfolio_NoMatches: 'ไม่มีโครงการที่ตรงกับตัวกรองของคุณ',
    View_Portfolio_ProjectCountMany: '{count} โครงการ',
    View_Portfolio_ProjectCountOne: '{count} โครงการ',
    View_Portfolio_SearchAriaLabel: 'ค้นหาโครงการ',
    View_Portfolio_SearchPlaceholder: 'ค้นหาโครงการ…',
    Import_Panel_CopyDetails: 'คัดลอกรายละเอียด',
    Import_Panel_Copied: 'คัดลอกแล้ว',
  };
});
