define([], function () {
  return {
    // ── Property pane ──
    PropertyPane_HeaderDescription: 'Smart Gantt Chart Ayarları',
    PropertyPane_GeneralGroupName: 'Genel',
    PropertyPane_TitleFieldLabel: 'Web Parçası Başlığı',
    WebPart_DefaultTitle: 'Smart Gantt Chart',

    // ── Toolbar ──
    Toolbar_ViewDashboard: 'Pano',
    Toolbar_ViewList: 'Liste',
    Toolbar_ViewGantt: 'Gantt',
    Toolbar_ViewKanban: 'Kanban',
    Toolbar_ZoomDay: 'Gün',
    Toolbar_ZoomWeek: 'Hafta',
    Toolbar_ZoomMonth: 'Ay',
    Toolbar_ZoomQuarter: 'Çeyrek',
    Toolbar_SelectProjectAriaLabel: 'Proje seçin',
    Toolbar_PortfolioLabel: 'Portföy',
    Toolbar_SelectAProject: 'Bir Proje Seçin',
    Toolbar_AllProjectsSubtext: 'Tüm projeler',
    Toolbar_NoProjectsYet: 'Henüz proje yok',
    Toolbar_ArchivedBadge: 'Arşivlendi',
    Toolbar_ShowArchivedProjects: 'Arşivlenmiş projeleri göster',
    Toolbar_NewProject: '+ Yeni Proje',
    Toolbar_ImportFileAsNewProject: '📥 Dosyayı Yeni Proje Olarak İçe Aktar…',
    Toolbar_AddTask: '+ Görev Ekle',
    Toolbar_EditProject: 'Projeyi Düzenle',
    Toolbar_OptionsButton: '⚙ Seçenekler',
    Toolbar_MoreOptionsTitle: 'Diğer seçenekler',
    Toolbar_ExportToExcel: '📊 Excel\'e Aktar',
    Toolbar_ExportToPowerPoint: '📑 PowerPoint\'e Aktar',
    Toolbar_ScrollToTodayTitle: 'Bugüne kaydır',
    Toolbar_TodayButton: '◉ Bugün',
    Toolbar_ImportTasks: '📥 Görevleri İçe Aktar…',
    Toolbar_ExportAsImage: '🖼 Resim Olarak Dışa Aktar (PNG)',
    Toolbar_UnarchiveProject: '📂 Arşivden Çıkar',
    Toolbar_ArchiveProject: '🗄️ Projeyi Arşivle',
    Toolbar_SendToRecycleBin: '🗑️ Geri Dönüşüm Kutusuna Gönder',

    // ── Filter bar ──
    FilterBar_ClearOption: 'Temizle',
    FilterBar_DueAny: 'Herhangi bir bitiş tarihi',
    FilterBar_DueOverdue: 'Süresi geçmiş',
    FilterBar_DueToday: 'Bugün bitiyor',
    FilterBar_DueWeek: '7 gün içinde',
    FilterBar_SearchPlaceholder: 'Görevlerde ara…',
    FilterBar_SearchAriaLabel: 'Görevlerde ara',
    FilterBar_StatusChipLabel: 'Durum',
    FilterBar_PriorityChipLabel: 'Öncelik',
    FilterBar_AssigneeChipLabel: 'Atanan Kişi',
    FilterBar_PhaseChipLabel: 'Aşama',
    FilterBar_DueDateAriaLabel: 'Bitiş tarihine göre filtrele',
    FilterBar_MatchCount: '{totalCount} içinden {matchCount}',
    FilterBar_ClearFilters: '✕ Filtreleri temizle',
    FilterBar_ChipLabelWithCount: '{label} ({count}) ▾',
    FilterBar_ChipLabelNoCount: '{label} ▾',

    // ── Gantt view ──
    Gantt_TaskColumnHeader: 'Görev',
    Gantt_DurationColumnHeader: 'Süre',
    Gantt_AddTaskButton: '+ Görev Ekle',
    Gantt_EmptyTitle: 'Henüz görev yok',
    Gantt_EmptySubtitle: 'Gantt şemasında görüntülemek için görev ekleyin.',
    Gantt_AddFirstTask: '+ İlk Görevi Ekle',
    Gantt_ImportTasksButton: '📥 Görevleri İçe Aktar',
    Gantt_EditTitle: 'Düzenle',
    Gantt_DeleteTitle: 'Sil',
    Gantt_EditTaskAriaLabel: '{taskTitle} görevini düzenle',
    Gantt_DeleteTaskAriaLabel: '{taskTitle} görevini sil',
    Gantt_ExpandPhaseAriaLabel: '{phase} aşamasını {action}',
    Gantt_ExpandAction: 'Genişlet',
    Gantt_CollapseAction: 'Daralt',
    Gantt_DependencyViolationTooltip: 'Tüm bağımlılıklar tamamlanmadan başlatıldı',
    Gantt_MilestoneAriaLabel: '{taskTitle}, kilometre taşı, {date}',
    Gantt_BarAriaLabel: '{taskTitle}, {startDate} - {dueDate}, %{percent} tamamlandı',
    Gantt_PercentCompleteTooltip: '%{value} tamamlandı',

    // ── Gantt options/settings panel ──
    GanttSettings_PanelHeader: '⚙ Seçenekler',
    GanttSettings_ColorCodingSection: 'Renk Kodlama',
    GanttSettings_ByStatus: 'Duruma Göre',
    GanttSettings_ByPriority: 'Önceliğe Göre',
    GanttSettings_ByPhase: 'Aşamaya Göre',
    GanttSettings_ByHealth: 'Sağlık Durumuna Göre',
    GanttSettings_HeaderColorSection: 'Başlık Rengi',
    GanttSettings_ThemeDark: 'Koyu',
    GanttSettings_ThemeNavy: 'Lacivert',
    GanttSettings_ThemeTeal: 'Deniz Mavisi',
    GanttSettings_ThemePurple: 'Mor',
    GanttSettings_ThemeLight: 'Açık',
    GanttSettings_HeaderLabelsSection: 'Başlık Etiketleri',
    GanttSettings_WeekLabelDates: 'Tarihler',
    GanttSettings_WeekLabelDatesDesc: '3 Haz, 10 Haz…',
    GanttSettings_WeekLabelProject: 'Proje Haftaları',
    GanttSettings_WeekLabelProjectDesc: 'H1, H2…',
    GanttSettings_WeekLabelIso: 'Takvim Haftaları',
    GanttSettings_WeekLabelIsoDesc: 'H23, H24…',
    GanttSettings_ProjectWeeksHint: '1. hafta, en erken göreviniz olan Pazartesi\'den başlar — sunumlar için idealdir.',
    GanttSettings_BarStyleSection: 'Çubuk Stili',
    GanttSettings_BarStyleGradient: 'Geçişli',
    GanttSettings_BarStyleFlat: 'Düz',
    GanttSettings_RowHeightSection: 'Satır Yüksekliği',
    GanttSettings_HeightCompact: 'Kompakt',
    GanttSettings_HeightNormal: 'Normal',
    GanttSettings_HeightSpacious: 'Geniş',
    GanttSettings_ShowHideSection: 'Göster / Gizle',
    GanttSettings_WeekendShading: 'Hafta sonu gölgelendirmesi',
    GanttSettings_DependencyArrows: 'Bağımlılık okları',
    GanttSettings_CriticalPathAlwaysVisible: 'Kritik yol her zaman görünür',
    GanttSettings_AllOthersOnHoverOnly: 'Diğerleri yalnızca fare üzerine gelince',
    GanttSettings_CriticalPathHighlight: 'Kritik yol vurgusu',
    GanttSettings_ProgressPercentOnBars: 'Çubuklarda ilerleme yüzdesi',
    GanttSettings_AssigneeNameOnBars: 'Çubuklarda atanan kişi adı',
    GanttSettings_HealthStatusBadges: 'Sağlık durumu rozetleri',

    // ── List view ──
    ListView_ColTaskName: 'Görev Adı',
    ListView_ColStatus: 'Durum',
    ListView_ColHealth: 'Sağlık Durumu',
    ListView_ColPriority: 'Öncelik',
    ListView_ColStart: 'Başlangıç',
    ListView_ColDue: 'Bitiş',
    ListView_ColAssignedTo: 'Atanan Kişi',
    ListView_ColProgress: 'İlerleme',
    ListView_ColPhase: 'Aşama',
    ListView_ColPredecessors: 'Öncüller',
    ListView_EmptyTitle: 'Henüz görev yok',
    ListView_AddFirstTask: '+ İlk Görevi Ekle',
    ListView_AddTaskRow: '+ Görev Ekle',
    ListView_Unassigned: 'Atanmamış',
    ListView_DependencyViolationTooltip: 'Tüm bağımlılıklar tamamlanmadan başlatıldı',
    ListView_StatusAriaLabel: '{taskTitle} durumu',
    ListView_PriorityAriaLabel: '{taskTitle} önceliği',
    ListView_EditTaskAriaLabel: '{taskTitle} görevini düzenle',
    ListView_DeleteTaskAriaLabel: '{taskTitle} görevini sil',
    ListView_EditTitle: 'Düzenle',
    ListView_DeleteTitle: 'Sil',

    // ── Kanban view ──
    Kanban_ColumnNotStarted: 'Başlamadı',
    Kanban_ColumnInProgress: 'Devam Ediyor',
    Kanban_ColumnOnHold: 'Beklemede',
    Kanban_ColumnCompleted: 'Tamamlandı',
    Kanban_ColumnCancelled: 'İptal Edildi',
    Kanban_AddTaskButton: '+ Görev Ekle',
    Kanban_EditTitle: 'Düzenle',
    Kanban_DeleteTitle: 'Sil',
    Kanban_CardAriaLabel: '{taskTitle}, {status}. Düzenlemek için Enter, durumu değiştirmek için Sol veya Sağ ok tuşuna basın.',
    Kanban_EditTaskAriaLabel: '{taskTitle} görevini düzenle',
    Kanban_DeleteTaskAriaLabel: '{taskTitle} görevini sil',

    // ── Dashboard view ──
    Dashboard_TotalTasks: 'Toplam Görev',
    Dashboard_Completed: 'Tamamlandı',
    Dashboard_InProgress: 'Devam Ediyor',
    Dashboard_OnHold: 'Beklemede',
    Dashboard_NotStarted: 'Başlamadı',
    Dashboard_Cancelled: 'İptal Edildi',
    Dashboard_OverallProgress: 'Genel İlerleme',
    Dashboard_ProjectManagerLabel: 'Proje Yöneticisi: {name}',
    Dashboard_PhaseProgressHeader: 'Aşama İlerlemesi',
    Dashboard_StatusBreakdownHeader: 'Durum Dağılımı',
    Dashboard_PriorityBreakdownHeader: 'Öncelik Dağılımı',
    Dashboard_PriorityCritical: 'Kritik',
    Dashboard_PriorityHigh: 'Yüksek',
    Dashboard_PriorityMedium: 'Orta',
    Dashboard_PriorityLow: 'Düşük',
    Dashboard_OverdueHeader: 'Süresi Geçmiş  ({count})',
    Dashboard_DueNext14DaysHeader: 'Sonraki 14 gün içinde bitecek  ({count})',
    Dashboard_CompletedThisWeekHeader: 'Bu Hafta Tamamlanan',
    Dashboard_UpdatedThisWeekHeader: 'Bu Hafta Güncellenen',
    Dashboard_Today: 'Bugün',
    Dashboard_Tomorrow: 'Yarın',
    Dashboard_DaysLeft: '{days} gün',
    Dashboard_EmptyTitle: 'Henüz görev yok',
    Dashboard_EmptySubtitle: 'Proje panonuzu görmek için görev ekleyin.',
    Dashboard_AddTaskButton: '+ Görev Ekle',

    // ── Portfolio view ──
    Portfolio_ProjectCount: '{count} Proje{plural}',
    Portfolio_OnTrackSummary: '{count} Yolunda',
    Portfolio_AtRiskSummary: '{count} Riskli',
    Portfolio_OverdueSummary: '{count} Süresi Geçmiş',
    Portfolio_DoneSummary: '{count} Tamamlandı',
    Portfolio_SortLabel: 'Sırala:',
    Portfolio_SortAZ: 'A-Z',
    Portfolio_SortHealth: 'Sağlık Durumu',
    Portfolio_SortStatus: 'Durum',
    Portfolio_SortCompletion: 'Tamamlanma',
    Portfolio_RefreshTitle: 'Yenile',
    Portfolio_RefreshButton: 'Yenile',
    Portfolio_LoadingStats: 'İstatistikler yükleniyor…',
    Portfolio_EmptyTitle: 'Henüz proje yok',
    Portfolio_CreateFirstProject: '+ İlk Projeyi Oluştur',
    Portfolio_StatsUnavailable: 'İstatistikler kullanılamıyor',
    Portfolio_StatsUnavailableDetail: 'Bu proje için istatistikler yüklenemedi.',
    Portfolio_OverallProgressLabel: 'Genel İlerleme',
    Portfolio_TaskCountDone: 'Tamamlandı',
    Portfolio_TaskCountActive: 'Aktif',
    Portfolio_TaskCountAtRisk: 'Riskli',
    Portfolio_TaskCountOverdue: 'Süresi Geçmiş',
    Portfolio_ViewGanttLink: 'Gantt\'ı Görüntüle →',
    Portfolio_TodayTooltip: 'Bugün',

    // ── Task panel ──
    TaskPanel_EditHeader: 'Düzenle: {taskTitle}',
    TaskPanel_NewTaskHeader: 'Yeni Görev',
    TaskPanel_TabBasic: 'Temel',
    TaskPanel_TabDetails: 'Ayrıntılar',
    TaskPanel_TabLinks: 'Bağlantılar',
    TaskPanel_ProjectLabelPrefix: 'Proje: ',
    TaskPanel_TaskNameLabel: 'Görev Adı',
    TaskPanel_TaskNamePlaceholder: 'Görev adını girin',
    TaskPanel_TaskNameRequired: 'Görev adı gereklidir',
    TaskPanel_DescriptionLabel: 'Açıklama',
    TaskPanel_DescriptionPlaceholder: 'Açıklama girin',
    TaskPanel_StartDateLabel: 'Başlangıç Tarihi',
    TaskPanel_DueDateLabel: 'Bitiş Tarihi',
    TaskPanel_DueDateError: 'Bitiş tarihi, başlangıç tarihi ile aynı veya sonrasında olmalıdır',
    TaskPanel_StatusLabel: 'Durum',
    TaskPanel_PriorityLabel: 'Öncelik',
    TaskPanel_PercentCompleteLabel: 'Tamamlanma: %{percent}',
    TaskPanel_AssignedToLabel: 'Atanan Kişi',
    TaskPanel_AssignedToPlaceholder: 'Kişi ara…',
    TaskPanel_PhaseLabel: 'Aşama',
    TaskPanel_PhasePlaceholder: 'Aşama adını girin',
    TaskPanel_PhaseHint: 'Gantt ve Liste görünümlerinde görevleri bir araya gruplar.',
    TaskPanel_MilestoneLabel: 'Kilometre Taşı',
    TaskPanel_MilestoneOnText: 'Evet',
    TaskPanel_MilestoneOffText: 'Hayır',
    TaskPanel_CustomBarColorLabel: 'Özel Çubuk Rengi',
    TaskPanel_CustomBarColorOptionalSuffix: ' (isteğe bağlı)',
    TaskPanel_AutoColorHint: 'Durum/öncelik/aşama ayarlarına göre otomatik renk.',
    TaskPanel_NotesLabel: 'Notlar',
    TaskPanel_NotesPlaceholder: 'Not girin',
    TaskPanel_ParentTaskLabel: 'Üst Görev',
    TaskPanel_ParentTaskNone: '(yok)',
    TaskPanel_ParentTaskHasChildrenHint: 'Bu görevin alt görevleri var ve kendi üst görevi olamaz.',
    TaskPanel_ParentTaskHint: 'Bu görevi başka bir görevin altına alt görev olarak yerleştirin.',
    TaskPanel_DependsOnLabel: 'Bağımlı Olduğu',
    TaskPanel_RemoveDependencyTitle: '"{taskTitle}" bağımlılığını kaldır',
    TaskPanel_AddDependencyPlaceholder: 'Bağımlılık ekle…',
    TaskPanel_SelectATaskOption: 'Bir görev seçin…',
    TaskPanel_DependsOnHint: 'Bunlar tamamlanana kadar görev başlayamaz.',
    TaskPanel_SavingLabel: 'Kaydediliyor…',
    TaskPanel_CreatingLabel: 'Oluşturuluyor…',
    TaskPanel_SaveChangesButton: 'Değişiklikleri Kaydet',
    TaskPanel_CreateTaskButton: 'Görev Oluştur',
    TaskPanel_CancelButton: 'İptal',
    TaskPanel_DismissAriaLabel: 'Kapat',
    TaskPanel_DiscardUnsavedChangesConfirm: 'Kaydedilmemiş değişiklikler atılsın mı?',
    TaskPanel_SaveFallbackError: 'Görev kaydedilemedi.',

    // ── Project panel ──
    ProjectPanel_EditHeader: 'Projeyi Düzenle',
    ProjectPanel_NewHeader: 'Yeni Proje',
    ProjectPanel_ProjectNameLabel: 'Proje Adı',
    ProjectPanel_ProjectNamePlaceholder: 'Proje adını girin',
    ProjectPanel_ProjectNameRequired: 'Proje adı gereklidir',
    ProjectPanel_DescriptionLabel: 'Açıklama',
    ProjectPanel_DescriptionPlaceholder: 'Açıklama girin',
    ProjectPanel_ProjectColorLabel: 'Proje Rengi',
    ProjectPanel_StatusLabel: 'Durum',
    ProjectPanel_StartDateLabel: 'Başlangıç Tarihi',
    ProjectPanel_DueDateLabel: 'Bitiş Tarihi',
    ProjectPanel_DueDateError: 'Bitiş tarihi, başlangıç tarihi ile aynı veya sonrasında olmalıdır',
    ProjectPanel_WhatHappensNextTitle: 'Sırada ne var?',
    ProjectPanel_WhatHappensNextBody: 'Proje oluşturulduktan sonra görev ekleyebilir, aşamalar oluşturabilir ve ilerlemeyi takip edebilirsiniz.',
    ProjectPanel_SavingLabel: 'Kaydediliyor…',
    ProjectPanel_CreatingLabel: 'Oluşturuluyor…',
    ProjectPanel_SaveChangesButton: 'Değişiklikleri Kaydet',
    ProjectPanel_CreateProjectButton: 'Proje Oluştur',
    ProjectPanel_CancelButton: 'İptal',
    ProjectPanel_DismissAriaLabel: 'Kapat',
    ProjectPanel_DiscardUnsavedChangesConfirm: 'Kaydedilmemiş değişiklikler atılsın mı?',
    ProjectPanel_SaveFallbackError: 'Proje kaydedilemedi.',

    // ── Import panel ──
    ImportPanel_SourceExcelTitle: 'Excel / CSV Dosyası',
    ImportPanel_SourceExcelSubtitle: 'Bir elektronik tablodan görevleri içe aktarın',
    ImportPanel_SourcePlannerTitle: 'Microsoft Planner',
    ImportPanel_SourcePlannerSubtitle: 'Bir Planner planından görevleri içe aktarın',
    ImportPanel_ClickToBrowse: 'Göz atmak için tıklayın',
    ImportPanel_DragDropSuffix: ' veya sürükleyip bırakın',
    ImportPanel_SupportedExtensions: '.xlsx, .xls, .csv destekler',
    ImportPanel_RowsColsSummary: '{rows} satır, {cols} sütun algılandı',
    ImportPanel_LoadingPlannerPlans: 'Planner planları yükleniyor…',
    ImportPanel_PlannerLoadError: 'Planner planları yüklenemedi.',
    ImportPanel_PlannerPermissionsHintPrefix: 'Planner\'a erişiminizin olduğundan ve ',
    ImportPanel_PlannerPermissionsHintEmphasis: 'Planner ve To Do ile Görevler',
    ImportPanel_PlannerPermissionsHintSuffix: ' uygulamasının bu sitede kullanılabilir olduğundan emin olun.',
    ImportPanel_NoPlannerPlansFoundTitle: 'Planner planı bulunamadı',
    ImportPanel_NoPlannerPlansFoundBody: 'Herhangi bir Planner planına erişiminiz olmayabilir veya bu hesap için hiç plan bulunmuyor olabilir.',
    ImportPanel_TaskCountFoundIn: '"{planName}" içinde {count} görev bulundu',
    ImportPanel_ProjectDetailsIntroPrefix: '',
    ImportPanel_ProjectDetailsIntroSuffix: ' projesine aktarılıyor. Aşağıdaki proje ayrıntılarını gözden geçirin.',
    ImportPanel_ProjectNameLabel: 'Proje Adı',
    ImportPanel_DescriptionLabel: 'Açıklama',
    ImportPanel_StatusLabel: 'Durum',
    ImportPanel_ColorLabel: 'Renk',
    ImportPanel_MapIntro: 'Dosyanızdaki sütunları görev alanlarıyla eşleştirin.',
    ImportPanel_CreatingProjectStatus: 'Proje oluşturuluyor…',
    ImportPanel_ImportingTasksStatus: 'Görevler içe aktarılıyor…',
    ImportPanel_ProgressLabel: '{total} içinden {done}',
    ImportPanel_CouldNotCreateProject: 'Proje oluşturulamadı.',
    ImportPanel_ImportCompletedWithErrors: 'İçe aktarma {count} hatayla tamamlandı.',
    ImportPanel_ProjectCreatedSuccess: 'Proje başarıyla oluşturuldu!',
    ImportPanel_ImportSuccessful: 'İçe aktarma başarılı!',
    ImportPanel_TasksAddedTo: '{count} görev "{projectName}" projesine eklendi',
    ImportPanel_FailedRowsLabel: 'Başarısız satırlar:',
    ImportPanel_CloseButton: 'Kapat',
    ImportPanel_OpenProjectButton: 'Projeyi Aç',
    ImportPanel_ViewImportedTasksButton: 'İçe Aktarılan Görevleri Görüntüle',
    ImportPanel_NextMapColumnsButton: 'İleri: Sütunları Eşleştir',
    ImportPanel_ImportNTasksButton: '{count} Görevi İçe Aktar',
    ImportPanel_BackButton: 'Geri',
    ImportPanel_CancelButton: 'İptal',
    ImportPanel_NextButton: 'İleri',
    ImportPanel_StepSource: 'Kaynak',
    ImportPanel_StepProject: 'Proje',
    ImportPanel_StepMap: 'Eşleştirme',
    ImportPanel_StepImport: 'İçe Aktar',
    ImportPanel_StepDone: 'Tamamlandı',
    ImportPanel_ImportAsNewProjectHeader: 'Dosyayı Yeni Proje Olarak İçe Aktar',
    ImportPanel_ImportIntoProjectHeader: 'Görevleri {projectName} Projesine Aktar',
    ImportPanel_CouldNotParseFile: 'Dosya işlenemedi.',
    ImportPanel_CouldNotLoadPlannerTasks: 'Bu plandaki görevler yüklenemedi.',
    ImportPanel_CouldNotCreateProjectDetail: 'Proje oluşturulamadı: {detail}',
    ImportPanel_CouldNotLinkDependencies: 'Bağımlılıklar bağlanamadı: {detail}',
    ImportPanel_UnknownError: 'bilinmeyen hata',

    // ── Column mapper (import) ──
    ColumnMapper_TaskNameRequiredBanner: 'Devam etmek için Görev Adı eşleştirilmelidir.',
    ColumnMapper_SkippedColumnsBanner: '{count} sütun atlanacak.',
    ColumnMapper_SourceColumnHeader: 'Kaynak Sütun',
    ColumnMapper_TargetFieldHeader: 'Hedef Alan',
    ColumnMapper_StatusHeader: 'Durum',
    ColumnMapper_SkippedBadge: 'Atlandı',
    ColumnMapper_AutoMappedBadge: 'Otomatik eşleştirildi',
    ColumnMapper_SetBadge: 'Ayarlandı',
    ColumnMapper_PreviewTitle: 'Önizleme: {columnName}',
    ColumnMapper_EmptyCellDash: '—',

    // ── Import field display names / ImportService ──
    ImportField_TaskName: 'Görev Adı',
    ImportField_StartDate: 'Başlangıç Tarihi',
    ImportField_DueDate: 'Bitiş Tarihi',
    ImportField_Status: 'Durum',
    ImportField_Priority: 'Öncelik',
    ImportField_AssignedTo: 'Atanan Kişi',
    ImportField_AssignedToEmail: 'Atanan Kişi E-postası',
    ImportField_PercentComplete: '% Tamamlandı',
    ImportField_Phase: 'Aşama',
    ImportField_Description: 'Açıklama',
    ImportField_Notes: 'Notlar',
    ImportField_IsMilestone: 'Kilometre Taşı mı',
    ImportField_Dependencies: 'Bağımlılıklar',
    ImportField_SkipColumn: '(Bu sütunu atla)',
    ImportService_EmptyFileError: 'Dosya boş görünüyor veya veri satırı içermiyor.',
    ImportService_ReadErrorDetail: 'Dosya okunamadı: {detail}.',
    ImportService_FileReadError: 'Dosya okuma hatası.',
    ImportService_RowError: 'Satır {rowNum} ("{title}"): {error}',
    ImportService_AmbiguousDependency: '"{name}" bağımlılığı birden fazla görev başlığıyla eşleşiyor — atlandı.',
    ImportService_LinkDependencyError: '{taskId} görevi için bağımlılıklar bağlanamadı: {error}',

    // ── Health labels (shared: healthUtils.ts and ExportService.ts both use this set; also replaces the duplicated Export_PortfolioHealthLabel* keys) ──
    Health_Done: 'Tamamlandı',
    Health_OnTrack: 'Yolunda',
    Health_AtRisk: 'Riskli',
    Health_Overdue: 'Süresi Geçmiş',

    // ── Status / Priority display labels (DISPLAY-ONLY — stored SharePoint Choice values remain unchanged/English) ──
    Status_NotStarted: 'Başlamadı',
    Status_InProgress: 'Devam Ediyor',
    Status_Completed: 'Tamamlandı',
    Status_OnHold: 'Beklemede',
    Status_Cancelled: 'İptal Edildi',
    Priority_Critical: 'Kritik',
    Priority_High: 'Yüksek',
    Priority_Medium: 'Orta',
    Priority_Low: 'Düşük',
    ProjectStatus_Planning: 'Planlama',
    ProjectStatus_Active: 'Aktif',
    ProjectStatus_OnHold: 'Beklemede',
    ProjectStatus_Completed: 'Tamamlandı',
    ProjectStatus_Cancelled: 'İptal Edildi',

    // ── Shell (SmartGantt.tsx) ──
    SmartGantt_LoadingProjects: 'Projeler yükleniyor…',
    SmartGantt_UnableToLoad: 'Yüklenemiyor',
    SmartGantt_RetryButton: 'Yeniden Dene',
    SmartGantt_NoProjectsYet: 'Henüz proje yok',
    SmartGantt_NoProjectsSubtitle: 'Başlamak için ilk projenizi oluşturun.',
    SmartGantt_CreateFirstProjectButton: '+ İlk Projeyi Oluştur',
    SmartGantt_ImportFromExcelButton: '📥 Excel\'den İçe Aktar',
    SmartGantt_LoadingTasks: 'Görevler yükleniyor…',
    SmartGantt_DismissAriaLabel: 'Kapat',
    SmartGantt_DeleteTaskDialogTitle: 'Görevi Sil',
    SmartGantt_DeleteTaskDialogSubtext: '"{taskTitle}" görevini silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
    SmartGantt_DeleteButton: 'Sil',
    SmartGantt_CancelButton: 'İptal',
    SmartGantt_ArchiveProjectDialogTitle: 'Projeyi Arşivle',
    SmartGantt_ArchiveProjectDialogSubtext: '"{projectTitle}" arşivlensin mi? Daha sonra arşivden çıkarabilirsiniz.',
    SmartGantt_ArchiveButton: 'Arşivle',
    SmartGantt_SendToRecycleBinDialogTitle: 'Geri Dönüşüm Kutusuna Gönder',
    SmartGantt_SendToRecycleBinDialogSubtext: '"{projectTitle}" site geri dönüşüm kutusuna gönderilsin mi?',
    SmartGantt_SendToRecycleBinButton: 'Geri Dönüşüm Kutusuna Gönder',
    SmartGantt_FailedLoadProjects: 'Projeler yüklenemedi. Site izinlerini kontrol edin.',
    SmartGantt_FailedLoadTasks: 'Bu proje için görevler yüklenemedi.',
    SmartGantt_FailedLoadPortfolioStats: 'Portföy istatistikleri yüklenemedi.',
    SmartGantt_CouldNotSaveProject: 'Proje kaydedilemedi: {message}',
    SmartGantt_CouldNotDeleteProject: 'Proje silinemedi: {message}',
    SmartGantt_CouldNotArchiveProject: 'Proje arşivlenemedi: {message}',
    SmartGantt_CouldNotUnarchiveProject: 'Proje arşivden çıkarılamadı: {message}',
    SmartGantt_CouldNotSaveTask: 'Görev kaydedilemedi: {message}',
    SmartGantt_CouldNotDeleteTask: 'Görev silinemedi: {message}',
    SmartGantt_ImageExportFailed: 'Resim dışa aktarma başarısız oldu: {message}',
    SmartGantt_PowerPointExportFailed: 'PowerPoint dışa aktarma başarısız oldu: {message}',
    SmartGantt_PortfolioExportFailed: 'Portföy dışa aktarma başarısız oldu: {message}',
    SmartGantt_CouldNotUpdateTask: 'Görev güncellenemedi: {message}',

    // ── Common ──
    ColorSwatch_AutoColorAriaLabel: 'Otomatik renk',
    ColorSwatch_CustomColorAriaLabel: 'Özel renk',
    ColorSwatch_PickCustomColorTitle: 'Özel bir renk seçin',

    // ── Export (Excel / PowerPoint) ──
    Export_ColTaskName: 'Görev Adı',
    Export_ColPhase: 'Aşama',
    Export_ColStartDate: 'Başlangıç Tarihi',
    Export_ColDueDate: 'Bitiş Tarihi',
    Export_ColStatus: 'Durum',
    Export_ColPriority: 'Öncelik',
    Export_ColAssignedTo: 'Atanan Kişi',
    Export_ColAssignedToEmail: 'Atanan Kişi E-postası',
    Export_ColPercentComplete: '% Tamamlandı',
    Export_ColIsMilestone: 'Kilometre Taşı mı',
    Export_ColDescription: 'Açıklama',
    Export_ColNotes: 'Notlar',
    Export_Yes: 'Evet',
    Export_No: 'Hayır',
    Export_SheetNameTasks: 'Görevler',
    Export_ExcelFileSuffix: ' - Görevler.xlsx',
    Export_TaskNameColumnLabel: 'GÖREV ADI',
    Export_ExportedDateLabel: 'Dışa Aktarma Tarihi: {date}',
    Export_ProjectReportLabel: 'PROJE RAPORU',
    Export_StatusLine: 'Durum: {status}',
    Export_DateRangeSeparator: ' - ',
    Export_ProjectManagerLine: 'Proje Yöneticisi: {name}',
    Export_GeneratedDateLine: 'Oluşturulma Tarihi: {date}',
    Export_ProjectSummaryTitle: 'Proje Özeti',
    Export_StatTotalTasks: 'Toplam Görev',
    Export_StatCompleted: 'Tamamlandı',
    Export_StatInProgress: 'Devam Ediyor',
    Export_StatOnHold: 'Beklemede',
    Export_StatNotStarted: 'Başlamadı',
    Export_OverallProgressLine: 'Genel İlerleme',
    Export_OverallProgressPercent: '%{percent}',
    Export_StatusBreakdownTitle: 'Durum Dağılımı',
    Export_StatusBreakdownRow: '{status}: {count} (%{percent})',
    Export_GanttTimelineTitle: 'Gantt Zaman Çizelgesi',
    Export_SummaryRecentActivityTitle: 'Son Etkinlik',
    Export_ProjectOverviewLabel: 'Proje Genel Bakışı',
    Export_DetailStatusLabel: 'Durum',
    Export_DetailStartDateLabel: 'Başlangıç Tarihi',
    Export_DetailDueDateLabel: 'Bitiş Tarihi',
    Export_DetailProjectManagerLabel: 'Proje Yöneticisi',
    Export_Past7DaysLabel: 'Son 7 Gün',
    Export_NoActivityMessage: 'Son etkinlik yok.',
    Export_CompletedThisWeekHeader: 'Bu Hafta Tamamlanan ({count})',
    Export_NewBadge: 'YENİ  ',
    Export_CompletedPercentLine: '%{percent} tamamlandı',
    Export_MoreItemsSuffix: '+ {count} daha',
    Export_InProgressUpdatedHeader: 'Devam Eden / Güncellenen',
    Export_StatusPercentLine: '{status} — %{percent}',
    Export_PortfolioReportLabel: 'PORTFÖY RAPORU',
    Export_PortfolioOverviewTitle: 'Portföy Genel Bakışı',
    Export_ProjectsCountLine: '{count} Proje',
    Export_HealthSummaryOnTrack: '{count} Yolunda',
    Export_HealthSummaryAtRisk: '{count} Riskli',
    Export_HealthSummaryOverdue: '{count} Süresi Geçmiş',
    Export_ProjectsSummaryHeader: 'Proje Özeti',
    Export_TableProject: 'Proje',
    Export_TableStatus: 'Durum',
    Export_TableHealth: 'Sağlık Durumu',
    Export_TableTotal: 'Toplam',
    Export_TableDone: 'Tamamlandı',
    Export_TableActive: 'Aktif',
    Export_TableAtRisk: 'Riskli',
    Export_TableOverdue: 'Süresi Geçmiş',
    Export_TablePctDone: '% Tamamlandı',
    Export_TableDueDate: 'Bitiş Tarihi',
    Export_PortfolioSummaryFileName: 'Portföy Özeti.xlsx',
    Export_PortfolioReportFileName: 'Portföy Raporu.pptx',
    Export_ProjectReportFileName: '{projectName} Raporu.pptx',
    Export_UnavailableLabel: 'Kullanılamıyor',
    Export_SheetNamePortfolio: 'Portföy',
    Export_ColStart: 'Başlangıç',
    Export_ColDue: 'Bitiş',
    Export_ImageGenerationFailed: 'Görsel oluşturulamadı — grafik görsel olarak dışa aktarılamayacak kadar büyük olabilir.',
    Export_DrawingContextFailed: 'Dışa aktarma için bir çizim bağlamı oluşturulamadı.',
    Export_SvgRenderFailed: 'SVG oluşturma başarısız oldu',

    // ── Added in v1.5 review ──
    Svc_TooManyDependencies: 'Bu görevin kaydedilemeyecek kadar çok bağımlılığı var (sınır yaklaşık 60). Bazılarını kaldırıp yeniden deneyin.',
    Svc_TaskChangedByOthers: 'Bu görev, siz yükledikten sonra başka biri tarafından değiştirildi. Sayfayı yenileyip yeniden deneyin.',
    Svc_ProjectChangedByOthers: 'Bu proje, siz açtıktan sonra başka biri tarafından değiştirildi. Sayfayı yenileyip yeniden deneyin.',
    Svc_ColumnCreateFailed: 'Yeni görev listesinde {count} sütun oluşturulamadı: {detail}',
    Svc_BaselineUnavailable: 'Temel plan sütunları eklenemediği için bu proje için temel planlar kullanılamıyor (listeyi düzenleme izniniz gerekebilir).',
    Svc_SubtaskReassignFailed: 'Bu görevin alt görevleri silinmeden önce yeniden atanamadı: {detail}',
    Svc_UnresolvedDependency: '{row}. satır ("{title}"): "{name}" bağımlılığı içe aktarılan bir görevle eşleştirilemedi.',
    Svc_SelfDependency: '{row}. satır ("{title}"): "{name}" bağımlılığı görevin kendisini gösteriyor ve atlandı.',
    Svc_ColId: 'Kimlik',
    Svc_ColDependencies: 'Bağımlılıklar',
    Svc_ColBaselineStart: 'Temel Plan Başlangıcı',
    Svc_ColBaselineDue: 'Temel Plan Bitişi',
    Svc_CsvFileSuffix: ' - Görevler.csv',
    Svc_IcsFileSuffix: ' - Kilometre Taşları.ics',
    Svc_PortfolioCsvFileName: 'Portföy Özeti.csv',
    Svc_PP_DisplayGroup: 'Varsayılanlar',
    Svc_PP_DefaultView: 'Varsayılan görünüm',
    Svc_PP_ViewGantt: 'Gantt',
    Svc_PP_ViewList: 'Liste',
    Svc_PP_ViewKanban: 'Kanban',
    Svc_PP_ViewDashboard: 'Pano',
    Svc_PP_ViewPortfolio: 'Portföy',
    Svc_PP_DefaultZoom: 'Varsayılan yakınlaştırma',
    Svc_PP_ZoomDay: 'Gün',
    Svc_PP_ZoomWeek: 'Hafta',
    Svc_PP_ZoomMonth: 'Ay',
    Svc_PP_ZoomQuarter: 'Çeyrek',
    Svc_PP_CalendarGroup: 'Çalışma takvimi',
    Svc_PP_DaySun: 'Pazar bir iş günüdür',
    Svc_PP_DayMon: 'Pazartesi bir iş günüdür',
    Svc_PP_DayTue: 'Salı bir iş günüdür',
    Svc_PP_DayWed: 'Çarşamba bir iş günüdür',
    Svc_PP_DayThu: 'Perşembe bir iş günüdür',
    Svc_PP_DayFri: 'Cuma bir iş günüdür',
    Svc_PP_DaySat: 'Cumartesi bir iş günüdür',
    Svc_PP_Holidays: 'Tatiller (çalışılmayan tarihler)',
    Svc_PP_HolidaysHint: 'Her satıra bir tarih, yyyy-MM-dd biçiminde (örneğin 2026-12-25).',
    Gantt_TimelineAriaLabel: 'Görev zaman çizelgesi',
    Gantt_DragLabel: '{start} → {end} ({days}g)',
    Gantt_KeyboardMoveAnnouncement: '{taskTitle}: {startDate} - {dueDate}',
    Gantt_KeyboardHint: 'Görevi açmak için Enter tuşuna basın. Sol ve sağ ok tuşları görevi bir iş günü kaydırır. Ok tuşlarıyla birlikte Shift bitiş tarihini değiştirir.',
    Gantt_ParentCycleTooltip: 'Bu görev döngüsel bir üst görev ve alt görev zincirinin parçası olduğundan en üst düzeyde gösteriliyor',
    Gantt_CollapseAll: 'Tüm aşamaları daralt',
    Gantt_ExpandAll: 'Tüm aşamaları genişlet',
    Gantt_BaselineTooltip: 'Temel plan: {start} → {due}',
    Gantt_VarianceTooltip: 'Bitiş sapması: temel plana göre {days} gün',
    Gantt_LinkHandleTitle: 'Bağımlılık oluşturmak için başka bir görevin üzerine sürükleyin',
    Toolbar_FitToProject: 'Sığdır',
    Toolbar_FitToProjectTitle: 'Tüm projeye sığacak şekilde yakınlaştır',
    Toolbar_UndoTitle: 'Geri Al (Ctrl+Z)',
    Toolbar_RedoTitle: 'Yinele (Ctrl+Y)',
    Toolbar_ExportCsv: '📄 Görevleri CSV\'ye Aktar',
    Toolbar_ExportIcs: '📅 Kilometre Taşlarını Aktar (iCal)',
    Toolbar_Print: '🖨 Yazdır / PDF Olarak Kaydet',
    Toolbar_SetBaseline: '📐 Temel Plan Belirle…',
    Toolbar_CopyLink: '🔗 Bağlantıyı Kopyala',
    Toolbar_CopyLinkTitle: 'Bu görünümün bağlantısını kopyala (proje, görünüm, yakınlaştırma ve filtreler)',
    App_UndoButton: 'Geri Al',
    App_Undone: 'Değişiklik geri alındı.',
    App_Redone: 'Değişiklik yinelendi.',
    App_DependentsMovedOne: '1 bağımlı görev taşındı.',
    App_DependentsMovedMany: '{count} bağımlı görev taşındı.',
    App_TaskConflict: 'Bu görev başka biri tarafından değiştirildi. En son görevler yeniden yüklendi — bunları inceleyip yeniden deneyin.',
    App_DependencyCycle: 'Bu bağlantı döngüsel bir bağımlılık oluşturur.',
    App_DependencyExists: 'Bu görevler zaten bağlı.',
    App_LinkCopied: 'Bağlantı panoya kopyalandı.',
    App_LinkCopyFailed: 'Bağlantı kopyalanamadı: {message}',
    App_PopupBlocked: 'Yazdırma penceresi engellendi. Bu site için açılır pencerelere izin verip yeniden deneyin.',
    App_SetBaselineDialogTitle: 'Temel Plan Belirle',
    App_SetBaselineDialogSubtext: 'Tüm {count} görevin geçerli başlangıç ve bitiş tarihleri temel plan olarak kaydedilsin mi? Mevcut temel plan değiştirilir.',
    App_SetBaselineButton: 'Temel Plan Belirle',
    App_BaselineSaved: 'Temel plan kaydedildi.',
    App_BaselineFailed: 'Temel plan kaydedilemedi: {message}',
    App_CsvExportFailed: 'CSV dışa aktarma başarısız oldu: {message}',
    App_IcsExportFailed: 'Takvim dışa aktarma başarısız oldu: {message}',
    App_BulkDeleteDialogTitle: 'Görevleri Sil',
    App_BulkDeleteDialogSubtext: '{count} görevi silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
    Common_PeoplePicker_ClearAriaLabel: 'Temizle',
    Common_PeoplePicker_DirectoryHeader: 'Dizindeki kişiler',
    Common_PeoplePicker_EmailLabel: 'E-posta (isteğe bağlı)',
    Common_PeoplePicker_EmailPlaceholder: 'name@company.com',
    Common_PeoplePicker_ExternalHint: 'Dizinde yok. Serbest metin olarak kaydedilir.',
    Common_PeoplePicker_InvalidEmail: 'Geçerli bir e-posta adresi girin.',
    Common_PeoplePicker_ListAriaLabel: 'Kişi önerileri',
    Common_PeoplePicker_RecentHeader: 'Son kullanılanlar',
    Common_PeoplePicker_ResultsAnnouncement: '{count} öneri var',
    Common_PeoplePicker_Searching: 'Aranıyor…',
    Common_PeoplePicker_UseExternal: '"{name}" kullan (harici / dizinde yok)',
    Import_Mapper_PreviewFirstRows: 'Önizleme (ilk {count} satır)',
    Import_Mapper_RequiredLegend: 'Zorunlu alan',
    Import_Mapper_RequiredMarkerLabel: 'Zorunlu',
    Import_Mapper_SelectAriaLabel: '{columnName} sütunu için hedef alan',
    Import_Panel_DateOrderAuto: 'Otomatik algıla',
    Import_Panel_DateOrderDMY: 'Gün/Ay/Yıl (31/12/2026)',
    Import_Panel_DateOrderDetected: 'Dosyanızdan algılandı: {order}.',
    Import_Panel_DateOrderHint: '03/04/2026 gibi rakamlarla yazılmış tarihlere uygulanır.',
    Import_Panel_DateOrderLabel: 'Tarih sırası',
    Import_Panel_DateOrderMDY: 'Ay/Gün/Yıl (12/31/2026)',
    Import_Panel_DropZoneAriaLabel: 'İçe aktarılacak bir dosya seçin. Göz atmak için Enter tuşuna basın.',
    Import_Panel_DropZoneChangeAriaLabel: 'Seçilen dosya: {fileName}. Farklı bir dosya seçmek için Enter tuşuna basın.',
    Import_Panel_FailedCount: '{count} başarısız',
    Import_Panel_NewProjectIntroMany: 'Yeni bir proje oluşturulacak ve {count} görevin tümü bu projeye aktarılacak. Bu ayrıntıları içe aktarmadan sonra istediğiniz zaman değiştirebilirsiniz.',
    Import_Panel_NewProjectIntroOne: 'Yeni bir proje oluşturulacak ve {count} görev bu projeye aktarılacak. Bu ayrıntıları içe aktarmadan sonra istediğiniz zaman değiştirebilirsiniz.',
    Import_Panel_PlanAriaLabel: '{planName}, {groupName}',
    Import_Panel_ProblemEndBeforeStart: 'Bitiş tarihi başlangıç tarihinden önce',
    Import_Panel_ProblemInvalidDueDate: '"{value}" bitiş tarihi geçerli bir tarih değil',
    Import_Panel_ProblemInvalidStartDate: '"{value}" başlangıç tarihi geçerli bir tarih değil',
    Import_Panel_ProblemMissingTitle: 'Görev adı eksik',
    Import_Panel_ProgressLabelWithPercent: '{done} / {total} (%{percent})',
    Import_Panel_SkipInvalidRows: 'Sorunlu satırları atla',
    Import_Panel_SuccessWithWarningsMany: 'İçe aktarma {count} uyarıyla başarılı oldu.',
    Import_Panel_SuccessWithWarningsOne: 'İçe aktarma {count} uyarıyla başarılı oldu.',
    Import_Panel_ValidationHeader: 'Sorunlu satırlar',
    Import_Panel_ValidationMore: '…ve {count} tane daha',
    Import_Panel_ValidationRow: 'Satır {rowNum}: {problem}',
    Import_Panel_ValidationSummaryMany: '{count} satırda sorun var',
    Import_Panel_ValidationSummaryOne: '{count} satırda sorun var',
    Import_Panel_WarningsLabel: 'Uyarılar ({count}):',
    Panel_Project_ManagerLabel: 'Proje Yöneticisi',
    Panel_Project_ManagerPlaceholder: 'Kişi arayın veya bir ad yazın…',
    Panel_Task_BaselineDueLabel: 'Temel plan bitişi',
    Panel_Task_BaselineHeader: 'Temel plan',
    Panel_Task_BaselineStartLabel: 'Temel plan başlangıcı',
    Panel_Task_DepTypeFF: 'Bitişten Bitişe (FF)',
    Panel_Task_DepTypeFS: 'Bitişten Başlangıca (FS)',
    Panel_Task_DepTypeSF: 'Başlangıçtan Bitişe (SF)',
    Panel_Task_DepTypeSS: 'Başlangıçtan Başlangıca (SS)',
    Panel_Task_LagAriaLabel: '{taskTitle} için iş günü cinsinden gecikme',
    Panel_Task_LagHint: 'Gecikme iş günü cinsindendir. Öndeleme için negatif bir sayı kullanın.',
    Panel_Task_LinkTypeAriaLabel: '{taskTitle} için bağlantı türü',
    Panel_Task_VarianceEarlier: '{days} iş günü erken',
    Panel_Task_VarianceLater: '{days} iş günü geç',
    Panel_Task_VarianceOnBaseline: 'temel planda',
    View_Dashboard_BurndownActual: 'Gerçekleşen',
    View_Dashboard_BurndownAria: 'Burndown grafiği: {total} görevden {remaining} tanesi kaldı',
    View_Dashboard_BurndownHeader: 'Burndown (Kalan Görevler)',
    View_Dashboard_BurndownIdeal: 'İdeal',
    View_Dashboard_BurndownNoData: 'Burndown çizmek için tarihli yeterli görev yok.',
    View_Dashboard_CriticalPathHeader: 'Kritik Yol  ({count})',
    View_Dashboard_PhaseDoneSummary: '{done}/{total} tamamlandı  •  %{percent}',
    View_Dashboard_TaskRowAriaLabel: '{taskTitle} görevini aç, {status}',
    View_Dashboard_WorkloadHeader: 'Atanan Kişiye Göre İş Yükü',
    View_Dashboard_WorkloadOpen: '{count} açık',
    View_Dashboard_WorkloadOverdue: '{count} gecikmiş',
    View_Kanban_AddTaskInColumnAriaLabel: '{column} sütununa görev ekle',
    View_Kanban_CollapseColumn: '{column} sütununu daralt',
    View_Kanban_ExpandColumn: '{column} sütununu genişlet',
    View_Kanban_LaneHeader: '{name} ({count})',
    View_Kanban_LaneNoPhase: 'Aşama yok',
    View_Kanban_LaneUnassigned: 'Atanmamış',
    View_Kanban_LanesAssignee: 'Atanan kişi',
    View_Kanban_LanesNone: 'Yok',
    View_Kanban_LanesPhase: 'Aşama',
    View_Kanban_SwimlanesLabel: 'Yüzme şeritleri',
    View_Kanban_WipEditTitle: '{column} için devam eden iş sınırını belirle (sınırsız için 0)',
    View_Kanban_WipExceededTitle: 'WIP sınırı aşıldı: {limit} sınırında {count}',
    View_Kanban_WipInputAriaLabel: '{column} için WIP sınırı',
    View_Kanban_WipLabel: 'WIP {count}/{limit}',
    View_Kanban_WipSet: 'WIP',
    View_List_BulkAssignApply: 'Ata',
    View_List_BulkAssigneePlaceholder: 'Ata…',
    View_List_BulkBarAriaLabel: 'Seçili görevler için toplu eylemler',
    View_List_BulkClear: 'Seçimi temizle',
    View_List_BulkDelete: 'Seçilenleri sil',
    View_List_BulkPercentApply: '% belirle',
    View_List_BulkPercentPlaceholder: '% tamamlanma',
    View_List_BulkPriorityPlaceholder: 'Öncelik belirle…',
    View_List_BulkSelectedCount: '{count} seçildi',
    View_List_BulkStatusPlaceholder: 'Durum belirle…',
    View_List_ExportCsv: 'CSV\'ye Aktar',
    View_List_NonWorkingDay: 'Çalışılmayan gün',
    View_List_SelectAllAriaLabel: 'Tüm görevleri seç',
    View_List_SelectRowAriaLabel: '{taskTitle} görevini seç',
    View_Portfolio_CardAriaLabel: '{projectName} projesini aç, {status}',
    View_Portfolio_ClearFilters: 'Filtreleri temizle',
    View_Portfolio_FilteredCount: '{total} projeden {shown} tanesi',
    View_Portfolio_HideDone: 'Tamamlananları / iptal edilenleri gizle',
    View_Portfolio_NoMatches: 'Filtrelerinizle eşleşen proje yok.',
    View_Portfolio_ProjectCountMany: '{count} Proje',
    View_Portfolio_ProjectCountOne: '{count} Proje',
    View_Portfolio_SearchAriaLabel: 'Projelerde ara',
    View_Portfolio_SearchPlaceholder: 'Projelerde ara…',
    Import_Panel_CopyDetails: 'Ayrıntıları kopyala',
    Import_Panel_Copied: 'Kopyalandı',
  };
});
