define([], function () {
  return {
    // ── Property pane ──
    PropertyPane_HeaderDescription: 'Налаштування Smart Gantt Chart',
    PropertyPane_GeneralGroupName: 'Загальні',
    PropertyPane_TitleFieldLabel: 'Назва веб-частини',
    WebPart_DefaultTitle: 'Smart Gantt Chart',

    // ── Toolbar ──
    Toolbar_ViewDashboard: 'Панель приладів',
    Toolbar_ViewList: 'Список',
    Toolbar_ViewGantt: 'Діаграма Ганта',
    Toolbar_ViewKanban: 'Канбан',
    Toolbar_ZoomDay: 'День',
    Toolbar_ZoomWeek: 'Тиждень',
    Toolbar_ZoomMonth: 'Місяць',
    Toolbar_ZoomQuarter: 'Квартал',
    Toolbar_SelectProjectAriaLabel: 'Виберіть проєкт',
    Toolbar_PortfolioLabel: 'Портфель',
    Toolbar_SelectAProject: 'Виберіть проєкт',
    Toolbar_AllProjectsSubtext: 'Усі проєкти',
    Toolbar_NoProjectsYet: 'Проєктів ще немає',
    Toolbar_ArchivedBadge: 'Заархівовано',
    Toolbar_ShowArchivedProjects: 'Показати заархівовані проєкти',
    Toolbar_NewProject: '+ Новий проєкт',
    Toolbar_ImportFileAsNewProject: '📥 Імпортувати файл як новий проєкт…',
    Toolbar_AddTask: '+ Додати завдання',
    Toolbar_EditProject: 'Редагувати проєкт',
    Toolbar_OptionsButton: '⚙ Параметри',
    Toolbar_MoreOptionsTitle: 'Додаткові параметри',
    Toolbar_ExportToExcel: '📊 Експортувати в Excel',
    Toolbar_ExportToPowerPoint: '📑 Експортувати в PowerPoint',
    Toolbar_ScrollToTodayTitle: 'Перейти до сьогодні',
    Toolbar_TodayButton: '◉ Сьогодні',
    Toolbar_ImportTasks: '📥 Імпортувати завдання…',
    Toolbar_ExportAsImage: '🖼 Експортувати як зображення (PNG)',
    Toolbar_UnarchiveProject: '📂 Розархівувати проєкт',
    Toolbar_ArchiveProject: '🗄️ Архівувати проєкт',
    Toolbar_SendToRecycleBin: '🗑️ Перемістити в кошик',

    // ── Filter bar ──
    FilterBar_ClearOption: 'Очистити',
    FilterBar_DueAny: 'Будь-який термін',
    FilterBar_DueOverdue: 'Прострочено',
    FilterBar_DueToday: 'Термін сьогодні',
    FilterBar_DueWeek: 'Термін протягом 7 днів',
    FilterBar_SearchPlaceholder: 'Пошук завдань…',
    FilterBar_SearchAriaLabel: 'Пошук завдань',
    FilterBar_StatusChipLabel: 'Статус',
    FilterBar_PriorityChipLabel: 'Пріоритет',
    FilterBar_AssigneeChipLabel: 'Виконавець',
    FilterBar_PhaseChipLabel: 'Етап',
    FilterBar_DueDateAriaLabel: 'Фільтрувати за терміном виконання',
    FilterBar_MatchCount: '{matchCount} з {totalCount}',
    FilterBar_ClearFilters: '✕ Очистити фільтри',
    FilterBar_ChipLabelWithCount: '{label} ({count}) ▾',
    FilterBar_ChipLabelNoCount: '{label} ▾',

    // ── Gantt view ──
    Gantt_TaskColumnHeader: 'Завдання',
    Gantt_DurationColumnHeader: 'Трив.',
    Gantt_AddTaskButton: '+ Додати завдання',
    Gantt_EmptyTitle: 'Завдань ще немає',
    Gantt_EmptySubtitle: 'Додайте завдання, щоб побачити їх на діаграмі Ганта.',
    Gantt_AddFirstTask: '+ Додати перше завдання',
    Gantt_ImportTasksButton: '📥 Імпортувати завдання',
    Gantt_EditTitle: 'Редагувати',
    Gantt_DeleteTitle: 'Видалити',
    Gantt_EditTaskAriaLabel: 'Редагувати завдання {taskTitle}',
    Gantt_DeleteTaskAriaLabel: 'Видалити завдання {taskTitle}',
    Gantt_ExpandPhaseAriaLabel: '{action} етап {phase}',
    Gantt_ExpandAction: 'Розгорнути',
    Gantt_CollapseAction: 'Згорнути',
    Gantt_DependencyViolationTooltip: 'Розпочато до завершення всіх залежностей',
    Gantt_MilestoneAriaLabel: '{taskTitle}, віха, {date}',
    Gantt_BarAriaLabel: '{taskTitle}, з {startDate} до {dueDate}, виконано {percent}%',
    Gantt_PercentCompleteTooltip: 'Виконано {value}%',

    // ── Gantt options/settings panel ──
    GanttSettings_PanelHeader: '⚙ Параметри',
    GanttSettings_ColorCodingSection: 'Кольорове кодування',
    GanttSettings_ByStatus: 'За статусом',
    GanttSettings_ByPriority: 'За пріоритетом',
    GanttSettings_ByPhase: 'За етапом',
    GanttSettings_ByHealth: 'За станом',
    GanttSettings_HeaderColorSection: 'Колір заголовка',
    GanttSettings_ThemeDark: 'Темна',
    GanttSettings_ThemeNavy: 'Темно-синя',
    GanttSettings_ThemeTeal: 'Бірюзова',
    GanttSettings_ThemePurple: 'Фіолетова',
    GanttSettings_ThemeLight: 'Світла',
    GanttSettings_HeaderLabelsSection: 'Підписи заголовка',
    GanttSettings_WeekLabelDates: 'Дати',
    GanttSettings_WeekLabelDatesDesc: '3 черв., 10 черв.…',
    GanttSettings_WeekLabelProject: 'Тижні проєкту',
    GanttSettings_WeekLabelProjectDesc: 'Т1, Т2…',
    GanttSettings_WeekLabelIso: 'Календарні тижні',
    GanttSettings_WeekLabelIsoDesc: 'Т23, Т24…',
    GanttSettings_ProjectWeeksHint: 'Тиждень 1 починається з понеділка вашого найранішого завдання — чудово підходить для презентацій.',
    GanttSettings_BarStyleSection: 'Стиль смуг',
    GanttSettings_BarStyleGradient: 'Градієнт',
    GanttSettings_BarStyleFlat: 'Плоский',
    GanttSettings_RowHeightSection: 'Висота рядка',
    GanttSettings_HeightCompact: 'Компактна',
    GanttSettings_HeightNormal: 'Звичайна',
    GanttSettings_HeightSpacious: 'Просторна',
    GanttSettings_ShowHideSection: 'Показати / приховати',
    GanttSettings_WeekendShading: 'Затінення вихідних',
    GanttSettings_DependencyArrows: 'Стрілки залежностей',
    GanttSettings_CriticalPathAlwaysVisible: 'Критичний шлях завжди видимий',
    GanttSettings_AllOthersOnHoverOnly: 'Усі інші лише при наведенні',
    GanttSettings_CriticalPathHighlight: 'Виділення критичного шляху',
    GanttSettings_ProgressPercentOnBars: 'Відсоток виконання на смугах',
    GanttSettings_AssigneeNameOnBars: 'Ім\'я виконавця на смугах',
    GanttSettings_HealthStatusBadges: 'Значки стану виконання',

    // ── List view ──
    ListView_ColTaskName: 'Назва завдання',
    ListView_ColStatus: 'Статус',
    ListView_ColHealth: 'Стан',
    ListView_ColPriority: 'Пріоритет',
    ListView_ColStart: 'Початок',
    ListView_ColDue: 'Термін',
    ListView_ColAssignedTo: 'Виконавець',
    ListView_ColProgress: 'Прогрес',
    ListView_ColPhase: 'Етап',
    ListView_ColPredecessors: 'Попередники',
    ListView_EmptyTitle: 'Завдань ще немає',
    ListView_AddFirstTask: '+ Додати перше завдання',
    ListView_AddTaskRow: '+ Додати завдання',
    ListView_Unassigned: 'Не призначено',
    ListView_DependencyViolationTooltip: 'Розпочато до завершення всіх залежностей',
    ListView_StatusAriaLabel: 'Статус завдання {taskTitle}',
    ListView_PriorityAriaLabel: 'Пріоритет завдання {taskTitle}',
    ListView_EditTaskAriaLabel: 'Редагувати завдання {taskTitle}',
    ListView_DeleteTaskAriaLabel: 'Видалити завдання {taskTitle}',
    ListView_EditTitle: 'Редагувати',
    ListView_DeleteTitle: 'Видалити',

    // ── Kanban view ──
    Kanban_ColumnNotStarted: 'Не розпочато',
    Kanban_ColumnInProgress: 'У процесі',
    Kanban_ColumnOnHold: 'Призупинено',
    Kanban_ColumnCompleted: 'Завершено',
    Kanban_ColumnCancelled: 'Скасовано',
    Kanban_AddTaskButton: '+ Додати завдання',
    Kanban_EditTitle: 'Редагувати',
    Kanban_DeleteTitle: 'Видалити',
    Kanban_CardAriaLabel: '{taskTitle}, {status}. Натисніть Enter для редагування, стрілку вліво або вправо для зміни статусу.',
    Kanban_EditTaskAriaLabel: 'Редагувати завдання {taskTitle}',
    Kanban_DeleteTaskAriaLabel: 'Видалити завдання {taskTitle}',

    // ── Dashboard view ──
    Dashboard_TotalTasks: 'Усього завдань',
    Dashboard_Completed: 'Завершено',
    Dashboard_InProgress: 'У процесі',
    Dashboard_OnHold: 'Призупинено',
    Dashboard_NotStarted: 'Не розпочато',
    Dashboard_Cancelled: 'Скасовано',
    Dashboard_OverallProgress: 'Загальний прогрес',
    Dashboard_ProjectManagerLabel: 'Керівник проєкту: {name}',
    Dashboard_PhaseProgressHeader: 'Прогрес за етапами',
    Dashboard_StatusBreakdownHeader: 'Розподіл за статусом',
    Dashboard_PriorityBreakdownHeader: 'Розподіл за пріоритетом',
    Dashboard_PriorityCritical: 'Критичний',
    Dashboard_PriorityHigh: 'Високий',
    Dashboard_PriorityMedium: 'Середній',
    Dashboard_PriorityLow: 'Низький',
    Dashboard_OverdueHeader: 'Прострочено  ({count})',
    Dashboard_DueNext14DaysHeader: 'Термін протягом 14 днів  ({count})',
    Dashboard_CompletedThisWeekHeader: 'Завершено цього тижня',
    Dashboard_UpdatedThisWeekHeader: 'Оновлено цього тижня',
    Dashboard_Today: 'Сьогодні',
    Dashboard_Tomorrow: 'Завтра',
    Dashboard_DaysLeft: '{days} дн.',
    Dashboard_EmptyTitle: 'Завдань ще немає',
    Dashboard_EmptySubtitle: 'Додайте завдання, щоб побачити панель проєкту.',
    Dashboard_AddTaskButton: '+ Додати завдання',

    // ── Portfolio view ──
    Portfolio_ProjectCount: '{count} проєкт{plural}',
    Portfolio_OnTrackSummary: '{count} за графіком',
    Portfolio_AtRiskSummary: '{count} під загрозою',
    Portfolio_OverdueSummary: '{count} прострочено',
    Portfolio_DoneSummary: '{count} завершено',
    Portfolio_SortLabel: 'Сортувати:',
    Portfolio_SortAZ: 'А-Я',
    Portfolio_SortHealth: 'Стан',
    Portfolio_SortStatus: 'Статус',
    Portfolio_SortCompletion: 'Завершеність',
    Portfolio_RefreshTitle: 'Оновити',
    Portfolio_RefreshButton: 'Оновити',
    Portfolio_LoadingStats: 'Завантаження статистики…',
    Portfolio_EmptyTitle: 'Проєктів ще немає',
    Portfolio_CreateFirstProject: '+ Створити перший проєкт',
    Portfolio_StatsUnavailable: 'Статистика недоступна',
    Portfolio_StatsUnavailableDetail: 'Не вдалося завантажити статистику для цього проєкту.',
    Portfolio_OverallProgressLabel: 'Загальний прогрес',
    Portfolio_TaskCountDone: 'Завершено',
    Portfolio_TaskCountActive: 'Активні',
    Portfolio_TaskCountAtRisk: 'Під загрозою',
    Portfolio_TaskCountOverdue: 'Прострочено',
    Portfolio_ViewGanttLink: 'Переглянути діаграму Ганта →',
    Portfolio_TodayTooltip: 'Сьогодні',

    // ── Task panel ──
    TaskPanel_EditHeader: 'Редагування: {taskTitle}',
    TaskPanel_NewTaskHeader: 'Нове завдання',
    TaskPanel_TabBasic: 'Основне',
    TaskPanel_TabDetails: 'Деталі',
    TaskPanel_TabLinks: 'Зв\'язки',
    TaskPanel_ProjectLabelPrefix: 'Проєкт: ',
    TaskPanel_TaskNameLabel: 'Назва завдання',
    TaskPanel_TaskNamePlaceholder: 'Введіть назву завдання',
    TaskPanel_TaskNameRequired: 'Назва завдання є обов\'язковою',
    TaskPanel_DescriptionLabel: 'Опис',
    TaskPanel_DescriptionPlaceholder: 'Введіть опис',
    TaskPanel_StartDateLabel: 'Дата початку',
    TaskPanel_DueDateLabel: 'Термін виконання',
    TaskPanel_DueDateError: 'Термін виконання має бути не раніше дати початку',
    TaskPanel_StatusLabel: 'Статус',
    TaskPanel_PriorityLabel: 'Пріоритет',
    TaskPanel_PercentCompleteLabel: '% виконання: {percent}%',
    TaskPanel_AssignedToLabel: 'Виконавець',
    TaskPanel_AssignedToPlaceholder: 'Пошук людей…',
    TaskPanel_PhaseLabel: 'Етап',
    TaskPanel_PhasePlaceholder: 'Введіть назву етапу',
    TaskPanel_PhaseHint: 'Групує завдання разом у поданнях діаграми Ганта та списку.',
    TaskPanel_MilestoneLabel: 'Віха',
    TaskPanel_MilestoneOnText: 'Так',
    TaskPanel_MilestoneOffText: 'Ні',
    TaskPanel_CustomBarColorLabel: 'Спеціальний колір смуги',
    TaskPanel_CustomBarColorOptionalSuffix: ' (необов\'язково)',
    TaskPanel_AutoColorHint: 'Автоматичний колір за параметрами статусу/пріоритету/етапу.',
    TaskPanel_NotesLabel: 'Примітки',
    TaskPanel_NotesPlaceholder: 'Введіть примітки',
    TaskPanel_ParentTaskLabel: 'Батьківське завдання',
    TaskPanel_ParentTaskNone: '(немає)',
    TaskPanel_ParentTaskHasChildrenHint: 'Це завдання має підзавдання і не може мати власного батьківського завдання.',
    TaskPanel_ParentTaskHint: 'Вкладіть це завдання в інше як підзавдання.',
    TaskPanel_DependsOnLabel: 'Залежить від',
    TaskPanel_RemoveDependencyTitle: 'Видалити залежність від "{taskTitle}"',
    TaskPanel_AddDependencyPlaceholder: 'Додати залежність…',
    TaskPanel_SelectATaskOption: 'Виберіть завдання…',
    TaskPanel_DependsOnHint: 'Завдання не може розпочатися, доки ці не будуть завершені.',
    TaskPanel_SavingLabel: 'Збереження…',
    TaskPanel_CreatingLabel: 'Створення…',
    TaskPanel_SaveChangesButton: 'Зберегти зміни',
    TaskPanel_CreateTaskButton: 'Створити завдання',
    TaskPanel_CancelButton: 'Скасувати',
    TaskPanel_DismissAriaLabel: 'Закрити',
    TaskPanel_DiscardUnsavedChangesConfirm: 'Відхилити незбережені зміни?',
    TaskPanel_SaveFallbackError: 'Не вдалося зберегти завдання.',

    // ── Project panel ──
    ProjectPanel_EditHeader: 'Редагувати проєкт',
    ProjectPanel_NewHeader: 'Новий проєкт',
    ProjectPanel_ProjectNameLabel: 'Назва проєкту',
    ProjectPanel_ProjectNamePlaceholder: 'Введіть назву проєкту',
    ProjectPanel_ProjectNameRequired: 'Назва проєкту є обов\'язковою',
    ProjectPanel_DescriptionLabel: 'Опис',
    ProjectPanel_DescriptionPlaceholder: 'Введіть опис',
    ProjectPanel_ProjectColorLabel: 'Колір проєкту',
    ProjectPanel_StatusLabel: 'Статус',
    ProjectPanel_StartDateLabel: 'Дата початку',
    ProjectPanel_DueDateLabel: 'Термін виконання',
    ProjectPanel_DueDateError: 'Термін виконання має бути не раніше дати початку',
    ProjectPanel_WhatHappensNextTitle: 'Що далі?',
    ProjectPanel_WhatHappensNextBody: 'Після створення проєкту ви зможете додавати завдання, налаштовувати етапи та відстежувати прогрес.',
    ProjectPanel_SavingLabel: 'Збереження…',
    ProjectPanel_CreatingLabel: 'Створення…',
    ProjectPanel_SaveChangesButton: 'Зберегти зміни',
    ProjectPanel_CreateProjectButton: 'Створити проєкт',
    ProjectPanel_CancelButton: 'Скасувати',
    ProjectPanel_DismissAriaLabel: 'Закрити',
    ProjectPanel_DiscardUnsavedChangesConfirm: 'Відхилити незбережені зміни?',
    ProjectPanel_SaveFallbackError: 'Не вдалося зберегти проєкт.',

    // ── Import panel ──
    ImportPanel_SourceExcelTitle: 'Файл Excel / CSV',
    ImportPanel_SourceExcelSubtitle: 'Імпортувати завдання з електронної таблиці',
    ImportPanel_SourcePlannerTitle: 'Microsoft Planner',
    ImportPanel_SourcePlannerSubtitle: 'Імпортувати завдання з плану Planner',
    ImportPanel_ClickToBrowse: 'Натисніть, щоб вибрати файл',
    ImportPanel_DragDropSuffix: ' або перетягніть файл сюди',
    ImportPanel_SupportedExtensions: 'Підтримуються .xlsx, .xls, .csv',
    ImportPanel_RowsColsSummary: 'Виявлено {rows} рядків, {cols} стовпців',
    ImportPanel_LoadingPlannerPlans: 'Завантаження планів Planner…',
    ImportPanel_PlannerLoadError: 'Не вдалося завантажити плани Planner.',
    ImportPanel_PlannerPermissionsHintPrefix: 'Переконайтеся, що у вас є доступ до Planner і що ',
    ImportPanel_PlannerPermissionsHintEmphasis: 'Завдання від Planner і To Do',
    ImportPanel_PlannerPermissionsHintSuffix: ' доступне для цього сайту.',
    ImportPanel_NoPlannerPlansFoundTitle: 'Плани Planner не знайдено',
    ImportPanel_NoPlannerPlansFoundBody: 'Можливо, у вас немає доступу до жодного плану Planner, або їх немає для цього облікового запису.',
    ImportPanel_TaskCountFoundIn: 'Знайдено {count} завдань у "{planName}"',
    ImportPanel_ProjectDetailsIntroPrefix: 'Імпорт до ',
    ImportPanel_ProjectDetailsIntroSuffix: '. Перегляньте деталі проєкту нижче.',
    ImportPanel_ProjectNameLabel: 'Назва проєкту',
    ImportPanel_DescriptionLabel: 'Опис',
    ImportPanel_StatusLabel: 'Статус',
    ImportPanel_ColorLabel: 'Колір',
    ImportPanel_MapIntro: 'Зіставте стовпці з вашого файлу з полями завдань.',
    ImportPanel_CreatingProjectStatus: 'Створення проєкту…',
    ImportPanel_ImportingTasksStatus: 'Імпортування завдань…',
    ImportPanel_ProgressLabel: '{done} з {total}',
    ImportPanel_CouldNotCreateProject: 'Не вдалося створити проєкт.',
    ImportPanel_ImportCompletedWithErrors: 'Імпорт завершено з {count} помилкою(ами).',
    ImportPanel_ProjectCreatedSuccess: 'Проєкт успішно створено!',
    ImportPanel_ImportSuccessful: 'Імпорт успішний!',
    ImportPanel_TasksAddedTo: '{count} завдань додано до "{projectName}"',
    ImportPanel_FailedRowsLabel: 'Неуспішні рядки:',
    ImportPanel_CloseButton: 'Закрити',
    ImportPanel_OpenProjectButton: 'Відкрити проєкт',
    ImportPanel_ViewImportedTasksButton: 'Переглянути імпортовані завдання',
    ImportPanel_NextMapColumnsButton: 'Далі: зіставлення стовпців',
    ImportPanel_ImportNTasksButton: 'Імпортувати {count} завдань',
    ImportPanel_BackButton: 'Назад',
    ImportPanel_CancelButton: 'Скасувати',
    ImportPanel_NextButton: 'Далі',
    ImportPanel_StepSource: 'Джерело',
    ImportPanel_StepProject: 'Проєкт',
    ImportPanel_StepMap: 'Зіставлення',
    ImportPanel_StepImport: 'Імпорт',
    ImportPanel_StepDone: 'Готово',
    ImportPanel_ImportAsNewProjectHeader: 'Імпортувати файл як новий проєкт',
    ImportPanel_ImportIntoProjectHeader: 'Імпортувати завдання до {projectName}',
    ImportPanel_CouldNotParseFile: 'Не вдалося обробити файл.',
    ImportPanel_CouldNotLoadPlannerTasks: 'Не вдалося завантажити завдання з цього плану.',
    ImportPanel_CouldNotCreateProjectDetail: 'Не вдалося створити проєкт: {detail}',
    ImportPanel_CouldNotLinkDependencies: 'Не вдалося зв\'язати залежності: {detail}',
    ImportPanel_UnknownError: 'невідома помилка',

    // ── Column mapper (import) ──
    ColumnMapper_TaskNameRequiredBanner: 'Для продовження потрібно зіставити назву завдання.',
    ColumnMapper_SkippedColumnsBanner: '{count} стовпців буде пропущено.',
    ColumnMapper_SourceColumnHeader: 'Вихідний стовпець',
    ColumnMapper_TargetFieldHeader: 'Цільове поле',
    ColumnMapper_StatusHeader: 'Статус',
    ColumnMapper_SkippedBadge: 'Пропущено',
    ColumnMapper_AutoMappedBadge: 'Зіставлено автоматично',
    ColumnMapper_SetBadge: 'Установлено',
    ColumnMapper_PreviewTitle: 'Попередній перегляд: {columnName}',
    ColumnMapper_EmptyCellDash: '—',

    // ── Import field display names / ImportService ──
    ImportField_TaskName: 'Назва завдання',
    ImportField_StartDate: 'Дата початку',
    ImportField_DueDate: 'Термін виконання',
    ImportField_Status: 'Статус',
    ImportField_Priority: 'Пріоритет',
    ImportField_AssignedTo: 'Виконавець',
    ImportField_AssignedToEmail: 'Електронна пошта виконавця',
    ImportField_PercentComplete: '% виконання',
    ImportField_Phase: 'Етап',
    ImportField_Description: 'Опис',
    ImportField_Notes: 'Примітки',
    ImportField_IsMilestone: 'Чи є віхою',
    ImportField_Dependencies: 'Залежності',
    ImportField_SkipColumn: '(Пропустити цей стовпець)',
    ImportService_EmptyFileError: 'Файл виглядає порожнім або не містить рядків даних.',
    ImportService_ReadErrorDetail: 'Не вдалося прочитати файл: {detail}.',
    ImportService_FileReadError: 'Помилка читання файлу.',
    ImportService_RowError: 'Рядок {rowNum} ("{title}"): {error}',
    ImportService_AmbiguousDependency: 'Залежність "{name}" відповідає декільком назвам завдань — пропущено.',
    ImportService_LinkDependencyError: 'Не вдалося зв\'язати залежності для завдання {taskId}: {error}',

    // ── Health labels (shared: healthUtils.ts and ExportService.ts both use this set; also replaces the duplicated Export_PortfolioHealthLabel* keys) ──
    Health_Done: 'Завершено',
    Health_OnTrack: 'За графіком',
    Health_AtRisk: 'Під загрозою',
    Health_Overdue: 'Прострочено',

    // ── Status / Priority display labels (DISPLAY-ONLY — stored SharePoint Choice values remain unchanged/English) ──
    Status_NotStarted: 'Не розпочато',
    Status_InProgress: 'У процесі',
    Status_Completed: 'Завершено',
    Status_OnHold: 'Призупинено',
    Status_Cancelled: 'Скасовано',
    Priority_Critical: 'Критичний',
    Priority_High: 'Високий',
    Priority_Medium: 'Середній',
    Priority_Low: 'Низький',
    ProjectStatus_Planning: 'Планування',
    ProjectStatus_Active: 'Активний',
    ProjectStatus_OnHold: 'Призупинено',
    ProjectStatus_Completed: 'Завершено',
    ProjectStatus_Cancelled: 'Скасовано',

    // ── Shell (SmartGantt.tsx) ──
    SmartGantt_LoadingProjects: 'Завантаження проєктів…',
    SmartGantt_UnableToLoad: 'Не вдалося завантажити',
    SmartGantt_RetryButton: 'Повторити',
    SmartGantt_NoProjectsYet: 'Проєктів ще немає',
    SmartGantt_NoProjectsSubtitle: 'Створіть свій перший проєкт, щоб почати.',
    SmartGantt_CreateFirstProjectButton: '+ Створити перший проєкт',
    SmartGantt_ImportFromExcelButton: '📥 Імпортувати з Excel',
    SmartGantt_LoadingTasks: 'Завантаження завдань…',
    SmartGantt_DismissAriaLabel: 'Закрити',
    SmartGantt_DeleteTaskDialogTitle: 'Видалити завдання',
    SmartGantt_DeleteTaskDialogSubtext: 'Ви впевнені, що хочете видалити "{taskTitle}"? Цю дію неможливо скасувати.',
    SmartGantt_DeleteButton: 'Видалити',
    SmartGantt_CancelButton: 'Скасувати',
    SmartGantt_ArchiveProjectDialogTitle: 'Архівувати проєкт',
    SmartGantt_ArchiveProjectDialogSubtext: 'Архівувати "{projectTitle}"? Ви зможете розархівувати його пізніше.',
    SmartGantt_ArchiveButton: 'Архівувати',
    SmartGantt_SendToRecycleBinDialogTitle: 'Перемістити в кошик',
    SmartGantt_SendToRecycleBinDialogSubtext: 'Перемістити "{projectTitle}" до кошика сайту?',
    SmartGantt_SendToRecycleBinButton: 'Перемістити в кошик',
    SmartGantt_FailedLoadProjects: 'Не вдалося завантажити проєкти. Перевірте дозволи сайту.',
    SmartGantt_FailedLoadTasks: 'Не вдалося завантажити завдання для цього проєкту.',
    SmartGantt_FailedLoadPortfolioStats: 'Не вдалося завантажити статистику портфеля.',
    SmartGantt_CouldNotSaveProject: 'Не вдалося зберегти проєкт: {message}',
    SmartGantt_CouldNotDeleteProject: 'Не вдалося видалити проєкт: {message}',
    SmartGantt_CouldNotArchiveProject: 'Не вдалося архівувати проєкт: {message}',
    SmartGantt_CouldNotUnarchiveProject: 'Не вдалося розархівувати проєкт: {message}',
    SmartGantt_CouldNotSaveTask: 'Не вдалося зберегти завдання: {message}',
    SmartGantt_CouldNotDeleteTask: 'Не вдалося видалити завдання: {message}',
    SmartGantt_ImageExportFailed: 'Помилка експорту зображення: {message}',
    SmartGantt_PowerPointExportFailed: 'Помилка експорту в PowerPoint: {message}',
    SmartGantt_PortfolioExportFailed: 'Помилка експорту портфеля: {message}',
    SmartGantt_CouldNotUpdateTask: 'Не вдалося оновити завдання: {message}',

    // ── Common ──
    ColorSwatch_AutoColorAriaLabel: 'Автоматичний колір',
    ColorSwatch_CustomColorAriaLabel: 'Спеціальний колір',
    ColorSwatch_PickCustomColorTitle: 'Виберіть спеціальний колір',

    // ── Export (Excel / PowerPoint) ──
    Export_ColTaskName: 'Назва завдання',
    Export_ColPhase: 'Етап',
    Export_ColStartDate: 'Дата початку',
    Export_ColDueDate: 'Термін виконання',
    Export_ColStatus: 'Статус',
    Export_ColPriority: 'Пріоритет',
    Export_ColAssignedTo: 'Виконавець',
    Export_ColAssignedToEmail: 'Електронна пошта виконавця',
    Export_ColPercentComplete: '% виконання',
    Export_ColIsMilestone: 'Чи є віхою',
    Export_ColDescription: 'Опис',
    Export_ColNotes: 'Примітки',
    Export_Yes: 'Так',
    Export_No: 'Ні',
    Export_SheetNameTasks: 'Завдання',
    Export_ExcelFileSuffix: ' - Завдання.xlsx',
    Export_TaskNameColumnLabel: 'НАЗВА ЗАВДАННЯ',
    Export_ExportedDateLabel: 'Експортовано {date}',
    Export_ProjectReportLabel: 'ЗВІТ ПРОЄКТУ',
    Export_StatusLine: 'Статус: {status}',
    Export_DateRangeSeparator: ' до ',
    Export_ProjectManagerLine: 'Керівник проєкту: {name}',
    Export_GeneratedDateLine: 'Сформовано {date}',
    Export_ProjectSummaryTitle: 'Резюме проєкту',
    Export_StatTotalTasks: 'Усього завдань',
    Export_StatCompleted: 'Завершено',
    Export_StatInProgress: 'У процесі',
    Export_StatOnHold: 'Призупинено',
    Export_StatNotStarted: 'Не розпочато',
    Export_OverallProgressLine: 'Загальний прогрес',
    Export_OverallProgressPercent: '{percent}%',
    Export_StatusBreakdownTitle: 'Розподіл за статусом',
    Export_StatusBreakdownRow: '{status}: {count} ({percent}%)',
    Export_GanttTimelineTitle: 'Часова шкала діаграми Ганта',
    Export_SummaryRecentActivityTitle: 'Остання активність',
    Export_ProjectOverviewLabel: 'Огляд проєкту',
    Export_DetailStatusLabel: 'Статус',
    Export_DetailStartDateLabel: 'Дата початку',
    Export_DetailDueDateLabel: 'Термін виконання',
    Export_DetailProjectManagerLabel: 'Керівник проєкту',
    Export_Past7DaysLabel: 'Останні 7 днів',
    Export_NoActivityMessage: 'Немає останньої активності.',
    Export_CompletedThisWeekHeader: 'Завершено цього тижня ({count})',
    Export_NewBadge: 'НОВЕ  ',
    Export_CompletedPercentLine: 'Виконано {percent}%',
    Export_MoreItemsSuffix: '+ ще {count}',
    Export_InProgressUpdatedHeader: 'У процесі / оновлено',
    Export_StatusPercentLine: '{status} — {percent}%',
    Export_PortfolioReportLabel: 'ЗВІТ ПОРТФЕЛЯ',
    Export_PortfolioOverviewTitle: 'Огляд портфеля',
    Export_ProjectsCountLine: '{count} проєктів',
    Export_HealthSummaryOnTrack: '{count} за графіком',
    Export_HealthSummaryAtRisk: '{count} під загрозою',
    Export_HealthSummaryOverdue: '{count} прострочено',
    Export_ProjectsSummaryHeader: 'Резюме проєктів',
    Export_TableProject: 'Проєкт',
    Export_TableStatus: 'Статус',
    Export_TableHealth: 'Стан',
    Export_TableTotal: 'Усього',
    Export_TableDone: 'Завершено',
    Export_TableActive: 'Активні',
    Export_TableAtRisk: 'Під загрозою',
    Export_TableOverdue: 'Прострочено',
    Export_TablePctDone: '% завершено',
    Export_TableDueDate: 'Термін виконання',
    Export_PortfolioSummaryFileName: 'Резюме портфеля.xlsx',
    Export_PortfolioReportFileName: 'Звіт портфеля.pptx',
    Export_ProjectReportFileName: 'Звіт {projectName}.pptx',
    Export_UnavailableLabel: 'Недоступно',
    Export_SheetNamePortfolio: 'Портфель',
    Export_ColStart: 'Початок',
    Export_ColDue: 'Термін',
    Export_ImageGenerationFailed: 'Не вдалося створити зображення — діаграма може бути завеликою для експортування як зображення.',
    Export_DrawingContextFailed: 'Не вдалося створити контекст малювання для експортування.',
    Export_SvgRenderFailed: 'Не вдалося виконати рендеринг SVG',
  };
});
