define([], function () {
  return {
    // ── Property pane ──
    PropertyPane_HeaderDescription: 'Cài đặt Smart Gantt Chart',
    PropertyPane_GeneralGroupName: 'Chung',
    PropertyPane_TitleFieldLabel: 'Tiêu đề Web Part',
    WebPart_DefaultTitle: 'Smart Gantt Chart',

    // ── Toolbar ──
    Toolbar_ViewDashboard: 'Bảng điều khiển',
    Toolbar_ViewList: 'Danh sách',
    Toolbar_ViewGantt: 'Gantt',
    Toolbar_ViewKanban: 'Kanban',
    Toolbar_ZoomDay: 'Ngày',
    Toolbar_ZoomWeek: 'Tuần',
    Toolbar_ZoomMonth: 'Tháng',
    Toolbar_ZoomQuarter: 'Quý',
    Toolbar_SelectProjectAriaLabel: 'Chọn dự án',
    Toolbar_PortfolioLabel: 'Danh mục',
    Toolbar_SelectAProject: 'Chọn một dự án',
    Toolbar_AllProjectsSubtext: 'Tất cả dự án',
    Toolbar_NoProjectsYet: 'Chưa có dự án nào',
    Toolbar_ArchivedBadge: 'Đã lưu trữ',
    Toolbar_ShowArchivedProjects: 'Hiển thị dự án đã lưu trữ',
    Toolbar_NewProject: '+ Dự án mới',
    Toolbar_ImportFileAsNewProject: '📥 Nhập tệp làm dự án mới…',
    Toolbar_AddTask: '+ Thêm công việc',
    Toolbar_EditProject: 'Chỉnh sửa dự án',
    Toolbar_OptionsButton: '⚙ Tùy chọn',
    Toolbar_MoreOptionsTitle: 'Thêm tùy chọn',
    Toolbar_ExportToExcel: '📊 Xuất ra Excel',
    Toolbar_ExportToPowerPoint: '📑 Xuất ra PowerPoint',
    Toolbar_ScrollToTodayTitle: 'Cuộn đến hôm nay',
    Toolbar_TodayButton: '◉ Hôm nay',
    Toolbar_ImportTasks: '📥 Nhập công việc…',
    Toolbar_ExportAsImage: '🖼 Xuất dưới dạng hình ảnh (PNG)',
    Toolbar_UnarchiveProject: '📂 Bỏ lưu trữ dự án',
    Toolbar_ArchiveProject: '🗄️ Lưu trữ dự án',
    Toolbar_SendToRecycleBin: '🗑️ Chuyển vào thùng rác',

    // ── Filter bar ──
    FilterBar_ClearOption: 'Xóa',
    FilterBar_DueAny: 'Bất kỳ hạn nào',
    FilterBar_DueOverdue: 'Quá hạn',
    FilterBar_DueToday: 'Đến hạn hôm nay',
    FilterBar_DueWeek: 'Đến hạn trong 7 ngày',
    FilterBar_SearchPlaceholder: 'Tìm kiếm công việc…',
    FilterBar_SearchAriaLabel: 'Tìm kiếm công việc',
    FilterBar_StatusChipLabel: 'Trạng thái',
    FilterBar_PriorityChipLabel: 'Mức ưu tiên',
    FilterBar_AssigneeChipLabel: 'Người được giao',
    FilterBar_PhaseChipLabel: 'Giai đoạn',
    FilterBar_DueDateAriaLabel: 'Lọc theo hạn hoàn thành',
    FilterBar_MatchCount: '{matchCount} trong tổng số {totalCount}',
    FilterBar_ClearFilters: '✕ Xóa bộ lọc',
    FilterBar_ChipLabelWithCount: '{label} ({count}) ▾',
    FilterBar_ChipLabelNoCount: '{label} ▾',

    // ── Gantt view ──
    Gantt_TaskColumnHeader: 'Công việc',
    Gantt_DurationColumnHeader: 'Thời lượng',
    Gantt_AddTaskButton: '+ Thêm công việc',
    Gantt_EmptyTitle: 'Chưa có công việc nào',
    Gantt_EmptySubtitle: 'Thêm công việc để xem trên biểu đồ Gantt.',
    Gantt_AddFirstTask: '+ Thêm công việc đầu tiên',
    Gantt_ImportTasksButton: '📥 Nhập công việc',
    Gantt_EditTitle: 'Chỉnh sửa',
    Gantt_DeleteTitle: 'Xóa',
    Gantt_EditTaskAriaLabel: 'Chỉnh sửa công việc {taskTitle}',
    Gantt_DeleteTaskAriaLabel: 'Xóa công việc {taskTitle}',
    Gantt_ExpandPhaseAriaLabel: '{action} giai đoạn {phase}',
    Gantt_ExpandAction: 'Mở rộng',
    Gantt_CollapseAction: 'Thu gọn',
    Gantt_DependencyViolationTooltip: 'Đã bắt đầu trước khi tất cả các phụ thuộc hoàn thành',
    Gantt_MilestoneAriaLabel: '{taskTitle}, cột mốc, {date}',
    Gantt_BarAriaLabel: '{taskTitle}, từ {startDate} đến {dueDate}, hoàn thành {percent}%',
    Gantt_PercentCompleteTooltip: 'Hoàn thành {value}%',

    // ── Gantt options/settings panel ──
    GanttSettings_PanelHeader: '⚙ Tùy chọn',
    GanttSettings_ColorCodingSection: 'Mã màu',
    GanttSettings_ByStatus: 'Theo trạng thái',
    GanttSettings_ByPriority: 'Theo mức ưu tiên',
    GanttSettings_ByPhase: 'Theo giai đoạn',
    GanttSettings_ByHealth: 'Theo tình trạng',
    GanttSettings_HeaderColorSection: 'Màu tiêu đề',
    GanttSettings_ThemeDark: 'Tối',
    GanttSettings_ThemeNavy: 'Xanh navy',
    GanttSettings_ThemeTeal: 'Xanh mòng két',
    GanttSettings_ThemePurple: 'Tím',
    GanttSettings_ThemeLight: 'Sáng',
    GanttSettings_HeaderLabelsSection: 'Nhãn tiêu đề',
    GanttSettings_WeekLabelDates: 'Ngày tháng',
    GanttSettings_WeekLabelDatesDesc: '3 Th6, 10 Th6…',
    GanttSettings_WeekLabelProject: 'Tuần dự án',
    GanttSettings_WeekLabelProjectDesc: 'T1, T2…',
    GanttSettings_WeekLabelIso: 'Tuần lịch',
    GanttSettings_WeekLabelIsoDesc: 'T23, T24…',
    GanttSettings_ProjectWeeksHint: 'Tuần 1 bắt đầu từ thứ Hai của công việc sớm nhất của bạn — rất phù hợp cho các buổi thuyết trình.',
    GanttSettings_BarStyleSection: 'Kiểu thanh',
    GanttSettings_BarStyleGradient: 'Chuyển sắc',
    GanttSettings_BarStyleFlat: 'Phẳng',
    GanttSettings_RowHeightSection: 'Chiều cao hàng',
    GanttSettings_HeightCompact: 'Gọn',
    GanttSettings_HeightNormal: 'Bình thường',
    GanttSettings_HeightSpacious: 'Rộng rãi',
    GanttSettings_ShowHideSection: 'Hiển thị / Ẩn',
    GanttSettings_WeekendShading: 'Tô màu cuối tuần',
    GanttSettings_DependencyArrows: 'Mũi tên phụ thuộc',
    GanttSettings_CriticalPathAlwaysVisible: 'Luôn hiển thị đường găng',
    GanttSettings_AllOthersOnHoverOnly: 'Các mục khác chỉ hiển thị khi di chuột qua',
    GanttSettings_CriticalPathHighlight: 'Tô sáng đường găng',
    GanttSettings_ProgressPercentOnBars: 'Phần trăm tiến độ trên thanh',
    GanttSettings_AssigneeNameOnBars: 'Tên người được giao trên thanh',
    GanttSettings_HealthStatusBadges: 'Huy hiệu tình trạng',

    // ── List view ──
    ListView_ColTaskName: 'Tên công việc',
    ListView_ColStatus: 'Trạng thái',
    ListView_ColHealth: 'Tình trạng',
    ListView_ColPriority: 'Mức ưu tiên',
    ListView_ColStart: 'Bắt đầu',
    ListView_ColDue: 'Hạn',
    ListView_ColAssignedTo: 'Người được giao',
    ListView_ColProgress: 'Tiến độ',
    ListView_ColPhase: 'Giai đoạn',
    ListView_ColPredecessors: 'Công việc trước',
    ListView_EmptyTitle: 'Chưa có công việc nào',
    ListView_AddFirstTask: '+ Thêm công việc đầu tiên',
    ListView_AddTaskRow: '+ Thêm công việc',
    ListView_Unassigned: 'Chưa phân công',
    ListView_DependencyViolationTooltip: 'Đã bắt đầu trước khi tất cả các phụ thuộc hoàn thành',
    ListView_StatusAriaLabel: 'Trạng thái của {taskTitle}',
    ListView_PriorityAriaLabel: 'Mức ưu tiên của {taskTitle}',
    ListView_EditTaskAriaLabel: 'Chỉnh sửa công việc {taskTitle}',
    ListView_DeleteTaskAriaLabel: 'Xóa công việc {taskTitle}',
    ListView_EditTitle: 'Chỉnh sửa',
    ListView_DeleteTitle: 'Xóa',

    // ── Kanban view ──
    Kanban_ColumnNotStarted: 'Chưa bắt đầu',
    Kanban_ColumnInProgress: 'Đang thực hiện',
    Kanban_ColumnOnHold: 'Tạm hoãn',
    Kanban_ColumnCompleted: 'Đã hoàn thành',
    Kanban_ColumnCancelled: 'Đã hủy',
    Kanban_AddTaskButton: '+ Thêm công việc',
    Kanban_EditTitle: 'Chỉnh sửa',
    Kanban_DeleteTitle: 'Xóa',
    Kanban_CardAriaLabel: '{taskTitle}, {status}. Nhấn Enter để chỉnh sửa, mũi tên Trái hoặc Phải để thay đổi trạng thái.',
    Kanban_EditTaskAriaLabel: 'Chỉnh sửa công việc {taskTitle}',
    Kanban_DeleteTaskAriaLabel: 'Xóa công việc {taskTitle}',

    // ── Dashboard view ──
    Dashboard_TotalTasks: 'Tổng số công việc',
    Dashboard_Completed: 'Đã hoàn thành',
    Dashboard_InProgress: 'Đang thực hiện',
    Dashboard_OnHold: 'Tạm hoãn',
    Dashboard_NotStarted: 'Chưa bắt đầu',
    Dashboard_Cancelled: 'Đã hủy',
    Dashboard_OverallProgress: 'Tiến độ tổng thể',
    Dashboard_ProjectManagerLabel: 'Quản lý dự án: {name}',
    Dashboard_PhaseProgressHeader: 'Tiến độ theo giai đoạn',
    Dashboard_StatusBreakdownHeader: 'Phân tích theo trạng thái',
    Dashboard_PriorityBreakdownHeader: 'Phân tích theo mức ưu tiên',
    Dashboard_PriorityCritical: 'Khẩn cấp',
    Dashboard_PriorityHigh: 'Cao',
    Dashboard_PriorityMedium: 'Trung bình',
    Dashboard_PriorityLow: 'Thấp',
    Dashboard_OverdueHeader: 'Quá hạn  ({count})',
    Dashboard_DueNext14DaysHeader: 'Đến hạn trong 14 ngày tới  ({count})',
    Dashboard_CompletedThisWeekHeader: 'Hoàn thành trong tuần này',
    Dashboard_UpdatedThisWeekHeader: 'Cập nhật trong tuần này',
    Dashboard_Today: 'Hôm nay',
    Dashboard_Tomorrow: 'Ngày mai',
    Dashboard_DaysLeft: 'còn {days} ngày',
    Dashboard_EmptyTitle: 'Chưa có công việc nào',
    Dashboard_EmptySubtitle: 'Thêm công việc để xem bảng điều khiển dự án của bạn.',
    Dashboard_AddTaskButton: '+ Thêm công việc',

    // ── Portfolio view ──
    Portfolio_ProjectCount: '{count} dự án{plural}',
    Portfolio_OnTrackSummary: '{count} đúng tiến độ',
    Portfolio_AtRiskSummary: '{count} có rủi ro',
    Portfolio_OverdueSummary: '{count} quá hạn',
    Portfolio_DoneSummary: '{count} hoàn thành',
    Portfolio_SortLabel: 'Sắp xếp:',
    Portfolio_SortAZ: 'A-Z',
    Portfolio_SortHealth: 'Tình trạng',
    Portfolio_SortStatus: 'Trạng thái',
    Portfolio_SortCompletion: 'Mức hoàn thành',
    Portfolio_RefreshTitle: 'Làm mới',
    Portfolio_RefreshButton: 'Làm mới',
    Portfolio_LoadingStats: 'Đang tải số liệu thống kê…',
    Portfolio_EmptyTitle: 'Chưa có dự án nào',
    Portfolio_CreateFirstProject: '+ Tạo dự án đầu tiên',
    Portfolio_StatsUnavailable: 'Không có số liệu thống kê',
    Portfolio_StatsUnavailableDetail: 'Không thể tải số liệu thống kê cho dự án này.',
    Portfolio_OverallProgressLabel: 'Tiến độ tổng thể',
    Portfolio_TaskCountDone: 'Hoàn thành',
    Portfolio_TaskCountActive: 'Đang hoạt động',
    Portfolio_TaskCountAtRisk: 'Có rủi ro',
    Portfolio_TaskCountOverdue: 'Quá hạn',
    Portfolio_ViewGanttLink: 'Xem biểu đồ Gantt →',
    Portfolio_TodayTooltip: 'Hôm nay',

    // ── Task panel ──
    TaskPanel_EditHeader: 'Chỉnh sửa: {taskTitle}',
    TaskPanel_NewTaskHeader: 'Công việc mới',
    TaskPanel_TabBasic: 'Cơ bản',
    TaskPanel_TabDetails: 'Chi tiết',
    TaskPanel_TabLinks: 'Liên kết',
    TaskPanel_ProjectLabelPrefix: 'Dự án: ',
    TaskPanel_TaskNameLabel: 'Tên công việc',
    TaskPanel_TaskNamePlaceholder: 'Nhập tên công việc',
    TaskPanel_TaskNameRequired: 'Tên công việc là bắt buộc',
    TaskPanel_DescriptionLabel: 'Mô tả',
    TaskPanel_DescriptionPlaceholder: 'Nhập mô tả',
    TaskPanel_StartDateLabel: 'Ngày bắt đầu',
    TaskPanel_DueDateLabel: 'Ngày đến hạn',
    TaskPanel_DueDateError: 'Ngày đến hạn phải cùng ngày hoặc sau ngày bắt đầu',
    TaskPanel_StatusLabel: 'Trạng thái',
    TaskPanel_PriorityLabel: 'Mức ưu tiên',
    TaskPanel_PercentCompleteLabel: '% Hoàn thành: {percent}%',
    TaskPanel_AssignedToLabel: 'Người được giao',
    TaskPanel_AssignedToPlaceholder: 'Tìm kiếm người…',
    TaskPanel_PhaseLabel: 'Giai đoạn',
    TaskPanel_PhasePlaceholder: 'Nhập tên giai đoạn',
    TaskPanel_PhaseHint: 'Nhóm các công việc lại với nhau trong chế độ xem Gantt và Danh sách.',
    TaskPanel_MilestoneLabel: 'Cột mốc',
    TaskPanel_MilestoneOnText: 'Có',
    TaskPanel_MilestoneOffText: 'Không',
    TaskPanel_CustomBarColorLabel: 'Màu thanh tùy chỉnh',
    TaskPanel_CustomBarColorOptionalSuffix: ' (không bắt buộc)',
    TaskPanel_AutoColorHint: 'Màu tự động theo cài đặt trạng thái/mức ưu tiên/giai đoạn.',
    TaskPanel_NotesLabel: 'Ghi chú',
    TaskPanel_NotesPlaceholder: 'Nhập ghi chú',
    TaskPanel_ParentTaskLabel: 'Công việc cha',
    TaskPanel_ParentTaskNone: '(không có)',
    TaskPanel_ParentTaskHasChildrenHint: 'Công việc này có công việc con và không thể có công việc cha riêng.',
    TaskPanel_ParentTaskHint: 'Lồng công việc này vào một công việc khác như một công việc con.',
    TaskPanel_DependsOnLabel: 'Phụ thuộc vào',
    TaskPanel_RemoveDependencyTitle: 'Xóa phụ thuộc vào "{taskTitle}"',
    TaskPanel_AddDependencyPlaceholder: 'Thêm một phụ thuộc…',
    TaskPanel_SelectATaskOption: 'Chọn một công việc…',
    TaskPanel_DependsOnHint: 'Công việc không thể bắt đầu cho đến khi các công việc này hoàn thành.',
    TaskPanel_SavingLabel: 'Đang lưu…',
    TaskPanel_CreatingLabel: 'Đang tạo…',
    TaskPanel_SaveChangesButton: 'Lưu thay đổi',
    TaskPanel_CreateTaskButton: 'Tạo công việc',
    TaskPanel_CancelButton: 'Hủy',
    TaskPanel_DismissAriaLabel: 'Đóng',
    TaskPanel_DiscardUnsavedChangesConfirm: 'Hủy bỏ các thay đổi chưa lưu?',
    TaskPanel_SaveFallbackError: 'Không thể lưu công việc.',

    // ── Project panel ──
    ProjectPanel_EditHeader: 'Chỉnh sửa dự án',
    ProjectPanel_NewHeader: 'Dự án mới',
    ProjectPanel_ProjectNameLabel: 'Tên dự án',
    ProjectPanel_ProjectNamePlaceholder: 'Nhập tên dự án',
    ProjectPanel_ProjectNameRequired: 'Tên dự án là bắt buộc',
    ProjectPanel_DescriptionLabel: 'Mô tả',
    ProjectPanel_DescriptionPlaceholder: 'Nhập mô tả',
    ProjectPanel_ProjectColorLabel: 'Màu dự án',
    ProjectPanel_StatusLabel: 'Trạng thái',
    ProjectPanel_StartDateLabel: 'Ngày bắt đầu',
    ProjectPanel_DueDateLabel: 'Ngày đến hạn',
    ProjectPanel_DueDateError: 'Ngày đến hạn phải cùng ngày hoặc sau ngày bắt đầu',
    ProjectPanel_WhatHappensNextTitle: 'Điều gì xảy ra tiếp theo?',
    ProjectPanel_WhatHappensNextBody: 'Bạn sẽ có thể thêm công việc, thiết lập các giai đoạn và theo dõi tiến độ sau khi dự án được tạo.',
    ProjectPanel_SavingLabel: 'Đang lưu…',
    ProjectPanel_CreatingLabel: 'Đang tạo…',
    ProjectPanel_SaveChangesButton: 'Lưu thay đổi',
    ProjectPanel_CreateProjectButton: 'Tạo dự án',
    ProjectPanel_CancelButton: 'Hủy',
    ProjectPanel_DismissAriaLabel: 'Đóng',
    ProjectPanel_DiscardUnsavedChangesConfirm: 'Hủy bỏ các thay đổi chưa lưu?',
    ProjectPanel_SaveFallbackError: 'Không thể lưu dự án.',

    // ── Import panel ──
    ImportPanel_SourceExcelTitle: 'Tệp Excel / CSV',
    ImportPanel_SourceExcelSubtitle: 'Nhập công việc từ một bảng tính',
    ImportPanel_SourcePlannerTitle: 'Microsoft Planner',
    ImportPanel_SourcePlannerSubtitle: 'Nhập công việc từ một kế hoạch Planner',
    ImportPanel_ClickToBrowse: 'Nhấp để duyệt',
    ImportPanel_DragDropSuffix: ' hoặc kéo và thả',
    ImportPanel_SupportedExtensions: 'Hỗ trợ .xlsx, .xls, .csv',
    ImportPanel_RowsColsSummary: 'Đã phát hiện {rows} hàng, {cols} cột',
    ImportPanel_LoadingPlannerPlans: 'Đang tải các kế hoạch Planner…',
    ImportPanel_PlannerLoadError: 'Không thể tải các kế hoạch Planner.',
    ImportPanel_PlannerPermissionsHintPrefix: 'Đảm bảo rằng bạn có quyền truy cập vào Planner và ',
    ImportPanel_PlannerPermissionsHintEmphasis: 'Tasks by Planner and To Do',
    ImportPanel_PlannerPermissionsHintSuffix: ' khả dụng cho trang này.',
    ImportPanel_NoPlannerPlansFoundTitle: 'Không tìm thấy kế hoạch Planner nào',
    ImportPanel_NoPlannerPlansFoundBody: 'Bạn có thể không có quyền truy cập vào bất kỳ kế hoạch Planner nào, hoặc không có kế hoạch nào tồn tại cho tài khoản này.',
    ImportPanel_TaskCountFoundIn: 'Tìm thấy {count} công việc trong "{planName}"',
    ImportPanel_ProjectDetailsIntroPrefix: 'Đang nhập vào ',
    ImportPanel_ProjectDetailsIntroSuffix: '. Xem lại chi tiết dự án bên dưới.',
    ImportPanel_ProjectNameLabel: 'Tên dự án',
    ImportPanel_DescriptionLabel: 'Mô tả',
    ImportPanel_StatusLabel: 'Trạng thái',
    ImportPanel_ColorLabel: 'Màu',
    ImportPanel_MapIntro: 'Ánh xạ các cột từ tệp của bạn tới các trường công việc.',
    ImportPanel_CreatingProjectStatus: 'Đang tạo dự án…',
    ImportPanel_ImportingTasksStatus: 'Đang nhập công việc…',
    ImportPanel_ProgressLabel: '{done} trên {total}',
    ImportPanel_CouldNotCreateProject: 'Không thể tạo dự án.',
    ImportPanel_ImportCompletedWithErrors: 'Nhập hoàn tất với {count} lỗi.',
    ImportPanel_ProjectCreatedSuccess: 'Tạo dự án thành công!',
    ImportPanel_ImportSuccessful: 'Nhập thành công!',
    ImportPanel_TasksAddedTo: 'Đã thêm {count} công việc vào "{projectName}"',
    ImportPanel_FailedRowsLabel: 'Các hàng thất bại:',
    ImportPanel_CloseButton: 'Đóng',
    ImportPanel_OpenProjectButton: 'Mở dự án',
    ImportPanel_ViewImportedTasksButton: 'Xem công việc đã nhập',
    ImportPanel_NextMapColumnsButton: 'Tiếp theo: Ánh xạ cột',
    ImportPanel_ImportNTasksButton: 'Nhập {count} công việc',
    ImportPanel_BackButton: 'Quay lại',
    ImportPanel_CancelButton: 'Hủy',
    ImportPanel_NextButton: 'Tiếp theo',
    ImportPanel_StepSource: 'Nguồn',
    ImportPanel_StepProject: 'Dự án',
    ImportPanel_StepMap: 'Ánh xạ',
    ImportPanel_StepImport: 'Nhập',
    ImportPanel_StepDone: 'Hoàn tất',
    ImportPanel_ImportAsNewProjectHeader: 'Nhập tệp làm dự án mới',
    ImportPanel_ImportIntoProjectHeader: 'Nhập công việc vào {projectName}',
    ImportPanel_CouldNotParseFile: 'Không thể phân tích tệp.',
    ImportPanel_CouldNotLoadPlannerTasks: 'Không thể tải công việc từ kế hoạch này.',
    ImportPanel_CouldNotCreateProjectDetail: 'Không thể tạo dự án: {detail}',
    ImportPanel_CouldNotLinkDependencies: 'Không thể liên kết các phụ thuộc: {detail}',
    ImportPanel_UnknownError: 'lỗi không xác định',

    // ── Column mapper (import) ──
    ColumnMapper_TaskNameRequiredBanner: 'Tên công việc phải được ánh xạ để tiếp tục.',
    ColumnMapper_SkippedColumnsBanner: '{count} cột sẽ bị bỏ qua.',
    ColumnMapper_SourceColumnHeader: 'Cột nguồn',
    ColumnMapper_TargetFieldHeader: 'Trường đích',
    ColumnMapper_StatusHeader: 'Trạng thái',
    ColumnMapper_SkippedBadge: 'Đã bỏ qua',
    ColumnMapper_AutoMappedBadge: 'Đã tự động ánh xạ',
    ColumnMapper_SetBadge: 'Đã đặt',
    ColumnMapper_PreviewTitle: 'Xem trước: {columnName}',
    ColumnMapper_EmptyCellDash: '—',

    // ── Import field display names / ImportService ──
    ImportField_TaskName: 'Tên công việc',
    ImportField_StartDate: 'Ngày bắt đầu',
    ImportField_DueDate: 'Ngày đến hạn',
    ImportField_Status: 'Trạng thái',
    ImportField_Priority: 'Mức ưu tiên',
    ImportField_AssignedTo: 'Người được giao',
    ImportField_AssignedToEmail: 'Email người được giao',
    ImportField_PercentComplete: '% Hoàn thành',
    ImportField_Phase: 'Giai đoạn',
    ImportField_Description: 'Mô tả',
    ImportField_Notes: 'Ghi chú',
    ImportField_IsMilestone: 'Là cột mốc',
    ImportField_Dependencies: 'Các phụ thuộc',
    ImportField_SkipColumn: '(Bỏ qua cột này)',
    ImportService_EmptyFileError: 'Tệp có vẻ trống hoặc không có hàng dữ liệu.',
    ImportService_ReadErrorDetail: 'Không thể đọc tệp: {detail}.',
    ImportService_FileReadError: 'Lỗi đọc tệp.',
    ImportService_RowError: 'Hàng {rowNum} ("{title}"): {error}',
    ImportService_AmbiguousDependency: 'Phụ thuộc "{name}" khớp với nhiều hơn một tên công việc — đã bỏ qua.',
    ImportService_LinkDependencyError: 'Không thể liên kết các phụ thuộc cho công việc {taskId}: {error}',

    // ── Health labels (shared: healthUtils.ts and ExportService.ts both use this set; also replaces the duplicated Export_PortfolioHealthLabel* keys) ──
    Health_Done: 'Hoàn thành',
    Health_OnTrack: 'Đúng tiến độ',
    Health_AtRisk: 'Có rủi ro',
    Health_Overdue: 'Quá hạn',

    // ── Status / Priority display labels (DISPLAY-ONLY — stored SharePoint Choice values remain unchanged/English) ──
    Status_NotStarted: 'Chưa bắt đầu',
    Status_InProgress: 'Đang thực hiện',
    Status_Completed: 'Đã hoàn thành',
    Status_OnHold: 'Tạm hoãn',
    Status_Cancelled: 'Đã hủy',
    Priority_Critical: 'Khẩn cấp',
    Priority_High: 'Cao',
    Priority_Medium: 'Trung bình',
    Priority_Low: 'Thấp',
    ProjectStatus_Planning: 'Đang lập kế hoạch',
    ProjectStatus_Active: 'Đang hoạt động',
    ProjectStatus_OnHold: 'Tạm hoãn',
    ProjectStatus_Completed: 'Đã hoàn thành',
    ProjectStatus_Cancelled: 'Đã hủy',

    // ── Shell (SmartGantt.tsx) ──
    SmartGantt_LoadingProjects: 'Đang tải dự án…',
    SmartGantt_UnableToLoad: 'Không thể tải',
    SmartGantt_RetryButton: 'Thử lại',
    SmartGantt_NoProjectsYet: 'Chưa có dự án nào',
    SmartGantt_NoProjectsSubtitle: 'Tạo dự án đầu tiên của bạn để bắt đầu.',
    SmartGantt_CreateFirstProjectButton: '+ Tạo dự án đầu tiên',
    SmartGantt_ImportFromExcelButton: '📥 Nhập từ Excel',
    SmartGantt_LoadingTasks: 'Đang tải công việc…',
    SmartGantt_DismissAriaLabel: 'Đóng',
    SmartGantt_DeleteTaskDialogTitle: 'Xóa công việc',
    SmartGantt_DeleteTaskDialogSubtext: 'Bạn có chắc chắn muốn xóa "{taskTitle}"? Hành động này không thể hoàn tác.',
    SmartGantt_DeleteButton: 'Xóa',
    SmartGantt_CancelButton: 'Hủy',
    SmartGantt_ArchiveProjectDialogTitle: 'Lưu trữ dự án',
    SmartGantt_ArchiveProjectDialogSubtext: 'Lưu trữ "{projectTitle}"? Bạn có thể bỏ lưu trữ sau.',
    SmartGantt_ArchiveButton: 'Lưu trữ',
    SmartGantt_SendToRecycleBinDialogTitle: 'Chuyển vào thùng rác',
    SmartGantt_SendToRecycleBinDialogSubtext: 'Chuyển "{projectTitle}" vào thùng rác của trang?',
    SmartGantt_SendToRecycleBinButton: 'Chuyển vào thùng rác',
    SmartGantt_FailedLoadProjects: 'Không thể tải dự án. Kiểm tra quyền của trang.',
    SmartGantt_FailedLoadTasks: 'Không thể tải công việc cho dự án này.',
    SmartGantt_FailedLoadPortfolioStats: 'Không thể tải số liệu thống kê danh mục.',
    SmartGantt_CouldNotSaveProject: 'Không thể lưu dự án: {message}',
    SmartGantt_CouldNotDeleteProject: 'Không thể xóa dự án: {message}',
    SmartGantt_CouldNotArchiveProject: 'Không thể lưu trữ dự án: {message}',
    SmartGantt_CouldNotUnarchiveProject: 'Không thể bỏ lưu trữ dự án: {message}',
    SmartGantt_CouldNotSaveTask: 'Không thể lưu công việc: {message}',
    SmartGantt_CouldNotDeleteTask: 'Không thể xóa công việc: {message}',
    SmartGantt_ImageExportFailed: 'Xuất hình ảnh thất bại: {message}',
    SmartGantt_PowerPointExportFailed: 'Xuất PowerPoint thất bại: {message}',
    SmartGantt_PortfolioExportFailed: 'Xuất danh mục thất bại: {message}',
    SmartGantt_CouldNotUpdateTask: 'Không thể cập nhật công việc: {message}',

    // ── Common ──
    ColorSwatch_AutoColorAriaLabel: 'Màu tự động',
    ColorSwatch_CustomColorAriaLabel: 'Màu tùy chỉnh',
    ColorSwatch_PickCustomColorTitle: 'Chọn một màu tùy chỉnh',

    // ── Export (Excel / PowerPoint) ──
    Export_ColTaskName: 'Tên công việc',
    Export_ColPhase: 'Giai đoạn',
    Export_ColStartDate: 'Ngày bắt đầu',
    Export_ColDueDate: 'Ngày đến hạn',
    Export_ColStatus: 'Trạng thái',
    Export_ColPriority: 'Mức ưu tiên',
    Export_ColAssignedTo: 'Người được giao',
    Export_ColAssignedToEmail: 'Email người được giao',
    Export_ColPercentComplete: '% Hoàn thành',
    Export_ColIsMilestone: 'Là cột mốc',
    Export_ColDescription: 'Mô tả',
    Export_ColNotes: 'Ghi chú',
    Export_Yes: 'Có',
    Export_No: 'Không',
    Export_SheetNameTasks: 'Công việc',
    Export_ExcelFileSuffix: ' - Công việc.xlsx',
    Export_TaskNameColumnLabel: 'TÊN CÔNG VIỆC',
    Export_ExportedDateLabel: 'Đã xuất {date}',
    Export_ProjectReportLabel: 'BÁO CÁO DỰ ÁN',
    Export_StatusLine: 'Trạng thái: {status}',
    Export_DateRangeSeparator: ' đến ',
    Export_ProjectManagerLine: 'Quản lý dự án: {name}',
    Export_GeneratedDateLine: 'Được tạo {date}',
    Export_ProjectSummaryTitle: 'Tóm tắt dự án',
    Export_StatTotalTasks: 'Tổng số công việc',
    Export_StatCompleted: 'Đã hoàn thành',
    Export_StatInProgress: 'Đang thực hiện',
    Export_StatOnHold: 'Tạm hoãn',
    Export_StatNotStarted: 'Chưa bắt đầu',
    Export_OverallProgressLine: 'Tiến độ tổng thể',
    Export_OverallProgressPercent: '{percent}%',
    Export_StatusBreakdownTitle: 'Phân tích theo trạng thái',
    Export_StatusBreakdownRow: '{status}: {count} ({percent}%)',
    Export_GanttTimelineTitle: 'Dòng thời gian Gantt',
    Export_SummaryRecentActivityTitle: 'Hoạt động gần đây',
    Export_ProjectOverviewLabel: 'Tổng quan dự án',
    Export_DetailStatusLabel: 'Trạng thái',
    Export_DetailStartDateLabel: 'Ngày bắt đầu',
    Export_DetailDueDateLabel: 'Ngày đến hạn',
    Export_DetailProjectManagerLabel: 'Quản lý dự án',
    Export_Past7DaysLabel: '7 ngày qua',
    Export_NoActivityMessage: 'Không có hoạt động gần đây.',
    Export_CompletedThisWeekHeader: 'Hoàn thành trong tuần này ({count})',
    Export_NewBadge: 'MỚI  ',
    Export_CompletedPercentLine: 'Hoàn thành {percent}%',
    Export_MoreItemsSuffix: '+ {count} mục khác',
    Export_InProgressUpdatedHeader: 'Đang thực hiện / Đã cập nhật',
    Export_StatusPercentLine: '{status} — {percent}%',
    Export_PortfolioReportLabel: 'BÁO CÁO DANH MỤC',
    Export_PortfolioOverviewTitle: 'Tổng quan danh mục',
    Export_ProjectsCountLine: '{count} dự án',
    Export_HealthSummaryOnTrack: '{count} đúng tiến độ',
    Export_HealthSummaryAtRisk: '{count} có rủi ro',
    Export_HealthSummaryOverdue: '{count} quá hạn',
    Export_ProjectsSummaryHeader: 'Tóm tắt dự án',
    Export_TableProject: 'Dự án',
    Export_TableStatus: 'Trạng thái',
    Export_TableHealth: 'Tình trạng',
    Export_TableTotal: 'Tổng',
    Export_TableDone: 'Hoàn thành',
    Export_TableActive: 'Đang hoạt động',
    Export_TableAtRisk: 'Có rủi ro',
    Export_TableOverdue: 'Quá hạn',
    Export_TablePctDone: '% Hoàn thành',
    Export_TableDueDate: 'Ngày đến hạn',
    Export_PortfolioSummaryFileName: 'Tóm tắt danh mục.xlsx',
    Export_PortfolioReportFileName: 'Báo cáo danh mục.pptx',
    Export_ProjectReportFileName: 'Báo cáo {projectName}.pptx',
    Export_UnavailableLabel: 'Không khả dụng',
    Export_SheetNamePortfolio: 'Danh mục',
    Export_ColStart: 'Bắt đầu',
    Export_ColDue: 'Hạn',
    Export_ImageGenerationFailed: 'Không thể tạo hình ảnh — biểu đồ có thể quá lớn để xuất dưới dạng hình ảnh.',
    Export_DrawingContextFailed: 'Không thể tạo ngữ cảnh vẽ để xuất.',
    Export_SvgRenderFailed: 'Không thể kết xuất SVG',

    // ── Added in v1.5 review ──
    Svc_TooManyDependencies: 'Công việc này có quá nhiều phụ thuộc để lưu (giới hạn khoảng 60). Hãy xóa bớt và thử lại.',
    Svc_TaskChangedByOthers: 'Công việc này đã được người khác thay đổi kể từ khi bạn tải. Hãy làm mới và thử lại.',
    Svc_ProjectChangedByOthers: 'Dự án này đã được người khác thay đổi kể từ khi bạn mở. Hãy làm mới và thử lại.',
    Svc_ColumnCreateFailed: 'Không thể tạo {count} cột trên danh sách công việc mới: {detail}',
    Svc_BaselineUnavailable: 'Đường cơ sở không khả dụng cho dự án này vì không thể thêm các cột đường cơ sở (bạn có thể cần quyền chỉnh sửa danh sách).',
    Svc_SubtaskReassignFailed: 'Không thể gán lại các công việc con của công việc này trước khi xóa: {detail}',
    Svc_UnresolvedDependency: 'Hàng {row} ("{title}"): không thể khớp phụ thuộc "{name}" với một công việc đã nhập.',
    Svc_SelfDependency: 'Hàng {row} ("{title}"): phụ thuộc "{name}" trỏ đến chính công việc đó và đã bị bỏ qua.',
    Svc_ColId: 'ID',
    Svc_ColDependencies: 'Phụ thuộc',
    Svc_ColBaselineStart: 'Bắt đầu đường cơ sở',
    Svc_ColBaselineDue: 'Hạn đường cơ sở',
    Svc_CsvFileSuffix: ' - Tasks.csv',
    Svc_IcsFileSuffix: ' - Milestones.ics',
    Svc_PortfolioCsvFileName: 'Portfolio Summary.csv',
    Svc_PP_DisplayGroup: 'Mặc định',
    Svc_PP_DefaultView: 'Chế độ xem mặc định',
    Svc_PP_ViewGantt: 'Gantt',
    Svc_PP_ViewList: 'Danh sách',
    Svc_PP_ViewKanban: 'Kanban',
    Svc_PP_ViewDashboard: 'Bảng điều khiển',
    Svc_PP_ViewPortfolio: 'Danh mục dự án',
    Svc_PP_DefaultZoom: 'Thu phóng mặc định',
    Svc_PP_ZoomDay: 'Ngày',
    Svc_PP_ZoomWeek: 'Tuần',
    Svc_PP_ZoomMonth: 'Tháng',
    Svc_PP_ZoomQuarter: 'Quý',
    Svc_PP_CalendarGroup: 'Lịch làm việc',
    Svc_PP_DaySun: 'Chủ nhật là ngày làm việc',
    Svc_PP_DayMon: 'Thứ Hai là ngày làm việc',
    Svc_PP_DayTue: 'Thứ Ba là ngày làm việc',
    Svc_PP_DayWed: 'Thứ Tư là ngày làm việc',
    Svc_PP_DayThu: 'Thứ Năm là ngày làm việc',
    Svc_PP_DayFri: 'Thứ Sáu là ngày làm việc',
    Svc_PP_DaySat: 'Thứ Bảy là ngày làm việc',
    Svc_PP_Holidays: 'Ngày nghỉ lễ (ngày không làm việc)',
    Svc_PP_HolidaysHint: 'Mỗi dòng một ngày, theo định dạng yyyy-MM-dd (ví dụ 2026-12-25).',
    Gantt_TimelineAriaLabel: 'Dòng thời gian công việc',
    Gantt_DragLabel: '{start} → {end} ({days} ngày)',
    Gantt_KeyboardMoveAnnouncement: '{taskTitle}: {startDate} đến {dueDate}',
    Gantt_KeyboardHint: 'Nhấn Enter để mở công việc. Các phím mũi tên trái và phải di chuyển công việc một ngày làm việc. Shift cùng các phím mũi tên sẽ thay đổi ngày kết thúc.',
    Gantt_ParentCycleTooltip: 'Công việc này thuộc một chuỗi vòng tròn gồm công việc cha và công việc con, nên được hiển thị ở cấp cao nhất',
    Gantt_CollapseAll: 'Thu gọn tất cả giai đoạn',
    Gantt_ExpandAll: 'Mở rộng tất cả giai đoạn',
    Gantt_BaselineTooltip: 'Đường cơ sở: {start} → {due}',
    Gantt_VarianceTooltip: 'Chênh lệch ngày hoàn thành: {days} ngày so với đường cơ sở',
    Gantt_LinkHandleTitle: 'Kéo đến công việc khác để tạo phụ thuộc',
    Toolbar_FitToProject: 'Vừa khít',
    Toolbar_FitToProjectTitle: 'Thu phóng vừa toàn bộ dự án',
    Toolbar_UndoTitle: 'Hoàn tác (Ctrl+Z)',
    Toolbar_RedoTitle: 'Làm lại (Ctrl+Y)',
    Toolbar_ExportCsv: '📄 Xuất công việc ra CSV',
    Toolbar_ExportIcs: '📅 Xuất cột mốc (iCal)',
    Toolbar_Print: '🖨 In / Lưu dưới dạng PDF',
    Toolbar_SetBaseline: '📐 Đặt đường cơ sở…',
    Toolbar_CopyLink: '🔗 Sao chép liên kết',
    Toolbar_CopyLinkTitle: 'Sao chép liên kết đến chế độ xem này (dự án, chế độ xem, thu phóng và bộ lọc)',
    App_UndoButton: 'Hoàn tác',
    App_Undone: 'Đã hoàn tác thay đổi.',
    App_Redone: 'Đã làm lại thay đổi.',
    App_DependentsMovedOne: 'Đã di chuyển 1 công việc phụ thuộc.',
    App_DependentsMovedMany: 'Đã di chuyển {count} công việc phụ thuộc.',
    App_TaskConflict: 'Công việc này đã được người khác thay đổi. Các công việc mới nhất đã được tải lại — hãy xem lại và thử lại.',
    App_DependencyCycle: 'Liên kết đó sẽ tạo ra một phụ thuộc vòng.',
    App_DependencyExists: 'Các công việc đó đã được liên kết.',
    App_LinkCopied: 'Đã sao chép liên kết vào bảng nhớ tạm.',
    App_LinkCopyFailed: 'Không thể sao chép liên kết: {message}',
    App_PopupBlocked: 'Cửa sổ in đã bị chặn. Hãy cho phép cửa sổ bật lên đối với trang này và thử lại.',
    App_SetBaselineDialogTitle: 'Đặt đường cơ sở',
    App_SetBaselineDialogSubtext: 'Lưu ngày bắt đầu và ngày hạn hiện tại của tất cả {count} công việc làm đường cơ sở? Đường cơ sở hiện có sẽ bị thay thế.',
    App_SetBaselineButton: 'Đặt đường cơ sở',
    App_BaselineSaved: 'Đã lưu đường cơ sở.',
    App_BaselineFailed: 'Không thể lưu đường cơ sở: {message}',
    App_CsvExportFailed: 'Xuất CSV không thành công: {message}',
    App_IcsExportFailed: 'Xuất lịch không thành công: {message}',
    App_BulkDeleteDialogTitle: 'Xóa công việc',
    App_BulkDeleteDialogSubtext: 'Bạn có chắc chắn muốn xóa {count} công việc không? Không thể hoàn tác thao tác này.',
    Common_PeoplePicker_ClearAriaLabel: 'Xóa',
    Common_PeoplePicker_DirectoryHeader: 'Người trong thư mục',
    Common_PeoplePicker_EmailLabel: 'Email (không bắt buộc)',
    Common_PeoplePicker_EmailPlaceholder: 'name@company.com',
    Common_PeoplePicker_ExternalHint: 'Không có trong thư mục. Được lưu dưới dạng văn bản tự do.',
    Common_PeoplePicker_InvalidEmail: 'Nhập địa chỉ email hợp lệ.',
    Common_PeoplePicker_ListAriaLabel: 'Đề xuất người',
    Common_PeoplePicker_RecentHeader: 'Dùng gần đây',
    Common_PeoplePicker_ResultsAnnouncement: 'Có {count} đề xuất',
    Common_PeoplePicker_Searching: 'Đang tìm kiếm…',
    Common_PeoplePicker_UseExternal: 'Dùng “{name}” (bên ngoài / không có trong thư mục)',
    Import_Mapper_PreviewFirstRows: 'Xem trước ({count} hàng đầu tiên)',
    Import_Mapper_RequiredLegend: 'Trường bắt buộc',
    Import_Mapper_RequiredMarkerLabel: 'Bắt buộc',
    Import_Mapper_SelectAriaLabel: 'Trường đích cho cột {columnName}',
    Import_Panel_DateOrderAuto: 'Tự động phát hiện',
    Import_Panel_DateOrderDMY: 'Ngày/Tháng/Năm (31/12/2026)',
    Import_Panel_DateOrderDetected: 'Phát hiện từ tệp của bạn: {order}.',
    Import_Panel_DateOrderHint: 'Áp dụng cho ngày được viết bằng số, chẳng hạn 03/04/2026.',
    Import_Panel_DateOrderLabel: 'Thứ tự ngày',
    Import_Panel_DateOrderMDY: 'Tháng/Ngày/Năm (12/31/2026)',
    Import_Panel_DropZoneAriaLabel: 'Chọn tệp để nhập. Nhấn Enter để duyệt.',
    Import_Panel_DropZoneChangeAriaLabel: 'Tệp đã chọn {fileName}. Nhấn Enter để chọn tệp khác.',
    Import_Panel_FailedCount: '{count} không thành công',
    Import_Panel_NewProjectIntroMany: 'Một dự án mới sẽ được tạo và tất cả {count} công việc sẽ được nhập vào đó. Bạn có thể thay đổi các chi tiết này bất cứ lúc nào sau khi nhập.',
    Import_Panel_NewProjectIntroOne: 'Một dự án mới sẽ được tạo và {count} công việc sẽ được nhập vào đó. Bạn có thể thay đổi các chi tiết này bất cứ lúc nào sau khi nhập.',
    Import_Panel_PlanAriaLabel: '{planName}, {groupName}',
    Import_Panel_ProblemEndBeforeStart: 'Ngày hạn trước ngày bắt đầu',
    Import_Panel_ProblemInvalidDueDate: 'Ngày hạn "{value}" không phải là ngày hợp lệ',
    Import_Panel_ProblemInvalidStartDate: 'Ngày bắt đầu "{value}" không phải là ngày hợp lệ',
    Import_Panel_ProblemMissingTitle: 'Thiếu tên công việc',
    Import_Panel_ProgressLabelWithPercent: '{done}/{total} ({percent}%)',
    Import_Panel_SkipInvalidRows: 'Bỏ qua các hàng có vấn đề',
    Import_Panel_SuccessWithWarningsMany: 'Nhập thành công với {count} cảnh báo.',
    Import_Panel_SuccessWithWarningsOne: 'Nhập thành công với {count} cảnh báo.',
    Import_Panel_ValidationHeader: 'Các hàng có vấn đề',
    Import_Panel_ValidationMore: '…và {count} mục khác',
    Import_Panel_ValidationRow: 'Hàng {rowNum}: {problem}',
    Import_Panel_ValidationSummaryMany: '{count} hàng có vấn đề',
    Import_Panel_ValidationSummaryOne: '{count} hàng có vấn đề',
    Import_Panel_WarningsLabel: 'Cảnh báo ({count}):',
    Panel_Project_ManagerLabel: 'Quản lý dự án',
    Panel_Project_ManagerPlaceholder: 'Tìm người hoặc nhập tên…',
    Panel_Task_BaselineDueLabel: 'Kết thúc đường cơ sở',
    Panel_Task_BaselineHeader: 'Đường cơ sở',
    Panel_Task_BaselineStartLabel: 'Bắt đầu đường cơ sở',
    Panel_Task_DepTypeFF: 'Kết thúc-Kết thúc (FF)',
    Panel_Task_DepTypeFS: 'Kết thúc-Bắt đầu (FS)',
    Panel_Task_DepTypeSF: 'Bắt đầu-Kết thúc (SF)',
    Panel_Task_DepTypeSS: 'Bắt đầu-Bắt đầu (SS)',
    Panel_Task_LagAriaLabel: 'Độ trễ theo ngày làm việc cho {taskTitle}',
    Panel_Task_LagHint: 'Độ trễ tính theo ngày làm việc. Dùng số âm cho thời gian dẫn trước.',
    Panel_Task_LinkTypeAriaLabel: 'Loại liên kết cho {taskTitle}',
    Panel_Task_VarianceEarlier: 'Sớm hơn {days} ngày làm việc',
    Panel_Task_VarianceLater: 'Muộn hơn {days} ngày làm việc',
    Panel_Task_VarianceOnBaseline: 'đúng đường cơ sở',
    View_Dashboard_BurndownActual: 'Thực tế',
    View_Dashboard_BurndownAria: 'Biểu đồ Burndown: còn lại {remaining}/{total} công việc',
    View_Dashboard_BurndownHeader: 'Burndown (công việc còn lại)',
    View_Dashboard_BurndownIdeal: 'Lý tưởng',
    View_Dashboard_BurndownNoData: 'Không đủ công việc có ngày để vẽ biểu đồ Burndown.',
    View_Dashboard_CriticalPathHeader: 'Đường găng  ({count})',
    View_Dashboard_PhaseDoneSummary: '{done}/{total} hoàn thành  •  {percent}%',
    View_Dashboard_TaskRowAriaLabel: 'Mở công việc {taskTitle}, {status}',
    View_Dashboard_WorkloadHeader: 'Khối lượng công việc theo người được giao',
    View_Dashboard_WorkloadOpen: '{count} đang mở',
    View_Dashboard_WorkloadOverdue: '{count} quá hạn',
    View_Kanban_AddTaskInColumnAriaLabel: 'Thêm công việc vào {column}',
    View_Kanban_CollapseColumn: 'Thu gọn cột {column}',
    View_Kanban_ExpandColumn: 'Mở rộng cột {column}',
    View_Kanban_LaneHeader: '{name} ({count})',
    View_Kanban_LaneNoPhase: 'Không có giai đoạn',
    View_Kanban_LaneUnassigned: 'Chưa được giao',
    View_Kanban_LanesAssignee: 'Người được giao',
    View_Kanban_LanesNone: 'Không có',
    View_Kanban_LanesPhase: 'Giai đoạn',
    View_Kanban_SwimlanesLabel: 'Làn',
    View_Kanban_WipEditTitle: 'Đặt giới hạn công việc đang thực hiện cho {column} (0 nghĩa là không giới hạn)',
    View_Kanban_WipExceededTitle: 'Vượt giới hạn WIP: {count}/{limit}',
    View_Kanban_WipInputAriaLabel: 'Giới hạn WIP cho {column}',
    View_Kanban_WipLabel: 'WIP {count}/{limit}',
    View_Kanban_WipSet: 'WIP',
    View_List_BulkAssignApply: 'Giao',
    View_List_BulkAssigneePlaceholder: 'Giao cho…',
    View_List_BulkBarAriaLabel: 'Thao tác hàng loạt cho các công việc đã chọn',
    View_List_BulkClear: 'Bỏ chọn',
    View_List_BulkDelete: 'Xóa mục đã chọn',
    View_List_BulkPercentApply: 'Đặt %',
    View_List_BulkPercentPlaceholder: '% hoàn thành',
    View_List_BulkPriorityPlaceholder: 'Đặt mức ưu tiên…',
    View_List_BulkSelectedCount: 'Đã chọn {count}',
    View_List_BulkStatusPlaceholder: 'Đặt trạng thái…',
    View_List_ExportCsv: 'Xuất CSV',
    View_List_NonWorkingDay: 'Ngày không làm việc',
    View_List_SelectAllAriaLabel: 'Chọn tất cả công việc',
    View_List_SelectRowAriaLabel: 'Chọn {taskTitle}',
    View_Portfolio_CardAriaLabel: 'Mở dự án {projectName}, {status}',
    View_Portfolio_ClearFilters: 'Xóa bộ lọc',
    View_Portfolio_FilteredCount: '{shown}/{total} dự án',
    View_Portfolio_HideDone: 'Ẩn đã hoàn thành / đã hủy',
    View_Portfolio_NoMatches: 'Không có dự án nào khớp với bộ lọc của bạn.',
    View_Portfolio_ProjectCountMany: '{count} dự án',
    View_Portfolio_ProjectCountOne: '{count} dự án',
    View_Portfolio_SearchAriaLabel: 'Tìm kiếm dự án',
    View_Portfolio_SearchPlaceholder: 'Tìm kiếm dự án…',
    Import_Panel_CopyDetails: 'Sao chép chi tiết',
    Import_Panel_Copied: 'Đã sao chép',
  };
});
