define([], function () {
  return {
    // ── Property pane ──
    PropertyPane_HeaderDescription: 'Smart Gantt Chart 设置',
    PropertyPane_GeneralGroupName: '常规',
    PropertyPane_TitleFieldLabel: 'Web 部件标题',
    WebPart_DefaultTitle: 'Smart Gantt Chart',

    // ── Toolbar ──
    Toolbar_ViewDashboard: '仪表板',
    Toolbar_ViewList: '列表',
    Toolbar_ViewGantt: '甘特图',
    Toolbar_ViewKanban: '看板',
    Toolbar_ZoomDay: '日',
    Toolbar_ZoomWeek: '周',
    Toolbar_ZoomMonth: '月',
    Toolbar_ZoomQuarter: '季度',
    Toolbar_SelectProjectAriaLabel: '选择项目',
    Toolbar_PortfolioLabel: '项目组合',
    Toolbar_SelectAProject: '选择一个项目',
    Toolbar_AllProjectsSubtext: '所有项目',
    Toolbar_NoProjectsYet: '暂无项目',
    Toolbar_ArchivedBadge: '已归档',
    Toolbar_ShowArchivedProjects: '显示已归档的项目',
    Toolbar_NewProject: '+ 新建项目',
    Toolbar_ImportFileAsNewProject: '📥 将文件导入为新项目…',
    Toolbar_AddTask: '+ 添加任务',
    Toolbar_EditProject: '编辑项目',
    Toolbar_OptionsButton: '⚙ 选项',
    Toolbar_MoreOptionsTitle: '更多选项',
    Toolbar_ExportToExcel: '📊 导出到 Excel',
    Toolbar_ExportToPowerPoint: '📑 导出到 PowerPoint',
    Toolbar_ScrollToTodayTitle: '滚动到今天',
    Toolbar_TodayButton: '◉ 今天',
    Toolbar_ImportTasks: '📥 导入任务…',
    Toolbar_ExportAsImage: '🖼 导出为图片 (PNG)',
    Toolbar_UnarchiveProject: '📂 取消归档项目',
    Toolbar_ArchiveProject: '🗄️ 归档项目',
    Toolbar_SendToRecycleBin: '🗑️ 发送到回收站',

    // ── Filter bar ──
    FilterBar_ClearOption: '清除',
    FilterBar_DueAny: '任意截止日期',
    FilterBar_DueOverdue: '已逾期',
    FilterBar_DueToday: '今天截止',
    FilterBar_DueWeek: '7 天内截止',
    FilterBar_SearchPlaceholder: '搜索任务…',
    FilterBar_SearchAriaLabel: '搜索任务',
    FilterBar_StatusChipLabel: '状态',
    FilterBar_PriorityChipLabel: '优先级',
    FilterBar_AssigneeChipLabel: '负责人',
    FilterBar_PhaseChipLabel: '阶段',
    FilterBar_DueDateAriaLabel: '按截止日期筛选',
    FilterBar_MatchCount: '{matchCount} / {totalCount}',
    FilterBar_ClearFilters: '✕ 清除筛选条件',
    FilterBar_ChipLabelWithCount: '{label} ({count}) ▾',
    FilterBar_ChipLabelNoCount: '{label} ▾',

    // ── Gantt view ──
    Gantt_TaskColumnHeader: '任务',
    Gantt_DurationColumnHeader: '工期',
    Gantt_AddTaskButton: '+ 添加任务',
    Gantt_EmptyTitle: '暂无任务',
    Gantt_EmptySubtitle: '添加任务后即可在甘特图中查看。',
    Gantt_AddFirstTask: '+ 添加第一个任务',
    Gantt_ImportTasksButton: '📥 导入任务',
    Gantt_EditTitle: '编辑',
    Gantt_DeleteTitle: '删除',
    Gantt_EditTaskAriaLabel: '编辑任务 {taskTitle}',
    Gantt_DeleteTaskAriaLabel: '删除任务 {taskTitle}',
    Gantt_ExpandPhaseAriaLabel: '{action}阶段 {phase}',
    Gantt_ExpandAction: '展开',
    Gantt_CollapseAction: '折叠',
    Gantt_DependencyViolationTooltip: '在所有依赖项完成之前已开始',
    Gantt_MilestoneAriaLabel: '{taskTitle}，里程碑，{date}',
    Gantt_BarAriaLabel: '{taskTitle}，{startDate} 至 {dueDate}，已完成 {percent}%',
    Gantt_PercentCompleteTooltip: '已完成 {value}%',

    // ── Gantt options/settings panel ──
    GanttSettings_PanelHeader: '⚙ 选项',
    GanttSettings_ColorCodingSection: '颜色编码',
    GanttSettings_ByStatus: '按状态',
    GanttSettings_ByPriority: '按优先级',
    GanttSettings_ByPhase: '按阶段',
    GanttSettings_ByHealth: '按健康状况',
    GanttSettings_HeaderColorSection: '标题颜色',
    GanttSettings_ThemeDark: '深色',
    GanttSettings_ThemeNavy: '藏青色',
    GanttSettings_ThemeTeal: '青色',
    GanttSettings_ThemePurple: '紫色',
    GanttSettings_ThemeLight: '浅色',
    GanttSettings_HeaderLabelsSection: '标题标签',
    GanttSettings_WeekLabelDates: '日期',
    GanttSettings_WeekLabelDatesDesc: '6月3日，6月10日…',
    GanttSettings_WeekLabelProject: '项目周',
    GanttSettings_WeekLabelProjectDesc: 'W1、W2…',
    GanttSettings_WeekLabelIso: '日历周',
    GanttSettings_WeekLabelIsoDesc: 'W23、W24…',
    GanttSettings_ProjectWeeksHint: '第 1 周从您最早任务所在周的星期一开始 — 非常适合用于演示。',
    GanttSettings_BarStyleSection: '条形样式',
    GanttSettings_BarStyleGradient: '渐变',
    GanttSettings_BarStyleFlat: '平面',
    GanttSettings_RowHeightSection: '行高',
    GanttSettings_HeightCompact: '紧凑',
    GanttSettings_HeightNormal: '正常',
    GanttSettings_HeightSpacious: '宽松',
    GanttSettings_ShowHideSection: '显示/隐藏',
    GanttSettings_WeekendShading: '周末底纹',
    GanttSettings_DependencyArrows: '依赖关系箭头',
    GanttSettings_CriticalPathAlwaysVisible: '关键路径始终可见',
    GanttSettings_AllOthersOnHoverOnly: '其他所有项仅在悬停时显示',
    GanttSettings_CriticalPathHighlight: '关键路径高亮',
    GanttSettings_ProgressPercentOnBars: '在条形图上显示进度百分比',
    GanttSettings_AssigneeNameOnBars: '在条形图上显示负责人姓名',
    GanttSettings_HealthStatusBadges: '健康状况徽章',

    // ── List view ──
    ListView_ColTaskName: '任务名称',
    ListView_ColStatus: '状态',
    ListView_ColHealth: '健康状况',
    ListView_ColPriority: '优先级',
    ListView_ColStart: '开始日期',
    ListView_ColDue: '截止日期',
    ListView_ColAssignedTo: '负责人',
    ListView_ColProgress: '进度',
    ListView_ColPhase: '阶段',
    ListView_ColPredecessors: '前置任务',
    ListView_EmptyTitle: '暂无任务',
    ListView_AddFirstTask: '+ 添加第一个任务',
    ListView_AddTaskRow: '+ 添加任务',
    ListView_Unassigned: '未分配',
    ListView_DependencyViolationTooltip: '在所有依赖项完成之前已开始',
    ListView_StatusAriaLabel: '{taskTitle} 的状态',
    ListView_PriorityAriaLabel: '{taskTitle} 的优先级',
    ListView_EditTaskAriaLabel: '编辑任务 {taskTitle}',
    ListView_DeleteTaskAriaLabel: '删除任务 {taskTitle}',
    ListView_EditTitle: '编辑',
    ListView_DeleteTitle: '删除',

    // ── Kanban view ──
    Kanban_ColumnNotStarted: '未开始',
    Kanban_ColumnInProgress: '进行中',
    Kanban_ColumnOnHold: '已暂停',
    Kanban_ColumnCompleted: '已完成',
    Kanban_ColumnCancelled: '已取消',
    Kanban_AddTaskButton: '+ 添加任务',
    Kanban_EditTitle: '编辑',
    Kanban_DeleteTitle: '删除',
    Kanban_CardAriaLabel: '{taskTitle}，{status}。按 Enter 键编辑，按左右方向键更改状态。',
    Kanban_EditTaskAriaLabel: '编辑任务 {taskTitle}',
    Kanban_DeleteTaskAriaLabel: '删除任务 {taskTitle}',

    // ── Dashboard view ──
    Dashboard_TotalTasks: '任务总数',
    Dashboard_Completed: '已完成',
    Dashboard_InProgress: '进行中',
    Dashboard_OnHold: '已暂停',
    Dashboard_NotStarted: '未开始',
    Dashboard_Cancelled: '已取消',
    Dashboard_OverallProgress: '总体进度',
    Dashboard_ProjectManagerLabel: '项目经理：{name}',
    Dashboard_PhaseProgressHeader: '阶段进度',
    Dashboard_StatusBreakdownHeader: '状态分布',
    Dashboard_PriorityBreakdownHeader: '优先级分布',
    Dashboard_PriorityCritical: '紧急',
    Dashboard_PriorityHigh: '高',
    Dashboard_PriorityMedium: '中',
    Dashboard_PriorityLow: '低',
    Dashboard_OverdueHeader: '已逾期 ({count})',
    Dashboard_DueNext14DaysHeader: '未来 14 天内到期 ({count})',
    Dashboard_CompletedThisWeekHeader: '本周已完成',
    Dashboard_UpdatedThisWeekHeader: '本周已更新',
    Dashboard_Today: '今天',
    Dashboard_Tomorrow: '明天',
    Dashboard_DaysLeft: '{days} 天',
    Dashboard_EmptyTitle: '暂无任务',
    Dashboard_EmptySubtitle: '添加任务以查看您的项目仪表板。',
    Dashboard_AddTaskButton: '+ 添加任务',

    // ── Portfolio view ──
    Portfolio_ProjectCount: '{count} 个项目{plural}',
    Portfolio_OnTrackSummary: '{count} 个进展顺利',
    Portfolio_AtRiskSummary: '{count} 个存在风险',
    Portfolio_OverdueSummary: '{count} 个已逾期',
    Portfolio_DoneSummary: '{count} 个已完成',
    Portfolio_SortLabel: '排序：',
    Portfolio_SortAZ: 'A-Z',
    Portfolio_SortHealth: '健康状况',
    Portfolio_SortStatus: '状态',
    Portfolio_SortCompletion: '完成度',
    Portfolio_RefreshTitle: '刷新',
    Portfolio_RefreshButton: '刷新',
    Portfolio_LoadingStats: '正在加载统计信息…',
    Portfolio_EmptyTitle: '暂无项目',
    Portfolio_CreateFirstProject: '+ 创建第一个项目',
    Portfolio_StatsUnavailable: '统计信息不可用',
    Portfolio_StatsUnavailableDetail: '无法加载此项目的统计信息。',
    Portfolio_OverallProgressLabel: '总体进度',
    Portfolio_TaskCountDone: '已完成',
    Portfolio_TaskCountActive: '进行中',
    Portfolio_TaskCountAtRisk: '存在风险',
    Portfolio_TaskCountOverdue: '已逾期',
    Portfolio_ViewGanttLink: '查看甘特图 →',
    Portfolio_TodayTooltip: '今天',

    // ── Task panel ──
    TaskPanel_EditHeader: '编辑：{taskTitle}',
    TaskPanel_NewTaskHeader: '新建任务',
    TaskPanel_TabBasic: '基本信息',
    TaskPanel_TabDetails: '详细信息',
    TaskPanel_TabLinks: '关联',
    TaskPanel_ProjectLabelPrefix: '项目：',
    TaskPanel_TaskNameLabel: '任务名称',
    TaskPanel_TaskNamePlaceholder: '输入任务名称',
    TaskPanel_TaskNameRequired: '任务名称为必填项',
    TaskPanel_DescriptionLabel: '描述',
    TaskPanel_DescriptionPlaceholder: '输入描述',
    TaskPanel_StartDateLabel: '开始日期',
    TaskPanel_DueDateLabel: '截止日期',
    TaskPanel_DueDateError: '截止日期必须晚于或等于开始日期',
    TaskPanel_StatusLabel: '状态',
    TaskPanel_PriorityLabel: '优先级',
    TaskPanel_PercentCompleteLabel: '完成百分比：{percent}%',
    TaskPanel_AssignedToLabel: '负责人',
    TaskPanel_AssignedToPlaceholder: '搜索人员…',
    TaskPanel_PhaseLabel: '阶段',
    TaskPanel_PhasePlaceholder: '输入阶段名称',
    TaskPanel_PhaseHint: '在甘特图和列表视图中将任务分组显示。',
    TaskPanel_MilestoneLabel: '里程碑',
    TaskPanel_MilestoneOnText: '是',
    TaskPanel_MilestoneOffText: '否',
    TaskPanel_CustomBarColorLabel: '自定义条形颜色',
    TaskPanel_CustomBarColorOptionalSuffix: '（可选）',
    TaskPanel_AutoColorHint: '根据状态/优先级/阶段设置自动配色。',
    TaskPanel_NotesLabel: '备注',
    TaskPanel_NotesPlaceholder: '输入备注',
    TaskPanel_ParentTaskLabel: '父任务',
    TaskPanel_ParentTaskNone: '（无）',
    TaskPanel_ParentTaskHasChildrenHint: '此任务包含子任务，不能再设置自己的父任务。',
    TaskPanel_ParentTaskHint: '将此任务作为子任务嵌套在另一任务下。',
    TaskPanel_DependsOnLabel: '依赖于',
    TaskPanel_RemoveDependencyTitle: '移除对“{taskTitle}”的依赖',
    TaskPanel_AddDependencyPlaceholder: '添加依赖项…',
    TaskPanel_SelectATaskOption: '选择一个任务…',
    TaskPanel_DependsOnHint: '在这些任务完成之前，此任务无法开始。',
    TaskPanel_SavingLabel: '正在保存…',
    TaskPanel_CreatingLabel: '正在创建…',
    TaskPanel_SaveChangesButton: '保存更改',
    TaskPanel_CreateTaskButton: '创建任务',
    TaskPanel_CancelButton: '取消',
    TaskPanel_DismissAriaLabel: '关闭',
    TaskPanel_DiscardUnsavedChangesConfirm: '放弃未保存的更改？',
    TaskPanel_SaveFallbackError: '无法保存该任务。',

    // ── Project panel ──
    ProjectPanel_EditHeader: '编辑项目',
    ProjectPanel_NewHeader: '新建项目',
    ProjectPanel_ProjectNameLabel: '项目名称',
    ProjectPanel_ProjectNamePlaceholder: '输入项目名称',
    ProjectPanel_ProjectNameRequired: '项目名称为必填项',
    ProjectPanel_DescriptionLabel: '描述',
    ProjectPanel_DescriptionPlaceholder: '输入描述',
    ProjectPanel_ProjectColorLabel: '项目颜色',
    ProjectPanel_StatusLabel: '状态',
    ProjectPanel_StartDateLabel: '开始日期',
    ProjectPanel_DueDateLabel: '截止日期',
    ProjectPanel_DueDateError: '截止日期必须晚于或等于开始日期',
    ProjectPanel_WhatHappensNextTitle: '接下来会发生什么？',
    ProjectPanel_WhatHappensNextBody: '项目创建完成后，您就可以添加任务、设置阶段并跟踪进度。',
    ProjectPanel_SavingLabel: '正在保存…',
    ProjectPanel_CreatingLabel: '正在创建…',
    ProjectPanel_SaveChangesButton: '保存更改',
    ProjectPanel_CreateProjectButton: '创建项目',
    ProjectPanel_CancelButton: '取消',
    ProjectPanel_DismissAriaLabel: '关闭',
    ProjectPanel_DiscardUnsavedChangesConfirm: '放弃未保存的更改？',
    ProjectPanel_SaveFallbackError: '无法保存该项目。',

    // ── Import panel ──
    ImportPanel_SourceExcelTitle: 'Excel / CSV 文件',
    ImportPanel_SourceExcelSubtitle: '从电子表格导入任务',
    ImportPanel_SourcePlannerTitle: 'Microsoft Planner',
    ImportPanel_SourcePlannerSubtitle: '从 Planner 计划导入任务',
    ImportPanel_ClickToBrowse: '点击浏览',
    ImportPanel_DragDropSuffix: '或拖放文件',
    ImportPanel_SupportedExtensions: '支持 .xlsx、.xls、.csv',
    ImportPanel_RowsColsSummary: '检测到 {rows} 行，{cols} 列',
    ImportPanel_LoadingPlannerPlans: '正在加载 Planner 计划…',
    ImportPanel_PlannerLoadError: '无法加载 Planner 计划。',
    ImportPanel_PlannerPermissionsHintPrefix: '请确保您有权访问 Planner，并且 ',
    ImportPanel_PlannerPermissionsHintEmphasis: 'Tasks by Planner and To Do',
    ImportPanel_PlannerPermissionsHintSuffix: ' 已在此站点中可用。',
    ImportPanel_NoPlannerPlansFoundTitle: '未找到 Planner 计划',
    ImportPanel_NoPlannerPlansFoundBody: '您可能没有访问任何 Planner 计划的权限，或此账户下不存在任何计划。',
    ImportPanel_TaskCountFoundIn: '在“{planName}”中找到 {count} 个任务',
    ImportPanel_ProjectDetailsIntroPrefix: '正在导入到 ',
    ImportPanel_ProjectDetailsIntroSuffix: '。请查看下方的项目详细信息。',
    ImportPanel_ProjectNameLabel: '项目名称',
    ImportPanel_DescriptionLabel: '描述',
    ImportPanel_StatusLabel: '状态',
    ImportPanel_ColorLabel: '颜色',
    ImportPanel_MapIntro: '将文件中的列映射到任务字段。',
    ImportPanel_CreatingProjectStatus: '正在创建项目…',
    ImportPanel_ImportingTasksStatus: '正在导入任务…',
    ImportPanel_ProgressLabel: '{done} / {total}',
    ImportPanel_CouldNotCreateProject: '无法创建该项目。',
    ImportPanel_ImportCompletedWithErrors: '导入已完成，但有 {count} 个错误。',
    ImportPanel_ProjectCreatedSuccess: '项目创建成功！',
    ImportPanel_ImportSuccessful: '导入成功！',
    ImportPanel_TasksAddedTo: '已将 {count} 个任务添加到“{projectName}”',
    ImportPanel_FailedRowsLabel: '失败的行：',
    ImportPanel_CloseButton: '关闭',
    ImportPanel_OpenProjectButton: '打开项目',
    ImportPanel_ViewImportedTasksButton: '查看已导入的任务',
    ImportPanel_NextMapColumnsButton: '下一步：映射列',
    ImportPanel_ImportNTasksButton: '导入 {count} 个任务',
    ImportPanel_BackButton: '返回',
    ImportPanel_CancelButton: '取消',
    ImportPanel_NextButton: '下一步',
    ImportPanel_StepSource: '来源',
    ImportPanel_StepProject: '项目',
    ImportPanel_StepMap: '映射',
    ImportPanel_StepImport: '导入',
    ImportPanel_StepDone: '完成',
    ImportPanel_ImportAsNewProjectHeader: '将文件导入为新项目',
    ImportPanel_ImportIntoProjectHeader: '将任务导入到 {projectName}',
    ImportPanel_CouldNotParseFile: '无法解析该文件。',
    ImportPanel_CouldNotLoadPlannerTasks: '无法从此计划加载任务。',
    ImportPanel_CouldNotCreateProjectDetail: '无法创建项目：{detail}',
    ImportPanel_CouldNotLinkDependencies: '无法关联依赖项：{detail}',
    ImportPanel_UnknownError: '未知错误',

    // ── Column mapper (import) ──
    ColumnMapper_TaskNameRequiredBanner: '必须先映射任务名称才能继续。',
    ColumnMapper_SkippedColumnsBanner: '将跳过 {count} 列。',
    ColumnMapper_SourceColumnHeader: '源列',
    ColumnMapper_TargetFieldHeader: '目标字段',
    ColumnMapper_StatusHeader: '状态',
    ColumnMapper_SkippedBadge: '已跳过',
    ColumnMapper_AutoMappedBadge: '已自动映射',
    ColumnMapper_SetBadge: '已设置',
    ColumnMapper_PreviewTitle: '预览：{columnName}',
    ColumnMapper_EmptyCellDash: '—',

    // ── Import field display names / ImportService ──
    ImportField_TaskName: '任务名称',
    ImportField_StartDate: '开始日期',
    ImportField_DueDate: '截止日期',
    ImportField_Status: '状态',
    ImportField_Priority: '优先级',
    ImportField_AssignedTo: '负责人',
    ImportField_AssignedToEmail: '负责人电子邮件',
    ImportField_PercentComplete: '完成百分比',
    ImportField_Phase: '阶段',
    ImportField_Description: '描述',
    ImportField_Notes: '备注',
    ImportField_IsMilestone: '是否为里程碑',
    ImportField_Dependencies: '依赖项',
    ImportField_SkipColumn: '（跳过此列）',
    ImportService_EmptyFileError: '文件似乎为空或不包含任何数据行。',
    ImportService_ReadErrorDetail: '无法读取文件：{detail}。',
    ImportService_FileReadError: '文件读取错误。',
    ImportService_RowError: '第 {rowNum} 行（“{title}”）：{error}',
    ImportService_AmbiguousDependency: '依赖项“{name}”匹配到多个任务标题 — 已跳过。',
    ImportService_LinkDependencyError: '无法为任务 {taskId} 关联依赖项：{error}',

    // ── Health labels (shared: healthUtils.ts and ExportService.ts both use this set; also replaces the duplicated Export_PortfolioHealthLabel* keys) ──
    Health_Done: '已完成',
    Health_OnTrack: '进展顺利',
    Health_AtRisk: '存在风险',
    Health_Overdue: '已逾期',

    // ── Status / Priority display labels (DISPLAY-ONLY — stored SharePoint Choice values remain unchanged/English) ──
    Status_NotStarted: '未开始',
    Status_InProgress: '进行中',
    Status_Completed: '已完成',
    Status_OnHold: '已暂停',
    Status_Cancelled: '已取消',
    Priority_Critical: '紧急',
    Priority_High: '高',
    Priority_Medium: '中',
    Priority_Low: '低',
    ProjectStatus_Planning: '规划中',
    ProjectStatus_Active: '进行中',
    ProjectStatus_OnHold: '已暂停',
    ProjectStatus_Completed: '已完成',
    ProjectStatus_Cancelled: '已取消',

    // ── Shell (SmartGantt.tsx) ──
    SmartGantt_LoadingProjects: '正在加载项目…',
    SmartGantt_UnableToLoad: '无法加载',
    SmartGantt_RetryButton: '重试',
    SmartGantt_NoProjectsYet: '暂无项目',
    SmartGantt_NoProjectsSubtitle: '创建您的第一个项目以开始使用。',
    SmartGantt_CreateFirstProjectButton: '+ 创建第一个项目',
    SmartGantt_ImportFromExcelButton: '📥 从 Excel 导入',
    SmartGantt_LoadingTasks: '正在加载任务…',
    SmartGantt_DismissAriaLabel: '关闭',
    SmartGantt_DeleteTaskDialogTitle: '删除任务',
    SmartGantt_DeleteTaskDialogSubtext: '确定要删除“{taskTitle}”吗？此操作无法撤消。',
    SmartGantt_DeleteButton: '删除',
    SmartGantt_CancelButton: '取消',
    SmartGantt_ArchiveProjectDialogTitle: '归档项目',
    SmartGantt_ArchiveProjectDialogSubtext: '要归档“{projectTitle}”吗？您稍后可以取消归档。',
    SmartGantt_ArchiveButton: '归档',
    SmartGantt_SendToRecycleBinDialogTitle: '发送到回收站',
    SmartGantt_SendToRecycleBinDialogSubtext: '要将“{projectTitle}”发送到站点回收站吗？',
    SmartGantt_SendToRecycleBinButton: '发送到回收站',
    SmartGantt_FailedLoadProjects: '加载项目失败。请检查站点权限。',
    SmartGantt_FailedLoadTasks: '无法加载此项目的任务。',
    SmartGantt_FailedLoadPortfolioStats: '无法加载项目组合统计信息。',
    SmartGantt_CouldNotSaveProject: '无法保存该项目：{message}',
    SmartGantt_CouldNotDeleteProject: '无法删除该项目：{message}',
    SmartGantt_CouldNotArchiveProject: '无法归档该项目：{message}',
    SmartGantt_CouldNotUnarchiveProject: '无法取消归档该项目：{message}',
    SmartGantt_CouldNotSaveTask: '无法保存该任务：{message}',
    SmartGantt_CouldNotDeleteTask: '无法删除该任务：{message}',
    SmartGantt_ImageExportFailed: '图片导出失败：{message}',
    SmartGantt_PowerPointExportFailed: 'PowerPoint 导出失败：{message}',
    SmartGantt_PortfolioExportFailed: '项目组合导出失败：{message}',
    SmartGantt_CouldNotUpdateTask: '无法更新该任务：{message}',

    // ── Common ──
    ColorSwatch_AutoColorAriaLabel: '自动配色',
    ColorSwatch_CustomColorAriaLabel: '自定义颜色',
    ColorSwatch_PickCustomColorTitle: '选择自定义颜色',

    // ── Export (Excel / PowerPoint) ──
    Export_ColTaskName: '任务名称',
    Export_ColPhase: '阶段',
    Export_ColStartDate: '开始日期',
    Export_ColDueDate: '截止日期',
    Export_ColStatus: '状态',
    Export_ColPriority: '优先级',
    Export_ColAssignedTo: '负责人',
    Export_ColAssignedToEmail: '负责人电子邮件',
    Export_ColPercentComplete: '完成百分比',
    Export_ColIsMilestone: '是否为里程碑',
    Export_ColDescription: '描述',
    Export_ColNotes: '备注',
    Export_Yes: '是',
    Export_No: '否',
    Export_SheetNameTasks: '任务',
    Export_ExcelFileSuffix: ' - 任务.xlsx',
    Export_TaskNameColumnLabel: '任务名称',
    Export_ExportedDateLabel: '导出日期：{date}',
    Export_ProjectReportLabel: '项目报告',
    Export_StatusLine: '状态：{status}',
    Export_DateRangeSeparator: ' 至 ',
    Export_ProjectManagerLine: '项目经理：{name}',
    Export_GeneratedDateLine: '生成日期：{date}',
    Export_ProjectSummaryTitle: '项目摘要',
    Export_StatTotalTasks: '任务总数',
    Export_StatCompleted: '已完成',
    Export_StatInProgress: '进行中',
    Export_StatOnHold: '已暂停',
    Export_StatNotStarted: '未开始',
    Export_OverallProgressLine: '总体进度',
    Export_OverallProgressPercent: '{percent}%',
    Export_StatusBreakdownTitle: '状态分布',
    Export_StatusBreakdownRow: '{status}：{count}（{percent}%）',
    Export_GanttTimelineTitle: '甘特图时间线',
    Export_SummaryRecentActivityTitle: '近期活动',
    Export_ProjectOverviewLabel: '项目概览',
    Export_DetailStatusLabel: '状态',
    Export_DetailStartDateLabel: '开始日期',
    Export_DetailDueDateLabel: '截止日期',
    Export_DetailProjectManagerLabel: '项目经理',
    Export_Past7DaysLabel: '过去 7 天',
    Export_NoActivityMessage: '暂无近期活动。',
    Export_CompletedThisWeekHeader: '本周已完成 ({count})',
    Export_NewBadge: '新  ',
    Export_CompletedPercentLine: '已完成 {percent}%',
    Export_MoreItemsSuffix: '+ 还有 {count} 项',
    Export_InProgressUpdatedHeader: '进行中 / 已更新',
    Export_StatusPercentLine: '{status} — {percent}%',
    Export_PortfolioReportLabel: '项目组合报告',
    Export_PortfolioOverviewTitle: '项目组合概览',
    Export_ProjectsCountLine: '{count} 个项目',
    Export_HealthSummaryOnTrack: '{count} 个进展顺利',
    Export_HealthSummaryAtRisk: '{count} 个存在风险',
    Export_HealthSummaryOverdue: '{count} 个已逾期',
    Export_ProjectsSummaryHeader: '项目摘要',
    Export_TableProject: '项目',
    Export_TableStatus: '状态',
    Export_TableHealth: '健康状况',
    Export_TableTotal: '总计',
    Export_TableDone: '已完成',
    Export_TableActive: '进行中',
    Export_TableAtRisk: '存在风险',
    Export_TableOverdue: '已逾期',
    Export_TablePctDone: '完成百分比',
    Export_TableDueDate: '截止日期',
    Export_PortfolioSummaryFileName: '项目组合摘要.xlsx',
    Export_PortfolioReportFileName: '项目组合报告.pptx',
    Export_ProjectReportFileName: '{projectName} 报告.pptx',
    Export_UnavailableLabel: '不可用',
    Export_SheetNamePortfolio: '组合',
    Export_ColStart: '开始日期',
    Export_ColDue: '截止日期',
    Export_ImageGenerationFailed: '无法生成图像——图表可能过大，无法导出为图像。',
    Export_DrawingContextFailed: '无法为导出创建绘图上下文。',
    Export_SvgRenderFailed: 'SVG 渲染失败',

    // ── Added in v1.5 review ──
    Svc_TooManyDependencies: '此任务的依赖项过多，无法保存（上限约为 60 个）。请删除一些后重试。',
    Svc_TaskChangedByOthers: '自您加载此任务以来，其他人已对其进行了更改。请刷新后重试。',
    Svc_ProjectChangedByOthers: '自您打开此项目以来，其他人已对其进行了更改。请刷新后重试。',
    Svc_ColumnCreateFailed: '无法在新任务列表中创建 {count} 个列：{detail}',
    Svc_BaselineUnavailable: '由于无法添加基线列，此项目无法使用基线（您可能需要编辑该列表的权限）。',
    Svc_SubtaskReassignFailed: '删除此任务之前，无法重新分配其子任务：{detail}',
    Svc_UnresolvedDependency: '第 {row} 行（“{title}”）：依赖项“{name}”无法与导入的任务匹配。',
    Svc_SelfDependency: '第 {row} 行（“{title}”）：依赖项“{name}”指向任务自身，已跳过。',
    Svc_ColId: 'ID',
    Svc_ColDependencies: '依赖项',
    Svc_ColBaselineStart: '基线开始日期',
    Svc_ColBaselineDue: '基线截止日期',
    Svc_CsvFileSuffix: ' - Tasks.csv',
    Svc_IcsFileSuffix: ' - Milestones.ics',
    Svc_PortfolioCsvFileName: 'Portfolio Summary.csv',
    Svc_PP_DisplayGroup: '默认值',
    Svc_PP_DefaultView: '默认视图',
    Svc_PP_ViewGantt: '甘特图',
    Svc_PP_ViewList: '列表',
    Svc_PP_ViewKanban: '看板',
    Svc_PP_ViewDashboard: '仪表板',
    Svc_PP_ViewPortfolio: '项目组合',
    Svc_PP_DefaultZoom: '默认缩放',
    Svc_PP_ZoomDay: '日',
    Svc_PP_ZoomWeek: '周',
    Svc_PP_ZoomMonth: '月',
    Svc_PP_ZoomQuarter: '季度',
    Svc_PP_CalendarGroup: '工作日历',
    Svc_PP_DaySun: '星期日为工作日',
    Svc_PP_DayMon: '星期一为工作日',
    Svc_PP_DayTue: '星期二为工作日',
    Svc_PP_DayWed: '星期三为工作日',
    Svc_PP_DayThu: '星期四为工作日',
    Svc_PP_DayFri: '星期五为工作日',
    Svc_PP_DaySat: '星期六为工作日',
    Svc_PP_Holidays: '节假日（非工作日期）',
    Svc_PP_HolidaysHint: '每行一个日期，格式为 yyyy-MM-dd（例如 2026-12-25）。',
    Gantt_TimelineAriaLabel: '任务时间线',
    Gantt_DragLabel: '{start} → {end}（{days} 天）',
    Gantt_KeyboardMoveAnnouncement: '{taskTitle}：{startDate} 至 {dueDate}',
    Gantt_KeyboardHint: '按 Enter 键打开任务。左右方向键可将任务移动一个工作日。按住 Shift 并使用方向键可更改其结束日期。',
    Gantt_ParentCycleTooltip: '此任务属于循环的父任务与子任务链，因此显示在顶层',
    Gantt_CollapseAll: '折叠所有阶段',
    Gantt_ExpandAll: '展开所有阶段',
    Gantt_BaselineTooltip: '基线：{start} → {due}',
    Gantt_VarianceTooltip: '完成日期偏差：与基线相差 {days} 天',
    Gantt_LinkHandleTitle: '拖到另一个任务上以创建依赖关系',
    Toolbar_FitToProject: '适应',
    Toolbar_FitToProjectTitle: '缩放以适应整个项目',
    Toolbar_UndoTitle: '撤消 (Ctrl+Z)',
    Toolbar_RedoTitle: '重做 (Ctrl+Y)',
    Toolbar_ExportCsv: '📄 将任务导出为 CSV',
    Toolbar_ExportIcs: '📅 导出里程碑 (iCal)',
    Toolbar_Print: '🖨 打印 / 另存为 PDF',
    Toolbar_SetBaseline: '📐 设置基线…',
    Toolbar_CopyLink: '🔗 复制链接',
    Toolbar_CopyLinkTitle: '复制指向此视图的链接（项目、视图、缩放和筛选器）',
    App_UndoButton: '撤消',
    App_Undone: '已撤消更改。',
    App_Redone: '已重做更改。',
    App_DependentsMovedOne: '已移动 1 个后续任务。',
    App_DependentsMovedMany: '已移动 {count} 个后续任务。',
    App_TaskConflict: '此任务已被其他人更改。已重新加载最新任务，请查看后重试。',
    App_DependencyCycle: '该链接会造成循环依赖。',
    App_DependencyExists: '这些任务已经链接。',
    App_LinkCopied: '链接已复制到剪贴板。',
    App_LinkCopyFailed: '无法复制链接：{message}',
    App_PopupBlocked: '打印窗口已被阻止。请允许此网站的弹出窗口后重试。',
    App_SetBaselineDialogTitle: '设置基线',
    App_SetBaselineDialogSubtext: '是否将全部 {count} 个任务当前的开始日期和截止日期保存为基线？现有基线将被替换。',
    App_SetBaselineButton: '设置基线',
    App_BaselineSaved: '基线已保存。',
    App_BaselineFailed: '无法保存基线：{message}',
    App_CsvExportFailed: 'CSV 导出失败：{message}',
    App_IcsExportFailed: '日历导出失败：{message}',
    App_BulkDeleteDialogTitle: '删除任务',
    App_BulkDeleteDialogSubtext: '确定要删除 {count} 个任务吗？此操作无法撤消。',
    Common_PeoplePicker_ClearAriaLabel: '清除',
    Common_PeoplePicker_DirectoryHeader: '目录中的用户',
    Common_PeoplePicker_EmailLabel: '电子邮件（可选）',
    Common_PeoplePicker_EmailPlaceholder: 'name@company.com',
    Common_PeoplePicker_ExternalHint: '不在目录中。将保存为自由文本。',
    Common_PeoplePicker_InvalidEmail: '请输入有效的电子邮件地址。',
    Common_PeoplePicker_ListAriaLabel: '用户建议',
    Common_PeoplePicker_RecentHeader: '最近使用',
    Common_PeoplePicker_ResultsAnnouncement: '有 {count} 条建议',
    Common_PeoplePicker_Searching: '正在搜索…',
    Common_PeoplePicker_UseExternal: '使用“{name}”（外部 / 不在目录中）',
    Import_Mapper_PreviewFirstRows: '预览（前 {count} 行）',
    Import_Mapper_RequiredLegend: '必填字段',
    Import_Mapper_RequiredMarkerLabel: '必填',
    Import_Mapper_SelectAriaLabel: '列 {columnName} 的目标字段',
    Import_Panel_DateOrderAuto: '自动检测',
    Import_Panel_DateOrderDMY: '日/月/年 (31/12/2026)',
    Import_Panel_DateOrderDetected: '从您的文件中检测到：{order}。',
    Import_Panel_DateOrderHint: '适用于以数字书写的日期，例如 03/04/2026。',
    Import_Panel_DateOrderLabel: '日期顺序',
    Import_Panel_DateOrderMDY: '月/日/年 (12/31/2026)',
    Import_Panel_DropZoneAriaLabel: '选择要导入的文件。按 Enter 键浏览。',
    Import_Panel_DropZoneChangeAriaLabel: '已选择文件 {fileName}。按 Enter 键选择其他文件。',
    Import_Panel_FailedCount: '{count} 个失败',
    Import_Panel_NewProjectIntroMany: '将创建一个新项目，并将全部 {count} 个任务导入其中。导入后您可以随时更改这些详细信息。',
    Import_Panel_NewProjectIntroOne: '将创建一个新项目，并将 {count} 个任务导入其中。导入后您可以随时更改这些详细信息。',
    Import_Panel_PlanAriaLabel: '{planName}，{groupName}',
    Import_Panel_ProblemEndBeforeStart: '截止日期早于开始日期',
    Import_Panel_ProblemInvalidDueDate: '截止日期“{value}”不是有效日期',
    Import_Panel_ProblemInvalidStartDate: '开始日期“{value}”不是有效日期',
    Import_Panel_ProblemMissingTitle: '缺少任务名称',
    Import_Panel_ProgressLabelWithPercent: '{done} / {total}（{percent}%）',
    Import_Panel_SkipInvalidRows: '跳过有问题的行',
    Import_Panel_SuccessWithWarningsMany: '导入成功，有 {count} 条警告。',
    Import_Panel_SuccessWithWarningsOne: '导入成功，有 {count} 条警告。',
    Import_Panel_ValidationHeader: '有问题的行',
    Import_Panel_ValidationMore: '…以及另外 {count} 项',
    Import_Panel_ValidationRow: '第 {rowNum} 行：{problem}',
    Import_Panel_ValidationSummaryMany: '{count} 行有问题',
    Import_Panel_ValidationSummaryOne: '{count} 行有问题',
    Import_Panel_WarningsLabel: '警告（{count}）：',
    Panel_Project_ManagerLabel: '项目经理',
    Panel_Project_ManagerPlaceholder: '搜索用户或输入姓名…',
    Panel_Task_BaselineDueLabel: '基线完成日期',
    Panel_Task_BaselineHeader: '基线',
    Panel_Task_BaselineStartLabel: '基线开始日期',
    Panel_Task_DepTypeFF: '完成到完成 (FF)',
    Panel_Task_DepTypeFS: '完成到开始 (FS)',
    Panel_Task_DepTypeSF: '开始到完成 (SF)',
    Panel_Task_DepTypeSS: '开始到开始 (SS)',
    Panel_Task_LagAriaLabel: '{taskTitle} 的延隔时间（工作日）',
    Panel_Task_LagHint: '延隔时间以工作日计。使用负数表示提前量。',
    Panel_Task_LinkTypeAriaLabel: '{taskTitle} 的链接类型',
    Panel_Task_VarianceEarlier: '提前 {days} 个工作日',
    Panel_Task_VarianceLater: '延后 {days} 个工作日',
    Panel_Task_VarianceOnBaseline: '符合基线',
    View_Dashboard_BurndownActual: '实际',
    View_Dashboard_BurndownAria: '燃尽图：{total} 个任务中还剩 {remaining} 个',
    View_Dashboard_BurndownHeader: '燃尽（剩余任务）',
    View_Dashboard_BurndownIdeal: '理想',
    View_Dashboard_BurndownNoData: '带日期的任务不足，无法绘制燃尽图。',
    View_Dashboard_CriticalPathHeader: '关键路径  ({count})',
    View_Dashboard_PhaseDoneSummary: '已完成 {done}/{total}  •  {percent}%',
    View_Dashboard_TaskRowAriaLabel: '打开任务 {taskTitle}，{status}',
    View_Dashboard_WorkloadHeader: '按负责人统计的工作量',
    View_Dashboard_WorkloadOpen: '{count} 个未完成',
    View_Dashboard_WorkloadOverdue: '{count} 个已逾期',
    View_Kanban_AddTaskInColumnAriaLabel: '向 {column} 添加任务',
    View_Kanban_CollapseColumn: '折叠 {column} 列',
    View_Kanban_ExpandColumn: '展开 {column} 列',
    View_Kanban_LaneHeader: '{name} ({count})',
    View_Kanban_LaneNoPhase: '无阶段',
    View_Kanban_LaneUnassigned: '未分配',
    View_Kanban_LanesAssignee: '负责人',
    View_Kanban_LanesNone: '无',
    View_Kanban_LanesPhase: '阶段',
    View_Kanban_SwimlanesLabel: '泳道',
    View_Kanban_WipEditTitle: '设置 {column} 的在制品 (WIP) 限制（0 表示无限制）',
    View_Kanban_WipExceededTitle: '已超出 WIP 限制：{limit} 个中的 {count} 个',
    View_Kanban_WipInputAriaLabel: '{column} 的 WIP 限制',
    View_Kanban_WipLabel: 'WIP {count}/{limit}',
    View_Kanban_WipSet: 'WIP',
    View_List_BulkAssignApply: '分配',
    View_List_BulkAssigneePlaceholder: '分配给…',
    View_List_BulkBarAriaLabel: '所选任务的批量操作',
    View_List_BulkClear: '清除选择',
    View_List_BulkDelete: '删除所选项',
    View_List_BulkPercentApply: '设置 %',
    View_List_BulkPercentPlaceholder: '完成百分比',
    View_List_BulkPriorityPlaceholder: '设置优先级…',
    View_List_BulkSelectedCount: '已选择 {count} 项',
    View_List_BulkStatusPlaceholder: '设置状态…',
    View_List_ExportCsv: '导出 CSV',
    View_List_NonWorkingDay: '非工作日',
    View_List_SelectAllAriaLabel: '选择所有任务',
    View_List_SelectRowAriaLabel: '选择 {taskTitle}',
    View_Portfolio_CardAriaLabel: '打开项目 {projectName}，{status}',
    View_Portfolio_ClearFilters: '清除筛选器',
    View_Portfolio_FilteredCount: '{total} 个项目中的 {shown} 个',
    View_Portfolio_HideDone: '隐藏已完成 / 已取消',
    View_Portfolio_NoMatches: '没有与筛选条件匹配的项目。',
    View_Portfolio_ProjectCountMany: '{count} 个项目',
    View_Portfolio_ProjectCountOne: '{count} 个项目',
    View_Portfolio_SearchAriaLabel: '搜索项目',
    View_Portfolio_SearchPlaceholder: '搜索项目…',
    Import_Panel_CopyDetails: '复制详细信息',
    Import_Panel_Copied: '已复制',
  };
});
