define([], function () {
  return {
    // ── Property pane ──
    PropertyPane_HeaderDescription: 'Smart Gantt Chart 設定',
    PropertyPane_GeneralGroupName: '一般',
    PropertyPane_TitleFieldLabel: 'Web 元件標題',
    WebPart_DefaultTitle: 'Smart Gantt Chart',

    // ── Toolbar ──
    Toolbar_ViewDashboard: '儀表板',
    Toolbar_ViewList: '清單',
    Toolbar_ViewGantt: '甘特圖',
    Toolbar_ViewKanban: '看板',
    Toolbar_ZoomDay: '日',
    Toolbar_ZoomWeek: '週',
    Toolbar_ZoomMonth: '月',
    Toolbar_ZoomQuarter: '季',
    Toolbar_SelectProjectAriaLabel: '選取專案',
    Toolbar_PortfolioLabel: '專案組合',
    Toolbar_SelectAProject: '選取一個專案',
    Toolbar_AllProjectsSubtext: '所有專案',
    Toolbar_NoProjectsYet: '尚無專案',
    Toolbar_ArchivedBadge: '已封存',
    Toolbar_ShowArchivedProjects: '顯示已封存的專案',
    Toolbar_NewProject: '+ 新增專案',
    Toolbar_ImportFileAsNewProject: '📥 將檔案匯入為新專案…',
    Toolbar_AddTask: '+ 新增工作',
    Toolbar_EditProject: '編輯專案',
    Toolbar_OptionsButton: '⚙ 選項',
    Toolbar_MoreOptionsTitle: '更多選項',
    Toolbar_ExportToExcel: '📊 匯出至 Excel',
    Toolbar_ExportToPowerPoint: '📑 匯出至 PowerPoint',
    Toolbar_ScrollToTodayTitle: '捲動至今天',
    Toolbar_TodayButton: '◉ 今天',
    Toolbar_ImportTasks: '📥 匯入工作…',
    Toolbar_ExportAsImage: '🖼 匯出為圖片 (PNG)',
    Toolbar_UnarchiveProject: '📂 取消封存專案',
    Toolbar_ArchiveProject: '🗄️ 封存專案',
    Toolbar_SendToRecycleBin: '🗑️ 傳送至資源回收筒',

    // ── Filter bar ──
    FilterBar_ClearOption: '清除',
    FilterBar_DueAny: '任何到期日',
    FilterBar_DueOverdue: '已逾期',
    FilterBar_DueToday: '今天到期',
    FilterBar_DueWeek: '7 天內到期',
    FilterBar_SearchPlaceholder: '搜尋工作…',
    FilterBar_SearchAriaLabel: '搜尋工作',
    FilterBar_StatusChipLabel: '狀態',
    FilterBar_PriorityChipLabel: '優先順序',
    FilterBar_AssigneeChipLabel: '負責人',
    FilterBar_PhaseChipLabel: '階段',
    FilterBar_DueDateAriaLabel: '依到期日篩選',
    FilterBar_MatchCount: '{matchCount} / {totalCount}',
    FilterBar_ClearFilters: '✕ 清除篩選條件',
    FilterBar_ChipLabelWithCount: '{label} ({count}) ▾',
    FilterBar_ChipLabelNoCount: '{label} ▾',

    // ── Gantt view ──
    Gantt_TaskColumnHeader: '工作',
    Gantt_DurationColumnHeader: '工期',
    Gantt_AddTaskButton: '+ 新增工作',
    Gantt_EmptyTitle: '尚無工作',
    Gantt_EmptySubtitle: '新增工作即可在甘特圖中檢視。',
    Gantt_AddFirstTask: '+ 新增第一項工作',
    Gantt_ImportTasksButton: '📥 匯入工作',
    Gantt_EditTitle: '編輯',
    Gantt_DeleteTitle: '刪除',
    Gantt_EditTaskAriaLabel: '編輯工作 {taskTitle}',
    Gantt_DeleteTaskAriaLabel: '刪除工作 {taskTitle}',
    Gantt_ExpandPhaseAriaLabel: '{action}階段 {phase}',
    Gantt_ExpandAction: '展開',
    Gantt_CollapseAction: '摺疊',
    Gantt_DependencyViolationTooltip: '在所有相依項目完成前即已開始',
    Gantt_MilestoneAriaLabel: '{taskTitle}，里程碑，{date}',
    Gantt_BarAriaLabel: '{taskTitle}，{startDate} 至 {dueDate}，已完成 {percent}%',
    Gantt_PercentCompleteTooltip: '已完成 {value}%',

    // ── Gantt options/settings panel ──
    GanttSettings_PanelHeader: '⚙ 選項',
    GanttSettings_ColorCodingSection: '色彩編碼',
    GanttSettings_ByStatus: '依狀態',
    GanttSettings_ByPriority: '依優先順序',
    GanttSettings_ByPhase: '依階段',
    GanttSettings_ByHealth: '依健康狀態',
    GanttSettings_HeaderColorSection: '標題顏色',
    GanttSettings_ThemeDark: '深色',
    GanttSettings_ThemeNavy: '海軍藍',
    GanttSettings_ThemeTeal: '藍綠色',
    GanttSettings_ThemePurple: '紫色',
    GanttSettings_ThemeLight: '淺色',
    GanttSettings_HeaderLabelsSection: '標題標籤',
    GanttSettings_WeekLabelDates: '日期',
    GanttSettings_WeekLabelDatesDesc: '6月3日、6月10日…',
    GanttSettings_WeekLabelProject: '專案週次',
    GanttSettings_WeekLabelProjectDesc: 'W1、W2…',
    GanttSettings_WeekLabelIso: '日曆週次',
    GanttSettings_WeekLabelIsoDesc: 'W23、W24…',
    GanttSettings_ProjectWeeksHint: '第 1 週從您最早工作所在週的星期一開始 — 非常適合用於簡報。',
    GanttSettings_BarStyleSection: '長條樣式',
    GanttSettings_BarStyleGradient: '漸層',
    GanttSettings_BarStyleFlat: '平面',
    GanttSettings_RowHeightSection: '列高',
    GanttSettings_HeightCompact: '精簡',
    GanttSettings_HeightNormal: '一般',
    GanttSettings_HeightSpacious: '寬鬆',
    GanttSettings_ShowHideSection: '顯示 / 隱藏',
    GanttSettings_WeekendShading: '週末網底',
    GanttSettings_DependencyArrows: '相依關係箭號',
    GanttSettings_CriticalPathAlwaysVisible: '關鍵路徑一律顯示',
    GanttSettings_AllOthersOnHoverOnly: '其他項目僅在滑鼠停留時顯示',
    GanttSettings_CriticalPathHighlight: '關鍵路徑醒目提示',
    GanttSettings_ProgressPercentOnBars: '在長條圖上顯示進度百分比',
    GanttSettings_AssigneeNameOnBars: '在長條圖上顯示負責人姓名',
    GanttSettings_HealthStatusBadges: '健康狀態徽章',

    // ── List view ──
    ListView_ColTaskName: '工作名稱',
    ListView_ColStatus: '狀態',
    ListView_ColHealth: '健康狀態',
    ListView_ColPriority: '優先順序',
    ListView_ColStart: '開始日期',
    ListView_ColDue: '到期日',
    ListView_ColAssignedTo: '負責人',
    ListView_ColProgress: '進度',
    ListView_ColPhase: '階段',
    ListView_ColPredecessors: '前置工作',
    ListView_EmptyTitle: '尚無工作',
    ListView_AddFirstTask: '+ 新增第一項工作',
    ListView_AddTaskRow: '+ 新增工作',
    ListView_Unassigned: '未指派',
    ListView_DependencyViolationTooltip: '在所有相依項目完成前即已開始',
    ListView_StatusAriaLabel: '{taskTitle} 的狀態',
    ListView_PriorityAriaLabel: '{taskTitle} 的優先順序',
    ListView_EditTaskAriaLabel: '編輯工作 {taskTitle}',
    ListView_DeleteTaskAriaLabel: '刪除工作 {taskTitle}',
    ListView_EditTitle: '編輯',
    ListView_DeleteTitle: '刪除',

    // ── Kanban view ──
    Kanban_ColumnNotStarted: '未開始',
    Kanban_ColumnInProgress: '進行中',
    Kanban_ColumnOnHold: '已暫停',
    Kanban_ColumnCompleted: '已完成',
    Kanban_ColumnCancelled: '已取消',
    Kanban_AddTaskButton: '+ 新增工作',
    Kanban_EditTitle: '編輯',
    Kanban_DeleteTitle: '刪除',
    Kanban_CardAriaLabel: '{taskTitle}，{status}。按 Enter 鍵編輯，按左右方向鍵變更狀態。',
    Kanban_EditTaskAriaLabel: '編輯工作 {taskTitle}',
    Kanban_DeleteTaskAriaLabel: '刪除工作 {taskTitle}',

    // ── Dashboard view ──
    Dashboard_TotalTasks: '工作總數',
    Dashboard_Completed: '已完成',
    Dashboard_InProgress: '進行中',
    Dashboard_OnHold: '已暫停',
    Dashboard_NotStarted: '未開始',
    Dashboard_Cancelled: '已取消',
    Dashboard_OverallProgress: '整體進度',
    Dashboard_ProjectManagerLabel: '專案經理：{name}',
    Dashboard_PhaseProgressHeader: '階段進度',
    Dashboard_StatusBreakdownHeader: '狀態分佈',
    Dashboard_PriorityBreakdownHeader: '優先順序分佈',
    Dashboard_PriorityCritical: '緊急',
    Dashboard_PriorityHigh: '高',
    Dashboard_PriorityMedium: '中',
    Dashboard_PriorityLow: '低',
    Dashboard_OverdueHeader: '已逾期 ({count})',
    Dashboard_DueNext14DaysHeader: '未來 14 天內到期 ({count})',
    Dashboard_CompletedThisWeekHeader: '本週已完成',
    Dashboard_UpdatedThisWeekHeader: '本週已更新',
    Dashboard_Today: '今天',
    Dashboard_Tomorrow: '明天',
    Dashboard_DaysLeft: '剩 {days} 天',
    Dashboard_EmptyTitle: '尚無工作',
    Dashboard_EmptySubtitle: '新增工作即可檢視您的專案儀表板。',
    Dashboard_AddTaskButton: '+ 新增工作',

    // ── Portfolio view ──
    Portfolio_ProjectCount: '{count} 個專案{plural}',
    Portfolio_OnTrackSummary: '{count} 個進度正常',
    Portfolio_AtRiskSummary: '{count} 個有風險',
    Portfolio_OverdueSummary: '{count} 個已逾期',
    Portfolio_DoneSummary: '{count} 個已完成',
    Portfolio_SortLabel: '排序：',
    Portfolio_SortAZ: 'A-Z',
    Portfolio_SortHealth: '健康狀態',
    Portfolio_SortStatus: '狀態',
    Portfolio_SortCompletion: '完成度',
    Portfolio_RefreshTitle: '重新整理',
    Portfolio_RefreshButton: '重新整理',
    Portfolio_LoadingStats: '正在載入統計資料…',
    Portfolio_EmptyTitle: '尚無專案',
    Portfolio_CreateFirstProject: '+ 建立第一個專案',
    Portfolio_StatsUnavailable: '統計資料無法使用',
    Portfolio_StatsUnavailableDetail: '無法載入此專案的統計資料。',
    Portfolio_OverallProgressLabel: '整體進度',
    Portfolio_TaskCountDone: '已完成',
    Portfolio_TaskCountActive: '進行中',
    Portfolio_TaskCountAtRisk: '有風險',
    Portfolio_TaskCountOverdue: '已逾期',
    Portfolio_ViewGanttLink: '檢視甘特圖 →',
    Portfolio_TodayTooltip: '今天',

    // ── Task panel ──
    TaskPanel_EditHeader: '編輯：{taskTitle}',
    TaskPanel_NewTaskHeader: '新增工作',
    TaskPanel_TabBasic: '基本資訊',
    TaskPanel_TabDetails: '詳細資料',
    TaskPanel_TabLinks: '關聯',
    TaskPanel_ProjectLabelPrefix: '專案：',
    TaskPanel_TaskNameLabel: '工作名稱',
    TaskPanel_TaskNamePlaceholder: '輸入工作名稱',
    TaskPanel_TaskNameRequired: '工作名稱為必填項目',
    TaskPanel_DescriptionLabel: '描述',
    TaskPanel_DescriptionPlaceholder: '輸入描述',
    TaskPanel_StartDateLabel: '開始日期',
    TaskPanel_DueDateLabel: '到期日',
    TaskPanel_DueDateError: '到期日必須晚於或等於開始日期',
    TaskPanel_StatusLabel: '狀態',
    TaskPanel_PriorityLabel: '優先順序',
    TaskPanel_PercentCompleteLabel: '完成百分比：{percent}%',
    TaskPanel_AssignedToLabel: '負責人',
    TaskPanel_AssignedToPlaceholder: '搜尋人員…',
    TaskPanel_PhaseLabel: '階段',
    TaskPanel_PhasePlaceholder: '輸入階段名稱',
    TaskPanel_PhaseHint: '在甘特圖與清單檢視中將工作分組顯示。',
    TaskPanel_MilestoneLabel: '里程碑',
    TaskPanel_MilestoneOnText: '是',
    TaskPanel_MilestoneOffText: '否',
    TaskPanel_CustomBarColorLabel: '自訂長條顏色',
    TaskPanel_CustomBarColorOptionalSuffix: '（選填）',
    TaskPanel_AutoColorHint: '依狀態／優先順序／階段設定自動配色。',
    TaskPanel_NotesLabel: '備註',
    TaskPanel_NotesPlaceholder: '輸入備註',
    TaskPanel_ParentTaskLabel: '父項工作',
    TaskPanel_ParentTaskNone: '（無）',
    TaskPanel_ParentTaskHasChildrenHint: '此工作包含子工作，無法再設定自己的父項工作。',
    TaskPanel_ParentTaskHint: '將此工作巢狀置於另一項工作之下作為子工作。',
    TaskPanel_DependsOnLabel: '相依於',
    TaskPanel_RemoveDependencyTitle: '移除對「{taskTitle}」的相依關係',
    TaskPanel_AddDependencyPlaceholder: '新增相依項目…',
    TaskPanel_SelectATaskOption: '選取一項工作…',
    TaskPanel_DependsOnHint: '在這些工作完成之前，此工作無法開始。',
    TaskPanel_SavingLabel: '正在儲存…',
    TaskPanel_CreatingLabel: '正在建立…',
    TaskPanel_SaveChangesButton: '儲存變更',
    TaskPanel_CreateTaskButton: '建立工作',
    TaskPanel_CancelButton: '取消',
    TaskPanel_DismissAriaLabel: '關閉',
    TaskPanel_DiscardUnsavedChangesConfirm: '要捨棄未儲存的變更嗎？',
    TaskPanel_SaveFallbackError: '無法儲存此工作。',

    // ── Project panel ──
    ProjectPanel_EditHeader: '編輯專案',
    ProjectPanel_NewHeader: '新增專案',
    ProjectPanel_ProjectNameLabel: '專案名稱',
    ProjectPanel_ProjectNamePlaceholder: '輸入專案名稱',
    ProjectPanel_ProjectNameRequired: '專案名稱為必填項目',
    ProjectPanel_DescriptionLabel: '描述',
    ProjectPanel_DescriptionPlaceholder: '輸入描述',
    ProjectPanel_ProjectColorLabel: '專案顏色',
    ProjectPanel_StatusLabel: '狀態',
    ProjectPanel_StartDateLabel: '開始日期',
    ProjectPanel_DueDateLabel: '到期日',
    ProjectPanel_DueDateError: '到期日必須晚於或等於開始日期',
    ProjectPanel_WhatHappensNextTitle: '接下來呢？',
    ProjectPanel_WhatHappensNextBody: '專案建立完成後，您就可以新增工作、設定階段並追蹤進度。',
    ProjectPanel_SavingLabel: '正在儲存…',
    ProjectPanel_CreatingLabel: '正在建立…',
    ProjectPanel_SaveChangesButton: '儲存變更',
    ProjectPanel_CreateProjectButton: '建立專案',
    ProjectPanel_CancelButton: '取消',
    ProjectPanel_DismissAriaLabel: '關閉',
    ProjectPanel_DiscardUnsavedChangesConfirm: '要捨棄未儲存的變更嗎？',
    ProjectPanel_SaveFallbackError: '無法儲存此專案。',

    // ── Import panel ──
    ImportPanel_SourceExcelTitle: 'Excel / CSV 檔案',
    ImportPanel_SourceExcelSubtitle: '從試算表匯入工作',
    ImportPanel_SourcePlannerTitle: 'Microsoft Planner',
    ImportPanel_SourcePlannerSubtitle: '從 Planner 計劃匯入工作',
    ImportPanel_ClickToBrowse: '按一下以瀏覽',
    ImportPanel_DragDropSuffix: '或拖放檔案',
    ImportPanel_SupportedExtensions: '支援 .xlsx、.xls、.csv',
    ImportPanel_RowsColsSummary: '偵測到 {rows} 列、{cols} 欄',
    ImportPanel_LoadingPlannerPlans: '正在載入 Planner 計劃…',
    ImportPanel_PlannerLoadError: '無法載入 Planner 計劃。',
    ImportPanel_PlannerPermissionsHintPrefix: '請確認您擁有 Planner 的存取權限，且 ',
    ImportPanel_PlannerPermissionsHintEmphasis: 'Tasks by Planner and To Do',
    ImportPanel_PlannerPermissionsHintSuffix: ' 已在此網站中啟用。',
    ImportPanel_NoPlannerPlansFoundTitle: '找不到 Planner 計劃',
    ImportPanel_NoPlannerPlansFoundBody: '您可能沒有任何 Planner 計劃的存取權限，或此帳戶尚無任何計劃。',
    ImportPanel_TaskCountFoundIn: '在「{planName}」中找到 {count} 項工作',
    ImportPanel_ProjectDetailsIntroPrefix: '正在匯入至 ',
    ImportPanel_ProjectDetailsIntroSuffix: '。請檢閱下方的專案詳細資料。',
    ImportPanel_ProjectNameLabel: '專案名稱',
    ImportPanel_DescriptionLabel: '描述',
    ImportPanel_StatusLabel: '狀態',
    ImportPanel_ColorLabel: '顏色',
    ImportPanel_MapIntro: '將檔案中的欄位對應到工作欄位。',
    ImportPanel_CreatingProjectStatus: '正在建立專案…',
    ImportPanel_ImportingTasksStatus: '正在匯入工作…',
    ImportPanel_ProgressLabel: '{done} / {total}',
    ImportPanel_CouldNotCreateProject: '無法建立此專案。',
    ImportPanel_ImportCompletedWithErrors: '匯入已完成，但有 {count} 個錯誤。',
    ImportPanel_ProjectCreatedSuccess: '專案建立成功！',
    ImportPanel_ImportSuccessful: '匯入成功！',
    ImportPanel_TasksAddedTo: '已將 {count} 項工作新增至「{projectName}」',
    ImportPanel_FailedRowsLabel: '失敗的資料列：',
    ImportPanel_CloseButton: '關閉',
    ImportPanel_OpenProjectButton: '開啟專案',
    ImportPanel_ViewImportedTasksButton: '檢視已匯入的工作',
    ImportPanel_NextMapColumnsButton: '下一步：對應欄位',
    ImportPanel_ImportNTasksButton: '匯入 {count} 項工作',
    ImportPanel_BackButton: '上一步',
    ImportPanel_CancelButton: '取消',
    ImportPanel_NextButton: '下一步',
    ImportPanel_StepSource: '來源',
    ImportPanel_StepProject: '專案',
    ImportPanel_StepMap: '對應',
    ImportPanel_StepImport: '匯入',
    ImportPanel_StepDone: '完成',
    ImportPanel_ImportAsNewProjectHeader: '將檔案匯入為新專案',
    ImportPanel_ImportIntoProjectHeader: '將工作匯入至 {projectName}',
    ImportPanel_CouldNotParseFile: '無法剖析此檔案。',
    ImportPanel_CouldNotLoadPlannerTasks: '無法載入此計劃中的工作。',
    ImportPanel_CouldNotCreateProjectDetail: '無法建立專案：{detail}',
    ImportPanel_CouldNotLinkDependencies: '無法連結相依項目：{detail}',
    ImportPanel_UnknownError: '未知錯誤',

    // ── Column mapper (import) ──
    ColumnMapper_TaskNameRequiredBanner: '必須先對應工作名稱才能繼續。',
    ColumnMapper_SkippedColumnsBanner: '將略過 {count} 個欄位。',
    ColumnMapper_SourceColumnHeader: '來源欄位',
    ColumnMapper_TargetFieldHeader: '目標欄位',
    ColumnMapper_StatusHeader: '狀態',
    ColumnMapper_SkippedBadge: '已略過',
    ColumnMapper_AutoMappedBadge: '已自動對應',
    ColumnMapper_SetBadge: '已設定',
    ColumnMapper_PreviewTitle: '預覽：{columnName}',
    ColumnMapper_EmptyCellDash: '—',

    // ── Import field display names / ImportService ──
    ImportField_TaskName: '工作名稱',
    ImportField_StartDate: '開始日期',
    ImportField_DueDate: '到期日',
    ImportField_Status: '狀態',
    ImportField_Priority: '優先順序',
    ImportField_AssignedTo: '負責人',
    ImportField_AssignedToEmail: '負責人電子郵件',
    ImportField_PercentComplete: '完成百分比',
    ImportField_Phase: '階段',
    ImportField_Description: '描述',
    ImportField_Notes: '備註',
    ImportField_IsMilestone: '是否為里程碑',
    ImportField_Dependencies: '相依項目',
    ImportField_SkipColumn: '（略過此欄位）',
    ImportService_EmptyFileError: '此檔案似乎是空的，或不含任何資料列。',
    ImportService_ReadErrorDetail: '無法讀取檔案：{detail}。',
    ImportService_FileReadError: '檔案讀取錯誤。',
    ImportService_RowError: '第 {rowNum} 列（「{title}」）：{error}',
    ImportService_AmbiguousDependency: '相依項目「{name}」符合多個工作標題 — 已略過。',
    ImportService_LinkDependencyError: '無法為工作 {taskId} 連結相依項目：{error}',

    // ── Health labels (shared: healthUtils.ts and ExportService.ts both use this set; also replaces the duplicated Export_PortfolioHealthLabel* keys) ──
    Health_Done: '已完成',
    Health_OnTrack: '進度正常',
    Health_AtRisk: '有風險',
    Health_Overdue: '已逾期',

    // ── Status / Priority display labels (DISPLAY-ONLY — stored SharePoint Choice values remain unchanged/English) ──
    Status_NotStarted: '未開始',
    Status_InProgress: '進行中',
    Status_Completed: '已完成',
    Status_OnHold: '已暫停',
    Status_Cancelled: '已取消',
    Priority_Critical: '緊急',
    Priority_High: '高',
    Priority_Medium: '中',
    Priority_Low: '低',
    ProjectStatus_Planning: '規劃中',
    ProjectStatus_Active: '進行中',
    ProjectStatus_OnHold: '已暫停',
    ProjectStatus_Completed: '已完成',
    ProjectStatus_Cancelled: '已取消',

    // ── Shell (SmartGantt.tsx) ──
    SmartGantt_LoadingProjects: '正在載入專案…',
    SmartGantt_UnableToLoad: '無法載入',
    SmartGantt_RetryButton: '重試',
    SmartGantt_NoProjectsYet: '尚無專案',
    SmartGantt_NoProjectsSubtitle: '建立您的第一個專案以開始使用。',
    SmartGantt_CreateFirstProjectButton: '+ 建立第一個專案',
    SmartGantt_ImportFromExcelButton: '📥 從 Excel 匯入',
    SmartGantt_LoadingTasks: '正在載入工作…',
    SmartGantt_DismissAriaLabel: '關閉',
    SmartGantt_DeleteTaskDialogTitle: '刪除工作',
    SmartGantt_DeleteTaskDialogSubtext: '確定要刪除「{taskTitle}」嗎？此動作無法復原。',
    SmartGantt_DeleteButton: '刪除',
    SmartGantt_CancelButton: '取消',
    SmartGantt_ArchiveProjectDialogTitle: '封存專案',
    SmartGantt_ArchiveProjectDialogSubtext: '要封存「{projectTitle}」嗎？您稍後可以取消封存。',
    SmartGantt_ArchiveButton: '封存',
    SmartGantt_SendToRecycleBinDialogTitle: '傳送至資源回收筒',
    SmartGantt_SendToRecycleBinDialogSubtext: '要將「{projectTitle}」傳送至網站資源回收筒嗎？',
    SmartGantt_SendToRecycleBinButton: '傳送至資源回收筒',
    SmartGantt_FailedLoadProjects: '無法載入專案。請檢查網站權限。',
    SmartGantt_FailedLoadTasks: '無法載入此專案的工作。',
    SmartGantt_FailedLoadPortfolioStats: '無法載入專案組合統計資料。',
    SmartGantt_CouldNotSaveProject: '無法儲存此專案：{message}',
    SmartGantt_CouldNotDeleteProject: '無法刪除此專案：{message}',
    SmartGantt_CouldNotArchiveProject: '無法封存此專案：{message}',
    SmartGantt_CouldNotUnarchiveProject: '無法取消封存此專案：{message}',
    SmartGantt_CouldNotSaveTask: '無法儲存此工作：{message}',
    SmartGantt_CouldNotDeleteTask: '無法刪除此工作：{message}',
    SmartGantt_ImageExportFailed: '圖片匯出失敗：{message}',
    SmartGantt_PowerPointExportFailed: 'PowerPoint 匯出失敗：{message}',
    SmartGantt_PortfolioExportFailed: '專案組合匯出失敗：{message}',
    SmartGantt_CouldNotUpdateTask: '無法更新此工作：{message}',

    // ── Common ──
    ColorSwatch_AutoColorAriaLabel: '自動配色',
    ColorSwatch_CustomColorAriaLabel: '自訂顏色',
    ColorSwatch_PickCustomColorTitle: '挑選自訂顏色',

    // ── Export (Excel / PowerPoint) ──
    Export_ColTaskName: '工作名稱',
    Export_ColPhase: '階段',
    Export_ColStartDate: '開始日期',
    Export_ColDueDate: '到期日',
    Export_ColStatus: '狀態',
    Export_ColPriority: '優先順序',
    Export_ColAssignedTo: '負責人',
    Export_ColAssignedToEmail: '負責人電子郵件',
    Export_ColPercentComplete: '完成百分比',
    Export_ColIsMilestone: '是否為里程碑',
    Export_ColDescription: '描述',
    Export_ColNotes: '備註',
    Export_Yes: '是',
    Export_No: '否',
    Export_SheetNameTasks: '工作',
    Export_ExcelFileSuffix: ' - 工作.xlsx',
    Export_TaskNameColumnLabel: '工作名稱',
    Export_ExportedDateLabel: '匯出日期：{date}',
    Export_ProjectReportLabel: '專案報告',
    Export_StatusLine: '狀態：{status}',
    Export_DateRangeSeparator: ' 至 ',
    Export_ProjectManagerLine: '專案經理：{name}',
    Export_GeneratedDateLine: '產生日期：{date}',
    Export_ProjectSummaryTitle: '專案摘要',
    Export_StatTotalTasks: '工作總數',
    Export_StatCompleted: '已完成',
    Export_StatInProgress: '進行中',
    Export_StatOnHold: '已暫停',
    Export_StatNotStarted: '未開始',
    Export_OverallProgressLine: '整體進度',
    Export_OverallProgressPercent: '{percent}%',
    Export_StatusBreakdownTitle: '狀態分佈',
    Export_StatusBreakdownRow: '{status}：{count}（{percent}%）',
    Export_GanttTimelineTitle: '甘特圖時間軸',
    Export_SummaryRecentActivityTitle: '近期活動',
    Export_ProjectOverviewLabel: '專案概觀',
    Export_DetailStatusLabel: '狀態',
    Export_DetailStartDateLabel: '開始日期',
    Export_DetailDueDateLabel: '到期日',
    Export_DetailProjectManagerLabel: '專案經理',
    Export_Past7DaysLabel: '過去 7 天',
    Export_NoActivityMessage: '尚無近期活動。',
    Export_CompletedThisWeekHeader: '本週已完成 ({count})',
    Export_NewBadge: '新  ',
    Export_CompletedPercentLine: '已完成 {percent}%',
    Export_MoreItemsSuffix: '+ 另有 {count} 項',
    Export_InProgressUpdatedHeader: '進行中／已更新',
    Export_StatusPercentLine: '{status} — {percent}%',
    Export_PortfolioReportLabel: '專案組合報告',
    Export_PortfolioOverviewTitle: '專案組合概觀',
    Export_ProjectsCountLine: '{count} 個專案',
    Export_HealthSummaryOnTrack: '{count} 個進度正常',
    Export_HealthSummaryAtRisk: '{count} 個有風險',
    Export_HealthSummaryOverdue: '{count} 個已逾期',
    Export_ProjectsSummaryHeader: '專案摘要',
    Export_TableProject: '專案',
    Export_TableStatus: '狀態',
    Export_TableHealth: '健康狀態',
    Export_TableTotal: '總計',
    Export_TableDone: '已完成',
    Export_TableActive: '進行中',
    Export_TableAtRisk: '有風險',
    Export_TableOverdue: '已逾期',
    Export_TablePctDone: '完成百分比',
    Export_TableDueDate: '到期日',
    Export_PortfolioSummaryFileName: '專案組合摘要.xlsx',
    Export_PortfolioReportFileName: '專案組合報告.pptx',
    Export_ProjectReportFileName: '{projectName} 報告.pptx',
    Export_UnavailableLabel: '無法使用',
    Export_SheetNamePortfolio: '投資組合',
    Export_ColStart: '開始日期',
    Export_ColDue: '到期日',
    Export_ImageGenerationFailed: '無法產生圖片——圖表可能太大，無法匯出為圖片。',
    Export_DrawingContextFailed: '無法建立匯出用的繪圖環境。',
    Export_SvgRenderFailed: 'SVG 轉譯失敗',
  };
});
